### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión exploratoria con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#10]
Se requiere realizar el 

**Sub Tareas**

- [x] Concertar reunión exploratoria con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buenas tardes,

Se concertó una primera sesión de capacitación y exploración de frente al sistema con la oficina asesora de tecnologías e información grupo de funcionamiento (Cristian Alape y Eduar González) y la oficina de control interno para determinar una base de posibles requerimientos para el desarrollo del sistema Sísifo V 2.0.

**La sesion fue desarrollada:**
Dia: 25 de abril de 2024
Hora: 10:00 am a 12:00 pm
Lugar: Presencial - Sede Paiba

**Link Grabación Reunión:**
https://udistritaleduco-my.sharepoint.com/personal/clalapea_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fclalapea%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FPresencial%20Capacitaci%C3%B3n%20Sisifo%20%2D%20Control%20Interno%2D20240425%5F101202%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E5212dcff%2D4832%2D4e48%2D8bc0%2D1af615a1be0b&ga=1&sw=auth


[Acta Sesion Exploratoria y Capacitacion SISIFO V1.pdf](https://github.com/udistrital/sisifo_documentacion/files/15205278/Acta.Sesion.Exploratoria.y.Capacitacion.SISIFO.V1.pdf)

Saludos,
Carlos Julián González Pérez
Analista de Requerimientos OATI

**Comment by jcmurilloa** [comment]
Hola Carlos Julian, revisando la proyección del acta de hago las siguienets precisiones:

1. En el apartado de participantes, describir los nombres y cargos, y en el campo de las firmas si mencionar el anexo.
2. Se menciona el orden del día con una numeración, sin embargo en el desarrollo del acta solo se enumera el punto 1. Inicio sesión, los demás no se describen 
3. Adjuntar el acta junto con las firmas en la respectiva carpeta del one drive.

Feliz día

**Comment by cjgonzalezp** [comment]
Buenas tardes Julián,

De acuerdo a tus comentarios, realice los cambios solicitados. Te comparto los links de los archivos donde quedan almacenados en OneDrive.

**Link Acta Reunión Exploratoria**
https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EcRMjPR8TMVMt0HwJxHrBZMBn2OxL_VCPN2wE2VotUuabw?e=jd3hLe

**Link Flujograma de proceso en SISIFO V1**
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EbginkkzDbJMiaLHPQ_Gth0BuQM8KCfuA3NbwuXzBBZOJQ?e=zdZa1r


Cordial saludo.
