### ISSUE TITLE
Integración actualización de usuario registrado microservicio histórico y microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#100]
Se requiere realizar la integración del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) con el microcliente de [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf), similar a lo trabajado en el registro en la Issue #99 se requiere permitir la actualización de un usuario registrado. Tener presente que:
- Al finalizar el periodo de ese usuario con ese rol se debe marcar como finalizado en true (por lo que es necesario el estado asociarlo a este campo).
- Al finalizar el periodo, es necesario en WSO2 remover el rol del usuario.

**Sub Tareas**

- [ ] Implementación de la integración con el microservicio histórico usuarios roles para la correcta actualización de un usuario, tener presente que se adicionó un nuevo campo _finalizado_ el cual al momento de finalizar el rol debe ser enviado como true.
- [ ] Implementación con WSO2 para remover roles a un usuario en WSO2.
- [ ] Pruebas funcionales de la actualización de un usuario en el microservicio histórico usuarios.
- [ ] Pruebas funcionales donde se observe que se removió correctamente el rol al usuario en WSO2.

**Escenarios de pruebas**
- [ ] Actualización de un usuario en histórico usuarios roles finalizando el periodo y validando el cambio de estado.
- [ ] Validación de la correcta eliminación del rol al usuario existente en WSO2.

**Criterios de aceptación**

- [ ] Documentación de las pruebas realizadas con la integración en la edición de un nuevo usuario. 

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se comienza con la implementación de búsqueda de información del usuario para la sección de actualización, tomando como base lo trabajado en la integración de WSO2 y terceros para la creación del usuario.

![Captura de pantalla 2024-07-24 a la(s) 9 39 27 p  m](https://github.com/user-attachments/assets/90a868c1-48d9-4d67-9478-7bfaf7bd809b)

![Captura de pantalla 2024-07-24 a la(s) 9 40 35 p  m](https://github.com/user-attachments/assets/6b34f57e-9717-4ad8-9eb3-81b69c3d455e)

Se debe confirmar el flujo de la búsqueda para la sección de actualización de usuario

**Comment by alexhrr** [comment]
Según lo informado en la reunion del dia de hoy, para iniciar con la integración de histórico_usuarios_roles se deben realizar algunos cambios en la interfaz del cliente de actualizar usuario, los inputs de documento y correo no son campos para buscar al usuario por lo tanto se retiran los botones de búsqueda, el campo del rol no es un selector por lo tanto se cambia a un input, el estado se deja por el momento como selector pero solo con el campo de "finalizado" y finalmente el campo de Fecha inicio se deja solo de lectura para que no pueda ser modificado. La interfaz queda de la siguiente forma:

![Captura de pantalla 2024-07-25 a la(s) 9 49 50 p  m](https://github.com/user-attachments/assets/30064439-a282-4348-8d1b-8d747be5c660)

**Comment by alexhrr** [comment]
Se realiza la búsqueda del usuario por su documento de identidad para traer la información del usuario haciendo la consulta en WSO2 y Terceros:

![Captura de pantalla 2024-07-26 a la(s) 6 29 54 p  m](https://github.com/user-attachments/assets/1d3f881d-95ae-46f0-80d8-ceb2d6ea728d)

Posteriormente se intenta realizar la integración de histórico_usuarios_roles para traer la información del rol asignado al usuario, sin embargo se debe desarrollar en endpoint para realizar la consulta por el id del usuario y facilitar su búsqueda, por lo tanto no se puede continuar con su desarrollo

![Captura de pantalla 2024-07-26 a la(s) 6 36 54 p  m](https://github.com/user-attachments/assets/0d194fc1-ab49-4d49-8dbc-91162ce5155a)

Finalmente para la integración de adición y eliminación de roles con WSO2 se encuentra el siguiente error al momento de agregar/eliminar roles, lo que impide continuar con la integración:

![image](https://github.com/user-attachments/assets/95b42c01-9c54-4f3b-a847-2a7554dd33b3)
