### ISSUE TITLE
Registro parámetros de plantillas de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#101]
Se requiere realizar el registro de los tipos de modal_alerta descritos en el modelo de datos en la Issue #90, adicional el registro de parámetros requeridos para elementos HTML tipo y tipo de dato (ver ejemplo en la Issue #82).

**Sub Tareas**

- [x] Revisión modelo de datos de [parametros_crud](https://github.com/udistrital/parametros_crud) para organizar los datos que se requieren crear teniendo presente los parámetros que tienen agrupación.
- [x] Revisión de registro de los parámetros requeridos usando el API [API de parametros_crud](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Parametros&version=v1&provider=admin&tenant=carbon.super)
- [x] Registro tipo de modal de alerta.
- [x] Registro tipo de elemento input -> texto e input -> numero. Y tipo select.

**Criterios de aceptación**

- [x] Cumplir con las subtareas y la correspondiente evidencia de los registros realizados.

**Requerimientos**

No aplica

**Material de apoyo**
- [API de parametros_crud](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Parametros&version=v1&provider=admin&tenant=carbon.super)
- Repositorio [parametros_crud](https://github.com/udistrital/parametros_crud)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
![image](https://github.com/user-attachments/assets/d0d1add4-b5fc-4de3-a5ef-cf4d5df987ed)
{
    "Data": {
        "Id": 27,
        "Nombre": "Plantilla formulario dinámico",
        "Descripcion": "Almacenamiento de parametros necesarios para las plantillas de formularios dinamicos.",
        "CodigoAbreviacion": "PFD",
        "Activo": false,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T14:20:41.713969145-05:00",
        "FechaModificacion": "2024-07-23T14:20:41.718310921-05:00"
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

**Comment by jucastro94** [comment]
![image](https://github.com/user-attachments/assets/2ee962ee-f790-4fe0-9348-80f5487e9817)
{
    "Data": {
        "Id": 128,
        "Nombre": "Modal alerta",
        "Descripcion": "tipos de modales de alertas",
        "CodigoAbreviacion": "MA",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T14:46:57.359906353-05:00",
        "FechaModificacion": "2024-07-23T14:46:57.360593743-05:00",
        "AreaTipoId": {
            "Id": 27,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": ""
        }
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

**Comment by jucastro94** [comment]
![image](https://github.com/user-attachments/assets/3602c65f-d09d-4d38-b7fb-cfdada598eee)


{
    "Data": {
        "Id": 129,
        "Nombre": "Elementos HTML",
        "Descripcion": "tipos de elementos html para formularios dinámicos",
        "CodigoAbreviacion": "E_HTML",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T14:55:40.604212636-05:00",
        "FechaModificacion": "2024-07-23T14:55:40.604297004-05:00",
        "AreaTipoId": {
            "Id": 27,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": ""
        }
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

**Comment by jucastro94** [comment]
registro tipo de  de modales:  error, almacenado , validación

![image](https://github.com/user-attachments/assets/b677233a-bf92-4d25-91c2-447dc926728a)
{
    "Data": {
        "Id": 6694,
        "Nombre": "Error",
        "Descripcion": "tipo modal error",
        "CodigoAbreviacion": "Error",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T15:11:19.198315112-05:00",
        "FechaModificacion": "2024-07-23T15:11:19.19841412-05:00",
        "TipoParametroId": {
            "Id": 128,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": null
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}
-------------------------------------------------------
![image](https://github.com/user-attachments/assets/66a47fc0-2590-4916-9dc6-f5ae6cd9d7d1)
{
    "Data": {
        "Id": 6695,
        "Nombre": "Almacenado",
        "Descripcion": "modal tipo almacenado",
        "CodigoAbreviacion": "Almacenado",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T15:13:09.901355092-05:00",
        "FechaModificacion": "2024-07-23T15:13:09.901461103-05:00",
        "TipoParametroId": {
            "Id": 128,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": null
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}
-------------------------------------------------------
![image](https://github.com/user-attachments/assets/e32798f2-2c24-401c-ba70-d7f5fd51dc15)

{
    "Data": {
        "Id": 6696,
        "Nombre": "Validación",
        "Descripcion": "modal tipo validación",
        "CodigoAbreviacion": "validación",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T15:14:10.874120606-05:00",
        "FechaModificacion": "2024-07-23T15:14:10.874230829-05:00",
        "TipoParametroId": {
            "Id": 128,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": null
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

**Comment by jucastro94** [comment]
registro de input como elemento padre 
![image](https://github.com/user-attachments/assets/4edbbc4b-ea6c-4a45-99ad-548ff2fce2c5)
{
    "Data": {
        "Id": 6697,
        "Nombre": "Input",
        "Descripcion": "elemento padre input",
        "CodigoAbreviacion": "input",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T16:12:40.687968051-05:00",
        "FechaModificacion": "2024-07-23T16:12:40.688071013-05:00",
        "TipoParametroId": {
            "Id": 129,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": null
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

---

registro select
![image](https://github.com/user-attachments/assets/8fbee16d-fb00-4190-af12-7105f57a2672)
{
    "Data": {
        "Id": 6698,
        "Nombre": "Select",
        "Descripcion": "elemento padre select",
        "CodigoAbreviacion": "select",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T16:14:39.563027662-05:00",
        "FechaModificacion": "2024-07-23T16:14:39.563139467-05:00",
        "TipoParametroId": {
            "Id": 129,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": null
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

**Comment by jucastro94** [comment]
resgistro de parametro 'Text' como hijo de input
![image](https://github.com/user-attachments/assets/159388b5-b7a0-403c-ac48-ca7af7483620)
{
    "Data": {
        "Id": 6699,
        "Nombre": "Text",
        "Descripcion": "elemento Hijo de input, texto",
        "CodigoAbreviacion": "texto",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T16:19:19.598740817-05:00",
        "FechaModificacion": "2024-07-23T16:19:19.598825004-05:00",
        "TipoParametroId": {
            "Id": 129,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": {
            "Id": 6697,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "TipoParametroId": null,
            "ParametroPadreId": null
        }
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

---

registro de parametro 'Number' como hijo de input
![image](https://github.com/user-attachments/assets/c836e65f-4bfc-4ae2-808f-d602cc5be570)
{
    "Data": {
        "Id": 6700,
        "Nombre": "Number",
        "Descripcion": "elemento Hijo de input, numero",
        "CodigoAbreviacion": "numero",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-23T16:20:37.303039532-05:00",
        "FechaModificacion": "2024-07-23T16:20:37.303150169-05:00",
        "TipoParametroId": {
            "Id": 129,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "AreaTipoId": null
        },
        "ParametroPadreId": {
            "Id": 6697,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": "",
            "TipoParametroId": null,
            "ParametroPadreId": null
        }
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}

**Comment by jucastro94** [comment]
se realiza activacion para el planilla formulario dinamico, area_tipo id: 27
![image](https://github.com/user-attachments/assets/37f1d569-5c87-4fcf-9532-37282fdca5e9)

**Comment by edwargl7** [comment]
Se realiza la revisión, pendiente ajustar el tipo de parámetro de los tipo de datos. Actualmente hacen parte del mismo tipo.

**Comment by jucastro94** [comment]
se crea tipo de dato faltante


![Image](https://github.com/user-attachments/assets/0509e502-14a3-482b-9666-37f05e40b92d)
{
    "Data": {
        "Id": 130,
        "Nombre": "Tipo de dato elemento",
        "Descripcion": "tipos de datos para los elementos html en formularios dinámicos",
        "CodigoAbreviacion": "tipo dato",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2024-07-29T15:39:35.291670384-05:00",
        "FechaModificacion": "2024-07-29T15:39:35.294088866-05:00",
        "AreaTipoId": {
            "Id": 27,
            "Nombre": "",
            "Descripcion": "",
            "CodigoAbreviacion": "",
            "Activo": false,
            "NumeroOrden": 0,
            "FechaCreacion": "",
            "FechaModificacion": ""
        }
    },
    "Message": "Registration successful",
    "Status": "201",
    "Success": true
}
