### ISSUE TITLE
Investigación pruebas unitarias en el microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#103]
Se requiere realizar la investigación de la aplicación de pruebas en el microcliente usando Jazmin y karma, dado que ya se cuenta con el microcliente de gestión usuarios con la integración requerida de los microservicios de WSO2, Terceros e Histórico usuarios roles, se inicia la revisión de pruebas unitarias.

**Sub Tareas**

- [x] Investigación Jazmin y karma para pruebas en el microcliente.
- [x] Documentación de ejemplos de aplicación de pruebas.

**Criterios de aceptación**

- [x] Documentación de la Issue con la revisión realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### investigación pruebas unitarias

Se continua con la investigación de pruebas usando Jasmine y Karma, se va a realizar la ejecución de un ejemplo tomado de internet que consiste en un formulario básico que contiene validadores y las pruebas evalúan el correcto funcionamiento del mismo de acuerdo a los requerimientos.

Se debe crear manualmente el archivo Karma.conf.js en la raiz del proyecto para poder ejecutar las pruebas, el contenido del archivo se establece por defecto y se puede sacar de internet:

![Captura de pantalla 2024-07-26 a la(s) 9 13 42 p  m](https://github.com/user-attachments/assets/6e19e9e7-aa6e-41e2-9925-f0afc2d9dfd5)

Este es el contenido del archivo Karma.conf.js:

![Captura de pantalla 2024-07-26 a la(s) 9 15 20 p  m](https://github.com/user-attachments/assets/447ac1ae-cb58-4959-9df8-f7fb678538e1)

La descripción de las pruebas se definen en el archivo que se genera automaticamente .spec.ts para los componentes:

![Captura de pantalla 2024-07-26 a la(s) 9 11 33 p  m](https://github.com/user-attachments/assets/ea6a1838-50d6-460b-a5fd-5127d8564401)

Aqui hay una muestra de las pruebas creadas para el ejemplo donde se verifican los datos ingresados en el formulario y que cumplan lo establecido:

![Captura de pantalla 2024-07-26 a la(s) 9 13 12 p  m](https://github.com/user-attachments/assets/3e28fd4c-e55f-42dd-947b-383f3b00c4c8)

Posteriormente se ejecutan las pruebas con: 

```
ng test
``` 

Finalmente se debe abrir el navegador automaticamente (en mi caso no es asi y lo abro con el link que sale en la consola) y en el navegador podemos ver la siguiente ventana:

![Captura de pantalla 2024-07-26 a la(s) 9 23 26 p  m](https://github.com/user-attachments/assets/bca40d68-103e-4243-bc73-df19c96ad874)

Al dar click en DEBUG podemos ver el resultado de la ejecución de las pruebas:
 
![Captura de pantalla 2024-07-26 a la(s) 9 24 12 p  m](https://github.com/user-attachments/assets/f0e70547-7401-45d9-a471-38a3610dbaad)

Si se presenta un fallo con alguna prueba se puede observar en la misma ventana del navegador.

**Comment by edwargl7** [comment]
Buen ejercicio realizado, se realizará posteriormente una implementación de las pruebas una vez finalizado el desarrollo del microcliente de gestión de usuarios.
