### ISSUE TITLE
Diseñar el mockup para el submódulo Programa de Trabajo Parte 2

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#104]
Se requiere continuar con el diseño del mockup para el submódulo Programa de Trabajo

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día

Se avanza en el desarrollo de los submódulos asignación de actividades, auditorías internas, seguimiento e informes que componían inicialmente el submódulo programa de trabajo el cual por solicitud del cliente se procede a dividir.

**Enlace diseños cargados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjqvehKllh1HvsFMvm98g8kBxZUNs7zMKPEunCyA67Klpg?e=UjWOp6


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presentan diseños de los módulos asignación de auditorías, auditorías internas, seguimiento e informes al cliente, se realizan ajustes según requerimiento del cliente, se finaliza la segunda parte de los módulos mencionados y se recibe aprobación por parte del cliente para el desarrollo en el sistema SISIFO V2.

**Enlace diseños ajustados y cargados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjqvehKllh1HvsFMvm98g8kBxZUNs7zMKPEunCyA67Klpg?e=Ae6aoz

**Acta de Reunión No 094/2024 Aprobación mockups** 
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtbX_J1YhdpMpk_CNXiUJN4Bk288UDM-lkHCMalOOx-LUw?e=cwcFIz


Saludos.

**Comment by jcmurilloa** [comment]
Gracias @cjgonzalezp, repasaremos los respectivos mockups aprobados por el cliente en la próxima review SoS!

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp, pendiente generar las modificaciones pertinentes en el mockup relacionado con auditoria interna.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes revisados con el equipo SoS del mockup del módulo auditorías internas.

**Diseño Mockup Módulo Auditorías Internas**
![Image](https://github.com/user-attachments/assets/597abc42-23b4-4c33-a1df-b946d792db6f)


Saludos.
