### ISSUE TITLE
Ajuste campo de fecha inicio y fin de la tabla periodo_rol_usuario

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#106]
Se requiere realizar el ajuste al microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) cambiando el tipo de dato de los campos _fecha_inicio_ y _fecha_fin_ de timestamp a date, dado que solo es requerido para estos campos almacenar el día, mes y año.

**Sub Tareas**

- [x] Creación de migración para cambiar el tipo de dato de los campos _fecha_inicio_ y _fecha_fin_.
- [x] Modificación del modelo, servicio y controlador para almacenar las fechas con solo día, mes y año.

**Escenarios de pruebas**
- [x] Prueba de funcionamiento correcto al registrar fecha de inicio y fin con día, mes y año.

**Criterios de aceptación**

- [x] Implementación realizada y pruebas documentadas en la Issue.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se crea y ejecuta migracion para modificar campo en base de datos


![Image](https://github.com/user-attachments/assets/8633b052-d3d3-4fbf-80ce-2e6d9d545f68)


![Image](https://github.com/user-attachments/assets/c668087f-a30a-4732-a786-ef803001c337)



![Image](https://github.com/user-attachments/assets/fb6577bd-081c-44ae-91b7-91925a446f2a)

**Comment by jucastro94** [comment]
se modifica modelo


![Image](https://github.com/user-attachments/assets/fc694a33-b552-4898-aed1-1e81185059a4)


se modifica service


![Image](https://github.com/user-attachments/assets/6914f335-73a5-4d6c-ac4a-45a1f85b750f)

se modifican test


![Image](https://github.com/user-attachments/assets/1620421e-1e02-4d9c-a91b-c390e93612cb)



![Image](https://github.com/user-attachments/assets/13311f5d-5887-4432-9e05-48da35f7c7ad)

**Comment by jucastro94** [comment]
se ejecutan validaciones
se ejecuta POST y PUT correctamente


![Image](https://github.com/user-attachments/assets/518380b9-28cc-47f4-93dd-6ca83ad91507)

se detecta error al momento de realizar peticiones get

por id, devuelve los valores como si siguera el tipo de dato en timestamp
![Image](https://github.com/user-attachments/assets/336c34fe-41ef-458a-b941-fb85471974f5)

por GETALL, no trae los registros luego del cambio de tipo de dato

**Comment by jucastro94** [comment]
se detecta que el formato de fechas inicio y fin se registran correctamente pero a la hora de consultarlas cambia de formato, se crea metodo en modelo para dar formato a las fecha de inicio y fin para los metodos getOne y getAll


![Image](https://github.com/user-attachments/assets/facb08ef-b6a3-45e4-bf65-c212e68023a6)

se valida la correcta ejecucion

![Image](https://github.com/user-attachments/assets/ff78df42-b440-4136-a353-41dd2e05a452)


se modifica limite de registro consultados para el retorno de la peticion y asi validar que esten trayendo todos los registros, la validacion es satisfactoria

**Comment by edwargl7** [comment]
Se realiza el PR, buen trabajo, pendiente revisar función comentada en el servicio de periodo rol.
![image](https://github.com/user-attachments/assets/b6d096ab-1661-4b0a-85b3-51159edb2adf)
