### ISSUE TITLE
Pruebas de integración microservicio plantillas de formularios dinámicos - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#107]
Se requiere realizar la implementación de pruebas unitarias y de integración al microservicio de [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud).

**Sub Tareas**

- [x] Investigación pruebas para crear mock de conexión a base de datos.
- [x] Implementar pruebas de integración endpoint Health Check.
- [x] Implementación base de pruebas con mock a la base de datos.
- [x] Resultado del coverage de las pruebas implementadas.
- [x] Actualización del README agregando la sección de _Ejecución de pruebas_.

**Escenarios de pruebas**
- [x] Prueba Health Check.
- [x] Prueba funcional de la implementación base de mock a la base de datos.

**Criterios de aceptación**

- [x] Escenarios mínimo de pruebas cubierto, se pueden agregar pruebas unitarias adicionales que sean identificadas en los recursos módulo, formularios y elementos HTML.

**Requerimientos**

- No aplica.

**Material de apoyo**
- Pruebas implementadas en un microservicio mid de ARGO [proveedores_mid](https://github.com/udistrital/proveedores_mid), Issue asociada [Pruebas de integración microservicio MID de Ágora - Proveedores](https://github.com/udistrital/argo_documentacion/issues/79).

**Especificaciones técnicas**

1. Repositorio microservicio crud [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Investigación y Análisis para Crear Mocks de Conexión a Base de Datos

Se comenzo con la investigación de las pruebas necesarias para crear mocks de conexión a base de datos utilizando Jest.

1. Se realizó un análisis del código existente en `proveedores_mid` para entender el uso de moks y el desarrollo de las pruebas unitarias.

2. Se revisó la documentación de Jest, enfocándose en las funcionalidades que permiten crear mocks, realizar aserciones y ejecutar pruebas unitarias:
     - **Mocks:** Cómo simular módulos y funciones para aislar las pruebas.
     - **Aserciones:** Verificación de resultados esperados en las pruebas.
     - **Pruebas Unitarias:** Creación de pruebas unitarias efectivas.

[Documentación de Jest](https://jestjs.io/docs/getting-started)

**Comment by CristianCGutierrezG** [comment]
## Pruebas de integración

**Creación de Pruebas Unitarias para la Colección `modulos`:**
Se desarrollaron pruebas unitarias específicas para la colección `modulos` para el service y el contoller, especificando pruebas satisfactorias y de error para cada función.  

**Service**
![image](https://github.com/user-attachments/assets/5053408d-5fc2-470e-818f-52fee9a0fa7d)

**Controller**
![image](https://github.com/user-attachments/assets/e5a1b463-daf5-44dc-b650-ae88979983bd)

### Modificación en la Estructura de los Controllers:
Se realizaron cambios en la estructura de manejo de los controllers para solucionar problemas detectados en la ejecución de las pruebas. Se añadieron bloques `try` y `catch` para mejorar la gestión de errores y el reconocimiento de las pruebas.

![image](https://github.com/user-attachments/assets/329b62fc-b3a5-4d60-bcb1-7f5cbe98ab2d)

### Prueba de Integración del Endpoint de Módulos:
Se ejecutó una prueba de integración para evaluar el comportamiento del endpoint de módulos, verificando su funcionamiento en un entorno más cercano al real.

![image](https://github.com/user-attachments/assets/2bc1a517-fde0-4084-bdf7-2e70b1da71f7)

![image](https://github.com/user-attachments/assets/cc04cd80-3304-44f7-b5cc-e6365d53f188)

### Observaciones
**Problemas con el Coverage:**
Se encontro un inconveniente con el reporte de cobertura (`coverage`), ya que no se está reconociendo que el `modulo.service` pasa todas las pruebas.

![image](https://github.com/user-attachments/assets/8bdf6260-6b56-4bba-b037-98116d03e3b7)

Se adjunta evidencia de que las pruebas en el `.service` se ejecutan correctamente, confirmando que los cambios realizados están funcionando según lo esperado.

![image](https://github.com/user-attachments/assets/979256ab-00f9-4040-9747-60cab9277cef)

**Comment by edwargl7** [comment]
Muy buen trabajo, avance bien documentado. Se resuelve el PR sin conflictos.
