### ISSUE TITLE
Implementación endpoint de consulta de periodos por documento del usuario

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#108]
Se requiere realizar la implementación de un nuevo endpoint que permita consultar los periodos asociados a un usuario consultando por documento de identidad y permitiendo agregar los query params para filtrar la consulta por activos, sistema al que pertenece y también que cuente con paginado y ordenar de resultados.

**Sub Tareas**

- [x] Implementación del nuevo endpoint _usuarios/{documento}/periodos_.
- [x] Implementación de query params como los implementados en los Get All, que permitan filtrar la consulta por activos, sistema al que pertenece y también que cuente con paginado y ordenar de resultados.
- [x] Pruebas funcionales del nuevo endpoint.

**Escenarios de pruebas**
- [x] Prueba funcional consultando los periodos de un usuario sin filtro.
- [x] Prueba funcional consultando los periodos de un usuario filtrando activos.
- [x] Prueba funcional consultando los periodos de un usuario filtrando inactivos.
- [x] Prueba funcional consultando los periodos de un usuario con paginado.

**Criterios de aceptación**

- [ ] Documentación de resultados de las pruebas funcionales, se detalla el mínimo de pruebas que se deben presentar, se pueden agregar adicionales según sea el caso.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se crea nuevo endpoint para traer periododos por documento ya funcional, se comienza a trabajar la integracion de query params
 se agrega elemento a router


![Image](https://github.com/user-attachments/assets/f256d0e4-f5a1-48fb-8be0-7635d29328bf)

se agrega controlador 


![Image](https://github.com/user-attachments/assets/1c551320-b1e9-4329-bc76-a56df3f6e17f)



![Image](https://github.com/user-attachments/assets/17b7d486-2e58-4b3d-9957-ddcb87b1f04b)

se agrega servicio


![Image](https://github.com/user-attachments/assets/a6c70569-006b-4ef3-aef3-3d6009fae900)



se agrega  metodos en modelos de usuairo y periodos_rol_usuario


![Image](https://github.com/user-attachments/assets/6efe4c25-a2ed-40ab-bbf7-9d0dca56393f)


![Image](https://github.com/user-attachments/assets/9b63118a-8149-41f1-9ed3-b0eefe50dd29)


se actualiza swagger



![Image](https://github.com/user-attachments/assets/f3a43d85-9602-49d4-b4f6-f2e0957e9556)

se realiza prueba funcional



![Image](https://github.com/user-attachments/assets/4a36e5be-523f-4008-961a-a5dfc612b7d0)

{
    "Data": [
        {
            "Id": 25,
            "Activo": true,
            "FechaCreacion": "2024-07-29 18:42:47.180237 +0000 +0000",
            "FechaModificacion": "2024-07-29 18:42:47.183584 +0000 +0000",
            "FechaInicio": "2026-07-26 00:00:00 +0000 +0000",
            "FechaFin": "2028-07-26 00:00:00 +0000 +0000",
            "Finalizado": true,
            "UsuarioId": {
                "Id": 2,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Documento": ""
            },
            "RolId": {
                "Id": 1,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Nombre": "",
                "SistemaInformacionId": null
            }
        },
        {
            "Id": 29,
            "Activo": true,
            "FechaCreacion": "2024-07-30 17:49:59.615655 +0000 +0000",
            "FechaModificacion": "2024-07-30 17:49:59.913757 +0000 +0000",
            "FechaInicio": "2020-07-26 00:00:00 +0000 +0000",
            "FechaFin": "2023-12-26 00:00:00 +0000 +0000",
            "Finalizado": true,
            "UsuarioId": {
                "Id": 2,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Documento": ""
            },
            "RolId": {
                "Id": 2,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Nombre": "",
                "SistemaInformacionId": null
            }
        },
        {
            "Id": 30,
            "Activo": true,
            "FechaCreacion": "2024-07-30 17:50:26.354486 +0000 +0000",
            "FechaModificacion": "2024-07-30 17:50:26.375921 +0000 +0000",
            "FechaInicio": "2013-07-26 00:00:00 +0000 +0000",
            "FechaFin": "2022-01-26 00:00:00 +0000 +0000",
            "Finalizado": true,
            "UsuarioId": {
                "Id": 2,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Documento": ""
            },
            "RolId": {
                "Id": 3,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Nombre": "",
                "SistemaInformacionId": null
            }
        },
        {
            "Id": 31,
            "Activo": true,
            "FechaCreacion": "2024-07-30 17:51:16.640822 +0000 +0000",
            "FechaModificacion": "2024-07-30 17:51:16.643983 +0000 +0000",
            "FechaInicio": "2018-02-06 00:00:00 +0000 +0000",
            "FechaFin": "2024-01-23 00:00:00 +0000 +0000",
            "Finalizado": false,
            "UsuarioId": {
                "Id": 2,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Documento": ""
            },
            "RolId": {
                "Id": 4,
                "Activo": false,
                "FechaCreacion": "",
                "FechaModificacion": "",
                "Nombre": "",
                "SistemaInformacionId": null
            }
        }
    ],
    "Message": "Petición exitosa",
    "Status": 200,
    "Success": true
}

**Comment by jucastro94** [comment]
se corrige respuesta de endpoint para que contenga la informacion del usuario y el rol 


![Image](https://github.com/user-attachments/assets/ff329cbb-c69b-4349-a058-8b579f3d5ca4)

**Comment by jucastro94** [comment]
se implementa query params query, fields, sortby, order, limit, offset y se ajusta documentacion swagger 

![Image](https://github.com/user-attachments/assets/9e0d8cf7-bf50-4aa5-a2d7-9b9dc273ba34)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales a query params

**Fields** y **limit**

![Image](https://github.com/user-attachments/assets/1b67dc27-9223-4d60-8bde-8c310918929a)

**offset**

![Image](https://github.com/user-attachments/assets/309b2f97-8de2-4582-bc7e-b6f334ff2e3f)

**query**
![Image](https://github.com/user-attachments/assets/b89b706d-03e7-403e-9b1a-dd829a5f4843)


**sortby** y **order**
![Image](https://github.com/user-attachments/assets/aefa53df-a4f4-40d8-b70a-c6150572371d)


![Image](https://github.com/user-attachments/assets/08841506-19a1-4fa8-99a2-7c5036bdac36)

**Comment by jucastro94** [comment]
prueba funcional de activos


![Image](https://github.com/user-attachments/assets/575f71dc-e8ce-4856-84c7-79e31272a194)

prueba funcional de inactivos


![Image](https://github.com/user-attachments/assets/457cdf14-b1fe-44ae-9d73-60c65ddad16c)

**Comment by edwargl7** [comment]
Muy buen trabajo y buena documentación de las pruebas funcionales realizadas. Se resuelve el PR.
