### ISSUE TITLE
Pruebas endpoints del microservicio de Historico Usuarios Roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#109]
Se requiere realizar la validación del uso de los query params de los endpoints GetAll del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) y realizar los ajustes necesarios para el correcto funcionamiento. 
![image](https://github.com/user-attachments/assets/0ee589e9-48a9-4896-801f-58e189ab9608)

**Subtareas**

- [x] Pruebas del correcto funcionamiento de los query params del endpoint sistema información.
- [x] Pruebas del correcto funcionamiento de los query params del endpoint usuarios.
- [x] Pruebas del correcto funcionamiento de los query params del endpoint roles.
- [x] Pruebas del correcto funcionamiento de los query params del endpoint periodos.

**Escenarios de pruebas**
- [x] Prueba usando el parámetro query.
- [x] Prueba usando el parámetro fields.
- [x] Prueba usando el parámetro sortby.
- [x] Prueba usando el parámetro order.
- [x] Prueba de paginado usando el parámetro limit y offset.

**Criterios de aceptación**

- [x] Documentación de las pruebas funcionales que cubran el correcto funcionamiento de los query params del microservicio.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
prueba de funcionamiento **fields**

usuario:


![Image](https://github.com/user-attachments/assets/b7c91835-f9ec-4c11-b61f-f423261704a6)

Roles


![Image](https://github.com/user-attachments/assets/b007f70d-f23e-4c4c-9593-0594697c1e38)

sistemas de informacion


![Image](https://github.com/user-attachments/assets/b0b46688-a244-4555-811e-3788716549d5)

periodos rol usuario

![Image](https://github.com/user-attachments/assets/63f59847-a857-41ec-87c4-08a13896c3c2)

**Comment by jucastro94** [comment]
pruebas de funcionamiento **query**

usuarios


![Image](https://github.com/user-attachments/assets/6296a993-cf89-42b7-bebd-4b5d95e689b5)


roles


![Image](https://github.com/user-attachments/assets/27bfadee-3764-4b41-9ead-104a073e9158)


sistema de informacion


![Image](https://github.com/user-attachments/assets/2555d140-3590-46b6-9ec4-147713a4e32e)


periodos rol usuairo


![Image](https://github.com/user-attachments/assets/ad62a5e6-d5f9-4ccf-9485-06610e8b518c)

**Comment by jucastro94** [comment]
pruebas funcionales **limit y offset**
usuarios


![Image](https://github.com/user-attachments/assets/0224c913-48b6-4ec1-af42-87abff727291)

![Image](https://github.com/user-attachments/assets/a02501d9-172a-4c56-a652-18cad99622c9)

![Image](https://github.com/user-attachments/assets/74f4ab3b-373a-4f07-82a8-38e5c354b097)


roles


![Image](https://github.com/user-attachments/assets/ebdbc140-df8b-4c04-b4d5-e65be836a203)
![Image](https://github.com/user-attachments/assets/e3df4bda-7b43-491f-a23d-e572c506fab6)

![Image](https://github.com/user-attachments/assets/84d8b911-16dd-4ce2-921f-b260c2130801)

sistemas de informacion


![Image](https://github.com/user-attachments/assets/f1027892-813d-4316-8d5d-838f718f79c1)


![Image](https://github.com/user-attachments/assets/94f82b6c-7ecf-402a-935e-a60316e6c441)


![Image](https://github.com/user-attachments/assets/3367d5e0-243b-426c-adcb-778ae59e49bc)





periodos rol usuario

![Image](https://github.com/user-attachments/assets/a11fb727-1d18-4337-b6cc-9fb636d37df6)

![Image](https://github.com/user-attachments/assets/d831c639-58ba-4916-9ad0-1229db5b9876)

![Image](https://github.com/user-attachments/assets/3f3f0523-b97e-43b1-9962-74b8b4ea12e7)

**Comment by jucastro94** [comment]
prueba de funcionameinto **sortby y order**

usuarios

![Image](https://github.com/user-attachments/assets/6dc09a0b-de22-4bb5-9634-e3da9f6150d4)


![Image](https://github.com/user-attachments/assets/201c813d-5789-4fd2-a9d3-5f67adb3957a)



roles


![Image](https://github.com/user-attachments/assets/887c2bff-bbd7-4843-b92e-efef05df0236)

![Image](https://github.com/user-attachments/assets/598c0f5b-4255-4a68-a891-0e59069c0e14)



periodo ro usuario


![Image](https://github.com/user-attachments/assets/b9dc4280-b020-4164-8dc8-968c54201240)


![Image](https://github.com/user-attachments/assets/a9a276f0-d2b3-4d6f-adc1-5653a7e94827)



sistemas de informacion


![Image](https://github.com/user-attachments/assets/d6ee45a7-d685-44f2-975f-bd2724bf68d5)


![Image](https://github.com/user-attachments/assets/000441e7-6f3d-45db-a521-ed2f2379dd76)

**Comment by jucastro94** [comment]
a peticion se realiza filtrado de usuarios por nuemero de documento 




![Image](https://github.com/user-attachments/assets/1c852b3c-4cf8-4cad-be7c-2d0df8895d50)

**Comment by edwargl7** [comment]
Muy buenas pruebas para complementar toda la funcionalidad del microservicio.
