### ISSUE TITLE
Construir diagrama de flujo según requerimientos del cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#11]
Se requiere realizar el 

**Sub Tareas**

- [x] Repasar diagrama de flujo actual del sistema
- [x] Generar las modificaciones según requerimientos del cliente

**Criterios de aceptación**

- [x] Diagrama de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buenas tardes,

Se desarrolla un diagrama de flujo inicial de los procesos que se realizan y módulos establecidos actualmente dentro del sistema Sísifo V1. Adicionalmente, los roles de usuarios con sus respectivas funciones y accesos.

**Flujo de Proceso**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/db6a740c-eb08-44c6-a7b6-1bc06ae8f3e7)

**Roles, Funciones y Permisos de los diferentes usuarios**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/a2260120-da59-44ee-b967-b304ad4b49f1)

**Flujo de Módulos Actuales**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/0a2d526b-7a38-496b-bea5-22772afc8712)


Saludos,
Carlos Julián González Pérez
Analista de Requerimientos OATI

**Comment by jcmurilloa** [comment]
El diagrama de flujo cumple con lo solicitado, por favor adjuntar la documentación a la carpeta de Analista en el proyecto de One Drive

**Comment by cjgonzalezp** [comment]
Buenas tardes Julián,

De acuerdo a tus comentarios, el archivo fue guardado en la carpeta del proyecto en OneDrive 

Link Flujograma del proceso SISIFO V1
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EbginkkzDbJMiaLHPQ_Gth0BuQM8KCfuA3NbwuXzBBZOJQ?e=dZca1t


Saludos.

**Comment by jcmurilloa** [comment]
El flujograma, en líneas generales describe el flujo del proceso, y este se documenta de manera adecuada, gran trabajo!
