### ISSUE TITLE
Integración microservicio de histórico usuarios y microcliente de gestión de usuarios - Consulta usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#111]
Se requiere realizar la integración del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) con el microcliente de [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf), el componente de consulta de usuarios.
Para esta integración se requiere realizar ajustes en el microcliente unificando los cambios que se vienen trabajando en las Issues #99 y #100, que permitan integrar este submódulo de consulta de usuarios.

![image](https://github.com/user-attachments/assets/8a5613eb-3380-4575-958b-6f36e13a1632)

**Subtareas**

- [x] Ajustes en el componente de consulta de usuarios en el microcliente.
- [x] Integración con el microservicio para consultar los usuarios registrados.
- [x] Agregar acciones para edición de usuario.
- [x] Implementación campo de búsqueda.

**Escenarios de pruebas**
- [x] Pruebas funcionales de la visualización de usuarios en la tabla.
- [x] Pruebas funcionales del filtrado usando el campo de búsqueda.

**Criterios de aceptación**

- [ ] Documentación pruebas funcionales que permitan visualizar el listado de los usuarios registrados y el funcionamiento del campo de búsqueda.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)
2. Repositorio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
3. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
4. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance consulta de usuarios

Se inicia con la revision del código del componente para comprender su funcionalidad.

Posteriormente se realiza el ajuste para llevarlo al modulo de "gestion-usuarios" y se cambia el nombre del componente a "consulta-usuarios", se verifica que se siga ejecutando correctamente

![Captura de pantalla 2024-07-29 a la(s) 11 43 16 p  m](https://github.com/user-attachments/assets/dc8084b3-6b92-44c4-b436-75a08b02f68b)

Finalmente se inicia con la implementación del campo de búsqueda por correo o documento:

![Captura de pantalla 2024-07-29 a la(s) 11 50 14 p  m](https://github.com/user-attachments/assets/dfe5b442-1c49-4aeb-97e0-742f059b19e8)

**Comment by alexhrr** [comment]
### Avance consulta de usuarios

Se procede a modificar el input para búsqueda por documento de identidad y agregando el boton para buscar:

![Captura de pantalla 2024-07-30 a la(s) 11 04 33 p  m](https://github.com/user-attachments/assets/f232f548-829a-4f98-b628-c733b4f383c5)

Posteriormente se continua con la integración de las consultas para el llenado de la tabla, en este caso se realiza la búsqueda por documento para traer algunos datos del usuario:

![gift1](https://github.com/user-attachments/assets/ddbd6233-4a26-4821-925e-86fe0afe5353)

Finalmente se ajusta el boton de edición para el usuario de la tabla, dirigiendo la consulta al componente de actualizar usuario:

![2024-07-30-22-58-35](https://github.com/user-attachments/assets/4a71c4f6-5f93-48e4-b507-7e3133cc0890)

Falta por completar la integración de historico roles con las consultas respectivas, asi mismo definir el flujo de consultas para la información que se va a mostrar en la tabla

**Comment by edwargl7** [comment]
Muy buen trabajo avanzado.

Revisando con apoyo del arquitecto se hace necesario para garantizar la menor cantidad de lógica posible en el microcliente realizar un desarrollo en autenticación mid.

**Flujo consultando por documento de identidad**

```mermaid
sequenceDiagram
    participant Gestion_Usuarios_MF
    participant Autenticacion_MID
    participant Historico_CRUD
    participant Terceros_CRUD
    

    Gestion_Usuarios_MF->>Autenticacion_MID: HTTP Request terceros/{documento}/periodos
    
    Autenticacion_MID->>Historico_CRUD: HTTP Request usuarios/{documento}/periodos
    Historico_CRUD-->>Autenticacion_MID: HTTP Response
    
    loop Datos Tercero
        Autenticacion_MID->>Terceros_CRUD: HTTP Request /tercero/identificacion
        Terceros_CRUD-->>Autenticacion_MID: HTTP Response

        Note right of Autenticacion_MID: Para cada periodo complementa <br/>los datos del tercero y correo de <br/>WSO2.
    end

    Autenticacion_MID-->>Gestion_Usuarios_MF: HTTP Response
```

**Flujo consultando sin filtro de usuario**
```mermaid
sequenceDiagram
    participant Gestion_Usuarios_MF
    participant Autenticacion_MID
    participant Historico_CRUD
    participant Terceros_CRUD
    

    Gestion_Usuarios_MF->>Autenticacion_MID: HTTP Request roles/periodos?limit=x&offset=y
    
    Autenticacion_MID->>Historico_CRUD: HTTP Request /periodos?limit=x&offset=y
    Historico_CRUD-->>Autenticacion_MID: HTTP Response
    
    loop Datos Tercero
        Autenticacion_MID->>Terceros_CRUD: HTTP Request /tercero/identificacion
        Terceros_CRUD-->>Autenticacion_MID: HTTP Response

        Note right of Autenticacion_MID: Para cada periodo complementa <br/>los datos del tercero y correo de <br/>WSO2.
    end

    Autenticacion_MID-->>Gestion_Usuarios_MF: HTTP Response
```

**Comment by edwargl7** [comment]
El alcance de esta tarea cambia para integrar la búsqueda del desarrollo adicional requerido abordado en la Issue #115 de consulta de usuario.

**Comment by edwargl7** [comment]
Se debe finalizar esta Issue con la #118 .

**Comment by alexhrr** [comment]
### Integración historico usuarios para consulta

Se realiza la integración del microservicio historico usuarios en el modulo de consulta de usuarios haciendo uso de autenticacion_mid como se muestra en los diagramas.

Prueba de información de los periodos de los usuarios sin filtro:

![Captura de pantalla 2024-08-09 a la(s) 7 14 08 p  m](https://github.com/user-attachments/assets/83278db5-ca25-4eae-a6eb-44e4b4df28d1)

Prueba de información de los periodos de los usuarios con filtro por documento:

![Captura de pantalla 2024-08-09 a la(s) 7 14 35 p  m](https://github.com/user-attachments/assets/8836ec85-1b12-4637-86fc-ff58b0062af6)
