### ISSUE TITLE
Integración microservicio histórico y microcliente de gestión de usuarios - Creación/Edición

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#112]
Se requiere continuar con la integración avanzada en las Issue #99 y #100 una vez se solucionen las dependencias requeridas con WSO2 para agregar y remover los roles. Y se implementen los ajustes requeridos en el microservicio de histórico para la consulta de periodos por documento del usuario.

**Sub Tareas**
- **Registrar usuario**
- [x] Implementación con WSO2 para agregar roles a un usuario en WSO2.
- [x] Pruebas funcionales donde se observe que se agregó correctamente el rol al usuario en WSO2.
- **Actualizar usuario**
- [x] Implementación endpoint de consulta de periodo.
- [x] Implementación con WSO2 para remover roles a un usuario en WSO2.
- [x] Pruebas funcionales donde se observe que se removió correctamente el rol al usuario en WSO2.
- [x] Pruebas funcionales de la actualización de un usuario en el microservicio histórico usuarios.

**Escenarios de pruebas**
- [x] Validación de la correcta asignación del rol al usuario existente en WSO2.
- [x] Actualización de un usuario en histórico usuarios roles finalizando el periodo y validando el cambio de estado.
- [x] Validación de la correcta eliminación del rol al usuario existente en WSO2.

**Criterios de aceptación**

- [x] Documentación de pruebas funcionales del registro de periodos a un usuarios y edición con la finalización de un periodo.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)
2. Repositorio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance Integración roles WSO2

Se realiza la integración de la adición de roles en WSO2 desde el microcliente para la sección de "Registrar usuario"

Se verifica los roles que tiene el usuario con identificacion "123456789" entre los que **no** se encuentra el rol JEFE_DEPENDENCIA:

![Captura de pantalla 2024-08-09 a la(s) 7 25 14 p  m](https://github.com/user-attachments/assets/536aef1b-f0e9-42d2-9e18-2f1bb015a2e7)

Se realiza la creación del usuario desde el microcliente seleccionado el rol JEFE_DEPENDENCIA:

![Captura de pantalla 2024-08-09 a la(s) 7 22 12 p  m](https://github.com/user-attachments/assets/a37c06fc-ef0c-4241-ba63-40b6bc62585d)

Se realiza la verificación de la creación del periodo en el modulo de consulta del microcliente:

![Captura de pantalla 2024-08-09 a la(s) 7 22 32 p  m](https://github.com/user-attachments/assets/7a767769-2e0b-4767-9274-a21445048462)

Finalmente se verifica la adición del rol JEFE_DEPENDENCIA en WSO2:

![Captura de pantalla 2024-08-09 a la(s) 7 26 33 p  m](https://github.com/user-attachments/assets/cd85cb9f-fbc4-416d-8ee6-536b1a37659f)

Se debe realizar la implementación requerida en el modulo de actualizar usuario

**Comment by alexhrr** [comment]
### Avance integración modulo Actualizar usuario

Se Implementa la consulta de rol id para traer la información del rol seleccionado:

![image](https://github.com/user-attachments/assets/4c8dbbd4-0408-4698-9b25-05a4687fe07a)

Se muestra la información en la interfaz:

![image](https://github.com/user-attachments/assets/83322865-4496-45f0-b70e-74956c5df581)

Se encontraron los siguientes inconvenientes:

* Las fechas se muestran con un día menos de diferencia, al parecer por la zona horaria
 
![image](https://github.com/user-attachments/assets/a954fda7-00a2-4c64-bd97-40a4506add28)

* La consulta del rol no trae el nombre del rol y se debe hacer una consulta adicional para obtener el nombre mediante el id.

* Se inicia con la actualización del periodo mediante histórico usuarios rol, y se encuentra un problema con las fechas y la información a enviar para realizar la actualización, se informa el inconveniente y posteriormente me informan la solución que voy a probar el día de mañana.

* Se da inicio a la eliminación del Rol en WSO2 y se logra la eliminación directa desde el microcliente pero falta implementarla ajustando la finalización o la fecha del periodo mientras se solucionan las otras partes:

Usuario con el rol JEFE_DEPENDENCIA

![image](https://github.com/user-attachments/assets/929df11d-68ea-4455-bc7a-d3d153027db3)

Información de la consulta:

![image](https://github.com/user-attachments/assets/3c14ff50-ea90-4332-ac54-770afc57634f)

Interfaz de actualización con los datos del periodo

![image](https://github.com/user-attachments/assets/113250f5-1bde-4d21-ba34-604981ca153e)

Eliminación directa del rol:

![image](https://github.com/user-attachments/assets/702d7215-286d-4e22-a4d9-ec041ef6729f)

**Comment by alexhrr** [comment]
### Integración modulo Actualizar usuario

Se soluciona el inconveniente de las fechas, a pesar de que se realizo el cambio del tipo de dato de las fechas en la base de datos aun se tenia el mismo problema, se resolvió agregando (00:00:00) a la cadena de fecha para ajustar la zona horaria local.

Posteriormente se realiza la implementación del cambio de estado en histórico usuarios cuando se realice el cambio a finalizado en el microcliente.
Asi mismo se integro la función de remover el rol en WSO2 al actualizar el usuario si se finaliza el rol

Consulta de los usuarios donde se muestra que el usuario tiene asignado el rol de JEFE_DEPENDENCIA  y que el estado del rol es vigente:

![Consulta](https://github.com/user-attachments/assets/d31c3f43-3409-49a3-9056-687d54a2b178)

Tambien se revisa que el usuario tenga asignado el rol en WSO2:

![Rol inicial](https://github.com/user-attachments/assets/4b7f7398-15ae-4b33-9fe6-81968ec11c35)

En la interfaz de actualización de usuario se muestran los datos del usuario y del periodo seleccionado, aqui se cambia el estado a finalizado para realizar los cambios y se da click en guardar:

![ActualizarUsu](https://github.com/user-attachments/assets/0a48720f-0f91-40ad-b00f-0fc0595d268e)

Se verifica en la interfaz de consulta que se apliquen los respectivos cambios:

![ConsultaFinal](https://github.com/user-attachments/assets/2294c6a9-d559-46e4-9dd8-dac2caf389dd)

Se verifica que se realice la eliminación del rol en WSO2:

![RolesFinal](https://github.com/user-attachments/assets/3faed7f9-4a82-4138-b852-2bb293c9cd76)

Para obtener el nombre del rol todavia se realiza mediante la consulta por el id del rol, se continua la revisión por parte de Juan Miguel para obtener el nombre directamente de la consulta por id del periodo.

**Comment by edwargl7** [comment]
Esta Issue aunque se había adelantado la integración con WSO2 en el sprint anterior, dados los ajustes requeridos tomo los 5 PH asignados para este sprint.

**Comment by edwargl7** [comment]
Muy buen trabajo, se finaliza la revisión y se resuelve el PR.
