### ISSUE TITLE
Diseñar el mockup para el submódulo auditoría interna, con vistas de dependencia auditada

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#114]
Se requiere continuar con el diseño del mockup para el submódulo auditoría interna, con vistas de dependencia auditada

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el desarrollo del mockup de vistas flujo de aprobación y ejecución auditoría interna.

![Image](https://github.com/user-attachments/assets/29a4af96-4138-4afc-8837-e4e3f797c0a2)



Saludos

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp, pendiente las recomendaciones generadas para posterior aprobación del cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes solicitados por el equipo SoS en el mockup desarrollado. Pendiente presentar y recibir aprobación por parte del cliente.

![Image](https://github.com/user-attachments/assets/a25eab7b-466b-46ca-8623-757aa0fb4fb3)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjfNrd02TDVGmmJOtGHAGOkBZtzG-_BkHlVKrYEHs0z_nQ?e=WWq4VQ

Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, pendiente aprobación por parte del cliente!
