### ISSUE TITLE
Implementación endpoints de consulta de periodos en autenticación MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#115]
Se requiere realizar la implementación de dos endpoints en el microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) que permitan consultar los periodos de un usuario obteniendo nombre, correo y la información relacionada al periodo. Tener presente que debe poder filtrarse por sistema para solo mostrar los registros de periodos del usuario correspondientes.

**Sub Tareas**

- [x] Implementación endpoint de consulta de periodos del usuario por documento de identidad en autenticacion_mid, que permita listar todos los periodos del usuario con los datos adicionales requeridos para el microcliente (nombre y correo).

> [!NOTE]
> Los parámetros que llegan al microservicio de autenticacion_mid deben ser enviados como parámetros al microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) el cual tiene la posibilidad de realizar los filtros requeridos.

**Escenarios de pruebas**
- [x] Pruebas funcionales del correcto funcionamiento de petición de periodos por documento de identidad.
- [x] Pruebas funcionales de petición de periodos por documento de identidad, para documento no encontrado.

**Criterios de aceptación**

- [ ] Documentación de las pruebas realizadas a cada endpoint nuevo.

**Requerimientos**

No aplica

**Material de apoyo**
> **Flujo consultando por documento de identidad**

```mermaid
sequenceDiagram
    participant Gestion_Usuarios_MF
    participant Autenticacion_MID
    participant Historico_CRUD
    participant Terceros_CRUD
    

    Gestion_Usuarios_MF->>Autenticacion_MID: HTTP Request terceros/{documento}/periodos
    
    Autenticacion_MID->>Historico_CRUD: HTTP Request usuarios/{documento}/periodos
    Historico_CRUD-->>Autenticacion_MID: HTTP Response
    
    loop Datos Tercero
        Autenticacion_MID->>Terceros_CRUD: HTTP Request /tercero/identificacion
        Terceros_CRUD-->>Autenticacion_MID: HTTP Response

        Note right of Autenticacion_MID: Para cada periodo complementa <br/>los datos del tercero y correo de <br/>WSO2.
    end

    Autenticacion_MID-->>Gestion_Usuarios_MF: HTTP Response
```

> **Flujo consultando sin filtro de usuario**
```mermaid
sequenceDiagram
    participant Gestion_Usuarios_MF
    participant Autenticacion_MID
    participant Historico_CRUD
    participant Terceros_CRUD
    

    Gestion_Usuarios_MF->>Autenticacion_MID: HTTP Request roles/periodos?limit=x&offset=y
    
    Autenticacion_MID->>Historico_CRUD: HTTP Request /periodos?limit=x&offset=y
    Historico_CRUD-->>Autenticacion_MID: HTTP Response
    
    loop Datos Tercero
        Autenticacion_MID->>Terceros_CRUD: HTTP Request /tercero/identificacion
        Terceros_CRUD-->>Autenticacion_MID: HTTP Response

        Note right of Autenticacion_MID: Para cada periodo complementa <br/>los datos del tercero y correo de <br/>WSO2.
    end

    Autenticacion_MID-->>Gestion_Usuarios_MF: HTTP Response

```
- Resultado consulta de periodos por documento de identidad en desarrollo en la Issue #108.
![image](https://github.com/user-attachments/assets/902339d8-47c3-49ff-833b-4130facb699f)

**Especificaciones técnicas**
1. Repositorio de [autenticacion_mid](https://github.com/udistrital/autenticacion_mid)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance integración

Se inicia con la integracion de Historico roles y terceros.
Se crea la rama para la integración en autenticación mid  y se ajustan las variables de entorno:

![Captura de pantalla 2024-07-31 a la(s) 10 38 52 p  m](https://github.com/user-attachments/assets/ab3fd7c5-6098-4a21-9e40-1faf83426711)

Se crean los archivos para los periodos en services y helpers:

![Captura de pantalla 2024-07-31 a la(s) 10 50 09 p  m](https://github.com/user-attachments/assets/b4073861-61a9-490d-8cbd-ff9c92e1a8b0)

![Captura de pantalla 2024-07-31 a la(s) 10 50 15 p  m](https://github.com/user-attachments/assets/2f1656ea-4d6e-41f7-a132-332ef5cf52ca)

Se realiza la revision de los datos para la creación de los modelos para el nuevo enpoint

**Comment by alexhrr** [comment]
Se realiza la revisión del endpoint creado para la implementación de PeriodosRoles y se comienza con su desarrollo 

Se esta realizando primero el endpoint con filtro por usuario y se hace un replanteamiento de la estructura a desarrollar para el flujo de las consultas, teniendo en cuenta la información recibida y como se va a mostrar

![Captura de pantalla 2024-08-01 a la(s) 10 40 15 p  m](https://github.com/user-attachments/assets/d67865ab-fe87-4bfb-8e63-6b41f402bbdc)

![Captura de pantalla 2024-08-01 a la(s) 10 37 56 p  m](https://github.com/user-attachments/assets/9bc5eacb-6d0b-4386-85b8-2b0f09b98e88)

Se tiene planeado el desarrollo de 3 helpers ( Usuario, periodoRol, terceros) que servirán para hacer las consultas necesarias y entregar la información al service que se encargara de reunir la información y guardar los datos necesarios en una estructura para la tabla de la consulta, esto se va a agregar al router que va a contener la información del endpoint, se realiza la definición de los modelos necesarios para la información que se va a recibir.

**Comment by alexhrr** [comment]
### Implementación endpoint consulta por documento

Se desarrolla el nuevo endpoint en el microservicio autenticacion_mid para consultar los periodos de un usuario mediante su documento de identidad, este endpoint realiza las consultas a terceros y WSO2 para traer la información del usuario, realiza la consulta al microservicio historico_usuarios_roles_crud para obtener la informacion de los periodos de los roles del usuario:

![Captura de pantalla 2024-08-02 a la(s) 11 52 09 p  m](https://github.com/user-attachments/assets/71e7a31e-cdd7-4d65-8fb7-f982875c0fa0)

![Captura de pantalla 2024-08-02 a la(s) 11 52 25 p  m](https://github.com/user-attachments/assets/584ef14c-a313-42e9-ab1b-d3308c5fbe02)

Este endpoint es consumido por el microcliente para mostrar los datos obtenidos en la tabla de consulta de usuarios cuando se filtra por documento de identidad como se ve a continuacion:

![Captura de pantalla 2024-08-02 a la(s) 11 54 40 p  m](https://github.com/user-attachments/assets/cb8a1295-4783-4058-87bc-5baf58e8911f)

Cuando se realiza la búsqueda de un documento que no existe se muestra el modal de usuario no encontrado:

![Captura de pantalla 2024-08-02 a la(s) 11 55 30 p  m](https://github.com/user-attachments/assets/4e759b60-fd46-4693-b428-016d6ae32062)

**Comment by edwargl7** [comment]
Muy buen trabajo, agregar por favor el campo **finalizado** al endpoint implementado en autenticación MID.

**Comment by alexhrr** [comment]
Se agrega el campo finalizado en el endpoint y el microcliente de la consulta:

![Captura de pantalla 2024-08-08 a la(s) 10 34 42 p  m](https://github.com/user-attachments/assets/4064464b-a3b0-4fd1-96db-d2aaee24ba31)
