### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#116]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente para aprobación de mockups

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación de Mockups por parte del cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta con el cliente, pendiente confirmación disponibilidad.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

se programa reunión con el cliente para el día 15 de agosto de 2024 hora 2:30 pm.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con el cliente en la oficina de control interno sede Paiba el día 15 de agosto de 2024 en horario de 02:30 pm a 4:30 pm. Pendiente levantar acta de reunión y posterior recolección de firmas.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión No 108/2024 Sisifo - Levantamiento de requerimientos. Pendiente recolección de firmas por los participantes presentes en la reunión.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqXOm6P0EMNEsvZ3D8dG7TkBVIWfZ21nsZXoRCtCgoOy-w?e=srMg2w


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se recolectan firmas de todos los participantes y se da por finalizada la issue #116.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqXOm6P0EMNEsvZ3D8dG7TkBVIWfZ21nsZXoRCtCgoOy-w?e=zIFZa6


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, cada vez te rinde más con la recolección de firmas!
