### ISSUE TITLE
Continuar con el diseño del mockup para el submódulo auditoría interna, con vistas de flujo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#117]
Se requiere continuar con el diseño del mockup para el submódulo auditoría interna, con vistas de flujo
**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla diseño de mockup del flujo de aprobación auditoría interna - rol dependencia auditada.

**Mockup del flujo de aprobación auditoría interna - rol dependencia auditada**
![Image](https://github.com/user-attachments/assets/4fa04c5b-27a1-4fff-9966-224180792fe7)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjfNrd02TDVGmmJOtGHAGOkBZtzG-_BkHlVKrYEHs0z_nQ?e=8aMENf


Saludos.

**Comment by jcmurilloa** [comment]
Muy buenos mockups @cjgonzalezp, pendiente recomendaciones del equipo SoS frente a las pestañas en la parte superior, el rol del auditor al momento de generar el plan de trabajo y exposición del diseño al cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes al mockup de acuerdo con las sugerencias del equipo SoS. Se presenta diseño al cliente, se realizan ajustes y se recibe aprobación para el desarrollo en el sistema SISIFO V2.


![Image](https://github.com/user-attachments/assets/4245a860-6c2e-4a51-8cfc-332c0521cac7)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjfNrd02TDVGmmJOtGHAGOkBZtzG-_BkHlVKrYEHs0z_nQ?e=8aMENf

**Acta de reunión No 108/2024 aprobación mockup submódulo auditorías internas y vistas del flujo**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqXOm6P0EMNEsvZ3D8dG7TkBVIWfZ21nsZXoRCtCgoOy-w?e=tSMe4J

Saludos.

**Comment by jcmurilloa** [comment]
Excelente diseño y recepción de ajustes @cjgonzalezp!
