### ISSUE TITLE
Implementación endpoint de consulta de periodos con filtros en autenticación MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#118]
Se requiere realizar la implementación de un endpoint en el microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) que permitan consultar los periodos de un usuario obteniendo nombre, correo y la información relacionada al periodo. Tener presente que debe poder filtrarse por sistema para solo mostrar los registros de periodos del usuario correspondientes. Continuación Issue #115.

**Sub Tareas**

- [x] Implementación endpoint de consulta de periodos sin filtro, manteniendo un paginado en auntenticacion_mid, que al igual que la subtarea anterior permita obtener esa lista de periodos con los datos completos requeridos para el microcliente (nombre y correo) permitiendo paginar y tener presente la posibilidad de filtrar (activos e inactivos).

> [!NOTE]
> Los parámetros que llegan al microservicio de autenticacion_mid deben ser enviados como parámetros al microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) el cual tiene la posibilidad de realizar los filtros requeridos.
> Agregar el campo **finalizado** al los dos endpoints.

**Escenarios de pruebas**
- [x] Pruebas funcionales del correcto funcionamiento de petición de periodos Get All.
- [ ] Pruebas funcionales de petición de periodos Get All, filtrado de resultado no encontrado.

**Criterios de aceptación**

- [ ] Documentación de las pruebas realizadas a cada endpoint nuevo.

**Requerimientos**

No aplica

**Material de apoyo**
> **Flujo consultando sin filtro de usuario**
```mermaid
sequenceDiagram
    participant Gestion_Usuarios_MF
    participant Autenticacion_MID
    participant Historico_CRUD
    participant Terceros_CRUD
    

    Gestion_Usuarios_MF->>Autenticacion_MID: HTTP Request roles/periodos?limit=x&offset=y
    
    Autenticacion_MID->>Historico_CRUD: HTTP Request /periodos?limit=x&offset=y
    Historico_CRUD-->>Autenticacion_MID: HTTP Response
    
    loop Datos Tercero
        Autenticacion_MID->>Terceros_CRUD: HTTP Request /tercero/identificacion
        Terceros_CRUD-->>Autenticacion_MID: HTTP Response

        Note right of Autenticacion_MID: Para cada periodo complementa <br/>los datos del tercero y correo de <br/>WSO2.
    end

    Autenticacion_MID-->>Gestion_Usuarios_MF: HTTP Response

```
- Tener presente que debe retornar la misma estructura trabajada en la Issue #115, la respuesta de consulta de periodos por documento de identidad en desarrollo en la Issue #108.
![image](https://github.com/user-attachments/assets/902339d8-47c3-49ff-833b-4130facb699f)

**Especificaciones técnicas**
1. Repositorio de [autenticacion_mid](https://github.com/udistrital/autenticacion_mid)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance consulta Periodos

Se da inicio a la implementación del endpoint para el microservicio autenticacion_mid que permite consultar los los periodos sin filtros obteniendo la información de los usuarios:  

Se realiza la creación del controller:  

![Captura de pantalla 2024-08-05 a la(s) 9 13 28 p  m](https://github.com/user-attachments/assets/5a50dcae-11ee-42a1-9ac5-e37aa3b83c25)

Se realiza la creación del helper:  

![Captura de pantalla 2024-08-05 a la(s) 9 13 51 p  m](https://github.com/user-attachments/assets/a714f9d7-5d78-4af8-a836-d732dca105d5)

Se inicia la creación del servicio que va a usar los respectivos helpers para la consulta de la información de los usuarios: 

![Captura de pantalla 2024-08-05 a la(s) 9 14 43 p  m](https://github.com/user-attachments/assets/59689e28-d147-4b97-9901-bd1fad03cf39)

**Comment by alexhrr** [comment]
### Avance consulta Periodos

Se realiza la implementación del nuevo endpoint (rol/periods) en el microservicio autenticacion_mid para realizar la consulta de los periodos de los usuarios obteniendo la información de cada usuario:

![Captura de pantalla 2024-08-08 a la(s) 9 39 20 a  m](https://github.com/user-attachments/assets/f903f867-dc08-4927-98c9-b1c380cfc94f)

Se tiene en cuenta la implementación de los filtros limit y offset para la paginación con los parametros según el diagrama:

![Captura de pantalla 2024-08-08 a la(s) 9 39 35 a  m](https://github.com/user-attachments/assets/7d270708-9d73-4115-ab2f-f803fc0214d7)

Se agregan datos para realizar las pruebas de la información a mostrar:

![Captura de pantalla 2024-08-08 a la(s) 9 39 58 a  m](https://github.com/user-attachments/assets/843f5da3-5075-49c6-9bd0-ccec27a22de9)

Información obtenida sin filtros limit y offset, se trae la información de cada usuario según los requerimientos haciendo la consulta en WSO2 y Terceros:

![Captura de pantalla 2024-08-08 a la(s) 9 39 47 a  m](https://github.com/user-attachments/assets/d34d7796-8b86-4f22-9f81-5524140ff2af)

Ahora se hace uso del filtro limit para mostrar unicamente dos registros:

![Captura de pantalla 2024-08-08 a la(s) 9 40 11 a  m](https://github.com/user-attachments/assets/1bacbf2d-19e8-4ea6-8625-d44047b0bb0a)

Resultados obtenidos:

![Captura de pantalla 2024-08-08 a la(s) 9 40 16 a  m](https://github.com/user-attachments/assets/e784a3cb-cd13-4454-896d-01d3e9f1f651)

Se solucionó un error que se obtenía al mostrar los correos de los usuarios desde el servicio de WSO2.
Tengo dudas con respecto al formato de las fechas de creación y modificación , se consultara en el daily.
Ahora se debe continuar con la revision del código para eliminar comentarios, logs etc.
Posteriormente se debe implementar el endpoint en la sección de consulta para el microcliente.

**Comment by edwargl7** [comment]
Se va a revisar con más detalle sobre la respuesta de las fechas de creación y actualización. Junto con @jucastro94

**Comment by alexhrr** [comment]
### Avance implementación endpoints

Se revisan los formatos de la estructura que recibe las fechas de creación/actualización y se soluciona el inconveniente que se tenía.

Se realiza una revision general del código del microservicio autenticacion_mid para su depuración.

Se agrega el campo finalizado en los endpoints desarrollados y se agrega el campo en el microcliente de consulta:

![Captura de pantalla 2024-08-08 a la(s) 10 34 42 p  m](https://github.com/user-attachments/assets/1055e14f-2875-44a0-8776-750c78de63f6)

Se realiza la integración del endpoint en el microcliente para la consulta de los periodos sin filtrar por usuario y mostrando la información de cada usuario:

![Captura de pantalla 2024-08-08 a la(s) 10 34 16 p  m](https://github.com/user-attachments/assets/ed1f4ea0-db7b-49d4-b570-04a8a9475123)

Se muestra la cantidad de resultados de acuerdo al limit y offset establecidos, enviadolos como parametro a autenticacion_mid y luego a historico_usuarios_roles_crud:

![Captura de pantalla 2024-08-08 a la(s) 10 36 25 p  m](https://github.com/user-attachments/assets/1ffc8f0b-64c5-4d3a-a0c3-6d3f32b4b122)

Se debe implementar el filtro por sistema.

**Comment by edwargl7** [comment]
Muy buen desarrollo, se finaliza y se trabajaran el filtro por sistema junto con otros filtros en otra Issue.
