### ISSUE TITLE
Diseñar el mockup de la vista del modulo Configuración

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#12]
Se requiere diseñar el mockup para la vista del módulo Plan de Mejoramiento de ARGO V2 de acuerdo a lo indicado en la reunión cliente. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al cliente.
- [ ] Realizar ajustes según comentarios del cliente.
- [ ] Presentar al equipo el mock definitivo para el desarrollo.

**Criterios de aceptación**

- [ ] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza un mockup inicial del módulo de configuración para el desarrollo del sistema SISIFO V2

**Identidad Visual Sisifo V2**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/4851ce98-9433-4e53-8535-e131c4165928)

**Modulo Tipo Calificación**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/35bdd85f-b600-43c5-8a67-c12a3e240ec2)

**Modulo Origen Plan Mejoramiento**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/cba18ab1-c719-4ec9-8d1b-1ad433008aa4)

**Modulo Proceso**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/bd6dde76-aa02-49f9-9c95-f56543d23ade)

**Modulo Abrir Registro Avance** 
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/17f8cfca-5b8a-4a33-b547-71710f999c16)

**Link archivo mockup modulo configuración**
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Efhaqh0b5NxKq4_kZ3141coBmdfz6v8utdSFosRcN5aXBA?e=0COqu4


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo de linea base del sistema actual. Se debe generar la actualización de diseño según los requerimientos del cliente, conforme a los lineamientos visuales vigentes.

**Comment by jcmurilloa** [comment]
Se cierra Issue debido a que, por el momento no se cuenta con constitución oficial del proyecto por parte del patrocinador y cliente.
