### ISSUE TITLE
Pruebas de integración microservicio plantillas de formularios dinámicos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#120]
Se requiere realizar la implementación de pruebas unitarias y de integración al microservicio de [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud).

**Sub Tareas**

- [x] Implementar pruebas de integración de creación, actualización, consulta de todos los registros, consulta por id y eliminación lógica de modal alerta.
- [x] Implementar pruebas de integración de creación, actualización, consulta de todos los registros, consulta por id y eliminación lógica de formulario.
- [x] Implementar pruebas de integración de creación, actualización, consulta de todos los registros, consulta por id y eliminación lógica de elementos HTML.

**Escenarios de pruebas**
- [x] Prueba creación, actualización, consulta de todos los registros, consulta por id y eliminación lógica del recurso _modal_alerta_ al servicio Mock para validar el correcto funcionamiento teniendo presente la revisión de Mock de base de datos.
- [x] Prueba creación, actualización, consulta de todos los registros, consulta por id y eliminación lógica del recurso _formularios_ al servicio Mock para validar el correcto funcionamiento teniendo presente la revisión de Mock de base de datos.
- [x] Prueba creación, actualización, consulta de todos los registros, consulta por id y eliminación lógica del recurso _elementos HTML_ al servicio Mock para validar el correcto funcionamiento teniendo presente la revisión de Mock de base de datos.

**Criterios de aceptación**

- [x] Escenarios mínimo de pruebas cubierto, se pueden agregar pruebas unitarias adicionales que sean identificadas en los recursos.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microservicio crud [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Modificaciones en las Pruebas de la Colección `modulos`

Se han realizado modificaciones significativas en las pruebas unitarias de la colección `modulos`. Estos cambios también se aplicarán a las demás colecciones;

1. **Reestructuración de las Pruebas:**
 Se ha ajustado la estructura de las pruebas para una implementación más efectiva. Anteriormente, se había planteado incorrectamente el acceso a las funciones del servicio durante las pruebas unitarias, lo que afectaba el reporte de cobertura.

![image](https://github.com/user-attachments/assets/4beb0c89-d640-48e3-9ee7-c865bebec879)

2. **Actualización en el Controlador:**
Se ha modificado la estructura de respuesta del controlador para incluir bloques `try` y `catch`, mejorando la gestión de errores y asegurando que las respuestas sean manejadas adecuadamente.

![image](https://github.com/user-attachments/assets/a1e6e18a-59eb-4f47-af9c-afb60079b429)

3. **Cambio de `save` a `create()`:**
Se ha reemplazado el uso de `save` por `create()` en las pruebas y en el código del servicio, debido a inconvenientes que presentaba el método `save` para el análisis en las pruebas unitarias.

![image](https://github.com/user-attachments/assets/1452ef90-cc66-4d0a-a3f1-cf7eb17d4101)

El nuevo reporte de coverage que refleja las modificaciones realizadas y el progreso en la cobertura de pruebas

![image](https://github.com/user-attachments/assets/ab34a659-2656-4f64-ab99-c728b4af30be)

**Comment by CristianCGutierrezG** [comment]
## Pruebas de Integración para Formularios

### Pruebas unitarias

Se desarrollaron pruebas unitarias específicas para la colección `formularios` para el service y el controller.

**Service**

![image](https://github.com/user-attachments/assets/0dcb9727-3fae-40cf-bd3b-cf4ce5f36f09)

**Controller**

![image](https://github.com/user-attachments/assets/85594c99-874b-4602-a938-a5753d64c496)

### Prueba de Integración

![image](https://github.com/user-attachments/assets/0ae2e384-1cdd-432c-9357-bda9a687d1d1)

![image](https://github.com/user-attachments/assets/76c81819-2ddf-41cc-af36-a7f5fc02e09f)

### Resultado del coverage

![image](https://github.com/user-attachments/assets/94197ca9-c4b2-450b-a18d-73e6fb3fa378)

**Comment by CristianCGutierrezG** [comment]
### Pruebas Unitarias y de Integración

Se desarrollaron pruebas unitarias y de integración específicas para el servicio y el controlador de las siguientes colecciones:

- **Sección**
- **Elementos HTML**
- **Elementos Personalizados**
- **Alerta Modal**

#### Resultado de Prueba de Integración del Endpoint de Módulos

![image](https://github.com/user-attachments/assets/c7f303fa-674c-4006-8545-650e422e7b3c)

#### Resultados del Coverage actual

![image](https://github.com/user-attachments/assets/4b9c2a71-a22e-42c4-9090-04355dd58545)
![image](https://github.com/user-attachments/assets/b4bb9d05-6fd3-4cbd-bc7d-33119c4d8fc9)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR.
