### ISSUE TITLE
Implementación query param filtro de periodos por sistema

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#121]
Se requiere realizar la implementación del filtro de periodos por sistema, para lo cual se requiere dado que no es directa la consulta investigar la forma de hacer join de la tabla rol con sistema para poder hacer ese filtro más fácil desde el cliente sin la necesidad de conocer el cliente los roles de dicho sistema.

**Sub Tareas**

- [x] Investigación de JOIN para realizar la consulta de periodos por sistema, puede revisarse Raw de Beego para query personalizadas.
- [x] Validar que la opción con Raw permita aplicar los query params como query, limit, offset, ... como en los Get All trabajados actualmente.
- [x] Se requiere agregar la validación en el endpoint de GetAll periodos-rol-usuarios y para el endpoint de periodos por documento de identidad /:documento/periodos. Que cumpla la estructura de filtro usada en las APIs de Beego _?query=sistema_informacion:1_.

**Criterios de aceptación**

- [x] Implementación de ajustes en los endpoints de consulta de periodos.

**Requerimientos**

No aplica

**Material de apoyo**
- https://github.com/beego/beedoc/blob/master/en-US/mvc/model/rawsql.md
- https://pkg.go.dev/github.com/beego/beego/v2/client/orm#section-readme

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se agrega validacion en GetAll de periodos-rol-usuarios para realizar JOIN con  ?query=sistema_informacion:1 permitiendo query params

```go


	// Verificar si el query contiene sistema_informacion
	var l interface{}
	var err error
	if sistemaID, ok := query["sistema_informacion"]; ok {
		// Llamar al servicio de SistemaInformacion
		l, err = services.PeriodosPorSistema(nil, sistemaID, query, fields, sortby, order, offset, limit)
	} else {
		// Llamar al servicio estándar
		l, err = services.GetAllPeriodoRolUsuario(query, fields, sortby, order, offset, limit)
	}

```
se escribe service que admite el id del servicio y el id del usuario para el endpoint de  /:documento/periodos



![Image](https://github.com/user-attachments/assets/060c45ee-5c59-473e-a5d4-311178ea9032)


se escribe modelo realizando JOIN con .Raw , validando si se ingresa un numero id de usuario, y seteando los parametros en el query

```go
func GetPeriodosBySistemaId(usuarioId *string, sistemaId int, query map[string]string, fields []string, sortby []string, order []string,
	offset int64, limit int64) (ml []interface{}, err error) {

	o := orm.NewOrm()
	var results []PeriodoRolUsuario

	// Base SQL Query con filtros por sistema de información y usuario
	sql := `SELECT p.* FROM periodo_rol_usuario p 
			INNER JOIN rol r ON p.rol_id = r.id 
			INNER JOIN sistema_informacion s ON r.sistema_informacion_id = s.id 
			WHERE s.id = ?`

	// Si se pasa un usuarioId, se agrega a la consulta
	if usuarioId != nil {
		sql += fmt.Sprintf(" AND p.usuario_id = %d", *usuarioId)
	}

	// Agregar otros filtros dinámicos
	for k, v := range query {
		sql += fmt.Sprintf(" AND %s = '%s'", k, v)
	}

	// Sorting
	if len(sortby) > 0 {
		sql += " ORDER BY "
		for i, s := range sortby {
			orderby := s
			if len(order) == 1 {
				orderby += " " + order[0]
			} else if len(order) > 1 {
				orderby += " " + order[i]
			}
			if i < len(sortby)-1 {
				sql += orderby + ", "
			} else {
				sql += orderby
			}
		}
	}

	// Pagination
	sql += fmt.Sprintf(" LIMIT %d OFFSET %d", limit, offset)

	// Execute query
	_, err = o.Raw(sql, sistemaId).QueryRows(&results)
	if err != nil {
		return nil, err
	}

	// Convertir los resultados a []interface{}
	for _, v := range results {
		// Si se especificaron campos, solo seleccionamos esos campos
		if len(fields) > 0 {
			m := make(map[string]interface{})
			val := reflect.ValueOf(v)
			for _, fname := range fields {
				m[fname] = val.FieldByName(fname).Interface()
			}
			ml = append(ml, m)
		} else {
			ml = append(ml, v)
		}
	}
	return ml, nil
}

```

**Comment by jucastro94** [comment]
se genera gitignore

se modifica query para que busque por nuemero de documento de llegar a ser necesario

![Image](https://github.com/user-attachments/assets/b01ec665-45ce-4147-9335-03c868b91025)



se implementalogica para identificar cuando llega un query diferente a "sistema_informacion"

![Image](https://github.com/user-attachments/assets/f0734747-ee04-47e8-8569-744adf475acd)


se modifica modelo de GetOne periodo_rol_usuario para que devuelva la informacion de los objetos relacionados

```go

// GetPeriodoRolUsuarioById retrieves PeriodoRolUsuario by Id. Returns error if
// Id doesn't exist
func GetPeriodoRolUsuarioById(id int) (*PeriodoRolUsuario, error) {
	o := orm.NewOrm()
	v := &PeriodoRolUsuario{Id: id}

	// Leer la entidad principal
	if err := o.Read(v); err != nil {
		return nil, err
	}

	// Cargar Usuario relacionado
	if v.UsuarioId != nil {
		if err := o.Read(v.UsuarioId); err != nil {
			return nil, err
		}
	}

	// Cargar Rol relacionado
	if v.RolId != nil {
		if err := o.Read(v.RolId); err != nil {
			return nil, err
		}
	}

	// cargar el SistemaInformacion relacionado con Rol
	if v.RolId != nil && v.RolId.SistemaInformacionId != nil {
		if err := o.Read(v.RolId.SistemaInformacionId); err != nil {
			return nil, err
		}
	}

	// Formatear fechas
	formateado, err := formatoFechas(*v)
	if err != nil {
		return nil, err
	}

	return &formateado, nil
}

´´´

**Comment by jucastro94** [comment]
se realizan pruebas  en endpoints periodos (periodos-rol-usuarios  , usuarios/:documento/periodos )

![Image](https://github.com/user-attachments/assets/c75eabf0-fa23-4eed-b9c2-e95591deab68)

![Image](https://github.com/user-attachments/assets/a563db76-2a82-42d2-ad9a-cd50430448d7)

**Comment by jucastro94** [comment]
se realiza pruebas de query params 

Fields
![Image](https://github.com/user-attachments/assets/1c8808b0-0f8b-411e-881b-384ab3c123f3)


Sortby y order
![Image](https://github.com/user-attachments/assets/72f90b1c-bab3-44dd-b076-5842c39d0ce2)

limit y offset
![Image](https://github.com/user-attachments/assets/4b4ebfe6-d101-4aa0-851e-45fda9f10681)

**Comment by jucastro94** [comment]
se realizan ajustes para que traiga los datos de los objetos relacionados en la respuesta


![Image](https://github.com/user-attachments/assets/921d974f-2665-4950-9879-250df59880a7)

**Comment by edwargl7** [comment]
Se realiza la revisión de la implementación, cuenta con un buen desarrollo que cumple con lo solicitado. Se pueden implementar ajustes para evitar la inyección SQL y posiblemente los ajustes para evitar la iteración de los fields y tratar de abordarla directamente en la consulta SQL.
