### ISSUE TITLE
Implementación microcliente Plan anual de auditoría - Registro de actividades

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#122]
Se requiere realizar la implementación del componente que se empleará para el registro de actividades del plan anual de auditoría que se combinará con el formulario dinámico empleado para la información general y el formulario de cada actividad.
Este nuevo componente debe implementar el paso 2 que cuenta con una serie de botones y la tabla de actividades, que permiten la visualización, registro, edición y publicación del plan anual de auditoría. 
![image](https://github.com/user-attachments/assets/44560bbc-6665-4beb-8a1e-87c6cf233d55)

**Sub Tareas**

- [ ] Implementación microcliente plan anual de auditoría base.
- [ ] Implementación componente de registro de actividades.

**Criterios de aceptación**

- [ ] Documentación de la implementación y pruebas de la correcta visualización del componente basado en el Mockup.

**Requerimientos**

No aplica

**Material de apoyo**
- [Mockup de Plan anual de auditoría](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EaCqT0N5_TtHvrjg5ZA7t9sBINcYGuefrq3aTtg2SFwpyQ?e=tCrnvA).
- Repositorio de microcliente de [gestion_contractual_compras_contrato_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) con implementación de módulos por cada paso del stepper.

**Especificaciones técnicas**
1. Repositorio microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza clonacion para core y root 

se genera proyecto en angular
Angular CLI: 16.2.14
Node: 18.19.0
Package Manager: npm 10.2.3


se modifican dependencias 


![Image](https://github.com/user-attachments/assets/d6b80541-2248-49c7-9840-50fc47888a54)

**Comment by jucastro94** [comment]
se genera modulo y componentes 


![Image](https://github.com/user-attachments/assets/e83770d3-e8fd-4dc2-8779-f18c92032b91)

se realizan ajustesen root



![Image](https://github.com/user-attachments/assets/56c8ba0b-e560-42a4-8a43-d2e46242c837)


![Image](https://github.com/user-attachments/assets/6a34b486-7524-499b-b2cf-668c70c608d1)



se esta presentando error en 


![Image](https://github.com/user-attachments/assets/8e4ef42c-8319-449f-8f09-bf723bfe8676)

**Comment by jucastro94** [comment]
se realizan ajustes en gestion-auditoria.component.html y  gestion-auditoria.component.ts

```html
<p>gestion-auditoria works!</p>
<div class="border">
    <mat-stepper [linear]="isLinear" #stepper labelPosition="bottom">
        <mat-step>
            <ng-template matStepLabel>INFORMACION</ng-template>
            
        </mat-step>
        <mat-step [stepControl]="secondFormGroup">
            <ng-template matStepLabel>AUDITORIAS</ng-template>
            <app-registro-plan-anual-auditoria />
        </mat-step>
    </mat-stepper>
</div>
```

```typescript
import {Component, OnInit, ViewChild } from '@angular/core';
import {MatStepper} from "@angular/material/stepper";
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {RegistroPlanAnualAuditoriaComponent} from "./registro-plan-anual-auditoria/registro-plan-anual-auditoria.component";

@Component({
  selector: 'app-gestion-auditoria',
  templateUrl: './gestion-auditoria.component.html',
  styleUrls: ['./gestion-auditoria.component.css']
})
export class GestionAuditoriaComponent implements OnInit{
  @ViewChild('stepper') stepper!: MatStepper;
  @ViewChild(RegistroPlanAnualAuditoriaComponent) registroPlan!: RegistroPlanAnualAuditoriaComponent;


  secondFormGroup: FormGroup;

  constructor(private _formBuilder: FormBuilder) {
    this.secondFormGroup = this._formBuilder.group({});
  }
  ngOnInit() {
    // Paso 2
    this.secondFormGroup = this._formBuilder.group({
      secondCtrl: ['', Validators.required],
    });

  }

  isLinear = false;

  ngAfterViewInit() {
    this.stepper.selectionChange.subscribe((event) => {
      //Reset del componente (ligado al orden)
      if (event.previouslySelectedIndex === 3 && event.selectedIndex !== 3) {
        this.registroPlan.onStepLeave();
      }
    });
  }

```

**Comment by edwargl7** [comment]
Se culmina la primera implementación del microcliente, se continuará el desarrollo en la Issue asociada.
