### ISSUE TITLE
Implementación eliminación lógica de versionado de plantillas de formularios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#123]
Se requiere realizar la implementación del endpoint de eliminación lógica de plantillas de formularios dinámicos. Al eliminar una versión debe indicarse el número de versión que se quiere eliminar y el modulo al que pertenece.
Identificados con estos parámetros se procede a realizar la eliminación de formulario, secciones asociadas al formulario y elementos personalizados asociados a cada sección.

> [!CAUTION]
> La eliminación lógica no implica que ese número de versión vuelva a estar disponible. Por ejemplo, si la última versión creada es la número 10 y se elimina esa versión, la nueva creada se asignará con la versión 11. Esto con el fin de mantener correctamente el almacenamiento de versiones sin causar una sobreescritura.

**Sub Tareas**

- [x] Implementación endpoint de eliminación lógica de una versión especifica.
- [x] Pruebas funcionales de la correcta eliminación lógica.

**Criterios de aceptación**

- [x] Documentación de la implementación del nuevo controlador y pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microservicio crud [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] #129
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
## Implementación del Endpoint `Plantillas DELETE` 
El un nuevo endpoint de tipo DELETE  se encarga de eliminar de manera lógica (activo: false) todos los componentes que formen parte de una plantilla, incluyendo formularios, secciones, y elementos personalizados.

-  Recibe: Como query, el `modulo_id` y `versión` del formulario a eliminar.

- Devuelve: Confirmación de la eliminación del formulario.

#### Funciones del Servicio
1. **Encontrar el Formulario:** Busca el formulario a eliminar basado en el `modulo_id` y la `versión`.
2. **Eliminar Secciones:** Encuentra y elimina lógicamente las secciones asociadas al formulario.
3. **Eliminar Elementos Personalizados:** Localiza los elementos personalizados asociados a cada sección y los elimina lógicamente.
4. **Verificar `version_actual`:** Si el formulario eliminado es la `version_actual`, se actualiza este estado asignándolo al formulario activo más reciente.

### Prueba del Endpoint
Estado inicial en la base de datos:
![image](https://github.com/user-attachments/assets/fd3324d9-ef23-4bbc-8302-a1cd61cae047)

Eliminacion de la version 4
![image](https://github.com/user-attachments/assets/03ab527f-7340-4125-828e-f861ef43e8c1)

Confirmacion en la base de datos
![image](https://github.com/user-attachments/assets/3139f4de-3425-45ad-92ad-b45c571eac12)

### Prueba de eliminacion `version_actual`
Eliminacion de la version 6
![image](https://github.com/user-attachments/assets/e1bad9c6-5250-437d-9b1b-b254788170fa)

Se cambia la version 6 por la 5 como la nueva `version_actual`
![image](https://github.com/user-attachments/assets/16bf3c15-fe18-4e97-9437-372612252a57)

**Comment by edwargl7** [comment]
Buena implementación y documentación, se resuelve el PR.

**Recomendaciones**
- Se puede optimizar la cantidad de peticiones a la base de datos para la eliminación lógica de secciones y elementos por medio de la función updateMany.
- Se puede dividir la lógica de la función _changeCurrentVersion_ creando una función nueva que maneje la búsqueda de última versión activa para asignarla como versión actual y puede esa función emplearse como complemento de esta.
![image](https://github.com/user-attachments/assets/1c17b2f1-c158-4575-ae3f-4474bef49bc9).

**Observación**
- Validar caso en el que no exista ninguna versión activa que pueda activarse. Según el resultado, se debe complementar respuesta para que el API informe el cambio de versión y caso en el que quedaría sin versión actual.
