### ISSUE TITLE
Implementación manejo de errores microcliente gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#124]
Se requiere realizar la implementación para manejar errores en peticiones que puedan no ser alcanzadas o en la visualización del spinner que le permita al usuario identificar que se encuentra en proceso alguna petición.

**Sub Tareas**

- [x] Implementación de [progress-spinner](https://material.angular.io/components/progress-spinner/overview).
- [x] Implementación de modales de alerta en caso de presentarse fallos en las peticiones de las integraciones implementadas.

**Escenarios de pruebas**
- [x] Error en consulta de periodos al microservicio de histórico CRUD.
- [x] Error en consulta a autenticacion_mid.

**Criterios de aceptación**

- [x] Documentación de la implementación requerida y pruebas realizadas.

**Requerimientos**

No aplica

**Material de apoyo**
- 

**Especificaciones técnicas**
1. Repositorio microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Ejemplo de implementación en SGA.
https://github.com/udistrital/sga_cliente/blob/develop/src/app/pages/espacios-academicos/creacion-espacios-academicos/creacion-espacios-academicos.component.ts#L617
![image](https://github.com/user-attachments/assets/8788c16c-3621-43c6-9405-d0fcd1f4ed84)
![image](https://github.com/user-attachments/assets/0529c1bd-db38-4f33-8a68-a35d5d2c60aa)

**Comment by alexhrr** [comment]
### Avance implementación manejo de errores microcliente

Se realiza la revisión del material de apoyo para la implementación del progress spinner y se realiza la revisión del sistema SGA donde se tiene dicha implementación

Se inicia con la aplicación al codigo el microcliente en el modulo de creación de usuarios

**Comment by alexhrr** [comment]
### Implementación spinner 

Se soluciona el problema que se tenia ajustando el css y el problema de import con el componente de consulta usuarios

Despues de que se logre visualizar correctamente el spinner se procede a revisar el codigo para poner el inicio y fin del mismo en cada solicitud, se implementa en los 3 componentes actuales de la gestión de usuarios.

Algunos ejemplos de la implementación en los componentes:

Creación de usuarios:

![2024-08-15 22-48-02](https://github.com/user-attachments/assets/8490cd5b-d103-46ed-b8dc-baba4797ddd8)

Consulta de usuarios:

![2024-08-15 22-49-49](https://github.com/user-attachments/assets/f367e2e2-fb9d-4682-ba07-bbfd5b53826b)

Consulta con filtro:

![2024-08-15 22-50-25](https://github.com/user-attachments/assets/2797166a-dc81-4015-8933-3766173f784e)

Actualización de usuarios:

![2024-08-15 22-51-53](https://github.com/user-attachments/assets/e1447e29-c696-4000-98d5-d0d71ceda848)

Finalmente se da inicio al manejo de errores mediante el modal creado inicialmente para usarlo con diferentes mensajes según sea el caso

**Comment by alexhrr** [comment]
### Manejo de errores microcliente

Se finaliza la implementación del modal para los diferentes errores en el microcliente, se ajusta el mensaje a mostrar de acuerdo a lo requerido en cada caso.

Creación de usuarios:

![image](https://github.com/user-attachments/assets/f3140542-9771-4d27-a7bd-223988c686d2)

![image](https://github.com/user-attachments/assets/675fd04a-23fd-4633-9806-52d43ffeb222)


Consulta de usuarios:

Actualización de periodos: 

![image](https://github.com/user-attachments/assets/899fb86f-3e7c-409c-a8ef-114336427109)

**Comment by edwargl7** [comment]
Muy buen trabajo, cuenta con una muy buena implementación.

**Posibles mejoras**
- Se puede cambiar el nombre de la función que se usa para mostrar los modales de error por un nombre más genérico (actualmente _usuarioNoExisteModal_).
- Revisión de estilos (asociados al spinner) para agregarlos en el root y poder utilizar estos estilos en cualquier microcliente.
- Revisión del orden en el que se muestra el modal y se cambia el valor del spinner para evitar que una vez se muestre el modal pueda seguir visualizándose el spinner temporalmente.
```
this.usuarioNoExisteModal('Error al buscar el correo. Verifica los datos e intenta nuevamente.');
this.loading = false;
```
