### ISSUE TITLE
Implementación autorización en el microcliente de gestión usuarios - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#125]
Se requiere realizar la implementación de autorización en el microcliente de gestión de usuarios para solo permitir la funcionalidad de edición a ciertos usuarios que cuenten con el rol especifico.

Roles de Sísifo:
- Administrador (Permisos de registro/edición)
- Auditor Experto (a) 
- Auditor (a) 
- Ejecutor 
- Jefe dependencia (Permisos de registro/edición)
- Analista 
- Soporte

Dado que este sistema es transversal, debe contar con la posibilidad de indicarse por variable de entorno los ids de roles que cuentan con permisos de edición, cualquier otro rol solo tendrá permisos de lectura.

**Sub Tareas**

- [ ] Implementar consulta de roles con los que cuenta el usuario que se encuentra en la sesión.
- [ ] Implementar función que permita basado en el rol permitir la visualización o edición.

**Escenarios de pruebas**
- [ ] Usuario con permiso de edición.
- [ ] Usuario con permiso de solo lectura.

**Criterios de aceptación**

- [ ] Documentación de la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Ejemplo filtro de permisos por rol de usuario 
https://github.com/udistrital/sga_cliente/blob/develop/src/app/pages/plan-estudios/creacion-plan-estudios/creacion-plan-estudios.component.ts#L157

**Comment by alexhrr** [comment]
### Avance autorización roles

Se inicia la revisión del ejemplo de SGA para la autorización de acuerdo al rol del usuario, se verifican los roles en un arreglo llamado personaRoles donde se guardan los roles usando autenticacionService y getRoles que hacen parte de ImplicitAutenticationService

Se agrupan los roles en dos grupos y se busca el rol del usuario:

![image](https://github.com/user-attachments/assets/4fbfa7b7-a243-4c9c-bb2f-56b92b963686)

![image](https://github.com/user-attachments/assets/84ab529f-3365-4a5a-8b10-ded0ce9789ef)

Servicio de autenticación implícita para obtener el rol del usuario:

![image](https://github.com/user-attachments/assets/65f9ab92-aa8f-4cfc-ae90-7bbd2f2182c5)
 
Este servicio gestiona la autenticación de usuarios, verifica el token de autenticación del navegador, que es almacenado con la información del usuario y su rol.

getRoles obtiene los roles del usuario que proviene de la información almacenada anteriormente

**Comment by alexhrr** [comment]
Se realiza la revisión de codigo de SGA para el manejo del rol del usuario en autenticación, se deja el link del ejemplo para el planteamiento que se va a realizar cuando se aborde el tema de autorización por roles:

https://github.com/udistrital/sga_cliente/blob/develop/src/app/%40core/utils/implicit_autentication.service.ts

**Comment by edwargl7** [comment]
Se finaliza la primera etapa de revisión de roles para implementación en microcliente de gestión de usuarios y se pueda usar de base para otros microclientes.
