### ISSUE TITLE
Integración filtro de periodos por sistema en el microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#126]
Se requiere realizar el ajuste de filtro de periodos por sistemas en el microcliente de gestión de usuarios, el endpoint en el microservicio se implementa en la Issue #121.

**Sub Tareas**

- [x] Ajuste en la petición de búsqueda de periodos de usuarios sin filtro.
- [x] Ajuste en las peticiones de búsqueda de periodos de usuarios por documento de identidad.

**Escenarios de pruebas**
- [x] Visualización correcta de periodos sin aplicar filtros del microcliente.
- [x] Visualización correcta de periodos con filtro por documento de identidad.
- [x] Visualización de modal para usuario sin registros de periodos en el sistema actual.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales realizadas.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance filtros por sistema

Se realiza la revisión del codigo desarrollado para realizar el filtro por sistema y se da inicio al desarrollo en las peticiones del microcliente para realizar la búsqueda sin filtro.

Se realizan los ajustes necesarios para recibir el parámetro del sistema de información en autenticación mid y en el microcliente:

![image](https://github.com/user-attachments/assets/5c39d0ee-6a97-425f-bd6b-31a96c96d45e)

![image](https://github.com/user-attachments/assets/fa8d6114-8e50-4eb1-b3e9-e333080f6122)

![image](https://github.com/user-attachments/assets/b74617e7-c479-45aa-a4bf-bd67193fa869)

filtro periodo rol sistema de información 2

![image](https://github.com/user-attachments/assets/ab763c3e-3c7f-4579-944f-1cfe7afa2e21)

**Comment by alexhrr** [comment]
### Integración filtro por sistema

En la base de datos se tienen 4 registros de periodos para los 3 usuarios, el usuario con id = 2 tiene 2 roles ( 1 y 4 )

![image](https://github.com/user-attachments/assets/d56bdd9b-bddf-4d74-97db-08c04e90e952)

El rol uno pertenece al sistema de información 1, el rol 4 hace parte del sistema de información 2:

![image](https://github.com/user-attachments/assets/e778252e-10ae-40d3-b3b7-f4c8ed40d0c5)

Consulta de usuarios sin filtro, se muestran solo los usuarios del sistema de información 1, el usuario con documento 123456789 tiene dos roles de diferentes sistemas y aqui se muestra solo uno debido al filtro integrado:

![image](https://github.com/user-attachments/assets/f707e511-60ef-4d2d-a618-db605396cd08)

Consulta por filtro de documento, al igual que en el punto anterior al filtrar por el usuario con documento 123456789 solo aparece un periodo y no dos debido al filtro por sistema:

![image](https://github.com/user-attachments/assets/a7f6cdf2-6427-450b-8478-c0a9bf9e5306)

**Comment by edwargl7** [comment]
Pendiente subir commits con el código en cada servicio para poder realizar la validación del desarrollo.

**Comment by edwargl7** [comment]
Se resuelve el PR, buena implementación, se debe agregar los parámetros de filtro Limit y Offset al endpoint de consulta por documento de identidad. Y agregar en autenticación el query params Query para no solo filtrar por sistema si no permitir que pueda obtener los demás filtros permitidos en histórico usuarios roles CRUD.
