### ISSUE TITLE
Implementación validadores creación de nueva versión de plantilla formularios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#127]
Se requiere realizar la implementación de validadores que permitan comprobar antes de iniciar el registro de la plantilla en base de datos garantizar que los elementos HTML asociados en los elementos personalizados existan.
Además, se requiere realizar la implementación que permita que en caso de fallo en el registro completo, la descripción clara de la causa (elemento HTML no encontrado, ...) y la eliminación de los registros incompletos realizados (formulario, secciones, elementos personalizados) sin que estos sean contados como una versión ni sean almacenados en base de datos.

**Sub Tareas**

- [x] Implementación validadores de elementos personalizados.
- [x] Implementación rollback controlado para eliminar registros en caso de no completar el registro de la plantilla completamente.
- [x] Pruebas funcionales de la implementación.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales realizadas.

**Requerimientos**

No aplica

**Material de apoyo**
- 

**Especificaciones técnicas**
1. Repositorio microservicio crud [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se plantea utilización de transacciones, específicamente `ClientSession`, proporcionado por la biblioteca Mongoose. Este enfoque garantizará que las operaciones de creación y almacenamiento de colecciones solo se realicen si todos los datos son ingresados correctamente. Esto significa que si alguna de las operaciones falla, todas se revertirán para mantener el estado consistente.
  
En una reunion con @edwargl7  se discutió el funcionamiento básico de las transacciones en MongoDB.

- **Posibles Problemas:**
  - **Rendimiento:** El uso de transacciones puede afectar el rendimiento debido al overhead asociado con el manejo de sesiones y la gestión de rollbacks.
  - **Manejo del Almacenamiento:** La gestión incorrecta de transacciones podría llevar a problemas como bloqueos prolongados o inconsistencias si no se implementa correctamente.

#### Próximos Pasos
1. **Investigación Adicional:** Se realizará una investigación más profunda sobre cómo las transacciones afectan el rendimiento y el almacenamiento.
2. **Pruebas:** Se implementarán pruebas para evaluar el impacto de las transacciones en el servicio y asegurar que el sistema maneje correctamente los casos de éxito y fallo.

**Comment by CristianCGutierrezG** [comment]
## Investigación sobre Transacciones en MongoDB

### Prerrequisitos

Para utilizar transacciones en MongoDB, se deben cumplir ciertos requisitos y configuraciones:

- **Versión de MongoDB:** Se necesita MongoDB 4.0 o superior, ya que las transacciones multi-documento están disponibles a partir de esta versión.
- **Configuración de Replica Set:** La base de datos debe estar configurada como un Replica Set. Las transacciones no están disponibles en instancias standalone.

### Standalone vs. Replica Set

- **Standalone:**  Es una única instancia de MongoDB que opera de forma independiente.
  - **Ventajas:**
    - Menor complejidad y coste.
    - Configuración y mantenimiento más sencillos.
  - **Desventajas:**
    - Sin redundancia ni alta disponibilidad.
    - Riesgo de pérdida de datos en caso de fallos.

- **Replica Set:** Conjunto de múltiples instancias de MongoDB (nodos) que trabajan juntas para mantener una copia idéntica de los datos.
  - **Ventajas:**
    - Alta disponibilidad y redundancia de datos.
    - Soporte para transacciones ACID y lecturas distribuidas entre nodos.
  - **Desventajas:**
    - Mayor complejidad y coste.
    - Necesita más recursos y una configuración más detallada.

Según la documentación de MongoDB, una instancia standalone no es una buena opción para un despliegue en producción debido a que puede ser un punto único de fallo. Se recomienda siempre usar un replica set en producción para proporcionar redundancia y disponibilidad.

### Transacciones en MongoDB

Las transacciones permiten garantizar la integridad de las operaciones en una base de datos, asegurando que todas las operaciones se completen correctamente o ninguna se aplique. 

#### Métodos para Gestionar la Sesión

- **`startSession()`:** Abre una nueva sesión. Las transacciones están asociadas a una sesión, por lo que siempre necesitaremos iniciar una sesión para manejar transacciones.
- **`endSession()`:** Cierra la sesión. Si hay alguna transacción en curso, esta se abortará automáticamente al cerrar la sesión.

#### Métodos para Controlar la Transacción

- **`Session.startTransaction()`:** Inicia una transacción multi-documento dentro de una sesión.
- **`Session.commitTransaction()`:** Confirma los cambios realizados dentro de la transacción.
- **`Session.abortTransaction()`:** Aborta la transacción y descarta los cambios realizados durante esta.

#### Ventajas

- Garantizan las propiedades ACID (Atomicidad, Consistencia, Aislamiento, Durabilidad).
- Permiten realizar operaciones complejas que afectan a múltiples documentos y colecciones.
- Ayudan a manejar fallos en medio de operaciones complejas.

#### Desventajas

- Pueden ser costosas en términos de rendimiento, especialmente si afectan a múltiples documentos y colecciones.
- Implementar transacciones añade complejidad al código, ya que es necesario gestionar sesiones y manejar posibles fallos que puedan requerir abortar la transacción.
- Si una transacción tarda demasiado en completarse, puede provocar bloqueos prolongados que afectan a otros procesos.

### Documentación de MongoDB

 Documentación oficial: [MongoDB Transactions](https://www.mongodb.com/docs/manual/core/transactions/)

**Comment by CristianCGutierrezG** [comment]
Se hace una modificación para evitar el cambio de versión hasta que se confirme que todos los datos son correctos.

Se guarda el formulario con una versión momentánea.
![image](https://github.com/user-attachments/assets/e976a583-e959-48de-b70d-a0c957316a31)

despues de crear todo la plantilla, se asigna la nueva versión.
![image](https://github.com/user-attachments/assets/2d291e1e-8a99-4652-a5b2-7dd29c7de5c1)

**Comment by edwargl7** [comment]
Muy buena investigación y abordamiento del problema a resolver. Se recomienda identificar las funciones de eliminación lógica y eliminación real para tener mayor precaución en el uso de estás en futuros desarrollos.
