### ISSUE TITLE
Implementación microcliente Plan anual de auditoría - Consulta plan

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#128]
Se requiere realizar la implementación de la vista de consulta del módulo plan anual de auditoría basado en el [Mockup](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EaCqT0N5_TtHvrjg5ZA7t9sBINcYGuefrq3aTtg2SFwpyQ?e=tCrnvA).
![image](https://github.com/user-attachments/assets/d80f60ab-ea6b-4cfd-be8c-90ce0e8363f1)

**Sub Tareas**

- [x] Code Review implementación inicial en el repositorio del microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).
- [x] Implementación módulo de consulta de plan anual de auditoría.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas de la correcta visualización del componente basado en el Mockup.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio del microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
## Configuración Inicial

Se realiza la clonación del repositorio `plan_anual_auditoria_mf` para iniciar con el desarrollo y al ejecutar el microfrontend, se encontró un error relacionado con problemas de importación.

![2024-08-20T16_43_21](https://github.com/user-attachments/assets/73dda86e-66f0-4c55-b78f-4f283bc34f9a)

Se actualiza el código para el manejo correcto de los módulos en Angular.

![2024-08-20T16_44_40](https://github.com/user-attachments/assets/4073dac2-938e-4f27-8e52-d0eda3537867)

Se realizan los cambios en el root para la conexión con el nuevo microcliente.

![2024-08-20T16_57_44](https://github.com/user-attachments/assets/f16a6571-9a25-4b5a-a5d9-b0fb35e89def)
![2024-08-20T17_28_40](https://github.com/user-attachments/assets/632d1624-e0d0-4911-9624-ac9870272c84)

Incluyendo el provider en el `plan_anual_auditoria_mf` 
![2024-08-20T17_29_31](https://github.com/user-attachments/assets/888fa25e-97af-4933-b384-059c779f9b5f)

Se cambia el puerto de `4202` al puerto `4203` para evitar interferencias con el microcliente `auditoria_plan_mejoramiento_usuario_mf`.
Se termina por reorganizar la estructura de módulos para que Angular pueda reconocerlos correctamente.

![2024-08-20T19_30_11](https://github.com/user-attachments/assets/0e57b21c-0308-4ca1-901c-f4b0974a1d4c)

## Primera Versión del Componente

![2024-08-20T19_36_31](https://github.com/user-attachments/assets/8f461335-0f5e-49ac-b051-81de2317cf88)

**Comment by edwargl7** [comment]
Para la subtarea de code review también es importante validar la estructura similar al proyecto https://github.com/udistrital/gestion_contractual_compras_contrato_mf/tree/develop/src/app/modules/registro-contrato.

**Comment by CristianCGutierrezG** [comment]
## Code Review

Se encontraron problemas al clonar el repositorio debido a la falta de importaciones del módulo principal y del `CommonModule` en el `app.module.ts`.
![image](https://github.com/user-attachments/assets/0d507131-4e6c-41d2-a192-e5cec838aed4)

Teniendo en cuenta el repositorio de [gestion_contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf/tree/develop/src/app/modules/registro-contrato.) , se observa una implementación similar en el manejo de los steppers y en el llamado de los diferentes componentes, diferenciándose únicamente en el nombre de dichos componentes.

![image](https://github.com/user-attachments/assets/7accf376-6c90-4d05-bbc8-ec3afff751f9)

**Comment by CristianCGutierrezG** [comment]
Se realizan las modificaciones necesarias par la organizacion de los componentes para que se parezca al del repositorio de [gestion_contractual](https://github.com/udistrital/gestion_contractual_compras_contrato_mf/tree/develop/src/app/modules/registro-contrato.)
![image](https://github.com/user-attachments/assets/2f16cc86-768d-4a0a-8ba2-0c17ed223ed3)

Se agrega el archivo theme.scss para el manejo de los estilos 
![image](https://github.com/user-attachments/assets/eba91d7a-f7b0-4dea-98fc-9d41ec52ea67)

## Consulta plan - vista
![image](https://github.com/user-attachments/assets/06ebab8e-c03a-488b-922a-1e03eab45bc0)

**Comment by edwargl7** [comment]
Buena implementación y code review. Pendiente resolver conflictos PR.
![image](https://github.com/user-attachments/assets/6bfc6da4-98eb-419c-ab28-47238161ca95)

**Comment by CristianCGutierrezG** [comment]
Se realizaron las pruebas del correcto funcionamiento del microfrontend (MF) con el último PR, pero se encontró un error debido a que se removieron varios archivos necesarios para la ejecución.

![image](https://github.com/user-attachments/assets/7b62296d-1981-4af8-b2c4-a9de3ec58449)

Se vuelven a agregar los archivos faltantes y se hacen pruebas del correcto funcionamiento del MF.

![image](https://github.com/user-attachments/assets/0b0a3778-300b-4a6c-9055-381b5085d65a)

![image](https://github.com/user-attachments/assets/37416768-9fb2-435c-b7a0-e50642b3d1d2)

Se realiza una nueva PR con los cambios
