### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de requerimientos

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#13]
Se requiere realizar el 

**Sub Tareas**

- [ ] Concertar reunión de requerimientos con el cliente
- [ ] Desarrollar la reunión de requerimientos
- [ ] Proyectar acta de la reunión

**Criterios de aceptación**

- [ ] Acta revisada por el líder de proyecto
- [ ] Acta firmada por las partes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta al cliente Liliana Romero para definir reunión de levantamiento de requerimientos para el desarrollo del sistema SISIFO V2, me informa que al día de hoy no se ha tomado la decisión de elegir Daruma o continuar con el desarrollo de SISIFO V2.

Por el momento, el cliente se compromete a enviarnos el consolidado de los requerimientos definidos por la oficina de control interno el día 09 de mayo de 2024. Para que sea analizado por el equipo del proyecto desarrollador de SISIFO V2, mientras se logra concertar la reunión para el siguiente sprint.


Cordial saludo.

**Comment by jcmurilloa** [comment]
Se cierra Issue debido a que, por el momento no se cuenta con constitución oficial del proyecto por parte del patrocinador y cliente.
