### ISSUE TITLE
Continuar con el diseño del mockup para el submódulo auditoría interna para informes de seguimiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#130]
Se requiere continuar con el diseño del mockup para el submódulo auditoría interna, para informes de seguimiento

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño de mockup del submódulo de informe final para el sistema ARGO V2.

![Image](https://github.com/user-attachments/assets/048e39e2-2f2a-4ad4-87a2-8618d8780cd7)


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla diseño de mockup de la primera parte del submódulo de evaluación para auditorías internas. Se revisará con el cliente en la reunión programada el 15 de agosto y con el equipo SoS en la próxima Daily Scrum.


![Image](https://github.com/user-attachments/assets/11d4bd62-1e25-4ef8-b2e3-c78764f76f67)



Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, por favor tener en cuenta las comentarios del equipo SoS. Se continuará el diseño de vistas de flujo en el siguiente sprint.
