### ISSUE TITLE
Definir modales de alerta para el microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#133]
Se requiere realizar el diseño de los modales de alerta para los flujos en el microcliente de gestión de usuarios como complemento al desarrollo de la Issue #124.

**Sub Tareas**

- **Registro de usuario**
- [x] Error en el servicio al consultar un usuario por documento (fallo del sistema).
- [x] Error en el servicio al consultar un usuario por correo (fallo del sistema).
- [x] Usuario no encontrado por documento de identidad.
- [x] Usuario no encontrado por correo.
- [x] Error en el servicio al registrar un usuario (fallo del sistema).
- [x] Error en el servicio al registrar un usuario (error en validaciones).
- [x] Registro exitoso de un usuario.
- **Actualización de periodo de usuario**
- [x] Error al consultar los datos del periodo de un usuario (fallo del sistema).
- [x] Error al actualizar un periodo (error en validaciones).
- [x] Actualización exitosa de un periodo.
- **Consulta de periodos**
- [x] Error al consultar periodos sin filtrar (fallo del sistema).
- [x] Error al consultar periodos con filtro (fallo del sistema).
- [x] Usuario no encontrado.
- [x] Fallo en el paginado.

**Criterios de aceptación**

- [x] Mockup con modales de alerta para cada caso.

**Requerimientos**

No aplica

**Material de apoyo**
- [MANUAL DE IDENTIDAD VISUAL SUBSISTEMAS DE INFORMACIÓN](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20ARGO%20V2%2F2024%2FEJECUCI%C3%93N%2FGesti%C3%B3n%20t%C3%A9cnica%2FDocumentaci%C3%B3n%20%20recopilada%20Argo%20v1%2FLineamientos%20aplicativos%20V2%2Epdf&parent=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20ARGO%20V2%2F2024%2FEJECUCI%C3%93N%2FGesti%C3%B3n%20t%C3%A9cnica%2FDocumentaci%C3%B3n%20%20recopilada%20Argo%20v1)

![image](https://github.com/user-attachments/assets/c3912bad-d73d-4178-8608-169b630dec04)

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrollan diseños de mockup para los modales de alerta solicitados.

![Image](https://github.com/user-attachments/assets/45599190-f171-4a24-9909-f85a4bd56abd)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmfdWP1_O2FCtvA9J0RmIF4B79iSl4fpfu-jM3VwUxEKJw?e=PPvM87


Saludos.

**Comment by jcmurilloa** [comment]
Se revisa Mockup cumpliendo con lo solicitado. Se requiere definir con @edwargl7 los diseños pendientes junto al analista.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los modales de alerta faltantes revisados con el líder técnico y se culmina con la issue #133.


![Image](https://github.com/user-attachments/assets/50b1e8d0-a47d-403f-8c1e-71e0bd673bb5)


**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Usuarios?csf=1&web=1&e=WLHxNX

Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp, el equipo de desarrollo ya cuenta con estos requerimientos para trabajar!
