### ISSUE TITLE
Definición de permisos en el microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#134]
Se requiere realizar la definición de permisos por cada rol del sistema Sísifo para el módulo de gestión de usuarios.

**Sub Tareas**

- [x] Definir que roles tienen permiso de crear, actualizar y consultar periodos en el microcliente de gestión de usuarios.

**Criterios de aceptación**

- [x] Documentación de matriz de roles y permisos para el módulo de gestión de usuarios.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la definición de accesos y permisos para los diferentes roles.


[Gestión de Usuarios - Módulos y Permisos.pdf](https://github.com/user-attachments/files/16733038/Gestion.de.Usuarios.-.Modulos.y.Permisos.pdf)

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen diseño, se entiende gráficamente el objetivo de la definición y permisos para los diferentes roles y su interacción con los módulos y bubmódulos del sistema. Por favor tener en cuenta para replicar en los demás sistemas @mantnicot @JuanCamiloMartinezLopez @diagutierrezro
