### ISSUE TITLE
Implementación de paginación en submódulo de consulta de microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#135]
Se requiere realizar la implementación de paginado en la vista de consulta de histórico de roles de usuario basado en la documentación de Angular Material. Dado que es necesario según la cantidad de elementos (limit) realizar la petición al servicio para traer la cantidad de elementos requeridos asociados a la página seleccionada por el usuario (offset).
![image](https://github.com/user-attachments/assets/c7acf394-998d-4272-8e00-62a56311f59a)

**Sub Tareas**

- [ ] Implementación de paginado en la vista de consulta de periodos de usuario sin filtro.
- [ ] Implementación de paginado en la vista de consulta de periodos de usuario con filtro.

**Escenarios de pruebas**
- [ ] Pruebas con paginado sin filtro.
- [ ] Pruebas con paginado con filtro.

**Criterios de aceptación**

- [ ] Documentación de la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Material de apoyo**
- Material con información de [Data table](https://v8.material.angular.io/components/categories/tables) con manejo de **Paginator**, **Sort Header** y **Table**.
- Material para [Table mat-table](https://v16.material.angular.io/components/table/overview)
- [Pagination](https://v16.material.angular.io/components/table/overview#pagination)

**Especificaciones técnicas**
1. Repositorio microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf/tree/develop)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance implementación paginación

Se realiza la revision del material de apoyo para la paginación en el componente de consulta de usuarios
Se revisan los cambios realizados en el servicio de histórico roles para el conteo de los datos en la paginación.

Se inicia la implementación en el componente de consulta usuarios para complementar la tabla con la paginación 

![Captura de pantalla 2024-08-23 a la(s) 9 48 46 a  m](https://github.com/user-attachments/assets/d2566f38-cb02-4dbd-9165-1b4423c3454c)

![Captura de pantalla 2024-08-23 a la(s) 9 48 37 a  m](https://github.com/user-attachments/assets/d2e2b8d9-350a-4788-8e75-60304533b504)

Se tiene un problema con la paginacion, ya que al hacer click en siguiente se cambian los valores y no se realiza de la forma correcta:

![Captura de pantalla 2024-08-23 a la(s) 9 49 12 a  m](https://github.com/user-attachments/assets/b6dafd59-b5cc-4a91-8c08-143a9c66dbac)

**Comment by alexhrr** [comment]
### Implementación paginacion

Se realizan ajustes en los modelos de autenticación mid para almacenar el count de historico roles en metadata, sin embargo, no se logra traer el valor al microservicio, se comenta el problema en el daily y se acuerda una revision posterior en el microservicio.

Se realizan cambios en el microcliente para ajustar los valores de la paginacion pero no se logra que se muestren los datos correctamente y se continua teniendo el problema con los cambios en los datos de la paginación, se decide tomar el valor del conteo directamente mientras se soluciona lo del microservicio, para hacer pruebas de la paginacion con el valor total de los registros.

**Comment by edwargl7** [comment]
Se continuará el desarrollo con la Issue #145 y se espera resolver la dependencia del paso de metadata entre el microservicio de histórico y autenticación mid.
