### ISSUE TITLE
Implementación metadata endpoints GetAll microservicio Histórico de roles de usuario

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#136]
Se requiere realizar la implementación en los endpoints de tipo GetAll para obtener metadata sobre la cantidad de registros existentes basado en los filtros aplicados (si existen) que permita al servicio consultante identificar cuantos registros totales existen para establecer por ejemplo una cantidad clara de paginas.

**Sub Tareas**

- [x] Implementación de campo de metadata con información útil para paginado en el endpoint de periodos GetAll.
- [x] Implementación de campo de metadata con información útil para paginado en el endpoint de periodos GetAll con filtro por documento de identidad.
- [x] Pruebas funcionales en los endpoints que permitan validar el correcto paginado y metadata.

**Criterios de aceptación**

- [x] Documentación de la Issue e implementación de metadata para los endpoints mencionados.

**Requerimientos**

- Confirmar con otros equipos el manejo actual de paginado en los microservicios dado que se hace necesario agregar un campo adicional de Metadata.

**Material de apoyo**
- [Pattern: Pagination](https://microservice-api-patterns.org/patterns/quality/dataTransferParsimony/Pagination)

**Especificaciones técnicas**
- Repositorio microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se incluye query para consuilta de cantidad de registros modelo GetPeriodosBySistemaId
![Image](https://github.com/user-attachments/assets/61cff7f5-f422-46ed-945b-b6d677becd57)


se hace uso de qs.Count() del orm para cantidad total de registros antes de los parametros de limit y offset
![Image](https://github.com/user-attachments/assets/ba66daaf-dbe0-41a1-acbe-30480aadd3d8)

los modelos adecuados retornan ademas 'total' para la cantidad de registros
```go
return ml, total, nil
```

se adecua capa servicio para aceptar el nuevo retorno 

se adecuan controladores para devolver en el body el registro

![Image](https://github.com/user-attachments/assets/f7941e08-4a3e-43cf-acea-844347977f61)


```go
      c.Data["json"] = map[string]interface{}{"Count": count, "Success": true, "Status": 200, "Message": "Petición exitosa", "Data": result}
```

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

endpoint periodos-rol -usuarios
![Image](https://github.com/user-attachments/assets/8eb75709-b8ed-45bb-bdb4-b7c483b64592)


aplicando limit y offset para verificar que traiga la cantidad total de registros
![Image](https://github.com/user-attachments/assets/9f1084cc-9dd1-4821-a450-296a76037b27)

---

endpoint usuarios/:documento/periodos
![Image](https://github.com/user-attachments/assets/916c41d2-af23-4e67-aaf3-ad1ab0efb700)

aplicando limit y offset
![Image](https://github.com/user-attachments/assets/13bcacb1-e42f-4f1c-85ae-79c7a124c3bf)

aplicando query=sistema_informacion
![Image](https://github.com/user-attachments/assets/70e089eb-3a14-491c-a093-801ccaf71388)

aplicando limit y offset con el query
![Image](https://github.com/user-attachments/assets/e86f3e01-ed30-4ffd-ad6b-98c509038d98)

**Comment by jucastro94** [comment]
se modifica para que count este dentro de objeto metadata


![Image](https://github.com/user-attachments/assets/b4932181-9faf-47b3-962c-5405143150d5)



![Image](https://github.com/user-attachments/assets/238edbd0-4356-4ad0-b024-515f13833ed3)

**Comment by edwargl7** [comment]
Revisado el código, se resuelve el PR. Buen trabajo.
