### ISSUE TITLE
Implementación microcliente Plan anual de auditoría - Registro de actividades - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#137]
Se requiere completar la implementación del componente del paso 2 del Mockup iniciada en la Issue #122. 
![image](https://github.com/user-attachments/assets/44560bbc-6665-4beb-8a1e-87c6cf233d55)

**Sub Tareas**

- [x] Implementación microcliente plan anual de auditoría base.
- [x] Implementación componente de registro de actividades.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas de la correcta visualización del componente basado en el Mockup.

**Requerimientos**

No aplica

**Material de apoyo**
- [Mockup de Plan anual de auditoría](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EaCqT0N5_TtHvrjg5ZA7t9sBINcYGuefrq3aTtg2SFwpyQ?e=tCrnvA).
- Repositorio de microcliente de [gestion_contractual_compras_contrato_mf](https://github.com/udistrital/gestion_contractual_compras_contrato_mf) con implementación de módulos por cada paso del stepper.

**Especificaciones técnicas**
1. Repositorio microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan correcciones en importaciones de moduilos y componente,

se evidencia implementacion de cliente en el root, con maquetado inical
![Image](https://github.com/user-attachments/assets/0a625b06-0422-462b-b52d-067261dfa868)

**Comment by jucastro94** [comment]
se hace cambio de puerto para ejecctar desde root y se realiza merge con los cambios correctivos realizados por @CristianCGutierrezG 

vista previa


![Image](https://github.com/user-attachments/assets/7b46fe77-c193-4902-abd9-0db9f6e3cfab)

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/9f72648f-6181-4197-8bee-3bbba6c67f3a)

**Comment by jucastro94** [comment]
se realizan ajustes para el correcto funcionamiento de  mat-stepper

![Image](https://github.com/user-attachments/assets/d0b1400e-6442-4231-adc0-6f260db27130)

**Comment by edwargl7** [comment]
Se complementa la revisión de código, ajustar título columna auditoría.
Pendiente resolver conflictos en el PR.
![image](https://github.com/user-attachments/assets/183d83c1-273c-4b09-92a0-6ed6163df462)

**Comment by jucastro94** [comment]
se corrigen palabras 

![Image](https://github.com/user-attachments/assets/d204470b-79cb-44b9-a4f6-a79395ed863e)
