### ISSUE TITLE
Apoyo estructura microservicio mid para almacenado de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#138]
Se requiere realizar la revisión y planteamiento inicial del microservicio mid para estructuración dinámica de los datos del microcliente de formularios dinámicos y el almacenamiento en base de datos por medio del microservicio CRUD.
El modelo de datos asociado se trabaja en la Issue #96.

**Sub Tareas**

- [x] Apoyo en la revisión de estructura de datos obtenida de los microclientes y transformación requerida para envío a microservicio MID y CRUD.
- [x] Dado que al tenerse un microcliente cuya funcionalidad debe permitir la creación de formularios dinámicos se debe analizar la lógica implementada en la estructuración del objeto JSON con los datos capturados por el microcliente y como poder implementar la lógica de transformación en un microservicio MID para disminuir la lógica en el microcliente.

**Criterios de aceptación**

- [x] Documentación de la Issue con la definición inicial del microservicio mid con enfoque de la arquitectura pizarra.

**Requerimientos**

No aplica

**Material de apoyo**
- [Investigación Arquitectura de Pizarra](https://github.com/udistrital/sisifo_documentacion/issues/92)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
###  Apoyo microservicio mid

Se realiza una reunion con Cristian para evaluar las posibilidades de implementar un microservicio para el manejo del almacenamiento de datos de los formularios dinámicos.

Inicialmente se realiza la contextualización del proceso que se ha llevado y las necesidades que se tienen, asi como el flujo que se tiene previsto para la implementación de los formularios.

Posteriormente procedo a informar el proceso que se lleva actualmente con los microservicios en los que he trabajado para encontrar temas relacionados que se puedan llevar a cabo de la misma forma.

Realizado el análisis se plantea como acercamiento inicial el siguiente diagrama para implementar el microservicio que se encargue de manejar la lógica para el almacenamiento de los datos.

![image](https://github.com/user-attachments/assets/c14d6d8d-3178-44d5-b5c7-d215e20c1fcd)

Para llevar a cabo la implementación del mid se debe tener en cuenta que la información que se va a almacenar puede cambiar y por lo tanto el mid debe poder recibir diferentes tipos de información dependiendo de las versiones de los formularios dinámicos, actualmente los microservicios que he manejado tienen definida previamente la data que se envía a las consultas y la que se recibe, se crean los modelos específicos para  esta información y se hace uso de la misma de acuerdo a lo que se requiera.

Se debe realizar una revision de como recibir y enviar información de forma dinámica en el microservicio que se va a crear para poderlo implementar en el uso de los formularios dinamicos.

**Comment by edwargl7** [comment]
Buen trabajo en este primer acercamiento, a medida que se avance en el desarrollo del microcliente se podrá establecer y tener más insumos para ir refinando este flujo de datos.
