### ISSUE TITLE
Diseñar el mockup para el submódulo auditoría interna, con vistas según roles de usuario

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#139]
Se requiere continuar con el diseño del mockup para el submódulo auditoría interna, con vistas según roles de usuario

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el submódulo ejecución >> auditorías internas - rol inicial del auditor. mañana 23 de agosto se terminará de desarrollar mockup de vista rol jefe de oficina de control interno.

![Image](https://github.com/user-attachments/assets/5a990d70-4ea4-4657-afca-4dcce6542d92)



Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrollan diseños de mockups para las vistas del módulo ejecución >> auditorías internas desde los roles del auditor, jefe de la oficina OCI y el rol del auditado. Para el siguiente sprint se proyecta diseñar mockups de la fase final de la auditoría interna.

**Mockup Módulo Ejecución >> Auditorías Internas Rol Auditor (a)**
![Image](https://github.com/user-attachments/assets/f77f240f-62e1-417d-ac2c-3e53af5da65c)

**Mockup Módulo Ejecución >> Auditorías Internas Rol Jefe OCI**
![Image](https://github.com/user-attachments/assets/edab02f6-8005-47db-bb78-4f9c6114bc8b)

**Mockup Módulo Ejecución >> Auditorías Internas Rol Auditado**
![Image](https://github.com/user-attachments/assets/865a0540-563c-45f3-b6ce-cfdb47c0dcb8)

Enlace archivo guardados en OneDrive en la carpeta del proyecto SISIFO V2
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EhyOSasUiupArNZTGv8vsJYBeTHrB8KAT8B-N5LOqElJKg?e=vbkRCw


Saludos.

**Comment by jcmurilloa** [comment]
Ecelente diseño, se complementará la vista de auditado en el sigueinte sprint!
