### ISSUE TITLE
Implementación mejoras endpoints de consulta de periodos por sistema - histórico roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#140]
Se requiere realizar mejoras en la implementación realizada en la Issue #121 para evitar la inyección SQL.

**Sub Tareas**

- [x] Implementación usando lista de parámetros adicional al SQL string para ser enviados a la función raw y delegar la responsabilidad para evitar inyección de SQL en las peticiones.
- [x] Pruebas funcionales del correcto funcionamiento.

**Criterios de aceptación**

- [x] Documentación de la Issue con implementación y resultado de las pruebas.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan cambios en modelo de periodo_rol_usuario,  en metodo GetPeriodosBySistemaId para evitar inyeccion SQL


![Image](https://github.com/user-attachments/assets/8487e52d-1d29-44f1-825c-18fb3fbcd763)

![Image](https://github.com/user-attachments/assets/0a91dcab-f0c8-42c0-8c6b-fe4ec4d8e3a1)

![Image](https://github.com/user-attachments/assets/adfea753-fd4a-4af7-b3a1-e30d1d15c4a0)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales
![Image](https://github.com/user-attachments/assets/e33f8a49-ffa4-4234-97c0-a0c7e9623b20)


![Image](https://github.com/user-attachments/assets/ea07b245-27c1-42d6-845d-5ca8e47fa37c)


![Image](https://github.com/user-attachments/assets/ac2ecbf1-b8bb-44ac-a4a2-4e7bfffd9cd8)



![Image](https://github.com/user-attachments/assets/590da889-1cda-4c50-a296-d429a2c97121)



![Image](https://github.com/user-attachments/assets/7e8ecf96-0ea3-4cc0-a721-d1001dcd4ce3)

**Comment by edwargl7** [comment]
Se resuelve el PR. Completado refactorización para evitar inyección SQL.
