### ISSUE TITLE
Diseñar el mockup para el submódulo auditoría interna, con vistas de respuesta por parte de la dependencia auditada

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#141]
Se requiere continuar con el diseño del mockup para el submódulo auditoría interna, con vistas de respuesta por parte de la dependencia auditada.

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla diseños de mockup del submódulo ejecución >> auditoría interna - fase final revisión respuesta preliminar del auditado y elaboración y aprobación del informe final, roles de auditor y jefe OCI.

**Fase Final Auditoría Interna Rol Auditor**
![Image](https://github.com/user-attachments/assets/70b35afa-91c8-40e6-85fd-dd468d51e69b)


**Fase Final Auditoría Interna Rol Jefe OCI**
![Image](https://github.com/user-attachments/assets/66187387-e29d-4ba8-a8c6-e8ca2f972b93)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Ejecuci%C3%B3n/Subm%C3%B3dulo%20Auditorias%20Internas?csf=1&web=1&e=U5675d


Saludos.

**Comment by jcmurilloa** [comment]
Excelente diseño @cjgonzalezp, lo revisaremos detenidamente en el review de hoy.

**Comment by jcmurilloa** [comment]
Tener en cuenta la observación relacionada con la notificación de correo electrónico, en la captura inicial de pantalla.

**Comment by cjgonzalezp** [comment]
Buen día,

Se ajusta notificación inicial de correo electrónico y se presenta diseño de mockup del submódulo auditoría interna con las vistas de los roles involucrados en el proceso. Se recibe aprobación bajo el **acta No 145/2024** para el desarrollo del módulo en el sistema SISIFO V2.

![Image](https://github.com/user-attachments/assets/8f4f7a04-b759-4056-8d9e-fa630b48f8f6)


**Enlace acta de reunión No 145/2024 SISIFO - Levantamiento de requerimientos**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Lqccbu

Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp, muy buen diseño.
