### ISSUE TITLE
Ajustes endpoints de consulta de periodos en autenticación mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#142]
Se requiere realizar ajustes en los endpoints de consulta de periodos de un usuario en autenticación que tenga la misma estructura de consulta con el parámetro **query**, adicional para el endpoint de consulta se requiere agregar los parámetros _limit_ y _offset_ para un correcto paginado.

**Sub Tareas**

- [x] Ajuste variable de SISTEMA_INFORMACION del microcliente por SISTEMA_INFORMACION_ID.
- [x] Ajuste microcliente para consulta con parámetro _query_.
- [x] Ajuste endpoints de consulta de periodos en el microservicio de autenticación para consulta con parámetro _query_.
- [x] Ajuste endpoint consulta por documento para agregar _limit_ y _offset_.

**Escenarios de pruebas**
- [x] Filtrado correcto en el endpoint de consulta de periodos.
- [x] Filtrado correcto en el endpoint de consulta de periodos por documento de identidad incluyendo paginado (limit y offset).

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales realizadas.

**Requerimientos**

No aplica

**Material de apoyo**
- 

**Especificaciones técnicas**
1. Repositorio microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid)
2. Repositorio microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
3. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
4. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
5. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Ajuste endpoints 

Se realiza el cambio de la variable del sistema de información:

![Captura de pantalla 2024-08-26 a la(s) 10 30 33 p  m](https://github.com/user-attachments/assets/388f6895-60ac-4d4a-b682-7f3b547ba09f)

Se realiza el ajuste en el microcliente y en autenticacion_mid para enviar y recibir el sistema de información como parámetro query dentro de la consulta:

Microservicio:

![Captura de pantalla 2024-08-26 a la(s) 10 33 26 p  m](https://github.com/user-attachments/assets/4a752c58-7804-4024-897e-45e272b2aab2)

![Captura de pantalla 2024-08-26 a la(s) 10 33 56 p  m](https://github.com/user-attachments/assets/7051d8c9-9e11-4c43-9558-4bd89ec64d90)

![Captura de pantalla 2024-08-26 a la(s) 10 34 43 p  m](https://github.com/user-attachments/assets/c87d84f0-d825-47d5-bb97-5b9e3667d1dc)

Microcliente:

![Captura de pantalla 2024-08-26 a la(s) 10 36 03 p  m](https://github.com/user-attachments/assets/29f45d65-8eec-4e0b-a25f-3a81557301f3)

En la consulta del cliente se obtienen los resultados solicitados mostrando los usuarios que pertenecen al sistema de información 1.

**Comment by alexhrr** [comment]
### Ajuste endpoints consulta periodos

Se realiza la implementación del limit y offset para la consulta filtrando por documento de identidad ya que no se tenia implementada.

Tambien se ajusta la consulta para el query de sistema de información:

![Captura de pantalla 2024-08-27 a la(s) 7 50 52 p  m](https://github.com/user-attachments/assets/90006e21-38b2-4761-80a9-1d88b2ec1788)

![Captura de pantalla 2024-08-27 a la(s) 7 51 48 p  m](https://github.com/user-attachments/assets/8a0f93a4-44b0-45fa-bb01-d58bff7bf320)

Para la consulta sin filtro de documento de identidad se ajusta el query para el sistema de información:

![Captura de pantalla 2024-08-27 a la(s) 7 56 59 p  m](https://github.com/user-attachments/assets/a7e8a410-4c2a-481e-9191-67cdb4ea0240)

Así mismo se realizan los cambios necesarios en el microcliente para implementar los cambios mencionados anteriormente y se dejan funcionando correctamente, no se toman capturas debido a que se nuestra la información personal de los usuarios usados para las respectivas pruebas.

**Comment by edwargl7** [comment]
Agregar por favor swagger, actualizar app.conf y README para el despliegue.

**Comment by edwargl7** [comment]
Se observa que en la función consumida para la búsqueda por documento de identidad desde el HTML se tiene los valores por defecto, para el paginado debe tener presente los valores del paginado en cada consulta (campos por default del paginador).
![image](https://github.com/user-attachments/assets/ff0f1824-ea12-4780-bef4-884e6842a15f)

Se realiza la revisión del PR en [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf) y se observa una correcta implementación.

**Comment by edwargl7** [comment]
Se observa en el microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) una correcta implementación. revisar la imagen adicional subida al repositorio.
![image](https://github.com/user-attachments/assets/4601f214-9be0-48cb-9c1d-c6c9c30beafe)
Aunque existen otras se debe revisar realmente la necesidad de estas imágenes.

Se finaliza la Issue muy buen trabajo.
