### ISSUE TITLE
Implementación Metadata en endpoints de consulta de periodos en autenticación MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#143]
Se requiere realizar la implementación en autenticación MID, dado que actualmente los endpoints usan el formato de respuesta de la librería util_oas la cual cuenta con la siguiente estructura 
![image](https://github.com/user-attachments/assets/398c028f-b223-48b9-b3ca-a1b22bef9063). 

Por lo tanto, se requiere realizar la implementación para poder enviar la nueva estructura sin afectar los endpoints actuales.

```json
{
   "Metadata":"metadata",
   "Success":"success",
   "Status":"statusCode",
   "Message":"message",
   "Data":"data"
}
```

**Sub Tareas**

- [x] Implementación nueva estructura de respuesta de endpoints tipo GetAll con Metadata.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales realizadas.

**Requerimientos**

- Validación con arquitecto para realizar los cambios en la estructura.

**Especificaciones técnicas**
1. Repositorio microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza clonacion de repositorio autentificacion_mid en local
![Image](https://github.com/user-attachments/assets/3db2f058-8534-4246-abd3-9bd59ec78027)

**Comment by jucastro94** [comment]
se realiza clonacion de utils_oas, queda pendiente informacion sobre desde que rama trabajar

**Comment by edwargl7** [comment]
Se debe trabajar desde la rama master.

**Comment by jucastro94** [comment]
util_oas

se crea modelo adicional para recibir la metadata
![Image](https://github.com/user-attachments/assets/d7d5db45-37ef-48fc-a6ad-722c7336a39d)

se crea funcion 
![Image](https://github.com/user-attachments/assets/e066f10e-ef5b-438e-8b55-ca76417d1607)

**Comment by jucastro94** [comment]
se modifica metodo getAll, autentificacion_mid
![Image](https://github.com/user-attachments/assets/305a62c8-75f7-4f3c-a067-2618f5990bae)

**Comment by jucastro94** [comment]
se realiza prueba funcional

![Image](https://github.com/user-attachments/assets/c7da5b43-d04c-4f1e-a359-5e896bb307de)

**Comment by edwargl7** [comment]
Validar nuevamente por favor el correcto funcionamiento una vez resuelto el PR en utils_oas.

**Comment by edwargl7** [comment]
Aprobado el PR de utils, puedes validar nuevamente por favor.

**Comment by jucastro94** [comment]
se valida actualizando go.mod y go.sum para verificar que los cambios en util_oas se esten ejecutando correctamente


![Image](https://github.com/user-attachments/assets/efd8891d-3509-4311-a19d-94e08c0ed70f)

![Image](https://github.com/user-attachments/assets/ce4c558e-6ad1-4663-a4b0-d2865e43e42f)

**Comment by edwargl7** [comment]
Tener presente los lineamientos en la documentación del PR y la referencia como comentario a la Issue en el mismo.
![image](https://github.com/user-attachments/assets/5c93cbdd-d883-4b1a-a70b-c4d6e4e36e43)

Muy buen trabajo y completadas las pruebas necesarias para garantizar el correcto funcionamiento de la nueva función de util_oas.

**Comment by edwargl7** [comment]
Se deben resolver conflictos para poder realizar el PR.
![image](https://github.com/user-attachments/assets/e3b72cf6-65df-4c31-9e81-bd06e5d0e2a1)

**Comment by edwargl7** [comment]
Se resuelve el PR validar el correcto funcionamiento por favor.
