### ISSUE TITLE
Investigación cargue masivo de auditorias/actividades

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#144]
Se requiere realizar la investigación para crear un microservicio que permita procesar el cargue masivo de actividades del plan anual de auditoría.

**Sub Tareas**

- [x] Investigación tecnología a emplear para cargue masivo de actividades.

**Criterios de aceptación**

- [x] Documentación de la investigación realizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se encuentra tecnologia [excelize](https://xuri.me/excelize/es/pivot.html#DeletePivotTable), libreria de go, compatible apartir de la version 1.18, presenta algunas incopatibilidades en la version go 1.21, permite crear y leer archivos con formatos ( XLAM / XLSM / XLSX / XLTM / XLTX), en la parte de lectura  de documento, permite la lectura y validacion de valores asi como tambien del formatos por cada registro/celda

**Comment by jucastro94** [comment]
se encuentra tecnologia para trabajar con librerias de node js, [exceljs](https://www.npmjs.com/package/exceljs?activeTab=readme#reading-xlsx) y [xlsx](https://www.npmjs.com/package/xlsx) 


-xlsx
   Optimizado para leer y escribir grandes archivos Excel rápidamente
   Menor uso de memoria, especialmente útil para archivos grandes.
   soporta formatos XLSX, CSV, XML
   Capaz de leer, escribir y modificar datos en hojas de cálculo.
   Soporta la creación y manipulación de hojas, filas y celdas.
   Capaz de manejar archivos de Excel que contienen fórmulas.

-exceljs
  Soporte para la validación de datos y protección de hojas/celdas.
  Soporte robusto para la manipulación avanzada de datos, incluyendo la unión y fusión de celdas.
  Soporte para proteger hojas y celdas con contraseñas.
  Menor rendimiento comparado con xlsx en archivos muy grandes, debido a su enfoque en la personalización y capacidades avanzadas.
  Mayor uso de memoria
  soporta formatos  XLSX y CSV
  MIT License, lo que permite su uso en proyectos comerciales y de código abierto.

**Comment by jucastro94** [comment]
se encuentra tecnologia para python [openpyxl](https://openpyxl.readthedocs.io/en/stable/#documentation), [informacion util de openpyxl](https://www.datacamp.com/es/tutorial/python-excel-tutorial) y [pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) 


-openpyxl
Puede leer y escribir archivos XLSX, incluyendo la manipulación de hojas, celdas y estilos.
Capaz de leer y escribir celdas con fórmulas.
Puede agregar validaciones de datos a celdas (ej., listas desplegables, restricciones de rango, etc.).
Capacidad para proteger hojas y celdas con contraseñas.
Puede ser más lento y consumir más memoria al trabajar con grandes volúmenes de datos.
Curva de aprendizaje más pronunciada si se necesitan funcionalidades avanzadas.
Principalmente soporta archivos XLSX.
No tiene soporte directo para otros formatos como CSV.

-pandas
 Utiliza funciones como pd.read_excel() y DataFrame.to_excel() para leer y escribir archivos Excel.
permite convertir un DataFrame a un objeto JSON usando .to_json(). Permite personalizar el formato JSON según lasnecesidades (por ejemplo, orientado a registros, columnas, etc.).
 permite verificar y convertir tipos de datos, como asegurar que ciertas columnas contengan solo números (pd.to_numeric()), fechas (pd.to_datetime()), o texto (astype(str)).
detecta valores nulos  en cualquier columna utilizando .isnull() o .notnull(), para luego decidir cómo manejarlos (por ejemplo, llenarlos, eliminarlos, etc.). Asi como tambien valida listas, fechas, y tipos de datos
 Permite trabajar con grandes conjuntos de datos en estructuras tabulares.
Optimizado para manejar grandes conjuntos de datos, utilizando la memoria de manera eficiente.
No está optimizado para la manipulación detallada de archivos Excel, lo que puede hacerlo menos eficiente para tareas específicas de Excel.

**Comment by jucastro94** [comment]
Es posible que desde la plantilla se realize una validacion de datos, restringiendo la informacion que se diligencie mediante la[ aplicacion de reglas,](https://support.microsoft.com/es-es/office/aplicar-la-validaci%C3%B3n-de-datos-a-celdas-29fecbcc-d1b9-42c1-9d76-eff3ce5f7249#:~:text=Seleccione%20las%20celdas%20en%20las%20que%20desea%20que%20se%20muestre,que%20se%20compartiera%20el%20libro.), y avisando al usuario mediante una alerta, esto al configurar las reglas para impedir que se diligencie o se peguen datos no permitidos en las celdas segun su regla
Para el caso de las listas es posible generar una hoja que contenga el [origen ](https://support.microsoft.com/es-es/office/v%C3%ADdeo-administrar-listas-desplegables-6a62d474-b599-47f4-a31b-ae93258c6a57)de los datos a seleccionar, bloqueando esa hoja o esas celdas para evitar ser modificadas,

**Comment by jucastro94** [comment]
https://github.com/user-attachments/assets/70d9c1f0-141e-437c-81c9-24d5baf6d3e3

**Comment by edwargl7** [comment]
Muy buen trabajo, pendiente confirmar que se mantenga las validaciones en otras distro de SO

**Comment by edwargl7** [comment]
Se realiza la validación del archivo desde ubuntu y se confirma el correcto funcionamiento siempre y cuando no se realice el copiado de datos en esas celdas.
Se finaliza la Issue tomando como principales alternativas las mencionadas en JS y Python para un futuro desarrollo.
