### ISSUE TITLE
Implementación de paginación en submódulo de consulta de microcliente de gestión de usuarios - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#145]
Se requiere continuar con el desarrollo de paginado en la vista de consulta de periodos para el histórico de roles de usuario iniciada en la Issue #135. 

**Sub Tareas**

- [x] Implementación de paginado en la vista de consulta de periodos de usuario sin filtro.
- [x] Implementación de paginado en la vista de consulta de periodos de usuario con filtro.

**Escenarios de pruebas**
- [x] Pruebas con paginado sin filtro.
- [x] Pruebas con paginado con filtro.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Material de apoyo**
- Material con información de [Data table](https://v8.material.angular.io/components/categories/tables) con manejo de **Paginator**, **Sort Header** y **Table**.
- Material para [Table mat-table](https://v16.material.angular.io/components/table/overview)
- [Pagination](https://v16.material.angular.io/components/table/overview#pagination)

**Especificaciones técnicas**
1. Repositorio microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf/tree/develop)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance implementación paginacion

Se continua con la implementación de la paginacion en el microcliente para las consultas de los periodos.

Se establece directamente el valor de la cantidad de los registros para usarlos en la paginacion mientras se soluciona lo de autenticacion mid.

![Captura de pantalla 2024-08-28 a la(s) 11 17 17 a  m](https://github.com/user-attachments/assets/a4a3031d-0beb-40b1-99eb-2c4a4fa29f9c)

![Captura de pantalla 2024-08-28 a la(s) 11 16 56 a  m](https://github.com/user-attachments/assets/c73d4346-934e-4fa7-a642-b2bfff42f96b)

Se continua revisando ya que se deshabilitan los botones para cambiar de pagina:

![Captura de pantalla 2024-08-28 a la(s) 11 18 20 a  m](https://github.com/user-attachments/assets/d6d1ecc2-a25d-4323-8df0-4a059a1cd039)

**Comment by alexhrr** [comment]
Se continua con la revision de la paginacion y se realizan las modificaciones necesarias para ajustar el valor de "paginator.lenght" que se establece automaticamente con la data de la consulta, este dato se usa para establecer el total de los datos a mostrar en la paginacion.

Se modifica el valor de "lenght" en diferentes partes del codigo y se muestra por consola el cambio, a pesar de que se establece el nuevo valor, la paginacion no se modifica ya que se sobreescribe automaticamente

![Captura de pantalla 2024-08-29 a la(s) 9 31 53 p  m](https://github.com/user-attachments/assets/3943bb82-2ff2-4f20-b224-f26cc0e2f30b)

![Captura de pantalla 2024-08-29 a la(s) 9 32 13 p  m](https://github.com/user-attachments/assets/2d527eff-a256-4c47-ae74-2c2afa2fa1bc)

![Captura de pantalla 2024-08-29 a la(s) 9 32 42 p  m](https://github.com/user-attachments/assets/ee9bdd3e-7a6b-4c31-9116-faa68b8f41b4)

La tabla inicial muestra la cantidad de datos y permite pasar a la siguiente pagina:

![Captura de pantalla 2024-08-29 a la(s) 9 48 05 p  m](https://github.com/user-attachments/assets/b4db3ba6-3f15-4b35-95a9-85367b9a9da6)

Al cambiar la pagina, el valor de la cantidad de datos se modifica automaticamente y solo toma el valor de la consulta del limit, que en este caso es 2 y no permite continuar con otra pagina ya que se esta mostrando la cantidad total en la tabla:

![Captura de pantalla 2024-08-29 a la(s) 9 48 14 p  m](https://github.com/user-attachments/assets/75b010af-e67f-4a3c-9046-cc294e04f206)

Se consulta el problema y se tienen que probar algunas opciones que consisten en sobreescribir los metodos de mat paginator y ajustarlos los valores requeridos.

**Comment by alexhrr** [comment]
## Implementación paginacion

Se realiza la implementación en el submodulo de consulta de usuarios con y sin filtro

![Captura de pantalla 2024-08-30 a la(s) 5 16 53 p  m](https://github.com/user-attachments/assets/396176e0-6c19-45e2-8079-8f2437d4de87)

Se asignan por ahora los valores del total de registros en cada función, se realizará el ajuste cuando se implemente la consulta con la metadata

![Captura de pantalla 2024-08-30 a la(s) 5 17 07 p  m](https://github.com/user-attachments/assets/50b2e7fc-d190-44bb-a99d-d549abffb05a)

![Captura de pantalla 2024-08-30 a la(s) 5 17 16 p  m](https://github.com/user-attachments/assets/2876bdae-4747-478e-9f07-03c98a049d7b)

Para la consulta con filtro por documento de identidad se crea la siguiente función que reinicia la paginacion cuando se haga la consulta con el boton de la búsqueda

![Captura de pantalla 2024-08-30 a la(s) 5 15 30 p  m](https://github.com/user-attachments/assets/bf4d15bf-d9b9-422e-82e5-c2b046375668)
             
![Captura de pantalla 2024-08-30 a la(s) 5 17 38 p  m](https://github.com/user-attachments/assets/579ef32a-3b3c-4a4f-a7c8-acfc5943da84)

El tamaño de la data se asigna a la paginacion el el html

![Captura de pantalla 2024-08-30 a la(s) 5 17 50 p  m](https://github.com/user-attachments/assets/bc549939-803f-4c97-b431-6eb263a263b0)


### Pruebas de funcionamiento sin filtro:

Se tiene un total de 7 registros y según la configuración actual se muestran de a dos en cada pagina, se muestra correctamente el flujo de la paginacion en los datos:

![Captura de pantalla 2024-08-30 a la(s) 5 26 36 p  m](https://github.com/user-attachments/assets/a0dc1cc9-8728-47d0-8207-ee3aff14b011)

![Captura de pantalla 2024-08-30 a la(s) 5 26 45 p  m](https://github.com/user-attachments/assets/d59ef24f-eda4-4a3c-a13f-71b7da6117a8)

Se llega al final y se termina la paginación correctamente

![Captura de pantalla 2024-08-30 a la(s) 5 27 02 p  m](https://github.com/user-attachments/assets/b45a1955-5b07-4c6f-8673-a55296efb290)

### Pruebas de funcionamiento  con filtro:

Se realiza la búsqueda del documento de identidad y se tienen 3 registros con el documento, se muestran de a dos y se observa el correcto flujo en la paginacion de los 3 registros

![Captura de pantalla 2024-08-30 a la(s) 5 27 19 p  m](https://github.com/user-attachments/assets/489bf821-6e77-4b02-974b-2694b39f19c3)

![Captura de pantalla 2024-08-30 a la(s) 5 27 28 p  m](https://github.com/user-attachments/assets/cf3f493d-a6a5-4f69-9863-8c17d2ff5118)

**Comment by edwargl7** [comment]
Revisar comentario de la Issue #142 y revisar los valores quemados en el HTML de la función BuscarDocumento que deben ser tomados del valor del paginador para los casos en los que el usuario pueda cambiar el paginador por default.
![image](https://github.com/user-attachments/assets/e1722a1e-9cae-428c-bcaa-db26508ddf57)

**Comment by edwargl7** [comment]
Muy buen trabajo se resuelve el PR. Revisar comentarios.

**Comment by edwargl7** [comment]
Revisar que pasa al solicitar sin cambiar de página más elementos de los cargados por defecto.

**Comment by alexhrr** [comment]
### Pruebas paginación

Cuando se realiza la solicitud de más elementos a los cargados por defecto, haciendo uso del selector para ajustar la cantidad de elementos a mostrar por página, la consulta se actualiza y trae la cantidad de datos seleccionados.

En las pruebas realizadas se observa que se debe dejar establecido el mínimo valor de los items a mostrar previamente y que se debe dejar el mismo para el "limit" de la consulta inicial que viene por defecto al cargar la pagina, esto se debe a que cuando se carga la pagina inicial el paginador no tiene en cuenta el valor del "limit" establecido en la consulta, por lo tanto se muestra la cantidad de valores de la consulta y no de la paginacion.

Para el filtro por documento se encuentra que cuando se ha cambiado el tamaño de los items por página antes de realizar el filtro, la paginacion toma en cuenta el "limit" de la consulta y no el tamaño de la pagina por lo que muestra una cantidad diferente entre el valor del limit y el valor del selector en la tabla, se debe decidir como ajustar el valor de forma predeterminada en la consulta o en la paginación.

**Comment by edwargl7** [comment]
Se debe revisar agregar una variable para controlar el número de paginado para la consulta de documento en la primera consulta.
