### ISSUE TITLE
Investigación integración microcliente en formulario

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#146]
Se requiere realizar la investigación de la posibilidad de integrar un microcliente en un paso especifico de un formulario. Esto es requerido para el paso de registro del plan anual de auditoría.

**Sub Tareas**

- [x] Investigar como integrar un microcliente en el formulario de otro microcliente.

**Criterios de aceptación**

- [x] Documentación de la investigación y prueba de concepto.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Investigación integración microcliente

Se realiza una reunion junto a Juan Camilo y Heiner para evaluar diferentes posibilidades en la integración del microcliente, se menciona que se debe tener presente el single spa para esta integración, así como el root del aplicativo.
Las opciones actuales que se pueden tener en cuenta para la integración son las siguientes:

### Parcels 

Esta es la opción mas viable según lo informado en la reunion, se debe tener en cuenta el correcto funcionamiento con Angular ya que se desconoce si actualmente se puede trabajar con las versiones más recientes.

son microaplicaciones autónomas que se pueden montar y desmontar dinámicamente dentro de otras aplicaciones, se pueden insertar directamente en el DOM de cualquier componente o sección de la aplicación, lo que los hace más adecuados para casos en los que se necesita una integración muy puntual, tienen su propio ciclo de vida que se maneja de manera independiente y no es necesario cambiar la ruta o recargar la pagina.

Material para revisar y profundizar:

https://single-spa.js.org/docs/parcels-overview/

https://single-spa.js.org/docs/ecosystem-angular

### Dependencias compartidas

Son una técnica utilizada en aplicaciones de microfrontend para evitar la duplicación de librerías comunes entre diferentes microclientes, las aplicaciones comparten versiones de las dependencias para que se carguen solo una vez y sirva para todas.
Se usa principalmente para optimizar el tamaño y rendimiento de la aplicación, también ayuda a que todos los micro-frontends usen la misma versión de una biblioteca para evitar incompatibilidades.

Material para revisar y profundizar:

https://single-spa.js.org/docs/recommended-setup/#shared-dependencies

### Props

Son objetos que contienen claves y valores con la información necesaria y  que se pasa a un microfrontend o a un parcel desde la aplicación que lo aloja. Los props permiten la comunicación entre el microcliente y la aplicación host (o entre microclientes), facilitando el paso de datos de manera flexible.

### Conclusión

Para la integración de un microcliente en el formulario de otro microcliente la opción que cumple con estas necesidades es la del uso de parcels y dada la necesidad de pasar información entre los microclientes (id) se debe complementar con el uso de los props que permite la comunicación entre ellos.
Las dependencias compartidas quedan descartadas por el momento para esta implementación.

Según la investigación realizada, los parcels actualmente cuentan con compatibilidad para las versiones más recientes de Angular así que no se tendría problema con eso.

Se debe realizar un acercamiento más profundo a esta herramienta y proceder a probar las opciones de parcel junto a los props y aprender su funcionamiento para finalmente decidir si se cumple con la necesidad de la integración para el PAA.

**Comment by edwargl7** [comment]
Buena investigación, dado que en Sísifo existen más módulos que requieren un comportamiento similar se evaluará que alternativa permite una mejor manejo e implementación.
