### ISSUE TITLE
Refactorización eliminación lógica microservicio crud plantillas formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#147]
Se requiere realizar modificaciones en funciones de eliminación lógica que permitan tener una clara identificación de las funciones de eliminación lógica vs eliminación de BD.

**Sub Tareas**

- [x] Evaluar ajustes para la optimización de la cantidad de peticiones a la base de datos para la eliminación lógica de secciones y elementos por medio de la función updateMany. Issue asociada #123 .
- [x] Modificar nombres de funciones que permitan identificar claramente cuales son de eliminación lógica y cuales de BD. Issue asociada #127 .
- [x] Pruebas funcionales del correcto funcionamiento una vez realizados los ajustes.

**Criterios de aceptación**

- [x] Documentación de la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
## Refactorización en la Creación de Plantillas

Se encontró un error en el servicio `createTemplate` que causaba que la creación de nuevas plantillas siempre iniciara en la versión 2. Este problema surgía porque, para evitar errores en el manejo de la versión actual, el formulario se creaba primero y luego se reasignaba la versión, lo que provocaba un incremento innecesario en el número de versiones.

#### Soluciones Implementadas:

- Se optimiza el proceso para evitar el cambio de la versión actual si se presenta un error durante la creación de la plantilla. Ahora, la versión no se incrementa adicionalmente.

![image](https://github.com/user-attachments/assets/2169d043-d82d-44f7-a58b-6739df3b8935)
![image](https://github.com/user-attachments/assets/a077eb0a-d63a-4b19-821a-5a19d90c3919)

  
- El control de la versión actual se mantiene hasta que se completa correctamente la creación de la plantilla. 

![image](https://github.com/user-attachments/assets/0cfee126-35f4-48ee-b94b-7db940fea544)

Este refactor mejora el proceso de creación de plantillas, y reajusta las versiones antiguas solo si se presenta un error.

**Comment by CristianCGutierrezG** [comment]
## Refactorización de Eliminación Lógica

#### Optimización de Peticiones a la Base de Datos

Se optimizó la cantidad de peticiones a la base de datos durante la eliminación lógica de secciones y elementos. Ahora, se utiliza la función `updateMany` para realizar actualizaciones en masa.

![image](https://github.com/user-attachments/assets/194d3078-3fb7-4250-90a5-e9f50c47afd2)

#### Nueva Función para Manejo de Versiones

La lógica de la función `changeCurrentVersion` se ha dividido, creando una nueva función dedicada para manejar la actualización de la versión actual.

![image](https://github.com/user-attachments/assets/e6fca9dd-c527-4a29-9fec-76d83f12337f)


#### Actualización de Mensajes de Respuesta

- **Información de Cambio de Versión**: Los mensajes de respuesta ahora incluyen información detallada sobre el cambio de versión, indicando la nueva versión actual.

![image](https://github.com/user-attachments/assets/62907f7e-6dc6-40b8-b970-03ed23706001)

- **Notificación de Eliminación de Plantillas**: El sistema también informa si se ha eliminado la última plantilla con versión activa disponible.

![image](https://github.com/user-attachments/assets/9a77f568-32bf-4714-8f7b-9ae6fed10e28)

**Comment by CristianCGutierrezG** [comment]
### Funciones de Eliminación

Se han agregado nuevas funciones que permiten diferenciar claramente entre las operaciones de eliminación lógica y las eliminaciones directas en la base de datos.

![image](https://github.com/user-attachments/assets/7292793a-6f37-4a2c-b545-b10f5cc0f482)

![image](https://github.com/user-attachments/assets/fe5684e5-db37-4c83-a64c-de75b72bd34b)

**Comment by edwargl7** [comment]
Sobre la implementación descrita en la Issue
![image](https://github.com/user-attachments/assets/b5526c9d-593f-475d-b878-511f5e0de730)
Se observa que se establece el siguiente número de versión basado en el máximo registrado, aunque la operación con un menor tiempo de respuesta puede ser contar los elementos esta forma de calcular partiendo de un escenario en el que el crecimiento de versiones de dichos formularios no va a ser tan grande puede ser una buena opción. Además, garantiza tener una mayor seguridad en la secuencia del valor de la versión.

**Comment by edwargl7** [comment]
:wrench: Se puede reemplazar la eliminación de secciones modificando la búsqueda en lugar de las secciones que coincidan con dicha lista por las que coincidan con el id del formulario.
![image](https://github.com/user-attachments/assets/5ffa1df7-bd51-4ba8-beaa-e3214ac5de88)

**Comment by edwargl7** [comment]
Se resuelve el PR. Buen trabajo. Pendiente revisión comentario de ajuste en eliminación lógica de secciones.

**Comment by CristianCGutierrezG** [comment]
Se hace el cambio en la eliminación lógica de las secciones para hacer la actualizacion buscando las seciones relacionadas con el formulario_id

![image](https://github.com/user-attachments/assets/5086acbc-e5ea-46ee-a2af-c9981c46f6ff)

Tambien se realizan pruebas del correcto funcionamiento
![image](https://github.com/user-attachments/assets/ff9a3338-68b9-49e5-b0f0-9c9a227f5db2)

**Comment by edwargl7** [comment]
Completada.
