### ISSUE TITLE
Implementación microcliente formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#148]
Se requiere realizar el empalme con las pruebas de concepto y avances que se vienen implementando en el microcliente para la creación de formularios dinámicos.

**Sub Tareas**

- [x] Participación en la reunión de empalme.
- [x] Pruebas funcionamiento del microcliente de formularios dinámicos integrando con el root mf de Sísifo.
- [x] Pruebas de correcto renderizado del JSON presentado en la reunión de empalme.
- [x] Exploración del código.
- [x] Se asignaran más tareas del trabajo en conjunto con SGA.

**Criterios de aceptación**

- [x] Documentación de la Issue según corresponda.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Solicitar acceso al repositorio de formularios dinámicos mf.

**Comment by CristianCGutierrezG** [comment]
## Pruebas de Funcionamiento del Microcliente de Formularios Dinámicos

 **Clonación del Repositorio**: Se realizó la clonación del repositorio `formularios_dinamicos_mf`. Durante la instalación de dependencias, surgieron varios conflictos de versiones entre distintas dependencias.
Se utilizó el comando `--legacy-peer-deps` para solucionar los conflictos.

![image](https://github.com/user-attachments/assets/54d5e846-d177-4874-b24c-bdb33138350d)

**Actualización de Rutas**: Se actualizaron las rutas en `root-mf` de Sisifo para incluir el `formularios_dinamicos_mf`.

![image](https://github.com/user-attachments/assets/33ae61b4-3e00-40de-bd0d-71c27a47367b)

**Verificación del Funcionamiento**: Se evidenció el correcto funcionamiento del microfrontend y el renderizado adecuado del JSON presentado.

![image](https://github.com/user-attachments/assets/580e1c5d-1464-437c-b73a-302e775faf8d)

**Estilos del Microcliente**: El microcliente  inicialmente aparecio con los colores de SGA pero al revisitar la pagina adquiere los estilos de Sisifo.

![image](https://github.com/user-attachments/assets/ce281817-4df4-4cd0-b91b-42c72f36e357)


![image](https://github.com/user-attachments/assets/af760168-83f4-4250-ac2c-8c72c890d964)

**Comment by CristianCGutierrezG** [comment]
### Instalación y Pruebas del Microcliente de Formularios Dinámicos

**Instalación de Dependencias**: Se realizó la instalación de dependencias utilizando `npm i --force`. Esta vez la instalación se completó sin mayores inconvenientes.

**Revisión de Video y Código**: Se volvio a revizar la grabación de [Empalme avance front formularios dinamicos](https://udistritaleduco-my.sharepoint.com/personal/dfceliv_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fdfceliv_udistrital_edu_co%2FDocuments%2FGrabaciones%2FEmpalme%20avance%20front%20formularios%20dinamicos-20240826_170536-Grabación%20de%20la%20reunión%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E1bbbff20-d23d-4172-89f3-1bd3cb1b8355) y el código del proyecto para comprender mejor el funcionamiento del microcliente y el proceso de obtención de datos.

**Mock en Postman**: Se investigó y creó un mock propio en Postman para realizar pruebas más controladas y personalizadas.
![image](https://github.com/user-attachments/assets/32443df9-8475-4a28-83f7-89ab63c3a914)

**Conexión con `Parametros_crud`**: Se verificó que la lógica de conexión con el servicio `Parametros_crud` ya estaba implementada en el microcliente. Con esto en cuenta se realizó una prueba GET para traer los datos desde `Parametros_crud`, confirmando la correcta obtención de datos.

![image](https://github.com/user-attachments/assets/a5fd1002-8414-42b6-8075-e55ead7f4344)
![image](https://github.com/user-attachments/assets/0e170da5-7e45-49ad-8e56-07db89d708f3)

**Comment by CristianCGutierrezG** [comment]
## Integración de `parametros_crud` en Formularios Dinámicos

### Desarrollo
 **Función `processUrl`**: 
Se desarrolló una función para adaptar la URL recibida y verificar a qué servicio pertenece para realizar la solicitud correspondiente.

![image](https://github.com/user-attachments/assets/156eefaf-1fe0-4a49-b807-f67b38284451)
   
**Función `transformData`**: 
Se implementó esta función para tomar los datos obtenidos desde la URL y adaptarlos para su uso en formularios dinámicos, transformando los valores recibidos en campos como `valor` y `etiqueta`.

![image](https://github.com/user-attachments/assets/79dc1a7b-6dc2-41a3-9074-69aca4a600ff) 


### Pruebas

 ** Datos de `parametros_crud`**:

![image](https://github.com/user-attachments/assets/92cd6462-2456-49c9-a61c-caca8f1e6446)

![image](https://github.com/user-attachments/assets/24f652b7-6eff-40e7-906a-af73358e927b)

![image](https://github.com/user-attachments/assets/b971e7f4-b699-4588-930e-93812a48ce6c)

![image](https://github.com/user-attachments/assets/5083fbc3-531d-4c52-93a2-7e6808454854)

 **Pruebas con Datos de URL Mock**:

![image](https://github.com/user-attachments/assets/df8063b1-7190-4a73-8c80-dcabc0d04f3a)

![image](https://github.com/user-attachments/assets/b2f2c678-f81b-45aa-9bd1-b8f083d0f39b)

Se podría considerar agregar la opción para que el usuario seleccione el servicio y los datos a los que desea acceder directamente desde la interfaz de creación del formulario.

**Comment by edwargl7** [comment]
Buena exploración, la alternativa de contar con un componente que cuente con su propio service de parametros_crud, podría ser una buena alternativa dada la probabilidad de uso que podría optimizar el tiempo de parametrización requerido de este componente por el usuario. Sin embargo, es bueno contar con la posibilidad de una consulta genérica para posibles cambios o necesidad de integrar un servicio diferente.

**Comment by edwargl7** [comment]
Muy buen trabajo y tener presente propuesta para estos tipos de servicios que generalmente pueden ser requeridos.
