### ISSUE TITLE
Diseñar el mockup para el submódulo de seguimiento e informes, con vista de roles

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#149]
Se requiere elabborar el diseño del mockup para el submódulo de seguimiento e informes, con las vistas de cada uno de los roles que intervienen en el proceso.

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrollan diseños de mockup del submódulo de planeación >> seguimiento e informes con las vistas de los roles involucrados en el proceso.

**Rol Auditor**
![Image](https://github.com/user-attachments/assets/f5535efe-5cd4-4aa1-b1bd-17301c6cdf7c)

**Rol Jefe OCI**
![Image](https://github.com/user-attachments/assets/34d2e05c-8804-4dd6-8bc0-45509bd9f993)

**Rol Auditado (a)**
![Image](https://github.com/user-attachments/assets/c356eefe-003f-49c8-8d90-98f8f0cbb6cf)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Planeaci%C3%B3n/Subm%C3%B3dulo%20Seguimiento%20e%20Informes?csf=1&web=1&e=Xuteqa


Saludos.

**Comment by jcmurilloa** [comment]
Diseños muy completos @cjgonzalezp, los repasaremos en el review para aprobar y de esta manera quedar refinados para equipo de desarrollo.

**Comment by jcmurilloa** [comment]
Pendiente notificación inicial de correo electrónico según las plantillas aprobadas y mostrar al cliente para su aprobación.

**Comment by cjgonzalezp** [comment]
Buen día,

Se ajusta notificación inicial de correo electrónico y se presenta diseño de mockup del submódulo seguimiento e informes con las vistas de los roles involucrados en el proceso. Se recibe aprobación bajo el **acta No 145/2024** para el desarrollo del módulo en el sistema SISIFO V2.

![Image](https://github.com/user-attachments/assets/4d728ab9-a7db-4549-9500-bfa9cade065a)

**Enlace acta de reunión No 145/2024 SISIFO - Levantamiento de requerimientos**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Lqccbu

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp!
