### ISSUE TITLE
Pruebas correcto funcionamiento endpoints en el servicio de autenticacion_mid - Despliegue

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#150]
Se requiere realizar la validación del correcto funcionamiento previo al despliegue y una vez desplegado se realiza la validación del correcto funcionamiento tanto de los nuevos endpoints como los actuales que no fueron modificados.

**Sub Tareas**

- [x] Revisión correcto funcionamiento endpoint del grupo token.
![image](https://github.com/user-attachments/assets/181b8f21-29f6-40bf-ba10-fcda48921e80)
- [x] Revisión correcto funcionamiento endpoints de rol (agregar y remover)
![image](https://github.com/user-attachments/assets/f545754c-7b8e-4044-8610-f4b67239fe06)
![image](https://github.com/user-attachments/assets/ebb57f11-9472-4303-bb73-8427d16b0b43)

**Criterios de aceptación**

- [x] Documentación de la Issue con las pruebas que puedan ser registradas sin exponer datos sensibles.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Pruebas previo al despliegue

Se realiza la validación de cada endpoint en el servicio autenticación_mid antes de realizar el despliegue:

### documentoToken

![DocumentoToken](https://github.com/user-attachments/assets/b3496104-f626-483a-8125-20ba84446f15)

### emailToken

![emailToken](https://github.com/user-attachments/assets/d243a696-ab6d-4456-9d0d-28b70d0ec222)

### userRol

![UserRol](https://github.com/user-attachments/assets/560daa0d-7ad2-4452-9fe2-466e189d409d)

### rol/remove

Se elimina el rol "AUDITOR" al usuario

![RemoveRol1](https://github.com/user-attachments/assets/8e980c0d-a988-45c1-a575-ae6c7d86a59e)

![RemoveRol2](https://github.com/user-attachments/assets/3119fb09-e604-4236-ba83-d54f916b2fa5)

Se verifica con una nueva consulta que el rol se haya eliminado correctamente:

![RemoveRol3](https://github.com/user-attachments/assets/02c90f02-839f-4ca9-a101-ca17f5125fab)

### rol/add

Se agrega nuevamente el rol "AUDITOR" al usuario

![AddRol1](https://github.com/user-attachments/assets/2191958d-d5ad-476c-a6f6-0b793493d354)

![AddRol2](https://github.com/user-attachments/assets/4c0e93b0-bcf1-4411-80f9-e113e5c73e9d)

Se verifica con una nueva consulta que el rol se haya agregado correctamente:

![AddRol3](https://github.com/user-attachments/assets/0b7c1e78-c9e1-40a3-86bf-d41a24d96694)


## Pruebas posterior al despliegue

Se realiza la validación de cada endpoint en el servicio autenticación_mid después de realizar el despliegue:

### documentoToken

![DocumentoToken](https://github.com/user-attachments/assets/77213c3e-9d39-4023-8b03-7dde0d765f61)

### emailToken

![emailToken](https://github.com/user-attachments/assets/d184a1ca-93a2-4d30-9963-5a6df03af4d6)

### userRol

![UserRol](https://github.com/user-attachments/assets/05af6c9d-16b9-4b84-b1ce-26f875223e54)

### rol/remove

Se elimina el rol "AUDITOR" al usuario

![RemoveRol](https://github.com/user-attachments/assets/d104e82f-9811-40db-91d8-6f00279a796f)

Se verifica con una nueva consulta que el rol se haya eliminado correctamente:

![RemoveRol2](https://github.com/user-attachments/assets/e697b554-5f0a-4869-b487-b06b62d39387)

### rol/add

Se agrega nuevamente el rol "AUDITOR" al usuario

![AddRol](https://github.com/user-attachments/assets/62c3d136-4d0e-4e86-821c-13f8f4a26845)

Se verifica con una nueva consulta que el rol se haya agregado correctamente:

![AddRol2](https://github.com/user-attachments/assets/9cd2d5ab-0e79-4678-8fb2-50cedee9f61a)

Después de realizar las respectivas pruebas de funcionamiento se evidencia que los endpoints del servicio autenticacion_mid funcionan correctamente antes y después del despliegue.

**Comment by edwargl7** [comment]
Muy buena revisión, se garantiza el correcto funcionamiento del servicio luego del despliegue.
