### ISSUE TITLE
Ajustes microservicio histórico usuarios roles para despliegue

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#151]
Se requiere realizar ajustes en el repositorio del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) para su despliegue en el ambiente de pruebas.

**Sub Tareas**

- [x] Actualización modelo de datos en el repositorio y almacenado en el mismo repositorio.
- [x] Eliminación de archivos relacionados al swagger diferentes al swagger.json y swagger.yml.
- [x] Ajuste en los script .go relacionados a las migraciones que tengan comentada la línea de código relacionada a la migración de beego y la nota de la razón por la que se comenta.

**Criterios de aceptación**

- [x] Documentación de la Issue con los ajustes sugeridos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se valida ultima version y se carga modelo de datos en proyecto, .PNG y .draw


![Image](https://github.com/user-attachments/assets/49e51092-2d07-4ce6-a686-d7569c1277df)

se direcciona a modelo de datos del proyecto en el README


![Image](https://github.com/user-attachments/assets/b83a2dfd-762a-4257-b0f2-cea968b4ac93)

**Comment by jucastro94** [comment]
se realiza la eliminacion en cache de archivos de swagger, se conservan swagger.json y swagger,yml


![Image](https://github.com/user-attachments/assets/b5bf5042-22ff-4843-9651-f02d28f69cbb)

**Comment by jucastro94** [comment]
se elimina en migracion de creacion de tablas linea de autorizacion


![Image](https://github.com/user-attachments/assets/3350f0f6-c469-482b-ac8b-d6143b09cd91)

se deja nota de la razon por la cual se comentarean las migraciones y se proceden a comentarear todas las migraciones


![Image](https://github.com/user-attachments/assets/d5d44004-6e1f-44bc-8ee2-b2bc3a63e88a)

**Comment by jucastro94** [comment]
se cambia de nombre de ´pruebas.env a example.env y se ajustan los nombres de las variables de entorno


![Image](https://github.com/user-attachments/assets/714a462d-113e-4736-9674-9a8c3914d29a)



![Image](https://github.com/user-attachments/assets/08086bcb-1e52-4a06-809e-91e186af4870)

**Comment by jucastro94** [comment]
se realiza prueba funcional



![Image](https://github.com/user-attachments/assets/69ec32ca-3abd-4dea-a04f-ae6fdaa7fc1f)


![Image](https://github.com/user-attachments/assets/d9d10443-1a63-4161-904a-fd029c3272fd)

**Comment by edwargl7** [comment]
Buen trabajo, antes de finalizar la Issue se debe:
- Remover y agregar en el gitignore el compilado (crear rama nueva desde develop el PR fue resuelto dado que cumple con los cambios solicitados).
![image](https://github.com/user-attachments/assets/130daf71-d34e-4891-8c36-920500ed566b)

**Comment by edwargl7** [comment]
Ajustes realizados correctamente.
