### ISSUE TITLE
Implementación de roles en microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#152]
Se requiere realizar la implementación de permisos basado en la matriz de roles para el microcliente de gestión de usuarios.

**Sub Tareas**

- [x] Implementación separada de roles que pueden consultar (variable de entorno con array de ids).
- [x] Implementación separada de roles que pueden crear/actualizar (variable de entorno con array de ids).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de la implementación que cumpla los permisos de consulta y creación/edición.

**Requerimientos**

No aplica

**Material de apoyo**
- Lista de permisos según el rol.
[Gestion.de.Usuarios.-.Modulos.y.Permisos.pdf](https://github.com/user-attachments/files/16839400/Gestion.de.Usuarios.-.Modulos.y.Permisos.pdf)
- Roles
> - JEFE_DEPENDENCIA
> - ANALISTA
> - SOPORTE_OAS
> - EJECUTOR
> - AUDITOR

**Especificaciones técnicas**
1. Repositorio microcliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance implementación de roles

Se inicia con el desarrollo de la verificación del rol del usuario actual en el microcliente para la gestión de usuarios, se toma como ejemplo el código de SGA implicit_autentication.service.ts donde se realiza la implementación 

https://github.com/udistrital/sga_cliente/blob/develop/src/app/%40core/utils/implicit_autentication.service.ts

Se crea el servicio en en proyecto:

![Captura de pantalla 2024-09-03 a la(s) 11 09 23 a  m](https://github.com/user-attachments/assets/59518c57-e511-48b9-a71d-05a51694f625)

![Captura de pantalla 2024-09-03 a la(s) 11 24 43 a  m](https://github.com/user-attachments/assets/0f036f8e-180b-49d3-991c-865f827ba86d)

**Comment by alexhrr** [comment]
### Avance implementación roles

Según lo indicado se continua con la implementación de las secciones del código necesarias inicialmente para obtener el rol del usuario que se encuentra autenticado en el sistema desde los componentes correspondientes

![Captura de pantalla 2024-09-04 a la(s) 11 25 20 a  m](https://github.com/user-attachments/assets/2b1c1e90-7003-4021-9846-95e7949c1a4d)

![Captura de pantalla 2024-09-04 a la(s) 11 22 55 a  m](https://github.com/user-attachments/assets/bc1a6c4f-240b-47eb-bfaa-d983a0413ecf)

![Captura de pantalla 2024-09-04 a la(s) 11 23 02 a  m](https://github.com/user-attachments/assets/5ca21ba3-fbf6-469b-9209-bfdf2172abfb)

Llamado en el componente de consulta de usuarios para verificar los roles

![Captura de pantalla 2024-09-04 a la(s) 11 23 12 a  m](https://github.com/user-attachments/assets/2975f0a7-0653-4749-9806-49bcb0e98116)

**Comment by alexhrr** [comment]
### Avance implementación roles:

Se obtienen los roles del usuario que se encuentra logueado en el sistema, haciendo uso de implicit autentication.
Para la prueba se realiza el inicio de sesion con diferentes usuarios para observar que funcione correctamente:

Roles usuario 1:
![Captura de pantalla 2024-09-05 a la(s) 10 45 04 a  m](https://github.com/user-attachments/assets/be4eefee-ea86-421d-bdad-c81a2693666d)

Roles usuario 2:

![Captura de pantalla 2024-09-05 a la(s) 10 45 27 a  m](https://github.com/user-attachments/assets/ff4c90ce-0ab1-4365-96c6-650aff8456e0)

Así mismo se agrupan los roles por variable de entorno para los respectivos permisos en el microcliente, de acuerdo a lo informado se decide que los arreglos que almacenan la información por roles no contengan los ids de los roles, sino directamente el rol:

![Captura de pantalla 2024-09-05 a la(s) 11 24 38 a  m](https://github.com/user-attachments/assets/3b3ad2cc-33cb-45ab-85b8-9cad7db242c0)

**Comment by alexhrr** [comment]
### Avance Permiso roles

Una vez obtenidos los roles del usuario que inició sesión se realiza la comparacion con los roles asignados en las variables  definidas previamente:  

![Captura de pantalla 2024-09-05 a la(s) 11 02 38 p  m](https://github.com/user-attachments/assets/d3250dcc-163a-4fb4-a35f-5958f4d2ed00)

![Captura de pantalla 2024-09-05 a la(s) 11 03 06 p  m](https://github.com/user-attachments/assets/ca9ae024-b39b-4c15-97d7-cc90e34eaf1b)

![Captura de pantalla 2024-09-05 a la(s) 11 03 15 p  m](https://github.com/user-attachments/assets/0d8a9ab6-b8f7-4f7e-8f70-9dc74d5430d6)

Modificación de los campos correspondientes en el html:

![Captura de pantalla 2024-09-05 a la(s) 11 03 56 p  m](https://github.com/user-attachments/assets/528cccfb-958c-4e5c-8ec2-2bc4ecbd8ad3)

![Captura de pantalla 2024-09-05 a la(s) 11 03 35 p  m](https://github.com/user-attachments/assets/9cfc5258-8de2-419d-b5c8-7ecd1ea539da)

#### Pruebas Usuario con permiso de edición:

![Captura de pantalla 2024-09-05 a la(s) 10 58 39 p  m](https://github.com/user-attachments/assets/21ac583c-5ffd-47b1-9fc1-d9f1a832fd72)

![Captura de pantalla 2024-09-05 a la(s) 10 58 55 p  m](https://github.com/user-attachments/assets/10935c97-2acc-4033-838c-9440a71af077)

#### Pruebas Usuario sin permiso de edición:

Se elimina el botón de editar para que el usuario no pueda acceder a la edición:

![Captura de pantalla 2024-09-05 a la(s) 10 59 40 p  m](https://github.com/user-attachments/assets/048f0dd0-2049-400c-8d1c-be592c0cc486)

Se deshabilitan los campos de edición de estado y fecha final:

![Captura de pantalla 2024-09-05 a la(s) 11 01 17 p  m](https://github.com/user-attachments/assets/98242986-8225-4573-be5f-c5fa86ce742c)

Se debe revisar y evaluar la funcionalidad de el botón visualizar, se realizara la consulta en el daily junto al lider.

**Comment by alexhrr** [comment]
### Implementación permisos roles

Se finaliza la implementación de permisos según los roles del usuario de acuerdo a lo solicitado teniendo en cuenta los permisos de edición y consulta.

Para los usuarios que pueden consultar se determina que no se debe mostrar la columna de "acciones" de la tabla de la información de la consulta, esto debido a que no van a poder editar/eliminar los datos del periodo y la información necesaria ya está en la tabla.

![Captura de pantalla 2024-09-06 a la(s) 8 29 46 p  m](https://github.com/user-attachments/assets/b69d9fac-acb9-4796-9cf8-d0527ecb430f)

Para los usuarios que tienen permiso de edición se realizan las validaciones según su rol y se permite acceder a las opciones de editar/eliminar.

![Captura de pantalla 2024-09-06 a la(s) 8 28 57 p  m](https://github.com/user-attachments/assets/6f25b0a3-2bc1-44ed-9ad0-7d1b8c6fd8ae)

**Comment by edwargl7** [comment]
Implementación y sugerencias adecuadas en la implementación de los roles.
Pendiente ajuste de columna de acción.
Resuelto PR. Muy buen trabajo.
