### ISSUE TITLE
Construcción inicial formulario dinámico del módulo de registro del Plan Anual de Auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#153]
Se requiere realizar la construcción del formulario de registro del plan anual de auditoría usando el microcliente de formularios dinámicos, creando la estructura basado en como actualmente se construye para el mf. Esto con el fin de validar componentes adicionales requeridos para Sísifo y la identificación de cambios requeridos para el modelo de datos y crud de plantillas de formularios dinámicos.

**Sub Tareas**

- [x] Creación JSON con estructura del formulario de registro del plan anual de auditoría.
- [x] Pruebas funcionales.
- [x] Identificación de campos requeridos en la implementación del microcliente de formularios dinámicos.
- [x] Identificación de cambios requeridos en el microservicio de plantillas de formularios dinámicos.

**Criterios de aceptación**

- [x] Documentación de los componentes adicionales requeridos si aplica, y la identificación de cambios requeridos para el microservicio de plantillas de formularios dinámicos.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microcliente.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se creó un mock en Postman y un archivo JSON para probar la estructura del formulario de registro del plan anual de auditoría en el microcliente.

```Json
{
    "nombre": "Registrar Plan Anual de Auditoría PAA",
    "secciones": [
        {
            "nombre": "INFORMACIÓN",
            "campos": [
                {
                    "nombre": "Objetivo",
                    "descripcion": "Objetivo del plan",
                    "etiqueta": "Objetivo",
                    "tipo": "textarea",
                    "placeholder": "Escriba aquí el Objetivo",
                    "deshabilitado": false,
                    "validaciones": {
                        "requerido": true
                    }
                },
                {
                    "nombre": "Alcance",
                    "descripcion": "Alcance del plan",
                    "etiqueta": "Alcance",
                    "tipo": "textarea",
                    "placeholder": "Escriba aquí el Alcance",
                    "deshabilitado": false,
                    "validaciones": {
                        "requerido": true
                    }
                },
                {
                    "nombre": "Criterios",
                    "descripcion": "Criterios del plan",
                    "etiqueta": "Criterios",
                    "tipo": "textarea",
                    "placeholder": "Escriba aquí el Criterios",
                    "deshabilitado": false,
                    "validaciones": {
                        "requerido": true
                    }
                },
                {
                    "nombre": "Recursos",
                    "descripcion": "Recursos del plan",
                    "etiqueta": "Recursos",
                    "tipo": "textarea",
                    "placeholder": "Escriba aquí los Recursos",
                    "deshabilitado": false,
                    "validaciones": {
                        "requerido": true
                    }
                }
            ]
        },
        {
            "nombre": "REGISTRAR AUDITORÍAS",
            "campos": [
                {
                    "nombre": "No_Auditoría",
                    "etiqueta": "No de Auditoría",
                    "tipo": "number",
                    "deshabilitado": false,
                    "validaciones": {
                        "requerido": true
                    }
                },
                {
                    "nombre": "Auditoría",
                    "etiqueta": "Auditoría",
                    "tipo": "text",
                    "validaciones": {
                        "requerido": true,
                        "maxLength": 15
                    },
                    "deshabilitado": false
                },
                {
                    "nombre": "Tipo_Evaluación",
                    "etiqueta": "Tipo de Evaluación",
                    "tipo": "select",
                    "opciones": [
                        {
                            "valor": "1",
                            "etiqueta": "Auditoria Interna"
                        },
                        {
                            "valor": "2",
                            "etiqueta": "Seguimiento"
                        },
                        {
                            "valor": "3",
                            "etiqueta": "Informe"
                        }
                    ],
                    "validaciones": {
                        "requerido": true
                    },
                    "deshabilitado": false
                },
                {
                    "nombre": "Cronograma_Actividades",
                    "etiqueta": "Cronograma de Actividades",
                    "tipo": "select",
                    "opciones": [
                        {
                            "valor": "1",
                            "etiqueta": "Enero"
                        },
                        {
                            "valor": "2",
                            "etiqueta": "Febrero"
                        },
                        {
                            "valor": "3",
                            "etiqueta": "Marzo"
                        }
                    ],
                    "validaciones": {
                        "requerido": true
                    },
                    "deshabilitado": false
                },
                {
                    "nombre": "Estado",
                    "etiqueta": "Estado",
                    "tipo": "select",
                    "opciones": [
                        {
                            "valor": "1",
                            "etiqueta": "Sin Iniciar"
                        },
                        {
                            "valor": "2",
                            "etiqueta": "Iniciada"
                        }
                    ],
                    "validaciones": {
                        "requerido": true
                    },
                    "deshabilitado": false
                }
            ]
        }
    ]
}
```

A continuación, se muestra cómo se genera el formulario en el microcliente.
![image](https://github.com/user-attachments/assets/c767f2ed-55d2-43f7-85e7-abe886cff578)

![image](https://github.com/user-attachments/assets/02cf55fb-e7b7-4ca6-bba0-5078f7ce81f8)

**Comment by CristianCGutierrezG** [comment]
Con base en los mockups del Plan Anual de Auditoria y el microcliente de formularios dinámicos, se identificaron las siguientes implementaciones faltantes y nuevas funcionalidades que podrían añadirse:

### Cambios Generales en el Microcliente

**1. Seccion Información**
- **Botón de Guardado por Sección**: El boton de envio por el momento es general para todo el formulario, puede deberse al acordeon, en los mockups cada seccion tiene su propio boton de guardado.  
- **Edición Personalizada en TextAreas**

![image](https://github.com/user-attachments/assets/d6da2367-4f79-4506-840a-fef06bf40e7a)

**2. Seccion Registrar auditorias**
- **Funciones Personalizadas**: Funciones personalizadas en los botones si se agregan al formulario. Por el momento no hay forma de incluir botones ni como interactuan.

### Formas de Implementar la Tabla en la Plantilla de Formularios

 **Opción 1: Agregar Listas en la Plantilla**
Asignar un nuevo campo en la sección que permita determinar si se trata de una lista o un elemento que se puede agregar varias veces.
**Cambios en el Microservicio**:
     - Añadir un nuevo campo  `tipo` en la coleccion `seccion` para soportar esta funcionalidad.
    
![image](https://github.com/user-attachments/assets/da6a32bc-a92c-4b1e-8228-5f04a464a5f0)

 
**Cambios en el Microcliente**:
- Crear el FormGroup Dinámico: Utilizar FormArray para manejar la lista o tabla de campos repetibles.
- Añadir Funcionalidad para Agregar/Eliminar Filas: Permitir que los usuarios agreguen o eliminen filas dinámicamente.
- Renderizar el Formulario en la Vista: Utilizar ngFor para iterar sobre las filas de FormArray y renderizar los campos.

![image](https://github.com/user-attachments/assets/f8e4f8c3-25a6-4fae-b4d9-4a5adf1cd061)

 **Notas**:
 - Investigar cómo se debe estructurar el JSON para almacenar la información del formulario.
 - Para mantener el componente de `formularios_dinamicos` de manera general, la tabla solo mostraría y permitiría editar campos en la lista, mientras que otras funcionalidades serían únicas de Sisifo.

 **Opción 2: Botón con Modal para Editar y Mostrar Tabla**
Tratar la funcionalidad de la tabla como un componente aparte del formulario, pero que el formulario defina el acceso a este.

**Cambios en el Microcliente**:
 - Incluir funciones personalizadas en los botones con redirección a un modal o página específica.

![image](https://github.com/user-attachments/assets/bafa0215-c296-4f36-88e1-8ada3a5d9c82)

![image](https://github.com/user-attachments/assets/c24af435-2520-4566-aba7-33ef707ded6a)

**Notas**:
- ¿El manejo de datos sería separado al de los formularios si la tabla se maneja como un componente aparte?

**Comment by edwargl7** [comment]
Vista para contemplar sección de comandos.
![image](https://github.com/user-attachments/assets/216291e1-ca6f-4cf3-b337-b6d45d022844)

**Comment by CristianCGutierrezG** [comment]
### Mejor visualización del formulario generado en el microcliente
![image](https://github.com/user-attachments/assets/98929eba-ab00-475b-b93a-16c2da65a5a9)

**Comment by CristianCGutierrezG** [comment]
### Implementación de Botones Personalizados en la Plantilla de Formularios

#### Cambios en el Microservicio:
No será necesario realizar modificaciones en el microservicio, ya que la nueva información puede almacenarse en los parámetros del campo

``` Json
{
    "nombre": "Modificar_Auditoria",
    "tipo": "button",
    "parametros": {
        "accion": "modificar_auditoria",
        "texto": "Modificar Auditoría"
    }
}
```

#### Cambios en el Microcliente:
- Definir la lógica para manejar los botones dinámicamente, basándose en el tipo de campo y la acción especificada en el JSON.
- Esta lógica se puede implementar en el componente de creación de formularios o mediante la creación de una **directiva personalizada** o un **componente personalizado** para los botones. Esto permitiría desacoplar la lógica del botón del formulario principal y definir su comportamiento en diferentes lugares, manteniendo el código modular y reutilizable.

![image](https://github.com/user-attachments/assets/6025c49c-84f1-4711-8365-42e98f95359e)
![image](https://github.com/user-attachments/assets/1368b9c8-2ea4-44df-834e-941017d5d331)

**Comment by edwargl7** [comment]
Se cuenta con dos opciones bastante acertadas para la solución del problema de manejo de tabla. Se cuenta con un comportamiento similar para la funcionalidad de los botones. Muy buen trabajo.
