### ISSUE TITLE
Implementación vista Evaluación Auditoría por Jefe Dependencia

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#154]
Se requiere realizar la implementación del submódulo de evaluación de auditoría por el jefe de dependencia.

![Image](https://github.com/user-attachments/assets/6ddc1f31-baf9-4cb6-88cd-34beb6740f7d)
![Image](https://github.com/user-attachments/assets/93b31d8f-f033-47f0-b08a-bca29b50d058)
![Image](https://github.com/user-attachments/assets/586e8ada-4776-4c71-8863-f4a8ee5caaf3)
![Image](https://github.com/user-attachments/assets/308ce68b-9735-49ea-b085-0167bd3dee7b)
![Image](https://github.com/user-attachments/assets/367f2bb1-ecf8-40c6-a0dc-d3739a2e5153)
![Image](https://github.com/user-attachments/assets/4dd6e8db-b496-4c4d-9e52-20d18675f5e4)

Este Mockup y otros flujos cuentan con una implementación similar, con ciertos cambios, lo que permite poder reutilizar estos flujos de aprobación.

**Sub Tareas**

- [x] Implementación de la vista de visualización de documentos del plan con botones de aprobación o rechazo.
- [x] Implementación modal de Observaciones una vez se realiza clic en el botón de rechazo.
- [x] Implementación de modal para confirmación de rechazo.
- [x] Implementación de modal de confirmación de rechazo efectuado.
- [x] Implementación de modal de confirmación de aprobación.
- [x] Implementación de modal de confirmación de aprobación efectuado.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de la correcta implementación y ejecución del flujo siguiendo los lineamientos de desarrollo.

**Requerimientos**

No aplica

**Material de apoyo**
- Enlace [Mockup rol Jefe OCI](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZLd0FWqTu5NvCQqg_qnB1cBC_NhGwF3Jl9XKJGdLizlmg?e=wOTCS9)

**Especificaciones técnicas**
1. Repositorio microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/c5d84caf-7543-40a9-a9dd-7ab36aae71c7)

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/a4982bc2-4ae8-4747-8074-211acc8f7216)

**Comment by jucastro94** [comment]
se realiza implementacion de pipe 
![Image](https://github.com/user-attachments/assets/c496c9c2-33d2-4e53-9bb2-93a3a47aceff)

se crea componente para alojar el object
![Image](https://github.com/user-attachments/assets/dda0de3e-9e12-4864-9813-c6341352ad46)

se implementa la forma en que se trae base64
![Image](https://github.com/user-attachments/assets/58fcb5f1-de2d-490f-ae94-614bcbf3451e)

se llama componente y se envia base64 
![Image](https://github.com/user-attachments/assets/ea382595-329b-46c3-a01e-7e27d0d38ae2)


se presenta errro al renderizar el objeto
![Image](https://github.com/user-attachments/assets/4460d319-e3ae-4587-92fc-412d1ea7a6ed)
![Image](https://github.com/user-attachments/assets/1225674b-3a30-4de5-9983-e03c8702df91)

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/db3d069e-6156-4ed6-9a07-3e2e9171bb50)

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/dae82feb-72ca-4894-ad50-9511e65f1016)

**Comment by jucastro94** [comment]
https://github.com/user-attachments/assets/42b9b025-3e13-41c7-b25e-7a14c5e190c9

**Comment by jucastro94** [comment]
se implementa logica para reutilizacion de modal, este tiene la capacidad de llamarse a si mismo para visualizar el modal final de confirmacion

```typescript
export class ModalConfirmarRechazoComponent {

  mensaje: string;
  icono: 'warning' | 'success' | 'error' | 'info';
  mostrarBotonCancelar: boolean;
  textoConfirmacion: string;
  textoCancelacion: string;
  continue:boolean;
  textoMensajeConfirmacion: string;
  textoSubMensajeConfirmacion:string;

  constructor(
    public dialogRef: MatDialogRef<ModalConfirmarRechazoComponent>,
    private dialog: MatDialog,
    @Inject(MAT_DIALOG_DATA) public data: any
  ) { 
    this.mensaje = data.mensaje || '¿Está seguro(a) de realizar esta acción?';
    this.icono = data.icono || 'warning';
    this.mostrarBotonCancelar = data.mostrarBotonCancelar !== undefined ? data.mostrarBotonCancelar : true;
    this.textoConfirmacion = data.textoConfirmacion || 'Aceptar';
    this.textoCancelacion = data.textoCancelacion || 'Cancelar';
    this.continue = data.continue;
    this.textoMensajeConfirmacion =data.textoMensajeConfirmacion;
    this.textoSubMensajeConfirmacion =data.textoSubMensajeConfirmacion || '';
  }
    
  ngOnInit(): void {
    this.mostrarModal();
}
mostrarModal(): void {
  const htmlContent = `
    <h1 style="margin-bottom: 5px; color:hsl(0deg 0% 59.61%);">${this.mensaje}</h1>
    ${this.textoSubMensajeConfirmacion && !this.continue ? `<h3 style="color:hsl(0deg 0% 59.61%);">${this.textoSubMensajeConfirmacion}</h3>` : ''}
  `;
  Swal.fire({
    html: htmlContent,
    icon: this.icono,
    showCancelButton: this.mostrarBotonCancelar,
    confirmButtonText: this.textoConfirmacion,
    cancelButtonText: this.textoCancelacion,
    confirmButtonColor: '#3085d6', 
    cancelButtonColor: '#d33',
    
  }).then((result) => {
    this.dialogRef.close();
    if (result.isConfirmed && this.continue) {
      // Lógica para cuando se presiona "Aceptar"
      
      console.log('Plan rechazado');

      // Abrir otro modal igual
      this.dialog.open(ModalConfirmarRechazoComponent, {
        data: {
          mensaje: this.textoMensajeConfirmacion,  
          icono: 'success',
          mostrarBotonCancelar: false,
          textoConfirmacion: 'OK',
          continue:false,
          textoSubMensajeConfirmacion:this.textoSubMensajeConfirmacion,
        }
        
      });
    } else if (result.dismiss === Swal.DismissReason.cancel) {
      // Lógica para cuando se presiona "Cancelar"
      console.log('Acción cancelada');
    }
  });
}
}
```

forma de abrir el modal enviando la informacion que necesita

![Image](https://github.com/user-attachments/assets/1d0f38c1-f3bd-47c9-b50d-be418e83fb4d)

prueba funcional


https://github.com/user-attachments/assets/b64882f4-d4e5-4400-bb6e-4887d97b4883

**Comment by jucastro94** [comment]
se corrigen y agregan estilos 

![Image](https://github.com/user-attachments/assets/570e6260-4737-4c15-9f98-b721d1e8a303)


se trabaja en la visualizacion del documento sin dar resuiltado, se continua con el mismo error


![Image](https://github.com/user-attachments/assets/65673918-9c52-4fbe-935b-b395252d385e)

**Comment by edwargl7** [comment]
Se cuenta con una solución alterna trabajada en ARGO se realizará la revisión completa y se evaluará la posibilidad de cambiar la implementación realizada par la visualización del PDF.
