### ISSUE TITLE
Ajustes microservicio de plantillas de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#156]
Se requiere realizar ajustes en el modelo de datos y microservicio de plantillas de formularios dinámicos basado en la implementación con la que cuenta actualmente el microcliente y que permite identificar ajustes requeridos en el almacenamiento de los datos.

**Sub Tareas**

- [ ] Ajuste tipo de datos del campo placeholder y label de Object a string.
- [x] Cambio nombre de colección elementos personalizados a campo.
- [x] Remover campo requerido dado que se va a usar dentro del objeto de validadores.
- [x] Ajuste modelo de datos con las actualizaciones.
- [x] Presentación de cambios del modelo de datos a DBA por medio del ticket.

**Criterios de aceptación**

- [x] Documentación de la implementación y ajustes realizados al microservicio.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizaron ajustes al modelo de datos. 

![_Modelo de datos - formularios dinámicos-versión 8 drawio](https://github.com/user-attachments/assets/faf1103e-ddae-4ceb-a6e4-fae64297f18e)

Sin embargo, no se modificaron los campos `placeholder` y `label` de Object a string, ya que aún no está claro cómo se manejará el comportamiento multilenguaje del formulario en relación con estos campos.

[Modelo de datos - formularios dinámicos V8](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ERbzd3pTeJBPl3rN0T6uJo4B4WPClvLajeptQ_j0vB7VlQ?e=VamKBR)

**Comment by CristianCGutierrezG** [comment]
En en el microcliente se ha implementado un cambio en la estructura de almacenamiento de las validaciones en cada campo

```
validaciones: [
{
  Tipo: "requerido",
  Valor: ''"
}, 
{
  Tipo: "min",
  Valor: ''10"
},
{ 
  Tipo: "max",
  Valor: ''10" 
}]
```
 Esta estructura es válida ya que el campo en la base de datos es de tipo `Object`, el cual permite también almacenar `Arrays`.

Con base en estos ajustes, se realizaron cambios en el modelo de datos para adaptarse a la nueva estructura de almacenamiento

![_Modelo de datos - formularios dinámicos-versión 8 drawio (1)](https://github.com/user-attachments/assets/06391229-c4e8-4ee7-ac10-4b0b798cf024)

[Modelo de datos - formularios dinámicos V8](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ERbzd3pTeJBPl3rN0T6uJo4B4WPClvLajeptQ_j0vB7VlQ?e=y2WMM4)

**Comment by CristianCGutierrezG** [comment]
Se realizan los ajustes necesarios en el microservicio propuestos en el modelo de datos y se comprueba el correcto funcionamiento del CRUD

![image](https://github.com/user-attachments/assets/21283bf1-8712-43f0-a253-413fccf01713)

![image](https://github.com/user-attachments/assets/d82eeaac-d579-4977-8dda-d5b5de24ba58)

![image](https://github.com/user-attachments/assets/35e5672f-cbab-4552-a194-cf2b5f53dd0f)

**Comment by CristianCGutierrezG** [comment]
#### Actualización de Validaciones y Parámetros , junto con Servicio `plantillas`

Se ajustaron los campos de validación y parámetros para alinearse con los cambios realizados.

![image](https://github.com/user-attachments/assets/5c45e2de-7496-4637-a1ea-9e8e207867c1)

Todas las interacciones  en el seservicio de `plantillas` con `elementos_personalizados`, que ahora son referidos como `campo`, fueron actualizadas.

Se llevaron a cabo pruebas para verificar el correcto funcionamiento del servicio tras las modificaciones.

![image](https://github.com/user-attachments/assets/6fef2ace-096f-470c-b078-0f70d9f1395b)

**Comment by edwargl7** [comment]
Se aborda la implementación con los ajustes identificados requeridos para el microservicio de plantillas de formularios dinámicos basado en los ajustes que surgen de la implementación del microcliente.
Muy buen trabajo se resuelve el PR.
