### ISSUE TITLE
Pruebas funcionales del microservicio histórico  usuarios roles crud en ambiente de pruebas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#157]
Se requiere realizar la verificación del correcto funcionamiento del microservicio histórico usuarios roles una vez desplegado en ambiente de pruebas. 

**Sub Tareas**

- [x] Ajustes requeridos para el despliegue (estabilización).
- [x] Pruebas de cada endpoint CRUD del microservicio funcionalidad completa (filtros, paginado, ...).

**Criterios de aceptación**

- [x] Documentación de las pruebas funcionales realizadas a cada CRUD.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se encuentra desplegado el microservicio.
Se puede seguir con las pruebas funcionales.

**Comment by jucastro94** [comment]
se verifica health check
![Image](https://github.com/user-attachments/assets/8049d4e7-c6ce-4c6e-8db2-9371fd70f9ba)

se realiza verificacion de swagger
![Image](https://github.com/user-attachments/assets/6b27f545-a56a-4408-bf2c-4d80f3082d6b)

se realiza validacion de GET
![Image](https://github.com/user-attachments/assets/f231b8d3-dda3-4726-9248-fb82f53c2f14)

se realiza validacion de POST
![Image](https://github.com/user-attachments/assets/1e51c195-5113-415c-8e3d-a4b659b2f4a4)

**Comment by edwargl7** [comment]
Se completan los ajustes para el despliegue y la validación del microservicio. Se debe validar con infraestructura el fallo en los endpoints del CRUD, dado que el healthCheck funciona correctamente.
