### ISSUE TITLE
Diseñar el mockup fase final de auditoria, seguimiento e informes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#158]
Se requiere diseñar mockup de la fase final de auditoria, seguimiento e informes.

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla diseño de mockup del submódulo ejecución >> seguimiento e informes, con los roles de auditor y jefe de OCI.

**Mockup Ejecución>>Seguimiento e Informes - Rol Auditor**
![Image](https://github.com/user-attachments/assets/2b9e3e0a-9999-45f5-bb75-04ee41a7247d)


**Mockup Ejecución>>Seguimiento e Informes - Rol Jefe OCI**
![Image](https://github.com/user-attachments/assets/75e62f6f-c8e2-4d9d-adc1-b9abe0f8e5d0)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Ejecuci%C3%B3n/Subm%C3%B3dulo%20Seguimiento%20e%20Informes?csf=1&web=1&e=w2YUCf

 
Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp, revisaremos los mockup en el review.

**Comment by jcmurilloa** [comment]
Mockup aprobado para muestra con el cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta diseño de mockup de la fase final de auditoría, seguimiento e informes. Se recibe aprobación bajo el **acta No 145/2024** para el desarrollo del módulo en el sistema SISIFO V2.

**Enlace acta de reunión No 145/2024 SISIFO - Levantamiento de requerimientos**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Lqccbu

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp!
