### ISSUE TITLE
Diseñar el mockup para el submódulo auditorías especiales

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#159]
Se requiere continuar con el diseño del mockup para el submódulo auditoría especiales.

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrollan diseños de mockup del submódulo auditorías especiales para las diferentes fases del proceso de auditoría.


**Submódulo Programación >> Auditorías Especiales**
![Image](https://github.com/user-attachments/assets/b98b7da9-7511-497f-a61e-8a8e9abd7104)


**Submódulo Planeación >> Auditorías Especiales**
![Image](https://github.com/user-attachments/assets/abe236fe-2f15-4090-b938-1554e5aee765)

**Archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
 https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Programaci%C3%B3n/Subm%C3%B3dulo%20Auditor%C3%ADas%20Especiales?csf=1&web=1&e=aSL7sh


Saludos.

**Comment by jcmurilloa** [comment]
Excelentes diseños @cjgonzalezp, mockups aprobados para la muestra respectiva al cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

El submódulo de auditorías especiales se integrará en los módulos de planeación y ejecución según el tipo de evaluación que se asigne a la auditoría especial, por tal motivo se da por finalizada la issue #159.

Saludos.

**Comment by edwargl7** [comment]
Revisada el 16/09/2024. Se finaliza la Issue con la observación de la agrupación de este submódulo.
