### ISSUE TITLE
División del sistema en Microservicios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#16]
Se requiere realizar el diseño de los microservicios de Sísifo, de tal forma que cada uno sea independiente, autosuficiente y escalable. El objetivo es lograr desacoplar las funcionalidades del sistema y descentralizar los servicios teniendo presente el concepto de microservicios.

**Material de apoyo**
- [División del sistema en Microservicios](https://github.com/udistrital/planeacion_cliente/issues/803)

**Sub Tareas**

- [x] Creación de diagrama de componentes de la arquitectura propuesta para el sistema Sísifo.
- [x] Listado de microservicios y principales funcionalidades.

**Criterios de aceptación**

- [x] El diagrama muestra la división clara del sistema Sísifo v1 en múltiples microservicios tanto los desarrollados para Sísifo como integraciones con otros sistemas de la OATI.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de microservicios.
- [x] Archivo subido a la carpeta de documentación con la lista de microservicios y principal funcionamiento.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Modelo de base de datos actual
![odoo-ud - public - plan_mejoramiento_accion](https://github.com/udistrital/sisifo_documentacion/assets/50187485/9a8edc42-b4db-4939-9014-6390b885ad37)

**Comment by CristianCGutierrezG** [comment]
Diagrama de microservicios:
![Microservicios Sisifo](https://github.com/udistrital/sisifo_documentacion/assets/48999834/73307a4c-b68b-4449-afe6-9525483a7dc6)

se adjunta enlace del diagrama:
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EeQcqSgWWWpIh6HnCUBMVZ0BcpZHlzXktwyCaZChSJamBQ?e=g9cwcp

**Comment by CristianCGutierrezG** [comment]
Listado de microservicios y principales funcionalidades:
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/bc9f5d8e-c09c-4382-9ee9-39800b5d1641)


se adjunta enlace del listado:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESXbGZhCN61JlxMK2GeaJJoBepfnSDWqga0Gb0yCNXlwNQ?e=cusf30

**Comment by edwargl7** [comment]
Excelente trabajo, cuenta con un buen análisis y diseño de las principales funcionalidades que tendrán cada microservicio basado en la documentación actual. Se realiza la revisión con el arquitecto.
