### ISSUE TITLE
Ajuste paginado consulta por defecto

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#160]
Se requiere realizar los ajustes al momento de realizar la consulta por defecto basado en los valores con los que cuenta el paginador.

**Sub Tareas**

- [x] Ajustes valores por defecto de consulta con y sin filtro para traer la cantidad de valores basado en el paginador.

**Criterios de aceptación**

- [x] Documentación avances en los ajustes.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Ajuste paginado

Se establecen valores por defecto para los registros por pagina desde un arreglo con los valores requeridos, para este caso, valores pequeños para poder realizar las pruebas correspondientes

![Captura de pantalla 2024-09-05 a la(s) 9 03 04 a  m](https://github.com/user-attachments/assets/8a33c029-4263-41a1-8176-029e85167f8b)

Ahora se pasa al paginador esta variable:

![Captura de pantalla 2024-09-05 a la(s) 9 03 55 a  m](https://github.com/user-attachments/assets/2a059fee-16a7-480c-8de9-6fea87e45440)

y se usa en las consultas iniciales a los endpoints para establecer el primer valor del tamaño de la pagina con el limit de la consulta:

![Captura de pantalla 2024-09-05 a la(s) 9 06 05 a  m](https://github.com/user-attachments/assets/9c8f59ae-ca38-4502-adac-96a8af575df4)

![Captura de pantalla 2024-09-05 a la(s) 9 06 22 a  m](https://github.com/user-attachments/assets/596c88b8-b02f-4413-95f8-a152ab5ded6d)

Para el manejo de filtro por documento de identidad, en una reunion se decidió junto al lider que se va a restablecer el tamaño de la pagina al valor inicial de las opciones cuando se realice la consulta del documento

![Captura de pantalla 2024-09-05 a la(s) 9 06 56 a  m](https://github.com/user-attachments/assets/f4983bf3-b202-4f17-bd52-459030d49172)

La paginacion funciona correctamente en las consultas con y sin filtro aún cuando se realizan cambios en el tamaño de las opciones y posteriormente se realiza el filtro por documento de identidad, solucionando el inconveniente que se tenía

![Captura de pantalla 2024-09-05 a la(s) 9 12 33 a  m](https://github.com/user-attachments/assets/cee238eb-e6f1-4c2d-b1a6-ad130f1d8624)

![Captura de pantalla 2024-09-05 a la(s) 9 13 06 a  m](https://github.com/user-attachments/assets/b974cd33-9b28-43d4-a3ca-7613f386e298)

![Captura de pantalla 2024-09-05 a la(s) 9 12 20 a  m](https://github.com/user-attachments/assets/bbc3ae96-7c03-4c77-be62-a9ae6fee8775)

**Comment by edwargl7** [comment]
Implementación adecuada a lo requerido, se resuelve el PR. Muy buen trabajo.
