### ISSUE TITLE
Implementación Stepper en microcliente de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#161]
Se requiere realizar la implementación de los Stepper en el microcliente de formularios dinámicos de tal forma que pueda ser posible elegir entre vista en _Accordion_ o en _Stepper_ cada una de las secciones principales del formulario.

**Sub Tareas**

- [x] Prueba de correcta visualización de los stepper en el formulario de pruebas actual.
- [x] Implementación lógica para elección de accordion o stepper.

**Criterios de aceptación**

- [x] Documentación de las pruebas y resultados obtenidos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se implementa la logica para la elección de accordion o stepper

Con accordion

![image](https://github.com/user-attachments/assets/98f3dc40-b8fe-4e96-b2e7-26028cbe7ebc)

![image](https://github.com/user-attachments/assets/62cab2e4-1eeb-4641-96a0-eadfdf4e6f84)

Con stepper

![image](https://github.com/user-attachments/assets/789f6a24-ec1e-4dc3-89cb-6c56bd957ae8)

![image](https://github.com/user-attachments/assets/eb54ff68-dad8-46d5-9fba-26cb2235101b)

![image](https://github.com/user-attachments/assets/047f9049-244b-435e-bcc0-68f8c41e2946)

**Comment by edwargl7** [comment]
Buena implementación y prueba de concepto se retoma la validación de viabilidad en un siguiente sprint.
