### ISSUE TITLE
Implementación submódulo de asignación de auditores

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#162]
Se requiere realizar la implementación del componente de asignación de auditores basado en el mockup.
![image](https://github.com/user-attachments/assets/39f9391c-f181-471d-939b-3f031f5e5dc4)

**Sub Tareas**

- [x] Implementación de tabla de actividades de la auditoría registradas en el paso 2 del registro del plan de auditoría.

**Criterios de aceptación**

- [x] Documentación de la implementación en el microcliente de gestión contractual.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/bdf173ab-6547-49dd-b72c-f259ffb5f245)

**Comment by edwargl7** [comment]
Se encuentra un buen trabajo se va a revisar la posibilidad de hacer code review con dos pares @alexhrr @CristianCGutierrezG dado que se cuenta con la posibilidad de enriquecer el proceso con la experiencia del equipo dado que las tareas actuales se encuentran enfocadas en la maquetación de diferentes vistas en el mf.

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/4245affd-35e4-4e09-81f7-28edc3cd4d64)

**Comment by edwargl7** [comment]
Se realiza la revisión del código, se debe realizar el PR unificando los demás cambios. Muy buen trabajo.
Una vez resuelto el PR validar cambios.
