### ISSUE TITLE
Ajustes icono de acciones en microcliente de gestión de roles de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#163]
Se requiere realizar las pruebas funcionales completas del microcliente de gestión de roles de usuarios previo al despliegue.

**Sub Tareas**

- [x] Ajuste estilo de botones de la tabla de listado de periodos, cambiarlo a los 3 puntos.
- [x] Revisión y eliminación de console log no requeridos para el ambiente de pruebas.
- [x] Pruebas funcionales completas finales asignando y removiendo periodos al usuario de pruebas.

**Criterios de aceptación**

- [x] Documentación de resultado completo de pruebas realizadas con los últimos ajustes solicitados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Ajustes microcliente

Se realiza la eliminación de algunos console log que no van a ser necesarios en el ambiente de pruebas.

Se realiza el cambio de los botones para el menú de las acciones

![Captura de pantalla 2024-09-09 a la(s) 8 52 42 p  m](https://github.com/user-attachments/assets/2633b0d5-0560-47fb-b311-255f1181bb8f)

![Captura de pantalla 2024-09-09 a la(s) 8 52 48 p  m](https://github.com/user-attachments/assets/81424838-5c34-453a-adb9-f947b900918a)

Se realiza la verificación de que sigan funcionando correctamente y con los permisos según el rol del usuario.

Se inicia con la ejecución completa de las pruebas funcionales del modulo de gestión de usuarios

**Comment by alexhrr** [comment]
## Pruebas funcionales gestión de usuarios

### Creación de usuario

Se realiza la creación del usuario y la  asignación de rol y periodo:

![Captura de pantalla 2024-09-10 a la(s) 9 44 31 a  m](https://github.com/user-attachments/assets/9b9f550e-4ed5-4591-b5bd-82c7649bef1d)

Se verifica que el rol se haya agregado al usuario:

![Captura de pantalla 2024-09-10 a la(s) 9 44 58 a  m](https://github.com/user-attachments/assets/8978f5e5-79a6-4b24-81a6-3eb5f0c59ca0)

### Consulta de usuarios

Se consultan los usuarios registrados y se verifica que el usuario que se creó en el paso anterior se encuentra correctamente

![Captura de pantalla 2024-09-10 a la(s) 9 45 33 a  m](https://github.com/user-attachments/assets/8a132c19-61e4-4e11-812f-c9d302625672)

Igualmente se hace la verificación de la consulta usando el filtro del documento de identidad

![Captura de pantalla 2024-09-10 a la(s) 9 45 47 a  m](https://github.com/user-attachments/assets/00c37b46-f55c-44e0-ac44-a5873fe17733)

Mediante el nuevo botón de acciones y con el permiso de edición, se accede a la sección de actualización

![Captura de pantalla 2024-09-10 a la(s) 9 53 07 a  m](https://github.com/user-attachments/assets/6239bba7-aa3a-4d55-b7f8-ff4e3828a12e)

### Actualización de usuarios:

Se trae la información del periodo del usuario seleccionado y se realiza el cambio de estado a finalizado:

![Captura de pantalla 2024-09-10 a la(s) 9 54 07 a  m](https://github.com/user-attachments/assets/05a7b9cc-1712-4272-a928-26f7bfe08715)

Se verifica finalmente el cambio en el estado del periodo.

![Captura de pantalla 2024-09-10 a la(s) 9 54 40 a  m](https://github.com/user-attachments/assets/24cfd434-9fea-4765-b4b1-2855f8f21df8)

Se agregan los correspondientes modales de éxito a la creación y actualización de usuarios:

![Captura de pantalla 2024-09-10 a la(s) 10 31 01 a  m](https://github.com/user-attachments/assets/003f177c-0695-4151-85b7-3ce8fbae74b3)

**Comment by edwargl7** [comment]
Muy buenos avances, se solicita la ayuda a @alexhrr para documentar los modales pendientes por definir.
Adicional a lo establecido en la tarea inicial se agrega la integración del campo metadata al mf.

**Comment by alexhrr** [comment]
### Modales en el microcliente:

Los modales cuentan con los siguientes parámetros para su creación:

**icono:** Se muestra en la parte superior del modal y puede ser de los siguientes tipos según sea el caso 'success' , 'error' , 'warning' , 'info'.
**Titulo:** Es el texto principal de la parte superior del modal
**Mensaje:** Texto de la parte inferior para dar mas detalles.

Actualmente se tienen implementados dos tipos de modales en el modulo de gestión de usuarios para mostrar resultados de éxito o de algún error en la ejecución:

**Modal de éxito:**

Para la creación y actualización de los usuarios, el titulo y el mensaje los puse de la siguiente manera:

![Captura de pantalla 2024-09-10 a la(s) 8 08 02 p  m](https://github.com/user-attachments/assets/78f12408-815e-49cd-81ae-7e5e5c89adcb)

![Captura de pantalla 2024-09-10 a la(s) 8 07 16 p  m](https://github.com/user-attachments/assets/198c19df-25f9-4164-9f18-10a358d6f28c)

**Modal de error:**

Los modales de 'error' contienen el mismo titulo y se cambia el mensaje según sea el caso:

![Captura de pantalla 2024-09-10 a la(s) 8 10 40 p  m](https://github.com/user-attachments/assets/2de5e628-7af2-45ce-96b7-2ccaf53c514f)

Los modales creados para la gestión de usuarios se pueden ajustar según el diseño deseado en cuanto al titulo, mensaje e icono, se debe confirmar si se van a dejar como están o se va a definir algún texto diferente para el usuario.

**Comment by alexhrr** [comment]
### Creación servicio para el manejo del modal

Se elimina el componente "usuario no encontrado" que centralizaba el uso de los modales en el microservicio y se reemplaza por el servicio "modal.service.ts".

Para simplificar el código y en el mf se implementa el servicio para el manejo del modal:

![Captura de pantalla 2024-09-11 a la(s) 11 18 40 a  m](https://github.com/user-attachments/assets/880e26a8-5212-448e-9736-7808f566e57a)

El llamado se continúa realizando de la misma forma, enviando los parámetros necesarios para mostrar el modal:
mensaje, icono y titulo.

![Captura de pantalla 2024-09-11 a la(s) 11 19 45 a  m](https://github.com/user-attachments/assets/45c70b70-b0c4-4464-b9d6-9bc57c6091e6)

Con este cambio ya no es necesario crear una función en cada componente para enviar los datos al modal y mostrarlos usando mat.dialog.

Tambien se realiza el cambio de nombre de la variable "cdr"

![Captura de pantalla 2024-09-11 a la(s) 11 23 27 a  m](https://github.com/user-attachments/assets/e1e13e6c-0e87-4443-9a99-eb16c0b431dd)

![Captura de pantalla 2024-09-11 a la(s) 11 23 40 a  m](https://github.com/user-attachments/assets/f54b3995-2add-40cf-b437-a4cac7f8b5a1)

**Comment by alexhrr** [comment]
### Integración campo metadata

Se obtiene el conteo de los registros totales desde histórico usuarios y de autenticación_mid  haciendo su respectiva verificación de funcionamiento, luego se procede a integrarlos en el microcliente para la consulta de usuarios con y sin filtro para finalizar el proceso de paginacion.

![Captura de pantalla 2024-09-11 a la(s) 1 50 36 p  m](https://github.com/user-attachments/assets/590bc927-3105-48f5-b9ef-41217a9f9df1)

![Captura de pantalla 2024-09-11 a la(s) 1 50 44 p  m](https://github.com/user-attachments/assets/b2afb073-66c7-4538-8268-bcc2906c1fd6)

Se realiza la verificación final del funcionamiento de la paginacion en el componente de consulta:
 
 Consulta sin filtro y con 5 registros totales:
 
![Captura de pantalla 2024-09-11 a la(s) 1 30 41 p  m](https://github.com/user-attachments/assets/876a0ae7-f917-4801-9868-73dee4364440)

Consulta con filtro por documento de identidad:

Un solo registro para el usuario:

![Captura de pantalla 2024-09-11 a la(s) 1 30 11 p  m](https://github.com/user-attachments/assets/c203c180-4d88-4f9e-bb7b-13a08626552a)

Dos registros para otro usuario:

![Captura de pantalla 2024-09-11 a la(s) 1 30 58 p  m](https://github.com/user-attachments/assets/06fa7a32-79aa-48c7-9886-91b7398503e5)

Como se observa en la pruebas de funcionamiento realizadas, se comprueba el correcto funcionamiento de paginador en el total de los registros a mostrar según sea el caso.

**Comment by edwargl7** [comment]
Muy buena documentación y revisión del proyecto que permitió pulir detalles adicionales. Adicional, se observan ajustes en nombres de variables y componentes que dan mejor legibilidad del código. Muy buen trabajo.
