### ISSUE TITLE
Implementación submódulo de auditorías especiales

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#164]
Se requiere realizar la maquetación del submódulo de registro de auditorías especiales basado en el mockup. Conformado por el registro inicial del año de la auditoría y posteriormente el registro de la auditoría.
![image](https://github.com/user-attachments/assets/bef97f16-11a5-48be-9777-439baec2205b)
![image](https://github.com/user-attachments/assets/9397e97e-7247-47ab-8d3c-631f8d1c38cc)

**Sub Tareas**

- [x] Implementación componente de registro y consulta de auditorías especiales.
- [x] Implementación de formulario de registro y actualización de auditoría.

**Criterios de aceptación**

- [x] Documentación del resultado de la maquetación del submódulo de registro de auditorías especiales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Repositorio https://github.com/udistrital/plan_anual_auditoria_mf

**Comment by alexhrr** [comment]
Se crea el submodulo de auditorias especiales en el repositorio del plan anual de auditoria.

![Captura de pantalla 2024-09-11 a la(s) 5 55 43 p  m](https://github.com/user-attachments/assets/5388fc49-1ac4-4182-89de-b9446989c1ae)

Se asignan las rutas correspondientes y se monta el mf:

![Captura de pantalla 2024-09-11 a la(s) 6 25 18 p  m](https://github.com/user-attachments/assets/fb24b3c6-7c84-428d-bfa9-a5dd8154bead)

![Captura de pantalla 2024-09-11 a la(s) 6 25 01 p  m](https://github.com/user-attachments/assets/264f876a-7502-48ca-b272-94cd651cac97)

Se inicia con la maquetación del modulo solicitado

**Comment by alexhrr** [comment]
### Maquetación auditorias especiales

Se realiza la implementación para mockup del registro inicial del año de la auditoría, queda de la siguiente forma:

![Captura de pantalla 2024-09-12 a la(s) 9 05 17 p  m](https://github.com/user-attachments/assets/82436826-6ed5-431f-9bd1-5817e12e423d)

Se consulta sobre la vista del regitro de la auditoria y se debe hacer como una ventana en el componente, se procede a realizar un modal para esta vista.

**Comment by alexhrr** [comment]
### Maquetación auditorias especiales

Se realiza la maquetación de la vista del registro de la auditoria usando un modal que se llama des de la vista del registro inicial del año de la auditoria con el botón editar auditoria:

![Captura de pantalla 2024-09-13 a la(s) 10 23 27 p  m](https://github.com/user-attachments/assets/427adf7e-fe78-4106-877d-059d1b8dfe73)
  
![Captura de pantalla 2024-09-13 a la(s) 10 22 38 p  m](https://github.com/user-attachments/assets/4b4bf608-02ca-40e6-b4b3-89ed853d6d82)

![Captura de pantalla 2024-09-13 a la(s) 10 23 41 p  m](https://github.com/user-attachments/assets/af9ee389-9c56-4ff3-bf3a-9105bd40294b)

![Captura de pantalla 2024-09-13 a la(s) 10 23 50 p  m](https://github.com/user-attachments/assets/adace241-7e93-4555-a81e-888f90f2912d)

**Comment by edwargl7** [comment]
Se resuelve el PR, buena documentación de pruebas e implementación. Se mezclaron dos ramas al resolver el PR, validar por favor el correcto funcionamiento.
