### ISSUE TITLE
Implementación componente tipo lista en formularios dinámicos - prueba de concepto

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#166]
Se requiere realizar la implementación de un componente tipo tabla como prueba de concepto que permita evaluar la posibilidad de contemplar con la funcionalidad requerida en el segundo paso de registro del plan.
![image](https://github.com/user-attachments/assets/0dfc4d2c-7a34-4ec6-8e4d-5611f91dbc19)
![image](https://github.com/user-attachments/assets/e51e723f-83ed-4547-8135-c852e462e82d)

**Sub Tareas**

- [x] Implementación componente de tabla que permita parametrizar los campos que conformaran la tabla y las acciones requeridas (junto con el servicio que ejecutará la acción).
- [x] Combinación tabla con formulario de registro (dos secciones).

**Criterios de aceptación**

- [x] Documentación de implementación y resultado obtenido.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Implementación de Componente No Dinámico

Se desarrolló un componente de lista **no dinámico** con el fin de observar su comportamiento y estructura, evaluando si es la implementación correcta 

Cuenta con las funcionalidades de agregar materia y eliminar materia

![image](https://github.com/user-attachments/assets/31760dd2-c44c-479e-a47e-f81741c90c5d)

**Comment by edwargl7** [comment]
Se da mayor prioridad a la tarea #172

**Comment by edwargl7** [comment]
Se requiere basado en la reunión trabajada en la Issue #174.

Se debe continuar la prueba implementada inicialmente en esta Issue a la creación de un componente en formularios dinámicos. 
Este componente debe ser una tabla que tenga para su configuración dos parámetros.
1. Definición de columnas que se van a mostrar.
2. Endpoint que va a suministrar la información a la tabla.

Para una siguiente iteración agregar la característica de filtros en la tabla.
![image](https://github.com/user-attachments/assets/b0c1c6cf-63cf-4f04-873f-c9a95247ff94)

Manejo de acciones.

**Comment by CristianCGutierrezG** [comment]
###  Componente tipo lista

**Inconvenientes con los Validadores**:
Se realizó un pull para incorporar los últimos cambios de SGA, pero se encontraron problemas con los validadores. Los validadores no se reconocen al momento de generar el formulario.

#### Implementaciones Realizadas:

Se realiza la implemetación del componente tipo tabla momentaneamente solo disponible para el formulario tipo stepper

 **Componente `list-dynamic-forms`**:
   - Se implementó el componente `list-dynamic-forms`, que incluye:
     - Un formulario generado dinámicamente con los campos de la sección.
     - Una tabla que permite agregar y eliminar campos, con acciones correspondientes.
     - La opción de renderizar datos en la tabla si la sección cuenta con una URL de datos asociada.

  
![image](https://github.com/user-attachments/assets/81684bf8-92bd-4caa-bf8e-161a976b1431)
 
**Mock de Datos de la tabla**
![image](https://github.com/user-attachments/assets/85ac561b-c99e-4cca-a1ed-827bb0ad2238)

**Vista del comoponente dinamico**
![image](https://github.com/user-attachments/assets/1e890d38-80ed-4d23-93dd-67ed5a5c4100)

**Vista del comoponente sin url**
![image](https://github.com/user-attachments/assets/04fc91a3-1de0-48a4-bbd0-bd91a84c34bd)


#### Cosas Pendientes por Implementar:
   - Implementar y manejar diferentes tipos de campos según las especificaciones del formulario.
   - Implementar la funcionalidad para deshabilitar campos que no deben recibir datos en el formulario.
   - Añadir validaciones a los campos construidos en la lista.

**Comment by edwargl7** [comment]
Se obtiene un resultado bastante cercano a lo requerido. Se realizará la revisión junto con @cjgonzalezp en una siguiente reunión para evaluar la viabilidad de esta alternativa.
Referente a los cambios llevados por el momento separados en el repositorio de formularios dinámicos mf, se va a revisar que cambios requerimos separar para actualizar partiendo de una rama nueva desde develop y llevar los cambios confirmados por el momento.
