### ISSUE TITLE
Revisión flujo del módulo de plan de auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#167]
Se requiere realizar la presentación del flujo de registro de los planes y programación de las auditorías por parte de @cjgonzalezp al equipo de desarrollo para tener más claro el flujo de las fases previas a la ejecución de la auditoría y las vistas donde se requieren combinaciones de formularios con tablas y acciones específicas.

**Sub Tareas**

- [x] Participación en la presentación del flujo de planes y programación de auditorías.

**Criterios de aceptación**

- [x] Participación en la presentación del flujo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza reunión con el equipo de desarrollo del proyecto SISIFO V2 el día martes, 10 de septiembre de 2024 Hora: 2:30 pm a 3:30 pm

**Motivo:** Revisión diagrama de flujo proceso de registro, revisión y aprobación del plan anual de auditoría y diagrama de flujo proceso de planeación, ejecución y aprobación de auditorías internas.

**Enlace Grabación Reunión**
https://udistritaleduco-my.sharepoint.com/:v:/r/personal/hegranadosl_udistrital_edu_co/Documents/Grabaciones/Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n%20de%20Presentaci%C3%B3n%20flujo%20Plan%20de%20Auditor%C3%ADa%20-%20S%C3%ADsifo%20v2-20240910_143727.mp4?csf=1&web=1&e=SnGWyJ&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Saludos.

**Comment by edwargl7** [comment]
Se finaliza la Issue. Muy buena presentación @cjgonzalezp. Se repasó y se cubrieron escenarios importantes para el equipo de desarrollo que nos pueden dar mayor claridad de la finalidad de cada una de las implementaciones que se vienen trabajando y la necesidad de poder reutilizar parte del desarrollo en diferentes etapas de la auditoría.
