### ISSUE TITLE
Ajustes sistema de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#168]
Se requiere realizar la documentación en esta Issue sobre los ajustes y reuniones abordadas entre el equipo SGA y Sísifo sobre cambios en modelo de datos, microservicio, mid y/o microcliente de formularios dinámicos.

**Sub Tareas**

- [x] Documentación cambios requeridos, sugerencias y reuniones establecidas durante la implementación de formularios dinámicos.

**Criterios de aceptación**

- [x] Documentación cambios requeridos, sugerencias y reuniones establecidas durante la implementación de formularios dinámicos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Reunión para aclarar dudas del Modelo de Datos Formularios Dinámicos

Se tuvo una reunión con Andrés, encargado del desarrollo del microcliente de formularios dinamicos por parte de SGA, para aclarar algunas dudas sobre el modelo de datos de `formularios_dinamicos`, llegando a las siguientes conclusiones:

1. **Tabla `elemento_html`**:
   - La tabla `elemento_html` agrega complejidad a la creación de campos, ya que obliga a usar un mid para traducir el JSON del microcliente al microservicio.
   - El frontend ya puede identificar el tipo de campo simplemente enviando `type=text` para un input, lo que simplifica la lógica.
   - Se analizará la necesidad de esta tabla y su relación con `parametros_crud`, evaluando si realmente es útil o si puede ser eliminada para simplificar el flujo.

2. **Endpoint `GET all` para plantillas**:
   - Se requiere un endpoint que devuelva todas las plantillas, de forma que el usuario pueda seleccionar sobre qué versión desea trabajar.
 ```Json
"Data": {
  "modulo_id": "moduloId",
  "formulario_id": "formularioId",
}
```

3. **Campo `Periodo` en el formulario**:
   - Se contempla la posibilidad de integrar un campo de **periodo** en los formularios, por ejemplo: `"Periodo": "2022-1"`.

4. **Etiqueta (`label`) como tipo JSON**:
   - Se concluyó que es más conveniente manejar el campo `label` como un tipo JSON, ya que facilitaría el manejo y la flexibilidad en el frontend.

**Comment by edwargl7** [comment]
En revisión con @fabianbarreto02 y Andrés se revisa la necesidad de agregar un campo para almacenar el periodo.
Se plantea agregar en la raíz el campo periodo.
Y se requiere la creación del endpoint get all que permita además filtrar por periodo.

**Comment by edwargl7** [comment]
Finalizada por este sprint, en caso de requerir más ajustes se creará una nueva Issue.
