### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#169]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente para mockups aprobados por equipos SoS.

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día, 

Se acuerda reunión con cliente para el día lunes 16 de septiembre de 2024 hora: 10:00 am de forma presencial en la sede Paiba.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con cliente el día lunes 16 de septiembre de 2024 hora: 02:00 pm a 4:00 pm. Pendiente terminar de levantar acta de reunión.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se documenta acta de reunión No 137 SISIFO - Levantamiento de requerimientos de la sesión celebrada el dia 16 de septiembre de 2024 hora: 02:00 pm a 04:00 pm. Pendiente recolección de firmas de los presentes en la reunión.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20137%20-%202024%20SISIFO%20-%20Levantamiento%20Requerimientos?csf=1&web=1&e=Jgeaob

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se recolectan firmas de los participantes presentes en la reunión realizada el 16 de septiembre de 2024. Acta No 137 SISIFO - Levantamiento de requerimientos.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20137%20-%202024%20SISIFO%20-%20Levantamiento%20Requerimientos?csf=1&web=1&e=JkQJmF

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp!
