### ISSUE TITLE
Diseño modelo de base de datos - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#17]
Se requiere realizar el diseño inicial del modelo de base de datos basado en las tareas previas del Sprint 0 y Sprint 1, en las que se identificaron los microclientes y se observan los formularios con los campos principales en el diligenciamiento del plan de mejora y cada módulo asociado. Tener presente los diferentes microclientes, dado que de forma similar existirán diferentes microservicios, por lo tanto, no se debe crear un solo diagrama que represente las relaciones entre las tablas como el modelo relacional si no a nivel de microservicios.

**Material de apoyo**
- [Modelo de Datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)
- [División del Cliente Sísifo v1 en Microfrontends - Microcliente Plan mejoramiento PT1](https://github.com/udistrital/sisifo_documentacion/issues/8)
- [División del Cliente Sísifo v1 en Microfrontends - Microcliente Configuración PT1](https://github.com/udistrital/sisifo_documentacion/issues/7)

**Especificaciones técnicas**

1. Se debe crear el modelo de base de datos teniendo presente la división de los microclientes, que dan la base para la separación en microservicios.

**Sub Tareas**

- [x] Diseño de diagrama con el modelo de datos de cada microservicio basado en los microclientes.

**Criterios de aceptación**

- [x] Diagrama con el modelo de base de datos de cada microservicio partiendo de la división de microclientes.

**Requerimientos**

No aplica.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama del modelo de base de datos almacenado en la carpeta de documentación de Sísifo.
- [x] Diagrama como soporte de la issue.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Modelo de Base de datos actual
![odoo-ud - public - plan_mejoramiento_accion](https://github.com/udistrital/sisifo_documentacion/assets/50187485/ab71ba70-863e-4fb6-b875-b665060377aa)

**Comment by jucastro94** [comment]
se presentan avances 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7edaf75c-1bad-45cd-ac9a-29f3b3c12109)

**Comment by edwargl7** [comment]
Se adjuntan los enlaces de los repositorios que se usan para la gestión de documentos. Para tenerlo presente en el manejo de adjutos de las evidencias de avances.
https://github.com/udistrital/documentos_crud
https://github.com/udistrital/gestor_documental_mid

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7181a06d-a06e-48c4-aec2-672ab60a18c4)

**Comment by jucastro94** [comment]
base de datos, diagrama general


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/6b6e1d57-06ef-47d9-90a6-2e55972e547d)


base de datos distribuida


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/764c19a2-3802-4219-be7c-c2bac3daf449)



url archivo de base de datos .draw
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EcdIgSyoXX1Fk-MfUiWny6YBVPZgQlDo6_82wugRFHHMkQ?e=WSovZA

**Comment by edwargl7** [comment]
Excelente trabajo, se realiza un primer diseño del modelo de base de datos que cuenta con una primera revisión por el arquitecto, en el que se plantea la posibilidad de usar MongoDB, el modelo planteado permite usar una base de datos relacional o no relacional. Una vez definida la base de datos a usar se realizará el ajuste del modelo según corresponda.
