### ISSUE TITLE
Diseñar diagrama de flujo del módulo plan de mejoramiento

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#170]
Se requiere realizar el diagrama de flujo del módulo de plan de mejoramiento

**Sub Tareas**

- [x] Repasar la documentación relacionada
- [x] Proyectar el diseño del diagrama con roles y estados.
- [x] Presentar al equipos SoS diagrama de flujo
- [x] Refinar diagrama de acuerdo con comentarios
- [x] Presentar al cliente para aprobación 

**Criterios de aceptación**

- [x] Diagramas de flujo aprobado equipo SoS y cliente
- [x] Diagrama de flujo documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza una investigación y se diagrama el flujo del proceso de aprobación del plan de mejoramiento de las auditorías registradas en el sistema ARGO V2 según vigencia.

**Diagrama de Flujo Proceso Plan de Mejoramiento**
![Image](https://github.com/user-attachments/assets/acbfaaa9-73c6-43a4-a36f-c7c4104c293a)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Diagramas/DIAGRAMAS%20PLAN%20DE%20MEJORAMIENTO?csf=1&web=1&e=po9KMW

Saludos.

**Comment by jcmurilloa** [comment]
Revisaremos al detalle en el review, buen trabajo!

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente refinación de estados según lo repasado en el review.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes de acuerdo a sugerencias por parte del usuario y el equipo SoS en reuniones anteriores.

![Image](https://github.com/user-attachments/assets/b0d5982a-11e0-42e1-b502-5cd1291a8d99)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Diagramas/DIAGRAMAS%20PLAN%20DE%20MEJORAMIENTO?csf=1&web=1&e=Obc1kt
 
Saludos.

**Comment by edwargl7** [comment]
Se revisará el flujo en la siguiente reunión de planning y review.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente mostrar diagrama al cliente y aprobar.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta diagrama de flujo para el proceso plan de mejoramiento con los ajustes solicitados por el equipo SoS y cliente y se recibe aprobación bajo el **acta No 145/2024** para la implementación del módulo en el sistema SISIFO V2.

**Enlace acta de reunión No 145/2024 SISIFO - Levantamiento de requerimientos**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Lqccbu

Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp!
