### ISSUE TITLE
Ajustes en microservicio de histórico roles para remover tabla de sistema de información

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#171]
Se requiere realizar el ajuste en el ms de histórico crud para remover la tabla y controladores asociados a dicha tabla. También remover la referencia directa de roles a la tabla de sistema y ahora espera el controlador un id de sistema.

**Sub Tareas**

- [x] Actualizar modelo de datos eliminando tabla de sistema_información.
- [x] Verificar tipo de relación en la tabla rol para remover posible referencia foránea con sistema.
- [x] Eliminación tabla (actualizar migración base para evitar migraciones de eliminación adicionales).
- [x] Eliminar modelo, controlador, servicio del ms.
- [x] Actualizar consulta por sistema_id.  
- [x] Actualizar pruebas unitarias y de integración relacionadas con sistema_información.
- [x] Actualizar swagger.
- [x] Actualizar README con modelo de datos.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de cambios efectuados y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actualiza modelo de datos, se reemplazan archivos de modelo de datos en carpeta docs y  se actualiza README con la nueva version
![Image](https://github.com/user-attachments/assets/a88fec95-72aa-4f7c-8c98-c3f7f80f821d)

**Comment by edwargl7** [comment]
Modelo actualizado correctamente, agregar nota de aclaración del campo sistema_informacion_id relacionado con parametros_crud.

**Comment by jucastro94** [comment]
se corrige modelo de datos
![Image](https://github.com/user-attachments/assets/10d5485b-2372-43a0-a1f8-5821604a9c94)

**Comment by jucastro94** [comment]
se elimina referencia a sistema_informacion en el route
![Image](https://github.com/user-attachments/assets/49769f39-dd8c-4902-8f80-47725152d166)

se limina sistema_informacion de controller, service y model
sistema_informacion

![Image](https://github.com/user-attachments/assets/a17e9cbf-8940-4841-8977-bf06421601cd)
![Image](https://github.com/user-attachments/assets/55ed4b58-0b13-42e1-8b87-f2c8352fd5f7)
![Image](https://github.com/user-attachments/assets/11462c57-8d71-41b0-b5a9-836b6cde830e)


se modifica modelo rol, para eliminar referencia a FK y cambio de tipo de dato 
![Image](https://github.com/user-attachments/assets/1bdcdea9-c22b-438d-b70d-f80c9875005d)


se modifica query para consulta de periodos por sistema
![Image](https://github.com/user-attachments/assets/47e8f3f7-57dc-4083-ae75-623bf3a7cb20)

**Comment by jucastro94** [comment]
se elimina referencia a SistemaInformacion para llenado de informacion en el retorno, modelo periodo_rol_usuario
![Image](https://github.com/user-attachments/assets/474f616a-3f69-4b19-827b-c7cc729462cc)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

**crud USUARIO**

![Image](https://github.com/user-attachments/assets/a2d1b5ae-4620-4d17-aa70-fc2158446ec4)

![Image](https://github.com/user-attachments/assets/be002504-0321-4090-9dc8-05e06c6835b9)
![Image](https://github.com/user-attachments/assets/994ea554-c8b8-490c-ba8a-a0f857fd8926)
![Image](https://github.com/user-attachments/assets/e03e82e9-a8ba-443a-b195-30ee0b447815)
![Image](https://github.com/user-attachments/assets/4cb5b69e-42c8-45e1-ae3b-7cb95a7aebd5)
![Image](https://github.com/user-attachments/assets/6a250619-6207-4bae-b593-85782c16cd1a)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

crud ROL

![Image](https://github.com/user-attachments/assets/8207426b-a644-416c-b106-3718a31ca508)
![Image](https://github.com/user-attachments/assets/c00e7af8-9896-47aa-8044-45192d5a27d3)
![Image](https://github.com/user-attachments/assets/e35c586e-0600-4bfd-bfb0-df91932dc147)
![Image](https://github.com/user-attachments/assets/552ff048-c233-45c0-af47-7a1286066cf3)
![Image](https://github.com/user-attachments/assets/0e93a396-3dac-4997-b8a3-cfb75f7dcf1f)
![Image](https://github.com/user-attachments/assets/96625ef2-1164-43f7-985e-53efdb800b41)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales 

crud **PERIODOS-ROL-USUARIOS**

![Image](https://github.com/user-attachments/assets/8ea774b7-82a4-49c7-9e40-93fe52f06813)
![Image](https://github.com/user-attachments/assets/0a70a214-0d9c-4bf0-8e45-8b902f75672c)


se presenta error en GetById
![Image](https://github.com/user-attachments/assets/0fae9b18-76f2-4234-8845-003d357abbcc)

**Comment by jucastro94** [comment]
se corrige error eliminando referencia a sistema de informacion metodo de getById en modelo PERIODOS-ROL-USUARIOS 
![Image](https://github.com/user-attachments/assets/4a364af0-ee53-4354-8ba3-728bf7278c61)
![Image](https://github.com/user-attachments/assets/2e618fed-8275-45d9-b366-c50749fbe761)
![Image](https://github.com/user-attachments/assets/53deed85-88c0-4eba-a29b-ca7f7efa75bd)
![Image](https://github.com/user-attachments/assets/5390e495-8719-47a7-80cc-3ff8dc557987)
![Image](https://github.com/user-attachments/assets/818441d0-d76f-4de1-9795-38093473dd66)

**Comment by edwargl7** [comment]
Modelo de datos presentado en kb al equipo DBA y aprobados ajustes.
Se puede cambiar el nombre del SCHEMA de usuario_rol_db a historico_rol_usuario.
Muy buena implementación y pruebas documentadas.
