### ISSUE TITLE
Ajustes microservicio de plantillas formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#172]
Se requiere realizar ajustes sobre el microservicio de plantillas de formularios dinámicos basado en los cambios requeridos e identificados en la implementación del microcliente. Issue asociada #168 

**Sub Tareas**

- [x] Ajuste de modelo de datos eliminando la colección de elemento HTML y eliminar la referencia del campo elemento_html_id de campo.
- [x] Agregar campo de periodo_id como number en la colección de formulario.
- [x] Agregar el campo tipo como string en la colección campo.
- [x] Detallar en el modelo que sistema_id va a ser de parametros_crud.
- [x] En el MS eliminar controladores, servicios y pruebas unitarias asociadas a la colección elemento HTML. Incluyendo los ajustes para el componente de campo.
- [x] Implementación nuevo controlador para listar las versiones de formularios teniendo presente los query_params query, filter, limit, sort, order y offset. Adicional campo metadata con contador de registros totales.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de la Issue con ajustes requeridos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizaron los ajustes solicitados al modelo de datos.

![_Modelo de datos - formularios dinámicos-versión 9 drawio](https://github.com/user-attachments/assets/99302bbf-c44a-4463-925c-b2531b0400d4)


[Modelo de datos - formularios dinámicos V9](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYEeFz6FjYZDjLJ67G_QZ4YB70BvbEIKqb6XKDeaGSm_-Q?e=aBEs6S)

**Comment by CristianCGutierrezG** [comment]
### Cambios en el Microservicio

Se realizaron los ajustes solicitados en el microservicio:

1. **Eliminación de la colección `elemento_html`**

2. **Agregar el campo `periodo_id`**

![image](https://github.com/user-attachments/assets/b5f32512-8320-4010-a9ea-11225afb1560)

3. **Agregar el campo `tipo`**

![image](https://github.com/user-attachments/assets/8614c18e-8d70-45bb-9f1f-99f241756c11)

4. **Realizar cambios en el servicio de plantillas para no utilizar "elementos_html" y evidenciar los nuevos campos**

![image](https://github.com/user-attachments/assets/d768154a-735b-4a79-8a12-3ffe7a5c17fd)

![image](https://github.com/user-attachments/assets/3e57e865-d9a3-4ad2-990a-e31615796897)

**Comment by CristianCGutierrezG** [comment]
###  Implementación nuevo controlador para listar las versiones de formularios

Se desarrolla el nuevo servicio y controlador `getAllTemplate` para obtener informacion de todos los formularios creados teniendo en cuenta los query_params 
![image](https://github.com/user-attachments/assets/d6c9541e-6109-403f-a39a-58745e52cad2)

Se realizan pruebas con algunos ejomplos de query_params 

![image](https://github.com/user-attachments/assets/fb87e958-30f4-4141-abb5-d2d658f01114)

![image](https://github.com/user-attachments/assets/59ef6266-2bfd-463b-b413-21a90c10e9b1)

![image](https://github.com/user-attachments/assets/e07900e2-2657-4bf4-978c-d9ccb1d6c723)


Se realiza un cambio al get de versiones para ser más preciso y evitar conflicto de rutas

![image](https://github.com/user-attachments/assets/3b1c4613-df73-4d1f-8d1e-ec972da4c325)

**Comment by CristianCGutierrezG** [comment]
Se agregan los campos `version` y `version_actual` en la respuesta del GetAll

![image](https://github.com/user-attachments/assets/254390ba-3a50-4650-8546-bbd6e300d433)

**Comment by edwargl7** [comment]
Pendiente revisar endpoint Get One y Get All para unificar rutas.

**Comment by edwargl7** [comment]
Ajustes implementados correctamente, socializar con Andrés los cambios realizados por favor. Pendiente revisión endpoint nuevo vs endpoint de lista de plantilla detallada.
Revisando parte de la implementación se observa que al remover la tabla de elementos HTML, la cantidad de validaciones se puede reducir, por lo tanto, se puede evaluar la lógica de mantener transaccional los registros, puede replantearse dado que la posibilidad de fallos al registrar campos disminuye.
Muy buen trabajo.

**Comment by CristianCGutierrezG** [comment]
Se hacen ajustes en el nombre del endpoint get para ser mas claros
![image](https://github.com/user-attachments/assets/9b21b8f1-b73f-420e-891e-42fe0f3e53a1)

Get /plantillas : informacion de todas las plantillas disponibles

![image](https://github.com/user-attachments/assets/bc1897e3-5c9e-4903-a186-5b7630dd1d10)

Get /plantillas/versiones: informacion de un plantilla en especifico segun la versión

![image](https://github.com/user-attachments/assets/5a95572f-5dd9-4086-83f0-31b197035b77)
