### ISSUE TITLE
Ajuste esquema base de datos microservicio histórico roles usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#175]
Se requiere realizar el ajuste en el nombre del esquema de la base de datos de usuario_rol_db a historico_rol_usuario.

**Sub Tareas**

- [x] Actualización de nombre de esquema y scripts de creación de BD.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación ajustes y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actualiza script de creacion y se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/a864c19f-46d9-4207-a2c7-ee03aef78053)
![Image](https://github.com/user-attachments/assets/f87a6f57-e26d-4c14-9ba2-d1ea4b773360)

**Comment by edwargl7** [comment]
Revisado y resuelto el PR.

**Comment by edwargl7** [comment]
Se requieren ajustes adicionales que se trabajaran en esta Issue.

**Comment by jucastro94** [comment]
se realizan validaciones de endpoints 

![image](https://github.com/user-attachments/assets/127397f6-835e-4b20-97e2-a4bd359268da)
![image](https://github.com/user-attachments/assets/a70f5ba2-7bf8-4c83-9261-5b55ba2a3a7e)
![image](https://github.com/user-attachments/assets/c7148459-40bd-4ef4-9ed6-ff24281e6a6e)
![image](https://github.com/user-attachments/assets/7675e02a-1c18-4735-a50c-4144a92a7082)
![image](https://github.com/user-attachments/assets/a9fcabc4-0e4c-4661-88c8-1356f4ee1220)

**Comment by edwargl7** [comment]
Se renombra el repositorio para evitar fallos al desplegar, y se solicita el apoyo en las pruebas que ya fueron documentadas. Se finaliza la Issue. Muy buen trabajo.
