### ISSUE TITLE
Pruebas funcionales del microcliente de histótico roles con microservicio histórico usuarios roles crud en ambiente de pruebas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#176]
Se requiere realizar las pruebas funcionales del microcliente de histórico roles en local tomando las variables del ambiente de pruebas de autenticación mid e histórico_roles despleado en ambiente de pruebas. Donde se valide el correcto funcionamiento.

**Sub Tareas**

- [x] Actualización variables de entorno y validación del correcto funcionamiento del microcliente con la integración de los microservicios en ambiente de pruebas.

**Criterios de aceptación**

- [x] Documentación de los resultados obtenidos de las pruebas funcionales.

**Requerimientos**

- Issue #194

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Avance pruebas de funcionamiento

Se realiza el ajuste en las variables de entorno para consumir los servicios desplegados de historico_roles y autenticación

### Creación de usuarios

Se realiza correctamente la busqueda del usuario ingresado y trae los datos necesarios:

![Captura de pantalla 2024-10-09 a la(s) 8 16 49 p m](https://github.com/user-attachments/assets/999a7624-0ad5-4128-96d9-74873605cc9c)

Se realiza la asignación de un rol y las fechas y se genera el siguiente error:

![Captura de pantalla 2024-10-09 a la(s) 8 24 48 p m](https://github.com/user-attachments/assets/b991c37d-c576-4077-aa78-b90c3ee1bf6f)

![Captura de pantalla 2024-10-09 a la(s) 8 24 33 p m](https://github.com/user-attachments/assets/8afbf42c-c9a0-404f-9f23-7d98ec6b5eae)

### Consulta de usuarios

La consulta sin filtro funciona correctamente al igual que la paginación

![Captura de pantalla 2024-10-09 a la(s) 8 06 08 p m](https://github.com/user-attachments/assets/bfffc38d-3e2f-4db6-8619-0ae1e5f18743)

![Captura de pantalla 2024-10-09 a la(s) 8 06 22 p m](https://github.com/user-attachments/assets/c69b1cae-b708-4500-b12e-300ab613aee7)

La consulta por filtro de documento funciona correctamente

![Captura de pantalla 2024-10-09 a la(s) 8 12 45 p m](https://github.com/user-attachments/assets/822804f3-b862-40aa-b6dd-0743263db87d)

### Actualización de usuario

Al hacer click en el botón de editar se redirige correctamente la información del usuario a la ventana de actualización:

![Captura de pantalla 2024-10-09 a la(s) 8 06 40 p m](https://github.com/user-attachments/assets/693cf0e9-1ff3-44b8-831e-ea8731a26d7b)

**Comment by edwargl7** [comment]
Se va a realizar la revisión con el arquitecto para determinar si puede ser el fallo de CORs por configuración del APIGateway.

**Comment by alexhrr** [comment]
## Pruebas de funcionamiento

Se continúa con las pruebas de funcionamiento para las funciones de creación y actualización de usuario con un nuevo usuario de prueba que no se encuentra registrado previamente.

### Creación de usuario

Se crea el usuario con el rol de auditor:

![2](https://github.com/user-attachments/assets/89b8082a-b687-423b-959e-936be2c4eb47)

![1](https://github.com/user-attachments/assets/2f14aec4-0a72-4087-84ae-91792de279ec)

### Consulta usuario creado

Se verifica que los datos se hayan registrado correctamente:

![3](https://github.com/user-attachments/assets/c2409041-380b-4f67-a735-54fad3a01a53)

### Actualización del periodo

Con los permisos de edición se accede a la actualización y se finaliza el periodo del usuario:

![4](https://github.com/user-attachments/assets/24078dbd-f5e8-4d7f-ac89-d7692f300830)

![5](https://github.com/user-attachments/assets/6a084e04-f907-4310-9d55-c3e920660834)

Finalmente se verifica la finalización del periodo desde la consulta:

![6](https://github.com/user-attachments/assets/08c427fd-6e6a-4b29-9ace-e6128bde83cc)


En la ejecución se encuentra que se debe manejar la creación de usuario cuando el usuario ya ha sido creado previamente, ya que se genera un error al intentar crearlo.

**Comment by edwargl7** [comment]
Muy buenas pruebas, se pueden complementar estos escenarios adicionales de creación y listado en autenticación mid de usuarios cuando no existe en terceros para evitar fallos.
