### ISSUE TITLE
Empalme desarrollo sistema de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#177]
Se requiere realizar la reunión de revisión de almacenamiento de datos para determinar si se requieren campos adicionales en el modelo de datos y microservicio de plantillas de formularios dinámicos. También reunión de empalme sobre desarrollo del microcliente.

**Sub Tareas**

- [x] Revisión almacenamiento de datos recolectados por el formulario dinámico con SGA.
- [x] Empalme microcliente de formularios dinámicos con SGA.

**Criterios de aceptación**

- [x] Participación en las reuniones y documentación de cada caso.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Implementar go rutinas o hilos, y hacer rollback en caso de fallo.
El microcliente almacena el servicio, endpoint y campo.
El MID procesa las rutas y mapeo.
Agrupamiento de campos por endpoint.
Campo de validación si debe agrupar o no.

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/da278f5f-d68f-4782-9ff9-7b97ee1fad9b)

**Comment by edwargl7** [comment]
```
{
    "pipe": [
        {
            "orden": 1,
            "sistema": "SGA",
            "endpoint": "tipo_evaluacion",
            "result": "Data"
        },
        {
            "orden": 2,
            "sistema": "SGA",
            "endpoint": "evaluacion",
            "structure": {
                "tipo_evaluacion_id": "SGA.tipo_evaluacion.Data.id"
            },
            "result": "Data.id"
        }
    ]
}


{
    "pipe": [
        {
            "orden": 1,
            "sistema": "SGA",
            "endpoint": "tipo_evaluacion",
            "result": "Data"
        },
        {
            "orden": 2,
            "sistema": "SGA",
            "endpoint": "evaluador",
            "result": "Data"
        },
        {
            "orden": 3,
            "sistema": "SGA",
            "endpoint": "evaluacion",
            "structure": {
                "tipo_evaluacion_id": "SGA.tipo_evaluacion.Data.id",
                "evaluador_id": "SGA.evaluador.Data.uuid"
            },
            "result": "Data.id"
        }
    ]
}

{
    "pipe": [
        {
            "orden": 1,
            "sistema": "SGA",
            "endpoint": "informacion_complementaria",
            "structure": {
                "tercero_id": "metadata.user_id",
                "info_compl_id": "SGA.evaluador.telefono.referencia_id",
                "evaluador_id": "SGA.evaluador.Data.uuid"
            }
        },
        {
            "orden": 2,
            "sistema": "SGA",
            "endpoint": "informacion_complementaria",
            "referencia": 12,
            "result": "Data"
        },
        {
            "orden": 3,
            "sistema": "SGA",
            "endpoint": "evaluacion",
            "structure": {
                "tipo_evaluacion_id": "SGA.tipo_evaluacion.Data.id",
                "evaluador_id": "SGA.evaluador.Data.uuid"
            },
            "result": "Data.id"
        }
    ]
}
```

**Comment by CristianCGutierrezG** [comment]
## Revisión de Almacenamiento de Datos Recolectados por el Formulario Dinámico

En la reunión de revisión para almacenamiento de datos recolectados por el formulario dinámico se discutieron varias ideas y soluciones para el problema. A continuación, se presenta un compendio de las ideas más relevantes:

- La opción 1 planteada en la issue #96 parece ser la más óptima para almacenar los datos, pero la mayor complicación surge al reestructurar los datos en el envío al cliente

![image](https://github.com/user-attachments/assets/854d4b82-8506-4c3c-ae53-017daa99e8a6)

### Controlador en el Cliente
- El cliente debe implementar un controlador que gestione la distribución del formulario y determine en qué servicio se almacenará la data.

### Estructura Mapeadora
- Este controlador debe mapear la estructura del formulario para coordinar el flujo de datos entre el servicio y la plantilla JSON correspondiente.
- Se requiere una estructura que parametrice cada campo con su respectivo servicio y endpoint.
- Un booleano indicará si el campo es parte de un grupo o es simplemente metadata.
- Se deben considerar casos donde varios campos compartan el mismo controlador y donde un mismo campo pueda repetirse en diferentes servicios o endpoints.

###  Funciones del MID
- **Obtener datos** desde los servicios según la parametrización definida.
- **Construir la estructura** basada en la plantilla JSON de destino, asignando los datos a los servicios y endpoints correspondientes.
- Implementar **hilos en Python** o **Go rutinas** para gestionar múltiples solicitudes simultáneamente y mejorar la eficiencia.
- Implementar mecanismos de **rollback** en caso de fallo, para garantizar la integridad de los datos.

###  Parametrización de los Campos
- Es importante que los campos del formulario estén asociados de manera clara a los servicios y endpoints definidos, y que personal capacitado esté involucrado en el proceso de configuración.
- Se consideraron casos complejos en los que los campos necesitan información de servicios de terceros o dependen de varias tablas.

### Metadatos y Auditoría
- Registrar información sobre el usuario que completó el formulario, junto con la fecha y hora

### Casos Especiales
- Se debe considerar la posibilidad de que algunos campos requieran información previa o adicional para su correcto mapeo y presentación en el formulario. Por ejemplo, algunos campos pueden depender de múltiples tablas, como en el servicio de Terceros, lo que complica la obtención de datos.
- Se considera guardar información sobre qué usuario registró el formulario y en qué momento.

**Comment by CristianCGutierrezG** [comment]
Para implementar el cambio de posición, se optó por la opción 5 planteada en la issue #174.

### Paginado con opción de elegir cambio de posición por número de índice:

- Se agregó una nueva columna editable para cambiar el orden de las filas.
-  Para ver el cambio en la estructura del array, se imprime temporalmente en la consola.

![image](https://github.com/user-attachments/assets/0846bd25-674a-4745-ab20-a27d18e80449)

![image](https://github.com/user-attachments/assets/bdb3852c-8251-48bf-acc7-89bc486a413f)

![image](https://github.com/user-attachments/assets/70d65155-6777-4009-83d2-b62ae4c1c47e)

![image](https://github.com/user-attachments/assets/c57c09f6-4749-4257-88b0-04e552aaeebd)

**Comment by CristianCGutierrezG** [comment]
Se tuvo una reunión con Andrés de SGA en la que se aclaró el funcionamiento del endpoint `GET ALL` de plantillas y se realizo el empalme del microcliente de formularios dinámicos con las nuevas características:

- Búsqueda de formularios según el módulo, servicio y período.
- Visualización del formulario activo, con opciones de previsualización, edición y visualización.
- Mejoras en el manejo de validaciones al construir formularios.

**Comment by edwargl7** [comment]
Se finaliza la Issue dado que se cubrió en ella lo relacionado a la integración y evaluación requerida para el sistema de formularios dinámicos. Muy buen trabajo.
