### ISSUE TITLE
Implementación acción eliminación en microcliente de histórico roles usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#179]
Se requiere realizar la implementación de la funcionalidad de la acción de eliminación para una eliminación lógica del registro del periodo. Para esto se requiere la implementación del modal de confirmación de la eliminación.

**Sub Tareas**

- [x] Implementación acción de eliminación lógica de un periodo.
- [x] Implementación modal de pregunta para confirmación de eliminación.
- [x] Implementación modal de eliminación realizada o fallida.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación del avance de la Issue y resultado de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance eliminación roles

Se realiza la implementación de la eliminación lógica para el microcliente de gestión de usuarios y se agrega el modal de confirmación de eliminación y el de error en la eliminación:
 
 Se verifica el estado inicial del periodo a eliminar, estado activo = true:
 
![Captura de pantalla 2024-09-16 a la(s) 9 20 17 p m](https://github.com/user-attachments/assets/c866a3cb-cd2b-4728-ae88-846c1234cd58)

Se agrega la función al botón de eliminar en las acciones:

![Captura de pantalla 2024-09-16 a la(s) 9 39 15 p m](https://github.com/user-attachments/assets/4df582f6-0231-4df6-a4c4-36abd19ced0e)

Se implementa el modal de confirmación para la eliminación del periodo:

![Captura de pantalla 2024-09-16 a la(s) 9 39 32 p m](https://github.com/user-attachments/assets/14d873c1-8d92-42f7-96bb-f983bd0bcc13)

![Captura de pantalla 2024-09-16 a la(s) 9 39 42 p m](https://github.com/user-attachments/assets/4d30f6ac-b977-4d42-bbea-eb3fce0c8c26)

Se verifica nuevamente el estado del periodo:

![Captura de pantalla 2024-09-16 a la(s) 10 00 13 p m](https://github.com/user-attachments/assets/9ff62097-b9de-4960-af3b-066430fd5053)

Se agrega el modal en caso de que se presente algún error en la eliminación:

![Captura de pantalla 2024-09-16 a la(s) 9 43 54 p m](https://github.com/user-attachments/assets/796d447a-aa80-412f-8423-6c59c3bcc8e8)

**Comment by edwargl7** [comment]
@cjgonzalezp nos puedes ayudar a revisar los mensajes de los modales por favor.

**Comment by alexhrr** [comment]
Se modifican los textos de los modales indicando la eliminación del periodo y no del usuario:

![Captura de pantalla 2024-09-17 a la(s) 8 25 34 p m](https://github.com/user-attachments/assets/a0d0e12e-e6c8-4959-b114-5a1961c1876f)

![Captura de pantalla 2024-09-17 a la(s) 8 22 24 p m](https://github.com/user-attachments/assets/a7cd9d58-e9c9-4c4d-ab61-3492454c165d)

![Captura de pantalla 2024-09-17 a la(s) 8 21 10 p m](https://github.com/user-attachments/assets/a9f86171-0ca7-4119-8a65-ae635b1efdcb)

Se realiza el ajuste quitando las opciones del menu de acciones, para que los usuarios que tengan el periodo finalizado no puedan realizar ninguna acción.

![Captura de pantalla 2024-09-17 a la(s) 8 20 52 p m](https://github.com/user-attachments/assets/94ae192a-c1bd-4a0c-ba39-afee61169110)

**Comment by edwargl7** [comment]
Se realiza la revisión con @cjgonzalezp y se sugiere cambiar el icono del modal de error al eliminar de warning a error.

**Comment by alexhrr** [comment]
Se realiza el cambio de icono para el modal de error de eliminación.

![Image](https://github.com/user-attachments/assets/48335dc1-7fa0-41f6-aa0c-d67849c98261)

**Comment by edwargl7** [comment]
Se resuelve el PR. Muy buen trabajo.
