### ISSUE TITLE
Revisión y ajustes del modelo de base de datos parte 1 con DBAs

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#18]
Se requiere realizar la revisión y ajustes del modelo de base de datos de Sísifo v2 con el equipo DBA para garantizar el correcto diseño, evitar la creación de tablas que puedan ser reemplazadas en su lugar por otros servicios que manejen estos datos y la posibilidad de generar servicios que gestionen datos que puedan ser transversales y que actualmente no existan.

**Sub Tareas**

- [x] Reunión con el equipo DBA para la revisión
- [x] Realizar los ajustes requeridos en el diagrama realizado en la Issue [Diseño modelo de base de datos - Parte 1](https://github.com/udistrital/sisifo_documentacion/issues/17)

**Criterios de aceptación**

- [x] Participación en la reunión de revisión
- [x] Realizar los ajustes sugeridos
- [x] Actualización del diagrama en la carpeta de documentación

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama actualizado y cargado en la documentación.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan ajustes a al modelo de BD y se genera version 2 del modelo



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c325bd18-123f-4164-9073-73f804fc246e)
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/46d8f642-5d1d-4b62-ba4c-48883d8a84b0)

se adjunta URL del archivo .draw 

https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ER8gJHX0WyBAr_zTjpjLf4QBxG5M2z1IKDkSRx7Jty32cQ?e=8i9ema

**Comment by edwargl7** [comment]
Excelente trabajo, se remueven las tablas paramétricas. Se realizará el ajuste una vez definido si se realizará una base de datos relacional o no relacional.
