### ISSUE TITLE
Empalme sistema de renderizado de plantillas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#180]
Se requiere realizar el empalme del estado de los microservicios que conforman las plantillas para documentos PDF y para correos con el equipo de SISGPLAN. Además, se requiere realizar el despliegue del microservicio de renderizado y las respectivas pruebas funcionales una vez desplegado.

**Sub Tareas**

- [x] Participación reunión de empalme con equipo SISGPLAN y documentación en la Issue de aspectos importantes a tener presente.

**Criterios de aceptación**

- [x] Documentación de los resultados de las pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
- se realiza reunion para empalme de sistema de renderizado de plantillas
- fue compartido el backlog para los documentos de informe tecnico, informe de diagnostico, y cierre de plantillas https://github.com/orgs/udistrital/projects/66/views/1

- se debe evaluar como se han estado registrando los sistemas de informacion en parametros para terminar de realizar la conexion del filtrado entre en mf y el ms

- se debe realizar realizar analisis del mf ya que esta construido como un monolito y adecuarlo para que sea en microfront end

- se debe realizar verificacion de la herramienta que se utilizo y su implementacion para evitar sql injection

- se dejan los 3 servicios en fase develop para evitar errores mientras se finaliza su desarrollo

- se deja la base de datos ya montada

- como se implemento otra herramienta diferente a renderizado_plantillas_html, se debe suspender el despliegue de este ms

**Comment by jucastro94** [comment]
grabacion de la sesion

https://udistritaleduco-my.sharepoint.com/:v:/g/personal/computo_udistrital_edu_co/EfeqkMWtO9tNoeSRT9p9whABKZIrD7xeWpiKM7N9pb3XXw?e=d30lfN

**Comment by edwargl7** [comment]
Se puede realizar la revisión del registro de la plantilla creada en la Issue #185 en el microservicio serverless desplegado en caso de encontrar fallas que no permitan completar correctamente las pruebas funcionales de la Issue #157

**Comment by edwargl7** [comment]
Se finaliza la Issue dado que fue requerido ajustes en la Issue #157.
