### ISSUE TITLE
Investigación cargue masivo desde archivo csv o xlsx con serverless

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#181]
Se requiere continuar con la investigación de cargue masivo requerida para cargue de actividades de auditoría. Dado que no va a ser de una frecuencia de uso constante se requiere realizar la investigación de la viabilidad de la implementación de este mediante serverless y la posibilidad de usar concurrencia en el procesamiento de cada registro.

**Sub Tareas**

- [x] Investigación tecnología a emplear usando serverless.
- [x] Investigación posibilidad de implementación de concurrencia en serverless y dado que requiere registrarlos por medio de endpoints que debe tenerse presente para realizar múltiples peticiones sin bloquear el servicio receptor.
- [x] Prueba de concepto.

**Criterios de aceptación**

- [x] Documentación de avances en la investigación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Avance investigación cargue masivo

Tecnologias a usar para serverless:

### AWS Lambda

Amazon S3
Almacenamiento de objetos creado para recuperar cualquier volumen de datos desde cualquier ubicación.

Subida del archivo a S3: El archivo CSV/XLSX se sube a un bucket de Amazon S3.

Trigger de AWS Lambda: S3 activa automáticamente una función Lambda cuando detecta que un archivo ha sido cargado.

Procesamiento del archivo: La función Lambda lee el archivo, lo procesa en lotes (o línea por línea) y registra cada fila en una base de datos.

Si el archivo es muy grande, se puede dividir y ejecutar varias instancias de Lambda en paralelo para procesar diferentes partes del archivo.

**Comment by alexhrr** [comment]
Se continua con la investigación teniendo en cuenta el uso de AWS SAM para el desarrollo.

Lambda tiene un límite de tiempo de ejecución (15 minutos) y memoria (10 GB).

Amazon S3: Es un servicio de almacenamiento en la nube que permite guardar archivos, puede desencadenar otros servicios, como Lambda, cuando se suben archivos.

SQS (Simple Queue Service): Es una cola de procesamiento y se puede usar para manejar la concurrencia y no sobrecargar a Lambda, sqs puede dividir el archivo en multiples mensajes  y luego procesar los mensajes en paralelo.

Por el momento con la información que se tiene actualmente puede ser posible llevar a cabo el cargue masivo usando serverless.

Se está revisando el material suministrado y encontrado para ampliar la información

**Comment by alexhrr** [comment]
Flujo actual para el cargue masivo:

1.	Obtener el archivo desde Nuxeo 

3.	Convertir el archivo según sea necesario:
	Tecnologías:
	•	Go (encoding/base64): Para decodificar los datos de base64 (si es necesario).
	•	Go (encoding/csv): Para trabajar con archivos CSV.
	•	Go (excelize): Para trabajar con archivos XLSX. 

4.	Procesar el archivo fila por fila (usando lambda).
        Tecnologías:
         •	Goroutines: permite manejar la concurrencia
         •	AWS Step Functions: Administra de forma centralizada un flujo de trabajo dividiéndolo en varios pasos

5.	Enviar las peticiones a otro microservicio.
         •	API Gateway: Recibirá las peticiones HTTP y las reenviará al microservicio que procesa los datos.
                permite establecer políticas de limitación de la tasa de solicitudes (rate limiting), lo que asegura que no se sobrecargue el microservicio receptor.

Se realiza la instalación de AWS SAM, AWS SAM CLI y Docker.

**Comment by edwargl7** [comment]
Para la prueba de concepto vamos a usarlo en base64, y usando un API para realizar registros de roles para estimar el tiempo de procesamiento requerido iterando uno por uno los registros del archivo.

Posiblemente se podría usar ngrok para evitar el error en la búsqueda del host en el docker o tener que usar una red si se usa el API en local.

**Comment by alexhrr** [comment]
Se realiza una reunion para definir los pasos a seguir para la elaboración de la prueba de concepto.

Se establece que se va a iniciar con una lectura de unos datos en base 64 para decodificarlos y posteriormente enviarlos a un endpoint para su registro.

Se inicia con la prueba de concepto usando go y sam, sin embargo se encuentran problemas de compilación 

![Captura de pantalla 2024-09-20 a la(s) 11 15 34 p m](https://github.com/user-attachments/assets/484ad277-ca05-49c1-8cec-b6eb25e637a8)

**Comment by alexhrr** [comment]
Se realiza el cambio a otro sistema operativo ya que no se pudo resolver el inconveniente en la compilación.

Ahora usando windows se continua con la prueba de concepto en su parte inicial. Se realiza la decodificación de los datos en base 64 y se muestran por pantalla, para este caso se realiza la simulación de los datos necesarios para la creación de un rol en historico_roles:

![image](https://github.com/user-attachments/assets/74f6d1f7-1481-47e2-99fc-e9bee166f893)

Posteriormente se realiza la creación de un json con los datos decodificados que posteriormente serán enviados al endpoint:

![jsonExample](https://github.com/user-attachments/assets/80d2442d-7b51-4f5f-a41e-66375a2e86df)

El siguiente paso será enviar el json al endpoint correspondiente para realizar el registro del rol.

**Comment by edwargl7** [comment]
Se continuará en la Issue #189
