### ISSUE TITLE
Implementación componente de visualización de PDF en el microcliente plan anual de auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#182]
Se requiere continuar con la implementación del componente transversal para renderizado de PDF trabajada inicialmente en la Issue #154 y basado en la implementación realizada en la [Issue 132 de ARGO](https://github.com/udistrital/argo_documentacion/issues/132) usando ng2-pdf-viewer.

**Sub Tareas**

- [x] Implementación componente para renderizado de PDF.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de avances en la implementación y resultados de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se implementa ng2-pdf-viewer
![Image](https://github.com/user-attachments/assets/ca2b1b8c-84fc-45aa-96fb-893cc1e1aeab)


se realiza importacion al modulo del componente

se integra al component.html
![Image](https://github.com/user-attachments/assets/aa7ce81f-561d-4a53-b1f7-262bbdd1f25a)


se intenta renderizar pdf agregando 'data:application/pdf;base64:.......' al base64 pero no funciona

con base en el ejemplo dado se convierte el documento en base64 a ArrayBuffer y posteriormente este se convierte a Uint8Array, asi dando un correcto renderizado
 ![Image](https://github.com/user-attachments/assets/a8d68a78-ca81-402d-aa42-2d3a796f34e0)


se requieren ajustar estilos

**Comment by jucastro94** [comment]
se ubica renderizador en la parte inferior para verificar como esta funcionando, ocupa el 100% de la ventana y renderiza de manera correcta
![Image](https://github.com/user-attachments/assets/beac65d5-72c4-48bf-be17-6ac8ccbc6cf5)

**Comment by jucastro94** [comment]
se realizan ajustes de css
![Image](https://github.com/user-attachments/assets/a102274f-0ae4-41eb-8add-a0884dc395c0)

**Comment by jucastro94** [comment]
se realizan correcciones para que la visualizacion sea tipo modal

se realiza prueba funcional

https://github.com/user-attachments/assets/4f44a651-467a-4778-909d-7df719d6850c

**Comment by edwargl7** [comment]
Se realiza la revisión con @cjgonzalezp y se observa que dado que se requiere poder llegar a esta vista desde un enlace de correo, se debe modificar como submódulo para poder tener un enlace que lo dirija específicamente al plan que se va a revisar por el id del mismo, dado que los modales se visualización dentro de la misma url del componente principal, no se lograría de esta forma el comportamiento requerido.

![image](https://github.com/user-attachments/assets/11e627b2-79a0-4603-90ee-b042fa528333)

Ejemplo URL:
/plan_auditoria/revision/10

**Comment by edwargl7** [comment]
Esta vista también puede ser consultada desde la tabla de consulta.
![image](https://github.com/user-attachments/assets/e457d145-5edc-438b-8002-4e62a9bd51f7)

**Comment by jucastro94** [comment]
se deshace ultimo commit 
se borra boton de cerrar
se realiza prueba funcional

https://github.com/user-attachments/assets/90bad525-fd14-493d-8638-2ff5e94a5a28

**Comment by edwargl7** [comment]
Se realiza la revisión con @cjgonzalezp y se va a evaluar la forma de poder acceder a la vista de consulta.

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR.
