### ISSUE TITLE
Creación documento de avance por módulo, submódulo o funcionalidades de Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#183]
Se requiere realizar la creación de un documento que permita desglosar los módulos, submódulos y/o funcionalidades y reportar el avance y pendientes frente a cada uno, con el fin de obtener una mejor claridad del avance del proyecto, identificar bloqueos o pendientes a nivel del análisis, diseño e implementación.
Se propone para ARGO la siguiente estructura, que puede servir de base para Sísifo:
![image](https://github.com/user-attachments/assets/74d78665-254e-417e-a9c4-149e691cf41f)

**Sub Tareas**

- [x] Documentación de cada módulo, submódulo y o funcionalidad para cada fase de Sísifo.

**Criterios de aceptación**

- [x] Documento con registro de los módulos y avance del proyecto, junto con los pendientes que existan.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se inicia creación de documento de avance por módulos, submódulos y funcionalidades

![Image](https://github.com/user-attachments/assets/5dc24a33-40ce-423d-9eff-49e8a0fae181)


Saludos.

**Comment by jcmurilloa** [comment]
A la fecha del review, no se consolida y expone documento final, por favor cumplir con las tareas proyectadas en el sprint.

**Comment by cjgonzalezp** [comment]
Buen día,

Se proyecta crea documento de avance por módulo, submódulo y/o funcionalidades de SISIFO V2.

**Enlace documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Gesti%C3%B3n%20t%C3%A9cnica/Documentaci%C3%B3n%20S%C3%ADsifo%20v2/M%C3%B3dulos%20avance%20S%C3%ADsifo.xlsx?d=w683d78fd868e4be9b0e7d45598f24183&csf=1&web=1&e=MwTRAK


Saludos.

**Comment by jcmurilloa** [comment]
El documento nos permite contar con una ruta de lo pendiente por recopilar para cada una de las fases del proyecto, y programar de esa manera los sprint.
