### ISSUE TITLE
Definición fuente de información requerida para usuarios de Sísifo

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#184]
Se requiere realizar la revisión y consulta de los usuarios requeridos al momento de realizar la asignación del líder y responsable auditado, de tal forma que nos permita identificar si se puede usar para la selección de los usuarios la fuente de terceros o si es necesario identificar otra fuente de información que permita obtener Jefes de dependencias u otros.

Tener presente la revisión para cada tipo:
- Proceso
- Macroproceso
- Dependencia
![image](https://github.com/user-attachments/assets/e80102d5-9e69-4031-8495-6eb470572c01)

**Sub Tareas**

- [x] Revisión e identificación de cada uno de los usuarios que se espera elegir según el tipo seleccionado.
- [x] Definición de fuente, forma de búsqueda (documento de identidad, ...) y criterios a tener presente.

**Criterios de aceptación**

- [x] Documentación de la definición de usuarios requeridos para cada tipo, fuente y criterios a tener presente para permitir la asignación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta con cliente para validar la información solicitada. Pendiente respuesta


Saludos.

**Comment by edwargl7** [comment]
Tener presente si se asigna solo "nombre del cargo" y no un usuario especifico, como se establece la reasignación y notificación en caso que durante el transcurso de esa vigencia el notificado ya no tenga ese rol (vacaciones, cambio, renuncia).

**Comment by jcmurilloa** [comment]
El cliente brindó respuesta alguna? recordemos que se deben generar los respectivos commit a medida que tenemos avance en el sprint!

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta nuevamente con el cliente, se está validando el tema internamente en la Oficina de Control Interno y quedan de enviar respuesta entre martes y miércoles.



Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

El cliente nos confirma que la fuente de información de líder y responsable actualmente la obtienen de la página del SIGUD en cada uno de los procesos, en este sistema solo se detalla el cargo o área asignada como se muestra a continuación.

![Image](https://github.com/user-attachments/assets/8ef0026a-7f66-4dc6-b1fd-a9856c0fbdf2)

Se está validando con funcionamiento si podemos interoperar con otro sistema para traer esta información, que también nos pueda traer el nombre propio de los responsables y los correos institucionales para poder direccionar el flujo de revisión y aprobación dentro del sistema.

**De acuerdo a la información brindada por el cliente, se consolida la tabla de información inicial para la parametrización de los campos líder y responsable**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Parametrizaciones?csf=1&web=1&e=FJ2MDS)?csf=1&web=1&e=FJ2MDS

Por otro lado, se está validando con el líder técnico la información de líder y responsable cuando la auditoría sea para una dependencia.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se define sesión con Cristian Alape de funcionamiento hoy 24 de octubre para las 02:00 pm para revisar la información requerida de los campos líder y responsable y la interoperabilidad con otro sistema.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Cristian Alape de funcionamiento nos dará respuesta mañana, sobre la viabilidad de integrar el sistema SISIFO con SICAPITAL para la parametrización del líder y responsable en la fase de planeación de la auditoría.

![Image](https://github.com/user-attachments/assets/0277a6d7-b54b-4aa3-900f-23e2163356a3)


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día, 

De acuerdo con investigación apoyada con el líder técnico, en los otros sistemas de la Universidad no está parametrizada esta información de lideres y gestores de los procesos actuales. Adicionalmente, se acuerda con el usuario Henry Arenas trabajar directamente con las cuentas de las dependencias o cargos debido a las rotaciones de personal, de este modo se garantizan las responsabilidades de la gestión de las auditorías.

Por lo anterior, se buscará implementar la fuente de información para alimentar los campos líderes y responsables desde el sistema SISIFO V2. Queda pendiente recolectar una parte de los correos de los responsables para completar la información.


**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Parametrizaciones/Lideres%20y%20Responsables.xlsx?d=waad69c5e83b74425bab423f15233de2a&csf=1&web=1&e=9OL2Nk


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, información importante al momento de creación de roles, por favor complementar con los correos pendiente y daremos finalizada la issue.
