### ISSUE TITLE
Actualizar versión microclientes root, plan y usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#186]
Se requiere realizar la actualización de la versión de angular en [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf), [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) y [auditoria_plan_mejoramiento_root_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_root_mf)
**Sub Tareas**

- [x] Actualizar versión de los mf solicitados.
- [x] Pruebas funcionales de los mf una vez realizados la actualizaciones.
- [x] Actualización README.

**Criterios de aceptación**

- [x] Documentación ajustes y pruebas funcionales que garanticen el correcto funcionamiento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se hace upgrade de plan_anual_auditoria_mf

se realizan pruebas funcionales
![Image](https://github.com/user-attachments/assets/fdb13ef2-202a-4b6e-bc2a-ded5ec157bb3)
![Image](https://github.com/user-attachments/assets/3fd8ca8f-e95f-4070-9cd7-25d15afde8a9)
![Image](https://github.com/user-attachments/assets/f9748c62-3a38-4bc9-a44b-5bb5293332cb)

**Comment by edwargl7** [comment]
Se continuará en el siguiente sprint.
