### ISSUE TITLE
Implementación registro de programa en el microcliente de plan anual de auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#187]
Se requiere realizar la implementación del módulo de registro del plan de auditoría. Separando el paso 1 de información usando formularios dinámicos, que permita registrar la información accediendo desde las acciones de la tabla principal (consulta/creación).
Luego mediante otra acción lo dirija a otro componente que cuente con la vista de tabla de actividades y esta incorpore todos las acciones requeridas basado en el mockup. Y que al crear o editar una actividad use otro formulario dinámico.

![image](https://github.com/user-attachments/assets/21f273a4-5d63-429f-ab2b-c28715e295c4)
![image](https://github.com/user-attachments/assets/afc2670d-4b41-4778-8685-fb2c68b5fdf8)
![image](https://github.com/user-attachments/assets/3355185b-2309-4c4f-b0c0-cb30ca0782a7)

Esta solución posiblemente permita alcanzar el objetivo requerido y disminuya la complejidad que se evaluó usando solo formularios dinámicos.

**Sub Tareas**

- [x] Implementación acción de registro de Información.
- [x] Implementación componente de registro de actividades (tabla, botones).
- [x] Integración formulario de registro de información.
- [x] Integración formulario de registro de actividades.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
#### Descarga y Configuración Inicial:
- Se descargan y realizan los pull necesarios en los siguientes microclientes para iniciar el desarrollo:
  - `auditoria_plan_mejoramiento_root_mf/`
  - `formularios_dinamicos_mf`
  - `plan_anual_auditoria_mf`

- Se ejecutan todos los servicios y se revisa la conexión correcta entre todos los microclientes.

#### Ajustes en el Componente de Consulta:
- Se realizan ajustes en el componente `consulta-plan-auditoria` y se agrega la redirección de Editar informe a "/formularios-dinamicos/view-formulario".

![image](https://github.com/user-attachments/assets/1b61c778-b7f0-462f-988a-df56f84afd79)

#### Problemas Encontrados:
1. **Inconvenientes de Rutas entre Microclientes**:

   - Al intentar realizar la navegación entre rutas entre paginas del mismo servicio, se presenta un problema:![image](https://github.com/user-attachments/assets/4ad7186c-16ea-4ff3-999f-796adc0fb4f8)
     - Angular no puede encontrar la ruta que se intenta navegar dentro del módulo de rutas del microfrontend actual. Si la ruta `/formularios-dinamicos/view-formulario` pertenece a otro microcliente, el enrutamiento directo a esa URL desde el microcliente actual puede no funcionar debido a la separación entre microfrontends.


    

3. **Redireccionamiento desde el Navegador**:
   - Se implementa un redireccionamiento desde el navegador, pasando como prueba el ID del plan de ejemplo para verificar el traspaso de datos.
![image](https://github.com/user-attachments/assets/4d21fd80-5358-4aaf-983e-d639ac6d4543)
   - La redirección se realiza de manera exitosa, se cambio el mock de postman para que solo se muestre la seccion especifica de información.
   -   los datos en parámetros de la URL no se pasan correctamente.

![image](https://github.com/user-attachments/assets/92f3a9c7-2d6b-4d50-ad04-fa264dd018bb)


3. **Llenado del Formulario**:
   - Se intenta llenar el formulario con base en el ID recibido usando un mock de prueba; sin embargo, debido a que no se pasa la informacion del ID  y a la forma en que está implementado el formulario dinámico, no se pudo realizar de manera directa.
   - Es necesario revisar cómo obtener los datos asociados a un formulario en concreto para mostrarlos en caso de edición.

**Comment by edwargl7** [comment]
Se requiere revisar con el equipo SGA o Cumplidos como se puede establecer la comunicación entre microclientes para envíar los IDs requeridos para consultar y llenar los formularios basados en el elemento seleccionado.

**Comment by CristianCGutierrezG** [comment]
#### Nueva Ruta para Editar Actividades:
- Se crea una nueva ruta `editar-actividades` para manejar la tabla dependiendo del plan seleccionado.
- Esta ruta se conecta con el microservicio de formularios dinámicos al añadir una nueva auditoría.

#### Implementación de Drag and Drop:
- Se intenta implementar la funcionalidad de **drag and drop** para reorganizar los elementos en la tabla. Sin embargo, se presentan inconvenientes ya que no se actualiza correctamente el orden de la tabla después de realizar el movimiento.

https://github.com/user-attachments/assets/b7d59ba4-98e8-48ee-9448-ac79898ea389

**Comment by edwargl7** [comment]
Pendiente consulta de vinculación de microcliente de formularios dinámicos y la identificación del método a usar (POST y PUT).

**Comment by CristianCGutierrezG** [comment]
El inconveniente con la funcionalidad de **drag and drop** estaba relacionado con los estilos del **Material Table**, que no permitían que los elementos fueran completamente arrastrables.

![image](https://github.com/user-attachments/assets/93d792c1-94db-4a25-8a8f-db6f554d2670)


https://github.com/user-attachments/assets/51c5c642-851b-480b-82f3-c0b542bfc53a

**Comment by CristianCGutierrezG** [comment]
### Estrategias para Compartir Datos entre Microfrontends

Se realiza una investigación para saber que formas existen para convartir datos entre los dos microfronenents

1. **Props**:
   - **Descripción**: Pasar datos al montar microfrontends.
   - **Ventajas**: Simple de implementar.
   - **Limitaciones**: Limitado a microfrontends montados en secuencia.

2. **Estado Compartido (BehaviorSubject)**:
   - **Descripción**: Usar un servicio reactivo para compartir datos entre microfrontends.
   - **Ventajas**: Ideal para aplicaciones que necesitan suscripción a cambios globales y reactividad.
   - **Limitaciones**: Puede volverse complejo con muchos cambios globales.

3. **Paquete npm o Monorepo**:
   - **Descripción**: Crear una biblioteca compartida que contiene el estado o lógica común.
   - **Ventajas**: Modular, escalable y fácil de mantener.
   - **Limitaciones**: Requiere configuración adicional y despliegue de bibliotecas compartidas.

4. **Cookies de Sesión**:
   - **Descripción**: Almacenar datos en cookies accesibles entre microfrontends.
   - **Ventajas**: Fácil de implementar y permite compartir información entre dominios.
   - **Limitaciones**: Limitado en tamaño y presenta desafíos de seguridad.

5. **localStorage/sessionStorage**:
   - **Descripción**: Almacenar datos en el navegador, accesible entre microfrontends.
   - **Ventajas**: Persistente, incluso entre recargas o sesiones del navegador.
   - **Limitaciones**: No es reactivo, por lo que no detecta cambios automáticamente.

Se reliza un implementación de prueba con el paso de datos desde el localStorage

https://github.com/user-attachments/assets/89775e87-b756-4646-bd0d-be5aafeb4404

**Comment by CristianCGutierrezG** [comment]
Se consulta con Bryan Muñoz del equipo de SGA, sobre la mejor forma de realizar el paso de datos entre los microfrontends. Tras la revisión, se decide volver a implementar el paso de datos a través de los **parámetros en la URL**, logrando finalmente **resultados positivos**.

cambios de prueba en la url de view-formulario para que reconozca los parametros

![image](https://github.com/user-attachments/assets/4fe3fda7-c1f3-4bf2-b0f2-6e56e3134bdb)


Se ajustan las paginas de consulta auditoria y editar actividades para que funcionen con la redirección y paso de datos, incluyendo el formulario a renderizar.

![image](https://github.com/user-attachments/assets/6dd4c5b6-c5f2-4ef1-8647-8f5c293ec8e5)


https://github.com/user-attachments/assets/71ae4002-bcb2-4ef2-a8e2-e815a343d8eb


Aún no es posible utilizar la opción de `navigate` en Angular, ya que al hacerlo, no se reconoce la conexión de las rutas entre los microfrontends.

**Comment by edwargl7** [comment]
Se observa un muy buen avance. Se complementará la revisión junto con el desarrollador en la planning.

**Comment by edwargl7** [comment]
Finalizada la Issue.
