### ISSUE TITLE
Actualizar versión microclientes root, plan y usuarios - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#188]
Se requiere continuar con la actualización de versión de los microclientes [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf), [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) y [auditoria_plan_mejoramiento_root_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_root_mf) iniciada en la Issue #186 

**Sub Tareas**

- [x] Actualizar versión de los mf solicitados.
- [x] Pruebas funcionales de los mf una vez realizados la actualizaciones.
- [x] Actualización README.

**Criterios de aceptación**

- [x] Documentación ajustes y pruebas funcionales que garanticen el correcto funcionamiento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan pruebas funcionales en [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)

![Image](https://github.com/user-attachments/assets/7931bd22-d8aa-44a5-9e07-fe607eed1b11)
![Image](https://github.com/user-attachments/assets/08859561-feb5-4e68-9e7a-26a05929ea01)
![Image](https://github.com/user-attachments/assets/bc3c3d5b-faf7-4901-9052-4263e8e74d93)

**Comment by jucastro94** [comment]
se realiza actualizacion del root con base en ejemplo de [gestion_contractual_root_mf](https://github.com/udistrital/gestion_contractual_root_mf)
![Image](https://github.com/user-attachments/assets/18ac4f04-10f7-4e65-9974-ebe7b63a3674)

se realiza prueba funcional 
![Image](https://github.com/user-attachments/assets/200f2964-3a8a-486a-b1e0-ef429b69a4bf)

**Comment by edwargl7** [comment]
Buen trabajo. Resueltos los PR de los mf.
