### ISSUE TITLE
Implementación cargue masivo - prueba de concepto

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#189]
Se requiere realizar la implementación del microservicio usando serverless basado en las investigaciones de la Issue #181 y #144.

**Sub Tareas**

- [x] Implementación función cargue de archivo desde un base64.
- [x] Implementación estructura JSON desde cada registro para envío a petición (evaluar lectura de configuración externa para comportamiento dinámico).
- [x] Implementación función de consumo de microservicio CRUD (manejo de excepciones).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
- Repositorio [cargue_archivo_mid_serverless](https://github.com/udistrital/cargue_archivo_mid_serverless)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avances cargue masivo

Se realizan ajustes en el codigo para separarlo en diferentes funciones.

![image](https://github.com/user-attachments/assets/87f1fd1e-c190-403c-ab1b-0a829d732905)

![image](https://github.com/user-attachments/assets/5ea30349-ace4-4a0e-a04f-8f2162b8f06a)

![image](https://github.com/user-attachments/assets/f6e6ba20-e275-4f3a-a173-f8d6668f9abd)

Se continúa con la implementación del envio del Json al endpoint con la información del body para la petición post.

**Comment by alexhrr** [comment]
### Avance cargue masivo

Se realiza el envio del Json generado a partir de los datos decodificados al correspondiente endpoint para el registro de roles:


Estructura decodificada con los roles de prueba a crear:

![image](https://github.com/user-attachments/assets/3c10c1c2-1921-4c33-8978-2ac22af34bf0)

Roles existentes:

![image](https://github.com/user-attachments/assets/a9f97e20-1d07-48d1-b3da-94711956edf0)

Roles registrados mediante serverless:

![image](https://github.com/user-attachments/assets/21f13c17-03c3-49af-ad00-8076c62318c8)

Se hace uso de ngrok para acceder al endpoint local y se muestran los resultados de estado:

![image](https://github.com/user-attachments/assets/2d916ab3-c5bf-47c2-9016-afa230cfd5f0)

![image](https://github.com/user-attachments/assets/6e69bb7a-145e-45a6-9cfd-513faed0264f)

**Comment by edwargl7** [comment]
Estructura inicial de manejo de errores,
```json
{
    'numero_registro': 1,
    'error': "Detalle del error"
}
```

**Comment by alexhrr** [comment]
### Avance cargue masivo

Se realiza la implementación para que se continúe con los registros a pesar de que se genere un error en alguno de los registros, para este caso se intenta crear un rol con el sistema de información numero 3 que no existe en la base de datos: 

![image](https://github.com/user-attachments/assets/8d33da4c-74ca-4fd4-a246-0abc8220fa9f)

El registro que tiene el sistema de información que no existe no se registra y muestra un error, el registro que sigue se registra correctamente:

![image](https://github.com/user-attachments/assets/a6ac782e-29c8-433f-b0b6-33125fdd0dd9)

![image](https://github.com/user-attachments/assets/ce2119b9-cdeb-414e-bd61-2527e321c0ee)

Se agrega la funcionalidad de identificar los registros, realiza una prueba añadiendo una columna para identificar cada registro con el objetivo de conocer el rol que no pudo ser registrado:

![image](https://github.com/user-attachments/assets/2001d85c-42ff-4c1d-87c0-9d4af7eebe34)

Se muestran los ids de los roles creados y de los que generaron error:

![image](https://github.com/user-attachments/assets/38567755-70e2-4d14-b732-88c752b4b357)

Finalmente se realiza una prueba adicional enviando 60 registros para ver que sucede con los tiempos y si se genera algún problema, el tiempo se encuentra limitado a 15 segundos en el template asi que al llegar a este tiempo se detiene el servicio en el registro 39.

![image](https://github.com/user-attachments/assets/11f885a1-ddc0-483e-9d89-0bbace0a29c2)

**Comment by edwargl7** [comment]
Muy buen avance y registro se va a trabajar en identificar también la memoria usada y otras pruebas de rendimiento.

**Comment by alexhrr** [comment]
## Cargue masivo serverless

Se realizan diferentes pruebas disminuyendo la cantidad de memoria en el template para los 60 registros:

### 60 mb

![image](https://github.com/user-attachments/assets/50fbbe88-14c8-4ebc-93bb-e19fc10e6b00)

### 30 mb

![image](https://github.com/user-attachments/assets/379756a6-2cbf-427c-852c-ec07d7eaea1d)

### 15 mb

![image](https://github.com/user-attachments/assets/0c427ffd-1691-4253-8a34-8670c5d41cbd)

Finalmente se dejan 15 mb para esta prueba ya que seguía funcionando correctamente si presentar problemas por la cantidad de memoria

### Prueba para la creación de periodos

Para verificar el comportamiento con una cantidad diferente de columnas en el archivo se modifica el codigo y se implementa el cargue masivo para la creación de periodos en histórico usuarios.
Ahora se tiene una cantidad mayor de columnas (5 para enviar al endpoint) para asemejar el comportamiento real, se tienen datos de fecha, booleano y enteros:

![image](https://github.com/user-attachments/assets/f8901d9a-ae5f-41ed-bb97-cc8d1cd91a42)

Se realiza la ejecución y se obtienen los siguientes resultados:

![image](https://github.com/user-attachments/assets/6b0b34c1-da39-4e29-aee3-5711fc4f3c99)

Posteriormente se realiza la prueba con una mayor cantidad de registros (20) para verificar el tiempo de ejecución:

![image](https://github.com/user-attachments/assets/2407b8da-08a7-4fce-bae9-2520d752ad02)

Resultados obtenidos con los 20 registros:

![image](https://github.com/user-attachments/assets/e2e43c5d-2d5d-4e20-ac66-af0924209f50)

Memoria: Con los 15 mb es suficiente para realizar la ejecución del cargue masivo tanto de los 60 roles (2 columnas) como de los 20 periodos (5 columnas)

Tiempo: el tiempo varia entre las diferentes pruebas asi no se modifique la cantidad de registros, la variación no es mayor a 2 segundos entre las pruebas realizadas.
En el caso de los 20 periodos se tuvo siempre valores inferiores a los 8 segundos

**Comment by edwargl7** [comment]
Muy buena implementación. La estructura del proyecto se puede ajustar usando el src, que permita de esta forma tener el proyecto agrupado. Ejemplo: https://github.com/udistrital/prueba_piloto_funciones_lambda/tree/feature/issues-161-multiples-planes-proyectos
