### ISSUE TITLE
Revisión y ajustes del modelo de microservicios para Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#19]
Se requiere realizar la revisión y ajustes del diagrama de componentes que representa la división en microservicios del sistema Sísifo actual con el equipo de Arquitectura para garantizar el correcto diseño, tener mayor claridad de los servicios identificados en esta primer etapa y evidenciar otros servicios que puedan ser reutilizados. 

**Sub Tareas**

- [x] Reunión con el arquitecto para la revisión
- [x] Realizar los ajustes requeridos en el diagrama realizado en la Issue [División del sistema en Microservicios](https://github.com/udistrital/sisifo_documentacion/issues/16)

**Criterios de aceptación**

- [x] Participación en la reunión de revisión
- [x] Realizar los ajustes sugeridos
- [x] Actualización del diagrama en la carpeta de documentación

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama actualizado y cargado en la documentación.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Buenas tardes,

De la revisión con el arquitecto se tienen los siguientes ajustes sugeridos:

1. El módulo de configuración se sugiere evaluar el uso de [parametros_crud](https://github.com/udistrital/parametros_crud)
2. Documentos CRUD/MID no es necesario dado que el servicio de gestor documental nos permite almacenar esa información asociada a cada avance [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid)
3. El manejo de roles se puede usar con WS2.

**Nota:** Se recomienda crear una nueva página para conservar esta primera versión.

**Comment by CristianCGutierrezG** [comment]
Diagrama de microservicios :

**Comment by CristianCGutierrezG** [comment]
Se realizan los ajustes correspondientes al listado de microservicios y principales funcionalidades:

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/f0cf5141-779e-402e-aa55-33cbd5e21c0a)



se adjunta enlace del listado con las respectivas correcciones:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EWIPafJgHe5GjoGXnjowTyABLSa7WbKRWn8fhrBFi6TsoA?e=reJbU2

**Comment by edwargl7** [comment]
Excelente trabajo, contempla las observaciones y sugerencias del arquitecto. Se realizaran ajustes progresivamente en el diagrama a medida que se obtienen y refinan los requerimientos, y se van conociendo mejor los servicios a los que se integraran.
