### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión de refinamiento con el cliente Mockups pendientes

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#190]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de refinamiento con el cliente respecto a Mockups pendientes de aprobación

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [X] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [X] No tiene bloqueos que impidan su ejecución.
- [X] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta con el cliente para concertar reunión, pendiente confirmación por parte del cliente día y hora.


Saludos.

**Comment by jcmurilloa** [comment]
Esperemos tener respuesta positiva para este mismo sprint y contar con aprobación de mockups pendientes por parte del cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se acuerda y programa reunión con cliente para el día viernes, 04 de octubre de 2024 hora: 10:00 am de forma presencial en la sede Paiba.



Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

La reunión tuvo que ser aplazada por fallos en el sistema de internet en la sede Paiba, se espera confirmación por parte del cliente la fecha para llevar a cabo la reunión.


Saludos.

**Comment by jcmurilloa** [comment]
Hasta ahora hay nueva fecha de reunión?

**Comment by cjgonzalezp** [comment]
Buen día,

Si, hoy me dieron respuesta y se agenda reunión para mañana 11 de octubre de 2024 hora: 11:00 am presencial en la sede Paiba.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se lleva a cabo reunión con cliente el día 11 de octubre de 2024 en horario: 11:00 am a 12:00 m. Pendiente terminar de levantar acta de reunión y recolección de firmas de los participantes.


Saludos.

**Comment by jcmurilloa** [comment]
@cjgonzalezp Recuerda lo que hablamos de no dejar pasar varios días sin la proyección del acta posterior a la fecha de reunión. Te encargo que la puedas tener lo más pronto posible por favor.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión No 145/2024 SISIFO - Levantamiento de requerimientos. Reunión desarrollada el dia 11 de octubre de 2024. Pendiente recolección de firmas de los participantes presentes en la sesión.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Sb7pcM

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, a recolectar las firmas por favor.

**Comment by cjgonzalezp** [comment]
Buen día,

Se da por finalizada la issue #190 con la firma del acta No 145/2024 de todos los participantes presentas en la reunión desarrollada el día el día 11 de octubre de 2024. El acta queda guardada en la carpeta SISIFO V2 en OneDrive.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Lqccbu


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp!
