### ISSUE TITLE
Diseñar el mockup para el submódulo auditorías externas

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#191]
Se requiere continuar con el diseño del mockup para el submódulo auditoría externa

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.
- [x] Mockup aprobado por cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño del submódulo de auditorías externas.

![Image](https://github.com/user-attachments/assets/a097abc4-2a52-4c55-89ed-5a7346548d2a)


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla diseño de mockup del submódulo auditorías externas. Pendiente proyectar diseño para auditorías de la contraloría de Bogotá.

![Image](https://github.com/user-attachments/assets/5f0f2f9a-20bc-4874-9090-5da06bcd281c)


**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Auditor%C3%ADas%20Externas/Subm%C3%B3dulo%20Auditor%C3%ADas%20Externas?csf=1&web=1&e=7G4ENh


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, tenía entendido que este submodulo de auditorías externas se podría utilizar para las relacionadas con la Contraloría de Bogotá u otro ente de control externo.

**Comment by jcmurilloa** [comment]
Pendiente las recomendaciones generadas por el equipo SoS, pendiente aprobar por el cliente posterior a la modificación.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes al mockup según sugerencias dadas por el equipo SoS.

![Image](https://github.com/user-attachments/assets/eb30f49a-e2cf-4677-bec0-77a400520587)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Auditor%C3%ADas%20Externas/Subm%C3%B3dulo%20Auditor%C3%ADas%20Externas?csf=1&web=1&e=JedUdQ


Saludos.

**Comment by jcmurilloa** [comment]
Queda solo pendiente aprobar por parte del cliente, muy buen trabajo @cjgonzalezp !

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta diseño de mockup para la implementación del submódulo auditorías externas que servirá para registro de hallazgos y documentación relacionada a la auditoría externa. Se recibe aprobación bajo el acta No 145/2024 para el desarrollo del módulo en el sistema SISIFO V2.

**Enlace acta de reunión No 145/2024 SISIFO - Levantamiento de requerimientos**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20145%20-%202024%20SISIFO%20-%20Levantamiento%20de%20Requerimientos?csf=1&web=1&e=Lqccbu

Saludos.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp!
