### ISSUE TITLE
Actualización mockups de notificación por correo

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#193]
Se requiere realizar la actualización del diseño de los correos de Sísifo.

**Sub Tareas**

- [x] Actualizar los diseños de los correos.

**Criterios de aceptación**

- [x] Mockup actualizado con el diseño nuevo de correos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza modificación de los diseños en los todos los mockups del módulo de gestión de auditoría, de la vista de cada una de las notificaciones que recibirán los usuarios involucrados en los procesos dentro del sistema SISIFO V2.

![Image](https://github.com/user-attachments/assets/9bc0d5fb-25a6-4b4f-b725-4b63142a0ae6)


**Enlace archivos actualizados y guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa?csf=1&web=1&e=bhCZlD


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp!
