### ISSUE TITLE
Pruebas funcionales del microservicio histórico usuarios roles crud en ambiente de pruebas - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#194]
Se requiere realizar la verificación del correcto funcionamiento del microservicio histórico usuarios roles una vez desplegado en ambiente de pruebas.

**Sub Tareas**

- [x] Pruebas de cada endpoint CRUD del microservicio funcionalidad completa (filtros, paginado, ...).

**Criterios de aceptación**

- [x] Documentación de las pruebas funcionales realizadas a cada CRUD.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se solucionan los problemas de permisos en la base de datos, se inician pruebas de funcionalidad

**Comment by jucastro94** [comment]
se realizan pruebas a CRUD usuarios

GETALL
![Image](https://github.com/user-attachments/assets/5ffb5c31-0976-4458-aa41-ca894dc07f8f)

POST
![Image](https://github.com/user-attachments/assets/a43b20ee-beaf-455b-a77e-15cd1760e318)

GETONE
![Image](https://github.com/user-attachments/assets/2b29ae57-6814-4d9e-8b8e-17f5a92f2feb)

PUT
![Image](https://github.com/user-attachments/assets/a780081b-ea94-46d5-a2f9-3af4b07d7dbb)

DELETE
![Image](https://github.com/user-attachments/assets/d07f2fa0-3dcd-4b15-b185-a1370d12d946)
![Image](https://github.com/user-attachments/assets/deb34c55-61ee-4484-844a-1cd59395ca0e)

QUERY PARAMS
![Image](https://github.com/user-attachments/assets/c1834fb6-9f9e-40e2-a93f-b7b34b747b4e)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales a CRUD roles

GET
![Image](https://github.com/user-attachments/assets/ba62033e-d1e7-4fe7-838b-67fcf886b980)

POST
![Image](https://github.com/user-attachments/assets/d83685c9-1363-49b1-814e-f7564820f2d4)

GETALL
![Image](https://github.com/user-attachments/assets/ab60f467-9674-43f8-8ece-2d4ff8bb6403)

PUT
![Image](https://github.com/user-attachments/assets/abc6d7e7-1ec4-4cb5-a167-e34186f68bd4)

DELETE
![Image](https://github.com/user-attachments/assets/73c40634-8921-439b-b029-7b60084392ce)

QUERY PARAMS
![Image](https://github.com/user-attachments/assets/3698e05e-56aa-45aa-a892-71f2d74f840f)

**Comment by jucastro94** [comment]
se realiza pruebas funcionales en CRUD periodos rol usuarios

GET
![Image](https://github.com/user-attachments/assets/4561abf0-f429-4935-a9a2-9f33f80b94cb)

POST
![Image](https://github.com/user-attachments/assets/b87334c1-f3f6-4346-9a97-2939f2264f68)

GETALL
![Image](https://github.com/user-attachments/assets/c1506fae-7884-4693-b1d3-ba51232a2f8d)

PUT
![Image](https://github.com/user-attachments/assets/f6fb00ef-691a-4965-a1ac-ab979bf98e20)

DELETE
![Image](https://github.com/user-attachments/assets/755c53ef-6664-4c68-8c74-d2173fb0f3f4)

QUERY PARAMS
![Image](https://github.com/user-attachments/assets/11564aa5-eeba-4025-8570-afe80d2e6a60)

**Comment by jucastro94** [comment]
se realiza pruebas funcionales en CRUD 
GET
![Image](https://github.com/user-attachments/assets/5839e48d-1edd-4cba-b49d-eb22c5b8bf86)

QUERY PARAMS
![Image](https://github.com/user-attachments/assets/b5a34905-a41f-42de-b7e4-bc9729332017)

**Comment by edwargl7** [comment]
Buenas pruebas, se finaliza la Issue.
