### ISSUE TITLE
Implementación registro de programa en el microcliente de plan anual de auditoria - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#195]
Se requiere continuar con la implementación iniciada en la Issue #187. Dado que la ruta evaluada para estos registros cumplen con lo requerido se procede a seguir la implementación.
![image](https://github.com/user-attachments/assets/21f273a4-5d63-429f-ab2b-c28715e295c4)
![image](https://github.com/user-attachments/assets/afc2670d-4b41-4778-8685-fb2c68b5fdf8)
![image](https://github.com/user-attachments/assets/3355185b-2309-4c4f-b0c0-cb30ca0782a7)

**Sub Tareas**

- [x] Implementación integración microcliente con componente de edición.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
- Repositorio [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)
- Repositorio [formularios_dinamicos_mf](https://github.com/udistrital/formularios_dinamicos_mf)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realiza el pull en el microcliente de `formularios_dinamicos` para obtener los últimos cambios del repositorio.

#### Hallazgos:
- Se evidencia una implementación con el uso del **microservicio CRUD de formularios dinámicos**, pero aún no se confirma si esta implementación está completamente funcional.
- El componente de vista se utiliza en varios otros componentes para renderizar un formulario.
- Se encuentra que el componente que renderiza los formularios (`dynamic-form`) ya contaba con una forma de visualizar el valor si este venía incluido en el JSON.

![image](https://github.com/user-attachments/assets/90c28130-7e11-4da6-b1db-06c3655bb846)


Se crean diferentes **mocks** para realizar pruebas y verificar el funcionamiento del componente y la integración con el microservicio CRUD.


https://github.com/user-attachments/assets/2012e68b-5c3d-4fab-bc25-1bbd9ab48579

**Comment by CristianCGutierrezG** [comment]
### Creación de Componente de Edición

Se crea un nuevo componente con una nueva ruta para llevar a cabo el proceso de edición;
Tambien se realiza una actualización en el componente que crea los formularios para incluir la funcionalidad de cambiar de operacion dependiendo si se requiere un POST o un PUT

![image](https://github.com/user-attachments/assets/ddaade96-86f5-48f5-b556-9e4a485e4ecc)


#### Páginas Actuales:
- **URL de la página de edición**: 
http://localhost:4200/formularios-dinamicos/editInfo-formulario/id/nombreForm
![image](https://github.com/user-attachments/assets/819de01b-0e15-41d6-a8f4-f28cdf01e881)

- **URL de la página de vista**: 
 http://localhost:4200/formularios-dinamicos/view-formulario/nombreForm
![image](https://github.com/user-attachments/assets/6c7bbad5-d8f2-4cc8-9170-10676be73827)


https://github.com/user-attachments/assets/a867326f-fefe-439a-a13c-9becd65bec6c


Se puede plantear la opción de utilizar **solo una URL** y definir en la lógica si se recibe un ID o no, determinando así el tipo de función que se requiere (edición o visualización).

**Comment by edwargl7** [comment]
Se puede evaluar invertir el orden de los parámetros para siempre obtener primero el id/nombre de la plantilla del formularios y el resto de parámetros los valores de consulta de datos o demás parámetros requeridos

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR. Revisar parámetro de consulta de formulario por nombre, se sugiere mejor usar id del formulario en lugar del nombre.
![image](https://github.com/user-attachments/assets/7f672240-3b44-4f30-885a-3ebebaec5d35)
