### ISSUE TITLE
Implementación registro de programa en el microcliente de plan anual de auditoria - Parte 3

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#196]
Se requiere realizar la implementación de la funcionalidad de los botones del registro de actividades del programa y los modales de validación de las acciones, basadas en el mockup.

![image](https://github.com/user-attachments/assets/298ae179-d698-40c9-b13b-9f832f79636b)
![image](https://github.com/user-attachments/assets/ed497a15-6e3c-49fe-9fdf-84e9b9aa3992)
![image](https://github.com/user-attachments/assets/f124e053-9fa0-4046-929b-b5c0b972795b)
![image](https://github.com/user-attachments/assets/14ef8f67-74b8-428c-931d-5771fa16bc40)
![image](https://github.com/user-attachments/assets/e0b5b213-58b2-425f-b22f-f5306ead1130)
![image](https://github.com/user-attachments/assets/66bf75ca-6fd6-4dfc-bad4-62dcf9752adb)
![image](https://github.com/user-attachments/assets/9b089f36-3756-4344-8c5b-9d46cb8e7439)

**Sub Tareas**

- [x] Ajuste alineación botones registro de actividades.
- [x] Implementación modales de confirmación y resultado de operaciones realizadas por el usuario.
- [x] Implementación modal de carga de archivos (sin integrar).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
- Repositorio [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance Implementación modales

Se realiza la actualización del repositorio local y se generan errores com la importación de PdfViewerModule en el modulo de revision-plan-auditoria, lo dejo comentado para poder ejecutar el código.

Se comienza con la implementación de los modales de confirmación según los mokups, se toma como base lo trabajado en el microcliente de gestión de usuarios para el manejo de los modales.

Se crea el modal.service para centralizar los modales, debido a que se van a implementar varios de ellos

![Captura de pantalla 2024-10-01 a la(s) 8 42 41 a m](https://github.com/user-attachments/assets/79e8e705-f6ad-49f3-a716-037091847c7b)

Se crean las funciones para los modales de confirmación y de aviso.

![Captura de pantalla 2024-10-01 a la(s) 8 42 55 a m](https://github.com/user-attachments/assets/5f63d800-8a27-4566-bced-9d15af1c693d)

![Captura de pantalla 2024-10-01 a la(s) 8 43 05 a m](https://github.com/user-attachments/assets/f548402f-c117-443b-9874-55b2e034b552)

Se inicia la integración de los modales en el código

**Comment by alexhrr** [comment]
## Avance implementación modales

Se crean los modales correspondientes según los mokups:

### Eliminar auditoria:

![Captura de pantalla 2024-10-01 a la(s) 10 20 43 p m](https://github.com/user-attachments/assets/981e8e6a-244a-40d6-ad1c-d1454a920cc9)

![Captura de pantalla 2024-10-01 a la(s) 10 20 50 p m](https://github.com/user-attachments/assets/ca41ea3d-b1b5-4df4-a1d8-642747d8ee5d)

### Guardar PAA:

![Captura de pantalla 2024-10-01 a la(s) 10 21 12 p m](https://github.com/user-attachments/assets/3e125c8e-b855-4dfb-99fa-48c07502352f)

![Captura de pantalla 2024-10-01 a la(s) 10 21 18 p m](https://github.com/user-attachments/assets/3c32c1e5-4ec7-40e6-808b-868d39bd6212)

### Enviar PAA:

![Captura de pantalla 2024-10-01 a la(s) 10 21 52 p m](https://github.com/user-attachments/assets/d8d14e2f-4229-434e-9719-4df9f1902ade)

![Captura de pantalla 2024-10-01 a la(s) 10 21 58 p m](https://github.com/user-attachments/assets/64c4df3d-26a7-4a22-93f7-8e09aedafb67)


Tambien se realiza la creación de un nuevo componente para el manejo del modal que carga los archivos:

![Captura de pantalla 2024-10-01 a la(s) 10 31 53 p m](https://github.com/user-attachments/assets/e1c0defd-e35b-419c-a60c-54e11c9eeaf8)

![Captura de pantalla 2024-10-02 a la(s) 8 58 21 a m](https://github.com/user-attachments/assets/acb50250-426b-4c66-8e4f-8343bbddc89d)

Se continúa con el ajuste de los estilos

**Comment by edwargl7** [comment]
Muy buen avance, del modal de carga de archivos por favor cambiarlo a español.
- Botón "Examinar ..." 
- Placeholder "Seleccionar archivo ..."

**Comment by alexhrr** [comment]
Se finaliza el modal para cargar archivos con los ajustes solicitados:

![Captura de pantalla 2024-10-02 a la(s) 11 21 37 a m](https://github.com/user-attachments/assets/ee7e8315-d0fd-4e9b-833a-3039cb81733b)

**Comment by edwargl7** [comment]
Muy buen trabajo. Resuelto PR.
