### ISSUE TITLE
Implementación ajustes en parametrización microcliente de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#197]
Se requiere realizar la evaluación e implementación de ajustes en los campos paramétricos en el microcliente de formularios dinámicos identificados en la Issue #192.

**Sub Tareas**

- [x] Evaluación imparto de agrupación de parámetros (url, vista, fecha_inicial, opciones, ...), evaluando el impacto en la vista de registro de plantilla de formulario.
- [x] Validar el cambio requerido en la repuesta "secciones" y "campos" que en el microservicio se retorna en singular.
- [x] Implementación ajustes en componentes.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Pruebas de Conexión y Evaluación del CRUD de Formularios Dinámicos

Se realizaron pruebas de conexión exitosas para la página `list-formulario`, pero se identificaron problemas en el mapeo de plantillas que impiden el renderizado correcto del formulario.

![image](https://github.com/user-attachments/assets/8f81e99f-b35a-44ea-a7ed-96500b21048d)

### Evaluación del Impacto del Cambio de Mapeo

#### Componentes Afectados:
1. **Componente `dynamic-form`**:
   - Actualmente, las opciones y la URL se manejan fuera de los parámetros, directamente en los campos.
   - Este componente es utilizado por las páginas de **buscar**, **visualizar** , **editarInfo** y **crear** para renderizar los formularios.

2. **Componente `field-builder`**:
   - En la creación de formularios y plantillas, tanto las opciones como la  URL se almacenan en los mismos campos.
   - La página `crud-formulario` utiliza este componente para crear nuevos formularios que luego muestra con `dynamic-form`.
   - No se cuenta actualmente con un campo específico para los parámetros.
![image](https://github.com/user-attachments/assets/f4ef6484-6156-4488-b31b-4d93bfc394a1)


#### Consideraciones:

- **Parámetros Específicos**:
  Los valores que van en `parámetros` son diversos y, en algunos casos, específicos para un campo o elemento. Es necesario analizar cada caso individualmente.

- **Cambios en los campos**:
   1. Se pueden agregar campos como `"vista"` y `"fecha_inicio"` en `parámetros`, modificando cómo acceden los elementos que los necesiten.
![image](https://github.com/user-attachments/assets/72052e7a-0ac4-4e99-bd51-11d14b01abfb)
![image](https://github.com/user-attachments/assets/e2333155-5732-4750-bab5-76c20cfee60d)

   
   3. **Campo "valor"**:
      - Es importante definir si este campo debe integrarse en `parámetros`.
      - ¿Debería agregarse en `parámetros` o traerse mediante un `mid` desde los datos almacenados en la BD?
   
   4. **Campo "etiqueta" o "label"**:
      - Revisar cómo se implementa este campo en el microcliente.
      - Es posible especificar si el campo debe tratarse como un **objeto** o un **string**.
      ![image](https://github.com/user-attachments/assets/a5edb9c5-3148-46dc-96c5-07ea507e4c19)

   
   5. **Nombres de Campos**:
      - Los cambios de nombre de campos pueden ser implementados más fácilmente en el microservicio CRUD.

   6. **Campo "icono"**:
      - Este campo debe agregarse al microservicio CRUD

**Comment by CristianCGutierrezG** [comment]
### Cambios Realizados en `dynamic-form`

1. **Creación del Formulario**:
   - Se ha implementado una verificación por parámetros durante la creación del formulario en el componente `dynamic-form`.

![image](https://github.com/user-attachments/assets/807db70b-24ed-4758-8757-b090579077c4)

![image](https://github.com/user-attachments/assets/031d0fbb-05cc-464f-b83b-3e7de06209d7)

2. **Actualizaciones en Campos**:
   - Se han realizado cambios en los campos que requieren un dato específico en `parámetros` 

![image](https://github.com/user-attachments/assets/3caca782-5c7e-4724-a20d-454ca2f19516)
![image](https://github.com/user-attachments/assets/91ecc305-733b-44a5-a43f-8a1ec72f92d7)


Las paginas de view-formulario y editInfo-formulario funcionan ahora con la nueva maquetación

---

### Cambios Realizados en `field-builder`

1. **Estructuración de Datos**:
   - Se han ajustado los cambios en cómo se almacenan la URL y las opciones dentro del componente `field-builder`.
   - Se ha presentado un error al momento de renderizar las opciones
 
![image](https://github.com/user-attachments/assets/cb489a70-13fe-4a79-9fdf-b5c1e29d215b)

El erro suele deberse a que el código intenta acceder a controles del formulario que aún no están inicializados, o puede que estén incorrectamente configurados

**Comment by CristianCGutierrezG** [comment]
### Solución al Error en la Construcción de Opciones y URL

1. **Identificación del Error**:
   - Se detectó que el error al construir las opciones y la URL surgía porque no se reconocía el `formGroup` desde donde se llamaban esos controles.
![image](https://github.com/user-attachments/assets/8515fd20-886a-4408-86b2-3a4da7bbb6f6)


2. **Solución Implementada**:
   - Se asignó un nuevo formulario, referenciando correctamente al `formGroup` creado para guardar los parámetros.
 
![image](https://github.com/user-attachments/assets/661026b7-d392-48b0-a038-0c19f9032c91)

![image](https://github.com/user-attachments/assets/f21a136d-d5be-4169-8859-f65c6135aa49)
![image](https://github.com/user-attachments/assets/618d91d4-811a-4cc4-9919-e55d7f145cc7)


3. **Pruebas Realizadas**:
   - Se llevaron a cabo pruebas y se verificó el correcto funcionamiento de la página `crud-formulario`. El componente ahora funciona correctamente al construir y renderizar las opciones, así como al manejar la URL de manera adecuada.

![image](https://github.com/user-attachments/assets/414cde83-6ed7-4e1d-a8be-2ed396b8e7b1)
![image](https://github.com/user-attachments/assets/30732434-0aa2-414e-a630-ba38f6660058)
![image](https://github.com/user-attachments/assets/fde94b4f-5d94-4048-ab42-1250dc97381a)

**Comment by CristianCGutierrezG** [comment]
### Cambios en Nombres de Maquetación en Formularios Dinámicos CRUD

1. **Renombramientos**:
   - `Seccion` se renombró a `Secciones`.
   - `Campo` se renombró a `Campos`.
   - `Label` se renombró a `Etiqueta`.

2. **Nuevos Campos**:
   - Se añadió el campo `icono` en las `secciones`.

![image](https://github.com/user-attachments/assets/5c3cb48e-ed4f-4b0d-81a6-8f63a05a84c4)

**Comment by edwargl7** [comment]
De la segunda consideración se puede plantear en el MID dado que la plantilla no tendría valor por defecto desde la plantilla (si es requerido valor por defecto desde la plantilla se puede plantear agregarlo al modelo de datos).
![image](https://github.com/user-attachments/assets/b3ae93a7-6640-4da1-9189-eb60078386a9)

Campo label sujeto a cambios en caso de requerir traducción.
![image](https://github.com/user-attachments/assets/bb712f99-bc10-481e-bcd4-ba5f12c19005)

Aprobados los cambios evaluados y realizados en el CRUD.
![image](https://github.com/user-attachments/assets/5cf98dca-2155-42d2-b1f4-c6557a457e65)

**Comment by edwargl7** [comment]
Resueltos los PR del CRUD y MF.

**Comment by edwargl7** [comment]
El campo de valor validando con @cjgonzalezp es necesario dado que se requiere valor predefinido desde la creación del formulario en el paso 1 del plan anual de auditoría.
