### ISSUE TITLE
Revisión y ajustes del modelo de microservicios para Sísifo v2 - Modelo de datos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#20]
Se requiere realizar la revisión y ajustes del diagrama del modelo de datos que fue estructurado y dividido en microservicios, este ajuste va más enfocado en el modelo de datos de cada microservicio basado en la revisión y sugerencias dadas por el equipo de arquitectura.

**Sub Tareas**

- [x] Reunión con el arquitecto para la revisión
- [x] Realizar los ajustes requeridos en el diagrama realizado en la Issue [Diseño modelo de base de datos - Parte 1](https://github.com/udistrital/sisifo_documentacion/issues/17)

**Criterios de aceptación**

- [x] Participación en la reunión de revisión
- [x] Realizar los ajustes sugeridos
- [x] Actualización del diagrama en la carpeta de documentación

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama actualizado y cargado en la documentación.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Buenas tardes,

De la revisión con el arquitecto se tienen los siguientes ajustes sugeridos:

1. El módulo de configuración se sugiere evaluar el uso de [parametros_crud](https://github.com/udistrital/parametros_crud), por lo tanto, podría no ser necesario todas las tablas de parámetros.
2. Documentos, no es necesario tener una tabla que nos permita almacenar el id del avance con el id del documento dado que el servicio de gestor documental nos permite almacenar esa información asociada a cada avance [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid)
3. El manejo de roles se puede usar con WS2.
4. Se recomienda si dejar en otro microservicio el módulo de avances.
5. Los usuarios se pueden tomar de [terceros_crud](https://github.com/udistrital/terceros_crud)

**Nota:** Se recomienda usar una base de datos No relacional para el módulo de plan de mejoramiento.

**Comment by jucastro94** [comment]
se marcan en rojo las tablas que serian eliminadas del modelo ya que, su informacion seria tratada atraves de otros servicios, segun lo comentado por el  arquitecto

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/beedffed-a96f-43be-9bd5-a03ef66f92f7)

**Comment by jucastro94** [comment]
url version 1.1 del diagrama .draw 
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EU9cCTZ9BAZMq4_pguUeRZ4BVGZhan37Lc9wtgxKuO5KVg?e=ZUUs64
