### ISSUE TITLE
Implementación integración de carga de documentos microcliente plan anual de auditoria con microservicio gestor documental

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#200]
Se requiere realizar la integración con el microservicio gestor documental.

**Sub Tareas**

- [x] Integración microcliente con gestor documental.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación integración y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se comparte la información de integración en una reunión con @alexhrr @jucastro94

**Comment by alexhrr** [comment]
### Integración carga de documentos

Se inicia con la implementación del gestor documental

Se crea el servicio gestor documental:

![Captura de pantalla 2024-10-02 a la(s) 9 53 21 p m](https://github.com/user-attachments/assets/cf50dc29-3a15-4d22-915c-b08865ed7043)

Asi mismo se crea el requestManager para hacer las solicitudes

![Captura de pantalla 2024-10-02 a la(s) 9 58 39 p m](https://github.com/user-attachments/assets/4ae5d301-a641-4dd8-8e36-ee62ec2503dd)

**Comment by alexhrr** [comment]
Se realiza la creación del requestManager para manejar las solicitudes:

![image](https://github.com/user-attachments/assets/b34d3c39-f241-4630-a010-0635333ebd3a)

![image](https://github.com/user-attachments/assets/1f9a6d68-fb17-4b5e-acd0-b03c2faec7ba)

![image](https://github.com/user-attachments/assets/0ad9b16b-f1b9-4f03-8f6f-f3cb36850d2f)

Se comienza la implementacion del codigo para cargar el archivo pdf al modal

![image](https://github.com/user-attachments/assets/ce714e49-7535-4652-a0be-a91cff60542f)


![image](https://github.com/user-attachments/assets/c4e37a29-f53e-4c99-bf9d-f695531bfe28)

**Comment by alexhrr** [comment]
Se realiza la implementación de la carga de documentos al gestor documental

https://github.com/user-attachments/assets/4ac41e6c-064f-4514-9daa-de37e91061cc

**Comment by edwargl7** [comment]
Buena implementación, pendiente PR.
