### ISSUE TITLE
Pruebas funcionales del microservicio autenticacion_mid en ambiente de pruebas

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#201]
Se requiere realizar la verificación del correcto funcionamiento del microservicio autenticacion_mid una vez desplegado los nuevos endpoints en ambiente de pruebas.

**Sub Tareas**

- [x] Pruebas funcionales endpoints actuales del microservicio (agregar rol, remover, ...)
- [x] Pruebas funcionales endpoints nuevos relacionados a histórico de roles.

**Criterios de aceptación**

- [x] Documentación de las pruebas funcionales realizadas a cada endpoint.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan pruebas funcionales a los endpoints actualuales

tocken/userRol
![Image](https://github.com/user-attachments/assets/c674ac23-5fba-46bc-a68d-edf7b056564a)
![Image](https://github.com/user-attachments/assets/1e364d6c-95e4-4cdd-9c50-e9afbc40ba81)

tocken/documentoToken
![Image](https://github.com/user-attachments/assets/08aa0d41-9d68-4af8-a3ff-ed6573f4eef3)
![Image](https://github.com/user-attachments/assets/3675ef4b-8cab-4401-94da-69c264d7b9b8)

rol/remove
![Image](https://github.com/user-attachments/assets/57ccf29a-d867-41ca-94ab-79c8ad530276)
![Image](https://github.com/user-attachments/assets/5d50bf5e-7bb4-4b86-ade1-4f6337bc2b60)
![Image](https://github.com/user-attachments/assets/a4e03afb-d063-4e26-8e91-b130c106f051)

rol/add
![Image](https://github.com/user-attachments/assets/2878bf83-3dd4-4fc2-b01a-50aa5c815e1d)
![Image](https://github.com/user-attachments/assets/d0618ece-65ba-41a5-a28a-31964158e6b5)
![Image](https://github.com/user-attachments/assets/e3bf863c-185a-476c-9787-f5e1d9d56bea)

token/emailToken
![Image](https://github.com/user-attachments/assets/7581c423-1a26-4699-bfdd-8a7614232afb)
![Image](https://github.com/user-attachments/assets/e4cedb29-db6a-4508-87d4-a8942880f7c4)

**Comment by jucastro94** [comment]
se realiza nuevamente la prueba a endpoint roken/emailToken, con un email diferente
![Image](https://github.com/user-attachments/assets/00bde0d7-5520-4582-bb67-7454f2461a21)


se obtiene codigo de respuesta 200
![Image](https://github.com/user-attachments/assets/a60084b5-80c1-4f6d-bf24-411cfc005491)

todos los endpoints actuales funcionan

**Comment by jucastro94** [comment]
se espera a desplique de nuevas funcionalidades para realizar pruebas relacionadas con historico de roles

**Comment by jucastro94** [comment]
se realiza despligue, se inician pruebas funcionales

**Comment by jucastro94** [comment]
se realiza validacion pos-despliegue de los endpoints existentes anteriormente

![Image](https://github.com/user-attachments/assets/1f9c48c3-8cd6-477c-9239-5e1acb52b3cd)
![Image](https://github.com/user-attachments/assets/28593a54-ce4e-4e24-b712-79487956cc1d)
![Image](https://github.com/user-attachments/assets/742bdf0c-d038-4680-8ad7-5afce7b1c144)
![Image](https://github.com/user-attachments/assets/9cc55d2e-ff97-47f7-8128-748d9db1acb3)
![Image](https://github.com/user-attachments/assets/0bea2484-bdb2-48a7-9100-420102e3b71c)

**Comment by jucastro94** [comment]
se realiza prueba funcional de los nuevos endpoints

![Image](https://github.com/user-attachments/assets/0674ac28-f614-4f65-a2b0-f62bd6757ae1)



![Image](https://github.com/user-attachments/assets/ee90f971-24bf-40a0-9391-4e9f7975bd39)
se evidencia que el numero de documento enviado mediante el enpoint, no es el mismo devuelto con la informacion del usuario en el json de respuesta

**Comment by jucastro94** [comment]
se registran varios usuarios en el despliegue de usuario_rol_crud , en unos con documento aleatorio, otros con documento que coincide con alguno de terceros, al correr /rol/periods por esos documentos que no coinciden, asi sea solamente 1 de estos, lanza error 404, habiendo documentos que si estan asociados
![Image](https://github.com/user-attachments/assets/6b5ab3d1-8cc2-4c40-b19f-4ca31a12f69c)

solo hasta que se corrigen los documentos aleatorios que puse, para que coincida con alguno de terceros, se devuleve respuesta 200
 ![Image](https://github.com/user-attachments/assets/afc555bf-a736-4b2b-8b96-bec63141984f)

esto indica que con 1 solo documento que no coincida, tumba la peticion, no se si este escenario va asi o si se deberia validar

**Comment by edwargl7** [comment]
Buenas pruebas y buenas observaciones para documentos no existentes en terceros y búsqueda aproximada
