### ISSUE TITLE
Validación sistema de plantillas renderizado

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#202]
Se requiere realizar la revisión del funcionamiento requerido para Sísifo del sistema implementado de plantillas, basado en el template creado en la Issue #185.

**Sub Tareas**

- [x] Revisión registro de sistema de información para Sísifo
- [x] Registro plantilla en microservicio CRUD de plantillas [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless/tree/feature/samServerless) - el servicio se encuentra desplegado
- [x] Ejecución del microservicio plantillas mid en local para validación de función de renderizado a PDF.

**Criterios de aceptación**

- [x] Documentación de los registros creados y pruebas funcionales.

**Requerimientos**

- Solicitud cURLs para consultas al serverless CRUD.
- Solicitud cURLs para consultas al MID.

**Especificaciones Técnicas**
- Microservicio [plantillas_mid](https://github.com/udistrital/plantillas_mid)

**Material de apoyo**
- Documentación técnica https://github.com/udistrital/plantillas_cliente/issues/53

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se prueba planilla_crud_serverless
![Image](https://github.com/user-attachments/assets/12088044-ae7a-4bcf-a5a7-4abbd6e8538c)

se revisa issues de [backlog de servicio de plantillas](https://github.com/orgs/udistrital/projects/66/views/1) para comprender la estructura  json para registrar la planilla diseñada

**Comment by jucastro94** [comment]
se realiza clonacion de [plantillas_mid](https://github.com/udistrital/plantillas_mid ) 
![Image](https://github.com/user-attachments/assets/aaf7237d-57dd-48cb-82dc-212d2a9df4f1)

se realiza ejecucion desde rama develop segun instrucciones en el README, se genera error
![Image](https://github.com/user-attachments/assets/765bde2d-35b3-4cb5-8098-56de41c53306)

se hace cambio a rama refactor/nuevasfuncionalidades, se realiza ejecuacion generando error
![Image](https://github.com/user-attachments/assets/c4cf3f9b-61b1-43d4-beef-06ddcb52f4a9)

**Comment by jucastro94** [comment]
se realiza busqueda para trabajar con varias versiones de go en windows

**Comment by jucastro94** [comment]
se cambia a version de go 1.19
![Image](https://github.com/user-attachments/assets/2e7d34d0-40ce-42a8-8e33-5ff1924d8027)

se ejecuta nuevamente segun lo establecido en el README
![Image](https://github.com/user-attachments/assets/3ac4e248-bf3d-40f1-9d84-c47f9a8b6f7d)

lanza error en tiempo de ejecucion ![Image](https://github.com/user-attachments/assets/6fcea090-8ba2-431a-918f-4831d526d026)

**Comment by jucastro94** [comment]
se realiza revision del backlog para la generacion de plantillas, al parecer no se ha implementado tratamiento de CSS

plantillas_mid implementa herramienta [gofpdf]( https://pkg.go.dev/github.com/jung-kurt/gofpdf#pkg-functions) para la gerenarcion de plantillas

se realiza revision de esta herramienta para conocer su alcance

**Comment by jucastro94** [comment]
registro de tipo de auditoria en  [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless/tree/feature/samServerless) 
id de registro: 67031ccf4f0dd1dc2fc79d99
![Image](https://github.com/user-attachments/assets/3cab511b-ab50-45b0-a397-d42ba0fcd0fc)

registro de plantilla
id de registro:  67031e8c8c966687f1dbd77c
![Image](https://github.com/user-attachments/assets/3c028cec-a282-4e6e-940a-3b7e0663fd9d)

**Comment by edwargl7** [comment]
Se debe continuar en la revisión de plantillas MID. Y se observa la creación de la plantilla, sin embargo, no se agrego o no se observa el HTML correspondiente a la plantilla.
