### ISSUE TITLE
Ajustes mockup programación y planeación por cambios requeridos para formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#203]
Se requiere realizar ajustes en el mockup las fases de programación y planeación dado que fue necesario modificar el uso de pasos por acciones que permitieran alcanzar las funcionalidades requeridas para el manejo de registro de auditorias y detalle en la fase de planeación. Los ajuste se detallan en la implementación realizada en la Issue #187.
![image](https://github.com/user-attachments/assets/823a1a10-54e5-452d-b70f-3ad092977d7b)

**Sub Tareas**

- [x] Actualización mockup de programación.
- [x] Actualización mockup de planeación.

**Criterios de aceptación**

- [x] Mockup actualizado de programación.
- [x] Mockup actualizado de programación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes solicitados por el líder técnico para los mockups relacionados con los módulos programación y planeación.

Submódulo >> Plan anual de auditoría
![Image](https://github.com/user-attachments/assets/92a3a5da-625a-42ba-a4b2-ada24acecd96)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Programaci%C3%B3n/Subm%C3%B3dulo%20Plan%20Anual%20de%20Auditor%C3%ADa?csf=1&web=1&e=m1NSIp


**Submódulo >> Auditoría Interna**
![Image](https://github.com/user-attachments/assets/c67e4087-c3c7-4534-8abd-261b5ac9ed61)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Planeaci%C3%B3n/Subm%C3%B3dulo%20Auditor%C3%ADas%20Internas?csf=1&web=1&e=Z3Zmu1


**Submódulo >> Auditoría de Seguimiento e Informes**
![Image](https://github.com/user-attachments/assets/aebf173f-7b8c-4a93-8669-914d6068f52a)

**Enlace archivos guardados en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Planeaci%C3%B3n/Subm%C3%B3dulo%20Seguimiento%20e%20Informes?csf=1&web=1&e=OpmvMs


Saludos.

**Comment by edwargl7** [comment]
Muy buena propuesta, se va a evaluar en desarrollo la posibilidad de la tabla resumen para las actividades, si se logra con exito a nivel de desarrollo se propone cambiar la transición del paso dos de actividades (formularios dinámico a formularios dinámico array forms) por (formularios dinámico -> formulario propio sísifo -> formularios dinámico) y permitir en este último la posibilidad de regresar al inicial nuevamente una vez finalizada la edición de actividades.

**Comment by edwargl7** [comment]
Se finaliza la Issue correctamente.
