### ISSUE TITLE
Implementación microservicio MID plantillas formularios dinámicos - Base

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#204]
Se requiere realizar la implementación base del microservicio MID basado en la revisión realizada en la Issue #198. Que cuente con el health Check y la implementación inicial de consumo de CRUDs para registrar la información como sea enviada desde el formulario del microcliente.

**Sub Tareas**

- [x] Implementación base del microservicio.
- [x] Implementación endpoint health check.
- [x] Implementación endpoint consumido por el microcliente para almacenar cualquier información enviada por el microcliente.
- [x] Implementación similar al RequestManager.
- [x] Prueba de integración endpoint health check.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados de pruebas funcionales.

**Requerimientos**

No aplica

**Especificaciones técnicas**
- Repositorio microservicio mid [formularios_dinamicos_mid](https://github.com/udistrital/formularios_dinamicos_mid)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza instalacion de nest y typescrip
![Image](https://github.com/user-attachments/assets/5a66a904-b941-4934-9309-a635a5607888)

se realiza creacion del proyecto
![Image](https://github.com/user-attachments/assets/79dfd9ac-49e6-4439-933f-cd98731d735d)
![Image](https://github.com/user-attachments/assets/f2c45d92-469e-40f2-9b5d-2513f6ebf7d4)

**Comment by jucastro94** [comment]
se reestructura el servicio a arquitectura por capas, se crea capa controller, capa service
![Image](https://github.com/user-attachments/assets/05a7acf3-63a9-4981-ae6c-58a487c81357)

controller
![Image](https://github.com/user-attachments/assets/f09cfa84-beb2-48fb-83a7-7ca427656c7e)

service 
![Image](https://github.com/user-attachments/assets/2886b3ee-52bc-465d-8032-eb24215ba440)


se implementan variables de entorno para configuracion del puerto
![Image](https://github.com/user-attachments/assets/5269ab85-0f52-45ea-9e8d-f3a2a59fd2a9)
![Image](https://github.com/user-attachments/assets/ca2bc8fc-f1fa-42d6-8bcc-126875a619fc)

se implementa healthcheck
![Image](https://github.com/user-attachments/assets/4f8cbe66-2c5c-40ee-bafd-ac9d2cf10f82)

se realiza prueba funcional de healthckeck y endpoint
![Image](https://github.com/user-attachments/assets/25c22e58-365f-4a06-bc23-a57fa42cf0dd)
![Image](https://github.com/user-attachments/assets/050deff6-3bb0-4b04-8c7d-732cf5753d39)

**Comment by jucastro94** [comment]
se realizan ajustes en la arquitectura del servicio
![Image](https://github.com/user-attachments/assets/194bc336-53c9-4791-b6ea-c1bbcb7fbcff)

se realizan ajustes en el healthcheck
![Image](https://github.com/user-attachments/assets/5b6a3b19-333d-422e-b0a5-9cef153e070a)

**Comment by jucastro94** [comment]
se realiza prueba al healthcheck
![Image](https://github.com/user-attachments/assets/2230d7ea-8fa5-4019-a3b4-6444a83122b9)

**Comment by jucastro94** [comment]
se implementa logica en service para agrupado de objetos
![Image](https://github.com/user-attachments/assets/8b13f333-299d-426f-b5d3-e2b8d0865634)
se realiza prueba
```json
{
    "Success": true,
    "Status": 200,
    "Messaje": "data formuario dinamico recibido",
    "agrupados": {
        "prueba-endopoint1": {
            "endpoint": "prueba-endopoint1",
            "servicio": "terceros",
            "items": [
                {
                    "nombre": "nombre",
                    "descripcion": "Nombre del usuario",
                    "label": {
                        "valor": "Nombre"
                    },
                    "tipo": "text",
                    "placeholder": {
                        "valor": "Escriba aquí su nombre"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        },
                        {
                            "tipo": "min",
                            "valor": "10"
                        },
                        {
                            "tipo": "max",
                            "valor": "10"
                        }
                    ]
                },
                {
                    "nombre": "apellidos",
                    "label": {
                        "valor": "Apellidos"
                    },
                    "parametros": {
                        "valor": "valor por default"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "tipo": "text",
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        }
                    ]
                },
                {
                    "nombre": "edad",
                    "label": {
                        "valor": "Edad"
                    },
                    "placeholder": {
                        "valor": "Ex. pat@example.com"
                    },
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        },
                        {
                            "Tipo": "min",
                            "valor": "10"
                        },
                        {
                            "Tipo": "max",
                            "valor": "10"
                        }
                    ],
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "tipo": "number"
                }
            ]
        },
        "prueba-endopoint2": {
            "endpoint": "prueba-endopoint2",
            "servicio": "otro service",
            "items": [
                {
                    "nombre": "nickname",
                    "label": {
                        "valor": "Nickname"
                    },
                    "parametros": {
                        "valor": "tunick"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "tipo": "text",
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        }
                    ]
                },
                {
                    "nombre": "email",
                    "label": {
                        "valor": "Correo Electrónico"
                    },
                    "placeholder": {
                        "valor": "Ex. pat@example.com"
                    },
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        },
                        {
                            "Tipo": "email",
                            "valor": ""
                        }
                    ],
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "tipo": "email"
                }
            ]
        }
    }
}
```
hace falta aplicar mas reglas para el correcto agrupado de los objetos

**Comment by jucastro94** [comment]
se implementa servicio de request manager
![Image](https://github.com/user-attachments/assets/01a769c2-7d1a-4f59-8b28-40a107a601ba)

**Comment by jucastro94** [comment]
se ajusta logica de servico ![Image](https://github.com/user-attachments/assets/637ad4a1-4bc1-4557-98bb-2228bf34075f)

**Comment by jucastro94** [comment]
se realizan pruebas
![Image](https://github.com/user-attachments/assets/d6e63c66-a862-48d0-bac3-89fda4ae0022)

```json
{
    "Success": true,
    "Status": 200,
    "Messaje": "data formuario dinamico recibido",
    "agrupados": {
        "agrupados": {
            "prueba-endopoint1": {
                "endpoint": "prueba-endopoint1",
                "servicio": "terceros",
                "items": [
                    {
                        "agrupado": true,
                        "nombre": "apellidos",
                        "label": {
                            "valor": "Apellidos"
                        },
                        "parametros": {
                            "valor": "valor por default"
                        },
                        "deshabilitado": false,
                        "solo_lectura": false,
                        "tipo": "text",
                        "validaciones": [
                            {
                                "tipo": "requerido",
                                "valor": ""
                            }
                        ]
                    },
                    {
                        "agrupado": true,
                        "nombre": "edad",
                        "label": {
                            "valor": "Edad"
                        },
                        "placeholder": {
                            "valor": "Ex. pat@example.com"
                        },
                        "validaciones": [
                            {
                                "tipo": "requerido",
                                "valor": ""
                            },
                            {
                                "Tipo": "min",
                                "valor": "10"
                            },
                            {
                                "Tipo": "max",
                                "valor": "10"
                            }
                        ],
                        "deshabilitado": false,
                        "solo_lectura": false,
                        "tipo": "number"
                    }
                ]
            },
            "prueba-endopoint2": {
                "endpoint": "prueba-endopoint2",
                "servicio": "otro service",
                "items": [
                    {
                        "agrupado": true,
                        "nombre": "email",
                        "label": {
                            "valor": "Correo Electrónico"
                        },
                        "placeholder": {
                            "valor": "Ex. pat@example.com"
                        },
                        "validaciones": [
                            {
                                "tipo": "requerido",
                                "valor": ""
                            },
                            {
                                "Tipo": "email",
                                "valor": ""
                            }
                        ],
                        "deshabilitado": false,
                        "solo_lectura": false,
                        "tipo": "email"
                    }
                ]
            }
        },
        "desagrupados": {
            "prueba-endopoint1": [
                {
                    "endpoint": "prueba-endopoint1",
                    "servicio": "terceros",
                    "agrupado": false,
                    "nombre": "nombre",
                    "descripcion": "Nombre del usuario",
                    "label": {
                        "valor": "Nombre"
                    },
                    "tipo": "text",
                    "placeholder": {
                        "valor": "Escriba aquí su nombre"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        },
                        {
                            "tipo": "min",
                            "valor": "10"
                        },
                        {
                            "tipo": "max",
                            "valor": "10"
                        }
                    ]
                }
            ],
            "prueba-endopoint2": [
                {
                    "endpoint": "prueba-endopoint2",
                    "servicio": "otro service",
                    "agrupado": false,
                    "nombre": "nickname",
                    "label": {
                        "valor": "Nickname"
                    },
                    "parametros": {
                        "valor": "tunick"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "tipo": "text",
                    "validaciones": [
                        {
                            "tipo": "requerido",
                            "valor": ""
                        }
                    ]
                }
            ]
        }
    }
}

```

**Comment by edwargl7** [comment]
Buen trabajo, el README se debe actualizar y ajustar los nombre de referencia en el mismo dado que contiene referencias a otro repositorio.
Cuenta con un nombre claro en las funciones, se reajustará la lógica de agrupación una vez confirmada la estructura a emplear y enviada desde el microcliente de formularios dinámicos.
