### ISSUE TITLE
Ajuste campos validaciones y parámetros microservicio CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#205]
Se requiere realizar el ajuste en el modelo de datos sugerido en el [kb 62541](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62541) cambiando validaciones y parámetros a singular. Y realizar este cambio en el CRUD de tal forma que para evitar cambios adicionales en el microcliente, el CRUD pueda almacenar y retornar estos campos en plurall y en base de datos los maneje en singular.

**Sub Tareas**

- [x] Actualización modelo de datos.
- [x] Ajustes en microservicio CRUD.

**Criterios de aceptación**

- [x] Documentación avances y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Cambios en el Modelo de Datos

1. **Actualización del Modelo**:
   - Se realizó el cambio del modelo de datos de acuerdo a las especificaciones requeridas.

2. **Validaciones**:
   - Se revisó el funcionamiento de las validaciones, que se reciben como un array de objetos, mientras que los parámetros se gestionan como un objeto clave-valor.
![image](https://github.com/user-attachments/assets/50a989be-fb72-4478-84b8-421f6f5d19c2)


![image](https://github.com/user-attachments/assets/a9df443f-1a48-4d21-a115-cc67385ad6db)

![Modelo de datos - formularios dinámicos V10-versión 10 drawio](https://github.com/user-attachments/assets/76507fa1-460b-4596-bc32-68fa9f36ab65)

**Comment by edwargl7** [comment]
De la revisión con @cjgonzalezp se requiere agregar el campo "valor" para permitir valores predefinidos en cada campo.

**Comment by CristianCGutierrezG** [comment]
### Ajustes sugerido en el [kb 62541](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=62541)

![Modelo de datos - formularios dinámicos-version 11 drawio](https://github.com/user-attachments/assets/b7aba9f8-e020-479b-a653-57db0bca405c)

**Comment by CristianCGutierrezG** [comment]
## Modelo de datos nueva versión

![Modelo de datos - formularios dinámicos-version 11 drawio (2)](https://github.com/user-attachments/assets/43bf1400-0789-4dcb-b882-1d4c4cf98a52)

**Comment by CristianCGutierrezG** [comment]
### Cambios en el CRUD y Base de Datos

**Actualización de Campos en el CRUD**:
   - Se realizaron los cambios respectivos para los campos de `parámetros` y `validaciones` en el CRUD. Ahora la base de datos guarda los datos en **singular** para mantener la consistencia del modelo.
   - Tambien se realiza el cambio para que `validacion` se guarde como un array de objetos.
   
![image](https://github.com/user-attachments/assets/2cd192a5-7194-47f7-b019-bd103c93de1d)

![image](https://github.com/user-attachments/assets/673610f6-a8d0-4146-a5b3-5e0b879af2b9)


- Datos guardados en la BD

![image](https://github.com/user-attachments/assets/87add68d-20c3-4a68-b6e4-ef1fb2625454)


 **Servicio de Plantillas**:
   - Se ajustas el servicio de plantillas para que siga recibiendo y devolviendo los datos en **plural** para que el microcliente los interprete correctamente. 
  
![image](https://github.com/user-attachments/assets/623be6b3-fad4-40d7-b81b-62aaa0c4c0b4)

![image](https://github.com/user-attachments/assets/ec02d3e3-5bc7-4a6b-83e1-688962b19be4)

- Datos guardados en la BD

![image](https://github.com/user-attachments/assets/cd21e9af-74f5-4163-89cd-3662ef0b5814)

**Comment by CristianCGutierrezG** [comment]
## Modelo de datos 

Se realiza el cambio de `label` a `etiqueta` en todas las colecciones que lo utilizan

![Modelo de datos - formularios dinámicos-version 11 drawio (4)](https://github.com/user-attachments/assets/59bfb628-5e8e-41c7-846a-f6edcce568f7)

Versión actual del modelo:
[formularios dinámicos-version11](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYP6ugJu5WtJlBc8jSGAfvQBMKhfj7J_S6VwD-muFDA0mA?e=GFJLdC)

**Comment by edwargl7** [comment]
Muy buen trabajo, ajustes al modelo realizados correctamente y actualizado en el repositorio. Se resuelve PR.
