### ISSUE TITLE
Actualización swagger metadata autenticación mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#206]
Se requiere realizar la actualización del swagger agregando los campos de metadata.

**Sub Tareas**

- [x] Actualización swagger agregando nueva estructura de respuesta.

**Criterios de aceptación**

- [x] Commit con ajuste a los swaggers.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Actualización swagger

Se realiza la actualización del swagger mediante el modelo de MetadataResponse para GerAllPeriodos y GetPeriodoInfo

![Captura de pantalla 2024-10-08 a la(s) 8 48 52 a m](https://github.com/user-attachments/assets/d7ff3db0-456e-4180-8ca2-8a8d9c2b823d)

![Captura de pantalla 2024-10-08 a la(s) 8 55 58 a m](https://github.com/user-attachments/assets/d58853da-e9b6-4a3a-94df-3601cf8030d2)

**Comment by edwargl7** [comment]
Se realiza la actualización con ayuda del arquitecto y por el momento se observa el correcto funcionamiento. Muy buen trabajo.
