### ISSUE TITLE
Implementación campos para distribución de información del formularido - microservicio CRUD y microcliente

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#207]
Se requiere realizar la implementación en el microservicio CRUD de los campos nuevos diseñados en el modelo de datos. Que permitan realizar la base del microservicio mid para la distribución de los datos de formularios dinámicos. 

**Sub Tareas**

- [x] Implementación campos nuevos en campos del microservicio CRUD.
- [x] Implementación de envío de campos nuevos desde el microcliente al guardar un formulario.
- [x] Implementación parcial de campos nuevos al crear un formulario (posteriormente se evaluara la fuente de estos campos con el arquitecto).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultados de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Nuevos Campos en el CRUD:

1. **Campos Agregados**:
   - Se han añadido los nuevos campos propuestos al modelo de datos en el servicio CRUD, incluyendo:
     - **Archivo**
     - **Servicio**
     - **Endpoint**
     - **Campo**
     - **Agrupado**

2. **Pruebas de Funcionamiento**:

**Endpoint de Campo**
![image](https://github.com/user-attachments/assets/02490fc2-50dd-4fa8-9408-f960e1767d57)

  - **Datos Guardados en la BD**
![image](https://github.com/user-attachments/assets/aa32e5fe-4ceb-472f-853d-1108fb6389d5)

  **Endpoint de Plantilla**
![image](https://github.com/user-attachments/assets/1a52816d-6ae1-4a1c-93ba-7d74ecb3d8ac)

  - **Datos Guardados en la BD**
![image](https://github.com/user-attachments/assets/d9035db0-bded-446b-8eb9-72b5b4871c3e)

**Comment by CristianCGutierrezG** [comment]
**Cambios en el Valor `label` a `etiqueta`**:
   - Se ha reemplazado el valor `label` por `etiqueta` en todas las colecciones del CRUD que utilizaban este campo (formularios, secciones, campos) .
   - Los cambios fueron aplicados tanto en el modelo de datos como en los servicios y controladores correspondientes.

**Pruebas de Funcionamiento**:
   - Se realizaron pruebas exitosas para verificar el correcto funcionamiento de las modificaciones. 
   - Los datos que antes utilizaban `label` ahora se almacenan y se recuperan con el campo `etiqueta`.
   
![image](https://github.com/user-attachments/assets/f2d01ed6-9447-4172-9e95-b2d15014b6fc)
![image](https://github.com/user-attachments/assets/ae9816ad-9146-4413-af09-29133eb2acd5)

 **Actualización del Modelo de Datos**:
   - El modelo de datos ha sido actualizado en el repositorio de [plantillas_formularios_dinamicos_crud](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Comment by CristianCGutierrezG** [comment]
Se realiza implementación de los nuevos valores de distribución en la creación de campos en la creación de formularios dinamicos. 

![image](https://github.com/user-attachments/assets/2b753754-1cac-442b-b826-db659be3b858)

Se imprime por consola el resultado para verificar cómo se estarían guardando los datos en la base de datos.

![image](https://github.com/user-attachments/assets/420224a9-0fdf-44a8-aedc-808af9bf40e6)


**Notas**:
   - **Validaciones**: No se tienen implementadas validaciones de llenado en los campos de creación de formularios, lo que podría permitir el envío de datos incompletos o incorrectos.
   - **Relación con el Módulo**: Al crear un nuevo formulario, no se está teniendo en cuenta a qué módulo pertenece. Este aspecto sigue pendiente de implementación.
   - **Lógica de Guardado**: La lógica para determinar a qué servicio o módulo se debe hacer referencia al momento de guardar no está completamente implementada.

**Comment by CristianCGutierrezG** [comment]
**Ajustes Implementados en el servicio CRUD**:
   - Se ha realizado el ajuste para que el sistema reconozca **secciones** en lugar de **sección** y **campos** en lugar de **campo** al momento de crear el formulario.

**Pruebas Realizadas**:
   - Se realizó una prueba para enviar los datos al servicio CRUD, incluyendo de forma directa los datos faltantes temporalmente.
   
![image](https://github.com/user-attachments/assets/89f3ba62-0bba-4e65-91b4-6201cb46ce20)

   - **Prueba de Guardado en la BD**
   ![image](https://github.com/user-attachments/assets/81710534-549a-4e91-a63a-d73a1d88be81)
   ![image](https://github.com/user-attachments/assets/e13d2822-0f13-493c-9c65-070c06207384)
   ![image](https://github.com/user-attachments/assets/73d8dd31-04ed-413f-80e6-beef80f9d87a)

**Campos Necesarios No Incluidos en la Creación del Formulario**:
![image](https://github.com/user-attachments/assets/1f661f08-f0b2-48c3-9621-c6deb73c7c67)

   - **Información relacionada con el formulario**:
     - `modulo_id`: No se está incluyendo en la creación del formulario.
     - `creado_por_id`: Tampoco se está incluyendo.
   - **Información relacionada con el campo**:
     - `solo_lectura`: No está implementado en el microcliente, ¿Sera necesario este campo?
    
**Diferencias Detectadas**:
   - El valor de **etiqueta** sigue almacenándose en el CRUD como un objeto, pero el microcliente lo interpreta como un string. Esto genera inconsistencias.
   -  No se está guardando la relación con el módulo al que pertenece el formulario ni el periodo relacionado.

**Error Encontrado**:
   - Hay un error en la construcción del formulario cuando la opción de **visualización** está activa. Si se realiza una modificación posterior, puede dañar el renderizado en la visualización del formulario.

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR. Tener presente las diferencias, en lo posible si se logrará mantener por el momento que el campo etiqueta soporte tanto si se pasa string como objeto dado que se podría más adelante requerir el uso de ese campo como objeto para usar traducción según sea requerido por el sistema y que no sea necesario hacer modificaciones en el CRUD para soportar las dos alternativas.
