### ISSUE TITLE
Validación sistema de plantillas renderizado - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#208]
Se requiere realizar la revisión del funcionamiento requerido para Sísifo del sistema implementado de plantillas el microservicio de plantillas mid, revisado inicialmente en la Issue #202, que en dichas pruebas no se logró el correcto funcionamiento, por lo que se realiza una evaluación adicional.

**Sub Tareas**

- [x] Ejecución del microservicio plantillas mid en local para validación de función de renderizado a PDF. Microservicio [plantillas_mid](https://github.com/udistrital/plantillas_mid)

**Criterios de aceptación**

- [x] Documentación de pruebas funcionales.

**Requerimientos**

No aplica

**Material de apoyo**
- Documentación técnica https://github.com/udistrital/plantillas_cliente/issues/53

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] #210
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance revision plantillas_mid

Se realiza la clonación del proyecto y se inicia su revision

Al ejecutarlo según indicaciones del readme se encuentra el siguiente error:

![Captura de pantalla 2024-10-08 a la(s) 10 51 29 p m](https://github.com/user-attachments/assets/82f3922f-ba2e-42ef-bf42-0a6d48bf03db)

Se inicia la búsqueda del error y se encuentra que el archivo de controllers solo tiene los métodos Post y Put implementados:

![Captura de pantalla 2024-10-09 a la(s) 8 28 14 a m](https://github.com/user-attachments/assets/963431d0-d3d8-40ca-87ae-048b5efeb21c)

Sin embargo, en el archivo commentsRouter_controllers.go se hace referencia a métodos GetAll, GetOne y Delete que no se encuentran definidos en el controller.

![Captura de pantalla 2024-10-09 a la(s) 8 27 00 a m](https://github.com/user-attachments/assets/81ed99c5-b8b2-4afe-a4ef-f11e460cf8fe)

Para permitir la ejecución del microservicio se dejan comentados los métodos mencionados anteriormente y se ejecuta correctamente:

![Captura de pantalla 2024-10-09 a la(s) 8 52 01 a m](https://github.com/user-attachments/assets/726f9881-39b9-481e-98a7-00e43dabe30b)

Adicionalmente se inicia con la revision del material de apoyo suministrado

**Comment by edwargl7** [comment]
Se informa por parte de @a52290451 que la rama que cuenta con el último desarrollo es https://github.com/udistrital/plantillas_mid/tree/refactor/nuevasfuncionalidades con la cual se procede terminar de revisar el funcionamiento desarrollado.

**Comment by edwargl7** [comment]
Se trabajarán pruebas similares a las realziadas en la Issue https://github.com/udistrital/sisifo_documentacion/issues/185

**Comment by alexhrr** [comment]
Se realiza el cambio de rama para la ejecución y revision del código. Al ejecutarlo se encuentra el siguiente error:

![Captura de pantalla 2024-10-10 a la(s) 9 45 21 p m](https://github.com/user-attachments/assets/750f257c-0c91-4283-867b-2ebc3b768d6e)

Se realiza la verificación del código para validar el método PruebaConexion que es el que aparentemente esta generando el error, se identifica que no esta creado como tal en el controlador y se encuentra en las siguientes partes del código

Plantilla controller:

![Captura de pantalla 2024-10-10 a la(s) 9 51 50 p m](https://github.com/user-attachments/assets/4eb35c07-3596-46ce-a0eb-5c763d4d500a)

router.go:

![Captura de pantalla 2024-10-10 a la(s) 9 50 44 p m](https://github.com/user-attachments/assets/92c863c3-4d08-4c11-9722-5c404e7f2a8f)

Se debe identificar el propósito de PruebaConexion en el código para realizar los cambios necesarios.

Adicionalmente se realiza la revision de la grabación del empalme Modulo plantillas

**Comment by edwargl7** [comment]
https://github.com/udistrital/plantillas_mid/blob/refactor/nuevasfuncionalidades/services/plantilla_service.go#L193

**Comment by alexhrr** [comment]
Se realizan las modificaciones sugeridas para ejecutar el código omitiendo PruebaConexion y se ejecuta en el puerto 8080.

Se comienza con la prueba de la función ProcesarDocumento para crear el pdf a partir del documento json que contiene el html para el plan anual de auditoria.

Al realizar cambios en la función y ejecutar el código para crear el pdf se generan bastantes errores, algunos son:

El html debe contener un id:
 
![Captura de pantalla 2024-10-11 a la(s) 4 39 49 p m](https://github.com/user-attachments/assets/95728454-0961-43cd-94a4-7928e1a4b8c2)

Se omite la verificación del id y se ejecuta de nuevo. Se debe instalar wkhtmltopdf para poder usarlo en la creación del pdf

![Captura de pantalla 2024-10-11 a la(s) 3 49 35 p m](https://github.com/user-attachments/assets/73ed06d0-17f3-4483-aa0d-94ba2c925aae)

Se realiza la instalación y se generan errores ahora con las imagenes que se tienen en el html

![Captura de pantalla 2024-10-11 a la(s) 3 46 02 p m](https://github.com/user-attachments/assets/474b3cbb-3d00-40dd-a494-3520b858839f)

continuan los errores con las imagenes:

![Captura de pantalla 2024-10-11 a la(s) 8 17 14 p m](https://github.com/user-attachments/assets/757ec536-bbaa-42bc-9de9-96b875c98023)

**Comment by edwargl7** [comment]
Se logra un gran avance, sin embargo, no se logra completar la prueba de renderizado completamente. Muy buen trabajo, se planteará la forma de completar la funcionalidad requerida.
