### ISSUE TITLE
Ajustes Mockup información de programación y planeación - Modal adicional de registro de información

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#209]
Se requiere realizar la creación de dos modales de registro de información exitoso y en caso que exista un error para el paso de registro de información, que aunque lo solicitado por el usuario es tener los valores predeterminados y que son poco cambiantes, se le va a permitir editarlos por lo que es necesario tener los modales que le permitan confirmar que cualquier cambio que pudiera o no hacer se almacena correctamente.
 
![image](https://github.com/user-attachments/assets/36d641ad-9856-4592-adab-33c1c4953854)

**Sub Tareas**

- [x] Diseño de los dos modales para cada caso.

**Criterios de aceptación**

- [x] Actualización del mockup.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza ajuste a mockup del módulo programación>>plan anual de auditorías creación de modales adicionales de edición de plan de acción. "confirmación, guardado exitoso y error al guardar edición"

![Image](https://github.com/user-attachments/assets/bd991a8f-d20f-42ca-a41e-2c7da6eb794e)

**Enlace guardado en OneDrive en la carpeta del proyecto SISIFO V2**
**Opción 2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Programaci%C3%B3n/Subm%C3%B3dulo%20Plan%20Anual%20de%20Auditor%C3%ADa?csf=1&web=1&e=UbiLd1

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza ajuste de acuerdo a revisión en reunión con equipo SoS y se da por finalizada la issue 209


![Image](https://github.com/user-attachments/assets/0638aa9a-6963-4a9c-9162-f50f098d2af4)



Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo en diseño @cjgonzalezp
