### ISSUE TITLE
Ajuste Microfrontend Sísifo Root-mf - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#21]
Se requiere realizar la revisión de los estilos con los cambios que se están evaluando para pasarlos del core mf al root mf. Continuación tarea [Creación Microfrontend Sísifo Root-mf - Parte 1](https://github.com/udistrital/sisifo_documentacion/issues/14)

**Sub Tareas**

- [x] Revisión modificaciones en los lineamientos para el manejo de los estilos.
- [x] Desarrollar microfrontend Root

**Criterios de aceptación**

- [x] Cliente root ajustado

**Requerimientos**

[ ] Finalizar issue [Creación Microfrontend Sísifo Root-mf - Parte 1](https://github.com/udistrital/sisifo_documentacion/issues/14)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se bloquea esta tarea ya que requiere una investigación más detallada para hacer el ajuste y se le da prioridad a la tarea https://github.com/udistrital/sisifo_documentacion/issues/23

**Comment by alexhrr** [comment]
Se realizó el ajuste que había quedado pendiente del favicon y el cargue al repositorio con la corrección del environment, sin embargo, queda pendiente el manejo de estilos (paleta de colores) ya que falta definir el proceso para solucionarlo desde el root.

**Comment by alexhrr** [comment]
## Uso de paleta de colores para Sisifo

Se agrega la siguiente linea de código siguiendo las propuestas para el manejo de estilos que se tiene hasta el momento y se actualiza el repositorio.

```bash
 <link rel="stylesheet" href="https://pruebasassets.portaloas.udistrital.edu.co/gaia-style.css">
```

Se observa como se aplica el color definido para el sistema en las siguientes imágenes:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/916bd414-204c-41f0-88f6-ca278e594b1c)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/a2122e5a-6aea-4c1c-ba16-5d1c344c4480)

**Comment by edwargl7** [comment]
Muy buena investigación, se realiza la revisión de los ajustes. Adicional, se realiza una explicación al equipo del proceso realizado hasta el momento, los errores que se presentaron en el proceso y los ajustes realizados.
