### ISSUE TITLE
Revisión y actualización Mockup Papeles de trabajo de la actividades - Fase de planeación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#211]
Se requiere realizar la revisión con el usuario sobre si es necesario en el momento del registro de cada actividad contar con el registro de los papeles de trabajo, en caso que es esos valores no sean necesarios diligenciarlos en ese momento se pueden remover del formulario y se mantienen en la plantilla que genera el PDF para mantener el formato.
![image](https://github.com/user-attachments/assets/168e46cc-e1a3-4c6c-82ea-4bd728337a4e)

**Sub Tareas**

- [x] Consulta registro de papeles de trabajo en la fase de planeación (fase 2).
- [x] Actualización del mockup según corresponda.

**Criterios de aceptación**

- [x] Actualización del mockup según corresponda.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se espera respuesta por parte del cliente frente a esta issue para proceder con el posible ajuste del mockup 


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Comparto respuesta por parte del usuario en relación a la información referenciada como papeles de trabajo, según comentario de Henry Arenas esta información a pesar de que va en el formato programa de trabajo solo es diligenciada en muy pocos casos cuando se entrega documentación para la auditoria de forma física por parte del auditado. 

![Image](https://github.com/user-attachments/assets/7e5a6ecd-87e5-453b-bc22-971f984285da)

Adicionalmente Henry comenta que por auditoría podrían registrar aprox de 15 a 20 actividades, por lo cual se plantean las siguientes opciones de diseño y se quitan los campos de papeles de trabajo en esta fase de planeación.

**OPCIÓN 1**
![Image](https://github.com/user-attachments/assets/3c0527c5-7e72-44be-a75c-2529284aea31)

**OPCIÓN 2**
![Image](https://github.com/user-attachments/assets/1c15aff9-1db3-42c8-9b91-8883f97a3929)

![Image](https://github.com/user-attachments/assets/d4ac2807-9286-4600-9e08-a8bdf7d748c9)


**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Planeaci%C3%B3n/Subm%C3%B3dulo%20Auditor%C3%ADas%20Internas?csf=1&web=1&e=e8bmS7


Saludos.

**Comment by edwargl7** [comment]
Se mantienen las dos versiones, sin embargo, se busca realizar la opción  1 que brinda una mejor experiencia de usuario.
