### ISSUE TITLE
Apoyo revisión plantilla mid y pruebas de renderizado plan de trabajo

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#213]
Se requiere realizar el apoyo en la revisión del microservicio plantillas mid, basado en el empalme recibido por el equipo que venía desarrollando parte del sistema.

**Sub Tareas**

- [x] Empalme de entrega del proyecto.
- [x] Apoyo en conversión de plantilla a HTML string.
- [x] Apoyo en pruebas de funcionamiento correcto.

**Criterios de aceptación**

- [x] Documentación de apoyo realizado en pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se comparte video de empalme a @alexhrr  

se comparte plantilla HTML y JSON a @alexhrr

**Comment by edwargl7** [comment]
Finalizada correctamente. Muchas gracias.
