### ISSUE TITLE
Implementación estructura envío de datos desde el microcliente de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#214]
Se requiere realizar la implementación del envío de datos recolectados en los formularios junto con los campos servicio, endpoint, campo y agrupación que permitan al MID procesar y distribuir la información.

**Sub Tareas**

- [x] Implementación con envío de datos desde el formulario dinámico.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
**Actualización del Mock**
   - Se realizó el cambio en el mock de Postman para incluir los nuevos valores en cada campo
![image](https://github.com/user-attachments/assets/37e14514-5a73-4a8c-aec3-b39af517f240)

**Implementación del Envío de Datos**
   - Se implementó el envío de los datos recolectados en los formularios, incorporando los campos adicionales:
     - `servicio`
     - `endpoint`
     - `campo`
     - `agrupación`
   - Estos cambios fueron aplicados en la función `onSubmit`
![image](https://github.com/user-attachments/assets/9a1384ea-5e59-473c-9f0c-c4f13b19502f)


**Resultados obtenidos**
![image](https://github.com/user-attachments/assets/6e22ab37-f053-432e-be83-a8b37fd108c0)

**Comment by edwargl7** [comment]
Muy buena implementación, se resuelve el PR.
