### ISSUE TITLE
Implementación stepper en microcliente de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#215]
Se requiere retomar la implementación de stepper en el microcliente donde se permita enviar en cada step la información recopilada en esa sección del formulario para su almacenamiento mediante el MID y su respectivo CRUD.

**Sub Tareas**

- [x] Implementación stepper en microcliente formularios dinámicos.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Actualización del Stepper con Nuevos Cambios

**Actualización de la Implementación**:
   - Se actualizó la implementación del stepper para adaptarse a los nuevos cambios, específicamente a la estructura del campo `parametros`.

**Preguntas Planteadas**:
   - ¿Cómo se espera el envío de datos al MID?
   - ¿El envío debe ser por sección o debe enviarse todo el formulario completo?

**Posibles Soluciones**:
   - **Envío por Sección**:
   Enviar los datos por cada sección, especificando el formulario al que pertenece, teniendo en cuenta que el CRUD debe recibir todo el formulario y la informacion de este.
   - **Reenvío del Formulario Completo**:
   Enviar el formulario completo constantemente, incorporando los nuevos cambios conforme se vayan ingresando los datos en cada paso.

**Implementación Provisional**:
   - Se implementó una solución temporal en la que los datos se envían (momentáneamente impresos en consola) por cada paso del stepper.
![image](https://github.com/user-attachments/assets/73e152fe-83eb-4aef-9235-47add9b24460)


 **Requisitos a tener en cuenta para la Implementación Final**:
   - Necesidad de enviar la información especificando a qué **sección** o **formulario** pertenece, dependiendo del caso.

**Comment by edwargl7** [comment]
Muy buen trabajo. Se solicita apoyo para mediante un vídeo documentar el estado actual de formularios dinámicos.

**Comment by CristianCGutierrezG** [comment]
### Inconvenientes al Implementar el Stepper

Se encontraron inconvenientes al implementar el **stepper** en algunos componentes, como el **crud-formularios**, ya que no estaban adaptados al cambio de estructura entre los modos **stepper** o **acordeón**.

Se realizaron los ajustes necesarios para adecuar los componentes y los moks al nuevo cambio de manera temporal.

![image](https://github.com/user-attachments/assets/ec26c5b1-2bdc-44e5-992b-6716db837abb)

**Comment by CristianCGutierrezG** [comment]
## Estado actual de formularios dinámicos

#### Módulo de Visualización de Formularios

  - Muestra un formulario generado a partir de una plantilla en formato JSON. 
  - Puede estar vacío o en modo edición si se reciben datos preexistentes.
  - Ofrece dos modos de visualización:
    - **Acordeón**: Almacena el formulario completo al finalizar el llenado de los datos.
    - **Stepper**: Almacena cada paso del stepper como una sección independiente.

https://github.com/user-attachments/assets/a5937756-04a7-4b65-812b-81f0cfb275a7



#### Módulo de Listar Formularios

  - Muestra información de los formularios existentes, filtrada por sistema, módulo y periodo.
  - Permite realizar acciones de lectura, edición y manejo de versiones.
  - Está conectado al CRUD, pero debido a que las relaciones de las plantillas no están completamente definidas, los formularios disponibles no se muestran correctamente.

https://github.com/user-attachments/assets/f4e197fd-5924-4cad-88d5-9eed860c5353

#### Módulo de Crear Formularios

  - Permite la creación interactiva de formularios, agregando secciones y campos.
  - Incluye una prueba de almacenamiento de los formularios en el CRUD.


https://github.com/user-attachments/assets/d8aefdb1-99d1-426c-9a54-34e0c6e4fe66



### Conexiones Realizadas con SISIFO

- Se implementó la conexión de algunos módulos de SISIFO con el módulo de visualización de formularios.
- Esto permitió verificar el comportamiento y el traspaso de datos entre los módulos.
https://github.com/udistrital/sisifo_documentacion/issues/195

**Comment by edwargl7** [comment]
Buena implementación realizada.
Muchas gracias por la documentación mediante los vídeos del estado actual de formularios dinámicos.
