### ISSUE TITLE
Presentación modelo de datos auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#216]
Se requiere realizar la presentación y revisión con el equipo DBA del modelo de datos no relacional propuesto para la gestión de datos del módulo de auditoría.

**Sub Tareas**

- [x] Presentación modelo de datos a equipo DBA.
- [x] Realizar ajustes requeridos.

**Criterios de aceptación**

- [x] Documentación observaciones realizadas y ajustes requeridos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza prensentacion del modelo de datos

se realizan correcciones al modelo de datos
se sube version 3.2  carpeta del proyecto
![Image](https://github.com/user-attachments/assets/321d2642-20da-4d31-90a2-2b474212cfda)

**Comment by edwargl7** [comment]
Modelo presentando. Se finaliza la Issue y se queda atento a las observaciones del equipo DBA.
