### ISSUE TITLE
Diseño modelo de datos para gestión de servicios, endpoints y campos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#217]
Se requiere realizar el diseño del modelo de datos que almacenará los datos de servicio, endpoint y campo requeridos por el MID para identificar el sistema al que será enviada la información.

**Sub Tareas**

- [x] Diseño modelo de datos (evaluar modelo relacional).

**Criterios de aceptación**

- [x] Documentación modelo de datos propuesto.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza el diseño inicial para el modelo de datos relacional siguiendo los lineamientos y las recomendaciones.

![modelo gestión de servicios](https://github.com/user-attachments/assets/0b772eae-146c-4d0c-87f4-1bffd973f4fc)

**Comment by edwargl7** [comment]
Diseño realizado correctamente, se puede agregar el campo url a la tabla de servicio. El resto de campos y relación entre tablas es el correcto.
