### ISSUE TITLE
Implementación endpoint de renderizado del plan de auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#219]
Se requiere realizar un endpoint nuevo en el microservicio plantillas mid que consuma el servicio de renderizado de plantillas [renderizado_plantillas_html](https://github.com/udistrital/renderizado_plantillas_html) y [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless), mediante un POST en el que se suministre el id de la plantilla y los datos que se requieren para el renderizado.
```json
{
    "plantilla_id": "X",
    "datos": {}
}
```

**Sub Tareas**

- [x] Implementación endpoint de renderizado de [plantillas en microservicio](https://github.com/udistrital/plantillas_mid).
- [x] Integración endpoint de consulta de plantillas [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless)
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se crea endpoint tipo post que reciba el json propuesto
![image](https://github.com/user-attachments/assets/d63e45fc-a00e-47d1-984f-c74a3ee09c61)

**Comment by jucastro94** [comment]
se crea modelo para establecer el JSON de entrada y los metodos para consumir renderizado [renderizado_plantillas_html](https://github.com/udistrital/renderizado_plantillas_html) y [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless)
![image](https://github.com/user-attachments/assets/d40568e0-9cab-4c14-9065-9ef32a46346f)
![image](https://github.com/user-attachments/assets/c5e1af47-593a-4b5c-854e-954a51478a11)
![image](https://github.com/user-attachments/assets/7f79e63f-d6a8-4c59-955a-07e579adac02)
![image](https://github.com/user-attachments/assets/d8c18d14-fbba-49c6-9c11-107c79ba0197)

**Comment by jucastro94** [comment]
se crea servicio
![image](https://github.com/user-attachments/assets/5e395355-2cfb-4cc3-b143-1d85baa688f0)

**Comment by jucastro94** [comment]
se realizan las correciones propuestas por @alexhrr en la issue #208 para la ejecucion del proyecto
![image](https://github.com/user-attachments/assets/8677cbce-038d-44a3-8611-7927ad0f3df5)

**Comment by jucastro94** [comment]
se realiza registro de plantilla html en [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless), adicionalmente se guarda string de HTML integrando CSS de la plantilla en https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoGRurwNLWhJuDAoWSOZ9lQBIDB7sV7hMGJIqPRqDX-ZTA?e=ZRj8o2

**Comment by jucastro94** [comment]
- se implementan variables de entorno para las url

![Image](https://github.com/user-attachments/assets/309e4325-bbe7-408c-8517-831906580040)

- se mueven metodos de para consumo de servicios de modelo a service

- se corrigen errores para el consumo de  [renderizado_plantillas_html](https://github.com/udistrital/renderizado_plantillas_html) y [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless)

![Image](https://github.com/user-attachments/assets/3830c7b4-6250-486e-84b0-9567fa8aedc6)
![Image](https://github.com/user-attachments/assets/ecc1a33d-539f-417d-af0a-23b9b1294fc4)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales
![Image](https://github.com/user-attachments/assets/0469ed0d-d180-492c-9bed-ecbc8e6849c5)
![Image](https://github.com/user-attachments/assets/99a9b2a3-2e2b-4580-9a41-cff4f6544cd4)


prueba de base64 de respuesta
![Image](https://github.com/user-attachments/assets/2bdd6a3d-99e8-4099-9abb-ad8ad069f070)

**Comment by jucastro94** [comment]
se implementa manejo de errores en cada servicio con errorhandler.HandlePanic
![Image](https://github.com/user-attachments/assets/7515f926-add8-4f32-b43d-d2f92209282e)

![Image](https://github.com/user-attachments/assets/0f6f4ea7-f7dc-41af-90f4-5a99aaf817e7)

![Image](https://github.com/user-attachments/assets/eaa9c605-1049-4954-afd6-8d955e9922a6)

**Comment by edwargl7** [comment]
Revisión reutilización variable servicio CRUD de plantillas.
![image](https://github.com/user-attachments/assets/af1ae3b2-baf3-4b6e-9db8-edf10f4809dc)
Revisión comments routes comentado, se pueden remover el llamado de estos controladores en los routes por default para evitar que se generen en la documentación.
![image](https://github.com/user-attachments/assets/b43d592c-5fcd-429a-b882-de2723872a30)

Muy buena implementación, podemos separar la lógica implementada en un controlador y service separado para mantener una división de la funcionalidad.
