### ISSUE TITLE
Revisión servicio parametros_crud para datos paramétricos identificados

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#22]
Se requiere realizar la revisión del servicio [parametros_crud](https://github.com/udistrital/parametros_crud) con las tablas paramétricas identificadas en las Issues de sprints anteriores en las que se identificaron los posibles registros que pueden ser almacenados en este servicio:

- https://github.com/udistrital/sisifo_documentacion/issues/17
- https://github.com/udistrital/sisifo_documentacion/issues/18

**Sub Tareas**

- [x] Revisión servicio parametros_crud
- [x] Establecer y organizar los datos paramétricos de Sísifo identificados hasta el momento que se van a almacenar y la estructura dentro de este servicio.

**Criterios de aceptación**

- [x] Lista de campos paramétricos del Sísifo que se almacenaran en el servicio parametros_crud contemplando la estructura y agrupación requerida.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Lista de campos paramétricos del Sísifo que se almacenaran en el servicio parametros_crud contemplando la estructura y agrupación requerida.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se identifican las tablas cuya informacion va a ser tratada meditante servicio parametros
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/cccc93f8-c82a-4e0a-a6c4-a692e568ef24)

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/0bff51cb-545d-469f-90e4-29a87d6c7c03)

**Comment by edwargl7** [comment]
Se revisa la tarea y cumple con la revisión inicial requerida, posteriormente se revisaran registros de la base de datos del servicio parametros_crud ya como parte del proceso de creación del microservicios core de Sísifo. Muy buen trabajo.
