### ISSUE TITLE
Integración cargue masivo de auditorías en el microcliente de plan de auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#220]
Se requiere realizar la integración de la funcionalidad de cargue masivo [cargue_archivo_mid_serverless](https://github.com/udistrital/cargue_archivo_mid_serverless) con el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)

**Sub Tareas**

- [x] Integración e implementación cargue masivo de auditorías.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance integración cargue masivo

Se inicia la integracion buscando realizar el cargue del de un archivo csv al modal creado el la prueba del cargue de la matriz.

Se realiza la revision del código anterior para verificar el método usado para subir el pdf y se esta usando uploadAnyFormat asi que se procede a quitar la verificación del archivo pdf:
 
![Captura de pantalla 2024-10-16 a la(s) 10 41 34 p m](https://github.com/user-attachments/assets/5f232b4d-a83d-4bca-a53c-14e5b71f8189)

Se genera un archivo csv de prueba con los datos previstos para enviar al endpoint:

![Captura de pantalla 2024-10-16 a la(s) 8 54 32 p m](https://github.com/user-attachments/assets/93f64c9b-fc89-4d9f-ae25-730052d6da00)

Se genera un error al intentar cargar el archivo al gestor documental:

![Captura de pantalla 2024-10-16 a la(s) 8 55 46 p m](https://github.com/user-attachments/assets/ad5283ad-ceb8-4e64-b07e-916e461dea86)

Después de tratar de encontrar el error en el mf del PAA decido iniciar la búsqueda en el código de gestor_documental_mid, se encuentra esta validación para el cargue de documentos:

![Captura de pantalla 2024-10-16 a la(s) 10 53 54 p m](https://github.com/user-attachments/assets/e80a48c7-f328-4321-8de7-304a66ddf732)

Se realiza la consulta y un archivo pdf contiene muchos más caracteres al convertirse en base64 que un csv

Pdf:

![Captura de pantalla 2024-10-16 a la(s) 8 53 23 p m](https://github.com/user-attachments/assets/518fb339-fea4-4658-9d40-c45ae1b9812c)

Csv:
![Captura de pantalla 2024-10-16 a la(s) 8 53 49 p m](https://github.com/user-attachments/assets/d02a16d1-e6a7-4cbe-8319-b7ac288dfe67)

Se procede a cambiar el contenido del archivo por uno con mas datos para cumplir con los 1000 caracteres que se requieren:

![Captura de pantalla 2024-10-16 a la(s) 9 03 30 p m](https://github.com/user-attachments/assets/22adcc73-350b-4f1a-a506-153586b6d016)

![Captura de pantalla 2024-10-16 a la(s) 9 04 37 p m](https://github.com/user-attachments/assets/9dd21848-0eaa-41a8-ba5e-11cf594905b0)

De esta forma se logra cargar el archivo csv al gestor documental.

**Comment by alexhrr** [comment]
Se realizan ajustes en el microcliente para usar el componente de cargue archivo en los botones de cargue masivo y de matriz, se hace la validación del tipo de documento (csv, xlsm o pdf) según sea el caso:

https://github.com/user-attachments/assets/17539d24-3bfd-4660-8b55-dbb2468c685b

Asi mismo se empiezan a revisar los cambios necesarios para ajustar la lambda de cargue masivo y su integración con el microcliente

**Comment by alexhrr** [comment]
Se continua con la integración para el cargue masivo, una vez ajustados los códigos para enviar el base64 desde el microcliente al la lambda, sin embargo se encuentra un error al momento de hacer la petición a la lambda:

![image](https://github.com/user-attachments/assets/66586c8f-9eac-4cbc-8a5f-7adb7a075f1a)

Se realizan consultas para encontrar una solución y se aplican algunas para tratar de solucionar el error:

![image](https://github.com/user-attachments/assets/0fef7eec-7c4d-4b0a-8684-97b7bbf20fac)

![image](https://github.com/user-attachments/assets/b11be808-5bf9-402f-b5a9-2aa5441b50a0)

![image](https://github.com/user-attachments/assets/0bf855c9-b108-4c4e-9c3a-50c39554d66b)

![image](https://github.com/user-attachments/assets/8f252054-235e-44d2-8a93-12c027f7184b)

![image](https://github.com/user-attachments/assets/c55acc7b-051d-4531-a35c-871f266a6ae0)

A pesar de los ajustes y cambios se continua presentando el mismo error

**Comment by edwargl7** [comment]
Se apoya en el ajuste para poder consumir la lambda desde el microcliente, se continuará el desarrollo e integración en el siguiente sprint.

**Comment by alexhrr** [comment]
Se encuentran algunos problemas con el separador de listas para la creación del csv y la decodificación ya que se tiene por defecto en el sistema ";"  y no ","

Los registros decodificados son los siguientes y debido al separado, no se pueden procesar para ser enviados al crud

![image](https://github.com/user-attachments/assets/75bf75e4-e669-4d0e-9b5e-d36b5ad9916f)

![image](https://github.com/user-attachments/assets/dbb03cad-cce5-4311-9271-b689791673f4)

De acuerdo a los ajustes del sistema en el equipo se puede cambiar a "," sin embargo en mi caso esto no es posible, este es un aspecto a tener en cuenta ya que es posible que los usuarios puedan tener el mismo inconveniente, por lo tanto se va a buscar una alternativa para poder trabajar con ambos tipos de separadores
 
![image](https://github.com/user-attachments/assets/60fcb6e3-90f4-4b28-b83c-fae632e5c3f6)

Para el siguiente sprint se van a realizar las pruebas teniendo en cuenta el separador de ";" temporalmente mientras se realiza el envio de datos al crud
