### ISSUE TITLE
Creación de historias de usuario de Programación de auditoria (Parte 2)

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#221]
Se requiere realizar la documentación de las historias de usuario para el módulo de registro del plan anual de auditoría en la fase de programación dado que se cuenta con una implementación con un buen avance cercano a lo solicitado en los requerimientos.

**Sub Tareas**

- [x] Documentación de las historias de usuario para el módulo de programación de auditoría.

**Criterios de aceptación**

- [x] Documento de historias de usuario parte 2.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la documentación del formato HU para el submódulo programación de auditoría.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/HU/HU-%20Historia%20de%20Usuario%20Subm%C3%B3dulo%20Plan%20Anual%20de%20Auditor%C3%ADa.xlsx?d=w0fd7a0b452464111a9d5a79358d3dd0d&csf=1&web=1&e=wikJDl

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la segunda parte de la creación y documentación del formato HU del submódulo programación de auditorías.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/[HU](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/HU?csf=1&web=1&e=mlcbhA)?csf=1&web=1&e=mlcbhA

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, al momento de culminar todas las historias de usuario debemos agendar para lograr aprobación del cliente.
