### ISSUE TITLE
Ajustes y validación renderizado

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#222]
Se requiere realizar los ajustes requeridos generados en el despliegue y las pruebas del correcto funcionamiento.

**Sub Tareas**

- [x] Ajustes si aplica.
- [x] Pruebas correcto funcionamiento.

**Criterios de aceptación**

- [x] Documentación avances y resultados de pruebas realizadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se implementa healthcheck en app.py
![image](https://github.com/user-attachments/assets/1d8a22a1-4084-43a9-b697-6fc68a624e1f)

se realiza prueba funcional
![image](https://github.com/user-attachments/assets/76e2296b-9d39-4271-8c23-b5036f412ec7)
![image](https://github.com/user-attachments/assets/8679ad7e-270b-4f9a-a17e-79f3bc31b3ba)

**Comment by edwargl7** [comment]
Desplegado y validado correctamente. Muchas gracias.
