### ISSUE TITLE
Revisión implementación formularios Sísifo plan y programa

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#223]
Se requiere realizar la validación de la implementación de los formularios revisados del mockup para la implementación estática del formulario en el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)

**Sub Tareas**

- [x] Implementación formulario base estático.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Implementación del Componente de Formularios

Se logró implementar el componente de formularios tomando como base el desarrollado en **formularios dinámicos**.
En el proceso se encontraron varios problemas relacionados con el manejo e inicialización de variables en TypeScript (TS).

El formulario se renderiza correctamente utilizando un **JSON de prueba** quemado en el código y muestra las secciones como acordeon. 

![image](https://github.com/user-attachments/assets/dd59405a-ddb3-46be-98d3-6c2a3c0e2097)

![image](https://github.com/user-attachments/assets/8e881945-4cc3-4220-8701-76a3c24cd4af)

**Comment by edwargl7** [comment]
1. Validar por favor que valide correctamente los campos obligatorios.
2. Validar que permita la organización similar a:
![image](https://github.com/user-attachments/assets/e93bf492-0ac4-4777-93a6-ca536f6e011a)

**Comment by CristianCGutierrezG** [comment]
### Reformulación de la Estructura del Formulario

- Se simplificó la lógica del formulario acorde a los requerimientos, transformándolo en una **clase** que puede recibir múltiples campos de manera más sencilla.
![image](https://github.com/user-attachments/assets/027eda92-d6c1-4e4b-9675-451632db4616)
  
### Validaciones

- Se comprobó la correcta validación de los **campos obligatorios**. El formulario ahora pasa los datos correctamente y detecta fallos si falta algún campo necesario.

### manejo de Grilla personalizada

- Se instaló **Bootstrap** para manejar las clases de organización de grillas. Se realizaron pruebas satisfactorias sobre la organización personalizada del formulario utilizando las clases de Bootstrap.
![image](https://github.com/user-attachments/assets/df691495-471c-45be-a9f6-e954aab4bad9)


### Comunicación entre Componentes

- Se modificó el componente **formulario-dinamico** (hijo) para que emita un evento y reciba una función desde un componente **padre**. Este padre puede definir las acciones a realizar con los datos del formulario.
![image](https://github.com/user-attachments/assets/beb44265-31e0-4a9a-9579-e0cb47cec749)

  
- Llamado del componente **formulario-dinamico** con la función implementada:
![image](https://github.com/user-attachments/assets/51f1e724-ea33-48b6-bb56-4d4361f9ed19)

  - Se creó una **función de prueba** que maneja los datos enviados por el formulario.
![image](https://github.com/user-attachments/assets/467863da-4d66-4373-99a9-1c9bffe4cc48)

  - Ahora el manejo del botón y la lógica asociada dependen del componente **padre**, donde se integra **formulario-dinamico**.
 
![image](https://github.com/user-attachments/assets/c7b6959e-871b-4068-a73c-0ae7af50faff)


### Notas:

- La organización de carpetas en el código **no está optimizada** para el uso modular de los componentes. El componente `formulario-dinamico` se está llamando directamente desde donde se necesita, lo cual podría mejorarse para un manejo más eficiente.
- No se ha agregado el valor **icono**, ya que aún no se define qué campos lo utilizarán o cómo funcionará exactamente.
- Algunos  mensajes en las validaciones aún no están bien implementados, como el número de caracteres máximo en un campo de text.

**Comment by edwargl7** [comment]
Muy buena implementación para la reutilización de este componente en las secciones de los formularios clásicos.
