### ISSUE TITLE
Implementación información plan microcliente plan anual auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#224]
Se requiere realizar los ajustes en la implementación del formulario de registro de información del plan.
![image](https://github.com/user-attachments/assets/9cd802f0-68c1-4996-ad91-3c307a276d6a)
![image](https://github.com/user-attachments/assets/0ad5edc1-c7d3-4a57-af8d-51886d9259cb)
![image](https://github.com/user-attachments/assets/e401dace-ae0b-4815-a907-cedd21291515)
![image](https://github.com/user-attachments/assets/35c54509-0d76-455b-9c8a-1aacc76b7b9f)
![image](https://github.com/user-attachments/assets/e034128f-d23f-4e78-a556-2187ded397ee)

**Sub Tareas**

- [x] Implementación registro de información.
- [x] Implementación manejo de valor por defecto.
- [x] Implementación de modales del flujo.

**Criterios de aceptación**

- [x] Documentación avances implementación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Modificaciones en las Validaciones de Formulario Dinámico

Se realizaron los ajustes necesarios para que las validaciones en la **creación de formularios dinámicos** funcionen correctamente, ya que antes no se estaban llamando adecuadamente al ser manejadas como **arreglos**.

![image](https://github.com/user-attachments/assets/f8d33a23-a22a-415a-8413-563e54e00e63)
![image](https://github.com/user-attachments/assets/b6b2c337-10b5-41bb-ac3b-1117e2c600a6)
![image](https://github.com/user-attachments/assets/651b3d1d-4403-4909-a07c-8d5c14dbe988)

### Investigación sobre Validaciones en campo fecha Personalizadas

 Se investigó la posibilidad de agregar validaciones para los campos de tipo **fecha**, con el objetivo de verificar que no se envíen fechas anteriores a la fecha actual. Es necesario implementar una **validación personalizada** para este caso.

### Revisión de la Organización de Carpetas

Se revisó la organización de las carpetas en el código para optimizar el uso de los distintos componentes. Se realizó una prueba con un componente específico para validar la nueva estructura, pero aún no se está seguro de si es la opción más óptima.

**Comment by edwargl7** [comment]
Pendiente validar si la importación del componente del formulario se optimiza al ser llamado en solo los componentes que lo requieren o se puede importar de forma general.

**Comment by CristianCGutierrezG** [comment]
### Implementación del Registro de planes

- Se realizó la implementación de una nueva página para el **registro de Planes**, incluyendo pruebas para verificar el correcto despliegue del formulario basado en una **plantilla**.
- Se probaron casos con y sin **valores por defecto** para asegurar la funcionalidad en ambos escenarios.
- Se llevó a cabo una primera implementación de los **modales** en el flujo del formulario, comenzando con el manejo de acciones clave que interactúan con los datos del registro.


https://github.com/user-attachments/assets/0e476ac4-6f54-41e4-84fa-a9c5f13e89dd

**Comment by CristianCGutierrezG** [comment]
Se identificó un conflicto en el uso de **Bootstrap**, específicamente con la clase `.container`, que es utilizada tanto por **Bootstrap** como por varios componentes personalizados. Este conflicto provoca que se apliquen **media queries** no deseadas que no estaban establecidas previamente en los componentes.

Se modificó la forma en la que se importan las clases de **Bootstrap**, limitando la importación únicamente a las clases necesarias para el manejo de la **grilla** en los formularios dinámicos desde el archivo `theme.scss`.

### Implementación de Información del Plan

![image](https://github.com/user-attachments/assets/991fc4de-0bf6-4893-8045-c44d03b5ba46)

**Comment by CristianCGutierrezG** [comment]
## Implementación de Almacenamiento y Carga de Valores desde variables de entorno

Se realizaron pruebas para almacenar los **IDs** requeridos como **variables de entorno** y utilizarlos en el formulario dinámico.
- Se implementó una nueva función dedicada a completar los valores del formulario a partir de:
  - Los datos obtenidos mediante el **servicio de parámetros**.
  ![image](https://github.com/user-attachments/assets/8702a6ac-a5ed-46ea-bb4a-1fd3266e8228)

  - Los **IDs** previamente guardados en las variables de entorno, momentaneamente los ID de tipo de evaluación.
  ![image](https://github.com/user-attachments/assets/e3e85a14-f1d8-49e2-a82b-4e375b69dc54)


### Resultados de las Pruebas

- Los datos de parámetros se obtienen correctamente y los valores se reflejan en la plantilla del formulario.
- Sin embargo, persiste un inconveniente en el cual el componente solo renderiza el formulario con los nuevos campos si se entra y sale de la pagina. Al recargar la pagina vuelve los valores a la plantilla base.

https://github.com/user-attachments/assets/8adf13f8-d77b-40fd-9e86-2986df31d07f

**Comment by edwargl7** [comment]
Se crea un PR para la revisión del código, se encuentra correctamente. Por favor solicitar PR. Muy buen trabajo.
