### ISSUE TITLE
Implementación registro de auditoría microcliente plan anual auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#225]
Se requiere realizar el diseño de la vista para añadir y editar auditorias en el paso de registro de auditorias microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).
![image](https://github.com/user-attachments/assets/9e3caf89-8482-4f0f-89d0-2742be53f74c)
![image](https://github.com/user-attachments/assets/66389673-a74f-4d77-8b37-c57f9e49b55e)

**Sub Tareas**

- [x] Diseño modal para registro de auditoria.
- [x] Integración con parámetros CRUD de selectores.

**Criterios de aceptación**

- [x] Documentación avances implementación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Implementación del Componente Modal

Se desarrolló un **componente modal** que crea formularios de manera estándar.
Para poder implementar formularios dinámicos en el modal, es necesario definir cómo obtener la información de **parámetros**. Esto se plantea de manera similar a lo que se realizó en una prueba anterior del microcliente de formularios dinámicos, donde se requería obtener los datos de parámetros y pasarlos a la plantilla.

![image](https://github.com/user-attachments/assets/87e9fd08-d675-44bd-8edb-c38f3e89181f)

### Implementación del `parametrosService`

Se implementa **`parametrosService`** para manejar la obtención de datos de parámetros.

Se identificó un error de tipos en el **`requestManager`**.
Al intentar obtener los datos mediante un **GET**, se encontró el siguiente error de tipos:
  - **Property 'Data' does not exist on type 'HttpEvent<any>'**
  
Se realizó un ajuste en el **`requestManager`** para solucionar este problema.

![image](https://github.com/user-attachments/assets/7a8e7a57-9455-48ca-937e-877a7b6bab51)

Tambien se presentaron errores adicionales al mostrar los datos de parámetros, lo que llevó a la creación de una **interfaz** que estableciera los tipos de datos esperados.

![image](https://github.com/user-attachments/assets/8064127b-f5e3-4d19-849c-e0ff731db362)

**Comment by CristianCGutierrezG** [comment]
### Pruebas y Ajustes en el `requestManager`

Se realizaron pruebas utilizando el **`requestManager`** obtenido del repositorio de **SGA** [sga_cliente_evaluacion_docente_mf](https://github.com/udistrital/sga_cliente_evaluacion_docente_mf/tree/develop).
Aunque el problema con **`HttpEvent`** fue resuelto, persisten algunos inconvenientes con los **tipos de datos** y la **interface** para manejar los datos de respuesta.
 Por el momento, se mantiene la versión actual del `requestManager`.

### Ajuste de Estilos
Se realizaron ajustes en los estilos de los componentes de Registrar Auditorías y el modal de auditoria

![image](https://github.com/user-attachments/assets/1bc6bfd1-5c5b-40ac-b5a4-dc3dca4e1f89)

![image](https://github.com/user-attachments/assets/e9f0ba10-388f-407e-8a8b-d22a56dc5162)

**Comment by edwargl7** [comment]
Muy buena implementación. Se puede realizar el PR.

**Observaciones**
- Ajustar a kebab case para nombrar los estilos definidos para las clases, dado que es la convención recomendada.
![image](https://github.com/user-attachments/assets/e0372f47-5910-4d95-a667-b26b4d7435fb)
