### ISSUE TITLE
Ajustes plantillas mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#226]
Se requiere realizar la organización del controlador de plantillas mid revisado en la Issue #219.

**Sub Tareas**

- [x] Reorganización controlador de renderizado.
- [x] Remover del router el controlador base por defecto que existe.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se reorganiza controller y service para que lo implementado sea independiente a lo ya desarrollado
![Image](https://github.com/user-attachments/assets/f3a41e4c-c899-4b2a-8226-6f60847d6232)
![Image](https://github.com/user-attachments/assets/49ec8c50-b7ce-4205-916a-8ed5da4f0465)

**Comment by jucastro94** [comment]
se modifica el commentsRouter y router
![Image](https://github.com/user-attachments/assets/c104ebf6-9a89-4ea5-9103-974b8b6cfd21)
![Image](https://github.com/user-attachments/assets/cbc0af1b-5fa7-48cd-9806-c3923956bf29)

**Comment by jucastro94** [comment]
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/87834757-9df3-452d-a64b-47364605d2ba)
![Image](https://github.com/user-attachments/assets/bd61206f-13e1-4278-9331-e9e6e2e0002d)

**Comment by jucastro94** [comment]
se comparten los curl para comprobar plantillas_mid, plantillas_serverless y renderizado_plantillas

[curl.txt](https://github.com/user-attachments/files/17479884/curl.txt)

**Comment by edwargl7** [comment]
Se podría cambiar Plantilla_id por PlantillaId
![Image](https://github.com/user-attachments/assets/c2304b07-8a87-4da3-aa7f-a760e1848f0e)

Se resuelve el PR. Muy buen trabajo.
