### ISSUE TITLE
Implementación aprobación secretario microcliente plan anual auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#227]
Se requiere realizar la maquetación del submódulo de aprobación por parte del secretario. Manejando en la vista la visualización de los documentos y no como modal para permitir mediante la url del microcliente la redirección al plan específico mediante el correo en un integración posterior.
![image](https://github.com/user-attachments/assets/7de38a2b-6811-4692-90f3-cab73685e75a)
![image](https://github.com/user-attachments/assets/aebf6050-7249-40b5-ba64-42fed3603de1)
![image](https://github.com/user-attachments/assets/a9e5c76c-334e-4f0d-9b85-e9b3acdb780d)
![image](https://github.com/user-attachments/assets/dce253fe-8168-49e6-9dfc-bc1ada61f56e)
![image](https://github.com/user-attachments/assets/723d6e32-3030-41ed-a9ce-c6d3b05a848f)
![image](https://github.com/user-attachments/assets/fbf2f948-c0c6-4b14-99bb-0210dacb4182)
![image](https://github.com/user-attachments/assets/6e08ca25-a357-4150-851a-c469a12add30)

**Sub Tareas**

- [ ] Implementación módulo de aprobación del secretario, se puede reusar y guiar del módulo de aprobación del jefe.
- [x] Implementación modal de carga de documento (acta).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultado de las pruebas funcionales.

**Material de apoyo**
- Repositorio microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf)
- Repositorio microcliente [auditoria_plan_mejoramiento_root_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_root_mf)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia la revisión del repositorio, clonación de ROOT, CORE y REPO del Microcliente para iniciar pruebas y familiarización del Proyecto.

**Comment by OscarLozano01** [comment]
![screencapture-localhost-4200-plan-auditoria-plan-anual-auditoria-2024-10-25-08_25_44](https://github.com/user-attachments/assets/84ce6b9f-fe8a-4619-bc57-50323a8883ae)

**Comment by edwargl7** [comment]
Por favor documentar avances @OscarLozano01 .

**Comment by OscarLozano01** [comment]
![screencapture-localhost-4200-plan-auditoria-plan-anual-auditoria-2024-10-28-08_30_38](https://github.com/user-attachments/assets/b2c2d15d-aa9c-4cbd-966f-4e6572beb890)

**Comment by OscarLozano01** [comment]
El día de hoy se terminan la parte de Consumir las alertas y adaptarlas al flujo solicitado en la Issue.

**Comment by OscarLozano01** [comment]
![screencapture-localhost-4200-plan-auditoria-plan-anual-auditoria-2024-10-29-06_54_42](https://github.com/user-attachments/assets/a608a260-0611-4de6-b3e4-333ddee3e1c0)

**Comment by OscarLozano01** [comment]
Flujo componente del componente `**plan-auditoria/plan-anual-auditoria**`


https://github.com/user-attachments/assets/b82201e7-77b6-47e4-ae9e-c4943ba2031b

**Comment by OscarLozano01** [comment]
Se realiza un pequeño ajuste en Revision-Plan-Auditoria para poder Exportar los componentes donde se encuentran los Componentes:

```
PdfVisualizadorComponent
ModalGeneral
ModalMotivosRechazoComponent
```
Ajuste realizado:

```
  exports: [
  PdfVisualizadorComponent,
  ModalGeneral,
  ModalMotivosRechazoComponent
  ]
```

**Comment by edwargl7** [comment]
Cumple parte de la implementación. Ajustar por favor el título de observaciones y el placeholder cambiar la primera M a mayúscula. 
Para el modal de carga se puede utilizar:
https://github.com/udistrital/plan_anual_auditoria_mf/tree/develop/src/app/modules/cargar-archivo

**Comment by OscarLozano01** [comment]
Se consume la logica del componente CargarArchivoComponent, se inicia la incorporación en el modal

https://github.com/user-attachments/assets/b9a42b53-e996-48b3-874f-a94701a5915d

**Comment by edwargl7** [comment]
Se aborda parte del sprint 27 en esta Issue y para documentar el complemento de la Issue del 27 se crea parte dos de esta tarea en la Issue 245.
