### ISSUE TITLE
Ajustes microservicio carga masiva

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#228]
Se requiere realizar ajustes de preparación para el despliegue del microservicio. Se debe ajustar el nombre del endpoint y documentación del README.

**Sub Tareas**

- [x] Creación del nombre del endpoint y ajuste en el template.yml.
- [x] Manejo de separador por variable enviada desde el POST.
- [x] Documentación del README.
- [x] Implementación envío de datos al CRUD.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza el ajuste para que se pueda usar temporalmente el separador ";" y se resuelven errores que se tenían en el formato csv para cargar los datos al endpoint.

Una vez solucionados los errores se logra el cargue masivo y el envío al gestor documental, 

![image](https://github.com/user-attachments/assets/ee560571-4cfe-45d1-8a79-500b535fa2a1)

Se enviaron algunos registros con algún error para verificar que el cargue continúe a pesar de los fallos en el registro:

![image](https://github.com/user-attachments/assets/28ea55df-79fc-42f0-8a6a-c9b9f672413a)

![image](https://github.com/user-attachments/assets/04510135-4662-40b6-9845-acb6c71c118f)

![image](https://github.com/user-attachments/assets/90165553-d89a-4718-b12f-dfa33b29dbad)

Se muestran los datos cargados a la base de datos:

![image](https://github.com/user-attachments/assets/25dfc839-8c0d-4315-ac2b-4824949a9742)

Tambien se obtienen los datos del tiempo de ejecución que para este caso fue aproximadamente de 14 segundos, la memoria se puede reducir nuevamente en otra prueba para verificar la cantidad usada:

![image](https://github.com/user-attachments/assets/f87a45e0-3218-4d11-b538-b052978cbb8b)

**Comment by edwargl7** [comment]
Pruebas a revisar:
- Validación manejo de separadores (; ,)
- Validación manejo celdas vacías.

**Comment by alexhrr** [comment]
### Validación separadores ( ; , )

Se agrega en el codigo una condición para que continúe con el otro separador en caso de no ser ";" tambien muestra un mensaje de error si el separador no es ";" o ","

![image](https://github.com/user-attachments/assets/3a49b7a7-acbd-4ace-b827-39c1cd6e2fc1)

Se hace la prueba con datos separados por ","

![image](https://github.com/user-attachments/assets/214b7b7e-d9fb-4ec6-bca8-497c53f1a504)

![image](https://github.com/user-attachments/assets/ac30cf88-8a0e-4238-a838-faf1732e244e)

Se registran los datos correctamente en la base de datos y se valida el funcionamiento de los separadores con "," y con ";"

![image](https://github.com/user-attachments/assets/389216a1-488e-497f-b59c-1c14bd388635)

No se ve afectado el tiempo de ejecución de la lambda.

### Validación para archivos xlsx

 Se debe hacer uso de la libreria excelize de go para leer archivos excel.
 
 Se hace una verificación inicial del tipo de archivo directamente en el codigo o se puede enviar previamente la extensión

**Comment by alexhrr** [comment]
Se asiste a una reunion junto al líder para realizar una revision de los ajustes realizados y las validaciones mencionadas anteriormente, en la reunion se determinan los siguientes aspectos importantes para continuar con la implementación:

- Uso de un solo archivo con la extension xlsx para el cargue masivo, se toma en cuenta que este tipo de archivo permite hacer unas validaciones para simplificar el cargue al usuario.

- Se va a trabajar en una estructura Json que contenga los parámetros necesarios para el cargue de los registros al endpoint, este va a ser enviado a la lambda y queda por definir el encargado de el envío (mid o mf). Se busca que el cargue masivo sea transversal.

- Para el manejo de las filas vacías en los archivos se toma la decisión de ignorarlas y continuar con los otros registros, las celdas vacías van a tener un manejo diferente donde se va a evaluar si la celda contiene información requerida, de acuerdo a esto se podrá continuar con el registro o en caso contrario no se hace el registro y se informa del error pero se continua con los demás.

- Se va a implementar python para el desarrollo de la lambda encargada del cargue masivo, por lo tanto se va a hacer la adaptación del código desarrollado previamente al nuevo lenguaje manteniendo la estructura general por lo que no se parte de cero en el desarrollo.

- Se planea iniciar con la adaptación de pequeñas partes del código y creación de la nueva lambda.

**Comment by alexhrr** [comment]
### Cargue masivo xlsx python

Se realiza la decodificación de la información en base64 y se usa pandas para crear la tabla que contiene los datos:

![Captura de pantalla 2024-10-23 a la(s) 8 34 56 p m](https://github.com/user-attachments/assets/089e8758-d62c-4b0e-946c-aea11dd80761)

![Captura de pantalla 2024-10-23 a la(s) 8 22 57 p m](https://github.com/user-attachments/assets/325cc700-593d-494f-8c35-14be4af0fd8c)

Se crean los registros en la base de datos usando el endpoint y el payload con los datos del excel:

![Captura de pantalla 2024-10-23 a la(s) 8 31 41 p m](https://github.com/user-attachments/assets/4d286e9b-b299-4fce-a8a2-533f9fa0e807)

**Comment by alexhrr** [comment]
### Pruebas cargue masivo

Se realizan ajustes en el código para que el archivo continue con los registros cuando se encuentre un error en los datos ingresados por el usuario
En este caso el registro 2 contiene una celda vacía y el registro 7 contiene un rol que no está creado en la base de datos:

![Captura de pantalla 2024-10-24 a la(s) 5 30 10 p m](https://github.com/user-attachments/assets/5be61dbf-9a10-4d40-a765-77b73cf7d627)

Se puede observar que se identifica que la fila 2 contiene una celda vacía y que se continua con el registro de los otros datos, asi mismo se identifica el error con la fila 7

![Captura de pantalla 2024-10-24 a la(s) 5 30 19 p m](https://github.com/user-attachments/assets/791db790-c35a-4dda-8840-61b91a1900f5)

Se encuentra que al haber una fila vacía el df toma los números como decimales, lo que genera error al enviarlos al endpoint, asi que se debe hace la conversion a entero :

![Captura de pantalla 2024-10-24 a la(s) 5 33 04 p m](https://github.com/user-attachments/assets/06bf87db-aa54-4f55-90ad-e53187f9ac25)

Después de realizar el ajuste se envían correctamente los datos al endpoint:

![Captura de pantalla 2024-10-24 a la(s) 5 38 42 p m](https://github.com/user-attachments/assets/e38ee974-e2d2-4e0c-b9c9-74790181db3c)

Se realiza tambien un ajuste en el código para eliminar las filas que estan completamente vacías:

![Captura de pantalla 2024-10-24 a la(s) 5 49 20 p m](https://github.com/user-attachments/assets/0a578ef6-bf5b-4293-afe7-b75801fc3aaf)

**Comment by edwargl7** [comment]
Se crea base de lambda para implementación con python en la rama https://github.com/udistrital/cargue_archivo_mid_serverless/tree/feature/cargue-python

Pruebas locales:
![image](https://github.com/user-attachments/assets/ba26579f-c8ce-4317-b9b0-f80f87f11523)

**Comment by edwargl7** [comment]
```
{
  "service": "Usuario",
  "endpoint": "/periodos",
  "structure": {
    "FechaFin": {
      "posicion": 0,
      "required": true
    },
    "FechaInicio": {
      "posicion": 1
    },
    "Finalizado": {
      "posicion": 2,
      "parse": "booleano",
      "required": true
    },
    "RolId.Id": {
      "posicion": 3,
      "parse": "int"
    },
    "UsuarioId.Id": {
      "posicion": 4,
      "parse": "int"
    }
}
}

"UsuarioId.Id": 1

"url": "http/.../periodos"
{
   "FechaFin":"09-12-2024",
   "FechaInicio":"07-12-2024",
   "Finalizado":true,
   "RolId":{
      "Id":1
   },
   "UsuarioId":{
      "Id":78
   }
}
```

**Comment by alexhrr** [comment]
### Ajustes lambda python

Se realiza la integracion del cargue masivo pasando de go a la lambda de python, se ejecuta con el base64 directamente en el código para verificar su funcionamiento

![Captura de pantalla 2024-10-25 a la(s) 6 45 33 p m](https://github.com/user-attachments/assets/f943039f-b95c-42c1-b08a-bdd312b1015e)

![Captura de pantalla 2024-10-25 a la(s) 6 45 48 p m](https://github.com/user-attachments/assets/e148d77f-1500-4df7-b453-351b03af754d)

Posteriormente se realiza la integracion con el microcliente, donde se selecciona el archivo y se carga al gestor documental, asi mismo se envia a la lambda el archivo en base64.
Se logra ejecutar y registrar la información suministrada en el archivo:

![Captura de pantalla 2024-10-25 a la(s) 7 52 34 p m](https://github.com/user-attachments/assets/793bd493-9df8-4e62-bb73-0862430735a0)

![Captura de pantalla 2024-10-25 a la(s) 7 52 50 p m](https://github.com/user-attachments/assets/cd334c2a-0073-42e2-9d80-230827bad551)


![Captura de pantalla 2024-10-25 a la(s) 7 52 18 p m](https://github.com/user-attachments/assets/1e78cf2a-1350-4e62-809a-a3c3f53a67ac)

![Captura de pantalla 2024-10-25 a la(s) 7 53 50 p m](https://github.com/user-attachments/assets/b8b59c64-ec96-424a-a246-e62b2ac2e529)

**Comment by edwargl7** [comment]
Muy buena documentación. Por favor subir código @alexhrr.

**Comment by edwargl7** [comment]
Muy buena implementación y se observa el icono adicional de cargue masivo, apropiado para la función del botón. En la siguiente iteración se recomienda separar la lógica en funciones.

**Observaciones microcliente**
- Cambiar nombre de variable por uno más apropiado para la funcionalidad del servicio.
![image](https://github.com/user-attachments/assets/db6de1fe-c219-4524-9271-644ccf29d5fb)

**Pruebas adicionales lambda**
- Capturar excepción en caso de error por dato incorrecto según el tipo esperado, por ejemplo, un texto en el campo de ID.

Nota: Se elimina rama develop y se crea nuevamente basada en la rama de desarrollo con python, se realiza limpieza de ramas del repositorio de cargue masivo mid serverless
