### ISSUE TITLE
Implementación microservicio CRUD plan auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#229]
Se requiere realizar la implementación del microservicio CRUD del modelo presentado y aprobado por DBA en la Issue #216.

**Sub Tareas**

- [x] Implementación base del proyecto.
- [x] Implementación endpoint HealthCheck.
- [x] Implementación pruebas integración HealthCheck.
- [x] Implementación CRUD de cada colección del modelo.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza instalacion de mongo DB y Studio T3

**Comment by jucastro94** [comment]
se realiza generacion de proyecto y estructuracion del mismo
![Image](https://github.com/user-attachments/assets/799cd2f3-2f51-4e18-be09-eb415235259a)

se genera modelo y esquema de plan-auditoria

![Image](https://github.com/user-attachments/assets/6fc97c2c-64d2-4f39-8185-f33aaf5b621c)
![Image](https://github.com/user-attachments/assets/5a527078-55eb-40a5-b8d8-38835e119ea2)

**Comment by jucastro94** [comment]
se implementa healthcheck
![Image](https://github.com/user-attachments/assets/a7e9131b-6f08-4290-bd63-ad326a047db1)

**Comment by jucastro94** [comment]
se creabase de datos en Docker
![Image](https://github.com/user-attachments/assets/5c106dcd-0106-4979-8337-f9871a8b0e46)
![Image](https://github.com/user-attachments/assets/4506dc44-eed4-406f-b242-871bd1cd9924)

**Comment by jucastro94** [comment]
se hace prueba funcional de health check
![Image](https://github.com/user-attachments/assets/b8b0b600-1425-4829-80f1-d86637e59d7a)

**Comment by jucastro94** [comment]
se completan los DTO y schemas  de cada una de las colecciones
![Image](https://github.com/user-attachments/assets/987c451a-c8ed-479d-8f13-88f9eadbcff5)

se implementan query params 
![Image](https://github.com/user-attachments/assets/91ed405a-1faa-477c-b662-9f4a176738b7)

se crea controller y servicio crud funcional de plan anual
![Image](https://github.com/user-attachments/assets/528dbfc4-a370-4ebc-bdfb-3874af0076dc)
![Image](https://github.com/user-attachments/assets/b3050e49-fdc0-44fb-9943-fa9883022bf2)

**Comment by jucastro94** [comment]
se realiza prueba funcional swagger

![Image](https://github.com/user-attachments/assets/ec649bb1-edeb-4b69-a4c1-599985d8ff97)

**Comment by jucastro94** [comment]
se realiza prueba funcional de crud plan_auditoria

**POST**
![Image](https://github.com/user-attachments/assets/2aad7aa9-a4e0-4a4b-bb3c-4acad4228f2f)
![Image](https://github.com/user-attachments/assets/977a24b8-93df-43e1-83df-5151a01ef353)

**GETALL**
![Image](https://github.com/user-attachments/assets/3e770ea4-0c80-4c65-8ac1-63255757769d)

**GET**
![Image](https://github.com/user-attachments/assets/dc2b6e4e-8f93-4a0e-bb08-7601fb4900db)

**PUT**
![Image](https://github.com/user-attachments/assets/5dfe426a-d4e4-4148-a9da-63abca3992b0)
![Image](https://github.com/user-attachments/assets/ed15ff75-183d-45d2-812f-335e8683d439)


**DELETE**
![Image](https://github.com/user-attachments/assets/1dc9b9a6-5e88-4c7d-a779-e0e8e07e5435)
![Image](https://github.com/user-attachments/assets/d3b86654-d1b6-447b-840b-f777d3da5362)


![Image](https://github.com/user-attachments/assets/13bb6e6d-30fd-45eb-a4f7-db0c90acc9bf)

**Comment by jucastro94** [comment]
se desarrolla CRUD controllador y service para colleccion auditoria

![Image](https://github.com/user-attachments/assets/d512ca70-7470-4ce5-8ba6-8fd7064d3e5b)
![Image](https://github.com/user-attachments/assets/430d7f68-a851-4e5a-92eb-af4ef31bfa2d)

**Comment by jucastro94** [comment]
se hacen pruebas funcionales crud auditoria

**POST**
![Image](https://github.com/user-attachments/assets/6d886e5c-ed07-442f-9b73-ba168ad67b8f)

**GETALL**
![Image](https://github.com/user-attachments/assets/f22be6f1-d207-4b79-a925-27854b2f6b5d)

**GET**
![Image](https://github.com/user-attachments/assets/c8cd833e-fb0a-4cc2-b26c-b2ad0e9164f7)

**PUT**
![Image](https://github.com/user-attachments/assets/9347dfd6-80f7-4cca-93e7-309fe8a66df1)

**DELETE**
![Image](https://github.com/user-attachments/assets/008c1322-40e2-4823-8da7-43e922ca06ff)
![Image](https://github.com/user-attachments/assets/8bbf352e-d1d2-43fa-a2af-62d9918de589)

**Comment by jucastro94** [comment]
se realiza desarrollo de CURD controller y service para la collecion actividad

![Image](https://github.com/user-attachments/assets/8bb221d2-e0b0-4358-aaa5-d91e5e8849bd)
![Image](https://github.com/user-attachments/assets/f7d285be-0661-45f5-afd1-5226a28aa06b)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

**POST**
![Image](https://github.com/user-attachments/assets/a1a2b854-39d5-4d83-94d2-e0b7f853060a)

**GETALL**
![Image](https://github.com/user-attachments/assets/685d5b94-32c7-44aa-b0be-97079c68a513)

**GET**
![Image](https://github.com/user-attachments/assets/b1fd3bdd-10d8-44b2-802e-9292c39d1243)

**PUT**
![Image](https://github.com/user-attachments/assets/544a9a28-b1ae-4821-bc68-e3f34c980a29)

**DELETE**
![Image](https://github.com/user-attachments/assets/b777e174-e9f4-4171-a007-65d09377774b)
![Image](https://github.com/user-attachments/assets/47ba3786-969b-46a6-8723-8b235b2a33c9)

**Comment by jucastro94** [comment]
se realiza pruebas funcionales de query params plan auditoria 

fields
![Image](https://github.com/user-attachments/assets/bcb69bdf-2e5a-4067-8119-afd391b1b7b2)
![Image](https://github.com/user-attachments/assets/791c9b77-cac6-4a93-88f0-9c165f217b63)

query
![Image](https://github.com/user-attachments/assets/8eebd7bd-bf2a-4a35-848a-73cad40a3576)
![Image](https://github.com/user-attachments/assets/a457e788-9165-4abc-85b0-29ae94190417)

order y sortby
![Image](https://github.com/user-attachments/assets/e37a159c-fe2d-4ec6-b17f-1f8bed7f8324)
![Image](https://github.com/user-attachments/assets/3ce8063f-4a47-4ab5-a63f-88fb61cf9d68)

limit y offset
![Image](https://github.com/user-attachments/assets/a6557ff9-58fc-40bf-bf32-27d47374bc2d)
![Image](https://github.com/user-attachments/assets/2b502193-b79a-49ae-be94-3b2ad9263cd5)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales de query params auditoria

FIELDS
![Image](https://github.com/user-attachments/assets/f25e0368-68eb-4bc3-a9cd-2db6ba8fb008)
![Image](https://github.com/user-attachments/assets/60a2a3e6-5ab2-4a67-85ca-6cad9d6bfdcd)

QUERY
![Image](https://github.com/user-attachments/assets/81db98ab-27ad-4212-b0c2-bb3b3796038b)
![Image](https://github.com/user-attachments/assets/4fab1277-75de-4752-820e-b21694f55dd7)

SORTBY Y ORDER
![Image](https://github.com/user-attachments/assets/5fd72f9a-7959-45b8-8e03-8b9febd8db15)
![Image](https://github.com/user-attachments/assets/913e8c97-86ca-450d-bd51-f64d8cdf7c2b)

LIMIT Y OFFSET
![Image](https://github.com/user-attachments/assets/1dc46eec-d415-4769-8144-051f8e008085)
![Image](https://github.com/user-attachments/assets/7e31f246-3a80-4bbb-8be9-b7b5740c7b11)

**Comment by jucastro94** [comment]
se realiza prueba funcional a query params actividad

FIELDS
![Image](https://github.com/user-attachments/assets/71e169d0-3189-487a-b595-befc8ca8dce8)
![Image](https://github.com/user-attachments/assets/0ba1def0-f790-4c38-9a4b-a266dc69663f)

QUERY
![Image](https://github.com/user-attachments/assets/46675442-759b-4178-8de1-ad273557569d)
![Image](https://github.com/user-attachments/assets/099b6adf-70cc-45b5-a401-1448f536ab24)


ORDER Y SORTBY
![Image](https://github.com/user-attachments/assets/ca559b12-e7c1-47df-82d5-d6e5b8536c29)
![Image](https://github.com/user-attachments/assets/aa0d49a4-d00d-4f0f-a1aa-5a5b0dbb1888)

LIMIT Y OFFSET
![Image](https://github.com/user-attachments/assets/6b2b9427-a7da-4ff1-968a-891ed95fdd33)
![Image](https://github.com/user-attachments/assets/c3124175-29fa-42a3-8816-941a1c279494)

**Comment by jucastro94** [comment]
se implementan pruebas de integracion con base en [plantillas_formularios_dinamicos_crud]( https://github.com/udistrital/plantillas_formularios_dinamicos_crud/tree/develop)
![Image](https://github.com/user-attachments/assets/b0b3892d-0636-4fdb-8476-54a84f8a165c)


 se detectan errores en los archivos .espect al momento de correr las prubas 
![Image](https://github.com/user-attachments/assets/8bf58b6a-474d-46a6-a142-a6f714624327)
![Image](https://github.com/user-attachments/assets/e37b99cb-3afa-4a45-898c-c56ab3f8a000)

![Image](https://github.com/user-attachments/assets/10378c67-6b02-45a8-b8fb-c41af4b00c79)
![Image](https://github.com/user-attachments/assets/2e3f1ce8-5e2e-4977-8398-7428306ce05a)
![Image](https://github.com/user-attachments/assets/2fba173a-a71f-4b1b-a6a5-6c859602fc00)
![Image](https://github.com/user-attachments/assets/b86f61c0-4e4b-46bb-b513-3a5f5a0d781b)
![Image](https://github.com/user-attachments/assets/6312ab16-f323-46d1-9d5c-6d0a83098f95)

entre otros

**Comment by edwargl7** [comment]
Muy buena implementación, se crea PR para validar más fácil el desarrollo realizado.

**Observaciones**
- El mensaje retornado no es acorde a la búsqueda realizada. Ajustar por favor, la búsqueda realizada es a la auditoría, la cual es correcta pero en caso de no encontrarse el mensaje indica activadad.
![image](https://github.com/user-attachments/assets/f1a21c0c-a975-4112-9a93-c7fa24b86b9b)
- Revisar función dado que estaría referenciando un campo que no existe.
![image](https://github.com/user-attachments/assets/bced02a7-057d-4a00-9799-e97e00667045)
- Los campos relacionados a los formularios deben ser opcionales para permitir cambios (agregar o remover campos a futuro).
![image](https://github.com/user-attachments/assets/f69a8e7e-45eb-4443-bf19-1be4f79a865f)
- El microcliente proporcionará los ids referentes a los meses, por lo tanto, cronograma_actividad debe ser de tipo array o lista de numbers. Se puede incluso cambiar el campo por cronograma_actividad_ids
![image](https://github.com/user-attachments/assets/10bfd12e-5003-4ba7-a906-a44db7347b07)

**Mejoras**
- Dado que existen auditorías especiales, que son las que son creadas sin la necesidad de pertenecer a un plan, dado que son auditorías que surgen después de la etapa de planeación.
![image](https://github.com/user-attachments/assets/63a35a22-8390-4729-8a69-9e6f22e97bb9)
- Mantener por favor en los casos que aplique un estilo de escritura (CamelCase o Snake case).
![image](https://github.com/user-attachments/assets/90c9e167-2346-4267-8ac2-ba94aeeb1b3e)
![image](https://github.com/user-attachments/assets/3bf36512-e197-4b66-94cc-07be50e9c246)
- Agregar documentación a cada función que complementa la documentación del swagger y detallar mejor los mensajes de respuesta en los controladores. Referencia guía https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/contratista/contratista.controller.ts
https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/contratista/contratista.service.ts

**Comment by edwargl7** [comment]
Se finaliza la Issue, muy buen trabajo. Tener presente el comentario anterior.
