### ISSUE TITLE
Creación Microfrontend transversal Root-mf - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#23]
Se requiere realizar la creación del microfrontend para Argo v2, apoyado de la tarea inicial de creación del root para Sísifo v2, se requiere el apoyo para la creación inicial del root para Argo.

**Sub Tareas**

- [x] Desarrollar microfrontend Root
- [x] Uso de estilos respectivos [assets](https://github.com/udistrital/assets)
- [x] Consumo de core-mf

**Criterios de aceptación**

- [x] Cliente root creado
- [x] Consumo cliente core-mf
- [x] Código en el repositorio

**Requerimientos**

- [x] Finalizar [Ajuste Microfrontend Sísifo Root-mf - Parte 2](https://github.com/udistrital/sisifo_documentacion/issues/21)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
# Avance Microfrontend Argo Root-mf

1. Se crea el Root con single-spa de acuerdo a las indicaciones.
2. Se empiezan a realizar las configuraciones correspondientes para la futura conexión del core.

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/135e76e1-d4b9-468a-a9e6-bc93fb769771)

**Comment by edwargl7** [comment]
Enlace al repositorio para el root de ARGO https://github.com/udistrital/argo_root_mf.

**Comment by alexhrr** [comment]
# Conexión core_mf_cliente y Root_argo

Se realiza la conexión del root creado anteriormente y el core_mf_cliente para el sistema Argo 
Actualmente se tienen las siguientes vistas del core con el logotipo de Argo

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/f8687dca-e885-4789-a0d0-9c447de83942)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/ad62b5dd-532c-43ec-88b7-8170ea76e1a0)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/0e061e90-3011-4082-8f5e-26aaa9ea0b4b)

Se deja montado el servicio del core-mf

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/dfa98aff-e7f1-4e87-8b7c-70eebf89212a)

Se realizó el cambio del favicon

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/b7352e6f-cff4-4d6a-9f9d-cde1c71fd73e)

Finalmente la estructura actual del codigo

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/ea618824-08e2-4682-961a-ae60d285ddc8)

Queda pendiente el cargue al repositorio y la configuración de la paleta de colores.

**Comment by alexhrr** [comment]
Se agrega la linea de código para consumir la paleta de colores 

```bash
<link rel="stylesheet" href="https://pruebasassets.portaloas.udistrital.edu.co/gaia-style.css">
```

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/3a40539d-c3f9-436f-828f-4c386a658515)

Adicionalmente se cargan los archivos al siguiente repositorio:

https://github.com/udistrital/argo_root_mf

**Comment by edwargl7** [comment]
Excelente trabajo, ajustes pendientes de la tarea relacionada resueltos correctamente y finalizada completamente esta Issues.
