### ISSUE TITLE
Creación de historias de usuario de fase de planeación desde el rol de auditor

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#230]
Se requiere realizar la documentación de las historias de usuario para la fase planeación desde el rol de auditor.

**Sub Tareas**

- [x] Documentación de las historias de usuario para la fase planeación.

**Criterios de aceptación**

- [x] Documentación de las historias de usuario para el módulo de registro de contratos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la creación del documento HU para la fase de planeación.

Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/[HU](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/HU?csf=1&web=1&e=N4v3Na)?csf=1&web=1&e=N4v3Na


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza documentación del formato HU para la fase de planeación desde el rol del auditor.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/HU/HU-%20Historia%20de%20Usuario%20Subm%C3%B3dulo%20Planeaci%C3%B3n%20Auditor%C3%ADas.xlsx?d=we34303c134d24b6e8d1ffe9f2e1455a5&csf=1&web=1&e=5vYwd6


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp!
