### ISSUE TITLE
Diseño mockup para gestión de observaciones en la aprobación de jefe o secretario

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#231]
Se requiere realizar el diseño del mockup para el manejo de histórico de observaciones.

**Sub Tareas**

- [x] Diseño del mockup para la vista de observaciones desde la vista del auditor.
- [x] Diseño de observaciones desde la vista del Jefe.
- [x] Diseño de observaciones desde la vista del secretario.

**Criterios de aceptación**

- [x] Diseño de mockup con las diferentes vistas requeridas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en diseño de mockup, implementando la visualización de observaciones de rechazo por parte de los roles jefe de OCI y secretario técnico. 

La notificación del correo la recibirá el rol auditor experto responsable de la creación del registro, en la notificación se genera una primera vista del motivo de rechazo.

![Image](https://github.com/user-attachments/assets/84c26c3b-c944-4583-ac3c-e725e760fcf2)

Al ingresar al enlace compartido en la notificación, direcciona al auditor experto al registro del plan rechazado y en las acciones se podrán ver nuevamente los comentarios u observaciones del motivo del rechazo.

![Image](https://github.com/user-attachments/assets/0686ab59-92ce-4f89-9134-0dde718857ee)

![Image](https://github.com/user-attachments/assets/a8ac76ba-ca4b-40dd-a38d-79bb34d996a7)

Además, se proyecta una trazabilidad de las acciones que se han realizado para tenerlo en cuenta en el desarrollo.

![Image](https://github.com/user-attachments/assets/e5c54ce1-1389-4b2a-9ecc-7a6e9cf86ae0)

Por último, se proyectan nuevamente las observaciones en el modal de vista de documentos para que desde este punto todos los roles puedan ver tanto los comentarios de rechazo como la trazabilidad de acciones realizadas sobre el registro.

![Image](https://github.com/user-attachments/assets/271caf4d-be3b-411b-9357-ce7b45b18e52)


**Comparto enlace del diseño guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Programaci%C3%B3n/Subm%C3%B3dulo%20Plan%20Anual%20de%20Auditor%C3%ADa?csf=1&web=1&e=BT8C8g


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, el diseño cumple con lo solicitado!
