### ISSUE TITLE
Agrupación componentes de la fase programación del PAA - microcliente plan anual auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#232]
Se requiere realizar la agrupación de los componentes de la fase de programación del plan anual de auditoría, manteniendo los componentes transversales fuera de la agrupación.
![image](https://github.com/user-attachments/assets/491b0a89-8ccc-47a1-a1f8-2b10b6a8d59b)

**Sub Tareas**

- [x] Agrupar los componentes relacionados a la fase de programación basado en la organización del [mockup](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ElwvBODc9MBLjUAiv1mlqewB5mrhFNzWoFuIY2fUdtwZAg?e=lmcMoX). Agrupar vista de consulta de planes, registro del plan (información, auditorías), evaluación y aprobación por jefe y secretario, asignación de auditorias.
- [x] Pruebas funcionales del correcto funcionamiento luego de reorganizar los componentes y ajustar rutas.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Material de apoyo**
- Ejemplo https://github.com/udistrital/sga_cliente_admisiones_mf/tree/develop/src/app/components/asignar-documentos-descuentos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Revisión y Reestructuración de `plan_anual_auditoria_mf`

**Comparación con la Estructura de SGA**:
Se inició la revisión de la estructura actual del microfrontend `plan_anual_auditoria_mf`comparandolo con el modelo de SGA, donde todos los componentes se registran y manejan desde `app.module.ts`, y todas las rutas están centralizadas en `app-routing.ts`. Esto permite una administración más sencilla y centralizada de componentes y rutas.

**Cambios en el mf**:

Se plantea eliminar este componente `GestionAuditoriaComponent`, dado que duplica las funciones de `ConsultaPlanAnualAuditoriaComponent`, pero con la implementación de `stepper`.

Los componentes relacionados con la consulta del plan se han movido a una nueva carpeta llamada `programacion` y se prueba el correcto funcionamiento, se evidencia que la organización de que cada componente cuente con su propio modulo no afecta el cambio de carpetas.

![image](https://github.com/user-attachments/assets/f5332b0e-2da5-447b-83b1-b0afc17aef4e)

**Comment by CristianCGutierrezG** [comment]
El componente `revision-plan-auditoria` ha sido renombrado a `revision-jefe` 

Se ajustaron todos los componentes relacionados con el módulo de `programacion`  y  se realizaron pruebas tras los cambios del correcto funcionamiento de cada componente

![image](https://github.com/user-attachments/assets/d4ca7ddf-cc45-45fb-bf58-ce1eec854d9e)


https://github.com/user-attachments/assets/32149d3a-1186-465f-b350-be08ffc0dbd6

**Comment by edwargl7** [comment]
Muy buen trabajo. Se resuelve el PR.

**Observación**
- Manejar el componente en upper camel case
![image](https://github.com/user-attachments/assets/507083b2-9381-4d02-9b68-5c240a91ee1a)
