### ISSUE TITLE
Implementación microservicio MID plan anual de auditorio

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#233]
Se requiere realizar la implementación del microservicio MID [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) que complemente la funcionalidad del microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) suministrando la información faltante en las consultas getOne y getAll relacionada a parámetros CRUD. 

**Sub Tareas**

- [x] Implementación base microservicio.
- [x] Implementación endpoints getAll integrados con parámetros CRUD.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se genera proyecto en nest

**Comment by jucastro94** [comment]
se desarrolla los 3 services con logica de enviar peticion solo una vez a parametros, este traera la informacion y la guardara en un array asi no se optimizara el rendimiento, una vez guardada la informacion en el array se reemplazara en la data entrante

![Image](https://github.com/user-attachments/assets/11fd59e1-398b-458a-9cae-d4da75082e11)
![Image](https://github.com/user-attachments/assets/1faaa8c3-d5f8-4dd6-a7e7-18b2cce9ab6d)
![Image](https://github.com/user-attachments/assets/d28efb6e-2753-4749-9d3e-9e4c6b2e703e)
![Image](https://github.com/user-attachments/assets/088092a0-8d1a-4574-ad9c-e274258a338b)
![Image](https://github.com/user-attachments/assets/a6639d01-ea92-45e6-8708-9d159f9d9092)

**Comment by jucastro94** [comment]
se requieren los Ids en parametros de tipo_parametros de 

tipo_id
macroproceso
lider
responsable
medio_id

**Comment by jucastro94** [comment]
se corrige estadoId


se hace prueba funcional
![Image](https://github.com/user-attachments/assets/2ca94c48-874c-4a74-bf4e-9727e33d06d5)
![Image](https://github.com/user-attachments/assets/f5ecd1e6-6a45-4801-b212-7a271552a3f1)

**Comment by jucastro94** [comment]
se integra control de query params para peticion a crud
![Image](https://github.com/user-attachments/assets/37344850-71c5-4720-94af-d71a2f4253ed)

**Comment by jucastro94** [comment]
se realizan correcciones para manejo de getOne
![Image](https://github.com/user-attachments/assets/09c3e989-c1d2-4362-b4c6-fe458a5e0c29)
![Image](https://github.com/user-attachments/assets/797bb032-96f4-4d76-845b-e6721726e9bc)
![Image](https://github.com/user-attachments/assets/cd595dd2-adef-4bc2-b9af-6fcb610c4716)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

**plan auditoria**
![Image](https://github.com/user-attachments/assets/48987597-5b2f-4d77-9a59-0233204d494c)
![Image](https://github.com/user-attachments/assets/2bae013c-43e7-4491-92b7-487e4b56093c)
![Image](https://github.com/user-attachments/assets/64f97505-dc51-48fc-bdb2-8fdafd37b6e9)

---

**auditoria**
![Image](https://github.com/user-attachments/assets/a5535691-98e6-4902-86f2-7fed1a5a8287)
![Image](https://github.com/user-attachments/assets/d7f5b99d-97a0-431f-a401-aa3f4fe7eece)
![Image](https://github.com/user-attachments/assets/71bc934e-2602-427a-8bd7-01b355cdea60)

---

**actividad**
![Image](https://github.com/user-attachments/assets/27a31b8f-bd36-426c-95d8-88ee6fc69569)
![Image](https://github.com/user-attachments/assets/dde23c93-f9b2-46cd-bfe2-400462bd33f1)
![Image](https://github.com/user-attachments/assets/7da3d97e-ec39-47a7-8b5d-97b73fa146fc)

**Comment by edwargl7** [comment]
Muy buena documentación y se observa un buen manejo en la petición a parámetros CRUD mediante el uso de fields, reduciendo así la cantidad de campos retornados.
