### ISSUE TITLE
Implementación estructura de almacenamiento en serverless carga masiva

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#234]
Se requiere realizar la implementación de la funcionalidad para generar el payload y la url de la petición para realizar el registro de los datos obtenidos del archivo realizando el procesamiento requerido a cada campo. Además, realizar los ajustes mencionados en la Issue #228.

**Sub Tareas**

- [x] Separar la lógica implementada para procesar el base64 y lectura del archivo en funciones separadas. Aplicando responsabilidad única.
- [x] Implementación función que crea la URL que debe ser consumida para el POST con los datos del JSON o diccionario de entrada.
- [x] Implementación y control de excepciones para las funciones basadas en el JSON o diccionario de entrada a la lambda que indica el procesamiento a cada campo de cada fila.
- [x] Pruebas funcionales.
- [x] Cambio variable de entorno en el microcliente que consume el serverless.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultados pruebas funcionales.

**Material de apoyo**
- Estructura JSON sugerida para la implementación.
```json
{
   "service":"Usuario",
   "endpoint":"/periodos",
   "structure":{
      "FechaFin":{
         "posicion":0,
         "required":true
      },
      "FechaInicio":{
         "posicion":1
      },
      "Finalizado":{
         "posicion":2,
         "parse":"booleano",
         "required":true
      },
      "RolId.Id":{
         "posicion":3,
         "parse":"int"
      },
      "UsuarioId.Id":{
         "posicion":4,
         "parse":"int"
      }
   }
}
```

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Creación de funciones

Se realiza la creación de diferentes funciones para separar la logica de la lectura del archivo y creación del dataframe, asi como el envío de los datos al endpoint:

![Captura de pantalla 2024-10-28 a la(s) 8 48 34 p m](https://github.com/user-attachments/assets/cd98892c-692e-46aa-8c35-9661a86c9aa9)

![Captura de pantalla 2024-10-28 a la(s) 8 48 40 p m](https://github.com/user-attachments/assets/1b190f7a-6277-4701-acdf-7b435e5bcb70)

![Captura de pantalla 2024-10-28 a la(s) 8 48 47 p m](https://github.com/user-attachments/assets/9687fbe4-62d0-46bd-b181-ca03fae8d2cb)

![Captura de pantalla 2024-10-28 a la(s) 8 48 53 p m](https://github.com/user-attachments/assets/890b448e-121f-4797-829f-6d260fb7a7c1)

Finalmente se realiza la verificación de funcionamiento después de los cambios realizados enviando un archivo xlsx desde el cliente para su registro y se ejecuta correctamente:

![Captura de pantalla 2024-10-28 a la(s) 8 49 06 p m](https://github.com/user-attachments/assets/62f25013-fa44-4179-bb20-8e0ef0ba1a7d)

**Comment by alexhrr** [comment]
### Implementación estructura

Se comienza la creación de las funciones para implementar la estructura json, asi como para la creación de la url tomando los datos de la estructura

![Captura de pantalla 2024-10-29 a la(s) 8 41 12 p m_](https://github.com/user-attachments/assets/e1ebd823-ce10-45e3-9e74-5914151860ed)

![Captura de pantalla 2024-10-29 a la(s) 8 41 42 p m_](https://github.com/user-attachments/assets/d098a9b0-262c-4de2-8a5d-580cc5f48bdc)

![Captura de pantalla 2024-10-29 a la(s) 8 42 18 p m_](https://github.com/user-attachments/assets/05e5675b-a7ba-4d09-875d-2205ab2e3a7c)

![Captura de pantalla 2024-10-29 a la(s) 8 41 54 p m_](https://github.com/user-attachments/assets/f2cd29b1-f8f0-4ef9-b7a2-b558c122cf5f)

**Comment by alexhrr** [comment]
### Implementación estructura

Se Prueba el funcionamiento de la implementación de la nueva estructura enviando unos datos para ser registrados en el endpoint de periodos usuarios, se obtienen algunos errores y se procede a su solución.

Posteriormente se envían los datos nuevamente y se logra crear el registro correctamente: 

Estructura enviada al endpoint:

![Captura de pantalla 2024-10-30 a la(s) 4 12 19 p m](https://github.com/user-attachments/assets/1651e828-f14b-453a-a30f-23fc399c6576)

Resultado de la lambda:

![Captura de pantalla 2024-10-30 a la(s) 4 12 51 p m](https://github.com/user-attachments/assets/7c5dd2eb-a58d-4da4-88d0-25a30323df64)

Registros creados en la base de datos:

![Captura de pantalla 2024-10-30 a la(s) 4 13 33 p m](https://github.com/user-attachments/assets/2f3d92fc-cd47-40d5-9411-d688d1e47b77)

**Comment by alexhrr** [comment]
### Pruebas de funcionamiento

Se realizan ajustes y pruebas adicionales para la validación de campos requeridos y no requeridos
En este caso se envia vacío el campo de fecha fin que no es un campo requerido en la base de datos

![Captura de pantalla 2024-10-30 a la(s) 4 54 48 p m](https://github.com/user-attachments/assets/4defed86-07a8-441c-b72c-b03f907a2c3b)

Se observa que realiza el registro correctamente:

![Captura de pantalla 2024-10-30 a la(s) 4 55 05 p m](https://github.com/user-attachments/assets/6edea7f5-6a9d-4460-850f-9b2cf1dddcb9)

![Captura de pantalla 2024-10-30 a la(s) 4 55 13 p m](https://github.com/user-attachments/assets/584d0c90-a53e-4a0e-9e80-82932dfb73ef)

Tambien se realiza una prueba adicional registrando unos datos diferentes y a un endpoint diferente, por lo que se hace la tabla con los siguientes registros para crear diferentes roles:

![Captura de pantalla 2024-10-30 a la(s) 5 53 12 p m](https://github.com/user-attachments/assets/2a26436a-daf6-4348-930a-178b206b7839)

![Captura de pantalla 2024-10-30 a la(s) 5 53 28 p m](https://github.com/user-attachments/assets/34fc5421-49a1-4598-a22a-14a93334bcfa)

![Captura de pantalla 2024-10-30 a la(s) 5 53 36 p m](https://github.com/user-attachments/assets/fa527285-3b75-414d-8d75-6ae358b8bee0)

![Captura de pantalla 2024-10-30 a la(s) 5 53 49 p m](https://github.com/user-attachments/assets/f97e2cf9-6cc7-4203-9ce0-babb12637d8d)

**Comment by alexhrr** [comment]
### Ajustes en el código

Se realiza la verificación y cambio de nombres en las variables y funciones:

![Captura de pantalla 2024-10-31 a la(s) 9 21 22 p m](https://github.com/user-attachments/assets/3fd52ae1-ffa9-4720-a642-765c41c72901)

![Captura de pantalla 2024-10-31 a la(s) 9 23 49 p m](https://github.com/user-attachments/assets/4e758a43-9c10-41df-9cbb-e8a31901ee24)

![Captura de pantalla 2024-10-31 a la(s) 9 29 07 p m](https://github.com/user-attachments/assets/c2f5a28f-2287-4f17-8e3e-5775edd1313b)

Se separa en una función nueva la parte del código que hace parse en los tipos de datos:

![Captura de pantalla 2024-10-31 a la(s) 9 23 13 p m](https://github.com/user-attachments/assets/30e4d591-659c-4c2b-a51a-9175626168d1)

**Comment by alexhrr** [comment]
## Ajustes y pruebas cargue masivo

### Campos vacíos

En esta prueba se revisa que al enviar un campo requerido vacío muestre el error de esa fila indicando cual columna falta y que continue con los otros registros.
También se revisa que al enviar vacío un campo no requerido lo registre en la base de datos:

![Captura de pantalla 2024-11-01 a la(s) 6 45 38 p m](https://github.com/user-attachments/assets/3fbfcd84-7126-4dd5-be3a-5cd87edc19fc)

![Captura de pantalla 2024-11-01 a la(s) 6 45 52 p m](https://github.com/user-attachments/assets/ef4a443b-7c5c-4c13-b97b-99a667766dcf)

![Captura de pantalla 2024-11-01 a la(s) 6 48 01 p m](https://github.com/user-attachments/assets/1ee9a0d4-01db-4f38-842d-b5e691b49a6f)

### Columnas archivo vs estructura

Se evalúa que cuando al archivo xlsx le falte alguna columna indicada en la estructura genere un error y muestre la columna faltante en el archivo y no continue con la ejecución de la lambda:

![Captura de pantalla 2024-11-01 a la(s) 6 49 06 p m](https://github.com/user-attachments/assets/0b2c1496-326e-4054-b95b-db0909617ca9)

![Captura de pantalla 2024-11-01 a la(s) 6 48 52 p m](https://github.com/user-attachments/assets/885cbfa6-ebf4-4d14-ad56-30c28ae53889)

### Revision payload enviado

Se imprime el payload que se va a enviar al la petición:

![Captura de pantalla 2024-11-01 a la(s) 7 06 02 p m](https://github.com/user-attachments/assets/652a6b00-49e9-492f-83e0-f573179b1330)

![Captura de pantalla 2024-11-01 a la(s) 7 08 04 p m](https://github.com/user-attachments/assets/12e950a3-bb80-4b55-a2d0-d569302f02c1)

**Comment by edwargl7** [comment]
Muy buena implementación y documentación. Se resuelve el PR.
