### ISSUE TITLE
Ajustes CRUD base - microservicio plan anual auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#235]
Se requiere realizar la implementación del campo Metadata a los endpoints getAll del microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) para la vista de consulta que requiere paginación. Además, realizar los ajustes mencionados en la Issue #229.

**Sub Tareas**

- [x] Implementación metadata endpoints getAll.
- [x] Los campos de este modelo no deben ser obligatorios exceptos los de seguimiento (activo, fecha creación, fecha modificación).
- [x] Cambio campo "cronograma_actividad" por "cronograma_ids".
- [x] Cambio campo "lider" y "responsable" por "lider_id" y "responsable_id".
- [x] El campo plan_auditoria_id no puede ser obligatorio dado que se pueden crear auditorías fuera del plan denominadas auditorías especiales.
- [x] Ajustes en los campos de los dto o schemas referente al estilo de escritura (CamelCase o Snake Case).
- [x] Ajustes mensajes retornados por el controlador y service.
- [x] Agregar documentación complementaria a cada función del controlador para generar un swagger más detallado. Ejemplo: [documentación controlador](https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/contratista/contratista.controller.ts), [documentación serializador](https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/contratista/contratista.service.ts)
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se cambia el requerido para las 3 colecciones
![Image](https://github.com/user-attachments/assets/faee797d-b339-4266-b88f-755b41d352f7)

se ajustan los estilos de escritura en para las 3 colecciones y se unifican en CamelCase
![Image](https://github.com/user-attachments/assets/d5eab78f-f992-41e8-b4df-1e6e15808151)

se cambia  "cronograma_actividad" por "cronograma_ids"
![Image](https://github.com/user-attachments/assets/4d8a7e75-b2a1-4689-a11a-169fc1f205ff)

se cambia lider" y "responsable" por "lider_id" y "responsable_id".
![Image](https://github.com/user-attachments/assets/bcb5c889-5e26-4f44-a531-bbba1e7cd861)

se cambia el requerido para campo de plan auditoria id
![Image](https://github.com/user-attachments/assets/3f9ed139-e0fe-4f32-bb31-195dd57149fb)

Agregar documentación complementaria a cada función en controladores

![Image](https://github.com/user-attachments/assets/112d667d-dfe1-4c01-b0cb-7d27277b25ff)
![Image](https://github.com/user-attachments/assets/5b39e382-16f4-4438-8b12-1188eb4208f7)
![Image](https://github.com/user-attachments/assets/ab275b89-342a-4ef4-a326-529c0972c49e)
![Image](https://github.com/user-attachments/assets/2a1c3df7-2f77-4907-a2e9-b31c56fa2a0d)
![Image](https://github.com/user-attachments/assets/dda6e352-0d42-4b92-b63b-107401e2465f)

**Comment by edwargl7** [comment]
Pendiente revisar generación de swagger con decoradores nuevos agregados al controlador.

**Comment by jucastro94** [comment]
se implementa objeto "metadata" con campo meta data
![Image](https://github.com/user-attachments/assets/f8fa8b66-2fbd-4676-a985-f33615468d44)
![Image](https://github.com/user-attachments/assets/d33dc83d-fc42-4b6a-a647-6bf284eaf93e)

**Comment by jucastro94** [comment]
se corrigen y modifican los mensajes de controladores y servicios

**Comment by jucastro94** [comment]
se ajusta alineacion de formato en el codigo, se corrigen pruebas de integracion, quedan fallando solamente 3 (los GetAll de cada coleccion)

![Image](https://github.com/user-attachments/assets/977f3214-47c0-4045-b155-65028b129c90)
![Image](https://github.com/user-attachments/assets/544ba8aa-eeb2-4618-9036-f7cbfe2ba423)
![Image](https://github.com/user-attachments/assets/237679a6-be91-4eb1-a175-2f7251d7a9b2)
![Image](https://github.com/user-attachments/assets/ba4eb1ac-1234-4e8b-8d51-10e4dde46140)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales
![Image](https://github.com/user-attachments/assets/927d9ecb-b14d-4fed-b66c-b311ce794530)
![Image](https://github.com/user-attachments/assets/09147e40-5a08-4d25-b0b5-477b7784f10e)
![Image](https://github.com/user-attachments/assets/4b3360ef-f82c-482b-ba75-e5a911da5cb4)
![Image](https://github.com/user-attachments/assets/990bacbb-9aa8-4b8e-aa7e-9b5c6e9fc733)
![Image](https://github.com/user-attachments/assets/5b50ac34-0ff6-4b8e-9a21-08069fed5f4e)

**Comment by jucastro94** [comment]
se desarrollan las pruebas de integracion para el campo count, en el controlador y el service, se soluciona los errores mencionados para los getAll 

service.scpec
![Image](https://github.com/user-attachments/assets/39466f18-e6e0-4592-afff-60fb2e59df0a)
![Image](https://github.com/user-attachments/assets/b4b97a5c-fe59-483c-aacf-795e85a2c847)

controller.spec
![Image](https://github.com/user-attachments/assets/ae0ccca5-9c7d-4703-b868-c9ea79886426)
![Image](https://github.com/user-attachments/assets/13815e7a-825b-4bb6-85ec-79c7fb0a1711)


pruebas funcionales de prubas de integracion
![Image](https://github.com/user-attachments/assets/2e48d470-5d2a-4666-aa1d-3b29a9e8c655)
![Image](https://github.com/user-attachments/assets/ece8cbb4-b3de-4662-8440-fa8b9fe3b3b3)

**Comment by jucastro94** [comment]
se  corrige informacion de count, antes traia el total de registros de la base de datos, ahora trae la cantidad de datos segun el query aplicado
![Image](https://github.com/user-attachments/assets/111ec55a-ba39-4d19-9c91-b6181b343807)

**Comment by jucastro94** [comment]
se hacen pruebas funcionales

 Plan Auditoria

![Image](https://github.com/user-attachments/assets/539de7ed-9c5d-4613-a550-a16df03e342d)
![Image](https://github.com/user-attachments/assets/d15f17e2-e602-43d2-ba04-ba9de0f5aa63)
![Image](https://github.com/user-attachments/assets/5fb94964-4e01-42a7-87bd-52d8b98fdf93)
![Image](https://github.com/user-attachments/assets/27851056-f75d-4e81-8052-048e92382f66)

---
Auditoria
![Image](https://github.com/user-attachments/assets/dba48770-69b8-47bb-95e8-1e82def04148)
![Image](https://github.com/user-attachments/assets/520e1c94-c142-44c6-8806-694325a3fa2e)
![Image](https://github.com/user-attachments/assets/52141497-2e71-48d8-84ec-c4f8f72436d9)
![Image](https://github.com/user-attachments/assets/5248242e-26b3-4979-8416-e347d6a19a5a)
 
---

Actividad
![Image](https://github.com/user-attachments/assets/0179e2a9-4307-43f3-a73e-186fc616012c)
![Image](https://github.com/user-attachments/assets/f0d69c60-b530-4177-a67a-c983cb4e5959)
![Image](https://github.com/user-attachments/assets/1180fefd-693f-4757-bed9-1d255ead0cc4)
![Image](https://github.com/user-attachments/assets/c1a6bb4c-b3c1-4605-9525-d748cd7bc905)

**Comment by edwargl7** [comment]
Muy buena documentación e implementación. PR resuelto.
