### ISSUE TITLE
Implementación endpoint consumo cargue masivo de auditorías microservicio MID plan anual auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#236]
Se requiere realizar la implementación del endpoint (en el microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid)) que cuente con la estructura JSON que debe ser enviada al momento de consumirse el endpoint de cargue masivo en el microcliente.

**Sub Tareas**

- [x] Creación JSON con la estructura requerida para el cargue masivo de las auditorías.
- [x] Implementación controlador que permita la integración entre el microcliente y el serverless enviando el json con la url, endpoint y estructura requerida por la lambda.
- [x] Implementar en el mismo controlador el manejo de excepciones que permita responder al microcliente en caso de peticiones erradas por no disponibilidad o problemas con el serverless, así como las respuestas exitosas.
- [x] Integración endpoint implementado en el microservicio MID con el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) con el botón de cargue masivo.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
El microcliente debe enviar al MID
```
{
   "base64data":"...",
   "complement":{
      "plan_auditoria_id":18
   },
   "type_upload":"auditorias"
}
```

Ejemplo estructura quemada en el MID

```
{
   "auditorias":{
      "base64data":"...",
      "service":VARIABLE_ENTORNO_SERVICE,
      "endpoint":"/v1/roles",
      "complement":{
         "plan_auditoria_id":18
      },
      "structure":{
         "titulo":{
            "file_name_column":"id",
            "required":true
         },
         "tipo_evaluacion_id":{
            "file_name_column":"auditoria",
            "required":true
         },
         "cronograma_id":{
            "column_group":[
               "enero",
               "febrero",
               "marzo",
               "abril",
               "mayo",
               "junio",
               "julio"
            ],
            "mapping":{
               "enero":1,
               "febrero":2,
               "marzo":3,
               "abril":4,
               "mayo":5,
               "junio":6,
               "julio":7
            }
         }
      }
   }
}
```

**Comment by alexhrr** [comment]
### Implementación cargue masivo

Se crea el modulo de cargue-masivo en plan_anual_auditoria_mid y se crea en controller y el service

![Captura de pantalla 2024-11-14 a la(s) 11 43 51 p m](https://github.com/user-attachments/assets/3cf4a6fe-5c92-4a89-a8d7-96fd48dc274f)

En el service se crea la estructura necesaria tomando en cuenta los datos recibidos desde el microcliente.
Me reúno con Juan para resolver las dudas con lo ids de los valores a usar en el mapping y confirmar los datos de la plantilla de excel y los del crud. Asi mismo me explica lo necesario para la ejecución del crud.

Estructura con los datos y mapping:

![Captura de pantalla 2024-11-14 a la(s) 11 48 48 p m](https://github.com/user-attachments/assets/a2b9df2e-34f3-4986-8ac8-27ce6c7d88c0)

Ajusto las funciones en el microcliente para enviar los datos necesarios al mid

![Captura de pantalla 2024-11-14 a la(s) 11 46 13 p m](https://github.com/user-attachments/assets/5d69fdfe-225b-4d45-9b8b-4c16dbe507f2)

![Captura de pantalla 2024-11-14 a la(s) 11 46 20 p m](https://github.com/user-attachments/assets/252c3681-7425-4d44-a515-76d2e6692569)

Se reciben los datos enviados del mf en el mid: 

![Captura de pantalla 2024-11-15 a la(s) 8 39 18 a m](https://github.com/user-attachments/assets/4e357861-8d00-48b6-9e7a-f7dc426fdb93)

**Comment by alexhrr** [comment]
### Integración mf - mid - serverless - Crud

Se envían algunos registros en la plantilla de excel para la creación de auditorias.
Los datos enviados contienen algunos campos vacíos para verificar el funcionamiento de la lambda en estos casos.
Tambien se seleccionan algunos campos de los meses para verificar que tome correctamente los meses correspondientes.

![Captura de pantalla 2024-11-15 a la(s) 6 26 00 p m](https://github.com/user-attachments/assets/4657e539-4198-4ab0-8a4d-7d1f6348369a)

El archivo es enviado desde el modal del microcliente de cargue masivo:

![Captura de pantalla 2024-11-15 a la(s) 7 18 44 p m](https://github.com/user-attachments/assets/75853486-c27a-4d74-8a76-8c0349e6f005)

En la estructura del mid se encuentran los datos necesarios para el mapping que realiza la lambda:

![Captura de pantalla 2024-11-15 a la(s) 7 21 07 p m](https://github.com/user-attachments/assets/4f7d78f0-3f35-4d2c-951b-248d6ded56c8)

Se envía el archivo y el mid crea la estructura necesaria y lo envía a la lambda donde se procesa el base64 recibido y se crea el payload para ser enviado al crud

En la lambda se verifica el dataframe del base64 y la creación del payload por cada registro valido del archivo excel.
Se observa que se realiza correctamente el mapping.

![Captura de pantalla 2024-11-15 a la(s) 6 21 01 p m](https://github.com/user-attachments/assets/7bf94ced-319f-4dfa-8707-76364f8b21b2)

Se verifica la creación de los registros en el crud, aqui se muestran los registros enviados correctamente y los que tienen algún error, el error es mostrado.
En este caso los errores corresponden a las celdas vacías del archivo excel enviado al inicio

![Captura de pantalla 2024-11-15 a la(s) 6 20 36 p m](https://github.com/user-attachments/assets/efac3c1e-7805-4d95-8a2c-f686ce59c5b3)

Se hizo uso del crud desplegado en el ambiente de pruebas, se hace una petición en postman para verificar los registros creados:

![Captura de pantalla 2024-11-15 a la(s) 6 22 47 p m](https://github.com/user-attachments/assets/45375876-6a84-44e2-b0c5-9a7521cc548f)

![Captura de pantalla 2024-11-15 a la(s) 6 23 10 p m](https://github.com/user-attachments/assets/b7d30ad1-d46c-4f66-abd4-df2b2b55f64f)

**Comment by edwargl7** [comment]
Muy buena documentación, pruebas e implementación. 

**Observaciones**
- Integrar complemento para enviar ObjectId del plan al que se registran las auditorias.
- Cambiar nombre de variable LAMBDA_SERVICE por CARGUE_MASIVO_MID
