### ISSUE TITLE
Integración microcliente y microservicio CRUD para registro del plan anual de auditoría - Fase programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#237]
Se requiere realizar la integración con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) para la creación del plan anual de auditoría en la fase de programación.

**Sub Tareas**

- [x] Integración/actualziación datos paramétricos vigencias.
- [x] Implementación integración creación de plan para nueva vigencia elegida.
- [x] Implementación integración registro de información al plan (objetivo, criterio, recurso, ...).
- [x] Implementación registro de auditoría individual asociada al plan.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Material de apoyo**
- Creación del registro del plan (método POST).
![image](https://github.com/user-attachments/assets/7d2e6677-ac4f-4e9a-8eeb-87cd3f43c9b8)
- Actualización del plan agregando información (método PUT).
![image](https://github.com/user-attachments/assets/ca377e84-86d3-444a-8976-e1cff32254f5)
- Registro individual de una auditoría (método POST).
![image](https://github.com/user-attachments/assets/6c096571-c7e4-46d2-9e72-a3febb8e4045)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
**Registro de Plan de Acción**:
   - Los valores asociados con el registro de un plan de acción se han dejado temporalmente especificados en la plantilla base del formulario.
   - Se ha comentado la lógica que maneja estos valores con variables de entorno
   ![image](https://github.com/user-attachments/assets/9b390eac-9693-45eb-ba08-3c104e97e9fa)
 

**Conexión con Servicio de Parámetros**:
   - Se estableció una conexión con el servicio de parámetros para obtener los años de vigencia en el componente de consulta. Esto permite actualizar automáticamente los datos según la vigencia configurada.
![image](https://github.com/user-attachments/assets/908bad39-964c-4a8b-bca6-ff5e0e330be5)


 **Clonación y Ejecución del Repositorio `plan_anual_auditoria_crud`**:
   - Se clonó el repositorio `plan_anual_auditoria_crud`, cargando las variables de entorno y el archivo Docker.
   - Se inicia con el desarrollo del servio en el microcliente.
   ![image](https://github.com/user-attachments/assets/3ed9e62c-2252-4727-b904-27a467a39771)

**Comment by CristianCGutierrezG** [comment]
Implementación del llamado de los meses en el componente `AddAuditoriaModal` , junto con la funcionalidad de agregar todos

![image](https://github.com/user-attachments/assets/9cc872f2-82ce-43a5-a85d-c3b6d67e44ba)

**Error de CORS**
Se inicia la integración de la funcionalidad para la creación de un nuevo plan pero se encuentra con un error al momento de hacer la petición.

![image](https://github.com/user-attachments/assets/83f75195-88d8-45bb-b242-a1bcc08b93cb)

Investigando se identifica que el error en la petición POST fue causado por la falta de permisos CORS en el servicio `plan_auditoria_crud`.
Se añade el siguiente código al servicio para permitir el acceso CORS y resolver el problema:

![image](https://github.com/user-attachments/assets/272b57b2-cc5d-4e3b-923c-c0bbed82f225)

**Creación de Planes y Visualización en Tabla**:
Con el error  solucionado, se logra realizar la petición POST para crear un nuevo plan de auditoría basado en el año de vigencia.
Los planes existentes ahora se obtienen correctamente y se muestran en la tabla, con algunos datos por defecto que se ajustarán en próximas iteraciones.

https://github.com/user-attachments/assets/77e51629-3908-453d-beea-bd1e9493e883

**Comment by CristianCGutierrezG** [comment]
### Implementación de la Integración para el Registro de Información al Plan

1. **Cambio de Página y Carga de Plantilla**:
   - Se ha realizado un ajuste en la implementación para que al cambiar de página se pase el dato del ID del plan específico.
   - Actualmente, la plantilla se carga por defecto, independientemente del ID que se pase como parámetro.

2. **Actualización de Planes**:
   - Se implementa correctamente la petición PUT para actualizar un plan específico con los datos ingresados en el formulario.
   - Esto permite que los cambios realizados en el formulario se reflejen en el plan correspondiente.

3. **Visualización de Datos del Plan**:
   - Al intentar visualizar los datos obtenidos de un plan específico, se detecta un error que provoca que todos los formularios se actualicen, ignorando su ID específico.
 

https://github.com/user-attachments/assets/487b7683-1993-4dd3-b50a-678e318edcd4


### Implementación del Registro de Auditoría Individual

1. **Creación de Auditoría**:
   - Se logra realizar la petición POST para crear una nueva auditoría, asegurando su relación con el ID del plan específico.
   - Esto permite que cada auditoría esté correctamente asociada al plan al que pertenece.

2. **Peticiones de Datos**:
   - Aún queda pendiente realizar las peticiones de los datos correspondientes dependiendo del ID del plan para poder visualizar y manejar la información de manera adecuada.


https://github.com/user-attachments/assets/45c5cc7b-cd08-4578-90bf-af2b286b6207

**Comment by edwargl7** [comment]
Muy buena documentación e implementación. Se resuelve el PR. Se puede manejar un orden ascendente que nos permita el último creado que ocupe la primera fila de la tabla.
