### ISSUE TITLE
Implementación base microcliente ejecución de la auditoría - Fase de ejecución

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#238]
Se requiere realizar la implementación base del microcliente para la ejecución de las auditorías en el repositorio [ejecucion_auditoria_mf](https://github.com/udistrital/ejecucion_auditoria_mf).

**Sub Tareas**

- [x] Implementación microcliente base para ejecución de auditorías.
- [x] Implementar componente de modales de alerta basado en el implementado en [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).
- [x] Agregar microcliente al root.

**Criterios de aceptación**

- [x] Documentación avances implementación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### creación ejecucion_auditoria_mf

Se realiza la creación del microcliente y se ajustan algunos parámetros necesarios.
Se agregan los estilos en assets con theme.scss y se agregan los environments

![Captura de pantalla 2024-10-31 a la(s) 9 12 39 p m](https://github.com/user-attachments/assets/0de6cf85-66f0-4490-9e2d-4b06cb02ec09)

**Comment by alexhrr** [comment]
### Creación microcliente ejecución de la auditoria

Se termina de implementar la base del mf y se agrega el servicio del modal, tambien se implementan los managers

![Captura de pantalla 2024-11-01 a la(s) 5 11 28 p m](https://github.com/user-attachments/assets/cdc477ad-1559-41af-966a-d544595118d0)

Se ejecuta el mf y se levanta correctamente:

![Captura de pantalla 2024-11-01 a la(s) 5 11 52 p m](https://github.com/user-attachments/assets/66f31364-b7e4-4c2c-8231-087057b9487f)

Se agrega el mf al root:

![Captura de pantalla 2024-11-01 a la(s) 5 13 02 p m](https://github.com/user-attachments/assets/87b47103-e31f-460a-bddf-33ce8d47f5d3)

![Captura de pantalla 2024-11-01 a la(s) 5 13 12 p m](https://github.com/user-attachments/assets/938621ce-3fb7-47a3-9977-f44257b28132)

Se ejecuta el root y se monta correctamente el mf de ejecucion-auditoria:

![Captura de pantalla 2024-11-01 a la(s) 5 12 17 p m](https://github.com/user-attachments/assets/85fd2606-8f69-45c4-a1f0-3ae4a7a5b580)

**Comment by edwargl7** [comment]
Muy buen trabajo. Remover carpeta .vscode y agregarla al gitignore por favor.
![image](https://github.com/user-attachments/assets/c3226e4b-1d9d-4937-87d4-0647e93eefbe)
