### ISSUE TITLE
Diseño excel y ajustes plantilla renderizado plan anual de auditoría - Fase Programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#239]
Se requiere realizar el diseño del formato de auditorías basado en la propuesta realizada inicialmente. Ajuste en la [plantilla HTML](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ES-u_q4aLFtDhEZmkPkljE4B3T98nXUgv0gso-_ziDtQMA?e=Bqi6Mw).

**Sub Tareas**

- [x] Crear plantilla XLSX basado en la prueba inicial que cubra los campos de información de auditoría.
- [x] Ajuste plantilla en orientación horizontal y uniformidad en los campos de los meses.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Soporte de plantilla XLSX cargada en la carpeta y en la Issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
cambia el sentido de la hoja a horizontal y el tamaño a carta

se cambia las imagenes para obtener mejor calidad
![Image](https://github.com/user-attachments/assets/71f15882-4cc1-4e9e-88f9-9994a04678e9)


pueba de documento
[descarga (1).pdf](https://github.com/user-attachments/files/17581565/descarga.1.pdf)

**Comment by jucastro94** [comment]
se revisa plantilla xslx
![Image](https://github.com/user-attachments/assets/5e36da9b-4eb4-4988-b981-c3ea9bef7e99)

valores parametricos es necesario buscar los ids que seran asociados
![Image](https://github.com/user-attachments/assets/d9d2038a-4e00-4e5d-8baa-5ccc25e4bb00)

**Comment by edwargl7** [comment]
Muy buen ajuste del diseño del HTML, se requiere ajustar el tamaño de letra del encabezado igual al resto del contenido del PDF.

**Comment by jucastro94** [comment]
se ajusta tamaño de letra e imagenes de plantilla

se cambia nombres de meses a abreviacion abre

[descarga (2).pdf](https://github.com/user-attachments/files/17594949/descarga.2.pdf)

falta ajustar la ubicacion de las imagenes

**Comment by jucastro94** [comment]
se ajusta plantilla xlsx
[prueba plantilla validacion.xlsx](https://github.com/user-attachments/files/17594955/prueba.plantilla.validacion.xlsx)

**Comment by edwargl7** [comment]
Muy buen diseño y ajustes del HTML, pendiente ajuste logo de la Universidad que se manejará en una siguiente Issue.
Del archivo XLSX remover columna de estado por favor.
![image](https://github.com/user-attachments/assets/ed8c8c59-5ef1-49c6-a85b-02ec1712d9e4)
Muy buen trabajo.

Se revisaran los formatos con @cjgonzalezp.
