### ISSUE TITLE
Creación módulo de gestión de roles Sísifo v2 - Microfrontend roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#24]
Se requiere realizar el diseño y desarrollo inicial del módulo de gestión de roles apoyado del diseño actual de sisgplan y el desarrollo del root de Sísifo v2 y consumo del core mf. Para esta primera etapa es requerido el diseño y desarrollo sin implementar la lógica de consumo de endpoints. Es requerido si integrarlo con el root y core mf teniendo presente los lineamientos de microclientes.

**Material de apoyo**
- [Aplicación Root](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/root_config.md)
- Credenciales acceso sisgplan

**Especificaciones técnicas**
1. El repositorio para el microcliente del módulo de roles es:

2. Se requiere crear el cliente a partir de single-spa.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.

**Sub Tareas**

- [x] Desarrollar microfrontend del módulo de gestión de roles
- [x] Uso de estilos respectivos [assets](https://github.com/udistrital/assets)

**Criterios de aceptación**

- [x] Cliente de gestión de roles creado
- [x] Código subido al repositorio teniendo presente los lineamientos [Etiquetas en Comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md#etiquetas-en-comentarios-de-commits)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Tomamos como ejemplo el módulo de sisgplan.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/6c48dffd-dd7c-4dee-841f-e31a80315840)

**Comment by edwargl7** [comment]
Te comparto el mf de sisgplan https://github.com/udistrital/planeacion_construccion_mf

**Comment by CristianCGutierrezG** [comment]
# Creación y ajustes del mf configuración 

## Ejecución del Root

Se realizo la clonación y ejecución de los repositorios:
 Root [sisifo_root_mf](https://github.com/udistrital/sisifo_root_mf)
 Core [core_mf_cliente](https://github.com/udistrital/core_mf_cliente)


![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/4ced0827-fa62-4b91-b3cd-d2f991ec1d4f)

## mf configuración

Creación de una aplicación de single-spa application / parcel de acuerdo a las indicaciones 
Con el uso recomendado de **Angular CLI: 16.2.14**, ya que las nuevas versiones vienen por defecto con el modo standalone y realiza la configuración de las rutas de manera distinta 

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/009adcfc-1a59-4c0c-8347-b2915fa6b69c)

Incluyendo la ruta al nuevo cliente en el objeto **parcels** de los diferente environments del **mf Root**

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/d68c91ad-c531-4c2e-b9fc-cb12f5137b59)

Se hace llamada al **mf configuración** en **microfrontend-layout.html** haciendo las configuraciones para que detecte que es llamada desde la nueva ruta

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/e7b9b1b6-077f-4c16-893c-ff52a23a30ce)
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/343a338d-02a9-4b72-8315-400aac940902)

**mf configuración** montado en la nueva ruta

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/fa2ffa4e-78ad-430e-b6d0-68f314687ef7)

**Comment by CristianCGutierrezG** [comment]
Se crea el modulo de gestión de roles y su respectivo componente, tomando como referencia el módulo de sisgplan

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/2769532e-81ad-4ea9-9c3f-566cd289f2db)
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/d6dfba05-ba9e-49f0-89ae-b413545908f4)

**Comment by edwargl7** [comment]
Muy buen trabajo y buena documentación, se realiza la revisión y se comparte el proceso trabajado con el equipo, errores y soluciones realizadas para el correcto funcionamiento.
