### ISSUE TITLE
Diseño estados plan anual de auditoría - Fase programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#240]
Se requiere realizar el diseño de la colección de estados del plan anual de auditoría que funcione similar a una tabla de rompimiento muchos a muchos. Que contenga los campos id, usuario_id, observación, estado_id (parámetros crud) fecha estado, plan anual id y activo. Ver ejemplo de ARGO v2:
![image](https://github.com/user-attachments/assets/163c2005-9dd4-4177-b741-c4d7908cb69a)

**Sub Tareas**

- [x] Diseño colección de histórico de estados y observaciones del flujo de aprobación del plan.

**Criterios de aceptación**

- [x] Modelo de datos con tabla de gestión de histórico de estados y observaciones.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
- Lineamientos [Modelos de Datos en Mongo](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/lineamientos_mongo.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia la revisión para el Diseño de estados **plan anual auditoria**

**Comment by OscarLozano01** [comment]
**Estructura de la Tabla** `pla_estado`

- `id`: Identificador único de cada registro de estado.
- `plan_anual_id`: Relación con el plan anual de auditoría para el que se está registrando el estado. Esto asegura que podamos rastrear a qué plan específico pertenece cada cambio de estado.
- `usuario_id`: Identificador del usuario que realiza la acción de cambio de estado (auditor, jefe, secretario, etc.).
- `observacion`: Campo opcional de texto que permite añadir comentarios u observaciones cuando se rechaza el plan o se agrega alguna nota importante.
- `estado_id`: Identificador del estado actual (en revisión, rechazado, aprobado, etc.), que se obtiene de una tabla de parámetros de estados para mantener consistencia.
- `fecha_ejecucion_estado`: Fecha y hora exactas en las que se realiza el cambio de estado, almacenando año, mes, día, hora, minutos y segundos.
- `activo`: Campo booleano que indica si el registro está activo, permitiendo una eliminación lógica.
- `fecha_creacion`: Fecha y hora en la que se creó el registro de estado.
- `fecha_modificacion`: Fecha y hora de la última modificación en el registro de estado.

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/455c6072-c2c3-4aa0-a11b-ae89d7f80023)

**Comment by OscarLozano01** [comment]
Actualización:
![image](https://github.com/user-attachments/assets/ab79db63-b616-43bf-b22a-cfc7c50a3413)

**Comment by edwargl7** [comment]
Aprobado, presentar por favor el modelo completo actualizado. Muchas gracias.

**Comment by OscarLozano01** [comment]
[Ruta del archivo](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehjgo7MTHz5NgSSmKg5dOMcBXDJX_KkhOhJ0E6ialeezzQ?e=tpyshQ)

![image](https://github.com/user-attachments/assets/93ef6ea0-bac8-468e-b4b5-8e919538e10e)

**Comment by edwargl7** [comment]
Se finaliza la Issue con el modelo actualizado. Muchas gracias.
