### ISSUE TITLE
Implementación estados plan anual de auditoría - Fase programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#241]
Se requiere realizar la implementación del controlador CRUD de estados que gestiona el histórico de estados y observaciones del plan anual de auditoría. Estos estados permiten gestionar la aprobación del plan.

**Sub Tareas**

- [x] Implementación CRUD estados del plan.
- [x] Implementación pruebas de integración controlador estados Ejemplo: [documentación controlador](https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/contratista/contratista.controller.ts), [documentación serializador](https://github.com/udistrital/gestion_contractual_crud/blob/develop/src/contratista/contratista.service.ts)
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.
- [x] Documentación de avances en la implementación y resultados pruebas de integración.

**Requerimientos**

- Aprobada la actualización del modelo de datos Issue #240.

**Especificaciones técnicas**
- Repositorio microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se desarrolla controller, service, dto y schema

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

**POST**
![Image](https://github.com/user-attachments/assets/fb0ffd23-7551-41c1-83ac-6492216da34f)
![Image](https://github.com/user-attachments/assets/2825c568-92a9-4ca6-9196-bd286bae91ea)


**GETALL**
![Image](https://github.com/user-attachments/assets/49945d7f-c10b-4983-9bd8-7630093a3104)

**GETONE**
![Image](https://github.com/user-attachments/assets/756cc809-28d8-4404-8dbe-a61abeca6577)

**PUT**
![Image](https://github.com/user-attachments/assets/88752330-c7a7-4233-b466-9276d96c7f8c)
![Image](https://github.com/user-attachments/assets/0e0eb504-a1f5-46b9-8cb3-0da2616d6e89)

**DELETE**
![Image](https://github.com/user-attachments/assets/e080fd52-1e8b-44ec-82b8-1b45fcf3ee22)
![Image](https://github.com/user-attachments/assets/7e89a60a-7054-4c59-b623-c850c57d5ad1)


**QUERY PARAMS**
query
![Image](https://github.com/user-attachments/assets/bea3238a-6c9f-4499-94f9-6e057a7d4b5a)
![Image](https://github.com/user-attachments/assets/6db75123-0fcc-476a-9469-c65967972a50)

fields
![Image](https://github.com/user-attachments/assets/0474ded2-11bf-40d2-ad7a-25b04ce8349a)
![Image](https://github.com/user-attachments/assets/bab0ba52-a79f-418c-89b6-79bba3689351)

sortby y order
![Image](https://github.com/user-attachments/assets/d416c3d3-aae7-4ba9-9fd8-e926b7d19cf4)
![Image](https://github.com/user-attachments/assets/ed46ed1d-ff11-4e11-85de-58e087336b6e)

limit y offset
![Image](https://github.com/user-attachments/assets/105c5e7c-6b56-4a99-9615-6f6101082130)
![Image](https://github.com/user-attachments/assets/1a2386a6-64cd-427f-aa6a-5c79c1a6e756)

**Comment by edwargl7** [comment]
Se manejará el estado actual basado en el última estado creado usando fechaEjecuciónEstado.

**Comment by jucastro94** [comment]
se cambian los schemas y dtopara que trabajen con snakecase
![Image](https://github.com/user-attachments/assets/1e83f2fa-0451-4911-950c-4eb53cc583f5)
![Image](https://github.com/user-attachments/assets/94f64543-3c5a-4b21-87d8-ed1b1a2d32cd)

se realizan pruebas funcionales

![Image](https://github.com/user-attachments/assets/dd247c46-2fca-41b3-821c-e8802c026b44)
![Image](https://github.com/user-attachments/assets/88b57a5b-d909-4e4c-9d26-fdf3e5aa6094)

---

![Image](https://github.com/user-attachments/assets/b14fcd6b-f430-44ee-832a-2ab10f9c6849)
![Image](https://github.com/user-attachments/assets/00f6bbfb-004d-40e6-9b4b-ea1b2a54b463)

---

![Image](https://github.com/user-attachments/assets/732ccfdf-bf5c-4e86-a0f5-4a4c3328a604)
![Image](https://github.com/user-attachments/assets/4517d4dd-11a7-431f-b56f-84003b7ae9ec)

---

![Image](https://github.com/user-attachments/assets/368aa2e9-c1ad-4d5f-af53-53696301fc0a)
![Image](https://github.com/user-attachments/assets/6d066e18-49ba-447d-8c33-3fefd23c64d6)

**Comment by jucastro94** [comment]
se implementan pruenas de integracion

![Image](https://github.com/user-attachments/assets/3728fdf4-7ca2-479c-ad71-c109627c5ab6)
![Image](https://github.com/user-attachments/assets/c2ec3469-6f53-4339-863b-5b9561599b88)
![Image](https://github.com/user-attachments/assets/0cc45af1-99d7-4de5-9aa3-1317348496f6)

**Comment by edwargl7** [comment]
Muy buena implementación, por favor baja los cambios de develop y ajusta los conflictos generados y crea el PR para combinar los cambios.

**Comment by jucastro94** [comment]
se realiza fetch y merge de develop a feature/crud-estado-plan, se resuelven conflictos, y se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/d8a6ad51-c108-42ad-801f-e8e1f65d88a4)

![Image](https://github.com/user-attachments/assets/103ae5a9-72c3-4253-b451-c542e64d598f)

![Image](https://github.com/user-attachments/assets/a6ff6e10-c2d9-4b72-805b-1e40c97f8615)
![Image](https://github.com/user-attachments/assets/454f2f21-e9f6-479e-b3ca-5342fbcf8c30)

---

![Image](https://github.com/user-attachments/assets/601e28d4-51a2-4075-92b3-139a6b63072f)
![Image](https://github.com/user-attachments/assets/c26e7c6a-fbfb-4272-b77c-a3b7958a9ad5)

![Image](https://github.com/user-attachments/assets/37664480-87a2-4f05-96a3-972e022932e4)

---

![Image](https://github.com/user-attachments/assets/fd3d4141-325d-4220-8c59-c26226469630)
![Image](https://github.com/user-attachments/assets/4d1eb78a-484d-4ea0-8b37-65f58f5b6f35)
