### ISSUE TITLE
Creación de historias de usuario de fase de planeación desde el rol de jefe de oficina y auditado

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#244]
Se requiere realizar la documentación de las historias de usuario para la fase planeación desde el rol de jefe de oficina y auditor.

**Sub Tareas**

- [x] Investigación de las historias de usuario para la fase planeación.

**Criterios de aceptación**

- [x] Documentación de las historias de usuario para el módulo de registro de contratos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la creación y articulación del formato HU para la fase de planeación desde los roles jefe OCI y auditado.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/[HU](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/HU?csf=1&web=1&e=QEzw2h)?csf=1&web=1&e=QEzw2h


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, revisaremos en review para posteriormente buscar aprobación de cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la creación y articulación del formato HU para la fase de planeación desde los roles jefe OCI y auditado.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/HU/HU-%20Historia%20de%20Usuario%20Subm%C3%B3dulo%20Planeaci%C3%B3n%20Auditor%C3%ADas.xlsx?d=we34303c134d24b6e8d1ffe9f2e1455a5&csf=1&web=1&e=Yn9bOU


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente aprobación por parte del usuario.
