### ISSUE TITLE
Implementación aprobación secretario microcliente plan anual auditoria - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#245]
Se requiere realizar la implementación del encadenamiento de modales iniciada en la Issue #227. Para el flujo de aprobación del secretario que cuenta con el modal de confirmación, luego el modal de carga de acta y finalmente la confirmación de completado.

**Sub Tareas**

- [x] Implementación encadenamiento en modal de carga de documentos.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia la implementación del encadenamiento de los módales para el proceso de aprobación secretario.

**Comment by edwargl7** [comment]
No se observan commits nuevos y no se cuenta con una documentación de avances en la Issue.

**Comment by OscarLozano01** [comment]
Se realiza la implementación de 1 Modal utilizando un Stepper con una secuencia de 3 pasos.

https://github.com/user-attachments/assets/26cf44f0-afd8-4f4f-98ec-adc9bdc59b71

**Comment by OscarLozano01** [comment]
Se inicia ajustes esteticos de la importación del documento PDF y flujo a los botones de Siguiente, Cancelar, Finalizar.

**Comment by OscarLozano01** [comment]
![screencapture-localhost-4200-plan-auditoria-plan-anual-auditoria-2024-11-05-10_05_52](https://github.com/user-attachments/assets/214245e1-2284-4808-bebb-67481e696d5a)

**Comment by OscarLozano01** [comment]
https://github.com/user-attachments/assets/d56b9fd0-ec6b-4c3a-be09-a86713b6b2f7

**Comment by edwargl7** [comment]
Se completa el desarrollo, se valida con el analista @cjgonzalezp y se debe ajustar a como se solicitó en el mockup. Sin embargo, es una propuesta que para el flujo requerido no aplica.
