### ISSUE TITLE
Implementación manejo de excepciones en serverless cargue masivo

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#246]
Se requiere realizar el manejo de excepciones en cada función implementada en el microservicio [cargue_archivo_mid_serverless](https://github.com/udistrital/cargue_archivo_mid_serverless) de tal forma que los errores que actualmente se imprimen puedan ser retornados en el body de la respuesta.

Se puede complementar cada función retornando una tupla de valores (valor actual, error) y según cada tipo de excepción (critica que finaliza el proceso o error en cada fila que se debe agrupar para responder al final del proceso, por ejemplo, datos incompletos en la fila) se debe manejar para retornar dicha respuesta.

**Definición respuesta**
Actualmente retorna,
![image](https://github.com/user-attachments/assets/f8c946ea-cd6f-4a69-af90-3e55f8ec735d)
Se puede complementar con:
```json
{
   "Success":"success",
   "Status":"status_code",
   "Message":"message",
   "Data":"data"
}
```
Ejemplos:
```json
{
   "Success":true,
   "Status":201,
   "Message":"Documento procesado correctamente",
   "Data": null
}
```

```json
{
   "Success":true,
   "Status":201,
   "Message":"Documento procesado con algunos registros por revisar",
   "Data":{
      "Correctos":[
         1,
         2,
         4,
         6,
         7,
         8,
         10
      ],
      "Erróneos":[
         {
            "Idx":3,
            "Error":"Error en conversión del campo FechaFinal"
         },
         {
            "Idx":5,
            "Error":"Falta campo FechaFinal"
         },
         {
            "Idx":9,
            "Error":"Id 180 no encontrado"
         }
      ]
   }
}
```

**Sub Tareas**

- [x] Implementación retorno de errores de las funciones implementadas.
- [x] Estructura de respuesta según excepción generada (criticas o individuales).
- [x] Implementación campo adicional de referencia (para este caso el archivo no conoce a que plan se están cargando dichas auditorias, este campo se pasa en el JSON de parametrización).
- [x] Implementar captura de errores en las funciones build_url (caso que falte service o endpoint o tipo erróneo) y parse_value (error de conversión).
- [x] Captura de respuesta para peticiones con status_code diferente a 200 o 201, esa respuesta debe asociarse al registro de la petición dado que si falla es necesario retornar en la respuesta ese registro porque falló.
- [x] Implementación función de mapeo de string por el Id respectivo (requerido para mapear los meses Enero, Febrero, ... a los respectivos Ids de parámetros CRUD).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Manejo de excepciones

Se agrega el manejo de errores para la función build_url:

![Captura de pantalla 2024-11-05 a la(s) 11 23 26 p m](https://github.com/user-attachments/assets/fb768354-5f9d-472a-8bac-68baee096016)

Se agrega el manejo de errores para la función parse_value:

![Captura de pantalla 2024-11-05 a la(s) 11 23 18 p m](https://github.com/user-attachments/assets/cdb67729-2cc4-4161-876d-ae9c7c8c28fc)

Se inicia con la revision y prueba del manejo de los registros por fila y acumulandolos:

![Captura de pantalla 2024-11-05 a la(s) 11 37 36 p m](https://github.com/user-attachments/assets/9cd8555c-457e-40b0-ae46-f98992a82bc2)

**Comment by alexhrr** [comment]
## Manejo de excepciones

Se realizan ajustes en el código para capturar los errores en cada función usando tuplas.

![Captura de pantalla 2024-11-06 a la(s) 9 37 59 p m](https://github.com/user-attachments/assets/549e5873-2709-478e-979e-8b15b9667582)

![Captura de pantalla 2024-11-06 a la(s) 9 35 08 p m](https://github.com/user-attachments/assets/ed41cbec-9df3-4a26-b86a-2c39bf234e7b)

![Captura de pantalla 2024-11-06 a la(s) 9 36 04 p m](https://github.com/user-attachments/assets/2847cb78-6b12-466b-9f2c-fd09d8fb3da0)

### Pruebas

Columnas faltantes en el archivo xlsx, se devuelve un error donde se indica la columna faltante:

![Captura de pantalla 2024-11-06 a la(s) 5 50 56 p m](https://github.com/user-attachments/assets/c9f68cf8-08b2-4db7-a18f-3529cd31de21)

Error del archivo base 64 enviado:

![Captura de pantalla 2024-11-06 a la(s) 5 56 44 p m](https://github.com/user-attachments/assets/3217713e-5e2c-4fbc-aabe-dfcddb3f9f06)

Error al intentar ajustar el tipo de dato en la función parse_value:

![Captura de pantalla 2024-11-06 a la(s) 6 19 04 p m](https://github.com/user-attachments/assets/b3deba91-5c98-4635-94f8-c676cd13947e)

Se envía un campo requerido vacío y se muestra la columna y el indice del dato:

![Captura de pantalla 2024-11-06 a la(s) 7 46 10 p m](https://github.com/user-attachments/assets/582afba5-761c-4bce-b512-cca851a6ac8d)

Se envía un registro sin errores para verificar la respuesta:

![Captura de pantalla 2024-11-06 a la(s) 9 25 50 p m](https://github.com/user-attachments/assets/4ffc7aa7-25ae-40df-99d3-5705e7212e21)

**Comment by edwargl7** [comment]
Ejemplo para datos complementarios (subtarea 3):

```
{
   "service":"Usuario",
   "endpoint":"/periodos",
   "complement"; {
	"plan_auditoria_id": 18
   },
   "structure":{
      "FechaFin":{
         "posicion":0,
         "required":true
      },
      "FechaInicio":{
         "posicion":1
      },
      "Finalizado":{
         "posicion":2,
         "parse":"booleano",
         "required":true
      },
      "RolId.Id":{
         "posicion":3,
         "parse":"int"
      },
      "UsuarioId.Id":{
         "posicion":4,
         "parse":"int"
      }
   }
}
```

Estructura de mapeo:
```
"mapping": {
         	"Admin": 1,
         	"Auditor Experto": 2,
         	"Auditor": 3
         }
```

**Comment by alexhrr** [comment]
### Implementación mapping

Se agrega al código la funcionalidad de realizar el mapping cargado en la estructura para tomar los valores cuando se envíen para este caso los roles en texto desde el archivo

![Captura de pantalla 2024-11-07 a la(s) 6 38 44 p m](https://github.com/user-attachments/assets/b831d1a1-d0c0-4c28-bce2-f815382d7fcc)

![Captura de pantalla 2024-11-07 a la(s) 6 38 54 p m](https://github.com/user-attachments/assets/9ebb2123-710f-468c-8543-7eba6bde4ea1)

Se envía el archivo con los datos de prueba y se agrega a la estructura el rol en texto y su respectivo id, se obtiene la respuesta con los registros correctos:

![Captura de pantalla 2024-11-07 a la(s) 6 34 02 p m](https://github.com/user-attachments/assets/5b201cd7-e12b-4f16-947c-f39e28ab5083)

![Captura de pantalla 2024-11-07 a la(s) 6 34 46 p m](https://github.com/user-attachments/assets/3bf9a084-1cd4-455e-bcb4-4e19161981a6)

### Implementación complement

Se crea la función add_complement donde se realiza la actualización del payload:

![Captura de pantalla 2024-11-07 a la(s) 8 22 22 p m](https://github.com/user-attachments/assets/51ca8bdf-6d8e-4b44-9b28-45f0cc8d2b0e)

Se agrega a la estructura json el complement:

![Captura de pantalla 2024-11-07 a la(s) 8 21 39 p m](https://github.com/user-attachments/assets/5272867a-e2c6-4a67-8247-2bf69d358897)

Se muestra el payload inicial y la actualización con el complement:

![Captura de pantalla 2024-11-07 a la(s) 8 20 55 p m](https://github.com/user-attachments/assets/592235ba-f1ab-4de3-bade-cfb7d637c8ba)

**Comment by alexhrr** [comment]
### Array en payload 

Se agrega la funcionalidad de tomar los encabezados de unas columnas especificas si las celdas no están vacías, estos datos se agregan a un array que adiciona al payload para ser enviado al endpoint posteriormente:

![Captura de pantalla 2024-11-09 a la(s) 10 39 42 a m](https://github.com/user-attachments/assets/936f46d2-4123-4fa5-aa6a-bc2e471d25a3)

![Captura de pantalla 2024-11-09 a la(s) 10 39 48 a m](https://github.com/user-attachments/assets/15570ed3-dffd-4376-99ee-d71b8392e582)

Se ajusta el código de validación de las columnas entre la estructura y el archivo para que tome en cuenta las columnas agrupadas en la estructura:

![Captura de pantalla 2024-11-09 a la(s) 10 39 27 a m](https://github.com/user-attachments/assets/a6e991f6-a586-4720-9e55-7bb5b0f69903)

Validación con datos de prueba:

Se envían campos vacíos y con diferentes valores para validar el funcionamiento:

![Captura de pantalla 2024-11-09 a la(s) 10 35 22 a m](https://github.com/user-attachments/assets/c25d92ef-2afa-47de-8b84-feb4021e08b1)

Se envía la estructura con los campos   agrupados del cronograma:

![Captura de pantalla 2024-11-09 a la(s) 10 40 04 a m](https://github.com/user-attachments/assets/320b7b9c-74f3-48f2-a8ad-dd8d9be03dc0)

Se agrega correctamente al payload los datos necesarios según el archivo enviado:

![Captura de pantalla 2024-11-09 a la(s) 10 35 07 a m](https://github.com/user-attachments/assets/3a259296-8a07-4988-ab68-17472bc86559)

Se debe realizar un ajuste para las celdas que tienen un espacio ya que las toma como celdas no vacías. 
También falta ajustar los nombres de las variables y revisar logs del código.

**Comment by edwargl7** [comment]
Muy buen trabajo, dado que no se realizó el despliegue por reagendamiento se cubre la implementación del manejo de arrays adicionalmente al alcance inicial de la tarea. Se deben realizar ajustar para no contar con la key especifica de cronograma_ids.
![Image](https://github.com/user-attachments/assets/71213672-0bbb-4861-bb27-a8edb0c5b3ee)
Y ajuste en el nombre de la key nombre_columnas. Para mantener formato similar en la estructura, y un mismo idioma en la parametrización.
