### ISSUE TITLE
Despliegue microservicio cargue masivo mid serverless

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#247]
Se requiere realizar el despliegue del microservicio [cargue_archivo_mid_serverless](https://github.com/udistrital/cargue_archivo_mid_serverless) en ambiente de pruebas.

**Sub Tareas**

- [x] Ajustes previos al despliegue.
- [ ] Despliegue microservicio.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Criterios de aceptación**

- [ ] Documentación resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Ajustes previos 

Se realiza la verificación del código para eliminar los logs que no son necesarios en la ejecución de la lambda.

Se ajusta el print del dataframe para verificar los datos del archivo, se muestran los encabezados y las primeras filas para que no se muestre todo el archivo completo en caso de tener muchos registros:

![Captura de pantalla 2024-11-08 a la(s) 6 47 43 p m](https://github.com/user-attachments/assets/b2433579-3980-4355-88b9-241691e98286)

Se complementa el readme con base al proyecto de prueba piloto lambda

![Captura de pantalla 2024-11-08 a la(s) 6 58 05 p m](https://github.com/user-attachments/assets/4c7e4575-95a8-490c-943d-99c884b36c57)

**Comment by edwargl7** [comment]
Se finalizan los ajustes previos y se complementa esta tarea con un desarrollo adicional registrado en la Issue #246.
