### ISSUE TITLE
Implementación endpoint para generar PDF del plan en la fase de programación en el microservicio plan_anual_auditoria_mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#248]
Se requiere realizar la implementación del endpoint que construya el JSON requerido para el renderizado de la plantilla con los datos registrados del plan (información base y auditorías).

**Sub Tareas**

- [x] Pruebas funcionales microservicio plantillas mid desplegado en ambiente de pruebas.
- [x] Implementación endpoint para generar PDF del plan en la fase de programación en el microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid).
- [x] Integración endpoint con el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).
- [ ] Integración para almacenamiento del PDF con el gestor documental.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan pruebas funcionales a plantillas mid en ambiente de pruebas

![Image](https://github.com/user-attachments/assets/ae2e38f2-e5cb-4bfc-8d61-8f140824f340)

![Image](https://github.com/user-attachments/assets/114776cd-66b9-4d42-8a54-394cdc44060b)

resultado obtenido
![Image](https://github.com/user-attachments/assets/2298d5ea-677f-4cf5-965d-4098007c1750)
[prueba plantillas mid ambiente de pruebas.pdf](https://github.com/user-attachments/files/17722508/descarga.6.pdf)

**Comment by jucastro94** [comment]
se genera modulo plantilla en plan_auditoria_mid  (controller con get y service)
![Image](https://github.com/user-attachments/assets/a1ed76c2-a579-451b-a82d-677467e8248b)


se realiza peticion a plan_auditoria_crud
![Image](https://github.com/user-attachments/assets/95026e82-354c-4d6e-83df-420ccd609b77)

se trabaja en la organizacion de la data para contrurir el json a plantillas_mid
![Image](https://github.com/user-attachments/assets/4f87aceb-6f53-4993-9469-8b8f59f2f0b9)
![Image](https://github.com/user-attachments/assets/e541d87e-ccf2-4cd7-9b70-c83b57b83b94)

se envia peticion POST a plantillas_mid
![Image](https://github.com/user-attachments/assets/0b316f1f-2e0b-4b5c-8097-ef87995ab98d)

**Comment by jucastro94** [comment]
se ajusta plan auditoria mid para generacion de formato con plantillas_mid con base en plan auditoria crud

se realizan prueba funcional
![Image](https://github.com/user-attachments/assets/94a4dafa-a11a-4687-8d51-01194b37e534)
![Image](https://github.com/user-attachments/assets/01181b5b-418d-48cf-90b3-30059e8338dd)

**Comment by jucastro94** [comment]
se integra enpoint con mf modulo registrar-auditorias
![Image](https://github.com/user-attachments/assets/83c8f809-4012-4bc6-b621-9f79ca65b4f9)
![Image](https://github.com/user-attachments/assets/00839f86-da11-4144-8006-25eb8fc493c2)

se crea metodo consumo de recuestmanager
![Image](https://github.com/user-attachments/assets/5097ff99-0235-44ec-89ea-da789369e771)

se crea variable de entorno para MID
![Image](https://github.com/user-attachments/assets/1747455e-af09-4723-a734-eb1b718f531f)

se realizan ajuste de claves que estaban con estilo camelCase, se cambian a snakeCase
![Image](https://github.com/user-attachments/assets/f5a89332-39e7-4da6-a1b5-e13a8e641774)


se realiza prueba lanzando error
![Image](https://github.com/user-attachments/assets/8fd64c0c-69d5-4dfc-99d8-9b920f22d3f6)

**Comment by edwargl7** [comment]
Se finaliza la Issue se continuará en el siguiente sprint. Muchas gracias.
