### ISSUE TITLE
Ajustes plantilla plan anual de auditoria - Fase programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#249]
Se requiere realizar los ajustes mencionados en la Issue #239 al HTML (Ajuste contenedor logo UD) y ajustes al XLSX. Además, se requiere la actualización del HTML en el servicio plantillas serverless (se realiza la revisión y no cuenta con versionado pero si con endpoint de actualización).

**Sub Tareas**

- [x] Ajustes template HTML.
- [x] Ajuste template XLSX.
- [x] Actualización HTML en servicio serverless.
- [x] Pruebas resultados obtenidos.
- [x] Listado de variables requeridas en el template HTML con el nombre de la variable.

**Criterios de aceptación**

- [x] Documentación ajustes realizados a los templates.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan correcciones a plantilla xlsx
![Image](https://github.com/user-attachments/assets/2d470c01-9c14-4961-aadc-804b56944a79)
[prueba plantilla validacion.xlsx](https://github.com/user-attachments/files/17637818/prueba.plantilla.validacion.xlsx)

**Comment by jucastro94** [comment]
**lista de variables requeridas en el template HTML**

- "codigo": " EC-PR-005-FR-001",

- "proceso":"Gestión de la Evaluación y el Control",

- "objetivo":"Planear las actividades que realizará el equipo auditor de la Oficina de control interno, mediante la aplicación de auditorías y seguimientos que contribuyan a proteger los recursos, garantizar los estándares de las operaciones, la confiabilidad y oportunidad de la información, dar manejo adecuado a los riesgos para contribuir con el cumplimiento de los objetivos institucionales y la mejora de la gestión de la Universidad.",

- "alcance":"Los informes determinados por la ley, los procesos, procedimientos y normatividad interna, requerimientos de los entes de control y partes interesadas, planes de mejoramiento, políticas de operación y gestión de riesgos.",

- "criterios":"<br>- Normatividad interna y externa aplicable a la Universidad.<br>- Direccionamiento Estratégico<br>- Modelo Integrado de Planeación y Gestión MIPG<br>- Sistema Integrado de Gestión<br>- Proyectos de Inversión",

- "recursos":"<br>- Humanos: Equipo de trabajo de la Oficina de Control interno (servidores públicos y/o particulares que ejerzan funciones públicas permanente o transitoria)<br>- Financieros: Presupuesto asignado<br>- Tecnológicos: Equipos de computo, sistemas de información, archivo documental, papelería, sistemas de redes y correo electrónico de la Universidad.",

- "items":[

        {"actividad": "pensamiento sincronico del conocimiento", "enero": "marcado", "febrero": "marcado", "marzo": "marcado", "abril": "marcado", "mayo": "marcado", "junio": "", "julio": "", "agosto": "", "septiembre": "marcado", "octubre": "marcado", "noviembre": "", "diciembre": "" },

         {"actividad": "anilisis analitico para analizar analizando anilisis analitico para analizar analizando anilisis analitico para analizar analizando", "enero": "", "febrero": "", "marzo": "", "abril": "marcado", "mayo": "marcado", "junio": "marcado", "julio": "", "agosto": "marcado", "septiembre": "marcado", "octubre": "", "noviembre": "", "diciembre": "" }
]

**Comment by jucastro94** [comment]
se centran imagenes en plantilla html, se acomoda tamaño de columnas de logos, se incorporan imagenes a la plantilla html para que no lleguen como variables
[json plantilla html.txt](https://github.com/user-attachments/files/17639354/json.plantilla.html.txt)

se realiza prueba funcional
[descarga (3).pdf](https://github.com/user-attachments/files/17639357/descarga.3.pdf)

**Comment by jucastro94** [comment]
se actualiza platilla en serverless 
![Image](https://github.com/user-attachments/assets/ffd0fafc-7e60-475b-9381-44762e3d1ecb)

se realiza prueba funcional a plantillas mid
![Image](https://github.com/user-attachments/assets/3d596202-90b5-48df-9a97-5126a46ae077)

resultado obtenido
![Image](https://github.com/user-attachments/assets/bdf5668c-a53f-4c59-a858-90d95b552a10)
[descarga (4).pdf](https://github.com/user-attachments/files/17639512/descarga.4.pdf)


json para plantillas_mid
[json plantillas_mid.txt](https://github.com/user-attachments/files/17639513/json.plantillas_mid.txt)

**Comment by edwargl7** [comment]
Muy buen trabajo, se puede realizar ajuste en el logo para mejorar su visualización por favor.
@cjgonzalezp nos ayudas con tu revisión por favor.

**Comment by edwargl7** [comment]
Color Hexadecimal para el encabezado del cronograma #8DB4E2

**Comment by edwargl7** [comment]
Ajustes de los dos logos y agregar altura a los títulos:
![image](https://github.com/user-attachments/assets/e7da40f7-cd83-4d71-9888-4fbdfc528779)
Y centrar:
![image](https://github.com/user-attachments/assets/f191b9e5-d34e-43c1-8f90-0eeef3eb203d)

**Comment by jucastro94** [comment]
se ajusta el color de cabecera de tabla, alineacion de encabezado, ancho de columna de SIGUD y  altura de encabezado

[prueba documento plantilla.pdf](https://github.com/user-attachments/files/17654617/export.3.pdf)
![Image](https://github.com/user-attachments/assets/4e828095-4ca6-4809-9fa0-7df398364f19)

**Comment by cjgonzalezp** [comment]
Buen trabajo @jucastro94 desde mi punto de vista creo que ya se realizaron todos los ajustes solicitados y quedo muy bien el diseño del formato.


Saludos.

**Comment by edwargl7** [comment]
Se revisa con @cjgonzalezp y se aprueba la opción del XLSX para manejo de columna por mes.

**Comment by jucastro94** [comment]
se ajusta xlsx para tomar multiples meses por cada auditoria
[prueba plantilla validacion.xlsx](https://github.com/user-attachments/files/17685221/prueba.plantilla.validacion.xlsx)

**Comment by jucastro94** [comment]
se ajusta plantilla html (cambio de imagen y alineamiento de 3ra columna a la izquierda en tabla de encabezado)
![Image](https://github.com/user-attachments/assets/77e88e3e-66fa-4ad8-82e7-9e73ff5cd1d3)
[prueba plantilla.pdf](https://github.com/user-attachments/files/17689134/prueba.plantilla.pdf)


se realiza actualizacion de plantilla en plantilla serverless
![Image](https://github.com/user-attachments/assets/28410105-1bbf-449f-bec4-e84aff4b3d10)


se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/8d6e5c9f-4d8f-4089-823b-cc84e6028c89)
![Image](https://github.com/user-attachments/assets/90c11b40-8eef-4b5c-8ae0-0c6dfa17f8c9)

**Comment by jucastro94** [comment]
se realizan ajustes en plantilla xlsx
![Image](https://github.com/user-attachments/assets/0abd865e-d6b2-4a0f-a069-be6992b90b86)

Se debera marcar con "X" los meses que correspondan segun la auditoria
[prueba plantilla validacion.xlsx](https://github.com/user-attachments/files/17689218/prueba.plantilla.validacion.xlsx)

**Comment by edwargl7** [comment]
Muy buen trabajo, aprobadas las dos plantillas. El logo de la universidad en la plantilla HTML tiene un tamaño pequeño pero logra la resolución requerida. Se finalizan las observaciones de mi parte, se revisará nuevamente estos ajustes con @cjgonzalezp para su aprobación.
