### ISSUE TITLE
Revisión y ajustes base de datos relacional - no relacional core Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#25]
Se requiere realizar la revisión inicial de la base de datos a usar para el core de Sísifo, se apoya la toma de la decisión con el equipo DBA y se realizarán los ajustes recomendados según sea el caso.

**Sub Tareas**

- [x] Revisión inicial criterios a tener presente en la selección de la base de datos.
- [x] Reunión con el equipo DBA
- [x] Ajustes modelo de datos según sea el caso.

**Criterios de aceptación**

- [x] Participación en la reunión con el equipo DBA
- [x] Ajustes al modelo según las recomendaciones dadas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Ajuste modelo de base de datos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se presentan avances
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/1779d943-880f-4ff8-8986-c0fbd2efd36e)

**Comment by edwargl7** [comment]
De le reunión con los DBAs el día 15/04/2024 se decide avanzar con una base de datos relacional, por lo tanto, el se procede a realizar los ajustes basado en los lineamientos.

Pendiente por parte del líder la revisión de la fuente de los procesos.

**Comment by jucastro94** [comment]
se aplican lineamientos de modelo de datos

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/1a8a39b3-ab7e-49a3-bff9-867d8f46a28a)

**Comment by jucastro94** [comment]
se adjunta URL archivo .draw, modedelo de datos V3
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EbcSpCZnMW9IhJaAO03-5ioBwU6kmWqICqN5N1uEmrw_cg?e=0ccriq

**Comment by edwargl7** [comment]
Muy buen trabajo, se va a revisar a más detalle los usuarios involucrados en cada registro para modificar posiblemente auditor_id por tercero_id dado que la fuente es del servicio de terceros aplicando el siguiente lineamiento.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/31af493d-99e2-430f-96c9-d5f48d75595d)
Caso similar con las dependencias.

Una vez identificado claramente los servicios identificados y resaltados de color verde y rojo se actualizaran y agregará la nota que permita visualizar que servicio proporciona dicha información.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/60300852-a0c4-4c7f-93fa-ac9464b6b1e2)

Para estos ajustes se creará una tarea que complemente claramente las fuentes de estos datos identificados. Muchas gracias.
