### ISSUE TITLE
Despliegue microservicio plantillas mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#250]
Se requiere realizar los ajustes al microservicio [plantillas_mid](https://github.com/udistrital/plantillas_mid) para el despliegue y pruebas funcionales una vez desplegado.

**Sub Tareas**

- [x] Actualización README (limpieza de variables de entorno).
- [x] Remover plantillas_mid.exe.
- [x] Agregar drone y entrypoint.
- [x] Pruebas funcionales ambiente de pruebas.

**Criterios de aceptación**

- [x] Documentación ajustes realizados y resultados pruebas funcionales ambiente de pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se agrega archivo drone

![Image](https://github.com/user-attachments/assets/8513e1ed-807d-4da7-8bad-693e77e82d16)

**Comment by jucastro94** [comment]
se crea entrypoint y se elimina plantillas_mid.exe
![Image](https://github.com/user-attachments/assets/62d2532f-7f4e-4da6-a2c8-cafca217804b)

**Comment by jucastro94** [comment]
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/c5dc1148-04a1-43f4-a680-7164e4c0759b)
![Image](https://github.com/user-attachments/assets/8e8ca988-ba2a-4800-9880-ea774bb476fc)

**Comment by edwargl7** [comment]
Se retorna la tarea a progreso dado que es requerido realizar las pruebas una vez desplegado en el ambiente de pruebas.

**Comment by jucastro94** [comment]
se integran librerias de util_oas xray y auditoria

se hace prueba funcional
![Image](https://github.com/user-attachments/assets/4877e076-58dd-4cfd-ae4a-2398611bce5c)

**Comment by edwargl7** [comment]
Se resuelve el PR y se despliega. Muy buen trabajo. Terminar la validación en el ambiente de pruebas en el siguiente sprint.
