### ISSUE TITLE
Integración microcliente y microservicio CRUD para registro del plan anual de auditoría - Parte 2 - Fase programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#251]
Se requiere realizar la implementación de la actualización del plan anual de auditoría en la fase de programación.

**Sub Tareas**

- [x] Implementación hidratación formularios existentes.
- [x] Implementación y ajustes edición del plan anual de auditoría.
- [x] Implementación e integración eliminación lógica de auditorías con los respectivos modales.
- [x] Implementación validación único plan por vigencia.
- [x] Implementación manejo de orden de auditorías usando el drag and drop.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Implementación de Hidratación en Formularios Existentes

Se ha logrado implementar correctamente la hidratación de los formularios, asegurando que se muestren los datos obtenidos de las peticiones antes de renderizar el formulario.

- Se reorganizó la lógica de manejo de datos para garantizar que los datos estén listos antes de la visualización.
- Se añadió una variable de control que indica el estado de los datos, permitiendo diferenciar entre formularios con y sin datos preexistentes.
- Se ha implementado un inicializador que formatea el formulario en caso de que no se obtengan datos en la solicitud. Esto permite que el formulario se muestre adecuadamente en un estado limpio cuando no hay datos cargados.

![image](https://github.com/user-attachments/assets/a1ce76dd-00a1-4793-af6b-d386f192b645)

https://github.com/user-attachments/assets/74552c84-3622-4f28-b6a4-5b9a0a345b04

**Comment by CristianCGutierrezG** [comment]
### Implementación e integración eliminación lógica de auditorías con los respectivos modales

https://github.com/user-attachments/assets/59c868a5-a3a2-4d1c-b54e-7a8609aabf10

**Comment by CristianCGutierrezG** [comment]
### Implementación y Ajustes en la Edición del Plan Anual de Auditoría

- **Reutilización del Componente `add-auditoria-modal`**:
  - Se ha reutilizado el componente `add-auditoria-modal` para implementar la funcionalidad de **POST** y **PUT** según el botón que se utilice al abrir el modal.
  - Se han realizado ajustes para que el componente detecte si se está creando un nuevo registro o editando uno existente basado en la presencia del ID del plan.

- **Almacenamiento de IDs del Cronograma**:
  - Se realizaron cambios para que los **IDs del cronograma de actividades** ahora se guarden como se obtienen desde `parametros_crud`, en lugar de utilizar strings con los nombres de los meses.

- **Carga de Auditorías Relacionadas al Plan**:
  - Se ha implementado la funcionalidad para **traer las auditorías** relacionadas con un plan específico, mostrando los datos correspondientes al abrir el modal en modo edición.
  - Ahora se cargan correctamente los datos del plan y sus auditorías vinculadas.

- **Funcionalidad Drag-and-Drop**:
  - Se ha probado la funcionalidad de **drag-and-drop** en la sección de registro de auditorías, y su correcto funcionamiento ha sido confirmado.
  - **Pendiente**: Implementar la actualización del **orden** de auditorías en el backend cuando se realicen cambios en el frontend mediante el drag-and-drop.

https://github.com/user-attachments/assets/890ec27b-8722-49c7-8f35-16f7ac3779bd

### Refactorización y Reutilización de Clases
  - Se ha optimizado el código para **reutilizar clases  compartidas**, mejorando la organización y reduciendo la duplicación.
![image](https://github.com/user-attachments/assets/3243d0d8-4f41-43cb-880c-0bcf1f5bad6f)

**Comment by CristianCGutierrezG** [comment]
### Ajustes en el Selector de Cronograma
Se ha agregado la opción **"Todos"** en el selector de cronograma de actividades.

![image](https://github.com/user-attachments/assets/8f38ffa8-2f72-4f90-8b48-9b264ffb508e)

![image](https://github.com/user-attachments/assets/986d569d-eaf4-4800-8360-26772aaaf883)

### Validación Única de Plan por Vigencia

- **Validación de Unicidad de Plan por Vigencia**:
  - Se ha realizado una **modificación en el microservicio `plan_anual_auditoria_crud`** para asegurar que solo se pueda registrar un plan por vigencia. El campo de **vigencia ahora es requerido y único**

![image](https://github.com/user-attachments/assets/c7e66ebf-7f5a-4d30-b494-79a35c2dd977)


- **Actualización en el Servicio `plan-auditoria`**:
  - Se han ajustado los métodos **POST** y **PUT** para validar que no exista un plan con la misma vigencia antes de proceder con el registro o la edición.

![image](https://github.com/user-attachments/assets/42141b8c-8645-4de9-aa3a-0f51a0e38714)

![image](https://github.com/user-attachments/assets/10551740-ff81-45dc-a9f3-12e9ff3ab445)

- **Implementación de Nuevos Modales para Manejo de Errores**:
  - Se han introducido **nuevos modales** para mostrar mensajes de error relacionados con la validación de vigencia en el microservicio.

https://github.com/user-attachments/assets/b07dadf0-53ec-4cd6-9bee-f4508129d921

**Comment by edwargl7** [comment]
Muy buena implementación. Se resuelven los PR del mf y ms. Tener presente nombre de funciones en el mf (idioma).

**Observaciones**
- Tener presente que podrían existir planes eliminados lógicamente dado que se incluye a nivel de modelo este manejo aunque en la vista implementada actualmente no se tenga la funcionalidad de eliminación.
![image](https://github.com/user-attachments/assets/471d4837-4a99-4912-bb29-a19c227bf545)
![image](https://github.com/user-attachments/assets/2c842b57-ea37-48cc-be56-4ade6439e47b)
