### ISSUE TITLE
Maquetación vista Auditado en etapa de ejecución

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#252]
Se requiere realizar la maquetación de la vista que permita al auditado visualizar los diferentes documentos del proceso de la auditoría. Dichos documentos se deben consultar de parámetros CRUD.
![image](https://github.com/user-attachments/assets/7c5859b6-3032-4939-9a76-4b4221a9dd63)

Implementar en el microcliente [ejecucion_auditoria_mf](https://github.com/udistrital/ejecucion_auditoria_mf).

**Sub Tareas**

- [x] Maquetación vista de consulta de documentos del auditado.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
No sé observan avances ni asistencia al daily.

**Comment by edwargl7** [comment]
No sé presentan avances ni asistencia al daily.
FYI: @jcmurilloa.

**Comment by edwargl7** [comment]
Se realiza la revisión de cierre del sprint y no sé observa avance alguno.
PSI: @jcmurilloa

**Comment by edwargl7** [comment]
Buen día,

Por favor documentar la Issue con la implementación realizada @OscarLozano01  para finalizar el sprint.

**Comment by OscarLozano01** [comment]
![screencapture-localhost-4200-plan-auditoria-auditorias-internas-2024-11-14-03_38_08](https://github.com/user-attachments/assets/f659a201-d7d2-4ce6-a9a6-eca790378ea3)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/054a8877-62c1-4d08-8e29-f6df0fa5740d)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/1fef9725-bd79-4662-bcbb-131bfc13326d)

**Comment by OscarLozano01** [comment]
Se define un componente de Angular llamado `AuditoriasInternasComponent`:

- archivo: Se usa para almacenar un archivo cargado, inicialmente es null.
- botonSeleccionado: Una cadena que indica qué botón ha sido seleccionado.
- documento: Almacena el documento en formato Base64 (en este caso, un documento PDF o similar).
- opcionSeleccionada: Almacena la opción seleccionada de los botones definidos en botonesData.
- displayedColumns: Define las columnas que se van a mostrar en una tabla (en este caso, "Id" y "Nombre"), Pero solo se muestra el Nombre en el HTML.
- botonesData: Array que contiene los datos para los botones (por ejemplo, los distintos tipos de informes disponibles en la auditoría).

**Comment by OscarLozano01** [comment]
https://github.com/user-attachments/assets/e9d75625-debd-44cd-88c9-f17c96c1e4fc

**Comment by OscarLozano01** [comment]
```
  botonesData = [
    { Id: 1, Nombre: 'Informe Preliminar' },
    { Id: 2, Nombre: 'Programa de Trabajo' },
    { Id: 3, Nombre: 'Oficio Anuncio Solicitud Información' },
    { Id: 4, Nombre: 'Carta de Representación' },
    { Id: 5, Nombre: 'Compromiso Ético del Auditor Interno' }
];
```

**Comment by OscarLozano01** [comment]
```
        <mat-table [dataSource]="botonesData">          
          <ng-container matColumnDef="Nombre">
            <mat-cell *matCellDef="let element"> {{ element.Nombre }} </mat-cell>
          </ng-container>
          <mat-row *matRowDef="let row; columns: ['Nombre'];" (click)="seleccionarOpcion(row)"
            [ngClass]="{'selected': opcionSeleccionada === row, 'unselected': opcionSeleccionada !== row}">
          </mat-row>
        </mat-table>
```

**Comment by OscarLozano01** [comment]
### Issue Finalizada

**Comment by edwargl7** [comment]
Aprobada y culminada completamente la Issue.
Muchas gracias.
