### ISSUE TITLE
Implementación manejo de roles módulo de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#254]
Se requiere realizar la implementación de manejo de roles basado en los roles del usuario de la sesión basado en la matriz de roles y permisos. Para esto emplear variables de entorno que faciliten el manejo de las comparaciones de roles en caso de ser necesario cambiar alguna (los roles a emplear son los manejados en WSO2).
[Gestión de Usuarios - Módulos y Permisos.pdf](https://github.com/user-attachments/files/17896962/Gestion.de.Usuarios.-.Modulos.y.Permisos.pdf)

**Sub Tareas**

- [x] Implementación obtención de roles del usuario de la sesión.
- [x] Implementación control de acciones vista de consulta del plan según rol Jefe.
- [x] Implementación control de acciones vista de consulta del plan según rol Secretario.
- [x] Implementación control de acciones vista de consulta del plan según rol Auditor.
- [x] Implementación control de acciones vista de consulta del plan según rol Auditor experto.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Análisis e Implementación de Roles en el Componente `consulta-plan`

#### Análisis de Repositorios
Se realizó un análisis de los siguientes repositorios para entender el manejo de roles y autenticación:
1. **sga_cliente_calendario_academico_mf**
2. **core_mf_cliente**

##### Observaciones:
- Los roles se obtienen directamente del **local storage** mediante el servicio `implicit_authentication.service` y la función `getRole()`.
![image](https://github.com/user-attachments/assets/0079e2da-6e11-4053-94d9-67b16c554b3c)

- **WSO2** no es necesario para la obtención de roles, simplificando la lógica de autenticación.
- El servicio `user.service` se utiliza para obtener información adicional del usuario en sesión.

#### Cambios Implementados
1. **Integración del Servicio de Roles**:
   - Se implementó el servicio de roles (`implicit_authentication.service`) en el componente `consulta-plan`.
   - Se utilizó la función `getRole()` para realizar pruebas con roles provisionales.
![image](https://github.com/user-attachments/assets/30fdfcd4-a0e2-4c7d-b9da-8f3aef2ed7d6)


2. **Pruebas de Obtención de Roles**:
   - Se adecuó el componente `consulta-plan` para identificar y reflejar acciones basadas en los roles obtenidos.
   - Roles y usuarios provisionales utilizados en las pruebas:
     - **utestvice**: Secretario.
     ![image](https://github.com/user-attachments/assets/de7709c8-463a-4485-8691-86d032c29c93)
     ![image](https://github.com/user-attachments/assets/cae2b238-9309-48c3-957f-111a2150f048)

     - **utest01**: Auditor Experto.
     ![image](https://github.com/user-attachments/assets/674828a3-e53d-46d7-8fe4-42ce4df318cd)

     
     - **pruebadocencia**: Jefe.
     ![image](https://github.com/user-attachments/assets/632c03ac-f723-4428-ae48-96701a9a3f17)
     ![image](https://github.com/user-attachments/assets/8ea97fad-060b-4156-8046-752710584f51)

**Comment by CristianCGutierrezG** [comment]
### Implementación de Roles y Restricciones 

1. **Integración de Cambios Existentes**:
   - Se migraron los cambios relacionados con la implementación de roles en el componente `consulta-plan` hacia la nueva estructura del microservicio.

2. **Implementación de `auth.guard`**:
   - Se añadió el guard implementado en SGA para manejar restricciones de acceso según los roles de usuario.
   - El guard realiza redirecciones automáticas en caso de usuarios no autorizados, sin mostrar alertas explícitas de restricción.
   - Algunos usuarios no cuentan con acceso al menú principal del sistema, lo que no permite analizar las restricciones específicas en ciertos casos. Actualmente, dichos usuarios tienen denegado el acceso a todo el servicio.

https://github.com/user-attachments/assets/33dca7ad-7393-4b26-8d0b-a042d813d636

**Comment by edwargl7** [comment]
Muy buena documentación y buena implementación, desarrollo presentado como avance al usuario.
