### ISSUE TITLE
Implementación observaciones del plan de auditoría en fase de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#255]
Se requiere realizar la implementación de la vista del histórico de observaciones desde la vista del auditor experto.

![image](https://github.com/user-attachments/assets/7b7cdac2-54a1-4c81-b82e-3af17091d6ba)
![image](https://github.com/user-attachments/assets/5a7e39ae-3f41-466d-b3d6-4c419ff98fa4)
![image](https://github.com/user-attachments/assets/74d85e4d-d91b-4b13-9d0f-29c92630fb9e)

**Sub Tareas**

- [x] Implementación modal de histórico de observaciones (se puede aplicar en el mismo de vista de aprobación de jefe o secretario).
- [x] Implementación acción de visualización de observaciones en la vista de consulta (solo aparece cuando el plan tiene observaciones de rechazo).
- [x] Implementación visualización de botón de observaciones en la vista del PDF (solo aparece cuando el plan tiene observaciones de rechazo).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultado pruebas funcionales.

**Materia de apoyo**
- Posibles iconos para la acción desde el auditor al tener observaciones.
```
<mat-icon>find_in_page</mat-icon>
<mat-icon>highlight_off</mat-icon>
<mat-icon>info</mat-icon>
<mat-icon>report_problem</mat-icon>
```
![image](https://github.com/user-attachments/assets/d7c289ce-e9ca-4c92-b119-facdafe6fcce)
![image](https://github.com/user-attachments/assets/e75116fb-cdd8-4a60-ba6e-84a00102c4a3)
![image](https://github.com/user-attachments/assets/209502c2-8fdd-409d-b8ea-60de8d9943bb)
![image](https://github.com/user-attachments/assets/00ae13f4-1dc9-46dd-99e0-5ddc834dfff7)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Implementación observaciones del plan de auditoría en fase de programación**

>[!NOTE]
> Interfaz de motivos de rechazo, y carga de información básica

menú: 

![image](https://github.com/user-attachments/assets/7270b9c2-ad86-4277-8ecc-8f5eb4f1870f)


Modal:

![image](https://github.com/user-attachments/assets/9f8ce11d-2474-4feb-a079-29340762b998)

Responsive:

![image](https://github.com/user-attachments/assets/e317284f-69c0-41bd-ab07-40adaffeda84)

**Comment by edwargl7** [comment]
@cjgonzalezp nos ayudas a validar si dejamos que se filtren y visualicen solamente los estados de rechazo dado que desde la vista de consulta el auditor o los demás usuarios podrían identificar en que estado está el plan.

**Comment by edwargl7** [comment]
Aprobado por @cjgonzalezp y @jcmurilloa mantener para esta funcionalidad solamente los estados rechazados. Posteriormente se evaluará la necesidad de visualizar el histórico completo.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Se agrego campo rol en el crud
> - Se trabajo el mid para traer campos completos
> - Cambio de interfaz (Se desarrollo esqueleto) Hay que ver posible librería para estas cositas

Esta activado el 3G para apreciar el esqueleto


https://github.com/user-attachments/assets/3423621c-ae2b-4cc2-be95-b0a11d286e83

**Comment by edwargl7** [comment]
Muy buena implementación, se resuelve PR.
