### ISSUE TITLE
Preparación presentación estado actual de Sísifo - Usuario final

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#256]
Se requiere realizar la preparación previa a la presentación con el usuario. Además, antes de la presentación el usuario final solicita un video previo que le permita observar el estado actual del proyecto.

**Sub Tareas**

- [x] Creación del video del estado actual del proyecto que permita ver el flujo de registro de un plan.
- [x] Creación video complementario de las vistas maquetadas de aprobación (jefe y secretario).
- [x] Preparación ambiente para la presentación.

**Criterios de aceptación**

- [x] Documentación avances de la preparación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
## Flujo de registro de un plan
https://github.com/user-attachments/assets/ec250f49-b942-4821-aacc-ee7128e54e16

**Comment by CristianCGutierrezG** [comment]
## Vistas maquetadas

https://github.com/user-attachments/assets/ebbb745f-9e19-4f26-887b-c1cb5487ea55

**Comment by edwargl7** [comment]
Muchas gracias @CristianCGutierrezG. @cjgonzalezp quedamos atentos a tu confirmación.

**Comment by edwargl7** [comment]
Diagrama del flujo para tenerlo presente.
![FLUJO ESTADOS PAA](https://github.com/user-attachments/assets/31454dda-7766-4415-afa3-a236572c5eb8)

**Comment by CristianCGutierrezG** [comment]
Se realiza una reunión con  @edwargl7  en la que se revisó el flujo del funcionamiento del software Sísifo teniendo en cuanta el desarrollo hecho hasta el momento, para tener claro el flujo a mostrar en la presentación con el cliente.

[Link de la reunión](https://udistritaleduco-my.sharepoint.com/personal/hegranadosl_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fhegranadosl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FAjustes%20despliegue%20mf%20root%20S%C3%ADsifo%20y%20preparaci%C3%B3n%20presentaci%C3%B3n%2D20241115%5F132153%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%201%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E5bef93e2%2D079b%2D41e8%2D9147%2D78e309fc4093)

**Comment by edwargl7** [comment]
Se finaliza la Issue con la preparación previa, se socializa el avance con el líder del proyecto y se concluye realizar la presentación presencial de parte del equipo técnico para garantizar la fluidez y solución de dudas de una forma más fácil.
