### ISSUE TITLE
Integración cargue masivo actividades de una auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#257]
Se requiere realizar el diseño de la plantilla XLSX para el cargue de actividades.

**Sub Tareas**

- [x] Diseño excel con los campos de actividades.

**Criterios de aceptación**

- [x] Formato XLSX e integración.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza formato xlsx para cargue masivo de actividades

[cargue masivo actividades.xlsx](https://github.com/user-attachments/files/18053980/cargue.masivo.actividades.xlsx)


 https://github.com/user-attachments/assets/bdd0b1cc-6dce-424b-ac69-1b53193a44f4

**Comment by edwargl7** [comment]
Se continuará en la Issue #317,
