### ISSUE TITLE
Integración flujo de aprobación o rechazo del plan por parte del jefe

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#258]
Se requiere realizar la integración de aprobación o rechazo del jefe de la oficina de control interno al plan anual de auditoría.

**Sub Tareas**

- [x] Integración de users.service para obtener [persona_id]()
- [x] Integración rechazo con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) (registro de observaciones) microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).
- [x] Integración aprobación con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Integración flujo de aprobación o rechazo del plan por parte del jefe**

>[!NOTE]
> Integración de users.service para obtener persona_id

```ts
this.userService.getPersonaId().then((usuarioId) => {
      this.usuarioId = usuarioId;
});
```

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Servicio de alertas
> - Registro en plan estado cuando se rechaza una auditoria anual 

Variables de entorno para el manejo de estados
```ts
PLAN_ESTADO: {
    EN_BORRADOR_ID: int,
    EN_REVISION_JEFE_ID: int,
    APROBADO_JEFE_ID: int,
}
```

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Alertas acorde al color del sistema

![image](https://github.com/user-attachments/assets/5f1eefbc-be6e-4454-9a6e-32143cba900e)

**Comment by edwargl7** [comment]
Buena implementación y apoyo para ajustes de estilos.
