### ISSUE TITLE
Mockup Tablero de control de auditorías

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#261]
Se requiere realizar el diseño del tablero de control de auditorías.

**Sub Tareas**

- [x] Diseño de tablero de control.

**Criterios de aceptación**

- [x] Mockup con el diseño del tablero de control.
- [x] Presentación al usuario.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en diseño de tablero de control para su implementación en el módulo de inicio del sistema SÍSIFO V2

![Image](https://github.com/user-attachments/assets/686a5b03-2981-4b3f-9609-4a5629e3b88b)


Saludos.

**Comment by edwargl7** [comment]
Revisar alternativas que empleen en la oficina por favor. (Metabase).

**Comment by jcmurilloa** [comment]
@cjgonzalezp por favor tener en cuenta las diferentes herramientas como alternativas de desarrollo, para proyectar un Mockup mas aterrizado al sistema.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presentará y validará con el equipo de funcionamiento como poder implementar el tablero de control en el módulo de inicio para que funcione como una herramienta de gestión de la información que monitoriza, analiza y muestra de manera visual los indicadores clave de desempeño, métricas y datos fundamentales para hacer un seguimiento del estado de las auditorías y planes de mejoramiento.

![Image](https://github.com/user-attachments/assets/f2fa3fc8-c263-45df-ab41-0928f3aa0d5d)


**Enlace mockup guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EhUC_iuJcTRGvZQ7iODCkY8BIHewZqiEmTe77EbB0nnG2w?e=hRKoeY

Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, estaremos atentos al resultado de la consulta con funcionamiento, con el fin de refinar estaremos atentos valiosa herramienta para el sistema.

**Comment by cjgonzalezp** [comment]
Buen día,

Se consulta con el equipo de funcionamiento si en la oficina de la OATI usan herramientas que nos sean útiles y cumpla con el requerimiento solicitado por el cliente para la implementación del tablero de control en el sistema Sísifo.

Cristian Alape nos informa lo siguiente:

Sí, en efecto, ese problema ya se ha resuelto antes. Nosotros contamos con dos herramientas para la creación de tableros de control:

1. **Knowage**:

- Es una herramienta de inteligencia institucional.
- Aunque está más enfocada en temas de reportes, también funciona para la creación de tableros.

2. **Metabase**:

- Es una herramienta utilizada a un nivel más gerencial.
- Es la que usa el jefe para visualizar resultados y otros análisis.

Respecto a cómo implementar estas herramientas dentro de los sistemas, alguna vez vi que lograron integrarlas en una aplicación web. Si no me equivoco, lo implementaron en SGA2. Sin embargo, no estoy seguro si también lo hicieron en ARCA2, ya que no lo recuerdo con claridad.

Con lo comentado por Cristian Alape, nos da claridad y una ruta por donde se podría realizar la implementación del tablero de control. En una siguiente issue se revisará y continuará investigando la mejor opción que sea funcional y cumpla con el objetivo de lo requerido.


Saludos.

**Comment by jcmurilloa** [comment]
Excelente investigación @cjgonzalezp
