### ISSUE TITLE
Diseñar el mockup de vista de registro del módulo del plan de mejoramiento. Rol Auditado

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#263]
Se requiere realizar el diseño del mockup de las diferentes vistas del módulo del plan de mejoramiento. Parte I

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos
- [x] Presentar el mockup al equipo SoS
- [ ] Realizar ajustes según comentarios del equipo SoS
- [ ] Presentar al equipo el mockup definitivo 

**Criterios de aceptación**

- [ ] Mockup aprobado por equipo SoS
- [ ] Diseño documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se diseña mockup inicial del módulo plan de mejoramiento>>registrar plan. 

Este módulo sería la primera fase donde la dependencia auditada deberá registrar las acciones a desarrollar para suplir los hallazgos encontrados en la ejecución de la auditoría. 

El sistema deberá generar el formato **EC-PR-003-FR-005 Plan de mejoramiento** a partir del formulario diligenciado y tendrá un flujo de aprobación por parte del rol auditor para dar inicio al plan.

![Image](https://github.com/user-attachments/assets/f7898369-878a-408e-9c90-619a8bdc6d5f)

**Enlace documentos guardado en OneDrive en la carpeta del proyecto SÍSIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et7XvruLX0JLjmXehXAWD4MBPj4OoKC-UCpnqRa8pd-XIw?e=O3GyDf


Saludos.

**Comment by edwargl7** [comment]
Refinar las opciones de responsable para en dado caso que realicen la búsqueda por el documento de identidad para evitar tener que filtrar y agrupar por grupo de trabajo de la dependencia.

Definición pendiente de los indicadores.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza ajuste solicitado.

<img width="517" alt="Image" src="https://github.com/user-attachments/assets/37487282-a103-4509-bb17-16c8071353d4" />


**Enlace documento guardado en OneDrive en la carpeta del proyecto**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et7XvruLX0JLjmXehXAWD4MBPj4OoKC-UCpnqRa8pd-XIw?e=C4Sydj


Saludos.
