### ISSUE TITLE
Creación mockup submódulo consulta general gestión de auditorías

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#265]
Se requiere realizar el diseño de mockup del módulo de consulta general de registro de auditorías para ser consultado por cualquier rol de la oficina de control interno

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos
- [x] Presentar el mockup al equipo SoS
- [x] Realizar ajustes según comentarios del equipo SoS
- [x] Presentar al equipo el mockup definitivo para presentar al cliente
- [x] Presentar al cliente para su aprobación

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS
- [x] Diseño documentado
- [x] Mockup aprobado por cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño de mockup del módulo de consulta general de auditorías en todas las fases de la misma, para los usuarios de la oficina de control interno

![Image](https://github.com/user-attachments/assets/350eff6c-a167-41e9-bbb5-9ea8bf39d1a6)


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp, pendiente solo aprobar por cliente!

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta el mockup del submódulo de consulta general al cliente y se recibe aprobación para proceder al desarrollo. La aprobación del mockup queda documenta bajo el acta de reunión No. 158/2024 

**Enlace acta de reunión guardado en OneDrive en la carpeta del proyecto Sísifo V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtW7SdqNSONOjRmh04Bn_LIBXqXWB7fOoIzo2rLPqGqj1w?e=OAiPaU


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp
