### ISSUE TITLE
Despliegue microservicio cargue masivo mid serverless

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#268]
Se requiere realizar el despliegue del microservicio [cargue_archivo_mid_serverless](https://github.com/udistrital/cargue_archivo_mid_serverless) en ambiente de pruebas.

**Sub Tareas**

- [x] Ajustes función de procesamiento de cronograma_ids.
- [ ] Despliegue microservicio.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Criterios de aceptación**

- [x] Documentación resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Ajustes

Se realizan los cambios para la key de cronograma_ids, asi mismo se cambia el nombre de "nombre_columnas" por "column_group"

![Captura de pantalla 2024-11-12 a la(s) 10 09 32 p m](https://github.com/user-attachments/assets/d5f77464-89d7-49ee-af7b-aa940f49253f)

Se agrega al código la eliminación de espacios vacíos externos en los textos de las celdas del dataFrame

![Captura de pantalla 2024-11-12 a la(s) 10 08 45 p m](https://github.com/user-attachments/assets/10b019b3-cfc1-4e32-b051-84f8dc7bd87d)

![Captura de pantalla 2024-11-12 a la(s) 10 09 13 p m](https://github.com/user-attachments/assets/542481b2-1b08-43c5-9003-a5874a130087)

Se realiza la prueba para la verificación de los espacios vacíos en los textos

![Captura de pantalla 2024-11-12 a la(s) 10 07 16 p m](https://github.com/user-attachments/assets/90b3cfc6-09f0-4b16-8547-f7a5c3c38e9d)

![Captura de pantalla 2024-11-12 a la(s) 9 46 27 p m](https://github.com/user-attachments/assets/e79b287b-a3d7-4d38-9aae-ddc73f877845)

**Comment by alexhrr** [comment]
### Mapping column_group

Se modifica la función get_columns y se agrega el mapping para los valores que se agregan de las columnas:

![Captura de pantalla 2024-11-13 a la(s) 12 02 47 p m](https://github.com/user-attachments/assets/e4acc6c4-8a0b-4524-b818-ec9a6a07fd3f)

![Captura de pantalla 2024-11-13 a la(s) 12 03 25 p m](https://github.com/user-attachments/assets/4b7842b3-a7ef-42fb-8f40-b3c1803a2322)

Se envía una prueba de mapping para asignar un número a los meses:

![Captura de pantalla 2024-11-13 a la(s) 11 41 39 a m](https://github.com/user-attachments/assets/b05ec20e-7615-4c82-a515-16f09fdfac09)

Se observa en el payload el resultado con los números asignados a cada mes

![Captura de pantalla 2024-11-13 a la(s) 12 02 14 p m](https://github.com/user-attachments/assets/826d657f-3a67-4f30-b6bf-75371ff6d1cf)

**Comment by edwargl7** [comment]
Aprobado PR, muy buen trabajo. Se aprovecha la Issue para las implementaciones adicionales, no se puede cubrir las pruebas dado que no se resolvió la solicitud de despliegue.
