### ISSUE TITLE
Implementación documentos del plan en el microservicio CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#269]
Se requiere realizar el diseño e implementación del CRUD de documentos del plan anual de auditoría en el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).

**Sub Tareas**

- [x] Diseño de tabla que permita almacenar documentos registrados en parámetros CRUD asociados al plan (evaluar en el diseño si la tabla puede almacenar los de la auditoría o si se requiere una tabla separada), Además almacene los ids de nuxeo para su posterior consulta.
- [x] Implementación de los controladores para el CRUD de documentos.
- [x] Implementación pruebas de integración.
- [ ] Integración con el almacenamiento del plan generado en PDF con el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [ ] Documentación avances en implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se diseña primera version para coleccion "documento"
![Image](https://github.com/user-attachments/assets/16a01432-8af7-42cf-adcc-d3e587ff52ca)

**Comment by jucastro94** [comment]
se desarolla controller, service, dtp y schema para coleccion documento

![Image](https://github.com/user-attachments/assets/9e79d622-33bf-40c5-98f2-7b83c8f9eae4)
![Image](https://github.com/user-attachments/assets/0a338fac-e706-44df-8e41-c02e526f201f)
![Image](https://github.com/user-attachments/assets/9d6b223e-fede-4d87-a29d-7dbaefcdb00c)
![Image](https://github.com/user-attachments/assets/a73e30e1-0de2-48f5-877a-87d1f15ed1bf)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales
POST

![Image](https://github.com/user-attachments/assets/2eab9bfe-ce26-42f2-9109-abeca37a6a64)
![Image](https://github.com/user-attachments/assets/081cfb84-7bad-4fef-8667-827bb477704d)
![Image](https://github.com/user-attachments/assets/9f965106-e000-4c7d-aa54-61edd8c21e3c)
![Image](https://github.com/user-attachments/assets/0eb2a50c-0584-40d4-aa62-cbea5574658a)

---

GET

![Image](https://github.com/user-attachments/assets/3e314f19-cfeb-4b20-b0ca-ace161fbe83c)

query params

query
![Image](https://github.com/user-attachments/assets/3133bf53-7289-4cea-8ef5-ba723a911ec3)
![Image](https://github.com/user-attachments/assets/e6d83b02-7cbd-48ba-821c-d56e4cfa5261)

fields
![Image](https://github.com/user-attachments/assets/3ca38888-5ee5-41f3-99ce-163230169d22)

order y sortby
![Image](https://github.com/user-attachments/assets/09a6f6c7-7b3b-42ed-b3e4-7b255a3244ee)

limit y offser
![Image](https://github.com/user-attachments/assets/e02dcde5-598a-4b4d-b0d4-09bb4c2fa487)

---

GET ONE

![Image](https://github.com/user-attachments/assets/386a1eaa-c51a-4a10-a002-60204742cb0a)

---

PUT
![Image](https://github.com/user-attachments/assets/44dee5f8-56d2-412a-bca4-36f093195254)
![Image](https://github.com/user-attachments/assets/72d39aa8-6a45-4463-ad1e-5e4b4b872adf)

---

DELETE
![Image](https://github.com/user-attachments/assets/0fa24cec-8a88-4856-9da5-0f9e2d5bb3fd)
![Image](https://github.com/user-attachments/assets/1e68e9aa-f125-4872-b36c-5a73d119619f)

**Comment by jucastro94** [comment]
se soluciona error con referencia_id
![Image](https://github.com/user-attachments/assets/9abcd146-d356-4d9c-9bb2-98c7183a0fd6)

**Comment by jucastro94** [comment]
qe realiza implementacion de pruebas de integracion
![Image](https://github.com/user-attachments/assets/3cf3e96c-8fb2-493a-bfa0-c7faf819a837)


esta pendiente a correccion de errores
![Image](https://github.com/user-attachments/assets/f8b1426f-8c37-44e8-90f3-7ba48d122408)
![Image](https://github.com/user-attachments/assets/8d406feb-831e-4387-a9eb-c5d9362aad96)

**Comment by jucastro94** [comment]
se solucionan errores en pruenas de integracion, se realiza merge de develop y solucionan conflictos

![Image](https://github.com/user-attachments/assets/cc0d8a6a-de1e-46cc-87b3-b1ab084bc721)
![Image](https://github.com/user-attachments/assets/ce7754c6-012a-470e-8f9d-da3176a08625)

**Comment by edwargl7** [comment]
Muy buen trabajo. Se finaliza la Issue y la integración faltante se trabajará en una nueva Issue.
