### ISSUE TITLE
Implementación aprobación secretario microcliente plan anual auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#270]
Se requiere realizar la implementación del encadenamiento de modales cuando el secretario aprueba.
![image](https://github.com/user-attachments/assets/a0da869e-a64a-4c86-8b60-4cd6778cd71e)
![image](https://github.com/user-attachments/assets/7ed65b34-94ac-44bd-aefb-7b250b02b885)

**Sub Tareas**

- [x] Maquetación flujo de aprobación del secretario.
- [x] Integración carga de acta con gestor documental.
- [x] Integración rechazo con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) (registro de observaciones).
- [x] Integración aprobación con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Implementación aprobación secretario microcliente plan anual auditoria**

>[!NOTE]
> - Cambios en la interfaz de revisión
> - Componente de revisión secretario

![image](https://github.com/user-attachments/assets/73c8864c-c739-4994-8d15-102b3af8cd94)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Flujo de aceptación o rechazo por parte del secretario

Nueva variable de entorno para aprobado por secretario
```ts
  PLAN_ESTADO: {
    EN_BORRADOR_ID: 6790,
    EN_REVISION_JEFE_ID: 6791,
    APROBADO_JEFE_ID: 6792,
    APROBADO_SECRETARIO_ID: 6794,
  },
```

Estilos sujetos a cambios
![image](https://github.com/user-attachments/assets/b8f16ae2-9c55-4cd8-ab15-535c910d49a2)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Arreglos de estilos, maquetación de core arreglada
> - Propuesta de componentes base

**Comment by edwargl7** [comment]
Muy buen trabajo, por favor resolver conflictos. Muchas gracias.
