### ISSUE TITLE
Maquetación formulario de registro de información de la auditoría en la fase de planeación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#272]
Se requiere realizar la maquetación del formulario de registro de información de una auditoría en la fase de planeación.
![image](https://github.com/user-attachments/assets/04b87f2e-58d4-46d5-8205-01c24357f9af)
![image](https://github.com/user-attachments/assets/e346e061-4497-4595-b6a9-7543b4d25239)
![image](https://github.com/user-attachments/assets/f164b13a-9b70-4575-901d-f856c7a6e2c3)
![image](https://github.com/user-attachments/assets/101c9841-3fae-4e78-acf7-81ecf61bec4b)

**Sub Tareas**

- [x] Maquetación formulario de registro de información complementaría de una auditoría.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultado de la maquetación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
## Avances en la maquetación

### Información

![image](https://github.com/user-attachments/assets/1087cd1f-a29b-4457-ac89-cde6f88a515c)

### Actividades

![image](https://github.com/user-attachments/assets/b5c06f5e-678e-4b3a-ab00-27e152587eec)

### Recursos

![image](https://github.com/user-attachments/assets/64054f98-6ce8-4f17-81c7-225ac9026341)

**Comment by CristianCGutierrezG** [comment]
#### **plan_anual_auditoria_crud (Backend)**:
- **Validación de Planes Activos**:
  - Se ha modificado el endpoint **POST** del servicio `plan-auditoria` para validar únicamente los **planes activos** antes de realizar la creación o modificación del plan.

![image](https://github.com/user-attachments/assets/e3dc479d-62d7-4c24-90ce-95e3f5e6696e)


- **Adaptación a Cambios en el Microfrontend**:
  - Se ha actualizado el microservicio `plan_anual_auditoria_crud` para **adaptarse a los cambios de nombres de campos** en el servicio, asegurando que los datos se procesen correctamente con el frontend en el componente de consltar-plan.

![image](https://github.com/user-attachments/assets/971088c5-0970-4a5c-baf8-227771ac0cf4)


#### **plan_anual_auditoria_mf (Microfrontend)**:
- **Ajustes en la Lógica del Stepper**:
  - Se ha ajustado la lógica del manejo de formularios en el componente **stepper** para asegurar que la **información de cada formulario** se envíe de manera **individual** y **correcta** en cada paso del proceso.

- **Nuevo Componente `documentos-anexos-auditoria`**:
  - Se ha creado el componente **`documentos-anexos-auditoria`** para gestionar el **cuarto paso del stepper**
  
![image](https://github.com/user-attachments/assets/cdacf4a3-dc44-4d65-9775-a4a6697a9704)

**Comment by edwargl7** [comment]
Revisar con ayuda de @cjgonzalezp si es necesario mantener o se puede remover la columna de papeles de trabajo del paso 2 actividades.

**Comment by edwargl7** [comment]
Muy buena documentación e implementación. Buena propuesta para el paso de documentos.
