### ISSUE TITLE
Consulta cambio de texto en el logotipo de Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#273]
Se requiere realizar la consulta y solicitud de actualización o generación del logotipo actualizando el texto. En el siguiente enlace se encuentra el logotipo actual  [logotipos_aplicativos_svg-sisifo.svg](https://github.com/udistrital/assets/blob/develop/logotipos_aplicativos_svg/sisifo.svg).

**Sub Tareas**

- [x] Consulta de proceso para solicitar la actualización del logotipo.
- [x] Validación nuevo diseño.

**Criterios de aceptación**

- [x] Documentación referente a la actualización del texto del logotipo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se está consultando con el equipo de funcionamiento el contacto para la creación del nuevo logo para el sistema.

**Se presentará la siguiente propuesta la cual solo cambiaría la descripción del sistema SISIFO V2**
![Image](https://github.com/user-attachments/assets/e081e4cf-cd19-4f7c-9cc5-1fcda546180f)



Saludos.

**Comment by jcmurilloa** [comment]
Por favor contactar @mantnicot, para refinamiento de logo y aprobación.

**Comment by jcmurilloa** [comment]
Cual es la actualidad de esta issue? hace falta comentar cual ha sido su respectiva evolución @cjgonzalezp

**Comment by cjgonzalezp** [comment]
Buen día Julián,

Tienes razón, dejo comentado que se solicitó revisión a la dependencia encargada de la propuesta de logotipo con la modificación que requería para la versión 2. Se recibió visto bueno y nos enviaron en logo en los formatos que se requieren para la implementación.

![Image](https://github.com/user-attachments/assets/eb0295ad-249e-4c1b-be34-9b9bda1ce2ff)

![Image](https://github.com/user-attachments/assets/b888d1b9-e479-47f9-930d-6a16a2d6ecd1)

**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/[Logotipo](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Logotipo?csf=1&web=1&e=QLfLud)?csf=1&web=1&e=QLfLud

Con esto se da por finalizada la issue #273 

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo, el logo compila lo que ofreceremos con la segunda versión del sistema.
