### ISSUE TITLE
Actualización Mockup adicionando temas del formato de solicitud de información

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#274]
Se requiere realizar la actualización del mockup que permita registrar los datos requeridos para la generación del formato de solicitud de información contemplando el apartado de temas.
![image](https://github.com/user-attachments/assets/ea6991e7-4a07-4804-8f43-30593f26fcaa)

**Sub Tareas**

- [x] Actualización del mockup con el apartado de temas.

**Criterios de aceptación**

- [x] Mockup actualizado y socializado al SoS.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza ajuste del mockup para la adición solicitud de información para la ejecución de la auditoría.

![Image](https://github.com/user-attachments/assets/fa9cfe33-6797-4da1-aa2c-7d5baefa8ef5)


**Enlace diseño actualizado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Mockups/M%C3%B3dulo%20Gesti%C3%B3n%20de%20Auditor%C3%ADa/Subm%C3%B3dulo%20Planeaci%C3%B3n/Subm%C3%B3dulo%20Auditor%C3%ADas%20Internas?csf=1&web=1&e=vYTWfd 

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp , pendiente únicamente añadir la opción de añadir más temas.
