### ISSUE TITLE
Preparación presentación estado actual Sísifo al usuario final - Montaje de servicios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#276]
Se requiere realizar el montaje de todos los servicios requeridos para la presentación del estado actual de Sísifo.

**Sub Tareas**

- [x] Montaje de los servicios de Sísifo v2.
- [x] Organización de escenario para la presentación.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación resultado de pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Montaje de Servicios - Sísifo V2

#### Servicios actualmente instalados:

1. **auditoria_plan_mejoramiento_root_mf**
   - **Commit local**: `feat:root_mf con rutas para local`

2. **plan_anual_auditoria_crud**
   - **Commit local**: `Merge pull request #11 from udistrital/feature/validación_unico_plan`

3. **plan_anual_auditoria_mf**
   - **Commit local**: `feat: Maquetación formulario de registro de información de la auditoría en la fase de planeación` 
   - Issue relacionado: `udistrital/sisifo_documentacion#272`

#### Montaje de nuevos servicios:

4. **plan_anual_auditoria_mid**
   - **Commit local**: `Merge pull request #2 from udistrital/feature/implementacion-cargue-masivo`

5. **cargue_archivo_mid_serverless**
   - **Commit local**: `Merge pull request #6 from udistrital/feature/validacion-espacios`

---

#### Verificación del servicio:
- Se realizó un **pull** de los últimos cambios en el **plan_anual_auditoria_mf** y se **comprobó el funcionamiento correcto** del servicio.

**Comment by CristianCGutierrezG** [comment]
Se realiza un pull de los nuevos cambios en `plan_auditoria_crud` y `plan_auditoria_mf`, seguido de las respectivas pruebas para verificar el correcto funcionamiento de cada servicio y sus componentes.

Se prueba el acceso a los datos utilizando el servicio `plan_auditoria_crud` desplegado.

Se revisa el flujo y los componentes a presentar en la próxima demostración.

**Comment by edwargl7** [comment]
**Servicios de Sísifo:**
_**Microclientes**_
- 
- Root ✅ 
- Plan anual auditoria mf ✅ 

_**Microservicios**_

- Parámetros CRUD (Ambiente pruebas) 🌐 
- Plan anual auditoria CRUD
- Plan anual auditoria MID
- Plantillas MID
- Plantillas Serverless CRUD
- Renderizado
- Cargue masivo serverles MID

**Comment by CristianCGutierrezG** [comment]
Se realiza un pull de los nuevos cambios en `plan_auditoria_mid` y `plan_auditoria_mf`.

Se ejecutan pruebas funcionales del componente de cargue masivo, y la correcta conexión con el servicio `plan_auditoria_mid` y el `cargue_archivo_mid_serverless`.

**Comment by CristianCGutierrezG** [comment]
### Finalización del Montaje de Servicios y Presentación al Cliente

#### Servicios Montados para la Presentación
Se completaron los montajes de los servicios necesarios para la presentación del estado actual de **Sísifo V2**. Los módulos implementados y configurados incluyen:

1. **Módulo de Programación**: 

![image](https://github.com/user-attachments/assets/e0eb1c5c-26a3-4059-a02b-f659c14a839f)
   
2. **Cargue Masivo**:

![image](https://github.com/user-attachments/assets/33a52991-3e60-45ca-a87e-3fb207eadd19)
   
3. **Visualización de PDFs**:

![image](https://github.com/user-attachments/assets/12e29486-2c48-4206-93c4-8944bf2b31c9)

4. **Módulo de Usuarios**:

![image](https://github.com/user-attachments/assets/6ad28706-40b6-427c-8ba9-5c6ae96aa991)


---

### Presentación al Cliente

 Se presentó el flujo del sistema, abarcando los módulos y funcionalidades implementadas.

**Comment by edwargl7** [comment]
Muy buen trabajo, se realizó la presentación a parte del equipo de usuarios con los que se levantaron los requerimientos.
Con la participación del equipo de desarrollo (@jucastro94, @CristianCGutierrezG y @alexhrr ) el analista @cjgonzalezp y los usuarios Henry y Ricardo.
