### ISSUE TITLE
Implementación spinner de carga en cada consulta

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#277]
Se requiere realizar la implementación del progress-spinner en cada una de las peticiones y transiciones del módulo del plan anual de auditoría - programación en [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf). Adicional, de ajustes de estilos a los modales de eventos de este mismo módulo.

**Sub Tareas**

- [x] Implementación spinner.
- [x] Implementación interceptor.
- [x] Ajustes de estilos modales del módulo de programación del PAA.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultados de las pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Implementación spinner de carga en cada consulta**

>[!NOTE]
> - Spinner implementado con interceptor


https://github.com/user-attachments/assets/4dc03342-3a4d-47ce-8d5e-6e2c97ec38cd

```ts
export const SpinnerIntercerptor: HttpInterceptorFn = (req, next) => {
  const spinnerSvc = inject(SpinnerService);
  spinnerSvc.show();
  return next(req).pipe(finalize(() => spinnerSvc.hide()));
};

```

**Comment by edwargl7** [comment]
Muy buen trabajo, pendiente resolver conflictos del PR.
