### ISSUE TITLE
Apoyo preparación presentación del estado de Sísifo al cliente

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#278]
Se requiere realizar el apoyo en el montaje de los servicios requeridos para la presentación de Sísifo v2 al usuario final.

**Sub Tareas**

- [x] Apoyo en montaje y ajustes requeridos.

**Criterios de aceptación**

- [x] Descripción de apoyo realizado para el montaje de los servicios.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Apoyo en el Montaje de Servicios

#### Instalación y configuración

Se realizó una reunión de trabajo con @alexhrr  para llevar a cabo la instalación de los siguientes servicios:

1. **Plan_anual_auditoria_mid**
   - Se ejecutó el proyecto localmente para asegurar su correcta instalación y funcionamiento.
  
![image](https://github.com/user-attachments/assets/2311cad3-d324-467b-85f3-246630855aaa)


2. **cargue_archivo_mid_serverless**
   - **Requisitos instalados**:
     - Python versión 3.9
     - AWS SAM CLI
   - **Proceso de configuración**:
     - Ejecución del proyecto en local.
     - Pruebas realizadas mediante **Postman**.
   
![image](https://github.com/user-attachments/assets/22f0316a-a449-4289-8940-19c74491f8a8)
![image](https://github.com/user-attachments/assets/f40e5e82-62d3-4ec4-a1b0-12d44444f262)

**Comment by edwargl7** [comment]
Se ajusta el orden del selector de vigencias de la vista de creación del plan.

**Comment by CristianCGutierrezG** [comment]
Junto con @alexhrr se completa la integración y pruebas exitosas del componente de cargue masivo, asegurando su funcionamiento al usar la VPN.

![image](https://github.com/user-attachments/assets/88c25193-03bc-4a06-a746-86b2b06a68b1)

![image](https://github.com/user-attachments/assets/bea29288-9e4d-44fd-b9ea-925060b8ddb9)

Con los cambios implementados por @jucastro94 , se logra la obtención de los datos para las tablas de consulta y registro de auditorías desde el servicio `plan_auditoria_mid`, garantizando que los datos se obtienen correctamente desde el servicio de parámetros.

![image](https://github.com/user-attachments/assets/6961698a-e42c-4b47-b14b-4d2fe81857c7)

**Comment by jucastro94** [comment]
se modifica referencia a campos de plan auditoria mid en los services, para snakeCase
![Image](https://github.com/user-attachments/assets/55a2192d-0789-4cab-8b48-f0c79d5a02c5)

**Comment by alexhrr** [comment]
### Apoyo montaje de servicios

Se realizan reuniones junto a @CristianCGutierrezG para el apoyo en el montaje de los recursos necesarios para la ejecución del cargue masivo y posteriormente para su ejecución, se verifican y solucionan los errores presentados en la ejecución y queda funcionando correctamente en el equipo.
Se realiza una breve explicación del funcionamiento y flujo general del servicio, tambien del cargue de la plantilla xlsx necesaria.

Se asiste a la reunion previa a la presentacion junto al equipo para apoyar en la verificación del funcionamiento de los servicios implementados y tambien se apoya en la ejecución del modulo de gestión de usuarios que se va a presentar, asi mismo se explica el funcionamiento general del modulo para su respectiva presentacion.

**Comment by edwargl7** [comment]
Muy buen trabajo, se realizó la presentación a parte del equipo de usuarios con los que se levantaron los requerimientos.
Con la participación del equipo de desarrollo (@jucastro94, @CristianCGutierrezG y @alexhrr ) el analista @cjgonzalezp y los usuarios Henry y Ricardo.

Gracias por el trabajo realizado se alcanzó la meta planteada.
