### ISSUE TITLE
Integrar módulo de planeación del PAA con el microservicio CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#279]
Se requiere realizar la integración del formulario de registro de información asociado a cada auditoría con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).
![image](https://github.com/user-attachments/assets/c91ccbfd-3424-4079-a864-8f7ab1a92f45)
![image](https://github.com/user-attachments/assets/957b92d1-5a88-4158-a9e9-5039d3b83188)

**Sub Tareas**

- [x] Integración registro de información paso de información.
- [x] Integración registro de información paso de recursos.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Integrar módulo de planeación del PAA con el microservicio CRUD**

>[!NOTE]
> Interfaz mejorada componente editar auditoria, manejo responsive


![image](https://github.com/user-attachments/assets/0f100502-f607-4bd6-86d3-db1651d93d72)

---

Vista responsive
![image](https://github.com/user-attachments/assets/b71aed41-379d-4f15-9377-2daef63c12c3)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Integrado con el back para la edición
> Conexión de api parámetros con form dinámicos

>[!WARNING]
> Hay que revisar el form dinámico para el manejo de eventos y escalabilidad de la etiqueta select

**Comment by edwargl7** [comment]
Muy buena implementación y ajustes realizados al diseño. Se revisará con @cjgonzalezp si es necesario dejar el título "Paso x" o si puede  omitir ese título.
