### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión requerimientos con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#28]
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión de requerimientos con cliente

**Sub Tareas**

- [x] Concertar reunión de requerimientos con el cliente
- [x] Desarrollar la reunión exploratoria
- [x] Diligenciamiento del formato de historias de usuario con el cliente
- [x] Aprobación del formato de historias de usuario
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrollo una primera sesión con el fin de revisar los parámetros y campos necesarios en el módulo de configuración para el desarrollo del sistema SISIFO V2 el día 27 de mayo de 2024 en horario de 10:00 am a 10:30 am, pendiente culminar el levantamiento del acta de reunión.

Adicionalmente, se agenda reunión exploratoria con el cliente de una hora el día 31 de mayo de 2024 a las 2:00 pm para levantamiento de requerimientos.

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan correcciones de acuerdo a sugerencias. Queda pendiente la recolección de las firmas de los participantes.

**Link documento guardado en OneDrive en la carpera del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqghPecbcjZMjaJ44gAKLJQBMtThSKupftXPzBwtOq_jDg?e=l1DShg

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión # 038/2024 de la segunda sesión con el equipo de la Oficina de Control Interno desarrollada el día 31 de mayo de 2024. Pendiente recolectar firmas de los participantes.

**Link documento guardado en OneDrive en la carpera del proyecto correspondiente**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtSJY2ZlBYVIl0MebZ1wfbAB8a_JyB2pOd8gHiJ9L-SbMg?e=apnviS

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se recolectan firmas de las actas 035/2024 y 038/2024 y se da por finalizado la issue #28

**Enlace de los documentos cargado en OneDrive en la carpeta del proyecto SISIFO V2**
**Acta 035/2024** 
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqghPecbcjZMjaJ44gAKLJQBMtThSKupftXPzBwtOq_jDg?e=wqUkkt

**Acta 038/2024**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtSJY2ZlBYVIl0MebZ1wfbAB8a_JyB2pOd8gHiJ9L-SbMg?e=ShNPiF

Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp!
