### ISSUE TITLE
Maquetación vista de consulta de auditorías en la fase de planeación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#280]
Se requiere realizar la maquetación de la vista de consulta de auditorías en la fase de planeación.
Microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).

![image](https://github.com/user-attachments/assets/a487449e-ad28-4bd3-9b72-b03cb6d3ef51)

**Sub Tareas**

- [x] Maquetación de la vista de consulta.
- [x] Integración consulta de auditorías por vigencia.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Los siguientes campos todavía no se integran por lo tanto no es requerido mostrar los valores en la columna.
![image](https://github.com/user-attachments/assets/640b457a-0ef7-4945-a134-d6aab612384e)

**Comment by edwargl7** [comment]
![image](https://github.com/user-attachments/assets/4e77e812-932d-49ef-a352-02aa78c15521)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Controlador obtener auditorias por vigencia
> Componentes para la visualización de las auditorias por vigencia


https://github.com/user-attachments/assets/c2a0f5ac-38ae-431d-aa70-d79c09af225e

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Integración correcta con el mid, para usar el endpoint ya diseñado 

Vista responsive
![image](https://github.com/user-attachments/assets/fb6215bd-68e9-439b-858b-392bae733d16)

**Comment by edwargl7** [comment]
Muy buena documentación e implementación de modales al no encontrar planes en la vigencia consultada. Pendiente resolver conflictos del PR. Se resuelve PR del MID.
