### ISSUE TITLE
Asociación plan auditoría a las auditorías del cargue masivo

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#281]
Se requiere realizar el ajuste para permitir que mediante el campo complement se asocien las auditorías del cargue masivo y la validación de que se visualicen las auditorías cargadas masivamente en el paso de auditorías.

**Sub Tareas**

- [x] Ajuste mf para envío de id del plan.
- [x] Ajuste en el ms mid para registro con dato complementario.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se actualiza la rama develop del mf y se encuentran algunas diferencias en la funcionalidad del cargue masivo. 
Se inicia el ajuste para incluir las funcionalidades en la rama actual de develop

![Captura de pantalla 2024-11-19 a la(s) 8 43 49 a m](https://github.com/user-attachments/assets/706b48a3-de51-4f52-93a0-aeb07b15e3d9)

![Captura de pantalla 2024-11-19 a la(s) 8 44 42 a m](https://github.com/user-attachments/assets/52c58669-dcd0-48b3-807e-ccc3f76dee38)

Se realiza la revisión del envío del id del plan de auditoria al componente del cargue masivo

**Comment by alexhrr** [comment]
Se ajusta el código en el mf para que tome el id del plan de auditoria y sea enviado al modal de carga masiva para que las auditorias a registrar pertenezcan al id del plan de auditoria.
Así mismo se envía el id como complemento a la lambda para ser registrado en el crud como parte del payload.

Se crea el xlsx con la información necesaria para crear las auditorias:

![Captura de pantalla 2024-11-19 a la(s) 3 36 54 p m](https://github.com/user-attachments/assets/a2bdd3b3-c10a-42fd-9608-dab934d1dbaf)

Se toma un plan vacío con el id '6737705bb8a3b56f7240db71' y se selecciona la opcion de cargue masivo

![Captura de pantalla 2024-11-19 a la(s) 1 12 52 p m](https://github.com/user-attachments/assets/9c024801-6601-440c-8b5d-ffe954e6bb89)

Se selecciona el archivo xslx con la plantilla y se sube:

![Captura de pantalla 2024-11-19 a la(s) 3 08 25 p m](https://github.com/user-attachments/assets/f7e9bd2c-2998-484d-a5b7-1cf19e4122f2)

La lambda toma el archivo, lo procesa y crea el payload incluyendo en el complement el id del plan:

![Captura de pantalla 2024-11-19 a la(s) 12 59 39 p m](https://github.com/user-attachments/assets/c0e2fe9d-b42a-4213-877f-345bd1706d44)

Por la consola del navegador se observa los registros creados:

![Captura de pantalla 2024-11-19 a la(s) 1 13 37 p m](https://github.com/user-attachments/assets/14082b04-9444-4335-b5de-abbb0aa1c6d5)

Se verifica en el mf la creación de las auditorias en el plan seleccionado:

![Captura de pantalla 2024-11-19 a la(s) 1 13 50 p m](https://github.com/user-attachments/assets/ebb51d32-5b6a-454a-becd-5cf7ee05772c)

Finalmente se verifican los registros en el crud, asociados al id del plan seleccionado:

![Captura de pantalla 2024-11-19 a la(s) 3 51 07 p m](https://github.com/user-attachments/assets/c25cf5c7-be46-4d86-8485-7161bf916bae)

**Comment by edwargl7** [comment]
Culminada integración, muy buen trabajo.
