### ISSUE TITLE
Integración registro de auditorías especiales con microservicio CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#282]
Se requiere realizar la integración entre el mf [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) y los microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) y el microservicio [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud).

![image](https://github.com/user-attachments/assets/358dcc6e-de55-4dfd-80f5-3ae05f000d23)

**Sub Tareas**

- [x] Integración parámetros CRUD para los selectores de tipo y cronograma.
- [ ] Integración selector de auditores de usuarios CRUD consultando los usuarios con rol auditor y auditor experto activo.
- [x] Integración con microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) para registro de auditoría nueva desde la vista de consulta.
- [x] Integración edición de auditoría para complementar los datos de la auditoría especial.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Integracion CRUD para los selectores

Se realizan los ajustes en el código para obtener los datos de parametros para los selectores:

![Captura de pantalla 2024-11-20 a la(s) 10 51 17 p m](https://github.com/user-attachments/assets/b9fd200f-e57b-414b-a21e-9644fa3455dd)

![Captura de pantalla 2024-11-20 a la(s) 10 50 53 p m](https://github.com/user-attachments/assets/21455fae-366f-4070-a2d5-19c8e4ec1e23)

![Captura de pantalla 2024-11-20 a la(s) 10 50 35 p m](https://github.com/user-attachments/assets/1a6f66cf-b19a-4ba0-a3cc-55471470476d)

Verificación del tipo de actividad:

![Captura de pantalla 2024-11-20 a la(s) 10 47 09 p m](https://github.com/user-attachments/assets/bb7f16b9-1686-4e73-8c6f-7f1971fd8479)

Verificación del cronograma:

![Captura de pantalla 2024-11-20 a la(s) 10 47 18 p m](https://github.com/user-attachments/assets/d9cb29c3-24ac-4e97-acdc-6c02069b249a)

Selección de datos:

![Captura de pantalla 2024-11-20 a la(s) 10 48 09 p m](https://github.com/user-attachments/assets/ebe61640-a760-4d0e-b239-b2dbd99d9a89)

**Comment by alexhrr** [comment]
Se continua con la implementación del crud para la creación y edición de auditorias especiales, se realiza la integracion de la edición de las auditorias especiales

![Captura de pantalla 2024-11-22 a la(s) 8 15 23 a m](https://github.com/user-attachments/assets/72cc391b-1e68-4fda-b7de-18e47a9b61b8)

Se listan las auditorias disponibles:

![Captura de pantalla 2024-11-22 a la(s) 8 15 37 a m](https://github.com/user-attachments/assets/1bc92b5e-b194-4140-ba6c-06de0bfac31e)

Se selecciona una y se cargan los datos al modal, se realiza la edición necesaria y se guarda:

![Captura de pantalla 2024-11-22 a la(s) 9 01 12 a m](https://github.com/user-attachments/assets/0ad2b693-4e5b-4621-ad28-d4c0be202dff)

**Comment by alexhrr** [comment]
### Creación de auditorias especiales

Se integra el crud y se traen los datos de parametros para los años, meses y evaluación.
Se selecciona el año para crear la auditoria:

![Captura de pantalla 2024-11-22 a la(s) 8 01 59 p m](https://github.com/user-attachments/assets/b3ea0aa2-888c-4180-bf18-64138b320030)

Se genera una auditoria inicial que se encuentra vacía, para que posteriormente en la edición se agreguen los datos necesarios:

![Captura de pantalla 2024-11-22 a la(s) 5 16 23 p m](https://github.com/user-attachments/assets/9cd97b37-4856-4cf1-b7db-0d371345caf4)

Se selecciona la opción de edición y aparece el modal para editar los datos de la auditoria:

![Captura de pantalla 2024-11-22 a la(s) 5 57 32 p m](https://github.com/user-attachments/assets/a0df27ff-6bae-4503-b212-b2bf537bb9cc)

Se agregan los parametros mediante los selectores según sea el caso ( titulo, evaluación y los meses)

![Captura de pantalla 2024-11-22 a la(s) 6 00 13 p m](https://github.com/user-attachments/assets/0e81f0ec-0478-4494-bfb3-e68862695cbe)

Guardan los datos y se genera el modal de confirmación asi como el modal de la creación:

![Captura de pantalla 2024-11-22 a la(s) 8 10 08 p m](https://github.com/user-attachments/assets/74abe385-bd4c-4e43-8af0-32e5d10f54db)

![Captura de pantalla 2024-11-22 a la(s) 8 10 42 p m](https://github.com/user-attachments/assets/0650e30d-5823-4244-b431-d2176f299ec4)

Finalmente queda actualizada la auditoria generada inicialmente:

![Captura de pantalla 2024-11-22 a la(s) 6 00 24 p m](https://github.com/user-attachments/assets/b606d746-527c-4da2-b2ef-a7518b2036ca)

Queda pendiente la implementación del mid para obtener el nombre de los meses y evaluación desde parametros, se genera error al ejecutar el mid.

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR.
