### ISSUE TITLE
Agregar vigencia a las auditorías - Auditorías sin plan

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#283]
Se requiere agregar el campo vigencia_id a la colección de auditorías dado que existen auditorías que no hacen parte de un plan pero que requiere conocerse la vigencia, por lo tanto, se requiere ajustar el controlador del microservicio  [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) con este nuevo campo obligatorio.

**Sub Tareas**

- [x] Actualización modelo de datos para agregar campo de vigencia_id a las auditorías.
- [x] Ajuste controladores de auditorías con el campo nuevo.
- [x] Actualización pruebas de integración.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se agrega campo vigencia_id a dto y schema
![Image](https://github.com/user-attachments/assets/5e4640f3-ca61-4e3a-9b7d-73dd4de59c83)
![Image](https://github.com/user-attachments/assets/eafeb3c8-393b-4bd8-9de0-a1fee4992acd)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/0c8fffd5-e9fb-4753-8d5d-dd96edd3b4a9)
![Image](https://github.com/user-attachments/assets/bd9461c1-9bf4-4c5a-bafb-b5f3c24601a3)


se actualizan pruebas de integracion
![Image](https://github.com/user-attachments/assets/5dc0adc3-4f3f-4e62-a08b-7f75d4dd6d19)
![Image](https://github.com/user-attachments/assets/80bcfc17-c8db-46c0-9681-093431109999)
![Image](https://github.com/user-attachments/assets/a3c17cf3-4473-43bf-88f8-a567112ad6c2)


se actualiza modelo de datos
![Image](https://github.com/user-attachments/assets/42eddf5a-53d2-4777-96e3-1e4c9d316541)

se carga modelo actualizado y se actualiza README
![Image](https://github.com/user-attachments/assets/9e6c91c2-27d2-4b0d-810e-5135ae548d6f)

**Comment by edwargl7** [comment]
Finalizada, muy buen trabajo.
