### ISSUE TITLE
Integración generación PDF PAA entre plantillas MID y MF plan anual de auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#284]
Se requiere realizar la integración entre plantillas MID y el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) y la integración con el gestor documental continuación de la Issue #248.

**Sub Tareas**

- [x] Integración plantillas MID y mf.
- [x] Integración para almacenamiento del PDF con el gestor documental.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se resuelve la integracion del enpoint para generar la el formato pdf con las auditorias segun el plan de auditoria

se realiza parche plantillas_mid main.ts para resolver el conflicto con CORS

```typescript
  app.enableCors({
    origin: 'http://localhost:4200', 
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE', 
    credentials: true, 
  });

```
![Image](https://github.com/user-attachments/assets/428eb2db-f29f-4956-98cf-59cd1c53d96e)

**Comment by jucastro94** [comment]
se realiza prueba funcional 
![Image](https://github.com/user-attachments/assets/5c8496ea-ba2d-42f9-882b-91b92a9df96d)
![Image](https://github.com/user-attachments/assets/2f1e5247-535a-48ca-9baf-6f86cf20ba19)
![Image](https://github.com/user-attachments/assets/ceb30d3b-7311-48a0-a685-acfddb0269dc)

**Comment by jucastro94** [comment]
se integra el guardado del formato pdf generado con gestor documentar
![Image](https://github.com/user-attachments/assets/8c806ced-61e7-477b-a9b7-1a065c384cff)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/02a9bba6-bbd8-4a62-84c9-3ebf4acfc2f8)

**Comment by jucastro94** [comment]
se presenta error local en plan auditoria mid 
![Image](https://github.com/user-attachments/assets/3490a0cb-497a-4654-b421-0d92917e19a3)

**Comment by edwargl7** [comment]
Muy buen trabajo, se presenta parte de la integración al usuario.
