### ISSUE TITLE
Implementación submódulo de asignación de auditorías

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#285]
Se requiere realizar la maquetación e integración de la asignación de auditorías a las auditorías del PAA. Integrando la consulta de usuarios por rol de la Issue #282.
![image](https://github.com/user-attachments/assets/66d77d41-e242-4e9f-9398-8265ae424aaa)

**Sub Tareas**

- [x] Maquetación del submódulo.
- [x] Integración selector de consulta de usuarios por rol microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid).
- [x] Implementación edición de asignación de auditores.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

- Issue #293.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza la maquetación inicial del submodulo de asignación de auditores tomando como base el modal para el registro de auditorias especiales 

![Captura de pantalla 2024-11-29 a la(s) 8 50 11 a m](https://github.com/user-attachments/assets/6a5ae732-a62f-4c55-8245-856ef53605de)

**Comment by alexhrr** [comment]
Se realiza la implementación de adición de auditores desde autenticación mid, asi mismo se ajustan los selectores para que se agreguen de forma dinamica, se prepara el documento a enviar al crud del paa.

https://github.com/user-attachments/assets/4a77f39e-1dc0-4b46-a946-50955d9592be

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelve el PR. Se debe agregar la funcionalidad que el auditor ya elegido no salga nuevamente en la lista de elegibles.
