### ISSUE TITLE
Implementación filtro de usuarios por rol

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#286]
Se requiere realizar la implementación de filtro de usuarios por rol en el servicio de usuarios CRUD y autenticación MID, donde retorne el nombre de los usuarios que cumplen ese críterio de consulta.

**Sub Tareas**

- [x] Implementación endpoint de consulta por rol.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza modificacion a la forma como se trabaja el query para que acepte varias claver del mismo tipo sin sobreescribirse, haceindo posible realizar el filtrado mediante queryparams

controller
![Image](https://github.com/user-attachments/assets/dc47de0a-f527-4e83-9fbf-07e717c16bf0)


modelo
![Image](https://github.com/user-attachments/assets/62804055-33b0-4060-af3c-3e0df36e57c1)

presenta error al no traer la data de los roles que se indican en el query
![Image](https://github.com/user-attachments/assets/b0d17475-be4c-4394-ade3-ff6482cdf970)

**Comment by edwargl7** [comment]
Se observa una buena implementación, se revisará en el siguiente sprint el error generado en las pruebas locales.
