### ISSUE TITLE
concertación, desarrollo y levantamiento del acta de sesión de muestra con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#287]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de muestra de avance del sistema con el cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se acuerda reunión con el usuario para la presentación de avances del sistema, para el dia 21 de noviembre de 2024 hora: 02:30 pm en la sede Paiba.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con cliente para la presentación de avances del sistema, en la reunión no pudo estar el Jefe de la Oficina de Control Interno por lo que se tuvo que presentar solo al equipo asignado para levantamiento de requerimientos.

El cliente nos solicita programar nuevamente la reunión con el Jefe Guillermo Alfonso el próximo jueves 28 de noviembre de 2024 hora: 09:30 am

**Pendiente la proyección del acta de reunión de la reunión desarrollada.**

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se proyecta acta de reunión No 151/2024 SÍSIFO Presentación avances del sistema, sesión desarrollada el pasado 21 de noviembre de 2024. Pendiente recolección de firmas de los presentes en la reunión

**Enlace documento guardado en OneDrive en la carpeta del proyecto SÍSIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20151%20-%202024%20S%C3%ADsifo%20-%20Presentaci%C3%B3n%20avances%20sistema?csf=1&web=1&e=gCCQZE


Saludos.

**Comment by jcmurilloa** [comment]
Hola @cjgonzalezp, agradezco me incluyas en los asistentes a la sesión, toda vez que estuve al tanto de su desarrollo y genere la respectiva intervención.

**Comment by cjgonzalezp** [comment]
Buen día Julián,

Si señor claro que sí, realizo ajuste al documento y se procede a recoger firmas de todos los participantes.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SÍSIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Actas%20de%20Reuni%C3%B3n/Acta%20151%20-%202024%20S%C3%ADsifo%20-%20Presentaci%C3%B3n%20avances%20sistema?csf=1&web=1&e=ULsG3V


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se da por finalizada la issue #287 con la recolección de firmas de los presentes en la sesión desarrollada y documentada bajo el acta No 151.

**Enlace documento guardado en OneDrive en la carpeta del proyecto Sísifo V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EnyrOmTXjtlBju5LhbFzzTwBxF_2eIo9pkGYkvh1idKZyA?e=gk3SNT

Saludos.
