### ISSUE TITLE
Construir diagrama modular y de procesos del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#288]
Se requiere realizar la construcción de los diagramas modulares y de procesos del sistema como complemento de la documentación técnica.

**Sub Tareas**

- [x] Revisar la inmersión del requerimiento según los siguientes enlaces: https://github.com/udistrital/polux_cliente/issues/832, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/ES7a6FEo7gFIvQXkuLrLJp8BwC2OkgrCL7OTdsrHmTVPfQ?e=lpuvxv, https://udistritaleduco-my.sharepoint.com/:b:/g/personal/caescorciab_udistrital_edu_co/Ef8JZ-s9FXJBkRFKbsLcR2EBWG2yk5hAQ_qt7x0dcUo_sA?e=q9rxnW
- [x] Articular con líder técnico la información necesaria.
- [x] Proyectar los diagramas modulares y de procesos para equipo SoS.

**Criterios de aceptación**

- [x] Diagramas aprobados por equipo SoS
- [x] Diagramas referenciados en carpeta Documentación técnica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la construcción del diagrama modular y de procesos del sistema.

![Image](https://github.com/user-attachments/assets/81d49b9a-cb37-46e5-bd34-af9b83f7c504)



Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la construcción del diagrama modular y de procesos del sistema. 
**Pendiente proyectar en una siguiente issue el módulo de planes de mejoramiento que no se han determinado los módulos a desarrollar dentro del sistema**

![Image](https://github.com/user-attachments/assets/dbc607e3-7a50-455e-8ecf-4805ee2df1b1)


**Enlace carpeta guardada en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Analista%20de%20requerimientos/Diagramas/DIAGRAMA%20MODULAR?csf=1&web=1&e=5Pl9G1


Saludos.

**Comment by jcmurilloa** [comment]
Muy biuen trabajo @cjgonzalezp
