### ISSUE TITLE
Ajustes vistas de consulta del plan y auditorías

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#289]
Se requiere realizar la integración en el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) y el microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) para las tablas de las vistas de consulta en la que se resuelvan los campos paramétricos requeridos para las columnas de las tablas. 
Adicional, es requerido incorporar los botones de las vistas de aprobación en la vista de consulta del plan según el estado del plan.

**Sub Tareas**

- [ ] Integración vista de consulta del plan (estado).
- [x] Integración vista de consulta de auditorías (meses, tipo).
- [x] Implementación acción de aprobación del jefe una vez se encuentre en el estado 6791	En Revisión por Jefe.
- [x] Implementación acción de aprobación del secretario una vez se encuentre en el estado 6792	Aprobado por Secretario.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Integración vista de consulta de auditorías (meses, tipo)

Se logra la correcta conexion con el servicio de `plan_auditoria_mid` para traer los datos de meses y tipo de manera correcta 

![image](https://github.com/user-attachments/assets/c1e1e6b8-35a3-42cf-9b58-788f636b52eb)

**Comment by CristianCGutierrezG** [comment]
### Integración vista de consulta de auditorías

Con los cambios implementados en el `plan_auditoria_mid` ahora se visualizan los meses de manera correcta

![image](https://github.com/user-attachments/assets/b55f0609-a18a-4649-9389-f800cee23da7)

---

### Adecuación del Componente `consulta-plan`

Se implementó una lógica inicial que habilita o deshabilita las acciones disponibles en el componente, dependiendo del rol del usuario.
Actualmente, los cambios en las acciones están controlados mediante una **variable de prueba**

https://github.com/user-attachments/assets/28a69d41-52f1-4ba5-adb2-a7855f1dbe6f


Aún no se realiza la lógica para el cambio de estado al ser aprobado o desaprobado el plan

**Comment by edwargl7** [comment]
Muy buena implementación, se resuelve el PR. Se trabajará una integración completa del flujo de estados.
