### ISSUE TITLE
Proyectar el Diseño del mockup de la vista del modulo Configuración

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#29]
Se requiere proyectar el diseño del mockup para la vista del módulo configuración de ARGO V2

**Sub Tareas**

- [x] Proyectar el diseño mockup con base en los requerimientos.
- [x] Presentar el mockup al cliente.
- [x] Realizar ajustes según comentarios del cliente.
- [x] Presentar al equipo el mock definitivo para el desarrollo.

**Criterios de aceptación**

- [x] Mockup aprobado por cliente y equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza un avance en el diseño del mockup del módulo de configuración. Teniendo en cuenta los lineamientos estipulados para los subsistemas de la universidad. Pendiente ajustes adicionales.

**Imagen Diseño Mockup Submódulos de Configuración** 
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/d8c72a4f-d661-4d3a-aed1-ef4092f03d21)

**Enlace archivo cargado en OneDrive en la carpeta del proyecto correspondiente** 
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=BFfPHb


Saludos

**Comment by jcmurilloa** [comment]
Muy buen trabajo, se debe refinar el mockup según precisiones del cliente
