### ISSUE TITLE
Organización arquitectura del microcliente plan_anual_auditoria_mf

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#290]
Se requiere realizar la reorganización de la arquitectura del microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).

**Sub Tareas**

- [x] Reorganización de los módulos del proyecto,
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Organización arquitectura del microcliente plan_anual_auditoria_mf**

>[!NOTE]
> **Refactorización de la arquitectura**
> - Cambio de carpetas
> - Definición correcta de módulos
> - Eliminación de módulos que no vienen al caso
> - Cambio en el enrutamiento para manejo de modulos 
> - Carga lazy para los módulos

![image](https://github.com/user-attachments/assets/0facb271-d82e-423f-9dbe-e6f9595d8d44)

**Comment by edwargl7** [comment]
Muy buen trabajo, culminada la Issue.
