### ISSUE TITLE
Diseño e implementación Auditores PAA

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#292]
Se requiere realizar el diseño de la colección de registro de auditores asociados a una auditoría (muchos a muchos) almacenando el número de documento de identidad del tercero, activo, fecha creación, fecha modificación, asignado (booleano para identificar los auditores asignados en caso de existir cambios de auditores) y id de referencia de la auditoría.
Implementación del CRUD de auditores en el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) e implementación en el microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) que permita resolver en la consulta de las auditorías la referencia del auditor o auditores.

**Sub Tareas**

- [x] Actualización del modelo de datos con la nueva colección de auditores.
- [x] Implementación CRUD de auditores.
- [x] Actualización controladores del microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) que retorne los números de documentos del o los auditores asignados en los endpoint getAll retornando el nombre del tercero y el id de referencia del registro de auditoría_auditor.
- [x] Implementación endpoint de consulta de auditores resolviendo los datos del tercero con el servicio tercero crud.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados de las pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actualiza modelo de datos plan auditoria crud![Image](https://github.com/user-attachments/assets/ce030374-7cdd-4530-9aa6-11d6a96fbbb1)


se actualiza modelo en carpeta database del proyecto y README

**Comment by jucastro94** [comment]
se crea modulo para la coleccion auditor (dtop, schema, controller y service)

![Image](https://github.com/user-attachments/assets/1132b03c-0c19-41e7-9dec-6a1c68b5deb4)

![Image](https://github.com/user-attachments/assets/df3fb51c-fca6-48d3-8459-c68b05b0afeb)

**Comment by jucastro94** [comment]
se realiza pruenas funcionales
![Image](https://github.com/user-attachments/assets/f27a540e-e3a5-49ce-a495-bcf7f0cead28)

![Image](https://github.com/user-attachments/assets/211b2e2d-7924-4862-bc1f-8eece24cd5fa)

![Image](https://github.com/user-attachments/assets/9722b90d-bffe-439f-b55b-ceeb4e4b1040)
![Image](https://github.com/user-attachments/assets/d1507e1f-d996-4172-a001-b00a2ec79fc5)
![Image](https://github.com/user-attachments/assets/c4f6b325-808c-4b8f-bd30-1c5194c86dce)

**Comment by jucastro94** [comment]
se actualiza plan auditoria mid con modulo audiores
![Image](https://github.com/user-attachments/assets/40d1030f-6010-4508-8ea8-f83245a13367)

**Comment by jucastro94** [comment]
se desarrolla servicio auditores, consumiendo terceros para devolver el nombre completo asosciado con el id

![Image](https://github.com/user-attachments/assets/0c75e5e8-60a1-472b-97cc-71fefc1b2989)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/53e74ea7-523c-425a-abc4-f9450f329f2a)
![Image](https://github.com/user-attachments/assets/43f8f84e-3586-4d4c-b929-9d5d2a1f4782)

**Comment by jucastro94** [comment]
se corrige dto y schema de auditor en plan auditoria crud para que el campo documento_id sea tipo number y el campo asignado tenga por valor default true
![Image](https://github.com/user-attachments/assets/5ea9881d-e87b-4017-94fb-ed1ec53ddd24)
![Image](https://github.com/user-attachments/assets/d073c035-3b26-40a1-b64f-67f235b6fe59)

**Comment by edwargl7** [comment]
Agregar por favor el campo asignado_por_id revisado.

Y se solicita un campo nuevo en la reunión con el cliente que permita identificar un auditor líder de esa auditoría, por lo tanto, agregar por favor un nuevo campo "auditor_lider" booleano.

**Comment by jucastro94** [comment]
se actuliza modelo de datos con los campos asignado_por_id y auditor_lider
se actualiza modelo en carpeta de proyecto y README
![Image](https://github.com/user-attachments/assets/6514e6bd-4ccb-492d-bd14-1b5ddf6a833f)

**Comment by jucastro94** [comment]
se realiza prueba funcional de plan auditoria crud
![Image](https://github.com/user-attachments/assets/ea32c03b-57ca-4b7a-a930-194ea144a89c)

**Comment by jucastro94** [comment]
se modifica plan auditoria mid, para realizar el reemplazo de asignado_por_id 
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/c60bd079-f0c4-49ab-941d-8908dbadc8a7)

**Comment by edwargl7** [comment]
Muy buen trabajo y documentación. Se resuelven los PR.
