### ISSUE TITLE
Implementación usuario por rol - Parte 2 - Autenticación MID

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#293]
Se requiere realizar el ajuste en el endpoint de consulta de usuario por rol implementado en [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) que ya cuenta con a consulta de usuario en [periodo_helper](https://github.com/udistrital/autenticacion_mid/blob/develop/helpers/periodo_helper.go).

**Sub Tareas**

- [x] Implementar consulta por varios ids del rol.
- [x] Pruebas funcionales usando los microservicios [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) y [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud).

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan ajustes en el desarrollo de filtrado por id

se establece clave para realizar busqueda por id's 
![Image](https://github.com/user-attachments/assets/d1a8a4cb-b4ec-45f0-9515-2324cbdb297e)

se ajusta logica de modelo de query para aceptar varios ids separados por comas y realziar lo que seria la funcion IN() en sql
![Image](https://github.com/user-attachments/assets/0045fc25-33ad-48e6-8804-cca43bee0357)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/1841952a-9e4a-4b6c-95a5-f789f3112fd7)
![Image](https://github.com/user-attachments/assets/668d0887-9ceb-445c-bb4a-62dfa9d6a385)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales

caso en que no exista ningun registro con el filtro
![Image](https://github.com/user-attachments/assets/c1c71a9c-60f8-4e9f-81dd-868069a9df4a)

---

caso en que existen  2 o mas registros
![Image](https://github.com/user-attachments/assets/4f88a738-2365-4834-966c-00fefb034af7)
![Image](https://github.com/user-attachments/assets/37657d84-2985-447a-8276-ed3dc5f06cba)

---

caso en que 1 no existe y 2 si
![Image](https://github.com/user-attachments/assets/f5526180-e8c8-416d-ab49-0e0b0f027010)
![Image](https://github.com/user-attachments/assets/905c5b59-3753-4a6a-8a2a-00a2f33543a4)

**Comment by jucastro94** [comment]
se desarrolla controller para el filtro en autenticacion mid
![Image](https://github.com/user-attachments/assets/99ff1835-0efb-4322-87a8-9bb9e6282d14)

**Comment by jucastro94** [comment]
se modifica autenticacion mid, para permitir clave de Rolid y asi enviarla junto a la url a servicio de usuarios_rol
![Image](https://github.com/user-attachments/assets/0961bb87-5e29-41d3-9418-e34e6f2a65cd)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/90d65d62-29ad-41d1-a6a4-d5de7c911a0f)
![Image](https://github.com/user-attachments/assets/0a0db40c-99ec-4d8d-b340-f34b7376678b)

**Comment by jucastro94** [comment]
se agrega parche en las consultas a ´parametros de limit=0
![Image](https://github.com/user-attachments/assets/3b221ad1-5b5c-442b-a339-7ceb60fcb95c)

se agrega adicion de campo _nombre  en modulo actividad
![Image](https://github.com/user-attachments/assets/700692f8-61f5-4d44-af7f-3d75c1e43f5b)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/9f3b8756-c0f3-4ddf-802a-de1290f05d94)

**Comment by jucastro94** [comment]
se realiza prueba funcional de filtro finalizado en periodos

![Image](https://github.com/user-attachments/assets/a5f4804c-b3e7-4ddf-856b-5a13015016fb)
![Image](https://github.com/user-attachments/assets/942d10b4-f2b5-463b-a788-40e935c95f9e)

---

![Image](https://github.com/user-attachments/assets/be0b637a-6e7e-4591-8544-002015853a8e)
![Image](https://github.com/user-attachments/assets/9fafaaa9-c5f6-4e38-877c-ce2ef30d616f)

---

![Image](https://github.com/user-attachments/assets/631fd86e-03d8-4aee-80ec-4eb1581ae4d6)
![Image](https://github.com/user-attachments/assets/e190918c-a9d4-41d7-87ea-29ed6bfa24f2)

**Comment by edwargl7** [comment]
Muy buena documentación e implementación, se resuelve el PR asociado.
