### ISSUE TITLE
Ajuste de estilos submódulo de Registro del PAA en la fase de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#294]
Se requiere realizar el ajuste de los estilos aplicados en la Issue #279 en el formulario de registro de datos complementarios de cada auditoría al submódulo de registro del PAA en el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).

**Sub Tareas**

- [x] Ajuste de estilos vista de registro de información base del plan.
- [x] Agregar botón de regreso a vista de consulta/creación desde a vista de información.
- [x] Ajuste de estilos vista de registro de Auditorías.
- [x] Agregar botón de regreso a vista de consulta/creación desde a vista de registro de auditorías.
- [x] Ajuste de estilos modal registro de auditoría individual.
- [x] Ajuste de estilos modal de cargue masivo.
- [x] Ajuste de estilos modal de cargue de matriz.
- [x] Ajuste de estilos modal de previsualización del PAA en PDF.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en ajuste de estilos y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Ajuste de estilos submódulo de Registro del PAA en la fase de programación**

>[!NOTE]
> Creación de plantilla tarjeta contenedora 

```ts
export class PlantillaTarjetaContenedoraComponent {
  @Input() breadcrumb!: SafeHtml;
  @Input() title: string = "";
  @Input() contenido!: TemplateRef<any>;
}

```

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Ajustes de estilo
> - Botones de regresar desde la plantilla
> - Cambios en las interfaces

Pasar de: 
![image](https://github.com/user-attachments/assets/2153f9a8-8134-4aea-ae13-9b6bbec7c1cf)

a:
![image](https://github.com/user-attachments/assets/0b1c4f77-9917-45ac-b89f-84f065cbe080)

---

Otros cambios:

![image](https://github.com/user-attachments/assets/f69ee684-1bc3-4539-ad27-5bc283c96014)
![image](https://github.com/user-attachments/assets/e6d0bc61-19a3-48d5-99fe-7e6b99312370)
![image](https://github.com/user-attachments/assets/d42dc2f9-6b52-469b-930f-542b6eb28fe5)
![image](https://github.com/user-attachments/assets/ae8f0e30-7761-4179-93a7-f37512243817)

>[!WARNING]
> Algunos detalles como las tablas o colores sueltos hay que pulirlos, cuando se toquen directamente

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Se cambio los alertas que abrían con modal service a alerta service

![image](https://github.com/user-attachments/assets/48cb66b7-f1f0-4e5f-88c6-08a81eae63b9)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Cambio de interfaces en los modales
> -Eliminación de CSS innecesario para mejor rendimiento 

Por ejemplo de: 

![image](https://github.com/user-attachments/assets/aad37e85-1019-4d97-af27-c98c9f6ffa84)
![image](https://github.com/user-attachments/assets/97b1c865-d855-4adf-bda6-71d5dcb67eaf)
![image](https://github.com/user-attachments/assets/7eb3ee67-b410-4879-876a-3d1006a09abc)

---

A:

![image](https://github.com/user-attachments/assets/4577bf46-111d-4381-a951-c6edce109e25)
![image](https://github.com/user-attachments/assets/a04774fe-2d48-4c83-a3e5-77b35ebc207a)
![image](https://github.com/user-attachments/assets/35cd9d9d-4f36-4e25-ba4f-7e9c780901e6)
![image](https://github.com/user-attachments/assets/22d9d2a2-301a-417c-97b8-e079443d417f)
![image](https://github.com/user-attachments/assets/33489a70-dcbf-4c4e-8e19-2104e0e48430)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Responsive

![image](https://github.com/user-attachments/assets/400b113e-ff3f-4917-9619-d1f0a5b6d6c9)
![image](https://github.com/user-attachments/assets/ab5751e9-f54a-43ab-a089-3062581360b7)
![image](https://github.com/user-attachments/assets/e2d27806-29b0-4b95-a313-7a024a87a4bc)

**Comment by edwargl7** [comment]
Muy buen trabajo, en el "cargue de archivos" revisemos por favor dejarlo en singular dado que solo se puede cargar un archivo @cjgonzalezp @K3vinchaparro .
