### ISSUE TITLE
Ajuste de estilos módulo de Gestión de Usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#295]
Se requiere realizar el ajuste de los estilos aplicados en la Issue #279 en el formulario de registro de datos complementarios de cada auditoría al módulo de Gestión de Usuarios en el microcliente [usuario_rol_mf](https://github.com/udistrital/usuario_rol_mf).

**Sub Tareas**

- [x] Ajuste de estilos vista de consulta de usuarios.
- [x] Ajuste de estilos vista de registro/edición de rol a un usuario.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en ajuste de estilos y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Ajuste de estilos módulo de Gestión de Usuarios**

>[!NOTE]
> Cambio de interfaces

De:
![image](https://github.com/user-attachments/assets/9ad1e9db-542a-437b-aabe-c4f51caa8f62)
![image](https://github.com/user-attachments/assets/9206079e-8edc-431e-a02a-681473df713b)
![image](https://github.com/user-attachments/assets/55384e93-57ea-494c-bcca-91045ac13f2c)

---

A:

![image](https://github.com/user-attachments/assets/ffed3412-dba5-46fc-99e9-fa68d3463874)

![image](https://github.com/user-attachments/assets/742cded0-4c1e-4d54-9ce0-d0c05106c1f6)

![image](https://github.com/user-attachments/assets/02d94567-63d3-43ff-a36a-f9822fd2e959)


Responsive
![image](https://github.com/user-attachments/assets/bd8269c7-cd58-41fe-8061-4f5a54731ccc)

**Comment by edwargl7** [comment]
Muy buen trabajo y documentación, resolver conflictos del PR por favor @K3vinchaparro.
