### ISSUE TITLE
Pruebas funcionales por ajuste de arquitectura al módulo de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#296]
Se requiere realizar las pruebas funcionales al módulo de programación por cambios en la arquitectura del proyecto.

**Sub Tareas**

_Cristian_
- [x] Prueba registro de información base de auditoría.
- [x] Prueba registro de auditoría individual.
- [x] Prueba cargue masivo.
- [x] Prueba previsualización PDF.

_Alex_
- [x] Prueba Registro de Auditorías Especiales.
- [x] Prueba Asignación de Auditor.

**Criterios de aceptación**

- [x] Documentación resultado de pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizaron pruebas de los diferentes modulo y paginas despues de la reestructuración realizada por @K3vinchaparro 

#### Modulo planeación
![image](https://github.com/user-attachments/assets/e28a8f89-30dd-4644-9336-b4ed8dcff05f)

![image](https://github.com/user-attachments/assets/0d7024e1-a682-4a18-b272-480b1bf01825)

#### Modulo programación

![image](https://github.com/user-attachments/assets/017f1b5a-aec9-45af-b534-4f84596a2f0e)

![image](https://github.com/user-attachments/assets/36ce1c95-8832-4c81-a8ab-07dfd41e26ff)

 Se encuentra un error en el renderizado de los meses al visualizar el plan
![image](https://github.com/user-attachments/assets/0dc1151f-fa52-4476-a917-546f416592f8)


Se encontraron errores al realizar las pruebas del cargue masivo
![image](https://github.com/user-attachments/assets/1f82046c-7864-4afb-9ff8-e10bef9e0b0b)

**Comment by alexhrr** [comment]
Se asiste a la reunion con el equipo de trabajo para realizar las pruebas después de los ajustes de arquitectura.
Se revisan los errores encontrados al ejecutar la lamba y por el momento no se encuentra la causa del error al enviar los registros al crud, se realizan los ajustes necesarios para adicionar la vigencia al complement del payload y continua saliendo error.
Después de revisar y actualizar el mid y el crud se sigue generando el error y no se encuentra la causa, se planea intentarlo con el crud que se encuentra desplegado nuevamente.

**Comment by CristianCGutierrezG** [comment]
Junto con @alexhrr, se completó la revisión de los servicios necesarios para la presentación, asegurando su correcto funcionamiento.
Se realizaron las revisiones finales del microservicio `auditoria_plan_mejoramiento_usuario_mf`, verificando que todos los módulos estén configurados y operativos, junto con los modulos de Registro de Auditorías Especiales.

**Comment by edwargl7** [comment]
Completada la Issue, muy buen trabajo. Pendiente integrar la vista del formulario de información de auditoría en la fase de planeación.
