### ISSUE TITLE
Implementación estados del PAA en la fase de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#297]
Se requiere realizar la implementación de los estados integrando las vistas de aprobación manteniendo en la url de las vistas de aprobación el identificador del plan.
![FLUJO ESTADOS PAA](https://github.com/user-attachments/assets/b92a3d53-62e3-417e-b73a-3b22f5304f71)

**Sub Tareas**

- [x] Implementación de estado al crear el plan.
- [x] Implementación de estado al enviar a aprobación del jefe.
- [x] Implementación de estado al rechazar el jefe (validación registro en el CRUD).
- [x] Implementación de estado al aprobar el jefe (validación registro en el CRUD).
- [x] Implementación de estado al rechazar el secretario (validación registro en el CRUD).
- [x] Implementación de estado al aprobar el secretario (validación registro en el CRUD).
- [x] Integración microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) para correcta visualización del estado en la vista de consulta.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación  y resultados pruebas funcionales.

**Material de apoyo**
- Estados
```
6790	Borrador
6791	En Revisión por Jefe
6792	Aprobado por Jefe
6793	En Revisión por Comité Coordinador
6794	Aprobado por Comité Coordinador
```

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Implementación de la Lógica de Estados


 **Estado Inicial al Crear el Plan**:
   - Al crear un nuevo plan, se realiza un `POST` que asigna automáticamente el estado con el ID `6790` (`Borrador`).

**Gestión de Estados en Operaciones Posteriores**:
   - **`GET`**: Se implementa la lógica para obtener el estado activo actual del plan según su ID.
   - **`DELETE`**: Se realiza la eliminación lógica del estado activo actual antes de realizar cualquier cambio.
   - **`POST`**: Se asigna el nuevo estado correspondiente según la acción realizada.

---

Implementación de estado al crear el plan/ enviar a aprobación del jefe

https://github.com/user-attachments/assets/1ee6fb67-7c67-425f-be30-f4510772a9e6

Implementación de estado al rechazar el jefe/ Implementación de estado al aprobar el jefe

https://github.com/user-attachments/assets/9a7c70c4-814f-4bda-afc9-8f0c39830c7c

**Comment by edwargl7** [comment]
Se requiere dada la revisión e integración avanzada la implementación de un ajuste en el microservicio crud para manejar mediante un nuevo campo "actual" de tipo booleano la identificación del estado actual del plan. Dado que existe la posibilidad den el flujo que existan más de un mismo registro de estado, pe borrador.

**Comment by CristianCGutierrezG** [comment]
### Cambios en el Módulo de Plan Anual de Auditoría

#### Modificaciones en `plan_anual_auditoria_crud`:
1. **Nuevo Campo en la Colección `plan_estado`**:
   - Se agregó el campo `"actual"` en la colección `plan_estado` para identificar el estado actual de un plan.
   ![image](https://github.com/user-attachments/assets/55de8439-aec2-498c-9a26-12d851c3baba)


2. **Actualización Automática del Estado Actual**:
   - Se modificó la petición `POST` de `plan_estado` para actualizar automáticamente el campo `"actual"` al crear un nuevo estado relacionado con un plan.
   ![image](https://github.com/user-attachments/assets/0875ef1c-f687-4ac1-877a-9a86980ee75d)


#### Modificaciones en `plan_anual_auditoria_mid`:
1. **Integración de Datos de Estados**:
   - Se realizaron ajustes en el servicio `plan-auditoria` para incluir la obtención de los datos de los estados asociados a los planes.
   - Se implementó la conversión del `estado_id` utilizando la API de parámetros

#### Modificaciones en el Cliente:
1. **Gestión de Estados**:
   - Se implementaron los cambios necesarios para la creación de estados en el CRUD directamente desde el cliente.
   - Se añadió la lógica para obtener información de los estados desde el MID


https://github.com/user-attachments/assets/fecd63dd-ae7b-46a1-a24a-337979e525d6

**Comment by edwargl7** [comment]
Muy buen trabajo, resuelto PR.
