### ISSUE TITLE
Ajuste endpoints del microservicio plan anual de auditoría mid ids y nombres

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#298]
Se requiere realizar el ajuste en los controladores del microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) que retorne el id o ids y adicional los nombres o datos complementarios según revisión e integración realizada el sprint anterior para a presentación.

**Sub Tareas**

- [x] Ajuste endpoint getOne de auditorías.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se ajusta service de auditoria para generar el nuevo campo de vigencia_nombre con su valor
![Image](https://github.com/user-attachments/assets/e3d5a287-0628-4f82-996a-5825cdf08305)
![Image](https://github.com/user-attachments/assets/e863451d-1b0a-4e69-a49d-d312b8bc9a18)
![Image](https://github.com/user-attachments/assets/b36f20e2-5bc9-4191-87cc-016cf5e2a3d1)

**Comment by jucastro94** [comment]
se ajusta metodo reemplazar para que genere el campo _nombre dinamicamente y socie el valor correspondiente

![Image](https://github.com/user-attachments/assets/9eabae37-d6ae-45df-8489-88495590af42)

**Comment by jucastro94** [comment]
se realiza pruebas funcionales

plan auditoria
![Image](https://github.com/user-attachments/assets/ea7b8ef6-96fd-4c45-a2c0-d092c61e6302)


auditoria
![Image](https://github.com/user-attachments/assets/96d23b01-382a-4812-a245-d7ac615a9526)

**Comment by edwargl7** [comment]
Pendiente PR. Muy buen trabajo.

**Comment by edwargl7** [comment]
Tener cuidado con los cambios en los archivos de configuración que podrían afectar los despliegues, para evitar reemplazarlas se puede crear un script que no se suba al repositorio que ayude en local a montar las variables de entorno antes de la ejecución.
![Image](https://github.com/user-attachments/assets/3637992b-d23b-4fe2-abbe-8ff419ea8f63)

**Comment by edwargl7** [comment]
Resuelto PR.
