### ISSUE TITLE
Integración visualización del PAA PDF con el gestor documental

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#299]
Se requiere realizar a integración con el gestor documental para consultar el documento asociado al PAA en PDF registrado por el auditor en cada una de las vistas de aprobación.

**Sub Tareas**

- [x] Validación que al registrar el auditor varias veces el documento del PAA, se mantenga activa la última versión en la tabla de documento o un único registro.
- [x] Validar almacenamiento enlace (uid).
- [x] Ajuste id de referencia del gestor documental.
- [x] Implementación consulta de PDF de gestor documental.
- [x] Integración visualización del PAA PDF en la vista de aprobación del jefe.
- [x] Integración visualización del PAA PDF en la vista de aprobación del secretario.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
Se verifica flujo del registro del formato en para el gestor documental, hace falta guardar el enlace de respuesta del gestor en la coleccion documento del plan auditoria crud

Se comienza a desarrollar dicho registro

**Comment by jucastro94** [comment]
se realiza ajuste en coleccion documento de plan_auditoria_crud para almacenar el id del gestor documental tipo number y el enlace tipo string
![Image](https://github.com/user-attachments/assets/a9f4c827-35df-4184-878e-645c53d9f332)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/c21d5648-6a32-445e-8a38-6f21d52088a1)
![Image](https://github.com/user-attachments/assets/ee624d86-ee77-4c95-97d7-7b4e90f56077)

**Comment by jucastro94** [comment]
se corrige ubicacion de campo "actual" en modelo de datos
![Image](https://github.com/user-attachments/assets/17f19cf7-e35f-4e7a-815d-19129f69f829)

se actualiza README y carpeta de proyecto

**Comment by jucastro94** [comment]
se realiza validacion para registrar o reemplazar registro en documento de plan auditoria crud
![Image](https://github.com/user-attachments/assets/6ad99bf1-4f9a-4f10-ae33-01ddb294c9e3)
![Image](https://github.com/user-attachments/assets/09ee004c-d0cf-4f7c-87c5-2e6128690f7f)

**Comment by jucastro94** [comment]
se realiza peticion get a plan auditoria crud para obtener el enlace segun el plan auditoria tanto para la revision de jefe como para el secretario


![Image](https://github.com/user-attachments/assets/a0a9952d-bd5a-43af-ab72-91b161379260)

**Comment by jucastro94** [comment]
se realiza peticion get al gestor documentar con el enlace para obtener el base64
![Image](https://github.com/user-attachments/assets/abca2d88-df18-4e11-9f0a-9d80391c0b75)

**Comment by jucastro94** [comment]
se asigna base64 a variable asosiada con el componente para renderizar
![Image](https://github.com/user-attachments/assets/f30eda51-6705-45ad-9d1e-269df4378eab)

**Comment by jucastro94** [comment]
se realizan correcciones para identificar los campos necesarios en la respuesta de las peticiones
![Image](https://github.com/user-attachments/assets/f5d6bba4-eca8-47fd-b14a-744d775d9d33)
![Image](https://github.com/user-attachments/assets/f3352591-bd93-470f-ae64-0bc60be0d6a7)
![Image](https://github.com/user-attachments/assets/bbf672c8-9465-415a-ae6b-76ab7e78435f)

se modifica componente de renderizado para detectar cammbios en el componente padre respecto al base64 que recibe, ya que en el componente padre se trabaja de manera asincronica y sin eso, llega vacio 
![Image](https://github.com/user-attachments/assets/767d1cdf-92b9-4270-bf6c-2a223e4cfef8)


se corrije ruta de para visaulizacion de plan jefe
![Image](https://github.com/user-attachments/assets/02178eac-0c96-4c43-b767-b6ce7ca8bb72)

**Comment by jucastro94** [comment]
se realizan pruebas funcionales
![Image](https://github.com/user-attachments/assets/3f658941-19ef-4e3d-8798-ce0ae83bef4c)
https://github.com/user-attachments/assets/8d71ed6a-daf9-4876-9478-9baf66618d6b

**Comment by edwargl7** [comment]
Muy buena implementación, se resuelve PR. Se debe ajustar los nombres de las colecciones.
