### ISSUE TITLE
Visualización matriz función pública microcliente PAA

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#300]
Se requiere realizar la integración con el gestor documental para la visualización de la matriz de función pública en las vistas de aprobación jefe y secretario.

**Sub Tareas**

- [x] Integración consulta de documento cargado como matriz asociado al plan en la vista de aprobación del jefe.
- [x] Integración consulta de documento cargado como matriz asociado al plan en la vista de aprobación del secretario.
- [ ] Pruebas funcionales.

**Criterios de aceptación**

- [ ] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza integracion en component html para revision de jefe y secretario
![Image](https://github.com/user-attachments/assets/327dc1f6-067d-421d-a398-95d2cfd263a4)

se adecua para que se realice el filtrado adicionalmente con tipo_id en plan auditoria crud para obtener tanto el PAA como la matriz de gestion publica del plan auditoria

se deben esclarecer los ids para cada tipo_id
![Image](https://github.com/user-attachments/assets/6b823569-b233-4c7d-9261-de78b1aaf9cd)

![Image](https://github.com/user-attachments/assets/71aa1ab8-8e37-4019-aace-62db8eb064dc)
![Image](https://github.com/user-attachments/assets/fb819c1a-1782-47f9-a797-dac7366da129)

**Comment by jucastro94** [comment]
se realiza prueba funcional provicional, donde se le envia el mismo tipo_id del PAA
![Image](https://github.com/user-attachments/assets/e324f3ec-02ee-4a41-9d5e-22b41c7d5d22)

**Comment by edwargl7** [comment]
Pendiente entrega del id de parámetros CRUD y agregar variable de entorno.

**Comment by edwargl7** [comment]
Finalizada con IDs creados
