### ISSUE TITLE
Ajustes gestión de roles de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#301]
Se requiere realizar la revisión de los errores al crear/actualizar un periodo de un usuario. Validación del error al existir registros en el microservicio [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud) al no existir registro del tercero en terceros crud.

**Sub Tareas**

- [x] Ajustes de errores en el microcliente [usuario_rol_mf](https://github.com/udistrital/usuario_rol_mf) al crear o actualizar un periodo.
- [x] Ajuste error cuando existe un registro en el ms [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) al no existir un registro asociado al tercero en el getAll.
- [x] Agregar drone basado en [.drone.yml](https://github.com/udistrital/gestion_contractual_mf/blob/develop/.drone.yml).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Pruebas creación y actualización 

Se realiza la creación de un usuario que no se encuentra registrado actualmente en roles crud y que se encuentra en terceros y autenticación mid:

![Captura de pantalla 2024-11-25 a la(s) 8 05 22 p m](https://github.com/user-attachments/assets/37d81934-9749-49d1-b9a9-15d11f870a9b)

Se le asigna el rol de auditor que se encuentra creado en el crud y se crea exitosamente el usuario con el rol asignado:

![Captura de pantalla 2024-11-25 a la(s) 8 05 42 p m](https://github.com/user-attachments/assets/5b55e2ca-a0c9-4234-8223-0458eb03be4e)

Se verifican los roles antes de la creación y se verifica nuevamente cuando se crea el usuario con el rol asignado 

![Captura de pantalla 2024-11-25 a la(s) 8 05 49 p m](https://github.com/user-attachments/assets/0e088b59-372a-4fbe-8f2c-768d1202e5d8)

![Captura de pantalla 2024-11-25 a la(s) 8 06 01 p m](https://github.com/user-attachments/assets/a022e880-1c19-48be-a71f-a6ecfbdb88c3)

En la sección de consultas se revisa que se haya creado el usuario con los datos indicados:

![Captura de pantalla 2024-11-25 a la(s) 8 06 28 p m](https://github.com/user-attachments/assets/dda0f02f-d9a2-4449-b97b-561da02613e6)

Se verifica en la sección de edición que se pueda eliminar el rol y finalizar el periodo:

![Captura de pantalla 2024-11-25 a la(s) 8 06 50 p m](https://github.com/user-attachments/assets/0e76b371-eca3-40ea-b603-65ba0acd7e3a)

![Captura de pantalla 2024-11-25 a la(s) 8 07 02 p m](https://github.com/user-attachments/assets/72e84836-5fee-4144-892f-e3c1ddf652f5)

El periodo se finaliza, se elimina el rol y se verifica nuevamente que se haya eliminado de autenticación mid:

![Captura de pantalla 2024-11-25 a la(s) 8 07 33 p m](https://github.com/user-attachments/assets/298a7403-c41e-4c5e-bbcb-62006e944025)

![Captura de pantalla 2024-11-25 a la(s) 8 08 04 p m](https://github.com/user-attachments/assets/50f45a1d-438e-47ba-a0a4-7e140512067b)

**Comment by edwargl7** [comment]
Se requiere solicitar la eliminación de registros de la base de datos.

**Comment by alexhrr** [comment]
Se agrega condicional para verificar si el usuario está creado y se actualiza el rol:

![Captura de pantalla 2024-11-26 a la(s) 10 31 43 p m](https://github.com/user-attachments/assets/7b90bf0c-2b91-4734-8f8c-fe2908ed8fb7)

![Captura de pantalla 2024-11-26 a la(s) 10 31 50 p m](https://github.com/user-attachments/assets/f02f6b63-1528-44fa-ad50-7265c54c7d5c)

**Comment by alexhrr** [comment]
### Ajustes creación de usuarios

Se realizan ajustes para la verificación de usuarios existentes y roles asignados previamente al usuario:

Se crea y se asigna el  rol de auditor al usuario:

![Captura de pantalla 2024-11-27 a la(s) 8 40 35 p m](https://github.com/user-attachments/assets/2acf671a-729e-4207-bb23-222dc554d6ca)

Se verifica la creación y se confirma el estado del periodo "vigente"

![Captura de pantalla 2024-11-27 a la(s) 8 40 45 p m](https://github.com/user-attachments/assets/98a5fbf8-08ec-4319-8985-4b364652d296)

Se le asigna nuevamente el rol de Auditor al mismo usuario y se muestra el error de que ya tiene el rol asignado:

![Captura de pantalla 2024-11-27 a la(s) 8 40 57 p m](https://github.com/user-attachments/assets/ec4e08ef-fd45-417e-bdd8-a80993e3b4a4)

Se finaliza el rol auditor:

![Captura de pantalla 2024-11-27 a la(s) 8 41 18 p m](https://github.com/user-attachments/assets/2136a1ef-4bea-47e1-a6ae-a772c7e19185)

se elimina el periodo y se verifica en la consulta

![Captura de pantalla 2024-11-27 a la(s) 8 41 25 p m](https://github.com/user-attachments/assets/d9411109-057f-439c-9171-f2ca5c285dcb)

![Captura de pantalla 2024-11-27 a la(s) 8 41 42 p m](https://github.com/user-attachments/assets/17a46747-49e8-4a53-85ae-3fdf1d0d487d)

Se asigna nuevamente el rol auditor al usuario, con el periodo anterior finalizdo. Se asigna correctamente:

![Captura de pantalla 2024-11-27 a la(s) 8 42 20 p m](https://github.com/user-attachments/assets/3a2920d6-f214-4688-963c-4027a68307c1)

![Captura de pantalla 2024-11-27 a la(s) 8 42 32 p m](https://github.com/user-attachments/assets/72190f04-51b4-4352-be6d-dd01b6ba7001)

**Comment by alexhrr** [comment]
Se realiza una estructuración en el código dividiendolo en diferentes funciones debido a que se agregaron nuevas validaciones al crear y asignar roles a los usuarios.

Se realiza la verificación de si el usuario a registrar existe previamente, si es asi se realiza una verificación de roles y se confirma que el periodo esté finalizado para su creación.

Tambien se realiza la creación del periodo y la asignación del rol en autenticación mid en funciones separadas a la creación del usuario

![Captura de pantalla 2024-11-28 a la(s) 5 30 01 p m](https://github.com/user-attachments/assets/72790d74-07fb-4384-9a6c-546f6a0ce68a)

![Captura de pantalla 2024-11-28 a la(s) 5 30 18 p m](https://github.com/user-attachments/assets/4c122fa6-dd47-4635-9b27-d5ce8915ebb8)

![Captura de pantalla 2024-11-28 a la(s) 5 30 31 p m](https://github.com/user-attachments/assets/46fe5bc1-eba7-4287-af01-fbd92f7331dc)

![Captura de pantalla 2024-11-28 a la(s) 5 30 43 p m](https://github.com/user-attachments/assets/5cccc693-3161-482b-8524-fe91b6b7dcbb)

![Captura de pantalla 2024-11-28 a la(s) 5 30 58 p m](https://github.com/user-attachments/assets/d5c34298-c766-40f3-8be6-e152d399ebaa)

**Comment by edwargl7** [comment]
Se requiere un nuevo rol que exista en wso2 para completar la validación, el resto de la implementación fue presentada al usuario.

**Comment by alexhrr** [comment]
Se realiza el ajuste en autenticacion_mid para capturar el error cuando no se puede encontrar un documento en terceros y no afectar la consulta completa.

![Captura de pantalla 2024-12-01 a la(s) 1 25 04 p m](https://github.com/user-attachments/assets/c53589ff-affc-46ee-8aa9-46cd60a6954c)

![Captura de pantalla 2024-12-01 a la(s) 1 25 52 p m](https://github.com/user-attachments/assets/040f6eb7-24d8-42be-8927-66cd18e75273)

![Captura de pantalla 2024-12-01 a la(s) 1 26 05 p m](https://github.com/user-attachments/assets/ae943353-1bd1-4216-aeb9-2c64f7d59f29)

Se muestran todos los periodos encontrados y si alguno presenta algún error se muestra igualmente con los espacios en blanco, se presenta una opción de mostrar el error en uno de los campos del tercero para que se muestre directamente al usuario:

![Captura de pantalla 2024-12-01 a la(s) 1 05 28 p m](https://github.com/user-attachments/assets/377b9836-2c24-4f6e-8767-70b25d0f0a5c)

![Captura de pantalla 2024-12-01 a la(s) 1 06 26 p m](https://github.com/user-attachments/assets/bbe26dc8-b958-4685-9f5b-5afb66b4179d)

**Comment by edwargl7** [comment]
Bien implementado la subtarea de consulta a tercero no encontrado, se puede cambiar el mensaje de cada columna a "No encontrado". Retorna los datos conocidos (el documento de identidad en la columna de consulta para que el usuario pueda identificar en la tabla que documento es el que no retorno los demás datos y crea el PR.
Muchas gracias.

**Comment by alexhrr** [comment]
Se realiza el ajuste para mostrar el documento que se está buscando y mostrar "No encontrado" en las otras columnas:

![Captura de pantalla 2024-12-02 a la(s) 12 43 24 p m](https://github.com/user-attachments/assets/5c4806ae-7721-47bf-b87e-c00df2a221d6)

**Comment by edwargl7** [comment]
Resuelto PR. Muchas gracias.
