### ISSUE TITLE
Implementación modal de visualización de errores de carga masiva

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#302]
Se requiere realizar la implementación del modal de visualización de errores de carga masiva de auditorías.

**Sub Tareas**

- [x] Implementación modal de visualización de errores de carga.
- [x] Integración con microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se inicia con la implementación para mostrar los errores de la carga masiva.

Se crea la función para mostrar los resultados y se capturan los datos de la respuesta mediante el servicio del modal:

![Captura de pantalla 2024-12-05 a la(s) 10 38 51 p m](https://github.com/user-attachments/assets/fde0965f-cb4d-43d5-ab3f-b0f471a685f2)

![Captura de pantalla 2024-12-05 a la(s) 10 37 36 p m](https://github.com/user-attachments/assets/faabab8c-3fa9-46fc-8d74-7afd039d45ae)

Se debe continuar con la mejora del modal segun el mockup sugerido

**Comment by edwargl7** [comment]
![Image](https://github.com/user-attachments/assets/84668dc4-3546-4492-bb41-28fc27db3488)

**Comment by edwargl7** [comment]
@cjgonzalezp nos ayudas por fa con la validación del diseño

**Comment by alexhrr** [comment]
Se realiza el modal para mostrar los registros correctos y con errores, se agrega la barra de desplazamiento para cuando se necesiten mostrar varios resultados:

https://github.com/user-attachments/assets/391ee51d-1b7b-40c8-bb35-3b39f6d13bd9

Se ajusta el ancho del modal y se cambia el texto de error en el servicio lambda. 
Se ajusta la numeración donde se muestran los errores para que inicie en 1:
 
https://github.com/user-attachments/assets/31bf4b79-c9f1-4220-9ebb-077e831fffcc

**Comment by edwargl7** [comment]
Resuelto PR, buen trabajo.
