### ISSUE TITLE
Concertar, desarrollar y levantar acta de de sesión de muestra con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#305]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de de sesión de muestra con el cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta con cliente y se agenda reunión presentación de avances con jefe Guillermo Alfonso y equipo asignado de la Oficina de Control Interno para el día jueves, 28 de noviembre de 2024 hora: 10:00 am de forma presencial en la sede Paiba


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con cliente incluido el jefe la Oficina de Control Interno para la presentación de avances del sistema.

Pendiente la proyección del acta de reunión de la reunión desarrollada.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión No 154/2024 Sísifo Presentación avances sistema de la reunión desarrollada el pasado 28 de noviembre. Pendiente la recolección de firma de los participantes presentes en la misma.

**Enlace documento guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErCshcIwmQJFi-7hAMUmlhsBvN869U9ULPMZVprJkcsQ-g?e=68dKdd


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, acta revisada y con VoBo para recoger las firmas correspondientes.

**Comment by cjgonzalezp** [comment]
Buen día,

Se da por finalizada la issue #305 con la recolección de firmas de los participantes presentes en la sesión documentada bajo el acta No 154.

**Enlace documento firmado y guardado en OneDrive en la carpeta del proyecto Sísifo V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/ErCshcIwmQJFi-7hAMUmlhsBvN869U9ULPMZVprJkcsQ-g?e=O1aD1n


Saludos.
