### ISSUE TITLE
Integración submódulo de asignación de auditorías - microservicio plan anual de auditoría CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#306]
Se requiere realizar la integración con el microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) para registrar los auditores a la auditoría especifica.
Adicional. agregar el campo para poder si es auditor principal (se puede agregar en todos los auditores la posibilidad de elegir). Si existe solo un auditor se marcará como auditor responsable o principal.

![image](https://github.com/user-attachments/assets/1b96718e-3f2f-4b23-a948-da1d8c971369)

**Sub Tareas**

- [x] Agregar checkbox de "Auditor Lider".
- [x] Ajuste observado en la Issue #285 para que los auditores ya seleccionados en esa misma auditoría no salga para elegirlos nuevamente en la misma auditoría.
- [x] Integración registro de auditores a auditoría microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).
- [ ] Pruebas funcionales.

**Criterios de aceptación**

- [ ] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se inicia con la implementación del checkbox para la selección del auditor líder:

![Captura de pantalla 2024-12-02 a la(s) 6 04 48 p m](https://github.com/user-attachments/assets/35ba3ece-abaa-4d72-a5a5-30eef62d7b50)

![Captura de pantalla 2024-12-02 a la(s) 6 04 54 p m](https://github.com/user-attachments/assets/8096b3d7-b280-49f7-b80c-72d30b7390e6)

**Comment by alexhrr** [comment]
Se realiza el ajuste para que no se muestren los auditores que ya se seleccionaron en los otros selectores

![Captura de pantalla 2024-12-03 a la(s) 10 47 44 p m](https://github.com/user-attachments/assets/8d227dd0-5629-4c51-866b-c034c2943650)

![Captura de pantalla 2024-12-03 a la(s) 10 48 05 p m](https://github.com/user-attachments/assets/b03d0111-01fb-4161-8cb2-37c1af8dcf0e)

Se inicia con el registro de los auditores en el microservicion crud

**Comment by edwargl7** [comment]
Pendiente corregir registro del usuario 2 de prueba.

**Comment by alexhrr** [comment]
Se finaliza la selección de auditores para que no salgan si ya han sido elegidos y se verifica el funcionamiento, se ajusta el checkbox para seleccionar el lider

https://github.com/user-attachments/assets/af90da89-3ee9-4a6e-a327-c19a52eb462a

Se continua con la integracion del Crud para el registro de los auditores

**Comment by edwargl7** [comment]
Se resuelve el PR, se continuará en el siguiente sprint dados los errores encontrados en el despliegue que no permitieron la integración con el CRUD.
