### ISSUE TITLE
Ajuste registro de auditores en microservicio CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#307]
Se requiere realizar el cambio del nombre de la colección de auditor por auditoria_auditor que permita representar la relación de muchos a muchos y permita relacionar el campo documento_id como auditor_id (tercero_id). 

**Sub Tareas**

- [x] Ajuste modelo de datos reemplazando el nombre de la colección y el campo documento_id.
- [x] Ajuste microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) los controladores relacionados a la colección.
- [x] Ajuste microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) petición al CRUD y cambio del campo documento_id.
- [x] Integración con el microservicio tercero CRUD para obtener el nombre del auditor por el id (auditor_id -> tercero_id).
- [x] Agregar campo actual al controlador de plan estado.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se  actualiza modelo de datos ![Image](https://github.com/user-attachments/assets/8fa64ac2-0da0-466c-bb4b-5c19634099fb)
![Image](https://github.com/user-attachments/assets/40074537-85c9-4978-bac2-82bcabddb316)

se actualiza README y carpeta del proyecto

**Comment by jucastro94** [comment]
se realizan ajustes en plan auditoria crud

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/7a4921b4-267b-4890-8159-439ffb5f422c)
![Image](https://github.com/user-attachments/assets/4e60e25c-a948-4944-84d7-4571f99ef46a)
![Image](https://github.com/user-attachments/assets/9798eb98-b6d1-48a2-abab-17f9703d9088)
![Image](https://github.com/user-attachments/assets/423fc795-a3ef-4d1f-a298-fbf50c44b36d)
![Image](https://github.com/user-attachments/assets/e3f54a58-ae24-4b48-bc35-a8420229412e)

**Comment by jucastro94** [comment]
se ajusta plan auditopria mid para trabajar con auditor_id en lugar de documento_id

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/95e4dbef-a6ee-4f0e-9a1b-46af23feb088)
![Image](https://github.com/user-attachments/assets/1023b4c2-61bd-4c03-b4be-aa806f40a358)

**Comment by edwargl7** [comment]
Buena documentación e implementación resuelto el PR.
