### ISSUE TITLE
Agregar campo de tercero id en los datos de los periodos de los usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#308]
Se requiere agregar el campo de tercero id en el microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) dentro de los datos que retorna del nombre, que permita identificar el id del tercero para almacenarlo como referencia en los otros sistemas.

**Sub Tareas**

- [x] Agregar campo tercero id en el endpoint de periodos del microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid).
- [x] Agregar campo tercero id en el endpoint de consulta de periodos por documento de identidad del microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se agrega el campo de id_tercero a las consultas de los periodos en autenticacion_mid

Consulta de todos los periodos:

![Captura de pantalla 2024-12-02 a la(s) 6 15 33 p m](https://github.com/user-attachments/assets/1ab24421-73ce-46ec-8532-2595d734e25b)

Consulta de periodos por documento:

![Captura de pantalla 2024-12-02 a la(s) 6 16 03 p m](https://github.com/user-attachments/assets/e9478ba1-1140-4d09-84f6-48ee221a39ab)

![Captura de pantalla 2024-12-02 a la(s) 6 16 17 p m](https://github.com/user-attachments/assets/af313c4b-d6e1-4694-8b96-6a55e9f37cdd)

**Comment by edwargl7** [comment]
Se resuelve el PR y se da por completado las subtareas solicitadas.
Se va a agregar adicionalmente el despliegue en ambiente de pruebas y la validación.

**Comment by alexhrr** [comment]
Una vez realizado el despliegue se realiza la validación de los ajustes realizados:

Consulta de todos los periodos:

![Captura de pantalla 2024-12-09 a la(s) 4 39 44 p m](https://github.com/user-attachments/assets/4b68f98e-5a89-4969-86f6-792b41f83189)

Consulta de periodos por documento:

![Captura de pantalla 2024-12-09 a la(s) 4 42 06 p m](https://github.com/user-attachments/assets/e8bf60f4-b2c8-4664-bd9f-41adfd126aab)

![Captura de pantalla 2024-12-09 a la(s) 4 35 11 p m](https://github.com/user-attachments/assets/ac1098c4-3c70-4e63-ad75-c6cbc311c42d)

**Comment by edwargl7** [comment]
Completada la evidencia adicional. Muchas gracias.
