### ISSUE TITLE
Paso a producción endpoint documentoToken del microservicio autenticacion_mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#309]
Se requiere realizar el despliegue a producción del endpoint documentoToken del microservicio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid).

**Sub Tareas**

- [x] Preparación despliegue solamente de ese endpoint ([rama con cambios](https://github.com/udistrital/autenticacion_mid/tree/feature/documentToken)).
- [x] Pruebas funcionales previas al despliegue de los endpoints actuales (ambiente Producción).
- [x] Pruebas funcionales posteriores al despliegue (ambiente Producción).

**Criterios de aceptación**

- [x] Documentación resultado pruebas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Pruebas funcionales previas al despliegue:

### /token/user/Rol

![Captura de pantalla 2024-12-10 a la(s) 6 16 36 p m](https://github.com/user-attachments/assets/9900fc44-0382-4151-a802-8f54f8796a12)

### /token/emailToken

![Captura de pantalla 2024-12-10 a la(s) 6 18 57 p m](https://github.com/user-attachments/assets/a3a3cd8b-cc67-42d2-b11e-c50512c7b85d)

**Comment by alexhrr** [comment]
Pruebas funcionales posteriores al despliegue:

### /token/user/Rol

![Captura de pantalla 2024-12-11 a la(s) 7 02 04 p m](https://github.com/user-attachments/assets/c1273f7b-8bcd-4cae-a7e4-fb7e8d2fd320)

### /token/emailToken

![Captura de pantalla 2024-12-11 a la(s) 7 02 24 p m](https://github.com/user-attachments/assets/0f58f283-4d64-4313-ac44-a9a8edf2fce3)

### /token/documentoToken

![Captura de pantalla 2024-12-11 a la(s) 7 02 47 p m](https://github.com/user-attachments/assets/32af8dc5-02f8-486b-8f47-d11533c56c2b)

**Comment by edwargl7** [comment]
Completado el paso a producción, se debe validar el caso de un usuario con más de un correo.
