### ISSUE TITLE
Actualización campos del módulo plan de mejoramiento

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#31]
Se requiere realizar la actualización de los campos recopilados en [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU1YeT1ywDtFqQN6wbqHJv0BMLwKsRXaeg1cdBAwB8CLaQ?e=gfygzq) para los submódulo de _plan de mejoramiento_ y _hallazgos_ del módulo de plan de mejoramiento basado en el formato [EC-PR-003-FR-005](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQG2qvRsdklKkBBNNvsr4d0BBi-ETYLtiolUI9W8DV-_kQ?e=nJCoxM). Identificando posibles restricciones y observaciones a tener presente de cada campo nuevo (si lo requiere).

**Sub Tareas**

- [x] Revisión formato [EC-PR-003-FR-005](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQG2qvRsdklKkBBNNvsr4d0BBi-ETYLtiolUI9W8DV-_kQ?e=nJCoxM) campos nuevos y campos no existentes.
- [x] Actualizar hoja SistemaActual-FormatoPlanMej-v2  de [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU1YeT1ywDtFqQN6wbqHJv0BMLwKsRXaeg1cdBAwB8CLaQ?e=gfygzq) resaltando de color rojo los campos que no se encuentran en el formato **EC-PR-003-FR-005** y en una columna nueva (agrupada) los campos que existen en el formato y no en el sistema actual.

**Criterios de aceptación**

- [x] Actualización del documento de campos de cada módulo **Módulos y dependencias** identificando los campos que actualmente existen y no son requeridos y los campos nuevos, junto con las restricciones u observaciones pertinentes.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Documento **Módulos y dependencias** actualizado
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizaron  los cambios en el documento [Módulos y dependencias](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EU1YeT1ywDtFqQN6wbqHJv0BMLwKsRXaeg1cdBAwB8CLaQ?e=gfygzq) de acuerdo a las especificaciones planteadas:  

- Se marcaron en rojo los campos que no se encuentran en el formato actual y se añadió una columna nueva para los campos que sí existen en el formato.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/cd534080-37b4-494a-94a2-c8f87baf0383)

Se asume que en el nuevo formato se entiende como **Acción** lo que en el actual Sísifo es la **Actividad**, así que se agregaron los nuevos campos correspondientes a este modulo.
En las notas, se especifica el nombre que relaciona el campo actual con el del nuevo formato o si posee alguna restricción.

**Comment by edwargl7** [comment]
Buen trabajo se realiza una primera revisión, se realizará la revisión más detallada. Por el momento cumple con lo requerido y se complemento adecuadamente el documento inicial de campos de cada submódulo.

**Comment by edwargl7** [comment]
Se realiza la revisión final, se observa correctamente finalizada la tarea, se agrega la observación del firmante _"Firma del Líder o Gestor del Proceso"_.
