### ISSUE TITLE
Implementación registro de organización de auditorías con drag and drop

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#310]
Se requiere realizar la implementación de registro del orden según organización establecida con el drag and drop en el microcliente. Evaluar la posibilidad de almacenar un array con el id del orden de las auditorías en el plan de tal forma que se evite la necesidad de reorganizar los valores del orden ante cualquier reorganización o eliminación de auditoría.

**Sub Tareas**

- [x] Implementación de almacenamiento de orden de auditorías.
- [x] Integración almacenamiento de registro de auditorías.
- [x] Implementación organización de auditorías en el microservicio MID basado en el array de ids.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Cambios en el Módulo de Auditoría del Plan Anual

#### Modificaciones en `plan_anual_auditoria_crud`:
1. **Nuevo Campo en la Colección `plan_auditoria`**:
   - Se añadió el campo `"auditorias"` en la colección `plan_auditoria` para almacenar la lista de auditorías asociadas a cada plan.
![image](https://github.com/user-attachments/assets/23144b93-8454-4086-b8be-63747e7293f1)


#### Modificaciones en `plan_anual_auditoria_mid`:
1. **Gestión de Auditorías**:
   - Se realizaron ajustes en el servicio `auditoria` para:
     - Obtener los datos de la lista de auditorías desde la colección `plan_auditoria`, obteniendo solo las auditorias activas.
     - Reordenar las auditorías con base a la lista proporcionada por el campo `"auditorias"`.

![image](https://github.com/user-attachments/assets/d35efff3-ce33-4adc-a0f4-3a42b7ababed)
![image](https://github.com/user-attachments/assets/9bc4922c-de3f-47e3-b2c8-89ead1ae779a)


#### Modificaciones en el Cliente:
1. **Actualización de la Lógica del Componente**:
   - Se implementaron los cambios necesarios para la modificacion del `plan_auditoria`, con el nuevo campo `"auditorias"` llenandola con la lista alterada por el drag&drop.
   - Se integró la obtención de las auditorías ordenas desde el MID.

https://github.com/user-attachments/assets/188e3a24-5b5b-4d89-b877-85b34e1b5cb4

**Comment by edwargl7** [comment]
Muy buena implementación y documentación.
