### ISSUE TITLE
Implementación estados del PAA en la fase de programación - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#311]
Se requiere realizar la implementación de visualización de acción según el estado del plan en las vistas de aprobación.

**Sub Tareas**

- [x] Implementación visualización de acción según estado del plan.
- [x] Integración registro de Acta de aprobación del secretario con gestor documental.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances en la implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Implementación visualización de acción según estado del plan


https://github.com/user-attachments/assets/53103489-6ddd-475c-ab70-6051fbde4e0c

**Comment by edwargl7** [comment]
Se revisa inicialmente con @cjgonzalezp y @jcmurilloa pero se debe abordar con más detalle el filtro según el rol cuando este en revisión del jefe (desde la vista del secretario).

**Comment by CristianCGutierrezG** [comment]
### Implementaciones y Cambios en el Cliente

#### Restricciones de Acciones por Rol:
1. **Remoción de Botones de Acciones**:
   - Se eliminaron los botones de acciones en la interfaz para los roles de **Jefe** y **Secretario**, dependiendo del estado del plan.

2. **Filtrado de Planes**:
   - Se implementó un filtro que evita que los planes en estado "Borrador" sean visibles o accesibles para los roles de **Jefe** y **Secretario**.

#### Integración con Gestor Documental:
1. **Registro de Acta de Aprobación**:
   - Se añadió la funcionalidad para el registro del acta de aprobación del **Secretario**, vinculando este proceso con el **Gestor Documental**.

https://github.com/user-attachments/assets/8f36207f-5c89-41a8-9943-a32ce66595c7

**Comment by edwargl7** [comment]
Muy buena documentación, confirmar PR.
