### ISSUE TITLE
Ajustes submódulo fase de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#312]
Se requiere realizar la implementación del botón de descarga del excel plantilla para el registro de auditorías de la fase de programación. Ajustes de variables del gestor documental.

**Sub Tareas**

- [x] Registrar plantilla en el gestor documental asociado a la plantilla.
- [x] Integrar petición de consulta de plantilla y descarga.
- [x] Implementar botón de descarga de plantilla.
- [x] Ajuste de ids de referencia de tipo de documento en el gestor documental.
- [x] Ajuste de rutas de aprobación que mantengan la referencia al plan que se encuentra en revisión.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
#### Gestión de Plantillas:
1. **Registro de Plantilla**:
   - Se registró en el **Gestor Documental** la plantilla asociada:
     ```json
     {
       "Id": 158543,
       "Nombre": "plantilla cargue masivo auditorias.xlsx"
     }
     ```

![image](https://github.com/user-attachments/assets/8ec40228-2375-4650-98f7-a88dab6dafda)

2.  **Variables de Entorno**:
   - Se agregaron las variables de entorno relacionadas con los tipos de documento admitidos por el Gestor Documental y se realizaron los ajuste de ids de referencia  
![image](https://github.com/user-attachments/assets/5c793d14-0727-4b96-9b2a-bf16fefbfbfb)


3. **Cambios en Componente `cargar-archivo`**:
   - Se actualizó el componente para:
     - Permitir la carga de cualquier tipo de documento.
     - Aceptar diferentes IDs de tipo de documento especificados en las variables de entorno.
     - Se realizaron pruebas exitosas con los botones de **Cargue Masivo** y **Cargue de Matriz** en el componente `registrar-auditorias`.


#### Actualización de URLs:
- Las URLs correspondientes a las vistas de **Jefe** y **Secretario**  reciben  la información del ID del plan

![image](https://github.com/user-attachments/assets/998cfe1d-8380-41c1-b4a5-26d3228e2e8d)

**Comment by CristianCGutierrezG** [comment]
### Implementación de la Funcionalidad para la Consulta y Descarga de Plantillas

#### Cambios Realizados:

1. **Descarga desde el Gestor Documental**:
   - Implementada la lógica para realizar peticiones al Gestor Documental y obtener los archivos asociados con base en el ID del documento.

2. **Funciones Desarrolladas**:
   - **Descargar desde Base64**:
     - Decodifica el archivo en formato Base64 y lo convierte a un objeto `Blob`.
   - **Manejo de Diferentes Formatos**:
     - Utiliza el campo `mime-type` del archivo para determinar el tipo MIME y asignar automáticamente la extensión adecuada.
   - **Lógica de Descarga**:
     - Crea un enlace temporal (`<a>`), lo vincula a la URL generada desde el objeto `Blob` y simula un clic para permitir la descarga del archivo.

3. **Pruebas y Estado Actual**:
   - **Implementación Temporal**:
     - La lógica está actualmente integrada de forma estática en el componente `registrar-auditoria`.
     - La funcionalidad es activada al hacer clic en el icono de lista.
   - **Propuesta de Mejora**:
     - Crear un servicio compartido para centralizar la lógica de:
       - Obtención de datos.
       - Conversión del buffer en `Base64`.
       - Manejo de extensiones según el tipo MIME.
     - Esto permitirá la reutilización de la funcionalidad en otros componentes.

https://github.com/user-attachments/assets/64a0d650-c655-4f41-816e-16c2665c225d

**Comment by edwargl7** [comment]
Buena implementación, por favor resolver conflictos del [PR 41](https://github.com/udistrital/plan_anual_auditoria_mf/pull/41).

Buen día @cjgonzalezp nos puedes ayudar a validar por favor.
