### ISSUE TITLE
Diseño formatos de la fase de planeación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#313]
Se requiere realizar el diseño de los formatos de la fase de planeación (PROGRAMA DE TRABAJO, SOLICITUD DE INFORMACIÓN y CARTA DE PRESENTACIÓN).

PROGRAMA DE TRABAJO
![image](https://github.com/user-attachments/assets/adf14d09-9ed8-4d03-a8ae-33a6c6ef35be)

SOLICITUD DE INFORMACIÓN
![image](https://github.com/user-attachments/assets/9fdb184f-bfc0-49f9-a521-9a7f249c2d64)

CARTA DE PRESENTACIÓN
![image](https://github.com/user-attachments/assets/e9767303-2281-4886-be59-663b0f47441b)

**Sub Tareas**

- [x] Diseño HTML del PROGRAMA DE TRABAJO.
- [x] Diseño HTML de la SOLICITUD DE INFORMACIÓN.
- [x] Diseño HTML de la CARTA DE PRESENTACIÓN.
- [x] Registro de plantilla en el microservicio [plantillas_crud_serverless](https://github.com/udistrital/plantillas_crud_serverless).
- [x] Pruebas renderizado.

**Criterios de aceptación**

- [x] Renderizado de las plantillas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Diseño formatos de la fase de planeación**

>[!NOTE]
> Primer diseño, falta ajustar medidas 

![image](https://github.com/user-attachments/assets/289b19e0-1289-4295-a80a-d6e1a4470e24)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Plantilla

![image](https://github.com/user-attachments/assets/5c1f141e-7c46-46c5-a425-abcad4ec23e1)

**Comment by cjgonzalezp** [comment]
Hola @K3vinchaparro veo muy bien el formato diseñado, mi sugerencia sería revisar los estilos (colores, tipo de letra y negritas) comparándolo con el formato PAA ya desarrollado para que queden iguales en estilos.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Plantillas registradas

Programa trabajo: 675214b4e11c6cfdd818c336
Solicitud información: 67521530e11c6cfdd818c338
Carta de presentación: 6752188ddddf9a06db2a0b3c

-
![image](https://github.com/user-attachments/assets/4ca70a3a-1c90-45c6-b6c7-5103eb555bd1)


-
![image](https://github.com/user-attachments/assets/e19a218a-ffd3-49c0-9490-c56a3e045f14)


-
![image](https://github.com/user-attachments/assets/d222987e-7d38-4037-ba04-b1c71dba8891)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Subido a la carpeta de plantillas

![image](https://github.com/user-attachments/assets/26128e97-810d-495e-bf33-ea501d2e56fe)

**Comment by edwargl7** [comment]
Mu buen trabajo.
