### ISSUE TITLE
Ajustes microcliente usuario rol 

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#315]
Se requiere realizar ajustes en la implementación previo al despliegue en ambiente de pruebas y la solicitud de pruebas de carga y seguridad.

**Sub Tareas**

- [x] Validación y eliminación módulo de gestion-roles
- [x] Implementación gestión de autorización a nivel de url
- [x] Pruebas funcionales

**Criterios de aceptación**

- [x] Documentación implementación y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza la verificación del código que se encuentra en el modulo de gestión de roles y se realiza la eliminación del modulo ya que no se estaba usando y se verifica que continue funcionando correctamente después de la eliminación

Se consulta con Cristian el tema de la autorización por url y se revisa el trabajo realizado anteriormente, asi mismo se inicia con la implementación:

![Captura de pantalla 2024-12-09 a la(s) 8 13 33 p m](https://github.com/user-attachments/assets/1ae761b4-34d1-428a-b2bc-42a1d5a132a6)

**Comment by alexhrr** [comment]
Se finaliza la implementación del auth.guard para la autorización a nivel de roles y se verifica su funcionamiento:

https://github.com/user-attachments/assets/7d8b999b-dcb5-4a51-8b1d-ec6fb1789df6

**Comment by alexhrr** [comment]
Se realizan modificaciones en la sección de consulta de usuarios por documento y por email, se verifica su funcionamiento:

https://github.com/user-attachments/assets/35aceb2a-643f-4de8-9818-8f7de5c28fcb

**Comment by edwargl7** [comment]
Buena documentación e implementación. PR resuelto.
