### ISSUE TITLE
Ajuste modelo de datos plan anual auditoria crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#316]
Se requiere realizar el ajuste en el nombre de las colecciones siguiendo los lineamientos "Si el nombre está compuesto por dos o más palabras, cada palabra debe ir en singular y debe utilizarse notación snake case, haciendo uso de _ como separador." [ver lineamiento](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/lineamientos_mongo.md).

**Sub Tareas**

- [x] Ajuste nombre de esquema para garantizar que se cumpla el lineamiento y tenga los mismos nombres que el presentado en el modelo de datos.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación ajuste y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza ajuste en los schemas de plan estado, auditoria auditor, y plan auditoria 
![Image](https://github.com/user-attachments/assets/1d0353ef-db2f-4a86-bfec-02c3f5cffcf5)
![Image](https://github.com/user-attachments/assets/bf72a1a3-5823-4d2b-97a4-2332bf532dce)
![Image](https://github.com/user-attachments/assets/8e97208a-9065-4b53-91b3-ac73608af00c)

**Comment by jucastro94** [comment]
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/72628de6-a0e9-4da9-83fb-aea3990a438c)

---

![Image](https://github.com/user-attachments/assets/ee83bac8-dc1f-4d20-9343-895f029c62ad)
![Image](https://github.com/user-attachments/assets/a96d9748-4105-40fb-9c7e-8a21b57f9cfd)
![Image](https://github.com/user-attachments/assets/1158f6ab-590c-4f4e-8ddc-058f0fc77f6b)

**Comment by edwargl7** [comment]
Finalizado
