### ISSUE TITLE
Integración cargue masivo actividades de una auditoría - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#317]
Se requiere realizar la implementación e integración del registro de actividades con el cargue masivo continuando la Issue #257.

**Sub Tareas**

- [x]  Implementación JSON y endpoint en el microservicio MID para procesamiento del archivo
- [x] Integración con microcliente.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se ajusta entorno para trabajar con servicio lamnda de cargue masivo

- se instala SAM CLI
- se instala python 3.9, necesario para desplegar el lamnda
- se ajusta path para el entorno local

![Image](https://github.com/user-attachments/assets/0cfdb167-62d5-4c48-97a3-3a23cd7aa3ae)

**Comment by jucastro94** [comment]
se realizan correcciones con apoyo de @alexhrr para correcto funcionamieto de lamnda junto a plan auditoria mid en cargue masivo

se corrigen errores apuntado url, variables de entorno y puertos

![Image](https://github.com/user-attachments/assets/a79dc164-77df-40f8-a2e4-2862ccc3531d)
![Image](https://github.com/user-attachments/assets/9500209e-99b2-4930-aac5-714e66e62051)
![Image](https://github.com/user-attachments/assets/87e6519d-c331-4326-bb75-4d815565bc3c)

**Comment by jucastro94** [comment]
se desarrolla controller y service para el procesamiento del cargue masivo en el MID 

![Image](https://github.com/user-attachments/assets/4b0def6b-73c6-4211-8567-a5c96ed7982d)

![Image](https://github.com/user-attachments/assets/31e91677-4594-422a-865b-850d9ba14f8c)

**Comment by jucastro94** [comment]
hacia falta el enrutamiento desde el boton editar de auditorias internas que llevara a la respectiva vista, junto a la vista de actividades

se reliza ajuste enviando el id de la auditoria 
![Image](https://github.com/user-attachments/assets/415bf004-bd2b-4cd8-8db6-aa017f32a87e)
![Image](https://github.com/user-attachments/assets/0de73b40-ecdb-447a-9920-892dbec584ce)
![Image](https://github.com/user-attachments/assets/f6130c59-a170-4eab-8a4b-761cf79e3f34)
![Image](https://github.com/user-attachments/assets/e946ba61-36c5-4915-89b8-11206c72f3c8)

**Comment by jucastro94** [comment]
se implementa cargue inicial de actividades

![Image](https://github.com/user-attachments/assets/955a6aa9-271e-4d46-bb92-c8043a159f25)
![Image](https://github.com/user-attachments/assets/c5106012-e3e3-4478-aa02-ac114f2ada23)
![Image](https://github.com/user-attachments/assets/0ea8114a-7607-49b7-b56f-ab2536528a20)

**Comment by jucastro94** [comment]
se agrega columna folio a archivo xlsx
![Image](https://github.com/user-attachments/assets/323c479b-786f-41a3-be12-88e5466d5ebb)
[cargue masivo actividades.xlsx](https://github.com/user-attachments/files/18138762/cargue.masivo.actividades.xlsx)

**Comment by jucastro94** [comment]
se agrega boton provicional para cargue masivo
![Image](https://github.com/user-attachments/assets/298295ae-af33-40ef-9638-9f52ead6bc79)

se realiza integracion de componente de cargue masivo
![Image](https://github.com/user-attachments/assets/f41e9e37-477e-4bff-a07b-acdb9edf5466)
![Image](https://github.com/user-attachments/assets/6c3e0f43-ebee-4deb-997c-adfb343b18d5)

se desarrolla adaptacion para reutilizacion del metodo cargar  archivo
![Image](https://github.com/user-attachments/assets/89dd2cf4-3497-43ad-86fe-603c04dad409)
![Image](https://github.com/user-attachments/assets/65dedfe5-7c99-4907-af10-65f2d240eb81)

**Comment by jucastro94** [comment]
se realiza prueba funcional

se debe ajustar el formato de las fechas en en xslx

![Image](https://github.com/user-attachments/assets/1dbd3fd4-c7ab-4a85-9fdb-c06bf3aaa424)

se realiza prueba con formato time stamp
![Image](https://github.com/user-attachments/assets/09634a95-2990-4748-a49e-6fa0cd44afd3)

![Image](https://github.com/user-attachments/assets/ba2f0272-2406-4c5d-a82e-02c5b204cde2)
![Image](https://github.com/user-attachments/assets/b6ef40bc-7a92-4d3c-a082-83ecb0d9d915)

**Comment by edwargl7** [comment]
Para el manejo de fecha inicio y fin solo usar dd-MM-yyyy y en complementar el formato para el registro en la función de estructura de cargue masivo. Muy buen trabajo.
![image](https://github.com/user-attachments/assets/1f33bc5f-714f-45c0-a932-8b7df4990ce3).

Resolver conflictos del [PR 51](https://github.com/udistrital/plan_anual_auditoria_mf/pull/51)
