### ISSUE TITLE
Integración submódulo de asignación de auditorías - microservicio plan anual de auditoría CRUD - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#318]
Se requiere realizar la integración entre el microservicio y el microcliente continuando con la Issue #306.

**Sub Tareas**

- [x] Integración actualización de auditores a auditoría microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud) (cambio de Auditor Lider).
- [x] Integración eliminación de auditores a auditoría microservicio [plan_anual_auditoria_crud](https://github.com/udistrital/plan_anual_auditoria_crud).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza el registro del auditor en el crud y se muestra el id en la tabla de consulta de las auditorias:

![Captura de pantalla 2024-12-13 a la(s) 6 06 50 p m](https://github.com/user-attachments/assets/138018f4-4271-44c5-8db7-0611a4d4e04c)

![Captura de pantalla 2024-12-13 a la(s) 6 05 44 p m](https://github.com/user-attachments/assets/0c0cfed4-7f6d-47f6-81bf-a34c7ea4f2b7)

![Captura de pantalla 2024-12-13 a la(s) 8 34 45 p m](https://github.com/user-attachments/assets/1c85ddef-0fc5-4ca5-9e2e-f54a0f71e62b)

**Comment by alexhrr** [comment]
Se realiza la integracion para actualizar el auditor líder en el crud y eliminar un auditor

### Actualización

![Captura de pantalla 2024-12-14 a la(s) 6 57 40 a m](https://github.com/user-attachments/assets/c812ebdd-6a6e-49b1-ab89-3adeba2adb5d)

![Captura de pantalla 2024-12-14 a la(s) 7 46 44 a m](https://github.com/user-attachments/assets/09050e07-4fb1-40cc-ad26-6ec178a6a346)

### Eliminación:

![Captura de pantalla 2024-12-14 a la(s) 8 42 53 a m](https://github.com/user-attachments/assets/de9bbfd8-aace-426d-aef6-8ea28e790f2b)

![Captura de pantalla 2024-12-14 a la(s) 8 45 56 a m](https://github.com/user-attachments/assets/3589aaac-e010-4e26-8278-7266336227d4)

**Comment by edwargl7** [comment]
Resuelto PR, buena documentación de pruebas realizas.
