### ISSUE TITLE
Implementación servicio de gestor documental

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#319]
Se requiere realizar la implementación del service del gestor documental que permita registrar/cargar un documento (retorne el id del gestor documental, el enlace) basado en el tipo de documento y la consulta del documento usando el enlace como parámetro. Adicional, el control de excepciones y el retorno de estás para la correcta visualización en caso de algún fallo.

**Sub Tareas**

- [x] Implementación del service gestor documental.
- [x] Refactor del consumo del gestor documental.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación de la implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Creación de Nuevos Servicios

#### Servicios Implementados:

1. **`nuxeoService`**:
   - Responsable de manejar la lógica de las peticiones al gestor documental **Nuxeo**.
   - Funciones principales:
     - **obtenerUrlFile(base64, minetype)**: Convierte un archivo codificado en Base64 a un objeto URL utilizable en el navegador. Crea un archivo File a partir de los datos Base64 y el tipo MIME, y genera una URL temporal con URL.createObjectURL
     - **fileABase64(file)**: Convierte un archivo del tipo File en una cadena codificada en Base64 utilizando la API FileReader. Maneja los errores potenciales durante la lectura del archivo.
     - **guardarArchivos(files)**:
          - Procesa una lista de archivos, detecta si ya están en formato Base64 o si necesitan ser convertidos.
          - Prepara los datos para enviarlos a un servicio de carga documental (gestorDocumentalService.postAny).
          - Publica un flujo (Subject) que emite los documentos cargados una vez que todos los archivos han sido procesados y subidos.

2. **`referenciaPdfService`**:
   - Servicio para gestionar las referencias de los documentos almacenados en **Nuxeo**.
   - Funciones principales:
     - **guardarReferencia(nuxeoResponse, referencia_tipo, tipo_id)**:
          - Construye un payload que contiene información de la referencia, incluyendo su tipo, ID, enlace, y otros detalles obtenidos de la respuesta de Nuxeo (nuxeoResponse).
          - Si el documento ya existe, actualiza su información a través de un PUT.
          - Si no existe, crea un nuevo registro mediante un POST.
---

#### Modificaciones en Componentes:

1. **`cargar-archivo`**: 
- Cargue Masivo
![image](https://github.com/user-attachments/assets/ec598290-5fef-4e8a-bb3e-58364ff68624)

- Matriz funcion publica
![image](https://github.com/user-attachments/assets/2de7063c-e73a-40b1-981c-b9b4932f2084)

2. **`pdf-visualizador`**:

![image](https://github.com/user-attachments/assets/8de1fda0-e173-4aa5-a1cc-318ecb7fae7d)

3. **`modal-aprobacion-secretrio`**:

![image](https://github.com/user-attachments/assets/a4c0b703-4c34-4e33-8dfe-28076759a18f)

**Comment by CristianCGutierrezG** [comment]
#### Nuevas Funciones en Servicios:

1. **`nuxeoService`**:
   - **getByUUID(uuid: string): Promise<string>**
       -  Realiza una solicitud al servicio gestorDocumentalService para obtener el documento correspondiente al uuid proporcionado.
       - Si la respuesta no contiene el campo file, lanza un error.
       - Si la respuesta es válida, devuelve el archivo en formato Base64.
       - Si ocurre un error en cualquier parte del proceso, captura y lanza un error indicando que no se pudo obtener el archivo.

2. **`referenciaPdfService`**:
   - **consultarDocumento(planAuditoriaId: string, tipoId: number): Observable<string>**
        - Realiza una consulta al servicio planAnualAuditoriaService para buscar un documento que coincida con el planAuditoriaId y tipoId.
        - Si la respuesta contiene el campo nuxeo_enlace, lo retorna.
        - Si no se encuentra o hay un problema en la respuesta, lanza un error indicando que el campo nuxeo_enlace no fue encontrado.
        - En caso de error en la consulta, maneja el error y devuelve un mensaje adecuado.

---

#### Modificaciones en Componentes:

Se adaptan los componentes de revisión-Jefe revisión-Secretario y ModalVerDocumentosPlanComponent para que obtengan la información del enlace y el archivo utilizando los nuevos servicios

![image](https://github.com/user-attachments/assets/889b74aa-0e5f-4ce7-a2a6-b5d8a5bd516e)

https://github.com/user-attachments/assets/b0f20a61-eb49-4a4b-9a28-14ca070c44da

Se adapta la descarga de plantilla para que obtenla el base64 con el enlace


## Notas:

Hubo problemas a momento de guardar los ID correspondientes a los documentos en la colección
La colección de Documentos solo permite dos tipos de archivos

![image](https://github.com/user-attachments/assets/a8da74b4-9109-4093-bd3a-e99adc4be095)

**Comment by edwargl7** [comment]
La referencia_tipo es usado para identificar la referencia la colección a la que se requiere guardar el registro.

El tipo asociado a parámetros CRUD que permite identificar que tipo de documento se trata de almacenar es el campo tipo_id.
![image](https://github.com/user-attachments/assets/17b3d304-2f7d-4135-ac1b-8940b0d8f746)

Se resuelve el PR. Muy buen trabajo. Se debe revisar la convención para el nombre de las funciones.
