### ISSUE TITLE
Ajuste modelo de datos relacional Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#32]
Se requiere realizar el ajuste del modelo de datos de Sísifo v2 basado en las recomendaciones del equipo DBA, los lineamientos del [Modelo de Datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md), el avance en la [Issue #25](https://github.com/udistrital/sisifo_documentacion/issues/25) y la identificación de campos nuevos de la [Issue #31](https://github.com/udistrital/sisifo_documentacion/issues/31).

**Sub Tareas**

- [x] Ajustes al modelo creado basado en los formularios del sistema actual, en el que se debe tener presente las siguientes observaciones:
    - Agregar dependencia al plan de mejoramiento.
    - uq_codigo_de_auditoria_plan_de_mejoramiento -> uq_codigo_de_auditoria, se debe validar con el usuario final si es el código de auditoria, de esa manera se maneja como se sugiera, si es el código del plan de mejoramiento, se puede cambiar a código dado que se encuentra en la tabla de plan de mejoramiento.
    - nombre_del_plan, nombre_hallazgo -> nombre, dado que ya se encuentra dentro de la tabla correspondiente, por lo tanto, no es necesario agregar el nombre de la tabla.
    - origen_plan_mejoramiento_id, sub_origen_plan_mejoramiento_id -> posiblemente puede cambiar por requerimientos del usuario. De lo contrario se puede remover el nombre de la tabla ya que no presenta otros campos con nombre similar.
    - actividad -> descripcion
    - uq_codigo_actividad_actividad -> Validar con el usuario si es requerido o se puede manejar con el id.
    - aprobacion_jefe_dependencia -> aprobado, y agregar un campo que almacene el id del usuario que realiza la aprobación (validar si existen otras aprobaciones).
- [x] Agregar campos nuevos identificados y aprobados en la [Issue #31](https://github.com/udistrital/sisifo_documentacion/issues/31).
- [x] Ajustar tablas de histórico que permitan ver claramente la relación entre los datos de los procesos (auditorias, planes, hallazgos, actividades, avances) y la designación de nuevos usuarios en los roles de auditor, jefe de dependencia, ejecutor. Relación muchos a muchos entre estas tablas.

**Criterios de aceptación**

- [x] Ajustes al modelo de datos de Sísifo v2 del módulo **Plan de mejoramiento** basado en las observaciones dadas de la Issue 25.
- [x] Adición de campos nuevos identificados en la Issue 31.

**Requerimientos**

- [x] Culminar la  [Issue #31](https://github.com/udistrital/sisifo_documentacion/issues/31)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Actualización del modelo de datos Sísifo v2.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se añaden añaden los campos segun la solicitud y esta en proceso la adicion de los campos identificados en la [issue #31](https://github.com/udistrital/sisifo_documentacion/issues/31)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ba5fa47b-ff93-4721-a586-3bc25a5405c1)

**Comment by jucastro94** [comment]
se finaliza la adicion de campos 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f502654c-29cb-47df-b3f2-4a336a2c2af9)

**Comment by jucastro94** [comment]
se diseña tabla adicional para esclarecer la relación entre los datos de los procesos y la designacion de usuarios, tambien normalizando y evitando redundancias

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7a4458b2-119b-4d5f-865f-bba9722ee08e)

**Comment by jucastro94** [comment]
se carga version 4 del modelo de datos a carpeta en one drive: [modelo de datos V4](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EbsOH5lHJw1Bsftrn8L51Z4Bzj-NKIxJkyMTdN76bdTN2w?e=NmTmZc)

**Comment by edwargl7** [comment]
Se realiza la revisión del diagrama, se observan algunos ajustes adicionales:

- Mantener los nombres de las tablas en minúsculas.
- **Plan mejoramiento**

> - Cambiar nombre de la tabla plan_de_mejoramiento a plan_mejoramiento

-

**Comment by edwargl7** [comment]
Se realiza la revisión del diagrama, se observan algunos ajustes adicionales:

- Mantener los nombres de las tablas en minúsculas.
- **Plan mejoramiento**
> - Cambiar nombre de la tabla plan_de_mejoramiento a plan_mejoramiento
> - El campo de fuentes se debe remover mientras se establece por requerimientos si todos son selectores y si cambian para evaluar como manejar esa tipología.
- **Actividad**
> - Remover campo actividad dado que se agrego el campo de descripción.
> - El campo indicadores se revisará con requerimientos para dividirlo en un campo de texto y numérico o solo texto.
- **Avances**
> - Cambiar campo de aprobación jefe dependencia por aprobado y agregar el campo aprobado_por para permitir la posibilidad de mantener id de rol diferente al jefe de dependencia.

Muy buen trabajo, se debe ajustar, y se evaluará la presentación del modelo de datos del plan de mejoramiento dado que puede sufrir cambios por los nuevos módulos de Auditoría que dan origen al plan de mejoramiento.
