### ISSUE TITLE
Implementación visualización de formulario desde el rol auditor experto

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#320]
Se requiere realizar la implementación de la visualización del formulario desde el rol auditor cuando el plan se encuentre en un estado diferente a los de edición.

**Sub Tareas**

- [x] Implementación vista de edición.
- [x] Integración acción de visualización de información básica y registro de auditorías.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Implementación de la Vista de Edición

1. **Actualización de Acciones Según el Estado del Plan**:
   - Modificada la lógica para ajustar las acciones disponibles para el auditor cuando el plan se encuentra en un estado diferente a **Borrador** o **Revisión**.

2. **Integración de Visualización y Registro**:
   - Actualizaciones realizadas en los componentes:
     - **`registrar-auditorias`**y  **`registrar-plan`**:
       - Deshabilitación dinámica del formulario e implementada lógica para no renderizar ciertos elementos del formulario cuando no son aplicables según el estado del plan.


https://github.com/user-attachments/assets/42afef0b-494d-4507-b94f-204a36f5d228

**Comment by edwargl7** [comment]
Revisado con @cjgonzalezp y se aprueba la propuesta para visualización se recomienda por parte de Carlos el nombre de "Ver Documentos" para el botón nuevo de "Ver Plan" y que este cuente con la visualización similar a la vista de aprobación como modal (solo regresar) y dentro de la vista de auditorías también se encuentre un botón "Ver Documentos" que muestre la vista vista de "Ver Documentos"

**Comment by CristianCGutierrezG** [comment]
### Componente modal Ver Documentos

Se crea un nuevo modal para permitir visualizar los documentos por parte del auditor cuando no se encuentre ni en borrador o rechazo.

 Se implementa la funcionalidad del nuevo modal en las acciones de consulta-plan y con un nuevo botón en el RegistrarAuditoriasComponente.


https://github.com/user-attachments/assets/dc4d13db-819b-4dde-91e2-12b8447d81ad

**Comment by edwargl7** [comment]
Se resuelve el PR. Muy buen trabajo. Se revisará con @cjgonzalezp si se puede remover la columna de Documento.
