### ISSUE TITLE
Implementación endpoint base de generación de programa PDF

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#321]
Se requiere realizar el desarrollo en el microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid) que consulte la información de las actividades asociadas a una auditoría y complemente lo datos paramétricos para el formato del programa.

![image](https://github.com/user-attachments/assets/d013043e-d46f-41c9-9ad1-00ffef28b61c)

**Sub Tareas**

- [x] Implementación endpoint base que generé el JSON para el renderizado del programa de trabajo integrando parametros CRUD.
- [x] Integración en el microcliente para previsualización del documento PDF generado con los datos parciales.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentacion implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Implementación endpoint base de generación de programa PDF**

>[!NOTE]
> Creación de servicio en el mid para la plantilla de plan trabajo

**Comment by K3vinchaparro** [comment]
>[!NOTE]
>Integración de la plantilla plan trabajo a la vista


https://github.com/user-attachments/assets/02b64847-9d96-4e49-bb6b-3035aa286efe

**Comment by edwargl7** [comment]
Resueltos PR. Muy buen trabajo.
