### ISSUE TITLE
Estabilización microservicio plan anual de auditoria CRUD

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#322]
Se requiere realizar la validación del error en el microservicio que no permite el consumo del controlador de auditor.

**Sub Tareas**

- [x] Validacion y despliegue en caso de ser necesario.

**Criterios de aceptación**

- [x] Resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza validacion en local de rama release/0.1.0 , funciona correctamente
![image](https://github.com/user-attachments/assets/89472c1b-fac8-4257-a80a-baffb57cd046)
![image](https://github.com/user-attachments/assets/96c18b92-2ef6-4296-bf46-b03122e54c0f)
![image](https://github.com/user-attachments/assets/cfe5791a-eca7-4778-b058-b4de8efc918f)

**Comment by jucastro94** [comment]
se realiza validacion de version de pruebas en intranet, no funciona endpoint de auditor
![image](https://github.com/user-attachments/assets/6a1e3749-db86-485b-ae9f-956852cf69d0)

funcionan demas endpoints
![image](https://github.com/user-attachments/assets/7770f7f3-8139-4e9a-92a0-129903319a5c)
![image](https://github.com/user-attachments/assets/bb518542-9932-4cdb-b8c3-2d880eb9fea6)

**Comment by jucastro94** [comment]
se valida re despliegue, no funciona

no se evidencia modulo de auditor, ni otros cambios de las ultimas versiones como por ejemplo, campo actual en  plan-estado, campo de nuexo_id en documento entre otros, en el swagger del despliege en intranet

![Image](https://github.com/user-attachments/assets/b6a50d83-5a73-4ddb-a9e0-7376bb93ee9e)

**Comment by jucastro94** [comment]
se realiza validacion luego de ajustes

ya se visualiza en swagger el modulo de auditor
![Image](https://github.com/user-attachments/assets/a0366811-9660-4ff9-8ded-88a636eb0aa7)

ultimas actualizaciones tambien se visualizan 
![Image](https://github.com/user-attachments/assets/b0aea2b1-b89c-42c4-b8d0-82a73f4ba905)
![Image](https://github.com/user-attachments/assets/630acc85-1ce7-48d7-b449-97b0bd28a57b)

**Comment by jucastro94** [comment]
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/bd0e170c-b5dc-4794-bb9c-bb48a3f744f1)
![Image](https://github.com/user-attachments/assets/b56dd6ac-68bb-48bd-b369-1862489866aa)
![Image](https://github.com/user-attachments/assets/0f59839c-c7a8-43d0-84fa-a1512c2b92b2)
![Image](https://github.com/user-attachments/assets/bdc3fc0f-75cf-4529-8639-33678fe8b313)
![Image](https://github.com/user-attachments/assets/604e0cb1-6f9d-487b-9c35-aa6244ea83e7)
![Image](https://github.com/user-attachments/assets/a8c308f7-1963-48f1-b903-7455d222057c)

**Comment by edwargl7** [comment]
Ajustes realizados en conjunto con el equipo de infraestructura. Se resuelven los errores y despliegue pendiente. Además, se observa las pruebas realizadas de forma adecuado. Muchas gracias.
