### ISSUE TITLE
Agregar campo nombre_wso2 al modelo de datos de usuario rol crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#323]
Se requiere realizar la actualización del modelo de datos de usuario rol, la creación del script para agregar el nuevo campo a la tabla. Ajuste del CRUD de roles en el microservicio [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud).

**Sub Tareas**

- [x] Ajuste endpoint de registro, edición y visualización de roles en el microservicio [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actualiza modelo de datos, se carga a README y carpeta del proyecto
![Image](https://github.com/user-attachments/assets/8e8647d6-1bc0-4bdf-ac38-a470368dd1a7)

**Comment by jucastro94** [comment]
se ajusta modelo en usuarios_rol_crud ![Image](https://github.com/user-attachments/assets/e4d481e8-81c6-4f39-85b0-94a9349485b5)

**Comment by jucastro94** [comment]
se crea script para la generacion del nuevo campo en la base de datos

[alter.table.txt](https://github.com/user-attachments/files/18069364/alter.table.txt)
![Image](https://github.com/user-attachments/assets/bdab8e88-3564-4e1d-8aa7-157476ff1502)

![Image](https://github.com/user-attachments/assets/e369dbfd-3b7a-4efc-af6a-1de60bee256f)

**Comment by jucastro94** [comment]
se realiza prueba funcional

GETALL
![Image](https://github.com/user-attachments/assets/38a15e14-d037-496a-8784-ece6b913dd2e)

---

POST
![Image](https://github.com/user-attachments/assets/1e2dcc7c-8938-442b-a9ec-ec48883fad36)

---

GET
![Image](https://github.com/user-attachments/assets/abe5a884-9109-4310-8115-d2b086b87c82)
![Image](https://github.com/user-attachments/assets/6041cf54-8313-4e1e-a078-631633dc324d)

---

PUT
![Image](https://github.com/user-attachments/assets/c63435b5-3da1-4da5-b203-5ca8e55588e7)
![Image](https://github.com/user-attachments/assets/2432c744-23d1-4b12-aa8a-bcd27d684aaa)

---

DELETE
![Image](https://github.com/user-attachments/assets/5639394c-b796-42b1-aab2-a719d374e1c7)
![Image](https://github.com/user-attachments/assets/64e0f680-f93f-49e1-9071-0d4ada76263c)

**Comment by edwargl7** [comment]
Se requiere ajustar el campo a la tabla rol por favor y se trabajará el ajuste en el microcliente para complementar la integración de este campo.
