### ISSUE TITLE
Integración vista de consulta de auditorías en el módulo de planeación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#324]
Se requiere realizar la integración de la vista de consulta de auditorías del módulo de planeación entre el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf) y el microservicio mid [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid)

![image](https://github.com/user-attachments/assets/7ad54b6a-f6e3-4669-af22-13ae56b76e7b)

**Sub Tareas**

- [x] Integración consulta de auditorías por vigencia.
- [x] Integración acción de edición de auditoría.
- [x] Integración paginado.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación avances implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Integración vista de consulta de auditorías en el módulo de planeación**

>[!NOTE]
> Integración de edición de auditoria


https://github.com/user-attachments/assets/9dc3fbff-ccce-4027-b5a8-b06107b3ac6e

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Implementación de paginador


https://github.com/user-attachments/assets/a6f99c91-e041-468e-8db1-1a5210c75cc4

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Servicio de custom paginador, para sobrescribir valores por defecto

Esto permite cambiar valores por defecto del paginador y queden globales para toda la aplicación 

```ts
import { MatPaginatorIntl } from "@angular/material/paginator";

export class CustomPaginadorIntl extends MatPaginatorIntl {
  override itemsPerPageLabel = "Elementos por página:";

  override getRangeLabel = (page: number, pageSize: number, length: number) => {
    if (length === 0 || pageSize === 0) {
      return `0 de ${length}`;
    }
    const startIndex = page * pageSize;
    const endIndex = Math.min(startIndex + pageSize, length);
    return `${startIndex + 1} - ${endIndex} de ${length}`;
  };
}

```

**Comment by K3vinchaparro** [comment]
>[!WARNING]
> Examinar el paginado cache 

- Hacerlo guardando clave valor de offset y limit
- Hacerlo guardando por index
- No hacerlo para actualización de datos, así sea con mas llamadas http

Igualmente las anteriores (1, 2) si no se implementan observables no se actualizarían correctamente, las 3 tienen pros y contras

**Comment by edwargl7** [comment]
Muy buen trabajo. El servicio paginador se puede revisar con @cjgonzalezp dado que el comportamiento es diferente en la vista de consulta del plan, auditorías, actividades y hallazgos. Pero puede ser un componente que permita uniformidad.

Se evaluará las ventajas y desventajas del cache.
