### ISSUE TITLE
Revisión y ajuste de la documentación técnica del sistema

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#325]
Se requiere realizar el apoyo en la revisión y ajuste de la documentación ténica con base a la elaborada en Pólux: [documentación tecnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbJ-FyQnHu1IqMFJJg_1SpsBVO193db6c_rNPMBPD-tWkQ) que se presenta a funcionamiento 

**Sub Tareas**

- [x] Establecer listado de documentos a proyectar,
- [x] Apoyar en la actualización de la documentación técnica.
- [x] Exponer documentos a equipos SoS

**Criterios de aceptación**

- [x] Lista de chequeo proyectada.
- [x] Documentación realizada y almacenada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se realiza la revisión de varios proyectos para recopilar documentos que puedan ser utilizados para la documentación de Sísifo v2.

Se toma como base los siguientes:

- [DESCRIPCIÓN TÉCNICA DEL DESARROLLO MÓDULO DE POLUX](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EbJ-FyQnHu1IqMFJJg_1SpsBVO193db6c_rNPMBPD-tWkQ?e=2NfGz3)
- [DESCRIPCIÓN TÉCNICA DEL SISTEMA DE REVISION CUMPLIDOS PROVEEDORES](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ESD9I23i7eJJj8Lt42W3bc4BxHRIKO_hTy-f-rmN-oIfTg?e=Wwt0of)
- [Documento Técnico - Módulos de Inscripción y Admisión para posgrados](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EaoojmImWIlAsAog85RBonUBS8FWqeqUuf7ZRmkP9MvNDw?e=QYHTBE)
- [Pruebas funcionales - Certificaciones DVE](https://github.com/udistrital/Cumplidos_y_certificaciones_documentacion/issues/237)

Basado en esa documentación se crean las Issues #333 y para el inicio de la documentación de Sísifo v2 con unos pequeños ajustes en los formato encontrados.

**Comment by cjgonzalezp** [comment]
Buen día,

A continuación, relaciono listado de documentos necesarios para la entrega del sistema

**LISTADO DOCUMENTOS ENTREGABLES**
1.	Diagrama modular - OK
2.	Diagrama de proceso general - Pendiente pasarlos a esta carpeta
3.	Formato Aceptación de entregables - Se crea documento en Word para documentar
4.	Documento descripción técnica del desarrollo - Se crea documento en Word para documentar

Adicionalmente, se crea una carpeta en OneDrive para consolidar la documentación y se organizó cada uno de los documentos para alimentar la información requerida. 

**Adjunto enlace**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et8uVf1CnLtKnrl1dlQPcv0B1oEu7n8V-8U4zAUvnBfoLQ?e=3xOzG0


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, este será el punto de partida para la consolidación de este requerimiento necesario para despliegue.
