### ISSUE TITLE
Implementación paginado vista de consulta del PAA

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#326]
Se requiere realizar la implementación de paginado en la vista de consulta del PAA en la fase de programación en el microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf).

**Sub Tareas**

- [x] Implementar paginado con valores de 5, 10, 25.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se inicia con la implementación del paginado para la consulta del PAA:

![Captura de pantalla 2024-12-11 a la(s) 10 22 14 p m](https://github.com/user-attachments/assets/16c7502d-e79b-4c06-b181-94f54c6c418f)

![Captura de pantalla 2024-12-11 a la(s) 10 24 15 p m](https://github.com/user-attachments/assets/4cfef6ce-db3b-4198-b859-9da5643b5472)

**Comment by alexhrr** [comment]
Implementación paginación consulta PAA

Se realiza la paginacion y se modifican lis indices de la tabla, tambien se verifica la paginacion al crear un nuevo plan

https://github.com/user-attachments/assets/fe4935c1-430a-4325-a6cb-7eef384cb258

**Comment by edwargl7** [comment]
Resolver conflictos del PR por favor, buena implementación y documentación.

**Comment by edwargl7** [comment]
Resueltos conflictos y realizado el PR.
