### ISSUE TITLE
Ajuste endpoint de renderizado

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#327]
Se requiere realizar el ajuste del endpoint de renderizado que actualmente se llama pdf por generar-pdf. Y ajustar la integración de los servicios que consumen el endpoint.

**Sub Tareas**

- [x] Actualizar ruta del endpoint.
- [x] Actualizar swagger.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación ajustes implementados y resultados pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actualiza endpoint y swagger
![Image](https://github.com/user-attachments/assets/a5691da4-68cd-4a4a-8fab-0cd2a2207a59)
![Image](https://github.com/user-attachments/assets/b16e0138-96bc-423e-98e7-e8543570f7e3)

**Comment by jucastro94** [comment]
se realiza acualizacion de endpoint para peticion en platillas_mid

**Comment by edwargl7** [comment]
Se realiza la validación del código y se resuelven los PR. Muy buen trabajo.
