### ISSUE TITLE
Revisión ventajas y desventajas en el cache para la vista de consulta en el microcliente del PAA

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#328]
Se requiere realizar el análisis de las ventajas y desventajas de emplear el 'cache' en las vistas de consulta en conjunto con el paginado. Se debe revisar en que momentos no afecte con la correcta visualización ante diferentes eventos de otros usuarios (actualizaciones de estados, creación o cargue masivo de nuevos registros). 

**Sub Tareas**

- [x] Revisión ventajas y desventajas de la vista de consulta de los planes de auditoria teniendo en cuenta roles y acciones.
- [x] Revisión ventajas y desventajas de la vista de consulta de las auditorías teniendo en cuenta roles y acciones.
- [x] Documentación borrador de ventajas y desventajas.

**Criterios de aceptación**

- [x] Documentación inicial de ventajas y desventajas.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Documentación Borrador: Ventajas y Desventajas del Uso de Caché en Consultas con Paginador**

---

>[!TIP]
> #### **Ventajas**
- **Reducción de Peticiones HTTP**  
  Evita consultas repetidas al servidor al navegar entre páginas ya consultadas. Mejora la velocidad de respuesta y la experiencia del usuario.

- **Optimización de Recursos**  
  Menor carga en el servidor y ahorro de procesamiento.

- **Respuesta Rápida**  
  Carga más eficiente de datos desde el caché del componente

- **Mejora Experiencia de Usuario**  
  Navegación fluida en roles de solo lectura, como **auditores**.

---

>[!CAUTION]
> #### **Desventajas**
- **Datos Desactualizados**  
  Si hay actualizaciones, creación o eliminación de registros, el caché puede mostrar información antigua. Afecta roles con permisos de modificación (ej. administradores).

- **Sobrecarga de Memoria**  
  Requiere recursos adicionales en cliente o servidor para almacenar caché.

- **Complejidad de Implementación**  
  Necesita una lógica para implementar cache

---

>[!IMPORTANT]
> #### **Conclusión:**
En el caso del paginador, ya sea con o sin caché, es necesario recargar la página o navegar a través del paginador para ver los cambios recientes. Aunque el uso de caché en el paginador mejora el rendimiento al evitar consultas repetidas, los datos siempre deben estar actualizados. Sin un sistema como los sockets, la página debe recargarse para reflejar los cambios realizados por otros usuarios, independientemente de si se utiliza caché o no.

**Comment by edwargl7** [comment]
Se terminará de revisar si aplicamos el cache dados los diferentes casos que aplican.
