### ISSUE TITLE
Remover token del microcliente usuario rol y ajustes logs

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#329]
Se requiere realizar el ajuste en el microcliente [usuario_rol_mf](https://github.com/udistrital/usuario_rol_mf) similar al implicit authentication del microcliente [plan_anual_auditoria_mf](https://github.com/udistrital/plan_anual_auditoria_mf/blob/develop/src/app/core/services/implicit_autentication.service.ts) dado que se remueve el token del environment. Ajustes generales en el microcliente.

**Sub Tareas**

- [x] Ajuste nombre del script.
- [x] Ajuste implementación del script implicit_authentication removiendo la variable TOKEN.
- [x] Ajustes en el módulo de consulta (mat error y logs).
- [x] Ajuste funciones no usadas (applyDocumentFilter).
- [x] Ajuste errorManager para manejo adecuado de errores no controlados, ejemplo [errorManager](https://github.com/udistrital/gestion_contractual_mf/blob/develop/src/app/managers/errorManager.ts)
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realizan los siguientes ajustes en el código del microcliente de usuarios

Se remueve la variable TOKEN del servicio implicit-autentication que hacia referencia a las variables de entorno.

Se realiza el ajuste y revision de las funciones de filtro en la consulta de usuarios ya que no se van usar en el funcionamiento del mf (applyDocumentFilter, applyRoleFilter)

Se revisan los console.log y mat-error del código y se eliminan los que no son necesarios por el momento.

Se inicia el ajuste del manejo de errores en el errorManager según el código de ejemplo

Se verifica el funcionamiento del microcliente después de realizar los cambios en el codigo

**Comment by alexhrr** [comment]
Se modifica el errorManager para mostrar al usuario los errores encontrados en la ejecución del mf:

![Captura de pantalla 2024-12-17 a la(s) 7 49 51 p m](https://github.com/user-attachments/assets/7bf6dcb1-bb2f-4df4-8752-db0c3efb12ff)

Se realiza el ajuste en la paginación para mostrar los textos en español:

![Captura de pantalla 2024-12-17 a la(s) 7 43 33 p m](https://github.com/user-attachments/assets/2db3de75-5326-4163-94fa-784aa70c03ac)

![Captura de pantalla 2024-12-17 a la(s) 7 44 28 p m](https://github.com/user-attachments/assets/7fea10e3-c50e-4a0a-9e9d-21a98f80a78f)

![Captura de pantalla 2024-12-17 a la(s) 7 44 10 p m](https://github.com/user-attachments/assets/6a93860a-a506-4869-86a1-dec7e524a686)

Se verifica el funcionamiento general:

https://github.com/user-attachments/assets/ec219cd6-d8ed-4d7b-af74-2815f56e8d4e

**Comment by edwargl7** [comment]
Resuelto PR. Muchas gracias.
