### ISSUE TITLE
División módulo de configuración Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#33]
Se requiere realizar la división del módulo de Configuración separando la Gestión de Usuarios y Roles de la funcionalidad de Gestión de parámetros con el fin de mantener una agrupación adecuada de los submódulos que los conforman.

**Sub Tareas**

- [x] Creación de una nueva versión del diagrama de microclientes del módulo de configuración [Issue 7](https://github.com/udistrital/sisifo_documentacion/issues/7) en la que evidencie la división del módulo.
- [x] Actualización del [documento de la lista de funcionalidades](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQplKSjhFnpAuWiAv-mj0YwB90SHk7qAsCLLxC2BBtnsXA?e=DUEZAh) que permita evidenciar la división del módulo.

**Criterios de aceptación**

- [x] Creación nueva versión del diagrama de microclientes con la división del módulo de configuración.
- [x] Actualización lista de funcionalidades con la división del módulo de configuración.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Creación nueva versión del diagrama de microclientes.
- [x] Actualización lista de funcionalidades.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se crea el nuevo modulo de gestión de usuarios separándolo del modulo de configuración 
![SISGPLAN Microfrontends-Configuacion drawio](https://github.com/udistrital/sisifo_documentacion/assets/48999834/660796aa-e575-4bc2-80cf-b94c064c9388)


Link del diagrama: 
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EQ24UNkayeRKtUmFWoe0OF0B05JcFVQ9CY_m-EA6XyHV4A?e=mhAais

**Comment by edwargl7** [comment]
Se realiza la revisión y se da por terminada. Buen trabajo y buena documentación de la Issue.
