### ISSUE TITLE
Ajuste campo nombre_wso2 al modelo de datos de usuario rol crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#330]
Se requiere realizar la actualización del modelo de datos de usuario rol, la creación del script para agregar el nuevo campo a la tabla. Ajuste del CRUD de roles en el microservicio [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud).

**Sub Tareas**

- [x] Ajuste endpoint de registro, edición y visualización de roles en el microservicio [usuario_rol_crud](https://github.com/udistrital/usuario_rol_crud).
- [x] Actualización script de base de datos.
- [x] Actualización del modelo de datos.
- [ ] Pruebas funcionales.
- [ ] Actualización de roles actuales.

**Criterios de aceptación**

- [ ] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actualiza modelo de datos
![Image](https://github.com/user-attachments/assets/c637fd31-b01d-4a9c-892c-c312e46c6336)

se crea script para la modificacion del campo en BD
[alter.table (1).txt](https://github.com/user-attachments/files/18158664/alter.table.1.txt)

se raliza modificacion en ms
![Image](https://github.com/user-attachments/assets/68933eee-8b0a-4842-9d8f-1f02d935899a)
![Image](https://github.com/user-attachments/assets/5ab31874-6369-4c03-b1cf-488d00ba7ea9)

se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/5f5a7d1d-b51a-43d0-af76-76b725eb542c)
![Image](https://github.com/user-attachments/assets/7526503a-0c3f-494b-8b07-edd4ba30539f)

**Comment by edwargl7** [comment]
Pendiente actualizar sql.

**Comment by jucastro94** [comment]
se realizan correcciones al modelo de datos segun observaciones de DBA
![Image](https://github.com/user-attachments/assets/dcc77ba8-ca98-453e-a67b-bd38d065563f)

**Comment by edwargl7** [comment]
Finalizada, depende del despliegue para culminar pruebas. Muchas gracias.
