### ISSUE TITLE
Integración campo nombre_wso2 al microcliente usuario rol

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#331]
Se requiere realizar la integración del campo nombre_wso2 que almacena el nombre del rol que se usa en wso2 y el campo nombre actual se mantiene para el usuario permitiendo mantener nombres diferentes de cada al usuario y logs vs los requeridos para la correcta integración con wso2 [usuario_rol_mf](https://github.com/udistrital/usuario_rol_mf).

**Sub Tareas**

- [x] Ajuste de roles y permisos con los roles de Sísifo (Edicion ADMIN_SISIFO, AUDITOR_EXPERTO) (Consulta JEFE_CONTROL_INTERNO).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza el ajuste de los permisos mediante los roles creados 

Edición - AUDITOR_EXTERNO

![Captura de pantalla 2024-12-18 a la(s) 6 39 00 p m](https://github.com/user-attachments/assets/89d43882-484a-401a-a5ce-5b37428c06b3)

Consulta - JEFE_CONTROL_INTERNO

![Captura de pantalla 2024-12-18 a la(s) 6 38 25 p m](https://github.com/user-attachments/assets/81639309-1c78-4246-83a3-6c0ad367068e)

**Comment by edwargl7** [comment]
Completada primera parte pendiente despliegue para culminar.
