### ISSUE TITLE
Implementación endpoint de reemplazo de valores en HTML 

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#332]
Se requiere realizar la implementación de un nuevo endpoint en el microservicio [renderizado_plantillas_html](https://github.com/udistrital/renderizado_plantillas_html) siguiendo los lineamientos. Este nuevo endpoint debe solamente reemplazar las variables en el HTML suministrado y retornar el nuevo HTML.

Ejemplo:

```python
from jinja2 import Template

template = Template(html_template)
rendered_html = template.render(context)
```

**Sub Tareas**

- [x] Implementación nuevo endpoint renderizar-HTML.
- [x] Actualizar documentación del swagger.
- [x] Pruebas funcionales locales.
- [x] Pruebas funcionales en ambiente de pruebas.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Ejemplo:

```python
template_str = """
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>Welcome, {{ username }}!</h1>
</body>
</html>
"""

template = Template(template_str)
context = {'title': 'Variable nuev {{ complemento }}', 'username': 'Juan'}

html_output = template.render(context)
```

**Comment by jucastro94** [comment]
crea nuevo enpoint que devuelve string del nuevo html
![Image](https://github.com/user-attachments/assets/05a0f053-6c87-4f68-9951-e95985f2b7c6)

se reutiliza metodo que ya ejecutaba la logica requerida
![Image](https://github.com/user-attachments/assets/f40ae184-adbc-4dbb-a5e4-ec4377e88c08)


se actualiza swagger
![Image](https://github.com/user-attachments/assets/c261d1e8-8475-485f-b458-9582cd8c5662)
![Image](https://github.com/user-attachments/assets/58a1a6f9-d038-44c1-a954-06b957c2e1ab)

**Comment by jucastro94** [comment]
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/35ceb6ca-ad41-4293-819b-d1948269c89a)
![Image](https://github.com/user-attachments/assets/eb1a35be-fc8b-47db-ab39-ddce2262b485)

**Comment by jucastro94** [comment]
se realiza pruebas en ambiente de pruebas![Image](https://github.com/user-attachments/assets/7c971636-d100-4a08-b590-6b72a1a63a02)
![Image](https://github.com/user-attachments/assets/4608d954-85fd-4e82-8aa3-b8b688243eb3)

**Comment by edwargl7** [comment]
Muy buena implementación y pruebas. Finalizada. Muchas gracias.
