### ISSUE TITLE
Implementación validaciones previas al envío del PAA a revisión

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#334]
Se requiere realizar la implementación que permita solamente habilitar la acción de "Envío a revisión ..." cuando el plan cuente con el registro de la informacion básica, registro de por lo menos una auditoría y generado el PDF. 
Implementar endpoint de consulta de planes para el módulo de programación que retorne solamente la información necesaria para la vista de consulta, adicional, agregar campo que permita identificar que el PAA cuenta con la información completa para habilitar el envío del PAA a revisión del Jefe en el microcliente (tener presente los estados en los que es permitido para evitar procesamiento adicional no requerido en estados diferentes a Borrador o Rechazado).

**Sub Tareas**

- [x] Implementación endpoint de consulta de los planes para vista de consulta con la información requerida para el módulo de programación.
- [x] Implementación campo adicional en el endpoint anterior para acción de envío a revisión.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se realiza la revisión con @CristianCGutierrezG para concretar la ruta adecuada tanto a nivel de desarrollo como la UX. Y se decide resolverlo manteniendo la acción de enviar a aprobación siempre. Y en esta validando si cuenta con el PDF del PAA creado, en caso que no se informa que le falta este y ya por la gestión y validación que debe hacer el usuario al momento de generar el PDF (información completa y correcta) se concluye que se manejan por parte del usuario el resto de validación.

Permitiendo solamente tener una regla ligera para la validación del PAA en el sistema.

**Comment by CristianCGutierrezG** [comment]
### validaciones previas al envío del PAA

Se ajusta la función de envió del plan para que realice la revisión Si existe algún documento activo relacionado con el plan a enviar, si no existe se manda una alerta para avisar al usuario de la falta de este, de existir hace la operación con normalidad

![image](https://github.com/user-attachments/assets/5b42b1a8-3d70-4d1d-8b0d-43263769d487)

https://github.com/user-attachments/assets/bb7d8759-a724-48d4-b79d-44f4ca3bd54f

**Comment by edwargl7** [comment]
Muy buena implementación se finaliza.
