### ISSUE TITLE
Implementación generación del PAA en PDF con el orden asignado

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#335]
Se requiere realizar el ajuste en el endpoint que suministra el listado de auditorías tomando el orden de las auditorias ya sea asignado por defecto en el registro manual y/o cargue masivo y/o ajustado con el drag and drop.

**Sub Tareas**

- [x] Ajuste en el orden de las auditorías en el documento generado del PAA.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
**Nuevo Endpoint: `@Get('reordenadas')`**:
   - Endpoint creado para obtener las auditorías en el orden especificado por el drag & drop en cada plan.

![image](https://github.com/user-attachments/assets/17548506-a0e8-4e03-b928-9d82d19822c6)

  - Se reajusta la ruta para cargar las auditorias en el mf

![image](https://github.com/user-attachments/assets/186d766f-f694-4583-a0f1-671016a2f749)


**Actualización del `plantilla.service`**:
   - La lógica del servicio se modifica para reorganizar las auditorías al momento de preparar los datos para ser renderizados.

![image](https://github.com/user-attachments/assets/07229f49-4343-41e1-8e11-632d79c35a24)

Se realizan pruebas con auditorias agregadas o reordenadas con los tres metodos

https://github.com/user-attachments/assets/a69d2842-eb7b-4dff-adc3-c4d14c1ce757

**Comment by CristianCGutierrezG** [comment]
Se realiza el cmbio del nuevo  Endpoint  a `@Get('ordenadas')`

![image](https://github.com/user-attachments/assets/60ee2e97-a789-45e8-85a9-c134327218f7)

![image](https://github.com/user-attachments/assets/629579b7-a1ba-4e38-b370-a0e7a8dda6e1)

**Comment by edwargl7** [comment]
Resueltos PR. Muy buen trabajo.
