### ISSUE TITLE
Ajustes y refactorización módulo de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#337]
Se requiere realizar la refeactorización del nombre de funciones de los microservicios del módulo de programación basado en la convención. Además, se incluye en esta Issue los demás ajustes encontrados en las pruebas funcionales.

**Sub Tareas**

- [x] Ajuste envío de vigencia_id para el cargue masivo de auditorias (Cristian).
- [x] Refactorización funciones del microservicio [plan_anual_auditoria_mid](https://github.com/udistrital/plan_anual_auditoria_mid).
- [x] Ajuste nombres de variables relacionadas al cargue masivo (lambda_payload).
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación implementación y resultado pruebas funcionales.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
###  Ajuste envío de vigencia_id

Se realizan cambios en el mf, en el componente de registrar auditorías para obtener la vigencia relacionad al ID del plan específico y así enviar la vigencia correcta al momento de crear la auditoría y el cargue masivo

Registro exitoso de diferentes auditorías con vigencia distinta

![image](https://github.com/user-attachments/assets/b781a53f-2853-4439-afbd-6879760b7b27)

Se realizan pruebas con el cargue masivo y el cambio en el registro correcto de las vigencias_id

![image](https://github.com/user-attachments/assets/80f53a88-a886-431f-93ae-9abf4c3e010c)
![image](https://github.com/user-attachments/assets/b180cf6e-5663-4fe5-83cb-bfbc0aa7a985)
![image](https://github.com/user-attachments/assets/94576e63-231c-4d3e-91b5-efab1c84909e)

**Comment by CristianCGutierrezG** [comment]
Se realiza el reajuste de algunas funciones del plan_anual_auditoria_mf

**Comment by jucastro94** [comment]
se realiza ajuste a nombre de variables y funciones en plan auditoria mid

**Comment by jucastro94** [comment]
se realiza prueba funcional
![Image](https://github.com/user-attachments/assets/eddf1f96-f4d9-4529-992c-2136f01187f1)
![Image](https://github.com/user-attachments/assets/66ed07a7-2906-4dc4-b99b-c412cb568596)
![Image](https://github.com/user-attachments/assets/ec731a78-3cb5-4929-9c17-dd4d33ba1aad)
![Image](https://github.com/user-attachments/assets/7ce9eecd-4b2c-4bac-9e08-04a78ac37001)

**Comment by edwargl7** [comment]
Muy buen trabajo, se resuelven PR.
Ajustar nombre de cargarAños.
![Image](https://github.com/user-attachments/assets/e05f5183-f661-4b94-abfa-1d3f6b8a29fc)
