### ISSUE TITLE
Ajuste estilo modo ver información básica del PAA en el módulo de programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#338]
Se requiere realizar el ajuste en el estilo de la visualización de la información del PAA cuando cambia a solo visualización para el usuario.

**Sub Tareas**

- [x] Ajuste path visualizado en la vista de ver (tiene "Editar").
![Image](https://github.com/user-attachments/assets/0f380c68-8e97-4502-b1ac-5b38ed0cbd14)
- [x] Ajuste estilo en la visualización de la información básica.
- [x] Pruebas funcionales.

**Criterios de aceptación**

- [x] Documentación resultado ajuste de estilo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Ajuste estilo modo ver información básica del PAA en el módulo de programación** 

>[!NOTE]
> Manejo de path e interfaz

![image](https://github.com/user-attachments/assets/f5ee27e1-478b-4409-8bf5-9bf8ffdad238)

---

![image](https://github.com/user-attachments/assets/cf61fd39-9b7b-4272-aa0c-02635150f2ce)

**Comment by cjgonzalezp** [comment]
Buen día @K3vinchaparro se ven muy bien los estilos del plan de acción, mi sugerencia seria para los campos que quedan bloqueados es dejar un gris más oscuro, pues la información no es muy clara de leer.

Gracias

**Comment by edwargl7** [comment]
Resuelto PR.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Cambio de interfaz de ver, para sea mas clara

![image](https://github.com/user-attachments/assets/fd8ed07b-bd3f-42d7-a790-1364d63f097e)

**Comment by cjgonzalezp** [comment]
Buen trabajo @K3vinchaparro
