### ISSUE TITLE
Evaluación modelo de datos para la gestión de usuario y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#34]
Se requiere realizar el análisis y diseño del modelo de datos para la gestión de usuarios que permita:

- Listar auditores activos e inactivos con el respectivo período.
- Integrar los usuarios de la Universidad del servicio de Terceros junto con el servicio de WSO2 que permite la asignación de roles a un especifico usuario.
- Garantizar la posibilidad de poder filtrar los diferentes procesos que realiza el usuario dentro del sistema

**Sub Tareas**

- [x]  Análisis de los roles del sistema en el módulo de gestión de usuarios y las funcionalidades requeridas (listar activos e inactivos, periodo con el rol, integración con los servicios Terceros y WSO2). 
- [x] Actualización del modelo de datos para el módulo de gestión de usuarios.

**Material**
- [Diseño modelo de base de datos - Parte 1](https://github.com/udistrital/sisifo_documentacion/issues/17)
- [Revisión y ajustes del modelo de microservicios para Sísifo v2 - Modelo de datos](https://github.com/udistrital/sisifo_documentacion/issues/20)
- [División módulo de configuración Sísifo v2](https://github.com/udistrital/sisifo_documentacion/issues/33)
- Roles 
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/a87f7286-25d6-4258-82fa-84a552e242e5)

**Criterios de aceptación**

- [x] Creada versión del modelo de datos para el módulo de Gestión de usuarios y roles.

**Requerimientos**

- [x] [División módulo de configuración Sísifo v2](https://github.com/udistrital/sisifo_documentacion/issues/33)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Nueva versión del modelo de datos para el módulo de gestión de usuarios y roles.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realiza analisis de gestión de usuarios y funcionalidades requeridas para usuarios y roles

se inicia modificaciones a modelo de datos para la gestion de usuarios

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/5fc904e0-58d3-41ee-89ae-179c0d06b443)

**Comment by jucastro94** [comment]
se genera modelo de datos de usuarios y roles

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/10d3dc38-47d4-492d-8d14-96f906965d03)

**Comment by edwargl7** [comment]
Se realiza la revisión del modelo propuesto con las siguiente observaciones:
- Aplicar los [lineamientos de modelos de datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md), validando los nombres de las tablas.
- **Tabla usuario**
> - No almacenar el nombre del usuario
> - Modificar el campo documento_id -> documento
- **Tabla periodo_rol_usuario**
> - Evaluar el uso del campo estado, ya que cada vez que se cambie de rol se crea un nuevo registro, no se retoman roles para Sísifo.
- **Tabla rol**
> - Revisar con el equipo el uso de la tabla roles y la integración con el microcliente de gestión de usuarios.
- **Tablas de permisos**
> - Es una buena propuesta, se debe evaluar el uso de esta. Dado que se puede presentar en ciertos formularios campos específicos que pueden ser solo modificados por cierto rol, lo cual dificulta el manejo de permisos en los formularios.

**Comment by jucastro94** [comment]
se carga archivo .draw en carpeta del proyecto [modelo usuarios y roles](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EU8AC-5UeV5MrqvBP77QMYkBqePVa6cNICPUNoTwv7ng9g?e=zjdbuO)
