### ISSUE TITLE
Apoyo revisión documentación pruebas funcionales módulo de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#340]
Se requiere apoyar la revisión de la documentación del comportamiento esperado en las pruebas funcionales del módulo de gestión de usuario que permitan complementar las HU para la Issue #333.

**Sub Tareas**

- [x] Revisión comportamiento esperado en el modulo de gestión de usuarios.

**Criterios de aceptación**

- [x] Resultado revisión de la documentación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza la revisión del documento creado de las pruebas funcionales desarrolladas para el módulo de gestión de usuarios.

**Observación de la revisión:**
1. Corrección de la ortografía del documento
2. Revisar paginado, ¿cantidad de registros a mostrar por pagina?
3. Aclarar el hallazgo 8 y agregar evidencia del resultado obtenido de la prueba
4. Pendiente poner evidencia de la prueba realizada en el hallazgo 13
5. Se debe corregir los accesos y permisos del rol auditor experto, las funciones de creación y edición pertenecen al rol administrador![Image](https://github.com/user-attachments/assets/84a03461-b56f-48e3-b3ef-d43210a86577)![Image](https://github.com/user-attachments/assets/6f4fa335-c92a-4c48-8484-8efaf7151eff)
4. Pendiente poner evidencia de la prueba realizada en el hallazgo 15
5. Se ajustan imágenes dentro del recuadro **resultados**
6. Revisar si se debe incluir un mensaje de error cuando el rol quiere eliminar un registro en el hallazgo 22
7. Aclarar el hallazgo 28, la evidencia muestra otro resultado
8. Realizar pruebas desde los demás roles **secretario técnico, líder, responsable y soporte**para dejar documentado los resultados de visualización del módulo de gestión de usuarios

Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la revisión del documento, el documento cubre todas las pruebas funcionales. Queda pendiente realizar los ajustes descritos en los comentarios de esta issue.


Saludos.

**Comment by edwargl7** [comment]
Muy buen trabajo. Muchas gracias,

**Comment by edwargl7** [comment]
Del punto 3, se elimina la fila 8 por caso repetido en el registro 6.
Se actualizan roles para remover registro de usuarios en el rol JEFE y Auditor Experto.
