### ISSUE TITLE
Actualización matriz de roles y permisos módulos de gestión de usuarios y programación

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#341]
Se requiere realizar la actualización de la matriz de roles y permisos de Sísifo v2 basado en los cambios realizados relacionados a los módulos de gestión de usuarios y programación.

**Sub Tareas**

- [x] Actualizar la matriz de roles y permisos.

**Criterios de aceptación**

- [x] Matriz actualizada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

Se actualiza matriz de roles y permisos del módulo de gestión de auditorías y gestión de usuarios.

**Enlace documento guardado en OneDrive en la carpeta del proyecto Sísisfo V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpotSdcwuCtGgGiZBiM6akYBy1PHvdwdRQV6icFQbCJZOw?e=K4qXpg


Saludos.

**Comment by edwargl7** [comment]
Revisada y aprobada. Muchas gracias.
