### ISSUE TITLE
Actualización documento de avances de Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#342]
Se requiere realizar la actualización del módulo de avances de Sísifo agregando columnas relacionadas a las diferentes fases y documentos requeridos en cada uno para la identificación de avances en cada ambiente y lo requerido para los pasos en cada ambiente.

**Sub Tareas**

- [ ] Documentación avances generales en documentación y manuales.

**Criterios de aceptación**

- [ ] Actualización del documento.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la actualización del documento de avances de Sísifo V2

**Enlace documento guardado en OneDrive en la carpeta del proyecto Sísifo V2**
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ef14PWiOhulLsOfUVZjyQYMBiZRHBWnJYSeXZ7O9yGfFBQ?e=c8qjLw


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se actualiza el documento de avances del proyecto Sísifo V2. Junto con el líder técnico haremos una reunión el día 19 de diciembre para complementar el documento desde la parte técnica.

**Enlace documento guardado en OneDrive en la carpeta del proyecto Sísifo V2**
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ef14PWiOhulLsOfUVZjyQYMBiZRHBWnJYSeXZ7O9yGfFBQ?e=c8qjLw

Saludos.

**Comment by edwargl7** [comment]
Se finaliza la actualización con los avances hasta la fecha.
