### ISSUE TITLE
Diseñar el mockup de vista de registro del módulo del plan de mejoramiento. Rol Auditor

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#344]
Se requiere realizar el diseño del mockup de vista de registro del módulo del plan de mejoramiento. Rol Auditor

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos
- [x] Presentar el mockup al equipo SoS
- [x] Realizar ajustes según comentarios del equipo SoS
- [x] Presentar al equipo el mockup definitivo 

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS
- [x] Diseño documentado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día.

Se diseña mockup de la vista de revisión y aprobación del plan de mejoramiento desde el rol auditor.

![Image](https://github.com/user-attachments/assets/350b2bc4-4085-45a1-808e-b50a0007e987)


**Enlace archivos guardados en OneDrive en la carpeta del proyecto Sísifo V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et7XvruLX0JLjmXehXAWD4MBPj4OoKC-UCpnqRa8pd-XIw?e=gZYbnE


Saludos.

**Comment by edwargl7** [comment]
Muy buen diseño. Se finaliza sin ajustes.
