### ISSUE TITLE
Apoyo revisión documentación pruebas funcionales módulo de programación del PAA

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#349]
Se requiere realizar el apoyo en la revisión de la documentación de pruebas funcionales del módulo de programación del PAA basado en las HU.

**Sub Tareas**

- [x] Revisión comportamiento esperado en el modulo de programación del PAA.

**Criterios de aceptación**

- [x] Resultado revisión de la documentación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en la revisión de la documentación pruebas funcionales del módulo de programación del PAA

Comentarios a revisar:
1. Agregar evidencias en el hallazgo 6
2. Pendiente la identificación del archivo establecido en el sistema para ser descargado por el auditor para el diligenciamiento y cargue masivo.
3. Aclarar hallazgo 10
4. Agregar evidencia del resultado de la prueba en el hallazgo 12
5. Del hallazgo 15, revisar si se pueden organizar las auditorías por tipo de evaluación y/o por nombre de auditoría (a-z o viceversa)

**Comment by cjgonzalezp** [comment]
Continuación de comentarios a revisar:

6. Seguido al hallazgo 17, se debe realizar prueba de como visualiza el jefe de la OCI cuando da clic en el submódulo plan anual de auditoría
7. Del hallazgo 23, ¿el botón de aprobar está bloqueado si el rol secretario aun no carga el acta de CCCI? Aclarar los comentarios técnicos 
8. Se debe realizar prueba funcional desde el rol secretario técnico, si el rol ingresa desde el sistema al submódulo plan anual de auditoría como visualiza el plan y que acciones puede hacer
9.  Del hallazgo 28, mostrar evidencia de modales de guardado de la asignación realizada.
10. En el módulo de asignación de auditorías se deben bloquear los campos de nombre auditoría, tipo de evaluación y cronograma.
11. Agregar un hallazgo prueba funcional para reasignar auditores cuando el rol auditor experto lo requiera.
12. Falta realizar pruebas funcionales del submódulo auditorías especiales.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente por parte de @edwargl7 la comunicación de las observaciones al equipo de desarrollo.
