### ISSUE TITLE
Integración roles al microcliente de Gestión de roles y usuarios - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#35]
Se requiere realizar la revisión y desarrollo base de la lógica requerida para la integración de WSO2 al [microcliente de gestión de usuarios](https://github.com/udistrital/sisifo_configuracion_mf), teniendo presente los roles de Sísifo.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/5f34859e-0ea3-4cca-ae11-80ffd146388e)

**Sub Tareas**

- [x] Revisión de la integración de WSO2 realizada en SISGPLAN [componente gestion-usuarios](https://github.com/udistrital/planeacion_construccion_mf/tree/develop/src/app/components/plan/gestion-usuarios) teniendo presente la importancia de [almacenar el período y la posibilidad de listar usuarios](https://github.com/udistrital/sisifo_documentacion/issues/34) en otros módulos de Sísifo v2.
- [x] Crear funcionalidad para agregar o remover roles a un usuario.
- [x] Identificar la forma de realizar el almacenamiento de los periodos en Sísifo por usuario.

**Material**
- [SISGPLAN componente gestion-usuarios](https://github.com/udistrital/planeacion_construccion_mf/tree/develop/src/app/components/plan/gestion-usuarios)
- [Evaluación modelo de datos para la gestión de usuario y roles](https://github.com/udistrital/sisifo_documentacion/issues/34)
- [Creación módulo de gestión de roles Sísifo v2 - Microfrontend roles](https://github.com/udistrital/sisifo_documentacion/issues/24)

**Criterios de aceptación**

- [x] Definición de consumo de Roles propios de Sísifo V2.
- [x] Desarrollo inicial de la funcionalidad para agregar o remover roles a un usuario en WSO2.

**Requerimientos**

- [ ] [Evaluación modelo de datos para la gestión de usuario y roles](https://github.com/udistrital/sisifo_documentacion/issues/34)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizo la revisión de la integración de WSO2 en SISGPLAN y con el apoyo de la  [capacitación sobre el  funcionamiento de WSO2](https://udistritaleduco-my.sharepoint.com/personal/hegranadosl_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fhegranadosl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FGrabaciones%2FCapacitaci%C3%B3n%20WSO2%20integraci%C3%B3n%20y%20manejo%20de%20hist%C3%B3rico%2D20240530%5F113423%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E480cdf09%2Dedcd%2D43c2%2D9bb6%2Df1c85ce94dc0&ga=1), se llego a las siguientes conclusiones sobre la Integración roles al microcliente del sistema Sísifo:

**WSO2**
- SISGPLAN realiza peticiones a la API de [autenticacion_mid](https://github.com/udistrital/autenticacion_mid), la cual se encarga de las solicitudes para añadir y remover roles de un usuario en WSO2.
- Se brindan consejos de como obtener la información del token de un usuario especifico: directamente desde el cliente al hacer el login de usuario o haciendo peticiones a la API de autenticacion_mid (opción recomendada).
- No se puede crear roles directamente en WSO2; hay que solicitar su creación al arquitecto. Una vez creado, ya se puede añadir un rol a un usuario con la API autenticacion_mid.
- WSO2 maneja información limitada de los usuarios, como correo, rol y cedula. Para acceder a información mas relevante,  es necesario hacerlo a través de la API de Terceros.

**Cliente**
- La API de autenticacion_mid no cuenta con un enpoint para listar los usuarios con base a un rol especifico, por temas de seguridad, no esta disponible por ningún cliente. Existe un servicio que cumple esta función, aunque se desconoce cuál, además de que hay que limitar los roles necesarios para Sísifo.
- Cada vez que se agregue o se remueva un rol de un usuario, es necesario pedir recargar la página para que se refleje el cambio.

**Almacenar el Periodo**
- WSO2 no guarda el histórico de la información de los roles,  por lo que hay que considerar otras opciones para la gestión del periodo.

**Comment by CristianCGutierrezG** [comment]
Se crea un nuevo modulo para añadir roles a un usuario, tomando como referencia el módulo de sisgplan
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/924b2f64-2eea-4d40-91ca-d6f184dcffb0)

Notas:
No se puede hacer la confirmación de la conexión con WSO por que aun no se crean los respectivos roles ni se cuenta con un usuario de pruebas.
Falta adecuar la lógica para obtener la información del usuario conectado y adaptarla al sistema de SISIFO

**Comment by edwargl7** [comment]
Se realiza la revisión del desarrollo realizado y se observa correctamente, se procederá con el peer code review. Y se revisará el escenario para poder validar el correcto funcionamiento por la dependencia de los roles registrados. Muy buen trabajo.
