### ISSUE TITLE
Investigación formulario dinámico para gestión de la auditoria

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#36]
Se requiere realizar la investigación y estrategia para la creación del formulario dinámico que permita almacenar una estructura [EC-PR-002-FR-004](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWceR73Nak5LnssDAFq7amkBna87LO2ZO-4OL9Unn03TOw?e=0OMotO) de las secciones:

- Aspectos generales
- Desarrollo de la auditoria
- Cuadro resumen de hallazgos
- Conclusiones
- Recomendaciones

**Sub Tareas**

- [x] Revisión formato [EC-PR-002-FR-004](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWceR73Nak5LnssDAFq7amkBna87LO2ZO-4OL9Unn03TOw?e=0OMotO)
- [x] Investigación creación formulario dinámico para almacenamiento de subdivisiones de cada sección.
- [x] Documentación sobre resultados de la investigación, estrategia y viabilidad. 

**Criterios de aceptación**

- [x] Documentación que permita evidenciar las posibles estrategias y viabilidad de la creación de un formulario dinámico dado que la mayoría de secciones del formato son texto (sin selectores).

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Documentación que evidencie los resultados de la investigación y viabilidad de la propuesta.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
# Avance investigación formulario dinámico

* Inicialmente se realiza la revisión del formato del documento de auditoria para comprender y definir las secciones a incluir en el formulario, donde se evidencia que se deben incluir campos de texto largos para detallar el proceso de auditoría, conclusiones, recomendaciones. Adicionalmente una tabla o lista dinámica para agregar los hallazgos.

* Se comienza la búsqueda de información relacionada a los formularios dinámicos y posibles aplicaciones al proyecto actual, se deben tener en cuenta los lenguajes de programación que faciliten su implementación. 
  * Para el formulario con Angular se esta revisando el uso de ReactiveFormsModule

* Se tiene en cuenta la sugerencia del uso de angular y la revision de la implementación de este tipo de formularios en otros sistemas (SGA).

* Se solicita información sobre los lineamientos que se deben tener en cuenta para la presentación final de los resultados obtenidos en la investigación.

**Comment by edwargl7** [comment]
Se puede observar el componente dinámico empleado en SGA https://github.com/udistrital/sga_cliente/tree/develop/src/app/%40theme/components/dinamic-form-group

**Comment by alexhrr** [comment]
Se realizo la revisión de los componentes dinámicos de ejemplo suministrados y se consultaron las dudas en una reunion con el líder para poder continuar con la investigación, se plantean las diferentes opciones para la generación de los formularios teniendo en cuenta las necesidades con respecto al documento de la auditoria, finalmente se procede a iniciar la elaboración de un documento con las observaciones encontradas.

**Comment by edwargl7** [comment]
Se realiza una revisión de aplicación en otros sistemas y se observa el uso de FormBuild. Se puede tomar este enfoque en lo propuesto. Se apoya la revisión de uso de esta opción.

El documento a entregar por el momento no debe ser un informe técnico dado que es una exploración inicial. Este documento debe contener los enlaces de material revisado, imágenes de posibles usos (recomendado de ser posible) y la conclusión de esta primera etapa de revisión.

**Comment by alexhrr** [comment]
# Entrega documento
Se realiza el documento solicitado de la exploración inicial para la implementación de formularios dinámicos para el formato de auditoria, se tiene la información inicial recolectada hasta el momento como un acercamiento al tema con los posibles recursos a usar para el desarrollo así como unos ejemplos encontrados en otros sistemas.

El documento se encuentra en la carpeta de la documentación de Sisifo para su consulta y continuación de acuerdo a las necesidades del cliente.

Se revisa el uso de formularios dinámicos con Angular y las implementaciones realizadas anteriormente en el sistema SGA.

[Exploracion formulario dinamico.pdf](https://github.com/user-attachments/files/15522262/Exploracion.formulario.dinamico.pdf)

Documento en linea:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EX1oa6V8YwRMgoKB1OwFpMUB1X5sCNe13D7xb941CixiFQ?e=vo0dn1
