### ISSUE TITLE
Documentar el README del repositorio microcliente gestión usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#38]
Se requiere realizar la documentación del README del repositorio de microclientes de gestión de roles y usuarios siguiendo los lineamientos [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md).

Para las variables de entorno se deben describir como se menciona en los lineamientos. Ejemplo:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/17f64934-f798-4fa4-92b1-92252318985f)

**Sub Tareas**

- [x] Documentar README del repositorio [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)

**Criterios de aceptación**

- [x] Documentación de los README siguiendo los lineamientos [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realiza la documentación del README en el repositorio microcliente gestión usuarios y roles siguiendo los lineamientos establecidos.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/d605ef3a-0d9c-407f-9ed3-efc86e42ee51)

**Comment by edwargl7** [comment]
Se apoya el ajuste del comentario del PR y se agrega el enlace al comentario del mismo para su enlace con la Issue.

Tener cuidado con los archivos y carpetas subidas al repositorio.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/ccde4cc5-0488-428b-8c01-5a7e52394742)
Se debe eliminar del repositorio remoto el archivo .vscode
