### ISSUE TITLE
Investigación formularios reactivos para gestión de la auditoría - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#39]
Se requiere realizar la investigación de los formularios reactivos y la creación de una estructura que permita una primera etapa de implementación similar a como se maneja actualmente en https://github.com/udistrital/sga_cliente/tree/develop/src/app/%40theme/components/dinamic-form-group y https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/form-espacio_academico.ts.

Se observa que esta funcionalidad es requerida para los módulos de auditoría en los que los formatos pueden sufrir cambios periódicamente, por lo que se hace de suma importancia contemplar en el desarrollo la posibilidad de realizar cambios en los formularios sin que esto impacte constantemente desarrollos nuevos en el nuevo sistema.

El material de apoyo se puede observar en la [Issue #36](https://github.com/udistrital/sisifo_documentacion/issues/36) en la que se realizó un primer acercamiento a las alternativas posibles.

**Sub Tareas**

- [x] Continuar con la investigación de formularios reactivos.
- [x] Establecer la estructura que permita la creación del formulario a partir de un json [ver](https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/form-espacio_academico.ts)
- [x] Primera parte de la documentación técnica.

**Criterios de aceptación**

- [x] Documentación técnica primera etapa que contenga los principales atributos a tener presente en la estructuración de los formularios reactivos según los principales elementos HTML usados en los formularios (select, input, textarea, ...)

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Documentación técnica inicial sobre formularios reactivos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realiza la revisión del material de apoyo de la issue https://github.com/udistrital/sisifo_documentacion/issues/36 sobre la exploración inicial formularios dinámicos y también la implementación en los repositorios del sistema SGA.

**Comment by CristianCGutierrezG** [comment]
Se inicia la creación de un documento recopilatorio con la información recolectada para ladesarrollo de formularios reactivos, basado en la  [documentación oficial de angular](https://angular.dev/guide/forms/dynamic-forms#enable-reactive-forms-for-your-project) y en los repositorios del sistema SGA.

De esta exploración surgieron las siguientes observaciones:

- En el componente [DinamicFormGroupComponent](https://github.com/udistrital/sga_cliente/tree/develop/src/app/%40theme/components/dinamic-form-group), se crea una plantilla para cualquier formulario, pero no parece que se utilice en otros componentes
- En [form_espacio_academico.ts](https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/form-espacio_academico.ts), se crea un objeto que almacena diferentes arrays con los inputs del formulario, estableciendo propiedades comunes como tipo, nombre, validación, etc.
- El formulario de [creacion-espacios-academicos.component.ts](https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/creacion-espacios-academicos.component.ts), pero está diseñado para realizar cambios en ese formulario específico. En este componente, se llama al objeto de [form_espacio_academico.ts](https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/form-espacio_academico.ts) y se crea el formBuilder con todos los formControl respectivos. Una vez hecho esto, se crean diversos métodos para manejar el formulario. 

Sería útil poder observar el funcionamiento del sistema SGA para comprender mejor su operatividad.

**Comment by edwargl7** [comment]
Ejemplo de documentos técnicos realizados por otros equipos.
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW-h4D4dgZBGsfJwUCMuonsBtJpSbtY-gBtAP5rFXSaqtQ?e=g7Delw
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=mIEGhW

En la portada agregar la siguiente tabla:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/8f036af9-c8f4-4a1a-9df5-5c8568fe950c)

**Comment by edwargl7** [comment]
Enlace de la carpeta en la que se deben subir los documentos de la investigación y borrador de documento técnico https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Gesti%C3%B3n%20t%C3%A9cnica/Documentaci%C3%B3n%20S%C3%ADsifo%20v2/Investigaci%C3%B3n%20Formularios%20Din%C3%A1micos?csf=1&web=1&e=zVfKOg

**Comment by CristianCGutierrezG** [comment]
Se ha creado un documento basado en la creación de formularios dinámicos utilizando los repositorios del sistema SGA.

- El documento incluye una breve explicación basada en la documentación de Angular sobre la biblioteca Reactive Forms.
- Se explica detalladamente el proceso de desarrollo de un formulario dinámico.
- Se describe cómo se desarrolla un formulario a partir de una estructura tipo JSON.
- El documento se ha subido a la carpeta correspondiente.

Enlace del documento:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EeCFmD4PFEBJk9WpeEVF3CABz-qWyqJJ4GDQ1iaBDZJFxg?e=24xrn4

**Comment by edwargl7** [comment]
Muy buena investigación, se revisará en la siguiente etapa la observaciones sobre el uso del formulario dinámico. Y lo necesario para la prueba del proyecto SGA usado como referencia.
Se observa un trabajo progresivo y una buena inmersión en la investigación.
Se toma este documento como insumo y se ira trabajando mientras se avanza en la investigación en el documento técnico.
