### ISSUE TITLE
Pruebas formularios reactivos para gestión de la auditoría - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#40]
Se requiere realizar la investigación e implementación inicial de una prueba de concepto de formularios reactivos partiendo del formulario desarrollado en la [Issue #24](https://github.com/udistrital/sisifo_documentacion/issues/24) la cual cuenta con un formulario con pocos campos, que puede ser usado como base para la construcción del mismo desde un formulario reactivo.

Se puede usar de ejemplo https://github.com/udistrital/sga_cliente/tree/develop/src/app/%40theme/components/dinamic-form-group y https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/form-espacio_academico.ts, que cuentan con un componente dinámico que permite desde un objeto que cumple una estructura definida construir un formulario.

En esta primera etapa se busca replicar un comportamiento similar al actual de SGA (enlaces suministrados), en una etapa posterior se busca que esos objetos sean almacenados en un servicio diferente.

**Sub Tareas**

- [x] Revisión material preliminar [Issue 36](https://github.com/udistrital/sisifo_documentacion/issues/36)
- [x] Implementación de prueba de concepto replicando el formulario de gestión de roles y usuarios de [Issue #24](https://github.com/udistrital/sisifo_documentacion/issues/24)

**Criterios de aceptación**

- [x] Evidencias de los resultados obtenidos.
- [x] Rama con el desarrollo realizado sin realizar el Pull Request

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza la revisión de la issue #24 para obtener la base del formulario, asi mismo se continua la revisión de los repositorios del sistema SGA para tomarlo como guía de la aplicación de formularios dinámicos

**Comment by edwargl7** [comment]
Ejemplo de documentos técnicos realizados por otros equipos.
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EW-h4D4dgZBGsfJwUCMuonsBtJpSbtY-gBtAP5rFXSaqtQ?e=g7Delw
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EdixQ978d0hFgJi-psItfw8B1HgCUT9vVDjo4hAqkWQ5qg?e=mIEGhW

En la portada agregar la siguiente tabla:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/8f036af9-c8f4-4a1a-9df5-5c8568fe950c)

**Comment by alexhrr** [comment]
## Avances formularios reactivos

Se realiza una reunion con Cristian para socializar los avances realizados en la investigación de los formularios reactivos y comprender la estructura usada en el SGA para asi empezar a definir un punto de partida para la creación del prototipo solicitado, tomando como guía la sección de "creación de espacios académicos"

Según lo comentado, se parte de la creación inicial de la estructura del formulario como se muestra a continuación: 

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/9bf5bfbe-08bb-4b3c-b4a1-f305b6a6db98)

Posteriormente se construye el formulario en diferentes etapas.

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/a13a93c8-68af-4b47-bdb2-5b2e12ab1105)

A continuación se crean las funciones necesarias para la interacción con el formulario.

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/24d08cca-be26-4e8e-928e-f66b0c440c4a)


Para la creación del prototipo solicitado hace falta comprender los siguientes pasos a los mencionados anteriormente y comprender mejor las librerías usadas en el proyecto de ejemplo, asi como descartar las funciones que no se necesitan para el prototipo, se encuentra el problema de que la revisión del codigo es compleja debido a su extensión y cantidad de funcionalidades por lo que se requiere mas tiempo para su comprensión y aplicación al prototipo.

**Comment by edwargl7** [comment]
Enlace de la carpeta en la que se deben subir los documentos de la investigación y borrador de documento técnico https://udistritaleduco-my.sharepoint.com/:f:/r/personal/computo_udistrital_edu_co/Documents/INVERSI%C3%93N/PROYECTOS%20DE%20INVERSI%C3%93N/GERENCIA%20DE%20PROYECTOS/PROYECTOS%20OAS/PROYECTO%20SISIFO%20V2/2024/EJECUCI%C3%93N/Gesti%C3%B3n%20t%C3%A9cnica/Documentaci%C3%B3n%20S%C3%ADsifo%20v2/Investigaci%C3%B3n%20Formularios%20Din%C3%A1micos?csf=1&web=1&e=zVfKOg

**Comment by edwargl7** [comment]
Se realiza la revisión de lo documentado en la Issue y cuenta con buena documentación,  es claro que para completar la prueba requiere continuar con la investigación y exploración. Por lo que se sigue en el siguiente sprint.

Recordar  realizar por favor el cambio de estado de la Issue para garantizar la finalización y poder culminar la revisión.

**Comment by alexhrr** [comment]
## Avances formularios reactivos

Junto a Cristian se comienza con la implementación del codigo para el prototipo solicitado, aplicando los conceptos investigados, a continuación se dejan algunas capturas del codigo realizado:

Creación del modulo de roles en el componente existente
![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/04057320-fa8a-4042-885e-c7cf9eb5f344)

Uso del FormGroup y FormControl para el formulario
![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/01bb9b56-1660-4d0c-9a28-03f637de89f3)

Actualmente encontramos dificultades en la implementación del formulario debido a la poca experiencia en el tema, se debe ampliar la practica con los formularios a nivel de codigo.

**Comment by edwargl7** [comment]
Se finaliza la Issue con la documentación recopilada, muy buen trabajo. Se continua en la siguiente Issue con la investigación y prueba.
