### ISSUE TITLE
Pruebas microcliente gestión de usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#41]
Se requiere realizar las pruebas integración microcliente de gestión de usuarios y roles con WSO2 implementado en [Issue 35](https://github.com/udistrital/sisifo_documentacion/issues/35).

**Sub Tareas**

- [x] Realizar las pruebas de adición y eliminación del rol a un usuario en WSO2.

**Criterios de aceptación**

- [x] Evidencias de las pruebas realizadas de agregando y removiendo roles a un usuario.

**Requerimientos**

- [x] Usuario para pruebas.
- [x] Roles registrados en WSO2.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se revisan lineamientos para clonacion de repositorio

**Comment by edwargl7** [comment]
Se comenta errores en la ejecución del proyecto root y el microcliente en el ambiente local, se solicita la revisión de versiones a @jucastro94 en lo que no se observa diferencias.

Se va a revisar en el siguiente sprint, sin embargo, se debe documentar la Issue con los errores encontrados por favor.

**Comment by jucastro94** [comment]
se realiza clonacion de repositorio https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8ce6fc6c-399f-4fbe-91ae-f4103a13a2e6)



se realiza ejecucion 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/70966bca-6fde-4410-8c21-ffe3247997e1)



se visualiza error al ejecutar, se procede a revisar por que no hay una correcta ejecucion
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/671cfeb1-ce1a-4926-b1b6-30753b218213)

**Comment by jucastro94** [comment]
con apoyo de @CristianCGutierrezG se corrigen errores y se despliega el ambiente

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/9c5102f9-d8c5-4c7b-9325-b5d3775d6345)

**Comment by jucastro94** [comment]
se realiza instalacion de extencion single-spa en el navegador

se hace cambio de rama para el root de (develop) a (feature) la cual tiene agregado el microcliente de usuario en su logica

**Comment by jucastro94** [comment]
Se procede a desvincular el rol predeterminado, se selecciona el rol a desvincular


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c73afaa7-4d16-4320-8fda-9d3715d974ab)

  
Se da click en boton desvincular y lanza mensaje de advertencia, se selecciona que si
 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/6e8b4fad-752c-4601-9d0c-27813df0ffe8)


Se evidencia mensaje de error al desvincular


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ec33d41a-e198-41c9-88f9-9e54365e6105)

**Comment by jucastro94** [comment]
Para prueba de vinculación de rol, se desvincula el usuario predeterminado quemado en el código


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/2183e058-1c42-42d9-8f5e-6cdc8b46286a)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/b084d6b0-4306-4e08-9858-57db81ec9d4b)



Se selecciona el rol a  asignar y se da botón de “vincular”


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/1c25209f-7680-4b8a-9279-6cd36505ad58)


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8c7511a1-c707-4b35-acb2-088b96767876)

Se selecciona “Si” y lanza mensaje de error en la operación para la vinculacion de rol


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/395bbcb1-bb1e-453b-9c4f-2869e67aa4e7)

**Comment by jucastro94** [comment]
se realiza el procesos de vinculacion con cada uno de los roles alli establecidos

**Comment by edwargl7** [comment]
Se realiza la revisión y cumple con las pruebas requeridas. Se da por finalizada la Issue.
