### ISSUE TITLE
Ajustes modelo de datos de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#42]
Se requiere realizar la revisión con el equipo DBA y el arquitecto del modelo de datos propuesto para la gestión de usuarios y roles en la [Issue 34](https://github.com/udistrital/sisifo_documentacion/issues/34) y realizar los ajustes sugeridos.
Una vez definido, evaluar los ajustes requeridos al microcliente de gestión de usuarios y roles en el manejo de Roles, dado que este los maneja por variables de entorno [Issue 35](https://github.com/udistrital/sisifo_documentacion/issues/35)

**Sub Tareas**

- [x] Revisión con el arquitecto.
- [x] Revisión con el equipo DBA.
- [x] Actualización con los ajustes sugeridos.
- [x] Revisión impacto en el microcliente de gestión de usuarios y roles.

**Criterios de aceptación**

- [x] Modelo de datos actualizado y revisado por el arquitecto y el equipo DBA.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Presentación del modelo de datos.
- [x] Actualización de modelo de datos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Se realiza una revisión con el arquitecto en la que se recibe la aprobación y la recomendación de agregar una tabla que almacene los nombres de los sistemas y permita agrupar los roles por cada sistema, con el fin de poder usar este microservicio en otros sistemas sin afectar el funcionamiento actual de WSO2.

Se debe realizar la revisión con el líder sobre el uso de la tabla de permisos, una vez realizados los ajustes se pasa a revisión con el equipo DBA.

**Comment by jucastro94** [comment]
se agrega tabla sistema_informacion para almacenar los sistemas, con la cual se permite agrupar los roles segun el sistema de información 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f25a5185-8f38-4a71-9d87-2dd8d337ba7b)

se carga archivo [usuarios y roles V2](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ETbygJx5gERCkN2nYK3mPA0B-DOUVn_NOGsmPr5MIYu09g?e=6Km8nh)

**Comment by jucastro94** [comment]
se valida por parte del equipo DBA el modelo de datos 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/43358af5-74fa-413b-9b3e-b4ba4493d402)

**Comment by edwargl7** [comment]
Aprobado modelo de datos por los DBA, se va a diseñar en la base de datos de WSO2 en un esquema separado. No se presentaron ajustes requeridos.

**Comment by edwargl7** [comment]
Se actualizan puntos de historia asignados por los ajustes trabajados y la revisión requerida de la tabla de permisos.

**Comment by jucastro94** [comment]
se analizan pros y contras de la gestion de permisos mediante el modelo de datos

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/dd2ff179-50b9-4516-a209-436da21eff63)

**Comment by jucastro94** [comment]
en cuanto a las consultas de la tabla roles para la gestion de roles y usuarios es recomendable realizarlo atravez del id, siendo necesario realizar los cambios respectivos en el microcliente y sus variables de entorno, si es necesario obtener mayor informcion sobre el rol que se esta requiriendo se puede realizar la consulta por medio de su identificador

**Comment by edwargl7** [comment]
Buen análisis de pros y contras de la tabla de permisos, se agregaron temas de seguridad bastante importantes para tener presente.

Culminada la Issue completamente con la revisión de los cambios requeridos a realizar con el modelo de datos propuesto.
