### ISSUE TITLE
Concertar, desarrollar y levantar acta de sesión requerimientos con cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#43]
Se requiere realizar la concertación, desarrollo y levantamiento acta de sesión de requerimientos con cliente, en lo relacionado con el formato programa de auditorias

**Sub Tareas**

- [x] Concertar reunión de requerimientos con el cliente
- [x] Desarrollar la reunión 
- [x] Diligenciamiento del formato de historias de usuario con el cliente
- [x] Aprobación del formato de historias de usuario
- [x] Proyectar acta de la reunión

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto
- [x] Acta firmada por las partes con anexo de historias de usuario

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by jcmurilloa** [comment]
Se genera traslado de issue a Sprint 7 debido a agendamiento con el cliente

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con el cliente de levantamiento de requerimientos hoy 12 de junio de 2024 de 2:00 pm a 3:30 pm. Se revisan los primeros formatos a tener en cuenta para el módulo de auditoría. Queda pendiente terminar el acta de reunión y enviarla a firmar por los participantes presentes.


Cordial saludo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla acta de reunión 043A/2024 levantamiento de requerimientos. Está pendiente hacer ajustes adicionales y enviar a firmar por los participantes en la reunión.

**Enlace del documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqTFHtc5a1xHln-CMaRNWMUBD6U9pwEw3aj0nMNVbkkN4g?e=8gvCVE

**Grabación desarrollo de reunión del día 12 de junio de 2024 Hora 2:00 pm**
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/EfkrTc53oipNtlKSLcJwQrIBdBbGmMCpxM7maWV6a_zZxw?e=yKHQMK&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan los ajustes al acta de reunión para revisión y visto bueno de Julián Murillo. Pendiente enviar para recolección de firmas de los participantes.

**Enlace del documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqTFHtc5a1xHln-CMaRNWMUBD6U9pwEw3aj0nMNVbkkN4g?e=JhTauk


Quedo atento a sus comentarios

Saludos.

**Comment by jcmurilloa** [comment]
Acta revisada con VoBo, continúa por favor con la recolección de firmas @cjgonzalezp.

**Comment by cjgonzalezp** [comment]
Buen día,

Se da por finaliza la issue con la recolección de las firmas de los participantes en la sesión de levantamiento de requerimientos acta 043A/2024.

**Enlace del documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EqTFHtc5a1xHln-CMaRNWMUBD6U9pwEw3aj0nMNVbkkN4g?e=iHp0wV


Cordial saludo.

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp!
