### ISSUE TITLE
Modificación microcliente de gestión de usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#44]
Se requiere realizar modificaciones al microcliente de gestión de usuarios y roles requeridos basado en el [modelo de datos](https://github.com/udistrital/sisifo_documentacion/issues/42) que permita almacenar los periodos de un usuario y el rol en el microcliente de gestión de usuarios y roles desarrollado en [Issue 35](https://github.com/udistrital/sisifo_documentacion/issues/35)

**Sub Tareas**

- [x] Ajuste a las variables de entorno de los roles cambiando por el id del rol, dado que actualmente el microservicio no existe se debe asignar AUDITOR=2 y JEFE_DEPENDENCIA=3.
- :boom: Ajuste a la interfaz gráfica agregando los campos de selección de periodos (fecha inicio, fecha fin) basado en el mockup. [Se debe desarrollar el nuevo componente)
- [x] Pruebas funcionamiento integración con WSO2 que no se vea afectado por los cambios realizados en el microcliente.

**Escenarios de prueba**
- [x] **Remover rol al usuario de pruebas en WSO2.**
> - **Descripción:** Remover el rol _AUDITOR_ al usuario de pruebas.
- [x] **Agregar rol al usuario de pruebas en WSO2.**
> - **Descripción:** Se debe realizar la prueba agregando el rol eliminado en la prueba anterior al usuario de pruebas.

**Criterios de aceptación**

- :boom: Desarrollo con los ajustes mencionados sin realizar la integración de almacenamiento con el modelo propuesto.
- :lock: (requiere una revisión en otra Issue dada la necesidad de apoyo con otros equipos para conocer la forma adecuada de realizarlo sin salir de los lineamientos) Visualización correcta de los estilos del formulario.
- [x] Documentar las pruebas con git o videos y separando los escenarios de prueba realizados.

**Especificaciones técnicas**
1. El actual usuario de pruebas cuenta con dos roles agregados _AUDITOR_ y _JEFE_DEPENDENCIA_.
2. Para validar los roles asignados en WSO2 puede hacerlo por medio del token. Actualmente, cuenta con:
```
{
...,
  "role": [
    "ADMIN_CAMPUS",
...,
    "ESTUDIANTE",
    "JEFE_DEPENDENCIA",
    "AUDITOR"
  ],
...,
  "email": "utest01@udistrital.edu.co"
}
```
3. Otra opción para validar es usando el endpoint /v1/token/userRol de autenticacion_mid. 

**Requerimientos**

- [x] [Diseño del mockup de la vista del modulo Gestión de usuarios](https://github.com/udistrital/sisifo_documentacion/issues/50)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Mientras se valida el modelo de datos propuesto en la [Issue 42](https://github.com/udistrital/sisifo_documentacion/issues/42) se puede ir avanzando en el clonado del repositorio root, core y microcliente de gestión de usuarios y realizar la ejecución del proyecto.

**Comment by edwargl7** [comment]
Se completa la creación del mockup requerido como insumo para este Issue.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/850dfb61-4473-4794-8fa0-6c50dedcceae)

**Comment by edwargl7** [comment]
Vista que se debe construir en el actual formulario del microcliente de gestión de usuarios y roles.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/9069bb1c-8b1f-4d0e-8c78-d46dcabd35df)

**Comment by jucastro94** [comment]
se dio solucion de la pueba de asignacion y designacion de roles [issue #41](https://github.com/udistrital/sisifo_documentacion/issues/41)
se cambian valores de los roles, se les quita "ROL_" al inicio de cada uno

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/431bd554-012d-4503-b000-c9b818043d26)

se cambia el rol predeterminado, a AUDITOR, ya que estaba asignado "ROL_SOPORTE" lo que generaba conflicto

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/a7df4870-edfc-48b0-9ac0-a7975505b177)


se procede a realizar la prueba de designacion de rol



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/cdf64eb5-6439-44ac-bba6-c9a7e62c6e09)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/88584189-d949-408c-b4b3-c8873d202e8d)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8e0b230c-a266-4d6d-b5c3-576cede1673e)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/b5fcc1b8-f497-446b-af13-3af027f18dd9)



se procede a vincular rol EJECUTOR


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/bf0cd86e-db14-4d5f-97eb-6ffe6fa4c073)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/99e50dda-4ca2-4e73-aa6d-4823b0fbe17a)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/af9670c7-ae91-4e98-a790-cb982940a272)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ca062d78-41f5-412d-89ff-1e5602fb48b0)

**Comment by jucastro94** [comment]
se realizan modificaciones para gestionar los roles a traves de indices



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/cdcb203a-baaa-4158-ae03-ff69541dad2d)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/4f9942ec-6971-43ab-a027-437fb22b0347)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/89aaf0c0-f406-4c78-972a-a9b52eb42772)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e77fb221-8ff9-40a6-a8b9-6fd330acca39)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/9200d6a3-7549-4ff2-a6aa-582f1940a924)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/95dd0e09-475b-4fe8-a23a-383c0ef037d4)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/405a12a8-5c7a-4756-a9f7-e72882517c07)

**Comment by edwargl7** [comment]
Pendiente subir cambios al repositorio remoto de los cambios realizados a la lógica del manejo de roles. Se observa en las pruebas que se logra los escenarios requeridos. Buen trabajo.

:pencil2: Se debe crear una nueva tarea en la que se desarrolle el nuevo componente de registro de usuarios.

**Comment by edwargl7** [comment]
Se realiza la revisión del código, sin embargo, no se observa el Pull Request solicitado. Dado que se avanzó en el desarrollo se deben bajar los cambios y resolver conflictos en local y luego solicitar el PR @jucastro94 .

**Comment by edwargl7** [comment]
Se finaliza la Issue con lo requerido, posteriormente se debe realizar ajustes una vez obtenido el microservicio CRUD de gestión de usuarios y roles.
