### ISSUE TITLE
Implementación microservicio de gestión de usuarios y roles - Sísifo v2 - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#45]
Se requiere realizar la implementación del microservicio de gestión de usuarios y roles para Sísifo v2 basado en el modelo relacional aprobado en la [Issue 42](https://github.com/udistrital/sisifo_documentacion/issues/42).

**Especificaciones técnicas**

1. Repositorio de este nuevo microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud).
2. El API debe cumplir con los siguientes lineamientos:
> a. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
> b. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
> c. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
3. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang.

**Sub Tareas**

- [x] Creación de lista de endpoints del servicio basado en [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/40d6f40d-86f2-49e5-9e60-fc8d740749e0)
- [x] Creación de la base de datos basado en el modelo de datos de la [Issue 42](https://github.com/udistrital/sisifo_documentacion/issues/42).
- [x] Creación API REST siguiendo los lineamientos.

**Criterios de aceptación**

- [x] Creación de la base de datos y script de creación.
- [x] Lista de endpoints del API REST siguiendo los lineamientos indicados.
- [x] API REST con los endpoints de la lista.

**Requerimientos**

- [x] Consulta a DBA sobre motor de base de datos a usar.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Motor de base de datos a usar: Postgres

**Comment by jucastro94** [comment]
se crea base de datos con base en [issue #42 ](https://github.com/udistrital/sisifo_documentacion/issues/42)
se deja el archivo.sql en carpeta de proyecyo https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EW1FAnDrIwFJuP2Q84tgiBIBdJR0_LvpDodTWNr1qvVtBQ?e=7N5Ndw

**Comment by jucastro94** [comment]
se hacen correcciones de modelo de datos 

1.Tabla rol

- se ajusta nombre de llave forane a lineamientos

2.Tabla periodo_rol_usuario

- se ajusta tipo de datos para campos de fecha_inicio y fecha_fin


3. se quitan tablas de permisos
4. se presenta modelo de datos con el cual se crea script de base de datos basado en [issue #42](https://github.com/udistrital/sisifo_documentacion/issues/42)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/077de9a2-108a-4cbe-b6a0-20f412d1d74d)

**Comment by jucastro94** [comment]
se crea API con beeGo


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/18813ed5-9492-4ae5-8447-1259d34fb0c2)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/efa78892-63eb-4c49-ad54-598499825fa4)

**Comment by edwargl7** [comment]
# Script base de datos :triangular_flag_on_post:
- Script creado basado en el ejemplo de [inscripcion_crud](https://github.com/udistrital/inscripcion_crud) :white_check_mark:
- Cumple con los lineamientos :white_check_mark:
- Cumple con los campos del modelo de datos aprobado por DBA :white_check_mark:
:wrench: Observación: Se requiere por favor el ajuste en el modelo de datos que el campo _fecha_fin_ de la tabla **periodo_rol_usuario** sea opcional dado que no se conoce siempre la fecha fin del rol y no se debe establecer una fechar arbitraría. :fire:

## Modelo de datos :heavy_plus_sign:
- Se observa la correcta actualización del modelo de datos, buen complemento de la Issue. Tener presente la observación anterior y seguir los lineamientos agregando el modelo de datos en el README del microservicio crud. :white_check_mark:

**Comment by jucastro94** [comment]
se crea API REST y se configura segun los lineamientos
se importa repositorio 	"github.com/udistrital/utils_oas/time_bogota" para configuracion de fechas de creacion y modificacion



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/2a41732b-c90b-493a-aeee-649b9d054fd9)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/91809f2d-e4da-419e-a8c2-697ed1382394)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/3783c36d-8e4b-475c-b2e2-3aef9dc6db61)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/066f9cac-24dd-4f94-a0f6-c537a5ad43d2)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/5a3b3277-70fc-4f5f-b1cb-6de689f69592)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/051bb0ca-d3ac-403d-ac57-7744155a25f6)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ac053887-b78d-4561-8b02-81bea0a6bea8)


igualmente para los 4 controladores

**Comment by jucastro94** [comment]
se ajusta modelo de datos y se carga a carpeta del proyecto [usuarios y roles V3.1](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdKRAKvigVlHgzioCnIWReQBAgDIL76X7OX0-hrZIJGEMA?e=qiJgEJ)


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/0a47c066-cfb5-44fd-bbbe-374d3efa7e0a)


se ajusta script de base de datos, se quita NOT NULL a campo fecha_fin para asi ser opcional

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/39747fb0-5f61-40b1-9fe3-9ffe4b8b91df)

se carga archivo .sql a carpeta del proyecto  [usuario_rol.sql](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EQcp-JirNktCkBfj7iTKvokBJT_8qAj4OW07fQM_lHY5Ag?e=RRSPML)

**Comment by jucastro94** [comment]
lista de enpoints con swagger


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/60d80998-5d23-4c4b-a661-d1e266133769)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/09883474-117b-4f4c-9925-77ce61571560)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/76bae317-15a0-49fc-a762-98037d164267)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ed7d2bb0-59bb-40b5-b624-25adb78e254e)

**Comment by jucastro94** [comment]
se realizan pruebas a CRUD usuario

POST

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/66874a2c-aa9f-496c-a1f0-0e7f5e4ed49e)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/2a1faeda-b8bb-4ada-ab5a-5ead551f910d)

GET


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e0b978b3-5943-4720-a8c1-143ddd7eb0ba)

GET ONE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/1fd6921e-e22d-4dc2-b08c-cfe960eecdad)

UPDATE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/bbb22d4f-6dc0-4016-bc78-b65a8d00512f)

DELETE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/edf23adc-88d5-439d-aa0a-438e97040cd5)


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/71f4fbf8-e381-4f14-b1d8-e884f7bad868)

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/2a56c35e-4f80-4b22-b841-b2a008b77242)

**Comment by jucastro94** [comment]
se corrigen endpoints


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/bbf80624-9511-47c3-9a16-90f9cebaaba8)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f49c5aff-57ff-4cdd-ae95-7cbcaf807ede)

**Comment by jucastro94** [comment]
se agrega codigo para mantener fecha de creacion a la hora de actualizar para cada controller 


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/4bb13805-94a5-425b-840f-5e755f2028b6)

**Comment by jucastro94** [comment]
se realiza pruebas para CRUD de  "periodo rol usuario"
POST


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/d4b1404c-e2cd-41fe-92fe-23f563001659)

GET ONE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e98a87cd-e0fc-41c1-b84f-73602c7b4289)


GET ALL



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f43c8148-4a4e-44e8-bfe9-6ecb06b0e361)

UPDATE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/2222cdf3-32c2-436a-9d85-51bc9b318c2e)
se evidencian error en la integridad de la fecha de creacion


DELETE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/48a6c4cd-ba61-4c11-86f7-cc51f93bc38a)

**Comment by jucastro94** [comment]
se realizan pruebas para CRUD "rol"

- POST


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/bb1e93af-5561-4599-ab8a-3b7b0189f43c)


- GET ONE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/1b8f5a66-b309-4fed-b764-755b98c4eb0b)


- GET ALL


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/59ee7f08-dd1a-401f-8f7a-841d18e03527)


- PUT


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/9a86e789-c2b3-40d9-bd9c-24d9a43a98f6)


- DELETE

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/4cf70d84-117d-441b-b9da-273582ac00dc)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/17de754b-671a-4f53-a5c4-137c0717eb2a)

**Comment by jucastro94** [comment]
se realizan pruebas de CRUD "periodos-rol-usuario"

POST



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8c62873f-679c-4751-a4f2-9991cab75e5e)

se presentan fallas en FechaInicio y FechaFIn 


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/a584bc00-b960-4052-a0c5-efb0f6ae09af)

se realiza insercion por gestor de base de datos para las siguientes pruebas

GET ONE


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7e2663c1-2c04-4af6-8cdf-249c4648c614)


GET ALL


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/72dad396-6fa3-4678-b645-d31a54adbcd6)


PUT


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/aec8ec82-79cf-4783-b588-cba0f082f3aa)
se presentan fallas en FechaInicio y FechaFIn 

DELETE



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/bb946d22-a74c-476c-b466-1db7c6f13eae)


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/9a560577-09b1-4a41-91c9-d2c5286748c0)

**Comment by jucastro94** [comment]
se realiza Pull Request a develope

**Comment by edwargl7** [comment]
Ya se encuentra resuelto el PR y cumple con lo requerido. Buen trabajo.
