### ISSUE TITLE
Agregar Docker al microservicios de gestión de usuarios y roles - Sísifo v2 - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#46]
Se requiere realizar la creación del Dockerfile, docker compose y la documentación del README del microservicio de gestión de usuarios y roles [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud).

**Especificaciones técnicas**

1. Repositorio del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud).
2. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
3. El archivo docker-compose debe tener la configuración para ejecutar el servidor del microservicio y de la base de datos.
4. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md).

**Sub Tareas**

- [x] Creación del archivo Dockerfile.
- [x] Creación del archivo docker-compose.
- [x] Documentación del README siguiendo los lineamientos.

**Criterios de aceptación**

- [x] Creación del Dockerfile y docker-compose siguiendo los lineamientos.
- :lock: Documentación de las pruebas realizadas que permitan validar el correcto funcionamiento del servicio con la base de datos por medio del docker compose.

**Requerimientos**

- [ ] Implementación del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) de la [Issue 45](https://github.com/udistrital/sisifo_documentacion/issues/45)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se adecua archivo README


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7dce7c01-af37-474c-9a22-99df963cdc78)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/50633d7c-727b-45a6-8c51-763861baa63a)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/88e48615-ac70-45d4-b3d5-2ee9abe63ba5)

**Comment by jucastro94** [comment]
se genera archivos dockerfile y docker-compose.yml


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/66d016f6-8a73-4c50-84ef-378c20c090e1)

**Comment by jucastro94** [comment]
archivo dockerfile

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/287ee30f-66b1-4588-83cf-6a48323a6d7b)

**Comment by jucastro94** [comment]
es necesario cambiar la version de golang como se comento antes de realizar el dokerizado adecuadamente,

**Comment by edwargl7** [comment]
Se continuará con esta tarea en la Issue #76. Para poder finalizar esta Issue documentar por favor los errores que surgieron en la ejecución del Docker.

**Comment by jucastro94** [comment]
se ejecuta comando docker-compose build, con dockerfile


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/a22b6597-574b-423f-9f9e-5df3cbdd11f0)

**Comment by jucastro94** [comment]
se ejecuta comando docker-compose build, con dockerfile

# Etapa 1: Compilación
FROM golang:1.20 as builder
 
# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app
 
# Copiar los archivos del proyecto al directorio de trabajo
COPY . .
 
# Descargar las dependencias del proyecto
RUN go mod download
 
# Compilar la aplicación Go
RUN go build -o main .
 
# Etapa 2: Construcción de la imagen final
FROM debian:bullseye-slim
 
# Crear un directorio dentro del contenedor para la aplicación
WORKDIR /app
 
# Copiar el binario compilado desde la etapa de compilación
COPY --from=builder /app/main .

se completa satis satisfactoriamente pero a la hora  ejecutar lanza 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ee9ad29f-71b8-47fe-a590-ff2e40ba71d3)

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/d61b16eb-f138-46fe-839b-69087a3ac3c4)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e76e44f7-64c5-4b7e-8343-6ba01f30c2fd)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/26b60b2e-cdaa-4e9c-8acd-9fcffc6b3751)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/537dd331-fa1f-4449-81cf-2422be8ae4ba)

**Comment by edwargl7** [comment]
Se finaliza la Issue con la documentación requerida, se continua el trabajo con Docker con el trabajo de cambio de versión.
