### ISSUE TITLE
Integración microservicio y microcliente de gestión de usuarios y roles - Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#47]
Se requiere realizar la integración del microservicio de gestión de usuarios y roles [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) con el microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf). Esta integración debe permitir registrar usuarios con un rol especifico y el periodo de fecha inicio y fin, además permitir la activación y desactivación de usuarios.

**Sub Tareas**

- [x] Integración microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) y microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf) manteniendo la integración con WSO2.
- [x] Pruebas registrando usuario con un rol.
- [ ] Prueba terminando periodo del usuario con un rol.
- [ ] Prueba desactivando y activando un usuario.

**Criterios de aceptación**

- [ ] Integración microcliente, microservicio y WSO2.
- [ ] Pruebas del correcto funcionamiento de la gestión de usuarios y roles.

**Requerimientos**

- [ ] Implementación del microservicio en la [Issue 45](https://github.com/udistrital/sisifo_documentacion/issues/45)
- [ ] Maquetación del formulario de registro y tabla de visualización de usuarios registrados.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Avances integración

Se ejecuta el script para la creacion de la base de datos

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/b10f4e0e-0aac-4a29-a8d9-1a98850747b7)

Se clona el repositorio del histórico_usuarios_roles_crud

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/15586dac-7552-4868-8a7b-af794db3a67f)

Se actualizan las variables de entorno para la ejecución del proyecto

Se encontraron varios errores al tratar de ejecutar el proyecto con go, por lo que tuve que realizar nuevamente su instalación completa asi como el framework, despues de solucionar estos problema se logra compilar el proyecto y acceder al swagger

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/bbccfa40-79ab-4c84-959b-c54b8344bcfe)

**Comment by alexhrr** [comment]
Se realiza la revisión de la tarea junto al líder para aclarar dudas con respecto a la integración y algunas partes se deben  detener hasta solucionar las inquietudes. 
Se debe consultar y definir la forma en la que se va a realizar la integración de los roles.

**Comment by alexhrr** [comment]
## Avance Integración

De acuerdo a lo decidido con el equipo se comienza con la integración de los servicios haciendo uso del request manager y por aparte el servicio como se muestra a continuación: 

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/901c486c-6c9f-4229-b308-cb1e5abea31c)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/18adb37e-a36a-4192-80fe-66bbaecfbe55)

Se hace la petición al servicio para mostrar los diferentes roles en el selector de la interfaz de creación de usuario

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/6ad462cd-73c0-464a-9f64-d8e430c267ea)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/4db17e39-e117-43a0-a965-a6c61e095e89)

Con esta implementación de la nueva estructura se deben ajustar los servicios que se consumían anteriormente y se debe aplicar tambien al selector de la interfaz de actualización

**Comment by alexhrr** [comment]
### Avances Integración

Se cambian los iconos por botones para los inputs de documento y correo en la interfaz de creación:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/7d88c8ea-e6bd-4998-b209-100f17d33017)

Se agrega la integración de roles a la interfaz  de actualización de usuarios:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/109e1862-6755-4c5f-98c5-01e56d391162)

### Revisión consulta de terceros

Como un acercamiento inicial a la consulta de terceros, se encuentra la siguiente información en el sistema de planeación:

Environment: se crea la ruta en las variables de entorno:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/39be67ec-f3d3-4a90-b35a-88802a9c8144)
 
Se llama a la ruta en los componentes que se requiera para la consulta:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/3c3d3f15-57c2-4d17-be20-658db8609b96)

Servicio: Se crea el acrivo tipo "service"

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/1da92c2d-a4b2-4617-9f6c-ebd51ad01048)

**Comment by edwargl7** [comment]
Se finaliza la Issue, con los insumos actuales se completa correctamente la Issue. Se debe complementar la integración con otros sistemas para completar el registro completo de este módulo. Buen trabajo y análisis.
