### ISSUE TITLE
Investigación formularios reactivos para gestión de la auditoría - Parte 3

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#48]
Se requiere continuar con la investigación de los formularios reactivos abordada en la Issue #39. El documento entregado es una base fundamental en esta investigación, en esta nueva Issue se aborda un enfoque más exploratorio sobre el proyecto SGA tomado como ejemplo. La finalidad de esta investigación es la generación de la estructura y modelos base para la creación de los formularios que presentan una modificación constante y no periódica. Por lo que este enfoque da un manejo adecuado para este escenario presentado por el usuario.  

**Sub Tareas**

- [x] Continuar con la investigación de formularios reactivos.
- [x] Establecer la estructura que permita la creación del formulario a partir de un json [ver](https://github.com/udistrital/sga_cliente/blob/d2275c64763a36410a3640e1ea098797a5ace81d/src/app/pages/espacios-academicos/creacion-espacios-academicos/form-espacio_academico.ts)
- [x] Continuar con la documentación técnica.

**Criterios de aceptación**

- [x] Definición de las estructura y modelos base para un formulario con elementos HTML usados para los formularios de este proyecto identificados inicialmente (select, input, textarea).

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Estructura o modelos iniciales para los formularios reactivos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se continúa con la implementación del código para el formulario dinámico junto a @alexhrr.

Se ha creado un nuevo componente para separar la lógica del formulario dinámico, reajustando el manejo de las rutas para el uso de este nuevo componente.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/6444f61a-cef7-492d-9c0b-f34bed1ab4b9)
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/2c51a13a-f5e7-457d-9e37-cba6d9c9d4dd)

Se ha iniciado la implementación del nuevo componente en el componente de usuarios ya existente.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/ab487f87-e331-45ae-9c09-1d3c22e603f3)

Actualmente, se presentan errores en la exportación de los componentes, los cuales están siendo revisados.

En cuanto a la documentación, se han planteado nuevos temas a añadir:

- Cómo crear un módulo que implemente el módulo de creación de formularios dinámicos.
- Lógica de creación de los campos por demanda; nuevos campos creados según la necesidad del usuario.

**Comment by CristianCGutierrezG** [comment]
Se ha avanzado en el desarrollo del formulario, logrando mostrar un formulario básico creado con base en la documentación planteada.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/0c6ca443-59bd-4488-930e-442f741bc85a)

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/ce02baba-aa23-4ce2-9674-0b81a7abfb66)

Además, se actualizó el documento [Investigación sobre formularios reactivos](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EeCFmD4PFEBJk9WpeEVF3CABz-qWyqJJ4GDQ1iaBDZJFxg?e=24xrn4) con la información recopilada durante el desarrollo del formulario.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/3aec8f8e-b5e0-41c3-91d0-2640261108f6)

**Comment by CristianCGutierrezG** [comment]
Se ha desarrollado la estructura y los modelos para un formulario utilizando elementos HTML básicos como <select>, <input> y <textarea>, tomando como base el desarrollo del SGA.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/81cf9384-8913-4476-b68d-ce188273ec5f)

Además, se ha logrado la creación de formularios dinámicos y reactivos a partir de un JSON, los cuales responden a los diferentes eventos.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/1d8da8f0-06bc-4c9d-8168-3b1a2fefc84a)

**Comment by edwargl7** [comment]
Se revisa la documentación y resultados. Se observa un buen ejercicio de prueba de concepto y buena documentación.
