### ISSUE TITLE
Pruebas formularios reactivos para gestión de la auditoría - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#49]
Se requiere continuar con el apoyo a la investigación e implementación de la prueba de concepto de los formularios reactivos iniciada en la Issue #40.

**Sub Tareas**

- [x] Revisión documentación generado en las Issue #39  y #40.
- [x] Implementación de prueba de concepto replicando el formulario de gestión de roles y usuarios de [Issue #24](https://github.com/udistrital/sisifo_documentacion/issues/24)

**Criterios de aceptación**

- [x] Evidencias de los resultados obtenidos.
- [x] Rama con el desarrollo realizado sin realizar el Pull Request.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Avance formularios dinámicos

Se continua con la implementación del codigo para el formulario dinámico junto a Cristian.

Se crea un nuevo componente para el separar la lógica del  formulario dinámico

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/a7fbbd73-673e-45ef-96c8-6f44e89870c7)

Se modifica la plantilla del formulario usando FormParams para generalizar la plantilla

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/194c9d14-d7a4-4ced-a184-28eefdb2c85a)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/3a6179dd-c8a4-4f43-827f-1b910fb96191)

Se debe continuar con la revisión y comprensión del codigo de SGA.

**Comment by alexhrr** [comment]
Se continua con la implementación del codigo para el formulario dinámico junto a Cristian, corrigiendo errores en las rutas para el componente dinámico.

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/9eb43daa-3aea-447e-bfc1-7012fa69d5b0)

**Comment by alexhrr** [comment]
# Avance Formularios dinámicos

En el trabajo realizado junto a Cristian se logra mostrar en la pagina el formulario de prueba con unos campos de ejemplo usando un input y un select como se ve a continuación: 

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/0530e567-e273-4f9a-b58a-5884d55c6607)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d06e0ca3-2299-44da-9819-eb75236d0ab6)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d711093a-767d-4734-906e-480f0e0cfa02)

Actualmente se debe corregir la parte de estilos para que los FloatLabel se puedan visualizar correctamente.

**Comment by alexhrr** [comment]
## Resultados formulario dinámico

Junto a Cristian se realiza la estructura del formulario dinámico solicitado, incluyendo los campos de input, select y text area.
A continuación se muestra la estructura realizada:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/51dfd9a1-f853-4bdd-9888-87fa92c9ab60)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d975fb52-12fa-46b8-b91e-9dcde86c2a8e)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/ede7e6b1-d9c1-45c8-87d5-69e48374d6c5)

Se crea la rama de pruebas_formulario_dinamico y se deja en el repositorio el codigo desarrollado:
https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf.git

Se debe revisar el uso de los estilos para los formularios, en este caso el floatLabel no se ve correctamente al ingresar datos a los campos del formulario.

**Comment by edwargl7** [comment]
Se realiza la revisión del código de la rama creada, y se observa correctamente la prueba de concepto. El tema de estilos se debe revisar con los otros equipos que actualmente han trabajado más con microclientes. Se recomienda no usar Bootstrap para los estilos por recomendación de la OATI. Muy buen trabajo.
