### ISSUE TITLE
Proyectar el Diseño del mockup de la vista del modulo Gestión de usuarios

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#50]
Se requiere proyectar el diseño del mockup para la vista del módulo Gestión de usuarios de ARGO V2

**Sub Tareas**

- [x] Desarrollar reunión de requerimientos.
- [x] Proyectar el diseño mockup con base en los requerimientos del líder de desarrollo.
- [x] Presentar el mockup al equipo.
- [x] Realizar ajustes según comentarios.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el desarrollo del mockup del módulo de gestión de usuarios para el sistema SISIFO V2.

![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/37d146b2-f7d9-48d8-b344-192d336013ce)


Saludos.

**Comment by edwargl7** [comment]
Se realiza una reunión con el analista y se realizan ajustes al mockup propuesto. Desde el punto de vista del técnico se aprueba el resultado.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/88c98ebe-aba1-4673-9372-916adc2dcdca)

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza diseño de mockup del módulo Gestión de Usuarios.

**Enlace del diseño cargado en OneDrive en la carpeta correspondiente del proyecto**
**Mockup Módulo Gestión de Usuarios**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=AQouL7


**Enlace Grabación realizada con el líder técnico del proyecto - Revisión y Ajustes**
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/EURjVcGVS01EsvgGBxp4fn0BnAIhw5iKymFAnihxAhtKuA?e=WAddea&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo equipo @edwargl7 @cjgonzalez. Lo revisamos detenidamente en la próxima sesión SoS.

**Comment by jcmurilloa** [comment]
Por favor @cjgonzalezp actualizar el mockup según revisión adelantada y compatir nuevamente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes del mockup de gestión de usuarios según la revisión en conjunto.

**Enlace del diseño cargado en OneDrive en la carpeta correspondiente del proyecto
Mockup Módulo Gestión de Usuarios**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=vux7ig

**Diseño Mockup con ajustes - Mockup Módulo Gestión de Usuarios**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/9b3fb3fc-fb2c-4810-9697-0b8c0ac622ed)


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, ahora a mostrar al cliente!

**Comment by cjgonzalezp** [comment]
Buen día, @jcmurilloa @edwargl7 

Se presenta el diseño del mockup del módulo de gestión de usuarios al cliente. Solo se sugiere por parte del cliente implementar un botón para poder exportar a Excel la base de datos de todos los usuarios creados.

Se recibe por parte del cliente aprobación del módulo de gestión de usuarios para desarrollo e implementación.

**Enlace del diseño cargado en OneDrive en la carpeta correspondiente del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=28e1Pl

**Acta de Reunión 066/2024 presentación y aprobación diseño mockup modulo gestión de usuarios**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et-a7_BrY3pEmFZ6uZF0QY0B9nxrTf9efMi3aD9Bn96RlQ?e=U072G6



Saludos.
