### ISSUE TITLE
Realizar PR de documentación README roots Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#51]
Se requiere realizar nuevamente el Pull Request de la documentación de los README de los root basado en las observaciones mencionadas en la Issue #37 siguiendo los lineamientos de [Etiquetas en Comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md).

**Sub Tareas**

- [x] Crear nuevamente los PR de los repositorios root de la Issue #37.

**Criterios de aceptación**

- [x] Pull Request con los lineamientos sugeridos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se crea el Pull Request con los lineamientos, según lo solicitado

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/09b2bc77-65b4-4be4-a40a-b73fac5e7673)

**Comment by edwargl7** [comment]
Finalizada la Issue correctamente.
