### ISSUE TITLE
Proyectar un informe técnico ejecutivo del proyecto para el periodo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#52]
Se requiere proyectar un informe técnico ejecutivo sobre cada línea de acción del proyecto para socialización con el patrocinador del proyecto, alimentando el informe del mes anterior: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ERC_-j07j4lMmdAmNCB0ZRABSRGo1EOGVmBf2AboeC0ADg?e=bVL3Uz

**Sub Tareas**

- [x] Establecer avances por cada línea de acción del proyecto en el periodo
- [x] Mencionar las limitantes encontradas en el proyecto en el periodo
- [x] Registrar nuevas líneas de acción del proyecto en el periodo

**Criterios de aceptación**

- [x] Informe ejectivo proyectado y enviado a líder de proyecto

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por líder de proyecto.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el desarrollo del informe técnico ejecutivo del proyecto SISIFO V2

**Se alimenta documento compartido con los parámetros solicitados, adjunto enlace del documento**
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/jcmurilloa_udistrital_edu_co/EbIzkwLpTl1JpboUM1Ex_wABF-dgzIV6EMuNHU3eZj6tqg?e=5sUVYI

**Enlace documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EuU_hkGDpFpGjcnbOtxncnwB-XZlU8SmoayJPI947OQKAg?e=P3C7Hj


Saludos.

**Comment by edwargl7** [comment]
Se realiza la actualización del estado actual de Sísifo.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/a9e50512-e4cb-4da9-a3cc-46eb5380d2c0)

**Comment by edwargl7** [comment]
Actualizado reporte ejecutivo con los avances, limitantes y proyecciones del proceso actual de Sísifo v2.

**Comment by jcmurilloa** [comment]
Gracias por sus aportes @cjgonzalezp y @edwargl7. El informe consolidado y la presentación la encuentran en el espacio https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EhDMY7HVPXhHjubEgwiKyjQBu3nxmcWcMA89IOXY3G4YOQ?e=AgdZaK
