### ISSUE TITLE
Realizar PR microcliente en el root Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#53]
Se requiere realizar nuevamente el Pull Request de la adición del microcliente auditoria_plan_mejoramiento_usuario_mf al root [ver](https://github.com/udistrital/auditoria_plan_mejoramiento_root_mf/tree/feature/ruta_configuracion_mf
) y remover la carpeta .vscode de [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).

**Sub Tareas**

- [x] Creación PR siguiendo los lineamientos.
- [x] Remover carpeta .vscode del repositorio del microcliente auditoria_plan_mejoramiento_usuario_mf.

**Criterios de aceptación**

- [x] PR siguiendo los lineamientos y recomendaciones dadas en la planning.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizó una nueva PR siguiendo los lineamientos.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/46eb09a3-f99d-498e-aeae-5dde66811fd7)

También se intentó eliminar la carpeta .vscode del repositorio del microcliente auditoria_plan_mejoramiento_usuario_mf, pero el permiso de subida fue denegado a menos que se cree una nueva rama.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/688bb3ba-be92-486d-886b-e9ce7c68499a)

**Comment by edwargl7** [comment]
Finalizada Issue correctamente.
