### ISSUE TITLE
Desarrollo interfaz del microcliente de gestión de usuarios y roles - Registro/Edición de usuario

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#54]
Se requiere crear el componente para el formulario de registro y edición de usuarios y roles Realizando la maquetación sin incluir la integración con el microservicio de gestión de usuarios y roles.

**Sub Tareas**

- [x] Realizar el desarrollo de la interfaz gráfica basado en el [mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Eb2K_WA3cdVNuebskYqgMZMBJ7fOwSzRZheVK47zcszfeQ?e=JtLjiT).

**Criterios de aceptación**

- [x] Creación de la rama con el desarrollo indicado.

**Especificaciones técnicas**

1. Repositorio de este microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)
2. Se requiere seguir implementado el cliente empleando single-spa.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
4. Maquetar el registro y edición de usuario del [mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Eb2K_WA3cdVNuebskYqgMZMBJ7fOwSzRZheVK47zcszfeQ?e=JtLjiT).
![Image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/1151d001-f3f0-4686-b46e-807ae17704a2)
![Image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/0ee611f5-ec58-4731-bb07-71c6764cf524)
5. No se debe consumir ningún endpoint de microservicios, solo realizar la maquetación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se realiza la clonación del repositorio del microcliente, se crea la nueva rama en local y se da inicio a la creación del componente

**Comment by alexhrr** [comment]
## Avance desarrollo interfaz

Se realiza la maquetación inicial del componente para el formulario de registro de usuarios mostrado a continuación. 

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/f5ed785b-261b-42b7-b2ec-5b5b528f31d4)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/9d475c8e-5732-4ff0-9338-b9e073e4b636)

Se debe terminar de ajustar esta interfaz de acuerdo al mockup y continuar con el formulario de actualización de usuarios.
Se han encontrado dificultades para el manejo de los estilos de Angular

**Comment by edwargl7** [comment]
Buen trabajo, información importante para el manejo de estilos en microclientes según lo conversado con varios líderes y desarrolladores que han guiado este proceso en la OATI. 

## 1. Definición estilos
En resumen, cada microcliente parcel complementa y maneja estilos para angular material y los que sean pertinentes agregando el siguiente script en la ruta src/assets/styles/<nombre-archivo>.scss

```
@use '@angular/material' as mat;

@include mat.core();

$md-primary: (
  50 : var(--md-primary-50),
  100 : var(--md-primary-100),
  200 : var(--md-primary-200),
  300 : var(--md-primary-300),
  400 : var(--md-primary-400),
  500 : var(--md-primary-500),
  600 : var(--md-primary-600),
  700 : var(--md-primary-700),
  800 : var(--md-primary-800),
  900 : var(--md-primary-900),
  A100 : var(--md-primary-A100),
  A200 : var(--md-primary-A200),
  A400 : var(--md-primary-A400),
  A700 : var(--md-primary-A700),
  contrast: (50 : var(--md-primary-contrast-50),
    100 : var(--md-primary-contrast-100),
    200 : var(--md-primary-contrast-200),
    300 : var(--md-primary-contrast-300),
    400 : var(--md-primary-contrast-400),
    500 : var(--md-primary-contrast-500),
    600 : var(--md-primary-contrast-600),
    700 : var(--md-primary-contrast-700),
    800 : var(--md-primary-contrast-800),
    900 : var(--md-primary-contrast-900),
    A100 : var(--md-primary-contrast-A100),
    A200 : var(--md-primary-contrast-A200),
    A400 : var(--md-primary-contrast-A400),
    A700 : var(--md-primary-contrast-A700),
  )
);

$md-accent: (
  50 : var(--md-accent-50),
  100 : var(--md-accent-100),
  200 : var(--md-accent-200),
  300 : var(--md-accent-300),
  400 : var(--md-accent-400),
  500 : var(--md-accent-500),
  600 : var(--md-accent-600),
  700 : var(--md-accent-700),
  800 : var(--md-accent-800),
  900 : var(--md-accent-900),
  A100 : var(--md-accent-A100),
  A200 : var(--md-accent-A200),
  A400 : var(--md-accent-A400),
  A700 : var(--md-accent-A700),
  contrast: (50 : var(--md-accent-contrast-50),
    100 : var(--md-accent-contrast-100),
    200 : var(--md-accent-contrast-200),
    300 : var(--md-accent-contrast-300),
    400 : var(--md-accent-contrast-400),
    500 : var(--md-accent-contrast-500),
    600 : var(--md-accent-contrast-600),
    700 : var(--md-accent-contrast-700),
    800 : var(--md-accent-contrast-800),
    900 : var(--md-accent-contrast-900),
    A100 : var(--md-accent-contrast-A100),
    A200 : var(--md-accent-contrast-A200),
    A400 : var(--md-accent-contrast-A400),
    A700 : var(--md-accent-contrast-A700),
  )
);

$md-warning: (
  50 : var(--md-warning-50),
  100 : var(--md-warning-100),
  200 : var(--md-warning-200),
  300 : var(--md-warning-300),
  400 : var(--md-warning-400),
  500 : var(--md-warning-500),
  600 : var(--md-warning-600),
  700 : var(--md-warning-700),
  800 : var(--md-warning-800),
  900 : var(--md-warning-900),
  A100 : var(--md-warning-A100),
  A200 : var(--md-warning-A200),
  A400 : var(--md-warning-A400),
  A700 : var(--md-warning-A700),
  contrast: (50 : var(--md-warning-contrast-50),
    100 : var(--md-warning-contrast-100),
    200 : var(--md-warning-contrast-200),
    300 : var(--md-warning-contrast-300),
    400 : var(--md-warning-contrast-400),
    500 : var(--md-warning-contrast-500),
    600 : var(--md-warning-contrast-600),
    700 : var(--md-warning-contrast-700),
    800 : var(--md-warning-contrast-800),
    900 : var(--md-warning-contrast-900),
    A100 : var(--md-warning-contrast-A100),
    A200 : var(--md-warning-contrast-A200),
    A400 : var(--md-warning-contrast-A400),
    A700 : var(--md-warning-contrast-A700),
  )
);

$light-theme: mat.define-light-theme((color: (primary: mat.define-palette($md-primary, 500),
        accent: mat.define-palette($md-accent, 500),
        warn: mat.define-palette($md-warning, 500),
      ),
      typography: mat.define-typography-config($font-family: 'Open Sans',
      ),
      desity: 0,
    ));

@include mat.all-component-themes($light-theme);
```

Donde,
```
/* Importación de Angular Material */
@use '@angular/material' as mat;
```
Permite usar las funciones del módulo de Angular Material y mixins en el archivo de estilos.

```
/* Inclusión del Núcleo de Angular Material */
@include mat.core();
```
Este mixin incluye los estilos básicos necesarios para Angular Material. Debe incluirse al menos una vez en su aplicación para que los componentes de Angular Material se rendericen correctamente.

```
/* Definición de Paletas de Colores */

/* Paleta primaria */
$md-primary: (...}

/* Paleta acento*/
$md-accent: (...}

/* Paleta Advertencia */
$md-warning: (...}
```
Se definen las paletas de colores _primary_, _warning_ y _accent_, para cada tonalidad del color, desde 50 hasta A700 basado en los estilos proporcionados en [assets](https://github.com/udistrital/assets) . Las variantes de contraste (contrast) también se definen para asegurar que el texto sobre el color primario sea legible.

```
/* Definición del tema claro */
$light-theme: mat.define-light-theme(
...
);
```

```
/* Asignación colores a Angular Material */
@include mat.all-component-themes($light-theme);
```
Finalmente, se aplica el tema definido a todos los componentes de Angular Material. Este mixin asegura que todos los componentes utilicen los colores, tipografía y densidad definidos en _light-theme_.

### Material adicional:
- lineamientos [Estilos de Angular Material](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/core.md#estilos-de-angular-material)
- [Theming Angular Material](https://material.angular.io/guide/theming)

## 2. Uso de estilos
Para poder usar los estilos se debe en cada microcliente referenciar los estilos en el script _angular.json_ en:
```
...,
"styles": [
  "src/assets/styles/<nombre-archivo>.scss",
  ...
],
...
```

**Comment by alexhrr** [comment]
### Avance formulario

Se revisa el material suministrado para el manejo de estilos y se implementa en el microcliente, los errores de estilos que se tenían con respecto al formulario quedan solucionados como se observa en la segunda imagen.

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/0b8499cc-5cdb-4be7-8f9c-9ddf21c602be)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d54fe261-b36d-422b-9b62-09383d50ebfb)

Asi mismo se inicia con la creación del componente de actualización de usuarios para trabajarla con Juan Miguel.

**Comment by alexhrr** [comment]
## Creación de los componentes
Se finaliza la creación de los componentes para la sección de creación y actualización de usuarios según el mockup suministrado para cada uno.

### Creación de usuario
![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/3f4d2b9c-ae9a-4655-94ce-0982b5d93189)

### Actualización de usuario
![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/c2f3aef5-53d0-4729-878b-78b77f860f77)

Se socializa el proceso de creación del componente con Juan Miguel.
Se realizaron los ajustes de tamaño para los inputs de documento de identidad y correo.
Se crea  la rama con el desarrollo indicado.

**Comment by edwargl7** [comment]
Se corrigen los commits.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/dce0040c-3949-41d8-a65c-dd565ebcd929)

**Comment by edwargl7** [comment]
Por qué fue necesario agregar <br /> en la parte superior del componente?
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/61ca164a-b063-4a36-a720-47e2661073a1)

**Comment by edwargl7** [comment]
Adicional a las observaciones anteriores no se encuentra nada más, buen trabajo. Por favor, realizar el PR. Antes de solicitarlo debe bajar los cambios que tiene la rama develop y resolver conflictos. Luego crear el PR.

**Comment by edwargl7** [comment]
Finalizada la tarea con el PR resuelto. Buen trabajo.
