### ISSUE TITLE
Desarrollo interfaz del microcliente de gestión de usuarios y roles - Vista de consulta de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#55]
Se requiere realizar el desarrollo de la vista de consulta de usuarios registrados en el microcliente de gestión de usuarios y roles basado en el [mockup]().

**Sub Tareas**

- [x] Realizar el desarrollo de la interfaz gráfica basado en el [mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Eb2K_WA3cdVNuebskYqgMZMBJ7fOwSzRZheVK47zcszfeQ?e=JtLjiT).

**Criterios de aceptación**

- [x] Creación de la rama con el desarrollo indicado.

**Especificaciones técnicas**

1. Repositorio de este microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf)
2. Se requiere seguir implementado el cliente empleando single-spa.
3. El API debe cumplir con los [lineamientos](https://github.com/udistrital/lineamientos_oas) establecidos para la creación de nuevos clientes definidos por la OATI.
4. Maquetar el registro de usuario del [mockup](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Eb2K_WA3cdVNuebskYqgMZMBJ7fOwSzRZheVK47zcszfeQ?e=JtLjiT).
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/da05a040-ce03-4fec-9b61-5a020d5d9938)
5. No se debe consumir ningún endpoint de microservicios, solo realizar la maquetación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se inicia el desarrollo de la vista de consulta de usuarios en una nueva rama, utilizando como base el desarrollo de la issue https://github.com/udistrital/sisifo_documentacion/issues/24 y  los mockups propuestos. 
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/96dabb6e-f034-4cc1-8936-0149b6caa8e8)

**Comment by CristianCGutierrezG** [comment]
Se progresa con el desarrollo del maquetado, incorporando datos aleatorios para observar el comportamiento tanto de la tabla como del formulario de búsqueda.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/6ac2e782-fe8a-4edb-abf1-8f7b8e8f9f09)

Se presentan dificultades al entender como funcionan los estilos predeterminados de Angular Material y como cambiarlos.

**Comment by edwargl7** [comment]
Buen trabajo, para el manejo de estilos se abordará en más detalle en el siguiente daily. En resumen, cada microcliente parcel complementa y maneja estilos para angular material y los que sean pertinentes agregando el siguiente script en la ruta src/assets/styles/<nombre-archivo>.scss

```
@use '@angular/material' as mat;

@include mat.core();

$md-primary: (
  50 : var(--md-primary-50),
  100 : var(--md-primary-100),
  200 : var(--md-primary-200),
  300 : var(--md-primary-300),
  400 : var(--md-primary-400),
  500 : var(--md-primary-500),
  600 : var(--md-primary-600),
  700 : var(--md-primary-700),
  800 : var(--md-primary-800),
  900 : var(--md-primary-900),
  A100 : var(--md-primary-A100),
  A200 : var(--md-primary-A200),
  A400 : var(--md-primary-A400),
  A700 : var(--md-primary-A700),
  contrast: (50 : var(--md-primary-contrast-50),
    100 : var(--md-primary-contrast-100),
    200 : var(--md-primary-contrast-200),
    300 : var(--md-primary-contrast-300),
    400 : var(--md-primary-contrast-400),
    500 : var(--md-primary-contrast-500),
    600 : var(--md-primary-contrast-600),
    700 : var(--md-primary-contrast-700),
    800 : var(--md-primary-contrast-800),
    900 : var(--md-primary-contrast-900),
    A100 : var(--md-primary-contrast-A100),
    A200 : var(--md-primary-contrast-A200),
    A400 : var(--md-primary-contrast-A400),
    A700 : var(--md-primary-contrast-A700),
  )
);

$md-accent: (
  50 : var(--md-accent-50),
  100 : var(--md-accent-100),
  200 : var(--md-accent-200),
  300 : var(--md-accent-300),
  400 : var(--md-accent-400),
  500 : var(--md-accent-500),
  600 : var(--md-accent-600),
  700 : var(--md-accent-700),
  800 : var(--md-accent-800),
  900 : var(--md-accent-900),
  A100 : var(--md-accent-A100),
  A200 : var(--md-accent-A200),
  A400 : var(--md-accent-A400),
  A700 : var(--md-accent-A700),
  contrast: (50 : var(--md-accent-contrast-50),
    100 : var(--md-accent-contrast-100),
    200 : var(--md-accent-contrast-200),
    300 : var(--md-accent-contrast-300),
    400 : var(--md-accent-contrast-400),
    500 : var(--md-accent-contrast-500),
    600 : var(--md-accent-contrast-600),
    700 : var(--md-accent-contrast-700),
    800 : var(--md-accent-contrast-800),
    900 : var(--md-accent-contrast-900),
    A100 : var(--md-accent-contrast-A100),
    A200 : var(--md-accent-contrast-A200),
    A400 : var(--md-accent-contrast-A400),
    A700 : var(--md-accent-contrast-A700),
  )
);

$md-warning: (
  50 : var(--md-warning-50),
  100 : var(--md-warning-100),
  200 : var(--md-warning-200),
  300 : var(--md-warning-300),
  400 : var(--md-warning-400),
  500 : var(--md-warning-500),
  600 : var(--md-warning-600),
  700 : var(--md-warning-700),
  800 : var(--md-warning-800),
  900 : var(--md-warning-900),
  A100 : var(--md-warning-A100),
  A200 : var(--md-warning-A200),
  A400 : var(--md-warning-A400),
  A700 : var(--md-warning-A700),
  contrast: (50 : var(--md-warning-contrast-50),
    100 : var(--md-warning-contrast-100),
    200 : var(--md-warning-contrast-200),
    300 : var(--md-warning-contrast-300),
    400 : var(--md-warning-contrast-400),
    500 : var(--md-warning-contrast-500),
    600 : var(--md-warning-contrast-600),
    700 : var(--md-warning-contrast-700),
    800 : var(--md-warning-contrast-800),
    900 : var(--md-warning-contrast-900),
    A100 : var(--md-warning-contrast-A100),
    A200 : var(--md-warning-contrast-A200),
    A400 : var(--md-warning-contrast-A400),
    A700 : var(--md-warning-contrast-A700),
  )
);

$light-theme: mat.define-light-theme((color: (primary: mat.define-palette($md-primary, 500),
        accent: mat.define-palette($md-accent, 500),
        warn: mat.define-palette($md-warning, 500),
      ),
      typography: mat.define-typography-config($font-family: 'Open Sans',
      ),
      desity: 0,
    ));

@include mat.all-component-themes($light-theme);
```

Donde,
```
/* Importación de Angular Material */
@use '@angular/material' as mat;
```
Permite usar las funciones del módulo de Angular Material y mixins en el archivo de estilos.

```
/* Inclusión del Núcleo de Angular Material */
@include mat.core();
```
Este mixin incluye los estilos básicos necesarios para Angular Material. Debe incluirse al menos una vez en su aplicación para que los componentes de Angular Material se rendericen correctamente.

```
/* Definición de Paletas de Colores */

/* Paleta primaria */
$md-primary: (...}

/* Paleta acento*/
$md-accent: (...}

/* Paleta Advertencia */
$md-warning: (...}
```
Se definen las paletas de colores _primary_, _warning_ y _accent_, para cada tonalidad del color, desde 50 hasta A700 basado en los estilos proporcionados en [assets](https://github.com/udistrital/assets) . Las variantes de contraste (contrast) también se definen para asegurar que el texto sobre el color primario sea legible.

```
/* Definición del tema claro */
$light-theme: mat.define-light-theme(
...
);
```

```
/* Asignación colores a Angular Material */
@include mat.all-component-themes($light-theme);
```
Finalmente, se aplica el tema definido a todos los componentes de Angular Material. Este mixin asegura que todos los componentes utilicen los colores, tipografía y densidad definidos en _light-theme_.

### Material adicional:
- lineamientos [Estilos de Angular Material](https://github.com/udistrital/lineamientos_oas/blob/master/single_spa/core.md#estilos-de-angular-material)
- [Theming Angular Material](https://material.angular.io/guide/theming)

**Comment by CristianCGutierrezG** [comment]
Se ha agregado el script que maneja los estilos de Angular Material y la paleta de colores:
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/3e75fc35-397f-425b-96ea-98e08e6f2066)
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/9746ed77-c0cf-4596-a919-ee2d0165a3f7)

Esto ha provocado un cambio en el comportamiento de los formularios, los cuales ahora funcionan correctamente y se visualizan adecuadamente:
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/e30a2776-72c0-4575-ad75-440af2c62143)

Además, durante el proceso de maquetado de la tabla para mostrar la información de los usuarios, surgieron algunas observaciones:

- Cambiar los estilos de los elementos mat-table es complicado debido a cómo la librería estructura dichos estilos, lo que dificulta especificar el tamaño de las filas.
- Según la documentación de [Angular Material](https://v16.material.angular.io/components/table/overview), actualmente no existe una forma de filtrar los elementos de la tabla.
- Hubo problemas para agregar otras filas (como las que se requieren para el filtrado) justo después del header de la tabla. Se plantea la opción de colocarlas como footer, una alternativa con la que cuenta la librería.

**Comment by CristianCGutierrezG** [comment]
Se ha agregado los elementos de filtrado en la parte inferior de la tabla como footer, siendo la opción viable por el momento
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/3125bdb2-1105-4f1f-a337-b0f8af23d1d8)

Además, se ha implementado la funcionalidad en los selectores de filtrado de Roles y Estado para ver su funcionamiento.
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/b5c3bd86-0491-4470-a744-9b9c0c8724b5)

**Comment by edwargl7** [comment]
Se realiza la revisión del código, luego trabajaremos con peer code review entre integrantes del equipo.
- :wrench: Tratar de no definir estilos en el HTML, agregarlos al estilo del componentes como los demás estilos creados.
`mat-card [style.width.%]="100"`
Se resuelve el PR. Buen trabajo.
