### ISSUE TITLE
Pruebas y ajustes de estilos microcliente de gestión de usuarios y roles de compras y servicios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#56]
Se requiere realizar la revisión y ajustes de los estilos requeridos en el microcliente de gestión de usuarios y roles de las Issue #54 y #55.

**Sub Tareas**

- [x] Revisión de los estilos definidos y aplicación en cada módulo (registro y consulta).
- [x] Ajustes de estilos requeridos de cada submódulo.

**Criterios de aceptación**

- [x] #64

**Requerimientos**

- [x] Apoyo revisión con otros equipos.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance revisión de estilos

De acuerdo a las indicaciones dadas para la implementación de los estilos en el microcliente, que consiste en la creación de un script en la ruta de los assets y referenciados en el script angular.json; se logra corregir el formato de los campos en los formularios

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/26927ef8-d2be-4d58-b63a-ae5d5a91f0bd)

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/73c08910-04bc-489e-9eb4-9ab804d8f8d0)

Algunos estilos no se pueden modificar directamente ya que no se aplican los ajustes al elemento, por ahora se encuentra una solución que permite establecer es estilo requerido usando la declaración ***!important*** que da prioridad sobre otras reglas de estilo:

![image](https://github.com/udistrital/sisifo_documentacion/assets/42241322/b2c37c13-caad-4559-b60d-cb4fb4f9cd78)

**Comment by edwargl7** [comment]
Buen trabajo, se trabajaran los estilos que sean requeridos en cada desarrollo nuevo de nuevas interfaces según sea requerido. Por el momento lo abordado cumple con la aplicación de estilos inicialmente en el microcliente según lo revisado con otros equipos y lo documentado en la Issue #54 -
