### ISSUE TITLE
Modelo de datos módulo de Auditoría - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#58]
Se requiere realizar el modelo de datos de las dos primeras fases de la auditoría basado en los [mockups](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Eb2K_WA3cdVNuebskYqgMZMBJ7fOwSzRZheVK47zcszfeQ?e=LbfxyO) diseñados por el analista en los que se abordan los formularios utilizados para la fase de formulación del plan anual de auditorias y el programa de trabajo. El diseño del modelo de base de datos debe ser un modelo no relacional que permita soportar los cambios que se quieren abordar con los formularios dinámicos.

Revisar el mockup completo de Plan Anual de Auditoría (PAA) en el Mockup.
![image](https://github.com/user-attachments/assets/57c4ea68-f83b-4cc7-beb1-aa0a64538761)

Revisar el mockup completo de Programa de Trabajo (PT) en el Mockup.
![image](https://github.com/user-attachments/assets/63292919-ec6d-40f0-bfb5-10266c7b9b98)

**Material de apoyo**
- Modelo de datos no relacional trabajado para formularios dinámicos Issue #82.

**Sub Tareas**

- [ ] Diseño del modelo de datos del plan anual de auditoría.
- [ ] Diseño del modelo de datos del programa de trabajo manteniendo la relación de las actividades proyectadas en el plan anual de auditoría.

**Criterios de aceptación**

- [ ] Diseño del modelo de datos siguiendo los lineamientos del modelo de datos relacional que apliquen.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
1. Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Modelo de datos base del módulo de Auditiría
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
modelo de datos plan anual de auditoria

![Image](https://github.com/user-attachments/assets/23e7b5ed-885d-4d54-87af-fe93dae52b9a)

se carga documento .draw a carpeta del proyecto
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Edg3N7cgD8RJq1geYCK2NQkBk-Xzt0mmpQcauaFo3-BCyQ?e=Ft8fSR

**Comment by edwargl7** [comment]
Se cambia el alcance de la tarea dado que no se puede abordar todavía el programa de trabajo.

**Comment by edwargl7** [comment]
Buen diseño del modelo de datos, cuenta con un buen manejo de etiquetas aclaratorias.

**Observaciones** :pencil2: 
- Aunque es un modelo de datos no relacional se recomienda para los campos que almacenan la relación con otra tabla o sistema el uso de **_id** al final del nombre del campo.
![image](https://github.com/user-attachments/assets/11f57035-6f84-4ba2-9826-a97f5cef985b)
Aplicarlos en los sigueintes campos:
>- estado -> estado_id
>- tipo_evaluacion -> tipo_evaluacion_id
- Agregar en la colección de información los campos de id del usuario que realiza la aprobación como jefe y secretario técnico.
- En la colección de información manejar la vigencia como relación paramétrico con parametros_crud.
- En la colección de actividad manejar fecha_inicio y fecha_fin con relación paramétrica y estos valores ser almacenados en parametros_crud.

Estos ajustes se abordaran en una nueva Issue.
