### ISSUE TITLE
Modelo de datos módulo de Auditoría - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#59]
Se requiere actualizar el modelo de datos que contenga lo requerido para la programación y planeación de la auditoría basado en los mockups de auditoría interna y tomando como base el modelo ajustado en la Issue #96.

Etapa de programación
![image](https://github.com/user-attachments/assets/9af42b22-3c9c-45ad-81e5-151a7add647d)
![image](https://github.com/user-attachments/assets/278b7eaf-9839-4527-b434-0f2718e6b03f)
![image](https://github.com/user-attachments/assets/fe4b854d-b4c5-49dc-be0d-8e50554d22d2)
![image](https://github.com/user-attachments/assets/81e80104-154f-4683-b646-82e86d96535f)

Etapa de planeación (cada auditoría del registro anterior se complementa en esta etapa)
![image](https://github.com/user-attachments/assets/f29bbb23-c0c3-45b8-af20-f221db5a4cc4)
![image](https://github.com/user-attachments/assets/7c6370c6-421a-4e21-babe-c3cf8d65dc81)
![image](https://github.com/user-attachments/assets/fc918e18-3723-4c19-8ba9-7fdc608bc756)
![image](https://github.com/user-attachments/assets/f2332e91-51a2-45c0-9997-bc58e3ebaa13)
![image](https://github.com/user-attachments/assets/9cf0995c-a3cc-4319-bda5-3404bf072725)

**Sub Tareas**

- [x] Actualización modelo de datos que tenga la colección plan_auditoria (actualmente información), auditorias (actividad) dado que más adelante cada auditoria tiene actividad y evaluar la agrupación de los campos complementarios de cada auditoria.

**Criterios de aceptación**

- [ ] Documentación de nueva versión creada con los respectivos avances.

**Requerimientos**

No aplica

**Material de Apoyo**
- Modelo no relacional base
![_plan_anual_de_auditoría_V1-version2 drawio](https://github.com/user-attachments/assets/6e5c69d1-18a6-499e-8259-35bd3000e235)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se actializa modelo de datos a la version 3 con base en mockups proporcionados

![Image](https://github.com/user-attachments/assets/cf49a338-dfc0-4a13-98e8-80e8e78714cf)


se carga archivo .draw actualizado a la version 3 en carpeta del proyecto
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmWrZiN_snFMt_5fvCfhUJUB7uOOpah2jX5Ez0ZiNObR2A?e=zgN4zr

**Comment by edwargl7** [comment]
Buen avance, se requiere realizar ajustes en el tipo de dato de los campos fecha_creacion y fecha_modificacion a timestamp.
Y remover las restricciones nn dado que necesitamos permitir que se pueda modificar el formulario.

**Comment by edwargl7** [comment]
Revisar la separación de una auditoría cuando se hace periodicamente para definir si es una relación uno a uno con la información embebida. Revisar con @cjgonzalezp en que momento esa auditoría periódica se divide para tener presente a nivel del modelo de datos si se puede usar un campo de agrupación.

**Comment by jucastro94** [comment]
se realizan ajustes al modelo de datos version 3
![Image](https://github.com/user-attachments/assets/dfc904fb-989a-4209-98d7-f7a9af99f7a4)

- cambio de campos de not null a null
- cambio de tipo de datos de los campos fecha_creacion y fecha_modificacion a timestamp
- cambio de tipo de dato, cronograma_actividad a array
- creacion de coleccion documento
- translado de campos de coleccion embebida a coleccion auditoria
- eliminacion de coleccion embebida en auditoria

se carga version al carpeta del proyecto

**Comment by edwargl7** [comment]
Se finaliza la revisión y se plantea manejo como se diseño, puede plantearsen ajustes mientras se avanza en las integraciones que vienen trabajando entre MID y plantillas CRUD.
