### ISSUE TITLE
Modelo de datos de formularios dinámicos - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#60]
Se requiere realizar el modelo de datos para los formularios dinámicos realizada en las investigaciones y el documento técnico que recopila parte de las investigaciones en la Issue #57. Adicional a lo revisado en las investigaciones y pruebas, se debe contemplar que los formularios dinámicos tengan la posibilidad de cada elemento de HTML identificado anteriormente sea posible agruparlo por secciones basado en la necesidad del [usuario de Sísifo v2](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ES0X52LCzu5FuCtkMb35UTQBFZiAlaZvtVDH4CUEFJzr-g?e=Y3q3bh) y la integración de este sistema de formularios dinámicos con otros sistemas.

**Material de apoyo**
Imágenes del primer formulario dinámico que requiere el usuario para el módulo de auditoría. 
Primera sección
![Image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/4bea51e6-a5b4-4713-a6c3-11bf4d57ae27)

Segunda sección
![Image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/12ad5589-f56e-41cd-919c-95141125a1b9)

**Especificaciones técnicas**

1. El modelo de datos debe almacenar el identificador del sistema similar al modelo de datos de gestión de usuarios #45 .
2. Debe almacenar información del módulo al que pertenece dentro del sistema.
3. Debe contar con un control de versiones de plantillas.
4. Debe contemplar la separación por secciones.
5. Información de quien realizó el registro (creación, modificación).
6. Aunque el modelo de datos propuesto es no relacional, tener como referente el lineamiento de [Modelo de datos](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)
7. Tener presente el diagrama propuesto de arquitectura para [formularios dinámicos](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYtS9t_pQwdFpuJiPqmBawUBtxJTwhgG5jMFAM9ypKaCuA?e=6gbWAW).

**Sub Tareas**

- [x] Revisión requisitos para agregar secciones al formulario.
- [x] Revisión arquitectura módulo de formularios dinámicos.
- [x] Diseño modelo de datos.

**Criterios de aceptación**

- [x] Modelo de datos siguiendo los requerimientos de modelo de datos para el nombre de las colecciones, identificadores con otras tablas/colecciones.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Modelo de datos de gestión de usuarios y roles.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se ha llevado a cabo la revisión de las especificaciones y archivos relacionados. También  se inicio un estudio sobre cómo realizar el modelado para una base de datos no relacional.

En un primer planteamiento, se proponen las siguientes colecciones:

sistema_informacion
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/ecbff82d-9c39-41b9-8d97-1928d9edb315)

modulo 
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/c7dfcbd8-505f-4124-b3a1-50b936ed52c2)

seccion
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/7453cc9e-1a98-495a-bc35-25f927009c98)

plantilla_formulario
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/9eacd72e-9d0c-47f4-89db-3ccc459c6c15)

parametro
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/a905a944-5c2a-432d-a75e-7a9b13a9cfba)


usuario
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/e0fea1c6-a9b9-4d17-aed7-54dc74cc00a3)

En este contexto, se propone inicialmente la creación de las colecciones sistema_informacion y usuario para facilitar la comprensión de sus relaciones en el diagrama. Sin embargo, estas entidades podrían ser proporcionadas por otros servicios externos.

**Comment by CristianCGutierrezG** [comment]
Se realizo un estudio sobre las bases de datos no relacionales  y se llego a ciertas aclaraciones para poder representar el modelo de datos de forma optima

# Modelamiento de bases de datos NoSQL
Para realizar el modelamiento de datos se manejan 2 formas de realizarlo:

**Embebida:** Dentro de una colección se registra un documento que tenga otras subcoleciones.

**Referenciada:** Se realiza relación con varias colecciones agregando un identificador único.

Existen 3 preguntas útiles para determinar que tipo de forma es necesaria

- ¿Qué tan frecuente es consultada la información?
- ¿Qué tan frecuente se actualiza la información?
- ¿La información se consulta en conjunto o por partes? 

## Manejo de las relaciones

Se puede utilizar cualquier forma dependiendo de la relación teniendo en cuenta algunas reglas especificas para cada una:

### Relación 1 a 1

Embebida:
 Existe una dependencia interna de ciertos atributos relacionados 

Casos de uso:
- En el 90% de los casos, cuando hay una relacion 1:1, esta suele ser embebida.
- Cuando la informacion se consulta en conjunto
- Los sub-documentos sean una dependencia directa, la dependencia no tienene sentido de forma aislada

Ejemplo de modelado:
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/c4f08e6f-8f3c-4154-8428-cd6d60d7e9db)

Referenciada:

- Cuando el documento ya es muy grande, cerca del límite de 16 mb, mejor se saca información para mejorar el rendimiento.
- Se puede usar el ObjectId, para referenciar el total de datos y agregar los 2 o 3 campos de los más comunes que se usan juntas para evitar la consulta a la 2da colección.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/1d537da7-b014-47fd-bbcf-eb754836e1b2)


### Relación 1 a muchos

Embebida:

Casos de uso:

- Cuando la informacion es consultada en conjunto
- El arreglo de subdocumentos no peligre el limite de 16MB
- Cuando los sub-documentos son una dependencia
- Cuando los sub-docs son 1:few (1 a pocos)

Referenciada:

Cunado un documento puede estar asociado a otros documentos de otra colección.

Casos de uso:
- Cuando la relación puede incrementar considerablemente
- Cuando la entidad se actualiza de forma constante
- Cuando la entidad es usada por muchos documentos

Relacion muchos a muchos
Se trabajan de manera referenciada
La referencia se almacena en forma de array

**Comment by edwargl7** [comment]
Se realiza la revisión del avance, cuenta con información útil para complementar o crear una parte de los lineamientos para modelos no relacionales.

Adicional, vamos a realizar una reunión con el equipo de SGA para alinearnos y revisar posibles distribuciones de carga y complementar lo propuesto hasta el momento.

**Comment by CristianCGutierrezG** [comment]
Se realiza la primera versión del diagrama de datos, tomando como referencia la investigación realizada
![_Modelo de datos de formularios dinámicos drawio](https://github.com/udistrital/sisifo_documentacion/assets/48999834/65e7abcc-2043-4f38-96c2-e3190c6c0d80)

También se tuvo una reunión con el equipo de **Planeación** en la que se habló del desarrollo realizado y se plantearon algunas necesidades de cada sistema:
- Se informa de un desarrollo realizado en SISGPLAN que utiliza los formularios dinámicos, realizando el almacenamiento y la estructuración de los mismos en forma de árbol
- Se mostró la estructura del modelo no relacional implementado en planes_crud.
- Se comenta la problemática de la recopilación de datos de los formularios y como esta debe ser compartida en distintos sistemas

**Comment by edwargl7** [comment]
Se va a realizar la revisión del modelo propuesto actualmente con el modelo existente en planes_crud que se encuentra en el repositorio https://github.com/udistrital/planes_crud.
Enlaces al [modelo](https://github.com/udistrital/planes_crud/blob/master/database/planes.png).

**Comment by CristianCGutierrezG** [comment]
# Revisión y Comparación de Modelos en planes_crud

Se realiza la revisión y comparación del modelo propuesto con el modelo existente en `planes_crud`.

En **Sisgplan** se crean unos planes que se traducen en formularios editables por el cliente, los cuales se conectan en forma de árbol con las conexiones entre subgrupos que contienen la información de los parámetros.

## Estructura del Diagrama de planes_crud

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/68d42a1d-f978-4d1a-b5c9-c60359f2b412)


Existen cuatro tablas importantes para la creación de un plan en el diagrama de `planes_crud`:

1. **plan**: Tabla principal que guarda la estructura del formulario.
2. **tipo-plan**: Tipos de planes.
3. **subgrupo**: Niveles del árbol, tipos de parámetros, crea las etiquetas. Contiene información del padre (plan al que pertenece) y de los hijos.
4. **subgrupo-detalle**: Guarda la información del parámetro (tipo, obligatorio, etc.). También guarda la información del manejo del formulario como un JSON.

### Atributos Utilizados para la Generación del Árbol

#### plan
- **padre_plan_id** (string): ID del documento plan padre de otro.
- **arbol_padre_id** (string): ID del documento plan que va por encima en la jerarquía del árbol (raíz).

#### subgrupo
- **padre** (string): Información del padre de un subgrupo.
- **hijos** (array[string]): Información de los diferentes hijos de un subgrupo.

#### subgrupo-detalle
- **subgrupo_id** (string): ID del subgrupo al que pertenece la información adicional.
- **dato** (json): Información de los parámetros para la construcción de un plan.

### Datos de un Parámetro en SISGPLAN

- **Nombre**: Text
- **Descripción/objetivo**: TextArea
- **Estado**: Boolean
- **Parámetros**: Boolean (Si requiere de algún dato o solo es una etiqueta; una etiqueta determina una sección de un formulario y agrupa diferentes entradas de datos).
- **Campo en tabla resumen**: Boolean (Tabla donde aparece la información del formulario de manera resumida).
- **Tipo de dato**: string[] (Numérico, texto, select).
  - **if(select)** 
    - **opciones**: TextArea (Opciones separadas por coma: opción1, opción2).
- **Obligatorio**: Boolean

### Notas
- El formulario se crea cuando el cliente pide observar un plan de acción.
- Se crea la interfaz con acordeones.
- La información de los datos ingresados en el formulario se guarda en la misma base de datos en la que se crea el plan.
- No existe referencia entre `plan` y `subgrupo`; su conexión se da por medio del atributo padre.
- Al guardar los parámetros como JSON se maneja la lógica de la información del formulario solo desde el cliente.
- Parece que el servicio de `PLANES_MID` también es requerido para la creación de un árbol.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/9317411e-2477-49ec-ae06-0d13b4d7642c)


### Diferencias

| Aspecto                                     | SISGPLAN                                  | Modelo Actual                        |
|---------------------------------------------|-------------------------------------------|--------------------------------------|
| Control de versionamiento                   | No se lleva un control                    | Se plantea el manejo de versiones   |
| Almacenamiento de la información            | Se guarda todo en un único JSON           | Información de cada parámetro de un formulario de manera especifica|
| Generación de validadores específicos       | No se cuenta con validadores específicos  | Se especifican validadores de manera directa |
| Uso principal                               | Solo para la creación de planes           | Más general, almacenamiento de información del sistema y módulos  que lo requieran|
| Jerarquía de árbol                             | Determina una jerarquía de padre e hijos versátil       | No cuenta con jerarquía |

**Comment by edwargl7** [comment]
De la revisión realizada por @CristianCGutierrezG se obtiene un buen detalle del funcionamiento actual, y es necesario tener acceso a la base de datos de ese modelo actual para poder analizar mejor los registros y escenarios empleados actualmente para poder ir construyendo con más claridad del modelo de datos unificando las ventajas de los dos modelos actuales (planeación y propuesto para Sísifo).

**Comment by edwargl7** [comment]
Se finaliza la revisión de la información recopilada. Buen trabajo. Se continuará la revisión del funcionamiento actual y se realizará la generación de la propuesta tomando parte del modelo de sisgplan y el propuesto para Sísifo.
