### ISSUE TITLE
Generar el diseño del módulo de gestión de auditoria

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#62]
Se requiere generar el diseño del módulo de gestión de auditoría, acorde a lo indicado en la reunión cliente. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [ ] Realizar ajustes según comentarios del equipo SoS.
- [ ] Preparar el Mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [ ] Mockup aprobado por elequipo SoS.
- [ ] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el diseño del mockup del módulo de plan anual de auditoría y seguimiento. 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/faa1ae93-4fee-46cf-a0fa-e4f7510fc113)


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,
@jcmurilloa @edwargl7 

Se realiza un primer ajuste del diseño inicial.

![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/83798692-3da8-42c1-a523-af1895a5eb5e)

**Enlace del mockup cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=kOuPE9


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con el líder técnico @edwargl7 para revisar y realizar ajustes al mockup del módulo de gestión de auditoria/plan anual de auditoría.

**Modulo Plan Anual de Auditoría**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/eb474d66-fe22-4fd4-a759-074831d91556)

**Enlace del mockup cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=Isf1vs

**Grabación Reunión**
https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/EV0RRt5BuThPrHRemZWvUrwBmt9RnNKxM953hy-e0Ir3eg?e=pbhZmw&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D


Saludos.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, corregir según observaciones por parte del equipo SoS pendiente la vista de flujo de aprobación que se asignará en una nueva issue!
