### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de requerimientos y/o refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#63]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta al cliente y se agenda reunión para el día 08 de julio de 2024 hora: 2:00 pm


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con el cliente el día 08 de julio de 2024 hora: 2:00 pm a 3:40 pm. Pendiente terminar de levantar el acta de reunión para aprobación de líder de proyecto y recolección de firmas de los participantes en la misma.


Saludos.

**Comment by jcmurilloa** [comment]
Espero nos haya ido muy bien @cjgonzalezp, nos cuentas en la siguiente sesión SoS. Pendiente acta.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión No 066/2024 SISIFO - Levantamiento de Requerimientos. Pendiente recolección de firmas por parte de los participantes presentes.

**Enlace del documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et-a7_BrY3pEmFZ6uZF0QY0B9nxrTf9efMi3aD9Bn96RlQ?e=RPjWQy


Cordial saludo.

**Comment by cjgonzalezp** [comment]
Buen día,

Se finaliza la issue con la recolección de las firmas de los participantes.

**Enlace del documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et-a7_BrY3pEmFZ6uZF0QY0B9nxrTf9efMi3aD9Bn96RlQ?e=DgETOz


Cordial saludo.

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp. Se procede a cerrar la issue.
