### ISSUE TITLE
Validaciones y revisión pruebas unitarias microcliente de gestión de usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#66]
Se requiere agregar las siguientes validaciones al microservicio CRUD, que permitan garantizar integridad en los datos que sean enviados.
- Que la fecha fin del periodo en el que un usuario fue asignado un rol no sea inferior a la fecha inicio.
- Que un usuario no pueda tener activos al tiempo dos registros con el mismo rol (inactivos si se debe permitir).
- No permitir duplicar los registros de usuarios.

Además, se debe realizar la revisión de pruebas unitarias con Jazmin y Karma e identificar demás validaciones que posiblemente sean requeridas para un correcto funcionamiento e integridad de los datos.

**Sub Tareas**

- [x] Agregar validaciones al microcliente.
- [x] Revisión de pruebas unitarias al microcliente.

**Criterios de aceptación**

- [x] Validaciones agregadas al microcliente.
- [x] Conceptualización de Pruebas unitarias al microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Pendiente documentación de la Issue.

**Comment by alexhrr** [comment]
## Documentación Jasmine y Karma

Jasmine y Karma vienen integrados por defecto en los proyectos de Angular para la realización de pruebas unitarias.

### Ejecución Jasmine y Karma

Verificar en el archivo angular.json que tenga las siguientes configuraciones:

![Captura de pantalla 2024-07-02 a la(s) 5 13 36 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/b72b7e63-f4b9-49db-8e63-8310a08f85ec)

Se debe tener el archivo de pruebas con la extensión .spec.ts 

``` bash
ng test
```

Se debe tener un archivo llamado karma.conf.js, con la siguiente estructura 

![Captura de pantalla 2024-07-02 a la(s) 5 52 50 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/a23061ed-aafb-4f95-83ca-aebc260be724)

Los resultados de las pruebas se mostrarán en la consola, las pruebas se definen en los archivos .spec.ts.

**Comment by edwargl7** [comment]
Se continuará en las pruebas una vez terminada la integración requerida en los microclientes.
