### ISSUE TITLE
Diseño de vistas de flujo de aprobación del sb módulo PAAS

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#67]
Se requiere generar el diseño de vistas de flujo de aprobación del sb módulo PAAS, acorde a lo indicado en la revisión del equipo SoS. 

**Sub Tareas**

- [x] Diseñar mockup con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Preparar el Mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por elequipo SoS.
- [x] Issue documentada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se avanza en el mockup de las diferentes vistas de aprobadores del plan anual de auditoria PAA.

**Mockup Módulo Plan Anual Auditoria - Flujo de Aprobación**



Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, lo revisaremos a detalle en el planning del 28/06.

**Comment by jcmurilloa** [comment]
Excelente diseño @cjgonzalezp, por favor tener en cuenta las recomendaciones de @edwargl7 respecto a los mensajes de advertencia al elmininar información del sistema.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realizan ajustes de acuerdo a sugerencias de @edwargl7 y adicional las sugerencias expuestas por el cliente en la reunión del 8 de julio de 2024 acta No 066/2024. Se recibe aprobación por parte el cliente

**Mockup Módulo Plan Anual Auditoria - Flujo de Aprobación**
https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ES0X52LCzu5FuCtkMb35UTQBWbee73fXVhC-CCnhh05sqw?e=NAddAE

Saludos.

**Comment by jcmurilloa** [comment]
Pendiente vista de programa de trabajo con la asignación inicial de actividades del PAA por parte del auditor experto.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contempla la asignación inicial de actividades del PAA en el módulo de programa de trabajo. Adjunto nuevamente el mockup de PAA final y aprobado por el cliente para su desarrollo.

**Mockup Módulo Plan Anual Auditoria - Flujo de Aprobación**
https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/ES0X52LCzu5FuCtkMb35UTQBWbee73fXVhC-CCnhh05sqw?e=TgHgue


Saludos.
