### ISSUE TITLE
Crear y refinar la parametrización de datos para el sistema SISIFO V2

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#68]
Se requiere realizar la creación y refinación la parametrización de datos para el sistema cumplidos proveedores

**Sub Tareas**

- [x] Construir el documento de parametrización de datos.
- [x] Refinar el documento con el equipo el documento.

**Criterios de aceptación**

- [x] Documento de parametrizaciín de datos definido

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by jcmurilloa** [comment]
@cjgonzalezp Recuerda que esta issue es del sprint anterior, ten en cuenta su desarrollo.

**Comment by cjgonzalezp** [comment]
Buen día Julián,

Agradezco trasladar esta issue para el sprint siguiente #12. en este sprint no se han definido aún datos paramétricos.

Gracias

Saludos.

**Comment by jcmurilloa** [comment]
Teniendo en cuenta tus comentarios, procedo a trasladar la issue al siguiente sprint.

**Comment by cjgonzalezp** [comment]
Buen día,

Se crea documento de datos paramétricos que se tendrán en cuenta en el desarrollo del sistema SISIFO V2. Cabe aclarar que el documento se ira alimentando hasta finalizar el levantamiento de requerimientos al 100%

**Enlace documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpotSdcwuCtGgGiZBiM6akYBX58kukRztJsDYBgf1uI45A?e=i3k8dD


Cordial saludo

**Comment by jcmurilloa** [comment]
Excelente trabajo @cjgonzalezp. Continuar la respectiva realimentación según los requermientos del cliente en los siguientes módulos.
