### ISSUE TITLE
Creación modelo de datos unificado de formularios dinámicos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#69]
Se requiere realizar el análisis de la base de datos de los formularios dinámicos actuales de SISGPLAN y continuar con la creación del modelo de datos para formularios dinámicos iniciada en la Issue #60.

**Sub Tareas**

- [x] Revisión registros base de datos de SISGPLAN tablas de formularios dinámicos.
- [x] Diseño de modelo de datos para formularios dinámicos.
- :timer_clock: :lock:  Reunión con el equipo de SGA para presentar el modelo de datos propuesto.

**Criterios de aceptación**

- [x] Diseño de modelo de datos para formularios dinámicos.
- :timer_clock: :lock:  Reunión con el equipo de SGA para presentar avances, alinear las necesidades y observar que el modelo propuesto aborde los requerimientos de Sísifo y SGA.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Modelo de datos de formulario dinámicos unificando en modelo de datos propuesto con el modelo de formularios de SISGPLAN.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Vista que podría contemplarse para las hojas finales del árbol.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/76bda47a-f5b4-4e32-996f-1859f00bc0f8)

**Comment by edwargl7** [comment]
Revisión estructura formularios de Google.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/f2db5829-27d5-4b53-9552-084bfd18f69c)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/dadbaa05-bfb2-4144-8864-8b293609c1e4)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/83710c8c-dc46-486d-a5e2-46fa21f8c21e)

Resultado de los registros del formulario, se observa que las secciones no son tenidas en cuenta.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/77d05fe5-9a49-47db-861a-ff1a7a5e2724)

**Comment by CristianCGutierrezG** [comment]
# Revisión y organización de la base de datos SISGPLAN

Se realizó la revisión de la base de datos de SISGPLAN, junto con @edwargl7 , analizando las tablas y registros relacionados con los Planes, para obtener un mejor entendimiento de su funcionamiento y aplicar los datos más relevantes en el modelo de formularios dinámicos actual en Sísifo.

## Consultas revisadas

### Consultas para determinar el manejo de la jerarquía del árbol

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/4e5802f2-a68c-47b6-8452-574df9804785)

- El atributo  `pagre_plan_id` determina la plantilla principal con la que se crea un formulario, es como el manejo de versiones, si un  `plan` la tiene implica que deriva de otro ya existente

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/6eb329a1-3049-44cc-b5db-56560631d1e8)

- La conexión entre `plan` y `subgrupo` se establece mediante el atributo `padre`, en el cual el plan es el padre de un subgrupo.
- La estructura en forma de árbol se genera con la información de los atributos `padre` e `hijo` en cada `subgrupo`.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/149e4f45-3a56-4adb-bd9f-be370ae4a062)

- `subgrupo-detalle` es la última parte (hoja) en la jerarquía del árbol cuando existe un parámetro para la creación del formulario. Si no existe un parámetro, la última hoja es un `subgrupo`.

![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/3667686e-6a47-4cbf-8171-24311e2cb244)

- En `subgrupo-detalle`, el atributo `dato` almacena un JSON con solo un tipo de parámetro por `subgrupo`.

# Nuevo diagrama

![_Modelo de datos de formularios dinámicos-Página-3 drawio](https://github.com/udistrital/sisifo_documentacion/assets/48999834/674bab2b-6aa8-4cc3-941d-f95ce56d3b2f)

- Las secciones son lo que en SGA se conoce como `subgrupo`, diferentes segmentos de un formulario con información agrupada.
- Se plantea coleccion `elemento_html` para dar más opciones a la hora de escoger elementos del formulario y que estos almacenen información de los atributos más relevantes (validadores, opciones, etc.), con la opción de poner más parámetros, como un objeto, en caso de ser requeridos.
- Las relaciones son referenciadas ya que son elementos que serán constantemente editados. Se plantea así para evitar tener que alterar los datos en múltiples colecciones.

**Comment by CristianCGutierrezG** [comment]
Se realiza una nueva revisión al cliente `planeacion_cliente` y a la API de `planeacion_mid` para entender el flujo en la construcción del árbol, pero no se encontró algo más relevante para modificar el modelo de datos.

### Modificaciones

![_Modelo de datos - formularios dinámicos-version 2 drawio](https://github.com/udistrital/sisifo_documentacion/assets/48999834/517c1f04-6cf8-42cb-82c9-26a79655780f)

Se remueve el atributo `hijos_id` ya que se evidencia en el ejercicio de las consultas que se puede acceder a cada colección por el atributo `padre_id`, evitando tener que cambiar datos con cada actualización de los hijos.

### Link de la ubicación del diagrama:
[Modelo de datos - formularios dinámicos](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EXeB_8G9YdJBoFeWbyggx_8Bg0T_xNtWO7b3SO_FaxXeRA?e=c9al6n)

### Investigación de Atributos Comunes en Formularios HTML
Para definir los atributos a almacenar en el componente `elementos_html`, se realiza una investigación para determinar que atributos son los más comunes en el uso de formularios.

### Datos más relevantes de un formulario

#### Atributos compartidos por los elementos HTML especificados en el diagrama:

- **nombre**: El nombre del campo, utilizado para identificar el dato cuando se envía el formulario.
- **placeholder**: Texto que aparece dentro del campo cuando está vacío (aplicable a `<input>` y `<textarea>`).
- **label**: Etiqueta que describe un control de formulario.
- **tipo**: Especifica el tipo de elemento (`<input>` , `<select>` , `<textarea>` , etc.).
- **tipo_dato**: Especifica el tipo de control de entrada (e.g., text, password, email, number, etc.).
- **requerido**: Hace que el campo sea obligatorio.
- **desabilitado**: Desactiva el campo, haciendo que no pueda ser editado ni enviado.
- **soloLectura**: Solo permite la lectura del campo sin posibilidad de modificarlo (aplicable a `<input>` y `<textarea>`).
- **validador[]**: Especifica los validadores únicos para cada elemento.

#### Atributos específicos

##### `<input>`:
- **value**: Valor predefinido del campo.
- **min** y **max**: Valores mínimo y máximo permitidos (aplicable a `number`, `date`, etc.).
- **step**: Incremento permitido para los valores (aplicable a `number`).
- **pattern**: Expresión regular para validar la entrada.
- **size**: Ancho del campo de entrada en caracteres.

##### `<select>`:
- **multiple**: Permite seleccionar múltiples opciones.
- **size**: Número de opciones visibles.

##### `<textarea>`:
- **rows**: Número de filas visibles.
- **cols**: Número de columnas visibles.
- **wrap**: Especifica cómo debe comportarse el texto cuando alcanza el borde del área de texto (e.g., soft, hard).

### Otros Elementos Comunes en Formularios

- **`<button>`**: Representa un botón que se puede hacer clic.
- **`<fieldset>`**: Agrupa elementos relacionados dentro de un formulario.
- **`<legend>`**: Proporciona un título para un `<fieldset>`.
- **`<datalist>`**: Proporciona una lista de opciones predefinidas para un `<input>`.
- **`<output>`**: Representa el resultado de un cálculo o acción.

**Comment by edwargl7** [comment]
Cuenta con buena documentación la Issue que puede complementar el documento técnico borrador que se viene trabajando para los formularios dinámicos. Adicional se puede revisar [componentes UI de Angular](https://material.angular.io/components/categories), por ejemplo, Checkbox, Slide toggle.

**Comment by edwargl7** [comment]
**Observaciones modelo de datos**
Revisando el modelo de datos propuesto se sugieren los siguientes cambios:
- En la colección **modulo** el campo _sistema_id_ como viene de un modelo de datos relacional se debe cambiar a tipo de dato numérico.
- En la colección **formulario**:
> - No requiere el campo _modificado_por_id_ dado que cada modificación crea una nueva versión.
> - El campo _creado_por_id_ se debe confirmar si es el id de la tabla de terceros o si es el número de identificación (se consulta a DBAs).
- En la colección **elemento_html** corregir el nombre del campo deshabilitado.
- Agregar una colección que permita gestionar la relación de muchos a muchos entre la colección _seccion_ y _elemento_html_ para que permita almacenar validadores propios según lo requiera el usuario al momento de construir el formulario usando los elementos HTML existentes.
