### ISSUE TITLE
División del Cliente Sísifo v1 en Microfrontends - Microcliente Configuración PT1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#7]
Se requiere realizar la planeación y estructuración para dividir el sistema Sísifo v1 en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

- [x] Análisis del sistema Sísifo v1 microcliente de Configuración (Calificación, Roles, Usuarios, Origen Plan Mejoramiento, Proceso, Notificaciones)
- [x] Crear diagrama de componentes de la arquitectura para el Sísifo v2.
- [x] Listado de funcionalidades de cada microcliente basado en las funciones conocidas en el manual de usuario revisado en las tareas realizadas en el Sprint 0.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división clara el sistema en múltiples microclientes.
- [x] Listado de funcionalidades que componen cada microcliente.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/370713d0-1184-4b88-bab5-14503ad445cb)

**Comment by jucastro94** [comment]
se adjunta enlace del diagrama de componentes:
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EdKGQPv-w1ZKlZn0d_1v1jQBRUEzCEN4O5AZB3E9VCF2lw?e=B51vhF

**Comment by jucastro94** [comment]
se agregan funcionalidades en el diagrama de componentes  en el modulo de USUARIOS

- Activacion / Desactivacion de usuario 
- Información básica

 se pone en amarillo las funcionalidades de Crear usuario y Editar información por falta de claridad de donde se trarera la información y como se trabajara con ella.

se agrega modulo de core


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/618e6157-0cca-4633-bcf4-e75fdd639fb8)

**Comment by jucastro94** [comment]
lista de funcionalidades:

CALIFICACION:

- Crear calificación
- Listar
- Editar
- Visualizar información

ROLES:

- Editar permisos
- Listar usuarios por rol
- Visualizar información

USUARIOS:

- Crear usuario
- Editar informacion
- Cambiar contraseña
- Asignar rol
- Listar usuarios
- Activar/Desactivar usuario
- Visualizar información

ORIGEN DE PLAN DE MEJORAMIENTO:

- Crear origen
- Crear sub-origen
- Listar
- Editar

PROCESOS:

- Crear Proceso
- Editar 
- Listar procesos

NOTIFICACIONES:

- Editar notificaciones
- Listar
- Visualizar información

**Comment by edwargl7** [comment]
Excelente trabajo. Agregar listado de funcionalidad a la carpeta de documentación Sísifo v2 por favor.

**Comment by jucastro94** [comment]
se anexan funcionalidades a documento https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/doc2.aspx?sourcedoc=%7B2829650a-16e1-407a-b968-80bfe9a3d18c%7D&action=edit&activeCell=%27Hoja1%27!C46&wdinitialsession=728b87c1-4adc-8bc7-6b75-1226610a4b4e&wdrldsc=2&wdrldc=1&wdrldr=AccessTokenExpiredWarningOrgPolicyRestriction%2CRefr



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ebc95fba-756a-417c-8c36-4774c060a0a6)
