### ISSUE TITLE
Integración Terceros y microcliente de gestión de usuarios y roles - Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#70]
Se requiere realizar la integración de terceros con el microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).
Esta integración debe permitir consultar en terceros un usuario con el número de identificación o correo electrónico si existe se debe traer el nombre completo del tercero, si no existe debe mostrar un modal indicando que el usuario consultado no existe.

**Sub Tareas**

- [x] Integración terceros y microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).
- [x] Pruebas consultando un usuario registrado en terceros y mostrando el nombre completo.
- [x] Prueba consultando un usuario que no existe en terceros y mostrando el modal de error.

**Criterios de aceptación**

- [x] Integración microcliente y terceros.
- [x] Pruebas del correcto funcionamiento integración terceros.

**Requerimientos**

- [x] Consulta al arquitecto sobre posibilidad de existencia de usuario en WSO2 y no en tercero, y como gestionar dicho caso.
- [x] Endpoint de consulta de tercero.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
API de terceros - Endpoint de [consulta de tercero](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Terceros&version=v1&provider=admin&tenant=carbon.super#!/tercero/TerceroController_Get_All)

**Comment by alexhrr** [comment]
## Avance integración de terceros

Con la información suministrada del endpoint para la integración del servicio se procede con su implementación en el microcliente 

![Captura de pantalla 2024-07-02 a la(s) 11 35 44 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/7fd03f19-8b89-4042-842c-fbf852c1fdd4)

![Captura de pantalla 2024-07-02 a la(s) 11 33 31 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/ff9b8348-9a74-4dfe-a79e-a7409e8b3afe)

![Captura de pantalla 2024-07-02 a la(s) 11 32 59 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/3334c05d-539f-4270-b25e-3af80aa5d64d)

Se continua revisando la información que trae el servicio para poder ser mostrada posteriormente en la interfaz

**Comment by edwargl7** [comment]
Para el modal se puede usar [sweetalert2](https://sweetalert2.github.io/) y te puedes guiar del modal creado en ARGO en la [Issue 39](https://github.com/udistrital/argo_documentacion/issues/39), el componente desarrollado para ARGO lo puedes ver en este [componente](https://github.com/udistrital/gestion_contractual_compras_contrato_mf/blob/develop/src/app/modules/registro-contrato/guardar-info/guardar-info.component.ts).

**Comment by edwargl7** [comment]
Modal base, puede realizarse cambios en los mensajes posteriormente.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/f13c0808-c223-4b00-9262-410c917e59d3)

**Comment by alexhrr** [comment]
## Integración terceros

Se realiza la integración del servicio de terceros con el microcliente.
Se consulta el usuario y se muestra el nombre en la interfaz 

![Captura de pantalla 2024-07-03 a la(s) 8 54 41 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/96aea3a5-6098-4a76-83d6-acdbfa48fc5d)

Cuando no se encuentra el usuario se muestra el modal informando el resultado, se realizo usando sweetalert2.

![Captura de pantalla 2024-07-03 a la(s) 8 54 25 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d968677a-a039-4f7c-808b-6465411e7ce6)

**Comment by edwargl7** [comment]
Se realiza la revisión de los avances, muy buen trabajo, pendiente subir el código con el que se desarrollo los modales para una revisión del código, no sé requiere PR en esta Issue dado que se requieren seguir realizando cambios con respecto a las necesidades de datos adicionales frente a los endpoints existentes. Se realiza la revisión de los estilos y se sugiere revisar la convención en el nombre de clases en los estilos CSS [Convenciones de nomenclatura de CSS que te ahorrarán horas de depuración](https://www.freecodecamp.org/espanol/news/convenciones-de-nomenclatura-de-css-que-te-ahorraran-horas-de-depuracion/)
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/2cd89f85-395d-46fc-97c1-5fef6248cd6d)

Se realizará una revisión de estilos posterior a culminar la integración, ya que se observan unos estilos que pueden dificultar la lectura de algunos elementos en el cliente.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/78df1d3a-fd81-4a49-99bb-23abced5155c)

**Comment by edwargl7** [comment]
Buen trabajo, se realiza una revisión parcial del código, revisando componentes principales del desarrollo y parte de la lógica implementada. Se observa que cumple con lo requerido para finalizar la Issue :white_check_mark:, y se describen unas observaciones adicionales para tener presente.

**Observaciones**
- En revisión con el arquitecto debemos evitar la lógica en los microclientes. Por lo tanto, además de requerir datos adicionales en el endpoint a crear, vamos a llevar esta lógica a los MID para dejar lo más sencillo posible los microclientes.
Punto de mejora gracias a las recomendaciones del arquitecto.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/866d6a6b-2f5d-4b71-a9d7-6c567110490b)
- :wrench: Al igual que para ARGO de donde se tomó de guía el modal, los estilos se pasaran al componente y no en el ts como se manejó inicialmente en este.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/3193587d-9bc6-4653-9cc5-84bf98daee95)
- :rocket: Muy buena práctica desde mi punto de vista la creación de funciones en los Service ya que permite la lectura más fácil del código y se aplica el principio Single Responsibility Principle.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/78bbc09a-4066-42c3-9f5e-2566b2f624c9)
 :pencil2: Se puede como sugerencia cambiar el nombre de la función a _getUserByEmail_ dado que estamos obteniendo los datos de ese usuario consultando por el email.
