### ISSUE TITLE
Integración WSO2 y microcliente de gestión de usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#71]
Se requiere realizar la integración de WSO2 con el microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).
Esta integración debe permitir consultar en WSO2 un usuario con el número de identificación o correo electrónico si existe tener la posibilidad de agregar o remover un rol, si no existe debe mostrar un modal indicando que el usuario consultado no existe.

**Sub Tareas**

- [x] Integración WSO2 y microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).
- [x] Pruebas consultando un usuario registrado en WSO2.
- [x] Prueba consultando un usuario que no existe en terceros y mostrando el modal de error.

**Criterios de aceptación**

- [x] Integración microcliente y WSO2.
- :lock: Pruebas del correcto funcionamiento integración WSO2 (add, remove, consulta).

**Requerimientos**

- [x] Consulta al arquitecto sobre posibilidad de existencia de usuario en tercero y no en WSO2, y como gestionar dicho caso.
- [x] Endpoint de consulta de WSO2.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Integración de WSO2

Se realiza la integración con WSO2 para realizar la búsqueda en la interfaz mediante el correo y que traiga el nombre del usuario como se muestra a continuación:

![Captura de pantalla 2024-07-04 a la(s) 9 59 08 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/f061a8a9-299a-430a-a8dc-b6233822d180)

Cuando no se encuentra el usuario se muestra el modal informando el resultado, se realizo usando sweetalert2.

![Captura de pantalla 2024-07-04 a la(s) 9 57 02 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/6337bce2-8d12-4f4f-b7f7-21abf3a2af86)

Mediante WSO2 no se tiene el nombre completo, sino los apellidos como se ve en la primer y ademas hay algunos usuarios que existen en WSO2 pero tienen el campo del nombre vacío.

**Comment by edwargl7** [comment]
Roles que existen en WSO2 AUDITOR=2 y JEFE_DEPENDENCIA=3

**Comment by edwargl7** [comment]
Buen trabajo, es necesario realizar ajustes en la integración realizada en la Issue #70 y #71 por la necesidad de la búsqueda en WSO2 por el documento de identidad y lograr de esta forma integrar la búsqueda con terceros cuando solo se cuenta con el documento de identidad del usuario a consultar. Se realizó la revisión con el Arquitecto y la solución requerida.

Tener presente los comentarios de la Issue #70 con respecto a los nombres de las clases de los estilos CSS. Dado que se trabaja en la misma rama de desarrollo las Issues 70 y 71, pendiente subir el código con los avances de los modales.
No requiere PR dado que se continuará desarrollando en la misma rama.

**Comment by edwargl7** [comment]
Se finaliza la revisión, y se documenta unas observaciones adicionales en la Issue #70. Muy buen trabajo.
