### ISSUE TITLE
Integración microservicio de usuarios y microcliente de gestión de usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#72]
Se requiere realizar la integración entre el microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) con el microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).
Esta integración requiere realizar primero la consulta en terceros y WSO2 de un usuario con el número de identificación o correo electrónico si existe tener la posibilidad de agregar o remover un rol, si no existe debe mostrar un modal indicando que el usuario consultado no existe.

**Sub Tareas**

- [x] Integración historico_usuarios_roles_crud y microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).

**Criterios de aceptación**

- [x] Integración microcliente y historico_usuarios_roles_crud.

**Requerimientos**

- [x] Completar Issue #70 y #71 ya que es requerido esos datos para poder realizar el registro del usuario en el microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud).

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Integración

Se realiza el ajuste de icono en el modal: 

![Captura de pantalla 2024-07-05 a la(s) 9 25 24 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d616a278-e5b3-4f34-b165-11fbe9325790)

Adicionalmente se esta ajustando el código del microcliente con los cambios realizados en la rama de actualizacion-roles-id para la gestion de roles.

**Comment by edwargl7** [comment]
Se finaliza tarea, se requieren realizar ajustes en los endpoints de terceros y WSO2 para finalizar el desarrollo e integración con el microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud).
