### ISSUE TITLE
Crear el diagrama de flujo del sistema para el submódulo PAA

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#73]
Se requiere realizar la actualización del diagrama de flujo del sistema para el submódulo PAS según requerimientos del cliente

**Sub Tareas**

- [x] Construir diagrama de flujo según requerimientos del cliente
- [x] Presentar al equipos SoS diagrama actualizado
- [ ] Aprobar con el cliente diagrama actualizado

**Criterios de aceptación**

- [ ] Diagrama de flujo refinado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se crea el diagrama del flujo para la creación del plan anual de auditoria PAA dentro del módulo correspondientes con las aprobaciones y asignación de estados para cada actividad. Pendiente presentarlo al cliente el día 08 de julio de 2024.

**Flujo de Estados PAA**
![Image](https://github.com/udistrital/sisifo_documentacion/assets/167805282/66d1efac-b3d3-446f-943c-55f38b27b9de)

**Enlace del archivo cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=30iDLN


Saludos.

**Comment by jcmurilloa** [comment]
Gracias @cjgonzalezp, lo revisaremos en la poxima sesión!

**Comment by jcmurilloa** [comment]
Muy buen trabajo @cjgonzalezp, pendiente presentar y aprobar con el cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Se presenta diagrama al cliente, se ajustan sugerencias en el diagrama y se tiene aprobación por parte del cliente en la reunión del día 08 de julio de 2024 Acta No 066/2024

**Flujo de Estados PAA**
![Image](https://github.com/user-attachments/assets/c34ae17c-e0bf-4655-b321-08e0a4c62865)

**Enlace del archivo cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmRTO2kVKBRLryvB-1auu6wBrFcm76lVRIRyKQzf8FTO5w?e=y2Lfk1

**Enlace Acta de Reunión No 066/2024**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Et-a7_BrY3pEmFZ6uZF0QY0B9nxrTf9efMi3aD9Bn96RlQ?e=NekN0m


Saludos.

**Comment by jcmurilloa** [comment]
Excelente refinamiento del flujo con equipo SoS y cliente @cjgonzalezp. La ruta queda clara para desarrollo.
