### ISSUE TITLE
Diseñar el mockup para el submódulo Programa de Trabajo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#74]
Se requiere iniciar con el diseño del mockup para el submódulo Programa de Trabajo

**Sub Tareas**

- [x] Diseñar mockup inicial con base en los requerimientos.
- [x] Presentar el mockup al equipo SoS.
- [x] Realizar ajustes según comentarios del equipo SoS.
- [x] Presentar al equipo el mockup definitivo para presentar al cliente.

**Criterios de aceptación**

- [x] Mockup aprobado por equipo SoS.
- [x] Diseño documentado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza el diseño de mockup para el módulo de Gestión de Auditoria>>Programa de Trabajo.

**Mockup Submódulo Programa de Trabajo**



**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoyRXl0SFiZMmELWestQmMIBugV1jfr_pQioxnPwlXtXqQ?e=DKmtoo



Saludos.

**Comment by jcmurilloa** [comment]
Muy buen diseño @cjgonzalezp, pendiente aprobación del cliente.

**Comment by cjgonzalezp** [comment]
Buen día,

Agradezco cerrar la issue #74. De acuerdo a revisión con el cliente y el equipo SoS. Se debe replantear el submódulo programa de trabajo y dividirlo por procesos de auditoría. Adicional solicito generar una nueva issue para proyectar los submódulos nuevos.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se proyecta el submódulo Asignar Actividades y Actividades de Auditoria. Pendiente diseño de vistas desde el rol jefe de oficina y auditado (a) y los submódulos actividades de seguimiento e informes de ley los cuales se desarrollarán como segunda parte en el sprint 13

**Diseño mockup submódulo Asignar Actividades** 
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjqvehKllh1HvsFMvm98g8kBxZUNs7zMKPEunCyA67Klpg?e=WyBzcc

**Diseño mockup submódulo Actividades de Auditoría** 
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EjqvehKllh1HvsFMvm98g8kBxZUNs7zMKPEunCyA67Klpg?e=WyBzcc

Saludos.

**Comment by jcmurilloa** [comment]
Excelentes diseños @cjgonzalezp, se continuará entonces con la issue asignada en el sprint 13.
