### ISSUE TITLE
Validaciones y pruebas unitarias microservicios de gestión de usuarios y roles - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#75]
Se requiere realizar la revisión de pruebas unitarias a los endpoints del microservicio y realizar ajustes a las pruebas unitarias agregadas en la Issue #65 teniendo presente los asserts.
```
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

funcTestAddition(t *testing.T) {
	x := 2
	y := 2

	assert.Equal(t, x, y, "x and y should be the same")
}
```

**Material de apoyo**
- [empezando-con-los-tests-automatizados-en-go](https://blog.friendsofgo.tech/posts/empezando-con-los-tests-automatizados-en-go/)
- [Tutorial de Pruebas Unitarias GO](https://platzi.com/tutoriales/2232-programacion-golang/12156-tutorial-de-pruebas-unitarias-go/)

**Sub Tareas**

- [x] Agregar pruebas unitarias al microservicio CRUD.
- [x] Ajustar pruebas unitarias agregando asserts.
- [x] Agregar el resultado de coverage de las pruebas unitarias.

**Criterios de aceptación**

- [x] Pruebas unitarias complementadas y ajustadas del microservicio CRUD.
- [x] Coverage de las pruebas unitarias.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se crean metodos segun casos de validacion 


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/cdbaf82b-5675-4b69-a2da-9c540c56a49a)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/3c30b06d-bf60-4b42-a668-3f4f7510a744)

**Comment by jucastro94** [comment]
se ajustan los mensajes de respuesta a español en todos los controladores


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/dbc347b4-f35f-45b2-a17f-d7f464b429ba)

**Comment by jucastro94** [comment]
se ajustan validaciones para trabajar con assert 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/cc9bf973-c25b-4485-9427-51697a40bcdc)

**Comment by jucastro94** [comment]
se crea capa helpers con archivo utilidades.go para metodo de control de excepciones


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/05625909-e816-4f42-bbcc-21e1998b2efd)

se aplica defer en cada uno de los controladores 


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/d6d79aa3-331a-4a6d-bad0-ef254bd55722)

**Comment by jucastro94** [comment]
se optimiza metodo 


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e2f79c4c-0b37-4da8-a302-7015ae55727d)


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/a41ab522-51a2-45c4-a94d-2872077a873b)

**Comment by jucastro94** [comment]
se crean validaciones para controlador usuario


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c63ce288-2b31-45a0-96e9-0c59033c83d8)

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c634b108-cd6d-4c34-a97f-becd23c24b58)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8746355e-047e-4a15-8e67-1a014cd43a81)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7221d181-3755-4ea0-82f7-de44b5d9191e)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/fd4742d8-50d2-4a39-b024-981df21bde22)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/514b02c2-01a9-4cf5-b98a-c653e70b299a)


Se debe agregar validación para el numero de documento
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/91b8f377-e62c-4239-91d1-48165f328d05)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c2150042-eec5-4759-8751-16f62f01ad3d)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f2978e51-a54d-4c1f-b592-16eeb2675e14)

**Comment by jucastro94** [comment]
generacion de coverage


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/b71521f2-fb46-445b-b26b-2b96f0f88807)

**Comment by edwargl7** [comment]
Pendiente remover los archivos comentados en el [PR 2](https://github.com/udistrital/historico_usuarios_roles_crud/pull/2) y solicitar de nuevo el Pull Request ya sin dichos archivos.

**Comment by jucastro94** [comment]
se remueven los archivos mencionados y se solicita PR


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7c7b0c5c-d28f-4ddd-b465-3258864535de)

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e867f3ae-51b8-413b-a7ab-59b9bf552744)

**Comment by edwargl7** [comment]
Se observa un buen trabajo, cuenta con los ajustes solicitados en las pruebas unitarias y cuenta con una buena organización del código.
- :wrench: se debe revisar el PR ya que no se observa en este el commit en el que se removieron los archivos, en la rama de desarrollo si cuenta con la eliminación de estos.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/07aa5cf2-4433-4331-b8af-a3ea4221272e)

Se procede a finalizar la tarea y se revisara con el desarrollador el PR.
