### ISSUE TITLE
Pruebas ambiente Docker - microservicios de gestión de usuarios y roles - Sísifo v2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#76]
Se requiere realizar el cambio de versión del microservicio de gestión de usuarios y roles a la versión 1.18 de Go por compatibilidad con XRAY.

Una vez realizado el ajuste, validar el correcto funcionamiento del mismo en el entorno local. Luego realizar las pruebas con el entorno Docker con el docker-compose para observar la correcta creación de la base de datos.

Esta Issue es la continuación de la Issue #46 

**Sub Tareas**

- [x] Cambio de versión de Go del proyecto a la versión 1.18.
- [x] Pruebas del correcto funcionamiento del microservicio una vez cambiada la versión.
- [x] Agregar XRAY al proyecto y validar su correcto funcionamiento.

**Criterios de aceptación**

- [x] Microservicio funcionando correctamente modificando versión del proyecto y agregando XRAY.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se cambia la version de go tanto en el entorno y del proyecto 

![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/4a302780-cdfb-41e4-863f-6f091059eb6b)


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/7d9d46d4-2ddc-4024-ac29-7efe3a6fedb1)

**Comment by jucastro94** [comment]
se realizan pruebas para verificar el correcto funcionamiento

GetOne
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/b78a28bc-914f-42b6-bc50-7b3d9f288f9d)

GetAll
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c860c16e-636b-409e-898b-cf5037267470)


Post
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/e0b15cb4-4072-4767-b49f-3b05ba7b676d)


Put
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/82bfa80f-c94a-47de-b986-022c6ccf2806)


Delete
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/c851399d-bf94-4250-ac85-d0226b3356a0)


test endpoints
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/a7207c28-7d10-4791-95ef-47707c128b3d)


test 
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/5abfa372-f86e-4e2b-b7a8-858787fbdf26)

**Comment by jucastro94** [comment]
se agrega xray al proyecto y se valida funcionamiento


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/3711daf1-e371-414a-93fa-453b6796188e)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/0afa1144-dc53-49a7-83ff-5a5a9beba017)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/0f214ddd-fb89-412d-9e16-3e1aefaf3304)

**Comment by edwargl7** [comment]
Basado en las pruebas documentadas se observa que cumple con el alcance proyectado, similar a lo descrito en la Issue #75 se debe revisar el pull request dado que no cuenta con los últimos commits desarrollados.
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/979ed298-7486-477d-9f18-2b480da7d385)
Se procede a cancelar el PR actual para que se solicite nuevamente por favor. Tener presente agregar en la descripción del PR primero la etiqueta udistrital/... y en el título la etiqueta según corresponda (feat, test, ...) por favor.
