### ISSUE TITLE
Desarrollo endpoint de consulta por documento de identidad en autenticacion_mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#77]
Se requiere realizar el desarrollo de un nuevo endpoint en el API MID [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) que retorne la misma estructura del endpoint _token/userRol_.
```json
{
    "role": [
        "CONTRATISTA",
        "ESTUDIANTE"
    ],
    "documento": "XXXXXXXX",
    "documento_compuesto": "CCXXXXXXXX",
    "email": "XXXXXXXX@udistrital.edu.co",
    "FamilyName": "XXXXXXXX XXXXXXXX",
    "Codigo": "XXXXXXXX",
    "Estado": "Z"
}
```
Agregando adicionalmente el campo de nombre completo requerido para el microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf).
```json
{
    "role": [
        "CONTRATISTA",
        "ESTUDIANTE"
    ],
    "documento": "XXXXXXXX",
    "documento_compuesto": "CCXXXXXXXX",
    "email": "XXXXXXXX@udistrital.edu.co",
    "FamilyName": "XXXXXXXX XXXXXXXX",
    "FullName": "XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX",
    "Codigo": "XXXXXXXX",
    "Estado": "Z"
}
```

**Sub Tareas**

- [x] Revisión API MID [autenticacion_mid](https://github.com/udistrital/autenticacion_mid) endpoint _token/userRol_.
- [x] Replicar el controlador _token/userRol_.
- [x] Refactorización funciones que pueden reutilizarse para el nuevo endpoint.
- [ ] Integración con terceros para obtener nombre_completo, primer_nombre, segundo_nombre, primer_apellido y segundo_apellido.
![image](https://github.com/user-attachments/assets/681d7822-0d0f-41c1-8a06-39d53b5444a5)
- [x] Pruebas del correcto funcionamiento del nuevo endpoint.

**Criterios de aceptación**

- [x] Nuevo controlador creado.
- [x] Pruebas locales del correcto funcionamiento del nuevo endpoint.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Avance 

Se realiza la clonación del repositorio autenticacion_mid y se da inicio a la revisión del endpoint.

![Captura de pantalla 2024-07-08 a la(s) 11 29 28 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/142f719c-c00e-4aa2-9b96-8ca40e6ff6ca)

**Comment by alexhrr** [comment]
## Avance desarrollo endpoint

Se realiza una reunión con el lider para aclarar algunas dudas con respecto a la integración de WSO2 ya que no se estaba ejecutando correctamente la búsqueda del usuario en el API autenticacion_mid.

![Captura de pantalla 2024-07-09 a la(s) 10 59 56 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/4073dfe2-3bc8-4ed6-9c32-ac6b6da60609)

Haciendo un debug se encuentra que falta un endpoint para la variable de entorno "GetCodeByEmailStudentService" que hace parte de la ejecución del mid y es necesaria para mostrar el resultado de la consulta. 
Quedo a la espera del endpoint para verificar el funcionamiento del API mid y continuar con el desarrollo de la búsqueda del usuario por el documento.

Durante la  reunión se evalúa y decide el flujo que se va a tener en la consulta de los usuarios para el microcliente, quedando de la siguiente forma:

La consulta realizada desde el mf se puede hacer con el documento de identidad o con el correo del usuario, con las dos opciones se hace uso del api autenticacion_mid para verificar que el usuario existe en WSO2 y posteriormente se hace la consulta en el endpoint de Terceros para traer los datos del usuario como por ejemplo su nombre completo.
* Para la búsqueda con el correo del usuario ya se cuenta con el servicio que trae los datos necesarios (incluido el documento de identidad) para la posterior consulta en terceros.

![Captura de pantalla 2024-07-09 a la(s) 10 46 16 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/490f2153-20d9-4c27-b2f8-1ad63e49625e)

* Para la consulta en WSO2 con el documento del usuario se debe crear el servicio que consuma el endpoint respectivo y verifique con el documento si el usuario esta registrado en WSO2  y que posteriormente realice la consulta en Terceros.
Para crear este nuevo servicio se va a hacer uso del endpoint con el que se puede realizar la busqueda por documento en WSO2, asi mismo se propone cambiar la estructura para agregar partes del código en funciones para ser usadas por el nuevo servicio y no se repita codigo.
  
![Captura de pantalla 2024-07-09 a la(s) 10 51 06 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/917818b9-6993-428b-9904-e86ff1337840)

Finalmente se debe crear el helper para Terceros que obtenga los datos del usuario mediante el documento de identidad una vez que se ha verificado que el usuario esta creado en WSO2.

![Captura de pantalla 2024-07-09 a la(s) 10 55 00 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/d1e325b8-303b-43cc-99cb-7eeebde1919a)

**Comment by alexhrr** [comment]
Se usa la variable de entorno suministrada para realizar las consultas en autenticacion_mid y se logra obtener la consulta satisfactoriamente:

Así mismo se ejecutan las pruebas para confirmar su correcto funcionamiento:

![Captura de pantalla 2024-07-10 a la(s) 3 05 45 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/225178c3-e138-4a7e-859f-0d318a3b13c0)

Por lo tanto se procede a iniciar con el desarrollo del nuevo endpoint para la consulta por documento de identidad.

**Comment by alexhrr** [comment]
### Consulta WSO2 por documento

Se realiza la creación de la consulta a WSO2 mediante el documento de identidad del usuario retornando información básica del usuario:

![Captura de pantalla 2024-07-11 a la(s) 11 10 20 p  m](https://github.com/user-attachments/assets/413438d2-a235-4682-ba41-8e7e83538740)

Así mismo, de acuerdo a lo solicitado se realiza la función GetPayload en la sección token_helper.go para evitar la repetición de código en el servicio:

![Captura de pantalla 2024-07-11 a la(s) 11 19 40 p  m](https://github.com/user-attachments/assets/24dc0623-8cec-473f-a229-43e23e88777f)

Teniendo la consulta en WSO2 mediante correo y documento del usuario se puede continuar con el desarrollo de la consulta a terceros mediante el documento del usuario, por lo tanto se inicia con su planteamiento.

**Comment by edwargl7** [comment]
Se confirma con el arquitecto si dejar el endpoint en camelCase o aplicar los nuevos [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md) que indica separar cada palabra por "-" y se va a manejar para este endpoint camelCase.

**Comment by edwargl7** [comment]
Se realiza la actualización de las subtareas basado en las diferentes subtareas realizadas.

**Comment by alexhrr** [comment]
### Consulta a terceros

Para realizar la consulta a terceros después de realizar la validación en WSO2 se debe tener primero la consulta al endpoint de terceros mediante el documento de identidad del usuario, por lo tanto se crea el respectivo endpoint:

![Captura de pantalla 2024-07-12 a la(s) 10 44 48 p  m](https://github.com/user-attachments/assets/976ae08e-654c-4c9c-8743-71f5efc7e999)

La consulta actualmente trae el nombre completo del usuario como se ve a continuación:

![Captura de pantalla 2024-07-12 a la(s) 10 44 35 p  m](https://github.com/user-attachments/assets/ed709cb4-c829-4669-b3dd-e93c8a8bddfd)

Se debe verificar la ruta para realizar la respectiva consulta y obtener los datos solicitados: nombre_completo, primer_nombre, segundo_nombre, primer_apellido y segundo_apellido.

Queda pendiente que la consulta a terceros se realice después de validar la consulta en WSO2.

**Comment by alexhrr** [comment]
### Consulta WSO2

Se realiza la corrección en la refactorización de la función GetPayload, añadiendo la función auxiliar mapAtributos, para mejorar la separación de responsabilidades:

![Captura de pantalla 2024-07-13 a la(s) 1 53 01 p  m](https://github.com/user-attachments/assets/f0d785b7-418d-4ab5-b3c8-584e0cff39ab)

![Captura de pantalla 2024-07-13 a la(s) 1 53 11 p  m](https://github.com/user-attachments/assets/9e6c2554-2146-450d-85d9-6a9aa58b02f4)

Se elimina el controlador que realizaba la búsqueda en Terceros, dado que se va a manejar esta funcionalidad en el microcliente, quedando solo la consulta por documento como nuevo endpoint.

![Captura de pantalla 2024-07-13 a la(s) 1 57 12 p  m](https://github.com/user-attachments/assets/d1b17c47-1e9d-4d03-acf3-b34ac4d3c6e4)

Asi mismo se realiza la prueba para verificar que los endpoints quedan funcionando correctamente:

### /userRol: 

Se remueve evidencia por datos sensibles.

### /emailToken:

Se remueve evidencia por datos sensibles.

### /documentoToken:

Se remueve evidencia por datos sensibles.

**Comment by edwargl7** [comment]
Se culmina el desarrollo revisado en una reunión de revisión de dudas. Pendiente permisos para poder subir el desarrollo y solicitar revisión y despliegue de los ajustes realizados con el arquitecto.

**Comment by edwargl7** [comment]
Se asginan permisos de escritura para subir el desarrollo realizado.
FYI: @alexhrr
