### ISSUE TITLE
Agregar campo de estados al controlador y tabla de periodo_rol_usuario del microservicios de gestión de usuarios y roles

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#78]
Se requiere realizar la adición del campo _finalizado_ en la tabla _periodo_rol_usuario_ del modelo de datos de [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud). Dado que es necesario diferenciar los registros cuyo periodo ya finalizó de una forma más práctica sin validar por fecha de finalización del periodo.

**Sub Tareas**

- [x] Actualizar modelo de datos con el campo _finalizado_.
- [x] Crear migración en el microservicio para crear en nuevo campo en la base de datos.
- [x] Modificar los modelos en el microservicio para contemplar el nuevo campo.
- [x] Pruebas del correcto funcionamiento de registro y actualización por medio de los endpoints de periodo_rol_usuario

**Criterios de aceptación**

- [x] Completar las subtareas siguiendo los lineamientos.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Modelos de datos**
1. Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se crean archivos .up.sql y -down.sql para la migracion


![Image](https://github.com/user-attachments/assets/e373f694-edaf-4ab4-88a1-774459587d12)




![Image](https://github.com/user-attachments/assets/0f6d694d-e3ea-4542-98c2-c25b31e065c3)



![Image](https://github.com/user-attachments/assets/80f8ff12-c61d-452a-91bc-a2d99d809618)

se crea archivo de migracion en database/migrations 


![Image](https://github.com/user-attachments/assets/eba9a37d-4566-4a91-8e0c-eac5a814487c)

se ejecuta comando bee migrate satisfactoriamente 


![Image](https://github.com/user-attachments/assets/90b06860-766f-41c0-9def-3143fca66325)



![Image](https://github.com/user-attachments/assets/66b2a2da-0fa3-4681-893d-ebcd92e7f587)

**Comment by jucastro94** [comment]
se modifica el modelo 

![Image](https://github.com/user-attachments/assets/fddc241e-27c2-46f1-978f-c94079a7d7bc)

**Comment by jucastro94** [comment]
se hace validacion de funcionamiento GET

![Image](https://github.com/user-attachments/assets/561f6588-68cb-477c-8309-a97d64eef0aa)



![Image](https://github.com/user-attachments/assets/8e85eaf4-be29-46d5-8e0f-a4e7a4c995ae)



![Image](https://github.com/user-attachments/assets/d8e047bf-2e38-4f8b-87ef-7f9b11228b79)

**Comment by jucastro94** [comment]
se modifica modelo de datos

![Image](https://github.com/user-attachments/assets/85db8624-8cef-4007-94c0-bde5a29310e7)

se adjunta a carpeta de proyecto

https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ESWBH2-Vz_FBrIkMxmyzlM0BmFvzx2viESGLkPVbkzjZMA?e=1OVGec

**Comment by edwargl7** [comment]
Se realiza la revisión, cuenta con el desarrollo correcto y documentación completa. Por favor actualizar el enlace del modelo de datos en el README del repositorio @jucastro94. Buen trabajo.

**Nota:** Se esta revisando con DBAs y el arquitecto cambios requeridos en la forma de ejecutar las migraciones con el framework dado que actualmente se correran las migraciones manualmente. Se revisa como evitar afectaciones con las migraciones que corre el framework.
