### ISSUE TITLE
Refinamiento modelo de datos formularios dinámicos - Parte 1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#79]
Se requiere realizar el refinamiento del modelo de datos propuesto para los formularios dinámicos. Esta primera parte de refinamiento aborda la realización de los ajustes observados en la Issue #69 por el líder técnico de Sísifo. En la segunda parte se realiza la presentación y realización de ajustes sugeridos por el equipo SGA y el líder técnico de Sísifo.

**Ajustes requeridos**
- En la colección **modulo** el campo _sistema_id_ como viene del [modelo de datos relacional de historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud?tab=readme-ov-file#modelo-de-datos) se debe cambiar a tipo de dato numérico.
- En la colección **formulario**:
> - No requiere el campo _modificado_por_id_ dado que cada modificación crea una nueva versión.
> - El campo _creado_por_id_ se debe vincular con el campo id de la tabla de tercero.
- En la colección **elemento_html**:
> - Corregir el nombre del campo _deshabilitado_.
> - El campo validador debe ser de tipo Lista.
- Agregar una colección que permita gestionar la relación de muchos a muchos entre la colección _seccion_ y _elemento_html_ para que permita almacenar validadores propios (custom del cliente) según lo requiera el usuario al momento de construir la plantilla del formulario usando los elementos HTML existentes (estos validadores son diferentes a los propios del elemento creado, por ejemplo, si el usuario que crea la plantilla requiere un campo numérico pero con unos valores mínimos o máximos específicos para esa plantilla). :test_tube: Aunque esta funcionalidad posiblemente no se implemente en una etapa cercana, es necesario contemplar este escenario.

**Sub Tareas**

- [x] Realizar los ajustes descritos en esta Issue (nueva versión del modelo de datos).

**Criterios de aceptación**

- [x] Modelo de datos actualizado con los ajustes descritos en esta Issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Nueva versión del modelo de datos con los ajustes requeridos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizan los ajustes descritos en esta Issue en una nueva versión del modelo de datos. Además, surgieron los siguientes cambios significativos:

![_Modelo de datos - formularios dinámicos-versión 3  drawio](https://github.com/udistrital/sisifo_documentacion/assets/48999834/a71cb0e9-507d-45b0-8439-575ed63b5272)

### elemento_personalizado

- Se crea una nueva colección `elemento_personalizado` para almacenar los elementos propios (personalizados del usuario), los cuales son creados con base en una plantilla de un `elemento_html`. También se hace el cambio para que esta nueva tabla guarde la información de los parámetros que el usuario pueda personalizar (label, placeholder, requerido, etc.).
- Los atributos `validadores_personalizados` y `parametros_personalizados` son para almacenar valores personalizados por el usuario (Opciones de un selector, max y min de un numérico, etc.).

### elemento_html

- La colección `elemento_html` ahora se encarga de almacenar los componentes más básicos para crear elementos de un formulario, sirviendo de plantilla para `elemento_personalizado`. 
- Se especifica la lista de validadores como `<Object[]>`. También se plantea la posible opción `<array(Object)>`.
- Los atributos `validadores` y `parametros` son para construir cualquier elemento de un formulario con sus valores más básicos y requeridos.

### Link del diagrama 

[Modelo de datos - formularios dinámicos V3](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ETSi8-j-CV9PuE4Wm2unUbMBOP6TTIdcpibZbBZ2zY7ytQ?e=9Gx6Nb)

**Comment by edwargl7** [comment]
Se observa que cumple con los ajustes requeridos, dado que en la revisión realizada hoy en la que se contemplo la necesidad de dejar el campo de fecha de modificación en la colección de formula, se debe evaluar dejar el campo de modificado_por_id pero solo para almacenar los cambios de activo. No sé podrán realizar más cambios en los registros, un cambio de otro tipo da la creación de una nueva versión.
