### ISSUE TITLE
División del Cliente Sísifo v1 en Microfrontends - Microcliente Plan mejoramiento PT1

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#8]
Se requiere realizar la planeación y estructuración para dividir el sistema Sísifo v1 en microclientes siguiendo los lineamientos brindados por la OATI. Para esto consulte el material de apoyo que brinda documentación de la separación del frontend en varios microclientes en otros sistemas desarrollados por la OATI.

**Material de apoyo**
- [Microclientes](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#microclientes)
- [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)
- [División del Cliente en Microfrontends PT1](https://github.com/udistrital/planeacion_cliente/issues/892)
- [División del Cliente en Microfrontends PT2](https://github.com/udistrital/planeacion_cliente/issues/910)

**Sub Tareas**

- [x] Análisis del sistema Sísifo v1 microcliente de Plan mejoramiento (Plan mejoramiento, Hallazgos, Actividades, Avances, Reportes, Cargue masivo, Notas/Mensajes)
- [x] Crear diagrama de componentes de la arquitectura para el Sísifo v2.
- [x] Listado de funcionalidades de cada microcliente basado en las funciones conocidas en el manual de usuario revisado en las tareas realizadas en el Sprint 0.

**Criterios de aceptación**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Listado de funcionalidades que componen cada microcliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división clara el sistema en múltiples microclientes.
- [x] Listado de funcionalidades que componen cada microcliente.
- [x] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
# Diagrama de componentes plan de mejoramiento Sísifo v2.

Se realiza la versión inicial del diagrama de componentes para los módulos del plan de mejoramiento del sistema SISFO.
Componentes:
* Planes por unidad
* Hallazgo
* Actividades
* Avances
* Reportes
* Cargue masivo
* Notas/Mensajes
* Herramientas 

![componentes SISFO-Plan de Mejoramiento](https://github.com/udistrital/sisifo_documentacion/assets/42241322/0fc200d1-1644-4445-8b4c-b51e56b8f520)

Las secciones de color amarillo son para realizar una revisión y aclarar dudas de su funcionamiento.

**Comment by CristianCGutierrezG** [comment]
se adjunta enlace del diagrama de componentes del plan de mejoramiento:
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ET6eKLlTkH1KsTehE75Hdf4Ba5NYSFTwIKDdavA4sKqPpg?e=eWhgNF

**Comment by CristianCGutierrezG** [comment]
Se adjunta enlace del listado de funcionalidades que componen cada microcliente:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQplKSjhFnpAuWiAv-mj0YwBQv3GxBLRy6MHFhYPDDyEKw?e=6zIAdd

**Comment by alexhrr** [comment]
# Listado de funcionalidades de los componentes

Se crea el listado de los componentes con sus respectivas funcionalidades:

![Captura de pantalla 2024-05-03 a la(s) 5 09 54 p  m](https://github.com/udistrital/sisifo_documentacion/assets/42241322/7d5fcaf9-170a-40b4-a4f6-25c1067acf55)

**Comment by edwargl7** [comment]
Excelente trabajo.Se debe agregar las dependencias del cargue masivo y el módulo de avances. Y remover adjuntos dejando solo soportes en el módulo de avances.
