### ISSUE TITLE
Diseñar diagrama de flujo del submódulo de programa de trabajo

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#80]
Se requiere realizar la actualización del diagrama de flujo del submódulo de programa de trabajo

**Sub Tareas**

- [x] Repasar diagrama de flujo del submódulo de programa de trabajo
- [x] Generar las modificaciones según requerimientos
- [x] Presentar al equipos SoS diagrama actualizado

**Criterios de aceptación**

- [x] Diagramas de flujo actualizado

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se realiza diagrama de flujo para la implementación del proceso de auditoría y seguimiento y los estados en cada una de las actividades del mismo.

**Diagrama de Flujo Proceso de Auditoria y Seguimiento**
![Image](https://github.com/user-attachments/assets/9cad5824-6384-47e3-b2b8-ff61ae5822c0)


**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ems_fZUi1tlJhckEYc5I6JYBc_DRhrr1itw9QfWQIULeMQ?e=euTLXG


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, repasaremos el diagrama en la próxima sesión review SoS.

**Comment by jcmurilloa** [comment]
Por favor tener en cuenta las recomendaciones realizadas por el equipo SoS y exponer al cliente para su aprobación.

**Comment by cjgonzalezp** [comment]
Buen día,

Según recomendaciones realizadas por el equipo SoS se realizan ajustes al diagrama inicial y se dividen los procesos en dos diagramas. Quedo atento a sus comentarios o sugerencias adicionales @jcmurilloa @edwargl7 

**Diagrama de flujo proceso de auditoria**
![Image](https://github.com/user-attachments/assets/9626ae63-c22d-4ff3-a719-9a44811dc137)

**Diagrama de flujo proceso de seguimiento e informes de ley**
![Image](https://github.com/user-attachments/assets/8fad734d-dd8a-440b-a8a4-de65f7483356)


**Enlace archivo guardado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ems_fZUi1tlJhckEYc5I6JYBc_DRhrr1itw9QfWQIULeMQ?e=mrtUfC


Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, revisaremos estos flujos en la siguiente sesión SoS.

**Comment by jcmurilloa** [comment]
Flujo aprobado por equipo SOS, pendiente exponer y aprobar por el cliente.
