### ISSUE TITLE
Refinamiento modelo de datos formularios dinámicos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#82]
Se requiere realizar el refinamiento del modelo de datos propuesto para los formularios dinámicos. Esta segunda parte de refinamiento aborda la presentación y realización de ajustes sugeridos por el equipo SGA y el líder técnico de Sísifo. La primera parte fue abordada en la Issue #79.

**Sub Tareas**

- [x] Presentación modelo de datos al equipo SGA.
- [x] Descripción en la Issue con el resumen de lo abordado en la reunión con el equipo SGA.
- [x] Realizar los ajustes resultantes de la reunión con el equipo SGA (nueva versión del modelo de datos).

**Criterios de aceptación**

- [x] Modelo de datos con los ajustes resultantes de la reunión con el equipo SGA (se realizaran ajustes parciales en caso que no se puedan abordar por completo en esta Issue).

**Requerimientos**

- Completar los ajustes requeridos en la Issue #79 

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Nueva versión del modelo de datos con los ajustes requeridos.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Cambios requeridos resultante de la reunión:

- [ ] padre_id de la colección de sección puede ser nulo, dado que puede existir un solo nivel
- [ ] en elemento personalizado el campo label puede cambiar a tipo Object para almacenar varios idiomas para manejo de traducción
- [ ] Agregar campo booleano de traducción en la colección de formulario, para identificar si el formulario tiene traducción

Adicional se va a revisar la posibilidad de almacenar la estructura json de retorno, y si esto requiere configuración desde la plantilla.

**Comment by CristianCGutierrezG** [comment]
Se realizan los cambios sugeridos al modelo de datos en la reunión con el equipo SGA.

![Modelo de datos - formularios dinámicos-versión 4](https://github.com/udistrital/sisifo_documentacion/assets/48999834/5d55e2c8-30f6-426e-9733-2d87a7968177)

Otras recomendaciones:
- Nueva colección para almacenar la estructura de salida de datos del formulario. Estructura para almacenar a dónde se dirige la información del formulario.
- Restricción atada a otro elemento, validadores cruzados que restringen elementos afiliados.

**Comment by CristianCGutierrezG** [comment]
### Modelo de datos versión 4
![_Modelo de datos - formularios dinámicos-versión 4  drawio](https://github.com/udistrital/sisifo_documentacion/assets/48999834/2905dc10-cbb2-45d4-8fc2-a2952ec54a72)


Link del diagrama
[Modelo de datos - formularios dinámicos V4](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EXp-9dSmOedEml-BxGvJcCEB1t6hgTEnSMBBir3OgutztA?e=gSM2u2)

**Comment by edwargl7** [comment]
Se cuenta con el modelo de datos ajustado con las sugerencias de la revisión con el equipo SGA, pendiente realizar un ejemplo de la estructura de la plantilla en formato JSON y de un acercamiento a la estructura generada para el almacenamiento de los datos, con el fin de identificar campos adicionales pueden ser requeridos desde la plantilla para la generación de la estructura de almacenamiento de datos.
Si se requiere una colección o tabla separada para plantear el mapeo de la estructura generada por el microcliente y la necesaria para el almacenamiento se contemplará en un módulo separado de este.

**Comment by CristianCGutierrezG** [comment]
Se realizan pequeñas modificaciones en el diagrama
- Se removió los << nn >> en todas las descripciones
- Se agrego el `modificado_por _id` en la colección `Formulario`

Además se realiza un ejemplo de la estructura de la plantilla en formato JSON usando como ejemplo un formulario de SGA:

![image](https://github.com/user-attachments/assets/4cd86b18-8abc-4479-a33c-a77e62071e75)

![image](https://github.com/user-attachments/assets/4be64591-3673-480c-b655-747d706a23be)

**Comment by edwargl7** [comment]
Se realiza la revisión del modelo y de la estructura de ejemplo. Se va a trabajar unos ajustes adicionales en el modelo de datos con lo observado en el ejercicio de construcción del JSON de la plantilla. En la que se observa la necesidad de agregar los mensajes de la validación y la necesidad de evaluar la relación entre elementos HTML por dependecias.

Muy buen trabajo.
