### ISSUE TITLE
Actualización documentación técnica formularios dinámicos con modelo de datos - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#83]
Se requiere realizar la actualización de la [documentación técnica](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWVOWLs_czZPgR0-Pr0YKs8Blkk5wyoS4jmAhxDqRa5JXQ?e=jW87nG) creada en la Issue #57, complementando con la información detallada en la Issue #69 en una nueva sección _Modelo de datos_ que incluya dos subsecciones:
1. Modelo de datos predecesor, en el que se agreguen la referencia al modelo de datos de sisgplan que involucre solamente las 3 tablas requeridas para el formulario dinámico (plan, subgrupo, subgrupo-detalle) y la descripción de estas colecciones según lo evidencia en la exploración realizada.
> - Agregar las consultas a base de datos realizadas con los ejemplos de resultados obtenidos que permitan evidenciar de forma clara la estructura del modelo actual. 
2. Modelo de datos propuesto, que detalle cada una de las colecciones involucradas en este modelo separadas en subsecciones dentro de esta subsección, adicional agregar la investigación relacionada con los atributos Comunes en Formularios HTML referenciada dentro de la descripción de la colección de elemetos_html.

**Sub Tareas**

- [x] Creación versión 1.1 del documento, almacenando en PDF la versión 1.0, y agregando en la tabla de versiones la versión 1.1. Ejemplo:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/7db32cf6-e78a-4c9f-8ea9-31f44881e356)
- [x] Agregar subsección de modelos de datos predecesor la cual se divida en subsecciones con la descripción base de las colecciones (plan, subgrupo, subgrupo-detalle), otra con los resultados de las consultas realizadas a la base de datos que permitan evidenciar la exploración realizada.
- [x] Agregar la subsección Modelo de datos propuesto, dividida en subsecciones de descripción de cada una de las colecciones agregadas mencionando solamente los campos principales de cada una. Adicional, dentro de la subsección de Modelo de datos propuesto agregar la subsección con la investigación de atributos comunes en elementos HTML, que sea referenciada en la subsección de la colección de elementos_html. 

**Criterios de aceptación**

- [x] Documento técnico actualizado con la sección y subsecciones descritas en esta Issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realiza la actualización de la documentación técnica sobre formularios dinámicos

### Almacenando un pdf con la versión 1.0 del documento

[Borrador documento técnico V1.0](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EYpewC-_jAtMqiUSfefJsdcBWfnc8Fb92RSI6fez1kmtjA?e=HeN9Ql)

### Agregando una nueva sección Modelo de datos con dos subsecciones siguiendo las especificaciones dadas:

- Modelo de datos predecesor
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/d0c47768-2153-4bf4-b788-adcba599d2c8)

- Modelo de datos propuesto
![image](https://github.com/udistrital/sisifo_documentacion/assets/48999834/be2db85e-c53e-4b60-85d3-55749be52e3d)

### Link del documento

[Borrador documento técnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWVOWLs_czZPgR0-Pr0YKs8BPH9dLesCSKfnmXl9WmmhsQ?e=C4LMuW)

**Comment by edwargl7** [comment]
Se realiza la revisión del documento, en una siguiente iteración se complementará los objetivos y conclusiones. Se trabajará también complementar la relación padre e hijos del modelo de SISGPLAN.
![image](https://github.com/user-attachments/assets/e99c451e-a355-4add-a5de-7da19d58bc07)
Buen trabajo.
