### ISSUE TITLE
Implementación endpoint Health Check en el microservicio gestión de usuarios roles crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#84]
Se requiere realizar la implementación del endpoint Health Check requerido para la etapa de despliegue. Se debe seguir el lineamiento [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis) que indica lo necesario para agregar dicho endpoint al microservicio desarrollado en Beego.

**Sub Tareas**

- [x] Revisión lineamiento [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis).
- [x] Implementación endpoint Health Check en el microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud).
- [x] Realizar la prueba descrita en _Escenarios de pruebas_.

**Escenarios de pruebas**
- [ ] Consumo del microservicio en el path / y que genere la respuesta similar a:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/cc4a0f09-a736-4b89-99f8-dcc9561fdf64)

**Criterios de aceptación**

- [ ] Desarrollo realizado siguiendo los lineamientos descritos.
- [ ] Prueba local completada. 

**Requerimientos**

No aplica

**Material de apoyo**
-  Repositorio asociado [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud)
- [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)
- Repositorio [inscripcion_crud](https://github.com/udistrital/inscripcion_crud) que implementa el endpoint requerido.
- Script donde se implementa el controlador en utils_oas [apiStatusLib](https://github.com/udistrital/utils_oas/blob/master/apiStatusLib/apistatus.go)

**Especificaciones técnicas**
1. Implementación del endpoint siguiendo los lineamientos [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se integra health check
![image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/b71b66d3-30cf-47d7-9d07-4301b4ab6c3a)

se realiza prueba
![image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/24cebfb5-011a-4957-b906-e05c5bf34d14)

**Comment by edwargl7** [comment]
Por favor realizar el commit y pull requests con el desarrollo realizado.

**Comment by edwargl7** [comment]
Se realiza la revisión y se finaliza. Buenas pruebas.
