### ISSUE TITLE
Creación Docker para microservicio de gestión de usuarios roles crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#85]
Se requiere realizar los ajustes requeridos en el Dockerfile que permitan ejecutar el microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) sin establecer una conexión con la base de datos, para esta prueba dado que no se contará con una conexión a base de datos, la forma de validar que el servicio se encuentra funcionando correctamente se debe realizar mediante el endpoint Health Check.

Nota: Se puede establecer la conexión de base de datos del contenedor con una base de datos sin usar el docker-compose, pero para este ejercicio no se aborda dicha prueba.

**Sub Tareas**

- [x] Realizar los ajustes requeridos al Dockerfile empleado para levantar el servicio sin una base de datos.
- [x] Validar el correcto funcionamiento del endpoint Health Check.

**Escenarios de pruebas**
- [x] Consumo del microservicio en el path / y que genere la respuesta similar a:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/cc4a0f09-a736-4b89-99f8-dcc9561fdf64)

**Criterios de aceptación**

- [x] Dockerfile ajustado y que permita levantar el servicio sin la conexión a base de datos con el docker-compose.
- [x] Prueba local completada. 

**Requerimientos**

- Completar el desarrollo del endpoint Health Check de la Issue #84

**Especificaciones técnicas**
1. Este Dockerfile es propio para este escenario, el empleado para levantar el servicio con docker-compose es el que se encuentra en el directorio bee_build.

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
- Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
-  [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se realizan ajustes en Dockerfile
![image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/39aad665-a6a9-4e94-b585-e366fa80b520)

**Comment by jucastro94** [comment]
se contruye docker sin conexion a base de datos
![image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8d8d80cc-8da7-4095-b40d-50f8b25e53c5)

**Comment by jucastro94** [comment]
ejecucion y prueba
![image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/04826ed3-b67e-4caa-9cf6-345901572117)
![image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/4909aae2-9d23-4e21-8f12-10c4f76aac80)

**Comment by edwargl7** [comment]
Cumple con el escenario de prueba pero no se observa el commit ni pull request. Por favor realizar el commit correspondiente. Adicional actualizar por favor el README.

**Comment by edwargl7** [comment]
Se realiza la revisión con el desarrollador y cumple con lo requerido, pendiente consulta realizada al equipo de infraestructura para tener presente si es necesario que este Dockerfile cuente con la librería de **awscli**. Buen trabajo.
