### ISSUE TITLE
Ajustes Docker y docker-compose para microservicio de gestión de usuarios roles crud

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#86]
Se requiere realizar los ajustes requeridos en el Dockerfile (directorio bee_build) y docker-compose para el correcto funcionamiento del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) iniciado en el sprint 10 y que se presentaron fallas frente a la ejecución del comando bee requerido para las migraciones.

**Sub Tareas**

- [x] Ajustes Dockerfile (directorio bee_build) para el docker-compose.
- [x] Ajustes docker-compose.
- [x] Revisión de correcta ejecución del microservicio mediante el endpoint Health Check.
- [ ] Validación de correcta ejecución de las migraciones mediante el comando bee en la base de datos levantada con el docker-compose.

**Escenarios de pruebas**
- [x] Consumo del microservicio en el path / y que genere la respuesta similar a:
![image](https://github.com/udistrital/sisifo_documentacion/assets/50187485/cc4a0f09-a736-4b89-99f8-dcc9561fdf64)
- [ ] Revisión de base de datos levantada con el docker-compose, que cuente con las tablas de la migración creadas.

**Criterios de aceptación**

- [ ] Correcto levantamiento del servicio usando docker-compose.
- [ ] Correcta ejecución de las migraciones del microservicio en la base de datos usando los comandos de bee.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
- Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f3431131-d961-423f-bffd-2bc33330cfb3)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/0a735b8b-b4e0-49e8-b30e-31a877fc9a06)

**Comment by jucastro94** [comment]
# Usa una imagen base de Go
FROM golang:1.18

# Añade GOPATH/bin al PATH
ENV PATH="/go/bin:${PATH}"

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /go/src/${API_BASE_DIR}/${API_NAME}

# Copia los archivos de la aplicación al directorio de trabajo
COPY . .

# Instala bee utilizando go install
RUN go install github.com/beego/bee/v2@latest

# Instala las dependencias de Go
RUN go mod tidy

# Expone el puerto en el que la aplicación Beego estará escuchando
EXPOSE ${API_PORT}

# Comando para ejecutar la aplicación
CMD ["sh", "-c", "cd /go/src/${API_BASE_DIR}/${API_NAME} && bee run -downdoc=true -gendoc=true"]



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/26d1bd48-ba01-4a07-91a1-60124dc2b1bf)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/2025806b-db70-49c3-b33e-b0b924b2f187)

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/154cfbd0-40e5-4991-92ef-556a03baf143)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/ea3fcaa0-791c-42c1-9133-98872cc8ae67)

**Comment by jucastro94** [comment]
se hace prueba sin linea 

bee migrate -driver=postgres -conn="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=disable&search_path=${POSTGRES_SCHEMA}" || true &&



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/1271dcda-8f5b-4436-8f49-d19d69a79f0d)

**Comment by jucastro94** [comment]
se hace prueba sin 
?sslmode=disable&search_path=${POSTGRES_SCHEMA}


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/37844715-ea83-424f-a157-955b0002d800)

arroja error
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/8933c611-eabb-4be7-9b59-3f6d37275f09)

**Comment by jucastro94** [comment]
![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/a664059b-4664-4716-bc17-d28898b75766)

se ajustan migraciones 


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/bee2039f-5258-41c5-887e-f98cb2bbcf1f)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/f0be98b4-161e-4784-a33b-810265a6816e)

**Comment by jucastro94** [comment]
se mantiene el error, se investiga sobre el caso

al crear el servicio con el docker-compose queda se logra la ejecucion pero sin conexion a base de datos


![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/98b9cd0f-de32-442c-b586-75231057850e)



![Image](https://github.com/udistrital/sisifo_documentacion/assets/107083834/32595e4a-1e88-4784-8eb1-c508453ccdb7)

**Comment by edwargl7** [comment]
Se va a consultar otros equipos para revisar que opción manejan y si los actuales docker-compose en los servicios de ellos funcionan correctamente.

**Comment by jucastro94** [comment]
se hacen ajustes en docker compose y se quitan referencias a github.com/beego/beego/logs, ajustes varios


![Image](https://github.com/user-attachments/assets/9a6065b2-7a56-4785-ac23-fb7a6d7750e1)

**Comment by edwargl7** [comment]
Se debe revisar problemas con el cambio de versión del proyecto a la versión 1.18, sobre problemas con las migraciones. No se logra una correcta ejecución del docker-compose. Se pausa esta revisión dado que no es requerida para los despliegues.
