### ISSUE TITLE
Pruebas unitarias endpoint de consulta por documento de identidad en autenticacion_mid

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#88]
Se requiere realizar el desarrollo de las pruebas unitarias al endpoint desarrollado en la Issue #77 para consultar en WSO2 por número de documento de identidad. Tomar como guía las mismas pruebas unitarias con las que cuenta el repositorio [autenticacion_mid](https://github.com/udistrital/autenticacion_mid/tree/develop).

**Material de apoyo**
- Pruebas unitarias trabajadas en [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud/blob/develop/tests/services/validar_asignar_periodo_test.go), principalmente tomar de ejemplo el uso de assert y las funciones que tiene disponibles.

**Sub Tareas**

- [x] Revisión pruebas unitarias del controlador _token/userRol_. Ejemplo: [token_controller_test](https://github.com/udistrital/autenticacion_mid/blob/develop/tests/controllers/token_controller_test.go).
- [x] Creación pruebas unitarias para el nuevo controlador desarrollado en la Issue #77.

**Criterios de aceptación**

- [x] Creación de pruebas unitarias al nuevo controlador.

**Requerimientos**

- Completar el desarrollo de la Issue #77.

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
### Avance pruebas unitarias 

Se realiza la revisión del material de apoyo para la creación de las pruebas unitarias tomando como referencia la información suministrada.

Se da inicio a la creación de las pruebas unitarias al endpoint de consulta por documento en WSO2.

**Comment by alexhrr** [comment]
Se realizan las pruebas unitarias para consultar en WSO2 por número de documento de identidad de acuerdo a las referencias y el material de apoyo:

![Captura de pantalla 2024-07-17 a la(s) 5 33 37 p  m](https://github.com/user-attachments/assets/5e263f82-5d9f-454a-aaa3-5ab1bba17475)

Resultado de la ejecución de las pruebas:
 
![Captura de pantalla 2024-07-17 a la(s) 5 34 56 p  m](https://github.com/user-attachments/assets/d2dc2b4d-684f-408d-9524-db9c6fd48aae)

Lo anterior se encuentra en revisión para realizar los ajustes necesarios o si cumple los requisitos cargarlo al repositorio correspondiente.

**Comment by alexhrr** [comment]
Se realiza el ajuste solicitado y se carga al repositorio

**Comment by edwargl7** [comment]
Se realiza la revisión del código, cuenta con un buen desarrollo tanto del controlador nuevo requerido como de las pruebas de integración. Aprobado para crear el PR @alexhrr.

**Comment by edwargl7** [comment]
Finalizada la Issue completamente
