### ISSUE TITLE
Integración WSO2 nuevos endpoints con microcliente de gestión de usuarios

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#89]
Se requiere realizar la integración del endpoint desarrollado en la Issue #77 con el microcliente [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf) empleando el servicio en ambiente local mientras se realizan las pruebas y despliegue de este nuevo desarrollo.

Una vez integrado el endpoint de consulta por email y el endpoint de consulta por documento de identidad en WSO2 se debe complementar la integración con la consulta a Terceros consultando por documento de identidad desarrollado en la Issue #70.

**Sub Tareas**

- [x] Integración endpoint de consulta por documento de identidad en WSO2.
- [x] Integración consulta de terceros para obtener el nombre completo.
- [x] Pruebas funcionales que permitan evidenciar la correcta integración para consulta por email.
- [x] Pruebas funcionales que permitan evidenciar la correcta integración para consulta por documento de identidad.

**Escenarios de pruebas**
- [x] Prueba realizando la consulta de un usuario por documento de identidad, en el que se evidencie el llenado de los campo de nombre completo y el email.
- [x] Prueba realizando la consulta de un usuario por email, en el que se evidencie el llenado de los campo de nombre completo y el documento de identidad.

**Criterios de aceptación**

- [x] Implementación de integración con WSO2 y pruebas funcionales documentadas en la Issue.

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
## Avance integración 

Se realiza la respectiva integración en el ambiente local del endpoint consultaDocumento desarrollado en autenticacion_mid.

![Autenticacion](https://github.com/user-attachments/assets/195790f7-c362-4d7d-9dba-d2ccb058989f)

Se desarrolla el codigo para realizar la consulta por documento en WSO2 usando el endpoint mencionado y obtener el documento de identidad para buscarlo posteriormente en terceros.

Se realizan los ajustes necesarios al codigo existente para realizar la busqueda por correo en WSO2 y obtener el documento de identidad para buscarlo posteriormente en terceros.

En ambos casos se obtiene de terceros el nombre completo del usuario.

Se debe agregar el llenado de los campos Documento de identidad o correo segun sea el caso cuando se realice la busqueda.

**Comment by alexhrr** [comment]
### Integracion WSO2 y terceros

Se realiza la integración del endpoint desarrollado para la consulta por documento de identidad y se ajusta la consulta por email.

Cuando se realiza la consulta por documento de identidad se llenan los campos del email y el nombre completo traido de terceros como se ve a continuación:

![ConsultaDocumento](https://github.com/user-attachments/assets/3806ca61-f6b8-47f0-991a-c9b02a653527)

Cuando se realiza la consulta por email se llenan los campos del documento de identidad y el nombre completo traido de terceros como se ve a continuación:

![ConsultaCorreo](https://github.com/user-attachments/assets/b5d4cfab-ebbd-4ed1-ba8f-5bf5884d2637)

**Comment by edwargl7** [comment]
Se realiza la revisión del código y cuenta con una buena distribución en las funciones. Cuenta con una buena documentación la Issue y con las pruebas completas. Buen trabajo. Pendiente realizar el PR.

**Observaciones**
- Revisar flujo else.
![image](https://github.com/user-attachments/assets/f0bb4acf-4355-4f23-8a10-926dec2f0c81)
- Revisar flujo else.
![image](https://github.com/user-attachments/assets/c665dfec-8e0d-4cb8-9d0d-5a2a191d549c)
- Revisar console logs.
![image](https://github.com/user-attachments/assets/0973f34c-015d-4b89-a843-36e9de288e96)
![image](https://github.com/user-attachments/assets/944f977e-0ae9-4c5c-892f-b5814ee58afb)

**Comment by alexhrr** [comment]
Se realizan los ajustes mencionados en el codigo, removiendo los console logs que ya no se necesitan más y revisando el uso de los modal en la ejecución de las consultas.

**Comment by edwargl7** [comment]
Finalizada la Issue con ajustes requeridos.
