### ISSUE TITLE
División del Cliente Sísifo v1 en Microfrontends - Microcliente Plan mejoramiento PT2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#9]
Se requiere realizar los siguientes ajustes:

1. Ajustes dependencias cargue masivo
2. Remover importación dejando solo la posibilidad de cargue de evidencias en el módulo de avances.

**Sub Tareas**

- [x] Correcciones diagrama de microclientes [División del Cliente Sísifo v1 en Microfrontends - Microcliente Plan mejoramiento PT1](https://github.com/udistrital/sisifo_documentacion/issues/8)

**Criterios de aceptación**

- [x] Correción diagrama de componentes con la división del sistema en múltiples microclientes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Diagrama de componentes con la división del sistema en múltiples microclientes
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizan las correcciones del diagrama de componentes para los módulos del plan de mejoramiento del sistema SISFO.

1. Ajustes dependencias cargue masivo
2. Remover importación dejando solo la posibilidad de cargue de evidencias en el módulo de avances.

![componentes SISIFO - diagrama V4-Plan de Mejoramient](https://github.com/udistrital/sisifo_documentacion/assets/48999834/fbae8287-2096-4090-95fa-d7e5abd333cb)

se adjunta enlace del diagrama de componentes con las respectivas correcciones:
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EVPFf5meD89AkK_ti2FQlcoBEcjhOrNEYbvKxpQYK4OhDw?e=WLGbFZ

**Comment by edwargl7** [comment]
Muchas gracias por el ajuste al diagrama. A medida que se recopilen más requerimientos se realizaran los ajustes que sean requeridos. Por el momento se parte de este diseño.

Excelente trabajo.
