### ISSUE TITLE
Adición colección para gestión de alertas a nivel de formulario - modelo de datos formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#90]
Se requiere realizar ajustes en el modelo de datos de formularios dinámicos que complementen los siguientes casos:

- Mensajes para cada formulario que cubra modal de error en la consulta de información, error al almacenar, almacenado correcto (registro, actualización) y validación de datos incompletos. Con los siguientes campos:
> - icono
> - título
> - descripción
> - título botón principal
> - título botón secundario
> - etiqueta de tipo (se relaciona con los tipos de mensaje según el caso que puede ocurrir)
Nota: Evaluar uso similar a elementos_html y elemento_personalizado
- Relación entre elementos HTML, se observa principalmente la necesidad de revisar la forma de gestionar la relación entre selectores para el caso en el que una selección puede generar filtros sobre los valores de otro selector.

**Sub Tareas**

- [x] Actualización modelo de datos con colecciones requeridas para los mensajes (modales).
- [x] Evaluación de gestión de relaciones entre elementos HTML.
- [ ] Modelo de datos actualizado con campo de relación entre elementos HTML.
- [x] Presentación modelo a DBAs.

**Criterios de aceptación**

- [ ] Versión nueva del modelo de datos con los cambios requeridos en las subtareas.

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
1. Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Colección `modal_alerta`
Se crea una nueva colección con una relación a formulario, siguiendo las especificaciones dadas.

![image](https://github.com/user-attachments/assets/972a807c-b445-466c-9aa5-9815cef1ee06)

### Relación entre elementos HTML
Se plantea la forma de gestionar la relación entre dos elementos, considerando dos casos de representación:

#### Con una relación embebida y los siguientes atributos:

- `elemento_personalizado_id`: Indica con qué elemento se establece la dependencia.
- `filtros`: Almacena un objeto con la información del valor seleccionado y las opciones que filtra.

![image](https://github.com/user-attachments/assets/c0475481-22e4-493d-aca6-b8db233efcd9)

#### Con un nuevo atributo `dependencia`:

Un atributo que almacene un objeto con la información de la dependencia.

![image](https://github.com/user-attachments/assets/2a7e0711-23df-4c07-8334-4db4dc14ce60)


#### Ejemplo de un documento:

#### Selector A

![image](https://github.com/user-attachments/assets/2d0a95b0-0833-43c9-a15f-35077b84da59)

#### Selector B

![image](https://github.com/user-attachments/assets/ac65bf96-3618-4f7d-b519-c1a9ba79e681)

**Comment by edwargl7** [comment]
Se realiza la revisión y se aprueba el ajuste para el modal alerta. Revisaremos con más detalle la relación entre elementos. Por el momento se plantea la presentación del modelo de datos sin contemplar la relación entre elementos.

**Comment by CristianCGutierrezG** [comment]
### Modelo actual:

![_Modelo de datos - formularios dinámicos-versión 5  drawio](https://github.com/user-attachments/assets/d1860641-2056-4531-902d-cb19019c2894)

**Comment by edwargl7** [comment]
Aprobado para presentación a DBAs.

**Comment by CristianCGutierrezG** [comment]
Se realiza la presentación a DBAs, de la que surgieron las siguiente observaciones:

Se plantea cambiar el tipo de dato String a una opción más Paramétrica, en los siguientes atributos

### Coleccion modal_alerta:
`tipo: < string >`

### Coleccion elemento_html:
`tipo: < string >`
`tipo_dato: < string >`

**Comment by edwargl7** [comment]
Adicional a la revisión de los campos mencionados se trabajará en una siguiente tarea:
- Relación entre elementos (terminar de confirmar cual opción se utilizará)
- Como se va a  trabajar las opciones de idiomas en la traducción.
- Modal_alerta vincularlo con parametros_crud.
- Revisar cuales de los dos campos de elementos_html va con parametros_crud.
- Revisar la posibilidad de agregar label a _formularios_ y _seccion_ para control separado a nivel de código vs interfaz gráfica.

**Comment by edwargl7** [comment]
Buen trabajo y buena presentación, se abordará en una siguiente iteración los ajustes finales del modelo.
