### ISSUE TITLE
Concertar, desarrollar y levantar el acta de sesión de requerimientos y/o refinamiento con el cliente

### ISSUE THREAD

**Issue by jcmurilloa** [udistrital/sisifo_documentacion#91]
Se requiere realizar la concertación, desarrollo y levantamiento del acta de sesión de requerimientos y/o refinamiento con el cliente para aprobación de flujo y mockup programa de trabajo

**Sub Tareas**

- [x] Concertar reunión con el cliente.
- [x] Desarrollar la reunión con el cliente.
- [x] Diligenciamiento y aprobación del formato de historias de usuario o Mockup por parte del cliente (si aplica).
- [x] Proyectar acta de la reunión.
- [x] Recolectar las firmas correspondientes.

**Criterios de aceptación**

- [x] Acta revisada por el líder de proyecto.
- [x] Acta firmada por las partes con anexo de historias de usuario o mockup.
- [x] Acta y anexos documentados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cjgonzalezp** [comment]
Buen día,

Se contacta con el cliente para concertar reunión, la cual se programa para el día 23 de julio de 2024 hora: 10:00 am lugar: sede Paiba.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se desarrolla reunión con el cliente en el horario acordado con normalidad. Pendiente terminar de levantar el acta de reunión y recolectar firma de los participantes presentes.


Saludos.

**Comment by cjgonzalezp** [comment]
Buen día,

Se levanta acta de reunión No. 094/2024 SISIFO - Levantamiento de Requerimientos desarrollada el día 23 de julio de 2024 se envía documento para recolección de firmas. Pendiente cargar documento firmado en la carpeta del proyecto.

**Enlace documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
 https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtbX_J1YhdpMpk_CNXiUJN4Bk288UDM-lkHCMalOOx-LUw?e=fE606g


Saludos.

**Comment by jcmurilloa** [comment]
Gracias @cjgonzalezp, pendiente recolección de firmas.

**Comment by cjgonzalezp** [comment]
Buen día,

Se da por finalizada la issue #91 con la recolección de firmas de todos los participantes presentes en la reunión desarrollada el día 23 de julio de 2024.

**Enlace documento cargado en OneDrive en la carpeta del proyecto SISIFO V2**
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtbX_J1YhdpMpk_CNXiUJN4Bk288UDM-lkHCMalOOx-LUw?e=3z72CE

Saludos.

**Comment by jcmurilloa** [comment]
Buen trabajo @cjgonzalezp, cada vez recolectamos mas pronto firmas!
