### ISSUE TITLE
Revisión modelo de datos para estructura de almacenamiento de datos recopilados en el formulario dinámico

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#92]
Se requiere realizar la revisión de una estructura de almacenamiento de datos del formulario que permita identificar elementos adicionales que sean requeridos para el modelo de datos de plantilla y que ayuden a establecer la estructura de almacenado. De otra forma se establecerá un modelo independiente que permita realizar el mapeo entre el microcliente y el sistema que almacene la información.

**Sub Tareas**

- [ ] Diseño de estructura de almacenamiento de datos del formulario.
- [ ] Establecer los campos adicionales o modelo independiente para la estructuración de datos entre el microcliente y el sistema de almacenamiento.
- [x] Revisión de arquitectura pizarra para el almacenamiento de datos.

**Criterios de aceptación**

- [x] Documentación de la Issue con los avances realizados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Investigación de la Arquitectura de Pizarra

La arquitectura de pizarra (blackboard) es útil cuando varios componentes computacionales necesitan compartir y manipular grandes cantidades de datos, que no son exclusivos de ninguno de ellos. Se busca que los componentes accedan y se comuniquen exclusivamente a través de un repositorio de datos global, conocido como blackboard.

#### Conceptos

**Pizarra (Blackboard):** Es una memoria compartida donde los componentes del sistema pueden leer y escribir datos. Actúa como un repositorio central donde se deposita todo el conocimiento generado por los distintos componentes.

**fuente de conocimiento (Knowledge Sources) o agente:** Son los módulos o agentes que contienen el conocimiento especializado para resolver una parte del problema. Estos componentes son independientes y colaboran indirectamente a través de la pizarra.

**Controlador (Controller):** Es un módulo que gestiona el flujo de información y la coordinación entre los agentes y la pizarra. El controlador determina cuándo y qué componentes deben actuar según el estado actual del problema.

![image](https://github.com/user-attachments/assets/4ca5bf02-7fb0-443a-8803-990c3ec17039)

#### Características

- Comúnmente usada en sistemas de inteligencia artificial, especialmente en problemas que requieren la integración de diferentes formas de conocimiento.
- Cada agente solo conoce un aspecto específico del problema y se especializa en una tarea concreta. No necesita conocer a otros agentes, solo el estado del problema a través de la pizarra.
- Los agentes examinan la pizarra, realizan su tarea y escriben sus conclusiones en la misma pizarra. Así, otro agente puede trabajar sobre los resultados generados.
- El estado inicial de la pizarra es una descripción del problema que se debe resolver, y el estado final será la solución del problema.

#### Ventajas

- **Modularidad y reutilización:** Cada agente es independiente.
- **Flexibilidad y extensibilidad:** Permite incluir nuevas fuentes de conocimiento.
- **Eficiencia:** El control selecciona los mejores componentes para el proceso.

#### Desventajas

- Fuerte dependencia del componente Pizarra.
- No es fácil la sincronización y estrategia de control entre múltiples agentes.
- Es un reto la depuración y prueba del sistema.

**Comment by edwargl7** [comment]
Se modifica la tarea, dado que se contó con unos cambios pequeños a nivel del modelo de datos. Y la necesidad presentada por el equipo de SGA de contar con el microservicio para la implementación del microcliente, se complementa esta tarea con la revisión de la tecnología a usar para el desarrollo del microservicio de plantillas de formularios dinámicos.

**Comment by edwargl7** [comment]
Se documenta los campos planteados para cubrir las dos primeras subtareas en el último comentario de la Issue #90. Se procede a finalizar la tarea actual.
