### ISSUE TITLE
Implementación microservicio de plantillas de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#93]
Se requiere realizar el desarrollo del microservicio crud de plantillas de formularios dinámicos basado en el modelo de datos que cuenta con unos últimos ajustes abordados en la Issue #97. Para este desarrollo se debe tener presente el uso de mongoDB como base de datos para el modelo relacional.

Tener presenta el formato de respuesta.
![image](https://github.com/user-attachments/assets/73724431-6eba-4bf3-a0af-31248af74efe)

**Sub Tareas**

- [x] Implementación endpoint CRUD para _modulo_.
- [x] Implementación endpoint CRUD para _formulario_.
- [x] Implementación endpoint CRUD para _modal_alerta_.
- [x] Implementación endpoint CRUD para _seccion_.
- [x] Implementación endpoint CRUD para _elemento_html_.
- [x] Implementación endpoint CRUD para _elemento_personalizado_.
- [x] Pruebas funcionales de cada endpoint.

**Escenarios de pruebas**
- [x] Pruebas CRUD (con eliminación lógica) para _modulo_.
- [x] Pruebas CRUD (con eliminación lógica) para _formulario_.
- [x] Pruebas CRUD (con eliminación lógica) para _modal_alerta_.
- [x] Pruebas CRUD (con eliminación lógica) para _seccion_.
- [x] Pruebas CRUD (con eliminación lógica) para _elemento_html_.
- [x] Pruebas CRUD (con eliminación lógica) para _elemento_personalizado_.

**Criterios de aceptación**

- [x] Implementación del microservicio con los endpoints para cada colección y las pruebas del correcto funcionamiento.

**Requerimientos**

- Completar los ajustes del modelo de datos en la Issue #97.

**Especificaciones técnicas**
1. Repositorio microservicio crud [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
Se realizó la investigación de la documentación de Nest.js para entender el funcionamiento del framework. También se revisaron los diferentes lineamientos con el fin de abordar el desarrollo del microservicio.

#### Iniciando la creación del microservicio `plantillas_formularios_dinamicos`

Se crea el nuevo microservicio con Nest.js

![image](https://github.com/user-attachments/assets/01ea066e-2c57-4ee0-a0df-e6005719cd99)

Hubo problemas con de compatibilidad de las ultimas versiones de Nest.js y node, así que se utilizaron versiones anteriores de ambos

![image](https://github.com/user-attachments/assets/326ebf8f-5b01-494f-bc85-ad90f285ca43)

![image](https://github.com/user-attachments/assets/e273fd5d-4aa9-4d0b-b98d-4e8adfdf9b43)

**Comment by edwargl7** [comment]
Se actualiza la url del repositorio https://github.com/udistrital/plantillas_formularios_dinamicos_crud.

**Comment by CristianCGutierrezG** [comment]
Se organiza la estructura del microservicio con base a los lineamientos de NestJS

![image](https://github.com/user-attachments/assets/583a400c-27c3-47ea-87d6-c204871dbcd4)

también se agregan y se modifican los archivos con las configuraciones iniciales

![image](https://github.com/user-attachments/assets/c399685c-152f-43d8-8855-9ce3d10ba033)

![image](https://github.com/user-attachments/assets/78869e6c-2387-4ada-aa57-b732affc1152)

se crea una imagen para mongo con Docker 
![image](https://github.com/user-attachments/assets/640da4bb-c50e-4f89-b46c-756af1aad0e0)

**Comment by edwargl7** [comment]
Puede servir de ejemplo para los getAll este que cuenta con la documentación de los query params en el Swagger [Planes v1](
https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Planes&version=v1&provider=admin&tenant=carbon.super#!/plan/PlanController_getAll), repositorio [planes_crud](https://github.com/udistrital/planes_crud) y los filtros se desarrollaron en [filters](https://github.com/udistrital/planes_crud/blob/develop/src/filters/filters.service.ts).

**Comment by CristianCGutierrezG** [comment]
Se realiza la conexión exitosa con la base de datos y se realiza el desarrollo de la coleccion modulos de acuerdo a los lineamientos

Se presentaron inconvenientes con la organización de los módulos, por el momento se tiene la coleccion de modulo con todos sus archivos en una única carpeta

![image](https://github.com/user-attachments/assets/4c80eab7-2553-45c9-a90d-87b55113975f)

Documentación en swagger de modulo

![image](https://github.com/user-attachments/assets/28d0a6b1-d962-48a3-bd4c-19b16c668cd5)

La documentación cuenta con las  diferentes configuraciones de los filtros

![image](https://github.com/user-attachments/assets/34932b97-0bdd-47dd-bff2-10e011184e2c)

**Comment by CristianCGutierrezG** [comment]
## pruebas a CRUD modulo

### Post
![image](https://github.com/user-attachments/assets/e65ab18a-014d-4c4e-bccf-86379d8b537f)

### Get
![image](https://github.com/user-attachments/assets/17885e1f-920b-469f-a4c1-ceac566ff813)

### Get one
![image](https://github.com/user-attachments/assets/75842a43-f3b6-4234-abe4-467d0c66049e)

### Update
![image](https://github.com/user-attachments/assets/c474b6cf-6a63-4814-bc76-a1b26ba7d434)

### Delete
![image](https://github.com/user-attachments/assets/de73322b-3bda-41cd-8005-e5065da48529)

Confirmación de la eliminación logica
![image](https://github.com/user-attachments/assets/c821954e-4d75-44e2-a444-bf39f2264957)

**Comment by CristianCGutierrezG** [comment]
Se ajusta modelo de datos para cambiar datos << nn >> 
![_Modelo de datos - formularios dinámicos-versión 7 drawio](https://github.com/user-attachments/assets/c4dc7b9b-f75c-4060-898a-777f8e34ba56)

Se sube la nueva versión del diagrama

[Modelo de datos - formularios dinámicos V7](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZnzquMgMbpKvmqmkFOrEEQBKIyg2RKW6LuoX3lbCYmUBw?e=pvJ2Oe)

**Comment by CristianCGutierrezG** [comment]
Lista de endpoints con swagger

![image](https://github.com/user-attachments/assets/b73c516e-aa32-446c-ac7f-dd9a23a83c3d)

![image](https://github.com/user-attachments/assets/d9862d1c-a1ce-4548-8823-5cfb745ec8cc)

![image](https://github.com/user-attachments/assets/d42e7450-c8ff-4142-9c89-9ab0d9f9bd02)

![image](https://github.com/user-attachments/assets/a9a52f1a-c5fa-4e90-9ef0-8700e952ba88)

![image](https://github.com/user-attachments/assets/28b129d0-6b48-4849-9906-7b34cd411a81)

![image](https://github.com/user-attachments/assets/ab19511e-7115-421f-b147-b2baae3444f1)

**Comment by CristianCGutierrezG** [comment]
## pruebas a CRUD formularios

### Post
![image](https://github.com/user-attachments/assets/ff0d2ac5-8b63-4053-9775-7d37d021260b)

### Get
Prueba con el Query `populate` para traer la información del modulo asociado 
![image](https://github.com/user-attachments/assets/63754d96-8a57-445d-99d9-328ea2eec98e)

### Get one
![image](https://github.com/user-attachments/assets/b47684a9-c4a9-4372-a1b0-c26f25e06d51)

### Update
![image](https://github.com/user-attachments/assets/d03e6a8f-08c7-4fdb-9e6d-5d6bf16971ce)

###  Delete
![image](https://github.com/user-attachments/assets/ff9271cc-0daa-442d-b99c-1c1769143cc3)

Confirmación de la eliminación lógica
![image](https://github.com/user-attachments/assets/6af3954c-e649-45a9-a9e4-9e4f30902ab6)

**Comment by CristianCGutierrezG** [comment]
## pruebas a CRUD modal-alertas

### Post
![image](https://github.com/user-attachments/assets/1b0097fb-ce21-49f8-b2af-897b2579eb0f)
### Get
![image](https://github.com/user-attachments/assets/63754d96-8a57-445d-99d9-328ea2eec98e)

### Get one
![image](https://github.com/user-attachments/assets/b47684a9-c4a9-4372-a1b0-c26f25e06d51)

### Update
![image](https://github.com/user-attachments/assets/d03e6a8f-08c7-4fdb-9e6d-5d6bf16971ce)

###  Delete
![image](https://github.com/user-attachments/assets/ff9271cc-0daa-442d-b99c-1c1769143cc3)

Confirmación de la eliminación lógica
![image](https://github.com/user-attachments/assets/6af3954c-e649-45a9-a9e4-9e4f30902ab6)

**Comment by CristianCGutierrezG** [comment]
## pruebas a CRUD modal-alertas

### Post
![image](https://github.com/user-attachments/assets/3fca0c5e-3dc9-4d3d-a86b-ae9f87794148)

### Get
Prueba con el Query populate para traer la información del formulario_id y el padre_id asociado
![image](https://github.com/user-attachments/assets/2077d3ae-ad97-40ca-9682-7968aecb5cec)

### Get one
![image](https://github.com/user-attachments/assets/c16e8395-6ee2-4dc6-828c-010ec93c09a2)

### Update
![image](https://github.com/user-attachments/assets/fffcc467-cbcc-4a58-8f5b-1cc196577799)

###  Delete
![image](https://github.com/user-attachments/assets/204f98c5-0059-4644-8ac8-26bb63e1fea8)

Confirmación de la eliminación lógica
![image](https://github.com/user-attachments/assets/c19219a8-cc89-4ce3-bcfd-160dd431edfa)

**Comment by CristianCGutierrezG** [comment]
## pruebas a CRUD elementos-html

### Post
![image](https://github.com/user-attachments/assets/6d1edbb2-6913-4c99-bdfb-922782e35567)

### Get
![image](https://github.com/user-attachments/assets/7ec3755e-e588-439e-9c8b-7ca80e1ad6a3)

### Get one
![image](https://github.com/user-attachments/assets/76bd7e48-5783-49e9-ad92-b0cb24e3f92c)

### Update
![image](https://github.com/user-attachments/assets/9b1d592d-1620-475a-8fde-ffbac9bee0d8)

###  Delete
![image](https://github.com/user-attachments/assets/d283cd0e-9ebe-48fd-8270-63cb5eacdf6b)

Confirmación de la eliminación lógica
![image](https://github.com/user-attachments/assets/f034ce95-4bef-4c0f-bf9b-e291eb35194e)

**Comment by CristianCGutierrezG** [comment]
## pruebas a CRUD elementos-personalizados

### Post
![image](https://github.com/user-attachments/assets/63e0265a-cddc-4e41-a2b5-2c206194331d)

### Get
![image](https://github.com/user-attachments/assets/393d2a27-d2a9-4256-8023-ad247bba0fe3)

### Get one
![image](https://github.com/user-attachments/assets/74723dfb-5531-4643-be92-c558ccc4431e)

### Update
![image](https://github.com/user-attachments/assets/ae024759-1a76-4ed5-846d-863bc1b9a773)

###  Delete
![image](https://github.com/user-attachments/assets/c4180fc8-da71-453e-98fe-dddb7ea26c43)

Confirmación de la eliminación lógica
![image](https://github.com/user-attachments/assets/0d42cfb8-c4f4-47ab-a696-9cd15a6c1bd5)

**Comment by edwargl7** [comment]
Completado el desarrollo requerido para esta Issue, cuenta con un muy buen desarrollo y documentación de la Issue, cubre las pruebas funcionales y los lineamientos que se aplican a este desarrollo. Muy buen trabajo.
Revisar los nombres de las variables de entorno para darles un nombre más claro.
