### ISSUE TITLE
Diagrama de arquitectura formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#94]
Se requiere realizar el modelo de arquitectura basado en el enfoque planteado con el microcliente que renderiza el formulario plantilla y el microservicio que almacena las plantillas. Tomando de base el modelo de arquitectura descriptiva:
![image](https://github.com/user-attachments/assets/c8ab2bb3-1d5c-4a25-87fa-5e73d5c00089)
 

**Sub Tareas**

- [x] Creación de diagrama de arquitectura con la vista de microcliente y microservicio de plantillas.

**Criterios de aceptación**

- [x] Diagrama cargado en la carpeta de documentación de Sísifo - Investigación formularios dinámicos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Ejemplo de diagrama requerido: 
![Diagrama técnico SGA Version 2 (1)](https://github.com/user-attachments/assets/89f43947-0d75-4e2f-afe1-32987deb8f44)

Se debe crear el diagrama de arquitectura, mencionando las tecnologías a usar en el microcliente y el microservicio.

**Comment by CristianCGutierrezG** [comment]
Se comienza con la creación del diagrama técnico para el sistema de formularios dinámicos

![diagrama técnico formularios dimamicos drawio](https://github.com/user-attachments/assets/812b3960-10c7-4efb-a554-cc62d335b223)

**Comment by CristianCGutierrezG** [comment]
Se agregan los últimos detalles al diagrama

![diagrama técnico formularios dimamicos drawio (1)](https://github.com/user-attachments/assets/3898ed73-c980-4967-a879-cf6376a1704d)

Se guarda en la carpeta de documentación de Sísifo - Investigación formularios dinámicos

[diagrama técnico formularios dinámicos](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EaiqeL0HxiVGrOV7qZSSTtkBM_jwanpIVKMGCDJOtJhZbw?e=cLK1qO)

**Comment by edwargl7** [comment]
Revisado, cumple con lo requerido. Una vez definida la tecnología a utilizar para el microservicio se realizará la actualización del diagrama, al igual que al tener definida la base de datos y detalles descritos en la tabla de la izquierda. Buen trabajo.
