### ISSUE TITLE
Modelo de datos módulo de Auditoría - Campos aprobación - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#96]
Se requiere realizar el ajuste al modelo de datos diseñado en la Issue #58. Los ajustes requeridos son los siguientes:
- Se recomienda para los campos que almacenan la relación con otra tabla o sistema el uso de _id al final del nombre del campo.
![image](https://github.com/user-attachments/assets/11f57035-6f84-4ba2-9826-a97f5cef985b)
Aplicarlos en los sigueintes campos:
>- estado -> estado_id
>- tipo_evaluacion -> tipo_evaluacion_id
- Agregar en la colección de información los campos de id del usuario que realiza la aprobación como jefe y secretario técnico.
- En la colección de información manejar la vigencia como relación paramétrico con parametros_crud.
- En la colección de actividad manejar fecha_inicio y fecha_fin con relación paramétrica y estos valores ser almacenados en parametros_crud.

**Sub Tareas**

- [x] Migración a modelo de datos no relacional que soporte la posibilidad de cambios en el formulario de formulación de plan anual de auditoría.
- [x] Actualización de campos con referencia a otras colecciones o sistemas.
- [x] Ajustes en la colección de _informacion_ con los ajustes de los nuevos campos para almacenar el id del usuario que realiza la aprobación y cambio de vigencia a campo paramétrico.
- [x] Ajuste colección de _actividad_ para manejo de fechas como paramétrico.
- [x] Revisión y planteamiento inicial microservicio mid para estructuración dinámica de los datos del microcliente de formularios dinámicos.

**Criterios de aceptación**

- [x] Modelo de datos actualizado. 

**Requerimientos**

No aplica

**Lineamientos Modelos de datos**
1. Lineamientos [modelos de datos relacional](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md)
2. Lineamientos [Modelos de Datos en Mongo](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/lineamientos_mongo.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
## Modelo de Datos Actualizado

Se realizaron los cambios recomendados al modelo de datos, y se adaptaron los tipos de datos para ajustarlos a un modelo no relacional.

![_plan_anual_de_auditoría_V1-version2 drawio](https://github.com/user-attachments/assets/6e5c69d1-18a6-499e-8259-35bd3000e235)

**Comment by CristianCGutierrezG** [comment]
Nueva version del modelo de datos [plan_anual_de_auditoría_V2](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Ef3HlWtWWB9Hp6oarEU3qzkBYWIV1kTih0ULWB4ZAm4xPA?e=W70Vl9)

**Comment by CristianCGutierrezG** [comment]
### Propuesta de Estructuras para el Microservicio MID de Formularios Dinámicos

Se plantean dos posibles estructuras para el desarrollo del microservicio MID destinado a la estructuración dinámica de los datos que manejará el microcliente de formularios dinámicos.

1. **MID para Plantillas y Almacenamiento de Datos**: 
    - En esta estructura, el MID recibiría y estructuraría los datos provenientes de las plantillas para formularios dinámicos (`Plantillas_crud`) y del microservicio encargado de almacenar los datos (`datos_crud`). 
    - Este enfoque permitiría llevar un registro detallado de los datos que corresponden a cada plantilla y la versión de la misma de forma directa. El MID actuaría como un intermediario, facilitando la relación entre las plantillas y los datos almacenados.

![_plan_anual_de_auditoría_V1-versión 7 drawio (1)](https://github.com/user-attachments/assets/171bef6f-796d-41e1-a517-0885d3957a4d)

2. **Recepción Directa de Plantillas**:
    - En esta alternativa, el microservicio recibiría las plantillas directamente y se conectaría con un MID encargado de estructurar los datos para su almacenamiento en el microservicio. 
    - Este enfoque simplificaría la arquitectura, permitiendo al microservicio gestionar directamente las plantillas mientras delega la estructuración de datos al MID.

![_plan_anual_de_auditoría_V1-versión 7 drawio](https://github.com/user-attachments/assets/e864bd8a-a8da-498f-b784-28108f23bc2b)

Se realizó una reunión con @alexhrr , donde se explicó en detalle el funcionamiento del `plantillas_crud` y los objetivos del microservicio de estructuración de datos. Durante la discusión, también se abordó el funcionamiento del servicio de autenticación MID. Aunque  el plantemaineto se puede dar de manera similar, es importante destacar que dicho servicio está construido sobre bases de datos SQL, mientras que la estructuración dinámica en este caso se requiere sobre MongoDB asi que se necesita de mas investigacion del dinamismo en las colecciones de las bases de datos no SQL.

Por el momento, no se contemplo la implementación de una arquitectura tipo "Pizarra" debido a su complejidad y a que podría no ser la alternativa más adecuada para compartir los datos en este contexto específico.

**Comment by edwargl7** [comment]
Buen diseño del modelo de datos, sin embargo para mayor facilidad de cambios podemos no dejar restricciones de campos obligatorios a nivel de modelo de datos. Se puede abordar otro enfoque en el modelo de datos donde un campo sea información y dentro de el un objeto que en este momento almacenaría objetivo, criterios, ... y que le permita más adelante tener una estructura manejable más fácil en el almacenado y recuperación de datos.

**Comment by edwargl7** [comment]
La primera alternativa podría ser la mejor alternativa dado que permitiría mantener un mismo flujo de cara al microcliente sin importar si es un formulario nuevo o si es un formulario en modo de edición o visualización. Además, podría soportar la alternativa que se tiene contemplada para almacenar en la plantilla el mapeo de cada valor al campo respectivo de la base de datos, permitiendo agregar metadata que permita identificar servicio, endpoint, tabla/colección y campo.
