### ISSUE TITLE
Ajustes modelo de datos plantillas de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#97]
Se requiere realizar los siguientes ajustes al modelo de datos de plantillas de formularios dinámicos abordados en la Issue #90:
- Campo tipo de modal_alerta cambiar a tipo numérico almacenando la relación con parametros_crud.
- Campos tipo y tipo_dato de elementos_html cambiarlos a tipo numérico almacenando la relación con parametros_crud.
- Agregar campo label a _formularios_ y _seccion_ para control separado a nivel de código vs interfaz gráfica.
- Definición de las dependencias entre elementos_html como un campo de tipo objeto opcional que permita tener una estructura ajustable para un mejor manejo según el tipo de dependencia del elemento.
![image](https://github.com/user-attachments/assets/6d946b7e-ee1e-41d7-969b-418fa23719ae)

**Sub Tareas**

- [x] Ajuste modelo de datos con los campos mencionados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
![image](https://github.com/user-attachments/assets/7fc68a4c-9b03-4abf-a63d-d035a7567336)
![image](https://github.com/user-attachments/assets/91c92240-8811-459e-b146-63171dcabfce)
![image](https://github.com/user-attachments/assets/d51e779b-69ea-45eb-88ef-c9c2425ca809)
![image](https://github.com/user-attachments/assets/9afafd48-f4fa-4027-b025-231c9a5897f7)

**Comment by jucastro94** [comment]
se carga version 6 del modelo de datos a la carpeta
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYXhmfF7bFVOlYLqKq6IVeMBtRSoZLc_TBoNEwP9a34MWg?e=4uDt4K

**Comment by jucastro94** [comment]
se realizan los ajustes mencionados 

![Image](https://github.com/user-attachments/assets/a05b077d-7ad6-442d-b0e0-47358ca6e011)

 se carga version 6 ajustada en carpeta
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZTxOxJkIA5Htn-k01CF-gIB6cG421Rdhb7R2bxGjDTnDg?e=dxiZgX

**Comment by jucastro94** [comment]
![Image](https://github.com/user-attachments/assets/12b5b6f9-f344-47b1-8f0c-c754e6e3ecb3)

**Comment by edwargl7** [comment]
Se realiza la revisión, se encuentra actualizado correctamente y cargado en la correspondiente carpeta. Buen trabajo.
