### ISSUE TITLE
Implementación versionado de plantillas de formularios dinámicos

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#98]
Se requiere realizar la implementación del versionado de plantillas de formularios dinámicos en el microservicio de plantillas de formularios dinámicos. Este versionado debe contemplar las colecciones de formulario, sección y elemento personalizado.

**Sub Tareas**

- [x] Implementación de lógica de versionado de formularios.

**Escenarios de pruebas**
- [x] Pruebas funcionales creando una nueva versión de una plantilla de formulario dinámico básico.

**Criterios de aceptación**

- [x] Implementación y prueba funcional del versionado de plantillas de formularios dinámicos.

**Requerimientos**

No aplica

**Especificaciones técnicas**
1. Repositorio microservicio crud [plantillas_formularios_dinamicos](https://github.com/udistrital/plantillas_formularios_dinamicos_crud)

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Lineamientos Microservicios**
1. Definición de endpoints para APIs REST [Hoja resumen de buenas prácticas](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/EYwQbkAKVCJCqrmJ7NgnjQ4B8WSd81vxGVx-hqi0WBAcfQ?e=lJZdx8) y [Aclaración y ejemplos de nombres adecuados para endpoints](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/lineamientos-endpoints.md)
2. Guiarse en la construcción del microservicio basado en los lineamientos de [APIS Beego](https://github.com/udistrital/lineamientos_oas?tab=readme-ov-file#5-apis-beego-mortar_board) si se usa Golang
3. Guiarse de los lineamientos de [ambientes dockerizados](https://github.com/udistrital/lineamientos_oas/blob/master/ambientes_dockerizados/dockerizacion.md)
4. [(health check) validación de estado en APIs](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/endpoint_validacions.md#health-check-validaci%C3%B3n-de-estado-en-apis)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by CristianCGutierrezG** [comment]
### Planteamiento del Versionamiento

Se realizó un análisis y planteamiento de posibles formas en las que se realizará la creación y almacenamiento de los datos de la plantilla de un formulario.

#### Casos de uso

1. Especificar toda la creación de la plantilla (formulario, secciones y elementos), relacionando toda la petición del usuario a una sola creación del formulario.

2. Crear una nueva versión por cada cambio que haga el usuario, incluyendo la creación de una sección o un elemento.

De estos posibles casos de uso surgieron opciones para plantear el versionamiento del formulario:

**Opción 1:** Crear nuevos documentos (clonar) con todos los elementos de un formulario cuando haya algún cambio. Cada vez que se crea un formulario hay que crear un nuevo documento para cada elemento y sección, para relacionarlos con el nuevo documento formulario.

**Opción 2:** Actualizar el ID de la sección o elemento con el nuevo formulario cada vez que haya una nueva versión (se pierde la información del formulario anterior).

### Versionamiento que se utilizará

Después del planteamiento, se realizó una reunión con @edwargl7 en la que se dieron explicaciones y se aclaró el tipo de versionado a realizarse.

Similara al caso 1, Se especificará una única plantilla en forma de JSON con toda la información para construir el formulario. Con base en ello, se crearán dos nuevos endpoints que realizarán el proceso de almacenamiento por colecciones y versionamiento de la plantilla.

#### Proceso de Versionamiento, Endpoint de tipo POST

- **Recibe:** Como body, un JSON que define la estructura a almacenar.
- **Devuelve:** La confirmación de la creación de la plantilla.

**Pasos a seguir:**
1. Creación de la función contar registros del módulo. Si el módulo relacionado al formulario ya cuenta con una plantilla, se crea una nueva versión con la información del nuevo JSON; si no cuenta con plantilla, será la primera versión.
2. Coger la información del JSON y crear el registro en formulario, almacenando el ID.
3. Iterar y crear las secciones con base en la información del JSON, definiendo los padres e hijos.
4. Crear elementos personalizados según la sección que corresponda. Implementar función de validación de que el `elemento_html` al cual se relaciona el elemento personalizado exista en la base de datos.

#### Proceso de Consulta, Endpoint tipo GET

- **Recibe:** Como parámetro, el número de versión del formulario requerida, junto con el ID del módulo al que pertenece.
- **Devuelve:** Un JSON, plantilla para la creación del formulario.

**Pasos a seguir:**
1. Obtener la información de la jerarquía de la plantilla: Módulo, formulario, sección y elementos_personalizados.
2. Generar el JSON con la estructura de la plantilla.

**Comment by CristianCGutierrezG** [comment]
## Creación del Endpoint `plantillas`

El nuevo endpoint de tipo POST se encarga de recibir un JSON con la plantilla para la creación de los formularios y almacena la información en cada colección específica (`Formulario`, `Seccion`, `ElementoPersonalizado`).

- **Recibe:** Como body, un JSON que define la estructura a almacenar.
- **Devuelve:** La confirmación de la creación de la plantilla.

![image](https://github.com/user-attachments/assets/e69f9f6f-8cdf-450c-9117-a16b49265dbc)

#### Funciones del servicio
1. Encuentra el módulo relacionado al formulario por su nombre.
2. Actualiza el número de versión y cambia el valor `version_actual` a `false` de las versiones anteriores del formulario.
3. Crea un nuevo documento formulario, revisando si el módulo relacionado existe.
4. Crea los nuevos documentos de secciones especificadas en la plantilla y guarda la relación del padre si es necesario.
5. Crea los nuevos documentos de elementos personalizados relacionados con las secciones y verifica si el `elemento_html_id` relacionado existe.

#### Prueba del Endpoint

Para realizar la prueba, se crearon algunos documentos en las colecciones `modulos` y `elementos_html`, ya que se requiere que existan de antemano para hacer las relaciones con los elementos del formulario.

![image](https://github.com/user-attachments/assets/d53f6c46-990e-47a8-bc77-4b14ff0a1596)
![image](https://github.com/user-attachments/assets/6e07b2d6-1f89-4471-ab07-6970ff5a6ed9)

Se actualiza el ejemplo de la plantilla base para la creación de un formulario.

```json
{
  "modulo_nombre": "Prueba",
  "formulario": {
      "nombre": "Creacion de espacios academicos 2",
      "descripcion": "---",
      "creado_por_id": 3,
      "traduccion": "true",
      "label": "Form1",
      "seccion": [
          {
              "nombre": "Seleccionar proyecto curricular",
              "label": {
                 "nombreIngles": "Select curriculum project"
              }
          },
          {
              "nombre": "Información sobre el Espacio Académico",
              "elemento_personalizado": [
                  {
                      "nombre": "Nombre",
                      "descripcion": "---",
                      "elemento_html_id": "66a9ab3b3741be5e64dd31e3",
                      "label": {
                        "nombre": "Nombre"
                      },
                      "deshabilitado": false,
                      "solo_lectura": false,
                      "requerido": true
                  },
                  {
                    "nombre": "codigo",
                    "elemento_html_id": "66a9ab823741be5e64dd31e5",
                    "label": {
                        "nombre": "codigo"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "requerido": true
                }
              ],
              "seccion": [
                  {
                      "nombre": "Asignar horas de trabajo",
                      "elemento_personalizado": [
                          {
                              "nombre": "HTD",
                              "elemento_html_id": "66a9ab823741be5e64dd31e5",
                              "label": {
                              "nombre": "codigo"
                              },
                              "deshabilitado": false,
                              "solo_lectura": false,
                              "requerido": true,
                              "validadores_personalizados": [
                                  {
                                      "nombre": "min",
                                      "params": {
                                          "min": 18
                                      }
                                  },
                                  {
                                      "nombre": "max",
                                      "params": {
                                          "max": 65
                                      }
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }
      ]
  }
}
```
**POST**

![image](https://github.com/user-attachments/assets/03cf3156-e285-4849-bd28-e0e23abd54e1)


**Confirmación de creación en la base de datos**

- **Formularios**
![image](https://github.com/user-attachments/assets/4657acc7-8208-4f0a-b042-03ffd6422363)


- **Secciones**
![image](https://github.com/user-attachments/assets/ff4b0467-8dcb-4116-b170-8d2c33e0f8f6)

- **ElementoPersonalizados**
![image](https://github.com/user-attachments/assets/205d0b85-5412-4531-87e2-2e2a44b3f865)

**Comment by edwargl7** [comment]
Muy buen trabajo, revisar por favor los campos de formulario que conserven el tipo de dato que se maneja en el modelo de dato (boolean y Object respectivamente).

```
"traduccion": "true",
 "label": "Form1",
```

**Comment by CristianCGutierrezG** [comment]
## Cambios y Correcciones

### Ejemplo de la Plantilla para la Creación de un Formulario

Se corrigieron los valores de `traduccion` y `label` para el formulario.

```json
{
  "modulo_id": "66a954c541c7887e90984a3c",
  "formulario": {
      "nombre": "Creacion de espacios academicos 2",
      "descripcion": "---",
      "creado_por_id": 3,
      "traduccion": true,
      "label": {
        "nombre": "Creacion de espacios academicos"
      },
      "seccion": [
          {
              "nombre": "Seleccionar proyecto curricular",
              "label": {
                 "nombreIngles": "Select curriculum project"
              }
          },
          {
              "nombre": "Información sobre el Espacio Académico",
              "elemento_personalizado": [
                  {
                      "nombre": "Nombre",
                      "descripcion": "---",
                      "elemento_html_id": "66a9ab3b3741be5e64dd31e3",
                      "label": {
                        "nombre": "Nombre"
                      },
                      "deshabilitado": false,
                      "solo_lectura": false,
                      "requerido": true
                  },
                  {
                    "nombre": "codigo",
                    "elemento_html_id": "66a9ab823741be5e64dd31e5",
                    "label": {
                        "nombre": "codigo"
                    },
                    "deshabilitado": false,
                    "solo_lectura": false,
                    "requerido": true
                }
              ],
              "seccion": [
                  {
                      "nombre": "Asignar horas de trabajo",
                      "elemento_personalizado": [
                          {
                              "nombre": "HTD",
                              "elemento_html_id": "66a9ab823741be5e64dd31e5",
                              "label": {
                              "nombre": "codigo"
                              },
                              "deshabilitado": false,
                              "solo_lectura": false,
                              "requerido": true,
                              "validadores_personalizados": [
                                  {
                                      "nombre": "min",
                                      "params": {
                                          "min": 18
                                      }
                                  },
                                  {
                                      "nombre": "max",
                                      "params": {
                                          "max": 65
                                      }
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }
      ]
  }
}
```
### Endpoint de Plantilla POST
Se realiza el cambio para que la plantilla busque la información por modulo_id. También se actualiza la salida de la respuesta en el endpoint con base en los lineamientos.

![image](https://github.com/user-attachments/assets/b58e9c42-b696-422f-bcf4-b763c20b2ca8)

### Variables de Entorno
Se realiza el cambio en el nombre de las variables de entorno.

![image](https://github.com/user-attachments/assets/d9f7970b-37e1-42fa-b303-cf3969150614)

![image](https://github.com/user-attachments/assets/29388884-5f38-47b5-95b9-6ebbbced3d07)

**Comment by CristianCGutierrezG** [comment]
## Creación del Endpoint `plantillas GET`

El nuevo endpoint de tipo GET se encarga de retornar una plantilla en forma de JSON con toda la información necesaria para la construcción de un formulario. 

- **Recibe:** Como query, el `modulo_id` y la versión del formulario a buscar. Si no se especifica una versión, se devuelve la versión actual.
- **Devuelve:** JSON con la estructura del formulario.

![image](https://github.com/user-attachments/assets/8b048b76-9c88-425b-a5cf-39c045a05952)

#### Funciones del Servicio
1. Obtener el formulario basado en el módulo y la versión.
2. Obtener las secciones del formulario, incluyendo las relaciones `padre_id`.
3. Obtener los elementos personalizados de cada sección, con `populate` de `elemento_html_id`.
4. Construir la estructura jerárquica del formulario.

### Prueba del Endpoint

**GET Version actual**

![image](https://github.com/user-attachments/assets/b38048d6-4d6b-4ce4-8b1a-4884f93c86c9)

![image](https://github.com/user-attachments/assets/d58eb88a-c2f8-442a-8b19-c644c948640b)

Confirmación en la base de datos ultima version

![image](https://github.com/user-attachments/assets/a63b1eb9-77fc-47e6-bb2b-42ee176e9171)


**GET otra version**

![image](https://github.com/user-attachments/assets/84f85b0c-c27b-43fa-89f6-0da18673983b)

Confirmación en la base de datos version 4

![image](https://github.com/user-attachments/assets/afd1391d-c347-4ddd-84e8-a0e8db6ffc9f)

**Comment by edwargl7** [comment]
Revisión para manejo de tipos de ObjectId o UUID https://github.com/udistrital/prueba_piloto_funciones_lambda/blame/feature/issues-161-multiples-planes-proyectos/src/handlers/crud_syllabus/app.py

**Comment by CristianCGutierrezG** [comment]
### Adecuación del `filter.service` para Búsqueda de IDs

Se ha realizado una actualización en el servicio `filter.service` para mejorar la búsqueda de IDs en los queries de los endpoints `GetAll`. Ahora el servicio manejará IDs en las consultas tanto en formato `string` como en formato `ObjectID`.

![image](https://github.com/user-attachments/assets/16848ad8-0878-4f6f-8b07-8022549ea4c7)

**Comment by edwargl7** [comment]
Agregar por favor los ids de formulario, sección y elemento personalizado. El resto de la implementación se observa completo frente a la revisión preliminar. Posteriormente, se realizará la revisión detallada del desarrollo.

**Comment by CristianCGutierrezG** [comment]
#### Actualizaciones Realizadas
**Agregados `_id` a Elementos de la Plantilla:**
 
Se añadieron identificadores `_id` a todos los elementos devueltos en la estructura de la plantilla del endpoint `plantillas GET`

![image](https://github.com/user-attachments/assets/f70a2161-44ea-4d37-9aff-4134208fadc0)

**Comment by edwargl7** [comment]
Muy buen trabajo, se completan los ajustes requeridos y se resuelve el PR.
