### ISSUE TITLE
Integración microservicio de histórico y microcliente de gestión de usuarios - Parte 2

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#99]
Se requiere completar la integración del microservicio [historico_usuarios_roles_crud](https://github.com/udistrital/historico_usuarios_roles_crud) con el microcliente de [auditoria_plan_mejoramiento_usuario_mf](https://github.com/udistrital/auditoria_plan_mejoramiento_usuario_mf), dado que ya se cuenta con la integración de WSO2 y terceros requerida para completar el almacenamiento del registro de un usuario.

**Sub Tareas**

- [x] Implementación de la integración con el microservicio histórico usuarios roles para el correcto registro de un nuevo usuario, tener presente que se adicionó un nuevo campo _finalizado_ el cual al momento de registrarse debe ser enviado como falso.
- :boom: Implementación con WSO2 para agregar roles a un usuario en WSO2.
- [x] Pruebas funcionales del registro de un nuevo usuario en el microservicio histórico usuarios.
- :boom: Pruebas funcionales donde se observe que se agregó correctamente el rol al usuario en WSO2.

**Escenarios de pruebas**
- [x] Creación de un nuevo usuario en histórico usuarios roles, asignando el rol de auditor.
- :boom: Validación de la correcta asignación del rol al usuario existente en WSO2.

**Criterios de aceptación**

- :boom: Documentación de las pruebas realizadas con la integración en el registro de un nuevo usuario. 

**Requerimientos**

No aplica

**Lineamientos Generales**
Lineamientos que se deben cumplir en cualquier desarrollo.
1. [Lineamiento y Metodología para Branches](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
2. [Etiquetas en comentarios de Commits](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/etiqueta_commits.md)
3. Seguir los lineamientos para la documentación del README [Contenido README](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by alexhrr** [comment]
Se inicia con la integración del microservicio de histórico_usuarios_roles_crud haciendo uso de la nueva rama para su implementación y al ejecutar el microcliente se ve afectada la interfaz:

![Captura de pantalla 2024-07-24 a la(s) 9 42 41 p  m](https://github.com/user-attachments/assets/95b04c94-6887-4ea8-85de-d3b71708becf)

Se actualiza la base de datos con el nuevo campo:

![Captura de pantalla 2024-07-24 a la(s) 9 49 36 p  m](https://github.com/user-attachments/assets/0eceb286-b66d-4b51-a411-25ac1a024605)

El día de mañana se realizara una sesión de aclaración de dudas con el lider para revisar la integración del microservicio.

**Comment by alexhrr** [comment]
### Avance integración histórico_usuarios_roles

Se Realiza la integración del microservicio histórico_usuarios_roles para la creación de un usuario según lo solicitado, en el microcliente se realiza la consulta del usuario a crear y se selecciona un rol para asignarlo al usuario, tambien se selecciona la fecha de inicio y finalización del rol asignado, al dar click en guardar se realiza la creación del usuario:

![Captura de pantalla 2024-07-25 a la(s) 9 56 20 p  m](https://github.com/user-attachments/assets/dd82c265-1105-4f13-8878-d3f0c19db6a4)

Inicialmente se crea el usuario con su documento de identidad en la tabla "usuario":

![Captura de pantalla 2024-07-25 a la(s) 9 57 29 p  m](https://github.com/user-attachments/assets/ba40919f-6a8d-413c-84f8-6876e42c6038)

Posteriormente se crea el Rol en la tabla periodo_rol_usuario teniendo en cuenta las fechas y el rol seleccionado, asignando por defecto **false** al campo **finalizado**:

![Captura de pantalla 2024-07-25 a la(s) 9 59 21 p  m](https://github.com/user-attachments/assets/a008dea1-f511-47b4-aee7-723c7a192474)

Para el caso anterior se asigna el rol Administrador que tiene el id = 1: 

![Captura de pantalla 2024-07-25 a la(s) 9 58 19 p  m](https://github.com/user-attachments/assets/e941beb9-82b6-4ab0-bcba-929bf35fc656)

Se debe continuar con la implementación con WSO2 para agregar roles al usuario en WSO2.

**Comment by edwargl7** [comment]
Se realiza la revisión junto con @alexhrr sobre el error reportado, se consulta al arquitecto y se valida que la configuración es correcta en el microservicio de autenticacion_mid y que si es posible ejecutarla directamente. Luego de continuar la revisión y consultar directamente en el API store se observa el mismo error.
![image](https://github.com/user-attachments/assets/d551cd5c-e009-43ed-919c-a37c3439be09)
El cual es requerido para completar la integración de agregar rol a un usuario.

**Comment by alexhrr** [comment]
Al continuar con la integración de la adición y eliminación de roles con WSO2 se encuentra el siguiente error al momento de agregar/eliminar roles, lo que impide continuar con la integración, se realiza la revision junto al lider y se consulta el API store para validar si el error continua y efectivamente se encuentra el error.
 
![image](https://github.com/user-attachments/assets/73dd8af9-6ebf-4ae5-9d81-7a8cce39b621)

**Comment by edwargl7** [comment]
Se finaliza esta Issue, dadas las dependencias que surgieron se abordará en el siguiente sprint completar el desarrollo y pruebas.
